### ISSUE TITLE
Feature Request: Delay sync by seconds (Synchronization Delay)

### ISSUE THREAD

**Issue by q2apro** [nextcloud/desktop#6366] opened 2024-01-20 10:36 UTC
When you work with big files, e.g. Photoshop files of 100 MB, you usually save your work every 30 seconds or so.

With each save Nextcloud starts to synchronize the file.

So after 30 min work, I got an unnecessary used bandwidth of 6 GB.

Or if you sync the user data of your browser, there is a constant sync running.

Also discussed over at Owncloud github [since 2016](https://github.com/owncloud/client/issues/3935
). A simple feature, IMHO, which would set Nextcloud apart.

⚠️ **An option to delay sync in the desktop client is a MUST (!)**

    

### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you want to have the same feature implemented.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Feature description
- Go to Nextcloud General Settings.
- Find option "Delay sync by seconds: [ __ ]"
- Fill in (e.g. 180), save.
- Result: Sync takes place only every 180 seconds.

**Comment by joshtrichards** [comment] 2024-01-20 17:09
Duplicate of #6203

**Closed by joshtrichards** 2024-01-20 17:09 UTC
Labels: enhancement
