### ISSUE TITLE
TLS handshake failed — cannot login from MacOS desktop client

### ISSUE THREAD

**Issue by xplosionmind** [nextcloud/desktop#4043] opened 2021-12-07 08:24 UTC
### Expected behaviour

Logging in smoothly from the client.

### Actual behaviour

All of a sudden, after upgrading to desktop client v3.4.0, I got logged out from my account in my Nextcloud, MacOS 12.0.1. When trying to log back in, I get these errors:

### Steps to reproduce

1. being logged out from a working account on Nextcloud
1. adding a new account on Nextcloud client
1. Error message: `Failed to connect to Nextcloud at httos://cloud.tommi.space/: SSL handshake failed`

### Client configuration
Client version:
3.4.0

Operating system: MacOS 12.0.1

OS language: English

### Server configuration

Nextcloud version: 22.2.0

### Logs

N/A

1. Client logfile: [log.zip](https://github.com/nextcloud/desktop/files/7666667/log.zip)
2. Web server error log: no error
3. Server logfile: nextcloud log (data/nextcloud.log): N/A (YunoHost package)

### Solution

Downgrading to client v3.3.6

#### Note

- I manually updated my SSL certificate from YunoHost webadmin, it updated correctly, but the error still apears.
- On my Nextcloud desktop client, I have another Nextcloud account from another server, and it works smoothly.

<img width="648" alt="Screenshot 2021-12-07 at 9 00 38 AM" src="https://user-images.githubusercontent.com/42862428/144990051-03269e79-0f4f-4fee-8e73-0719b5fae7de.png">
<img width="411" alt="Screenshot 2021-12-07 at 9 00 27 AM" src="https://user-images.githubusercontent.com/42862428/144990059-c5c5fc00-fa11-47c7-ac8d-0ba74dfadcbf.png">
<img width="695" alt="Screenshot 2021-12-07 at 9 00 13 AM" src="https://user-images.githubusercontent.com/42862428/144990062-271c49ce-5ce4-49c6-99a3-4e1e1700755e.png">
<img width="551" alt="Screenshot 2021-12-07 at 8 53 25 AM" src="https://user-images.githubusercontent.com/42862428/144990067-4afb8aa5-53c1-49e3-8905-6da494c1dfae.png">

**Comment by wilchak** [comment] 2021-12-08 23:12
Looks like a dupe of #3974

**Comment by luc-ass** [comment] 2021-12-26 15:15
Same probable, but different operating system. Had to revert to 3.3.6 as well.

**Comment by claell** [comment] 2022-01-18 10:36
Marking as duplicate. Feel free to reopen or complain if this is not correct.

**Comment by claell** [comment] 2022-01-18 10:36
Duplicate of #3974

**Closed by claell** 2022-01-18 10:36 UTC
Labels: bug, regression, os: :apple: macOS
