### ISSUE TITLE
Files with ":" ignored but synchronization shows as successful (no error message)

### ISSUE THREAD

**Issue by Aldaris1985** [nextcloud/desktop#1723] opened 2020-01-13 14:49 UTC
### Expected behaviour
Syncing pictures from my iPhone (iOS 13, Nextcloud 2.25.3.6) to my VPS (Ubuntu 16.04, Nextcloud 15.0.12) and then back to my desktop (Windows 10 x64, Nextcloud 2.6.2). iPhone stored pictures with time and ":" in the name which is no problem for Linux but files are not synced to Windows. Due to this issue, an error message is shown. (maybe apart from the file handling as indicated #1537 )

### Actual behaviour
Files with ":" in the name are ignored, synchronization is shown as successful.

### Steps to reproduce
1. Create a file containing ":" in the linux server
2. Try to sync with Windows Client for Nextcloud

### Client configuration
Client version: 2.6.2

Operating system: Windows 10 x64, 1909

OS language: English

Installation path of client: C:\Program Files\Nextcloud

### Server configuration
Nextcloud version: 15.0.12

### Logs

[OCC::PropagateItemJob::scheduleSelfOrChild 	Starting INSTRUCTION_IGNORE propagation of "Video12,Dec 29 2019, 13:01:32:23,PM 4528.mov" by OCC::PropagateIgnoreJob(0x24b6b0abd50)
[OCC::PropagateItemJob::done 	Could not complete propagation of "Video12,Dec 29 2019, 13:01:32:23,PM 4528.mov" by OCC::PropagateIgnoreJob(0x24b6b0abd50) with status 6 and error: "File names containing the character ':' are not supported on this file system."
[OCC::ActivityWidget::slotItemCompleted 	Item  "Video12,Dec 29 2019, 13:01:32:23,PM 4528.mov"  retrieved resulted in  "File names containing the character ':' are not supported on this file system."
[OCC::ActivityWidget::slotItemCompleted 	Item  "Video12,Dec 29 2019, 13:01:32:23,PM 4528.mov"  retrieved resulted in error  "File names containing the character ':' are not supported on this file system."

[OCC::Folder::slotSyncFinished 	Client version 2.6.2stable-Win64 (build 20191224)  Qt 5.12.5  SSL  OpenSSL 1.1.1d  10 Sep 2019
[OCC::Folder::slotSyncFinished 	SyncEngine finished without problem.
[OCC::Folder::showSyncResultPopup 	Folder sync result:  3

**Comment by cloo** [comment] 2020-03-04 14:12
I confirm the case with "|" character. 

Naturally Windows does not support such filenames, but users should be informed that something is not syncing.

(I risked getting into fight with a coworker, because the sync was obviously working, and I didnt see his files appearing on time)

Nextcloud 16, Windows client 2.6.2

**Comment by claell** [comment] 2020-04-04 17:14
This seems to be a duplicate of #464. Please confirm and close this issue if that is the case. Discussion can continued in the original issue then.

**Comment by Aldaris1985** [comment] 2020-04-11 01:22
@claell this is not the same issue. #464 is in general about the issue with some characters in Windows, while this issue mentions that the error with special characters for syncing is not popping up (more an error reporting topic).

**Comment by claell** [comment] 2020-04-11 15:51
Alright, thanks for pointing that out. I will leave this open then, since it addresses a more specific issue (probably also resulting of the causes #464 describes) but might be solvable with a different solution.

**Comment by damienvancouver** [comment] 2020-07-07 21:18
I just fixed this after an employee renamed files in the web UX to have "|" chars in them.

I can confirm that it is a silent failure:
- No errors in the client (the folders just vanish)
- No log entries whatsoever of the problem folders/files in the sync log.

That behavior is dangerous because it erodes the trust/credibility that the users have in Nextcloud: it needs to _feel_ safe / rock solid / ephemeral etc. in order for mass adoption to take place.

Ideally there would be both log message and error message.     

The solution of "rename the file in the web interface" is a good one to offer as well.

**Comment by er-vin** [comment] 2020-08-11 05:51
Duplicate of #464

**Closed by er-vin** 2020-08-11 05:51 UTC
Labels: bug, feature: :arrows_counterclockwise: sync engine, os: :door: Windows

**Comment by Aldaris1985** [comment] 2020-08-18 23:39
> 
> 
> Duplicate of #464

This is not a duplication. Although the issue with special characters in Windows is the same, this issue refers to how the client is reporting the issue. If you have a file with special charter in your linux server with Nextcloud, then this file is not synchronized to your Windows client but the Nextcloud client is still reporting the synchronization as successful without any indication of such character issue (apart from the log file where "normal" users would not look into).
