### ISSUE TITLE
Segfault on ubuntu 21.04 beta

### ISSUE THREAD

**Issue by fulljackz** [nextcloud/desktop#3090] opened 2021-04-12 13:33 UTC
### Expected behaviour
Starting nextcloud-client at the boot, from app menu or from command-line.
Starting the client must start synchro check and add an icon on system tray.

### Actual behaviour
- At the boot step, nothing.
- When trying to start nextcloud from cli, here is the output : 

```
un@nu:~|⇒  nextcloud
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
[1]    60762 segmentation fault (core dumped)  nextcloud
```
- Applying warn tip : 

```
un@nu:~|⇒  QT_QPA_PLATFORM=wayland nextcloud
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
[1]    60963 segmentation fault (core dumped)  QT_QPA_PLATFORM=wayland nextcloud
```

### Steps to reproduce
- Following nextcloud ppa informations : https://launchpad.net/~nextcloud-devs/+archive/ubuntu/client
1. sudo add-apt-repository ppa:nextcloud-devs/client
2. sudo apt update
3. sudo apt install nextcloud-desktop

### Client configuration
Client version:

Operating system: Ubuntu 21.04 (beta)

OS language: EN

Qt version used by client package (Linux only, see also Settings dialog): N/A

Client package (From Nextcloud or distro) (Linux only): Nextcloud ppa

Installation path of client:

Nextcloud version: 21.0.1

Storage backend (external storage): Directory

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile: 
```
Apr 12 15:28:18 kernel: [89954.092779] nextcloud[60963]: segfault at 8 ip 00007fd48a36063f sp 00007ffeebe52ef0 error 4 in libQt5Core.so.5.15.2[7fd48a101000+30b000]
Apr 12 15:28:18 kernel: [89954.092793] Code: 48 89 50 18 48 89 cb eb a5 66 90 f3 0f 1e fa 55 48 89 e5 41 57 41 56 41 55 41 54 53 48 81 ec a8 00 00 00 48 89 95 70 ff ff ff <4c> 8b 7f 08 64 48 8b 04 25 28 00 00 00 48 89 45 c8 31 c0 41 f6 47
```

**Comment by FlexW** [comment] 2021-04-12 14:13
The `QT_QPA_PLATFORM` environment variable is probably unrelated to this. Is it possible that you post your core dump after the crash?

**Comment by fulljackz** [comment] 2021-04-12 14:34
Yep I can upload a coredump (26M).
Is there a better solution that github to upload binary files ?
I don't really know coredump and debug related files, are there some risks to expose on on the internet ?

Regards,

**Comment by FlexW** [comment] 2021-04-12 14:37
Sure. You can upload it here https://cloud.nextcloud.com/s/gF7E326o5fPiXFi

**Comment by ShevT** [comment] 2021-04-12 14:37
Kubuntu 21.04 beta (no wayland)
https://gist.github.com/ShevT/580f633fdb98a3cbbc599c7af4f77afb

**Comment by fulljackz** [comment] 2021-04-12 14:39
> Sure. You can upload it here https://cloud.nextcloud.com/s/gF7E326o5fPiXFi

Done. Compressed.zip is it ok for you ?

**Comment by FlexW** [comment] 2021-04-12 14:42
> > Sure. You can upload it here https://cloud.nextcloud.com/s/gF7E326o5fPiXFi
> 
> Done. Compressed.zip is it ok for you ?

Yes, thanks.

**Comment by jirislav** [comment] 2021-04-12 21:25
I also have this issue. And I confirm that `QT_QPA_PLATFORM` is not related as this error message is not shown to me.

Version used: `3.2.0-20210410.072919.14fbf1b10-1.0~hirsute1`

OS: Ubuntu Hirsute 21.04
Lang: EN
PPA used: yes

---

Also note that when I run the AppImage, it runs without any problem at all: https://github.com/nextcloud/desktop/releases/tag/v3.2.0-rc3

**Comment by bjo81** [comment] 2021-04-14 09:35
Same here on MATE without wayland.

**Comment by FlexW** [comment] 2021-04-15 08:01
I looked into this and can confirm the crash but I'm unsure why it happens. If I compile the client myself, then it runs fine. I would suggest it's a problem with the ppa itself. @ivaradi what do you think?

**Comment by bjo81** [comment] 2021-04-15 08:21
The 3.1.0 client from the usual 21.04 repos also crash, so it seems it's nothing special to the ppa.

**Comment by ivaradi** [comment] 2021-04-15 15:29
The build is basically the same for Hirsute and, say, Groovy, except of course that the system libraries and the compiler, etc. are of different versions. 

I use the Groovy version on my machine, and it does not crash, so I also think the issue is not specific to the PPA itself, but rather the Hirsute environment.

**Comment by jirislav** [comment] 2021-04-16 08:52
My first guess is that the problem is exactly that you can run it on `groovy`.

You actually should not be able to run it there, but on `hirsute` itself.

So my thought is:
- what OS distribution is used for the packaging?
- it should be always the same as the target distro
- if package for `hirsute` is built inside a `groovy` environment, that'd explain a lot

**Comment by matttbe** [comment] 2021-04-18 06:14
Thank you for looking at the issue.

FYI, this issue is also tracked on Launchpad as it also affects the version packaged by the distribution: https://bugs.launchpad.net/ubuntu/+source/nextcloud-desktop/+bug/1923053

If the issue is in QT libs, it is possible to notify people maintaining these libs. Do you know which lib is causing that?

**Comment by matttbe** [comment] 2021-04-18 06:24
> it should be always the same as the target distro

@jirislav packages available on Launchpad and the "official" ones (distributed with Ubuntu in the official repo) ensure that.
In theory, if libs introduce some modifications that require a rebuild of apps depending on these libs, "official" packages are rebuilt. But here, even these packages have the issue.

**Comment by rikmills** [comment] 2021-04-22 09:25
This appears to be due to building with LTO enabled, as per #2790

**Comment by drohhyn** [comment] 2021-04-22 09:53
Just to bump the urgency: Ubuntu 21.04 release is today.

**Comment by rikmills** [comment] 2021-04-22 10:20
LTO can be disabled by

```
-export DEB_BUILD_MAINT_OPTIONS = hardening=+all
+export DEB_BUILD_MAINT_OPTIONS = hardening=+all optimize=-lto
```
in debian/rules

**Comment by marukuru** [comment] 2021-04-22 11:31
> LTO can be disabled by
> 
> ```
> -export DEB_BUILD_MAINT_OPTIONS = hardening=+all
> +export DEB_BUILD_MAINT_OPTIONS = hardening=+all optimize=-lto
> ```
> 
> in debian/rules

Rebuild the PPA package locally with `-lto` and it works fine.

**Comment by jbouter** [comment] 2021-04-22 13:53
> I also have this issue. And I confirm that `QT_QPA_PLATFORM` is not related as this error message is not shown to me.
> 
> Version used: `3.2.0-20210410.072919.14fbf1b10-1.0~hirsute1`
> 
> OS: Ubuntu Hirsute 21.04
> Lang: EN
> PPA used: yes
> 
> Also note that when I run the AppImage, it runs without any problem at all: https://github.com/nextcloud/desktop/releases/tag/v3.2.0-rc3
> 
> If you need to run Nextcloud as of right now, run this command for hotfix:
> 
> ```shell
> wget https://github.com/nextcloud/desktop/releases/download/v3.2.0-rc3/Nextcloud-3.2.0-rc3.AppImage
> chmod +x Nextcloud-3.2.0-rc3.AppImage
> sudo mv Nextcloud-3.2.0-rc3.AppImage /usr/bin/nextcloud
> ```

The appimage now has a segault for me as well (using `Nextcloud-3.2.0-x86_64.AppImage`). Ubuntu 21.04 regular. Both wayland and xorg session.

**Comment by ivaradi** [comment] 2021-04-22 15:01
Thanks @rkmills and @marukuru, I have disabled the LTO build for Hirsute in the PPA and have rebuilt the 3.2.0 packages. They should work now.

**Comment by fulljackz** [comment] 2021-04-22 15:05
I confirm, it works now !
Thanks for your help !

**Comment by jbouter** [comment] 2021-04-22 20:30
Can confirm as well - works fine indeed. Thanks @ivaradi !

**Comment by FlexW** [comment] 2021-04-23 12:21
@ivaradi are you allowed to close the issue? If yes, please close it if it is resolved, otherwise tell me that it is resolved and then I will close it :)

**Closed** 2021-04-23 12:25 UTC
Labels: bug, crash
