### ISSUE TITLE
Local Keepass File corrupted by Nextcloud Sync Desktop Client on Win10

### ISSUE THREAD

**Issue by Linkinsoldier** [nextcloud/desktop#2718] opened 2020-12-14 18:53 UTC
Hi,

I am using Nextcloud for contacts, calendar and also Keepass Files. However for some reason since I use the Nexcloud Desktop app on different PCs (WIN10), it sporadically keeps happening that my local Keepass file gets corrupted by the Client. 

### Steps to reproduce
1. Start PC
2. Let Nextcloud Desktop Client sync the Files
My guess is, that this sporadically happens, when the network connection is 

### Expected behaviour
Sync happens without corrupting files OR it waits (if no network connection) until sync can be safely performed.

### Actual behaviour
It seems like there is some kind of network connection error. I get a "red cross" sync error and when i compare the File manually downloaded from my server with the "synced" version - I see the HTTP 500 Error in the file! So somehow the sync is not done successfully, but the file is nevertheless changed and it looks to me, like some part of the error log gets written into the local file. I can no longer use the Keepass file afterwards obviously. Solution is to drag/drop the "manually downloaded" file from nextcloud (webpage) to my nextcloud folder (local - which is then "synced" via the client) and everything works again. Since most of my passwords are being stored there, I am kind of nervous about this and therefor ask if someone has seen this before?

### Server configuration
I use a webserver from pixelx: https://www.pixelx.de/nextcloud.html
I dont know the details about der server (PHP version, webserver, ...), but if it is important (I would guess not since it is a sync topic) I can try to find out all the info you need. I am pretty sure it has nothing to do with pixelx.

**Nextcloud version:** happened twice with 19.0.5 and 19.0.6 now - I just updated to NC 20.0.3, but I doubt its the Nextcloud Version

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated from NC14 - using it since a few years

**Desktop Client Version: 3.0.2

**Are you using external storage: no

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one: I think no

**Comment by kesselb** [comment] 2020-12-15 10:06
cc @er-vin

**Comment by er-vin** [comment] 2020-12-15 10:25
Not sure we can do much about this. It's the nature of KeePass which makes it harder to deal with stuff like that. They have very weird and needed ways to save to the file.

At least I know that on KeePassXC there are settings to try to mitigate this for Dropbox and the likes (including us).

**Comment by Linkinsoldier** [comment] 2020-12-15 19:38
Sorry, i was not aware there is a difference between keepassXC and keepass regarding this. I am using KeepassXC. 

The funny thing is. Keepass was closed yesterday on my desktop, i added new keys on my laptop and the sync to my cell via nextcloud was okay. However when i started my desktop again i received the sync error after logging in... before i have done anything with keepass on my desktop.

So I am pretty sure this has nothing to do with keepass. Or is there some logical link I am not aware of?

**Comment by er-vin** [comment] 2020-12-16 04:43
If you use KeePassXC I'd advise you try unchecking "Safely save database files" in the settings and see if that helps.

**Comment by Linkinsoldier** [comment] 2020-12-16 05:43
According to this, i should keep it enabled:
https://github.com/keepassxreboot/keepassxc/issues/1724

I am sorry to ask, but it also doesnt explain to me, why the 500 error was written in the keepassxc file. What i did:

1) Change file on desktop
2) let it be synced cia nextcloud to my laptop (so saving should not have done any harm)
3) changing it on my laptop
4) letting it sync to nextcloud
5) boot up my pc again without entering the password in keepassxc
-> now my pc file was corrupted, but nextcloud and laptop files were still fine!

How can this be a "saving problem" on the pc?

**Comment by er-vin** [comment] 2020-12-16 05:49
Oh right kind of overlooked it saved the HTTP 500 error in the file. That sounds like a duplicate of something we hunted earlier with no good way to reproduce it Someone had it for a little while and it disappeared before we could pinpoint it. I will thus close this on in favor of #2483

If you can get us the logs I'm requesting on #2483 and post them there it'd help.

**Closed by er-vin** 2020-12-16 05:49 UTC
Labels: 0. Needs triage, bug
