### ISSUE TITLE
after updating to 3.X from 2.x, it changes my Sync Settings!

### ISSUE THREAD

**Issue by mer-at** [nextcloud/desktop#2370] opened 2020-09-06 08:40 UTC
### Expected behaviour
after updating from 2.6 to 3.x, the new version should have THE SAME SETTINGS!!!!!!!!! as the old version

### Actual behaviour
it just tries to sync EVERYTHING on my nextcloud server. even though i've setup the 2.6 app to just sync ONE SINGLE FOLDER! (AND FOR A GOOD REASON!!!!!!!)

### Steps to reproduce
update 2.6 to 3.x

Operating system: Windows 10

**Comment by iav** [comment] 2020-09-06 10:46
Before update I have 7 different sync folders, all sync to different places (not one tree). After upgrade I see only one folder sync pair.

**Comment by Bockeman** [comment] 2020-09-06 14:17
Same issue for me and others
https://help.nextcloud.com/t/folder-sync-connections-lost-after-win10-nextcloud-client-upgrade-to-3-0-1/91460/6

I did the upgrade to 3.0.1
When I started "Settings" to view the status of each my Folder Sync Connections, only one (out of 13) was present.

Just to be sure, in case a system reboot might help, I rebooted.  Now two showed up.

I stopped Nextcloud-Client and restarted it.  Now three Folders showed up.
Obviously, I repeated and got all 13 back.

Next, when I  did the upgrade on a laptop, with much less storage, I repeated the same process of restarting until all sync folders reappeared.  However, within each folder, the selection of subdirectories has been lost.  That required manually adjusting each one.

Something has clearly  gone wrong with the list of sync folders and subfolder details.

**Comment by workingmachine** [comment] 2020-09-06 14:19
Hi, i had the same issue at upgrading the client from 2.6.5 to 3.0.1 at Windows 10.
It turned out that the client add at every new start one recent sync folder.
You can see this behavior by open the settings dialog.
Wait the client has synced new recent folder, than close the client and start it again and open the settings dialog.

**Comment by mlegner** [comment] 2020-09-07 07:47
I have the same issue under archlinux.

**Comment by er-vin** [comment] 2020-09-07 11:42
Looks like a duplicate of #2279

**Closed by er-vin** 2020-09-07 11:42 UTC
