### ISSUE TITLE
[Bug]: nextcloud-client nagging about "network unreachable" 

### ISSUE THREAD

**Issue by philfry** [nextcloud/desktop#6647] opened 2024-04-17 13:39 UTC
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

since some releases everytime I open my laptop from sleep or suspend I get nagged from nextcloud-client about "Host not found". Yes, it's probably correct that the network is not fully available right after the laptop is woken up, but imho it would be better to just check the network status and try again later.

### Steps to reproduce

1. open laptop lid to wake it up
2. get nag screen about "network unreachable"

### Expected behavior

nextcloud-client connecting to the server after it detects the network is back again

### Which files are affected by this bug

none

### Operating system

Linux

### Which version of the operating system you are running.

Fedora 39

### Package

Distro package manager

### Nextcloud Server version

28.0.4.1

### Nextcloud Desktop Client version

nextcloud-client-3.12.3-1.fc39.x86_64

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Enabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [X] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by PhilippSchlesinger** [comment] 2024-04-18 07:05
This is a duplicate of https://github.com/nextcloud/desktop/issues/6487

**Comment by eldar** [comment] 2024-04-26 06:58
I can confirm this on Fedora 40 and Nextcloud Desktop 3.12.3. Even though I've disabled all notifications, when I log in the KDE Plasma session or wake from sleep, I keep getting the notification that the "network is unreachable".

**Comment by willemb2** [comment] 2024-04-29 21:53
3.13.0 renamed the notification from 'Network error' to 'Connection issue' but did not solve it :(
I found a way to speed up the reconnect after resume from sleep: go to Settings, Network and quickly switch to 'no proxy' and back to 'system proxy'. It starts synchronizing immediately!

**Comment by PhilippSchlesinger** [comment] 2024-05-02 09:40
@philfry As this issue is a duplicate of https://github.com/nextcloud/desktop/issues/6487, can you please close it yourself
@eldar @philfry please add your valuable details to https://github.com/nextcloud/desktop/issues/6487

**Closed** 2024-05-02 10:00 UTC
Labels: 0. Needs triage
