### ISSUE TITLE
Missing 2.6 Nextcloud Client Manual

### ISSUE THREAD

**Issue by TP75** [nextcloud/desktop#1509] opened 2019-10-12 22:50 UTC
One would presume the availability of an active online and current Manual for the NC desktop client.  However, the URL for the Manual shows a dead link i.e. "File not found".

Mac OS X / MacOS NC desktop client: Version 2.6.0stable (build 20190927)

See the client tab "General" i.e. "Allgemein" in the German locale as follows:
> Version 2.6.0stable (build 20190927). Für weitere Informationen klicken Sie bitte [hier.](https://docs.nextcloud.com/desktop/2.6/)

- https://docs.nextcloud.com/desktop/2.6/  -- is empty

Furthermore, the issue on "[ What is the current Client Manual? #839](#839)" appears as relevant as before.

**Comment by TP75** [comment] 2019-10-15 08:59
see #1507

**Comment by jancborchardt** [comment] 2019-10-26 14:50
Closing as duplicate of https://github.com/nextcloud/desktop/issues/1507

**Closed by jancborchardt** 2019-10-26 14:50 UTC
