### ISSUE TITLE
Windows Desktop: cant resolve conflict

### ISSUE THREAD

**Issue by Snazzie** [nextcloud/desktop#2353] opened 2020-09-02 22:14 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour
1. Pressing on click for details should give me details.
 
![yOjIyDllEK](https://user-images.githubusercontent.com/19627023/92039586-34b95200-ed6d-11ea-8167-f64f8fb1777e.gif)

2. Pressing the conflict activity should take me to a place where i can resolve conflict.
3. Conflict activity text isnt wrapped, so a lot of the text isnt visible.
![sETISiVg3i](https://user-images.githubusercontent.com/19627023/92039589-35ea7f00-ed6d-11ea-9279-6d752e2ea649.gif)

### Actual behaviour
Tell us what happens instead
1. doesnt give me details. It doesnt do anything at all.
2. takes me to a place that doesnt help me resolve the issue.

### Steps to reproduce
1. copy synced contents to a new location that is also a same path. (fresh windows install)
2. set up next cloud.
3. start sync.
3. conflict occurs.

### Client configuration
Client version: 3.0.1

Operating system: Win 10

OS language: English UK

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From Nextcloud or distro) (Linux only):

Installation path of client: C:/.....

### Server configuration

Run in docker on unraid server.

Nextcloud version: 18.0.8, 19.0.2

Storage backend (external storage):

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile: No logs appear when clicking on click for details
2. Web server error log: none appears for both click for details and conflict activity 
3. Server logfile: nextcloud log (data/nextcloud.log): https://gist.github.com/Snazzie/be77f986ae8fb781366d23544521a893

**Comment by Snazzie** [comment] 2020-09-03 09:52
Just updated, this issue still exists in 19.0.2

**Comment by er-vin** [comment] 2020-09-03 12:40
Looks like a duplicate of #2349

**Closed by er-vin** 2020-09-03 12:40 UTC

**Comment by Snazzie** [comment] 2020-09-03 17:34
Not entirely, the other one doesnt cover the click to show details part of this issue.

**Comment by Snazzie** [comment] 2020-09-03 17:35
i can reduce this issue if you like.

**Comment by er-vin** [comment] 2020-09-08 12:47
Thanks for the offer but don't bother, the "show details" we got in various forms as well in other issues. So it's in the list as well already.
