### ISSUE TITLE
[Bug]: Files larger than 100MB not uploading / better handling of chunk limits

### ISSUE THREAD

**Issue by N-Hertstein** [nextcloud/desktop#6473] opened 2024-02-21 15:51 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

I am using Nextcloud behind nginx proxy manager and cloudflare. I have given a few family members access to my Nextcloud server, however they cannot upload files larger than 100MB due to the cloudflare upload limit. Now I understand that I can change the max chunksize in the client config file, however this is not a real solution. I can't teach my gandpa how to installl teamviewer so I can fix his shit every time he has a new laptop. And businesses cannot be expected to change this for every pc in a large scale deployment. Since Cloudflare is so widely used either the default chunksize needs to be <100MB or I need to be able to adjust this from the server. 

### Steps to reproduce

1. Have a nextcloud server
2. Set it up with cloudflare
3. Install nexcloud client on family's computer
4. Wait until they inevitably have a file >100MB
5. Get constant errors
6. Get constant texts about errors 

### Expected behavior

1. Have a nextcloud server
2. Set it up with cloudflare
3. Install nexcloud client on family's computer
4. Wait until they inevitabaly 
5. Chunksize is <100MB resulting in a working system OR: Get errors and adjust chunksize in server

### Installation method

None

### Nextcloud Server version

28.0.2

### Operating system

Docker Linux (Debian/Truenas Scale)

### PHP engine version

8.2.16

### Web server

Uncertain of what to put here

### Database engine version

PostgreSQL 13.1 (Debian 13.1-1.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit

### Is this bug present after an update or on a fresh install?

Yes

### Are you using the Nextcloud Server Encryption module?

Nope

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

Default apps + cookbook

**Comment by joshtrichards** [comment] 2024-02-21 22:56
P.S.  I apologize for leaning a bit more on speculation than I usually prefer in my response a short bit ago.

My aim was to add a bit to the discussion, but upon reflection I *probably* should have just left it as a draft for now. :-)

This topic just happens to connect with one I've had on my "to investigate" list for a bit: the behavior of chunking, particularly in a default configuration, in the Desktop versus Web clients.

(Lacking time today to get deeply into this, I'm drawing heavily on memory and an *incomplete* prior review of the Desktop chunking code).

This is mostly a disclaimer to take my speculation about differences in behavior with a grain of salt  for now. :-)

**Comment by joshtrichards** [comment] 2024-08-15 13:45
Duplicate of #4278

**Closed by joshtrichards** 2024-08-15 13:45 UTC
Labels: 0. Needs triage, bug, discussion, feature: :arrows_counterclockwise: sync engine
