### ISSUE TITLE
[Bug]: Speicherzugriffsfehler

### ISSUE THREAD

**Issue by kaffeeringe** [nextcloud/desktop#5215] opened 2022-11-25 14:50 UTC
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

Nextcloud doesn't start.

### Steps to reproduce

1. I click the icon
2. It doesn't start

1. Open the console
2. I type "nextcloud"
3. Console says:
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
Speicherzugriffsfehler (Speicherabzug geschrieben)

### Expected behavior

The programme should start

### Which files are affected by this bug

The Nextcloud programme

### Operating system

Linux

### Which version of the operating system you are running.

Ubuntu 22.10

### Package

Distro package manager

### Nextcloud Server version

25.0.0

### Nextcloud Desktop Client version

3.6.0

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Enabled

### Are you using an external user-backend?

- [X] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by joshtrichards** [comment] 2023-11-25 23:13
Duplicate of #5079

**Closed by joshtrichards** 2023-11-25 23:13 UTC
Labels: 0. Needs triage
