### ISSUE TITLE
[Bug]: Unable to read the text in the systray window

### ISSUE THREAD

**Issue by nodiaque** [nextcloud/desktop#7505] opened 2024-11-16 17:39 UTC
### ⚠️ Before submitting, please verify the following: ⚠️

- [x] This is a **bug**, not a question or a configuration issue.
- [x] This issue is **not** already reported on Github (I've searched it).
- [x] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

I'm on Windows 10 22H2with dark theme. Because of that, I'm unable to read whatever this screen is suppose to show.

![Image](https://github.com/user-attachments/assets/480656b4-275b-4127-a026-0cfcedaa7c87)

### Steps to reproduce

Click on the systrai Icon

### Expected behavior

The background should follow the theme

### Which files are affected by this bug

systray

### Operating system

Windows

### Which version of the operating system you are running.

10 22h2

### Package

Official Windows MSI

### Nextcloud Server version

30.0.2

### Nextcloud Desktop Client version

3.14.3

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [x] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Nextcloud Server logs

```shell

```

**Comment by Rello** [comment] 2024-11-17 13:16
Duplicate of
https://github.com/nextcloud/desktop/issues/7269

fix expected upcoming week

**Closed by Rello** 2024-11-17 13:16 UTC
Labels: 0. Needs triage, bug
