### ISSUE TITLE
When using multiple macOS spaces, nextcloud moves to one of them.

### ISSUE THREAD

**Issue by tex0l** [nextcloud/desktop#2643] opened 2020-11-16 12:53 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour
The nextcloud window should appear on click on the tray icon without changing from one [space](https://support.apple.com/fr-fr/guide/mac-help/mh14112/mac) to the other.

### Actual behaviour
Sometimes, there is one privileged space on which the nextcloud window appears, and if the click on the tray icon happens from another space, it switches to this privileged space.

### Steps to reproduce
1. Create multiple spaces (you can differentiate them by the background image) ;
<img width="1440" alt="Capture d’écran 2020-11-16 à 13 55 47" src="https://user-images.githubusercontent.com/7548264/99255013-8ec99f80-2813-11eb-9730-e4828ff6d121.png">
2. Click on the tray icon from one of them (I'm hovering on the icon, but the mouse pointer doesn't show on the screenshot);
<img width="1440" alt="Capture d’écran 2020-11-16 à 13 56 19" src="https://user-images.githubusercontent.com/7548264/99255039-98eb9e00-2813-11eb-8a55-78b099f6ce54.png">
3. If the window appears on this space it means this one is the privileged one, you'll need to switch to another space to reproduce, and click on the tray icon. It should forcibly switch to the privileged space. (I've blacked what's personal in the screenshot)
<img width="1440" alt="Capture d’écran 2020-11-16 à 13 56 30" src="https://user-images.githubusercontent.com/7548264/99255164-cb959680-2813-11eb-9221-f2b117a2c27f.png">

NB: apparently when using a secondary screen, when clicking on the tray icon, it resets the privileged space of the other screen to the currently displayed space on this other screen, even if it can be reproduced without a secondary screen.

### Client configuration
Client version: 3.0.3

Operating system: 11.0.1 but it happened as well on the latest Catalina

OS language: French

Installation path of client: /Applications/nextcloud.app

### Logs
When opening from the "privileged" space:
```
2020-11-16 13:48:17:086 [ debug nextcloud.gui.systray ]	[ OCC::Systray::computeWindowReferencePoint ]:	screenRect: QRect(0,0 1440x900)
2020-11-16 13:48:17:086 [ debug nextcloud.gui.systray ]	[ OCC::Systray::computeWindowReferencePoint ]:	taskbarRect: QRect(0,0 1440x22)
2020-11-16 13:48:17:087 [ debug nextcloud.gui.systray ]	[ OCC::Systray::computeWindowReferencePoint ]:	taskbarScreenEdge: OCC::Systray::TaskBarPosition::Top
2020-11-16 13:48:17:087 [ debug nextcloud.gui.systray ]	[ OCC::Systray::computeWindowReferencePoint ]:	trayIconCenter: QPoint(1069,11)
2020-11-16 13:48:17:087 [ debug nextcloud.gui.systray ]	[ OCC::Systray::computeWindowPosition ]:	taskbarScreenEdge: OCC::Systray::TaskBarPosition::Top
2020-11-16 13:48:17:088 [ debug nextcloud.gui.systray ]	[ OCC::Systray::computeWindowPosition ]:	screenRect: QRect(0,0 1440x900)
2020-11-16 13:48:17:088 [ debug nextcloud.gui.systray ]	[ OCC::Systray::computeWindowPosition ]:	windowRect (reference) QRect(869,26 401x511)
2020-11-16 13:48:17:088 [ debug nextcloud.gui.systray ]	[ OCC::Systray::computeWindowPosition ]:	windowRect (adjusted ) QRect(869,26 401x511)
2020-11-16 13:48:17:095 [ debug nextcloud.gui.activity ]	[ OCC::User::slotRefresh ]:	Do not check as last check is only secs ago:  2
2020-11-16 13:48:18:671 [ debug nextcloud.gui.systray ]	[ OCC::Systray::computeWindowReferencePoint ]:	screenRect: QRect(0,0 1440x900)
2020-11-16 13:48:18:671 [ debug nextcloud.gui.systray ]	[ OCC::Systray::computeWindowReferencePoint ]:	taskbarRect: QRect(0,0 1440x22)
2020-11-16 13:48:18:672 [ debug nextcloud.gui.systray ]	[ OCC::Systray::computeWindowReferencePoint ]:	taskbarScreenEdge: OCC::Systray::TaskBarPosition::Top
2020-11-16 13:48:18:672 [ debug nextcloud.gui.systray ]	[ OCC::Systray::computeWindowReferencePoint ]:	trayIconCenter: QPoint(1069,11)
2020-11-16 13:48:18:672 [ debug nextcloud.gui.systray ]	[ OCC::Systray::computeWindowPosition ]:	taskbarScreenEdge: OCC::Systray::TaskBarPosition::Top
2020-11-16 13:48:18:672 [ debug nextcloud.gui.systray ]	[ OCC::Systray::computeWindowPosition ]:	screenRect: QRect(0,0 1440x900)
2020-11-16 13:48:18:673 [ debug nextcloud.gui.systray ]	[ OCC::Systray::computeWindowPosition ]:	windowRect (reference) QRect(869,26 401x511)
2020-11-16 13:48:18:673 [ debug nextcloud.gui.systray ]	[ OCC::Systray::computeWindowPosition ]:	windowRect (adjusted ) QRect(869,26 401x511)
2020-11-16 13:48:18:678 [ debug nextcloud.gui.activity ]	[ OCC::User::slotRefresh ]:	Do not check as last check is only secs ago:  4
```

When opening from another space:
```
2020-11-16 13:48:49:079 [ debug nextcloud.sync.networkjob ]	[ OCC::AbstractNetworkJob::slotFinished ]:	Network job OCC::RequestEtagJob finished for "/"
2020-11-16 13:48:53:469 [ debug nextcloud.gui.systray ]	[ OCC::Systray::computeWindowReferencePoint ]:	screenRect: QRect(0,0 1440x900)
2020-11-16 13:48:53:470 [ debug nextcloud.gui.systray ]	[ OCC::Systray::computeWindowReferencePoint ]:	taskbarRect: QRect(0,0 1440x22)
2020-11-16 13:48:53:470 [ debug nextcloud.gui.systray ]	[ OCC::Systray::computeWindowReferencePoint ]:	taskbarScreenEdge: OCC::Systray::TaskBarPosition::Top
2020-11-16 13:48:53:470 [ debug nextcloud.gui.systray ]	[ OCC::Systray::computeWindowReferencePoint ]:	trayIconCenter: QPoint(1069,11)
2020-11-16 13:48:53:470 [ debug nextcloud.gui.systray ]	[ OCC::Systray::computeWindowPosition ]:	taskbarScreenEdge: OCC::Systray::TaskBarPosition::Top
2020-11-16 13:48:53:471 [ debug nextcloud.gui.systray ]	[ OCC::Systray::computeWindowPosition ]:	screenRect: QRect(0,0 1440x900)
2020-11-16 13:48:53:471 [ debug nextcloud.gui.systray ]	[ OCC::Systray::computeWindowPosition ]:	windowRect (reference) QRect(869,26 401x511)
2020-11-16 13:48:53:471 [ debug nextcloud.gui.systray ]	[ OCC::Systray::computeWindowPosition ]:	windowRect (adjusted ) QRect(869,26 401x511)
```

**Comment by er-vin** [comment] 2020-12-02 07:21
Duplicate of #2332

**Closed by er-vin** 2020-12-02 07:21 UTC
Labels: enhancement, os: :apple: macOS
