### ISSUE TITLE
No avatar at first

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/desktop#2881] opened 2021-01-28 12:23 UTC
- start 3.1.2 appImage on Arch Linux
- ![image](https://user-images.githubusercontent.com/5836855/106138028-e1a4c900-616b-11eb-8a76-5a25a48b3c79.png)

- click on other account
- ![image](https://user-images.githubusercontent.com/5836855/106138072-f41f0280-616b-11eb-9f59-07efa778760e.png)

- click on next account
- ![image](https://user-images.githubusercontent.com/5836855/106138112-00a35b00-616c-11eb-89f9-540253f2b92d.png)

**Comment by er-vin** [comment] 2021-01-28 12:30
Duplicate of #2731 I think. I suspect this in fact goes all the way back to 3.0.0.

**Closed by er-vin** 2021-01-28 12:30 UTC
Labels: bug, package: appimage
