### ISSUE TITLE
Write and read comments or activity log for a file by right-clicking

### ISSUE THREAD

**Issue by mkrecek234** [nextcloud/desktop#3767] opened 2021-09-08 20:22 UTC
Would be great if the Nextcloud client also offers to see and add comments for a file, by right clicking on the desktop.

**Comment by joshtrichards** [comment] 2023-11-21 22:42
Duplicate of #4002 

Let's track progress there. Feel free to upvote/subscribe to that issue.

**Closed by joshtrichards** 2023-11-21 22:42 UTC
Labels: enhancement
