### ISSUE TITLE
Fix White Window issue on Windows after Qt 5.12.4 upgrade

### ISSUE THREAD

**Issue by camilasan** [nextcloud/desktop#1446] opened 2019-09-26 09:06 UTC
See #1445

**Comment by misch7** [comment] 2019-09-29 12:56
Fixed by upgrading to Qt 5.12.5. Already integrated and confirmed working in our 2.6.0 release, so closing this with a good feeling 🎉 😸 

Revert "Fix White Window issue on Windows after Qt 5.12.4 upgrade": https://github.com/nextcloud/desktop/commit/00db94a73c6da2ed343bc39a2205b3fea4a4ff65

This reverts commit 8f61696.

Turns out that with the upgrade to the new released Qt 5.12.5 the issue
has been solved by the Qt developers, so this fix becomes obsolete.

**Closed by misch7** 2019-09-29 12:56 UTC
Labels: technical debt
