### ISSUE TITLE
macOS client hangs during login

### ISSUE THREAD

**Issue by frankgerhardt** [nextcloud/desktop#934] opened 2018-12-11 12:46 UTC
To reproduce 

1. enter server url
2. enter username and password
3. "Forwarding" ("Weiterleiten") is displayed and it hangs forever

I reinstalled the client 5 times already.

macOS 10.14, client Nextcloud-2.5.1.20181204.pkg, also tried 2.5.0 

The "solution" is to use 2.3.3 which is behind around one year of development. 

As a side node, on a MacBook Air the dialog is too high and the Next (Weiter) button can not be seen. The "solution" is to make the dialog full-screen to force a re-layouting. On the next dialog page the sam, to high, not shown, go to full-screen. Annoying.

**Comment by frankgerhardt** [comment] 2018-12-11 12:47
And, the older releases of the client are hard to find. As a techie it was worth trying a shorter URL so that I could find the directory listing at https://download.nextcloud.com/desktop/releases/Mac/Installer/

**Comment by janvlug** [comment] 2018-12-12 12:07
Is this a duplicate of issue #279?

**Comment by camilasan** [comment] 2021-02-12 16:01
Hi, Could you try to run the most recent desktop client and server to check if you still have this issue? The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients) and [https://nextcloud.com/install/#instructions-server](https://nextcloud.com/install/#instructions-server) respectively.

If you still have this problem with the latest desktop client, please re-open the issue.

Thanks!

**Closed by camilasan** 2021-02-12 16:01 UTC
