### ISSUE TITLE
Virtual FS : Sync folders don't appear in the explorer's navigation pane

### ISSUE THREAD

**Issue by Webbeh** [nextcloud/desktop#3228] opened 2021-04-28 17:02 UTC
### Expected behaviour
If the `Show sync folders in Explorer's navigation pane` checkbox is ticked, it is expected to have the synchronized folders appear in said navigation pane.

### Actual behaviour
Whenever the `Virtual file` support is enabled on a sync, whether by adding a new sync or updating an existing one, that synchronized folder disappears from the explorer's nav panel.

This happens whether or not the setting is checked, and whether the sync is added before or after checking said setting.

As a precision : this does not affect normal syncs, only those with virtual file system.

### Steps to reproduce
1. Create a new folder sync
2. Enable `virtual file` support
3. Examine the explorer navigation panel and try to look for that new folder sync.

### Client configuration
Client version: 3.2.0stable-Win64 (build 20210409)

Operating system: W10 Enterprise - 20H2 - 64bit

OS language: English

Installation path of client: Default

### Logs
In debug archive below.

### Debug archive
https://cockatoo.cloud/s/G4SD2GFjtG64P7w

**Comment by FlexW** [comment] 2021-04-29 07:14
I think this a duplicate of #3113

**Closed by FlexW** 2021-04-29 07:14 UTC
Labels: bug
