### ISSUE TITLE
[Bug]: German localization broken in 3.6.5 (macOS)

### ISSUE THREAD

**Issue by macschlingel** [nextcloud/desktop#5346] opened 2023-01-19 19:43 UTC
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

The macOS version of Nextcloud Desktop 3.6.5 shows the same text instead of localized strings if german is selected as the system language.

### Steps to reproduce

1. Set System language to German
2. Open Nextcloud Desktop
3. Click the Nextcloud Desktop Icon in the menubar
4. Look bewildered at the string "Übersetzung. Hier wird nur die formelle Übersetzung verwendet (de_DE)." instead of pretty much every german string
...

### Expected behavior

German localized strings are properly localized.

### Which files are affected by this bug

-

### Operating system

Mac OS

### Which version of the operating system you are running.

macOS 13.1 ventura

### Package

Appimage

### Nextcloud Server version

24.0.7

### Nextcloud Desktop Client version

3.6.5

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 3.4.2 to 3.4.4)

### Are you using the Nextcloud Server Encryption module?

Encryption is Enabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by kaekimaster** [comment] 2023-01-19 22:36
Duplicate of #5339

**Comment by allexzander** [comment] 2023-01-20 00:27
duplicate

**Closed by allexzander** 2023-01-20 00:27 UTC
Labels: 0. Needs triage
