### ISSUE TITLE
2.5 - wrong path - 404 Not Found

### ISSUE THREAD

**Issue by BurtGummer** [nextcloud/desktop#832] opened 2018-11-15 10:57 UTC
Just install the new 2.5 (Windows 10) version. The installer remove the old version, then it starts the configuration. I enter my path:

https://oc.example.org/cloud

Next Window "grand access" (Zugriff gewähren), but i select "access with App-Token", enter the App-Token. Next window i select a different local path. In this window, i can not select elements for syncing, it just show "There are no subfolders on the server."

then i klick "connect..." and i get:

![image](https://user-images.githubusercontent.com/1249295/48548454-464a1500-e8cd-11e8-89ac-92b0d8fa4686.png)

but i did not enter the path `..de/nextcloud/status.php` - any ideas? Bug?

**Comment by yoyko** [comment] 2018-11-15 12:14
I have my nextcloud instance under `https://<server>/nc/` and I just had the same problem (with the Mac client). Looks like the client doesn't work with nextcloud installed under different path on the server because of how it checks for `status.php`.

The client checks for `/status.php` and then falls back to `/nextcloud/status.php` (instead of using the correct "base" path from the base url):

https://github.com/nextcloud/desktop/blob/master/src/libsync/networkjobs.cpp#L464
https://github.com/nextcloud/desktop/blob/master/src/libsync/networkjobs.cpp#L500

(Note: I worked around it by adding a `RedirectPermanent /nextcloud/status.php /nc/status.php` to my apache configuration, but that's not really a solution ;)

**Comment by rullzer** [comment] 2018-11-15 15:09
What is your nextcloud version?

**Comment by BurtGummer** [comment] 2018-11-16 10:31
My post above have the Nextcloud Server Version 13. I try now with a other server with version 14, but after i enter the app-token and klick "grand access ->" nothing happens. The nextcloud.log have nothing and with the old client, everything works well.

**Comment by rullzer** [comment] 2018-11-16 11:33
@BurtGummer can you provide me with test credentials on both systems? `roeland at nextcloud.com`

**Comment by BurtGummer** [comment] 2018-11-16 12:33
@rullzer i have send you a mail. thank you for your time and work!

**Comment by rullzer** [comment] 2018-11-16 15:38
@BurtGummer thanks. I'll see if I can reproduce and debug.

**Comment by bebob1** [comment] 2018-11-16 15:55
I'm having the exact same problem after upgrading to 2.5. But for me it's the MacOS client.

**Comment by AKKlostermann** [comment] 2018-11-19 06:13
I have a similar problem, but on my setup, Nextcloud is hosted on the path /nextcloud, and that seems to be ignored (after correctly logging in, btw).

Server returned "404 Not Found" for "PROPFIND https://portal.my-domain.de/remote.php/webdav/"

I believe it should be https://portal.my-domain.de/nextcloud/remote.php/webdav/

**Comment by nr458h** [comment] 2018-11-19 07:43
@Akklostermann same here. The Client removes /nextcloud/ from the url after logging in

**Comment by AKKlostermann** [comment] 2018-11-19 10:41
Also I frequently get an error about authentication information not being present in the request. Not sure if that has anything to do with anything.

**Comment by rullzer** [comment] 2018-11-23 10:33
Ah right.

So. Yeah this is broken on <14.0.3 (server side).
If you upgrade to 14.0.4 it is fixed: https://github.com/nextcloud/server/pull/12299

**Comment by camilasan** [comment] 2018-11-27 17:08
@AKKlostermann Did upgrading worked for you?

**Comment by xylo** [comment] 2019-01-08 13:53
I cannot upgrade to NC 14, because NC 14 requires php7 which is not available on our server.

IMO this has to be fixed in the client.

**Comment by xylo** [comment] 2019-01-16 12:21
OK.  It looks like this is also fixed in Nextcloud server 13.0.8.  So PHP 5 people can upgrade to NC 13. :)

**Comment by StarPicard** [comment] 2019-02-01 11:18
I'm running Nextcloud 13.0.8 and just installed the Client in Version 2.5.1 and got the same error... So it doesn't seemed to be fixed.

**Comment by rullzer** [comment] 2019-02-01 12:02
@xylo great to hear.
Please do note that NC13 will be EOL soon.

**Closed by rullzer** 2019-02-01 12:02 UTC
Labels: 0. Needs triage
