### ISSUE TITLE
Add E2E encryption to Sync Process

### ISSUE THREAD

**Issue by Jonas1871** [nextcloud/desktop#1866] opened 2020-01-24 11:04 UTC
It would be awesome if you could enable E2E directly if you set up a new sync process so you don't have to create a dedicated sub-folder. Also it would help a lot if you could select to use E2E before actually starting the sync (guess that would help with the problem that you currently have to create a encrypted folder first before you can fill it with data).
Im aware that this method can only work for backing up folders from your PC to nextcloud and not for adding E2E to folders that are already stored on the cloud.

Example:
I'd like to backup a folder containing some photos using E2E (via the win desktop client).
 Currently i have to to add a folder sync, then add a sub folder, enable encryption for that folder and then copy my files to that folder.
What I whish:
I create a new folder sync of the folder i want to backup using E2E. In the process of selecting the folder I can just enable a checkbox for E2E.

If theres already a feature like this please tell me where I can find it because I wasn't able to find a better solution to my problem yet :)

**Comment by georgehrke** [comment] 2020-03-12 16:39
cc @misch7

**Comment by er-vin** [comment] 2020-05-19 15:47
Hello,

Closing as this is very likely a duplicate of #1063.

Regards.

**Closed by er-vin** 2020-05-19 15:47 UTC
Labels: 0. Needs triage, enhancement, feature: :lock: end to end encryption
