### ISSUE TITLE
Please bring back 'Pause sync for all' quick access

### ISSUE THREAD

**Issue by ajay10000** [nextcloud/desktop#2391] opened 2020-09-09 00:47 UTC
### Expected behaviour
Previous desktop client versions for Windows, right click system tray icon, select 'Pause sync for all'.

Nextcloud Windows desktop client repeatedly fires sync failure notifications when certain programs are open (i.e. Quicken/Reckon). The data files of these programs are locked and can't be sync'd. At this point I need to choose 'Pause sync for all' to stop the notifications interrupting until I close the offending program. 

### Actual behaviour
Pause sync for all is now three clicks away on a sub menu.

### Steps to reproduce
1. As above

### Client configuration
Client version: 3.0.1

Operating system: Windows 10 2004

OS language: English (AU)

**Comment by er-vin** [comment] 2020-09-09 16:58
Well the root cause is more about the client not dealing properly with said locked files or am I missing something?

**Comment by ajay10000** [comment] 2020-09-10 00:39
Yes I agree, but quick access to Pause sync for all is such a useful tool it is a shame to hide it away.  Another scenario is that Nextcloud desktop is still ignoring my ignore list in certain circumstances (I believe when the computer is restarted), so I use Pause Sync for all then as well.  Or perhaps when I get a video call and I'd like to quickly stop a sync to improve bandwidth.

**Comment by er-vin** [comment] 2020-09-10 10:58
Only the last case would be a more valid use case IMO, the rest is pretty much working around other issues (I prefer root causes to be fixed instead). @jancborchardt any opinion?

**Comment by jancborchardt** [comment] 2020-09-15 11:01
> Nextcloud desktop is still ignoring my ignore list in certain circumstances

@ajay10000 could you open a separate issue for that? Agree with @er-vin we should rather fix the root issues. :) 

> Or perhaps when I get a video call and I'd like to quickly pause a sync to improve bandwidth.

Makes sense, I actually find myself doing a similar thing when I want to improve bandwidth, I simply Exit Nextcloud fully. But yeah, putting "Pause sync" in the right-click menu ("Pause sync for all" if multiple accounts are configured) makes sense to access that quicker.

The entry should be in second position, between "Open main dialog" and "Settings".

**Comment by alex-dacosta** [comment] 2020-09-29 07:56
I agree that it was a useful option for circumventing the fact the Nextcloud client slows down the Windows Explorer to an unusable state.
However, until this Explorer overload is not fixed, it is more than useful to restore this capability.
Thanks

**Comment by biva** [comment] 2020-09-30 09:30
It is also useful when the client loses the connection to the server (for example because the server is down). When the server is available again, it happens that the client doesn't start the sync again (even after 1 hour): the icon in the Windows taskbar remains grey. This function ('Pause all sync') should be available even if the connection with the server is lost (or in general, even if the Nextcloud icon is grey in the Windows taskbar). 

The solution today is to stop the client, and start it again. 

I would also love to have a button "Force all sync" in this menu, but I don't know if it's the same issue or if I should start a new one?

**Closed** 2020-11-10 17:43 UTC
Labels: design, enhancement, feature: :arrows_counterclockwise: sync engine
