### ISSUE TITLE
add sync schedule to run only during certain times

### ISSUE THREAD

**Issue by penCsharpener** [nextcloud/desktop#198] opened 2018-02-27 07:42 UTC
the cloud sync app from a synology NAS has this where you can drag the mouse over a 7 line grid to mark the hours when syncing is enabled. 

![image](https://user-images.githubusercontent.com/26190934/36716305-2e410a50-1b9a-11e8-9569-f35fa8d71de2.png)

This is particularly useful for those in remote areas with satellite internet and contracts that give them unlimited data quota during certain hours of the night.

**Comment by esguti** [comment] 2019-09-18 07:01
I am working on it [https://github.com/esguti/desktop](https://github.com/esguti/desktop). Still ugly and not fully functional, but the working is on progress ;)

**Comment by camilasan** [comment] 2019-09-19 15:50
Hey @esguti we will have a contributor weekend of working on the desktop client in the end of October. Would you be interested in attending? if yes, drop me an email, I can give you the details. Thanks!

**Comment by esguti** [comment] 2019-09-20 10:46
> Hey @esguti we will have a contributor weekend for working on the desktop client in the end of October. Would you be interested in attending? if yes, drop me an email, I can give you the details. Thanks!

it would be really good!, but I am not sure if I will be able to attend in person. I send you an email

**Comment by jancborchardt** [comment] 2019-09-21 09:30
Heyhey, only saw this issue now. :) Are there examples of how e.g. Google Drive, Dropbox or iCloud solve this?

Cause Synology interface seems like a lot, and also difficult to maintain and test, no? I’d be a bit hesitant to put it in the core of the client?

> This is particularly useful for those in remote areas with satellite internet and contracts that give them unlimited data quota during certain hours of the night.

Maybe a first start would just be where you could define a time of day where it would sync?

But also, this seems a bit like this is functionality which could/should be in the operating system or handled more globally, no? Cause there’s also updates to install and other batch operations like this which use more data? :)

**Comment by esguti** [comment] 2019-09-22 20:12
I have seen evidence of this feature in Dropbox, Google drive or iCloud. The only reference I have found is using [the task scheduler in Windows for Google Drive](https://www.wintips.org/how-to-schedule-google-backup-and-sync/).

In my opinion is a cool feature and the missing of it in other collaboration platforms is an advantage. Think about a computer that it is used for running a heavy task during the day, which is very common in science, where you have to run simulations which consume a lot of resources of your machine. You don't want to synchronize every step of the simulation, you just want to synchronize the results at the end of the day, check them at home and plan the next simulation.

**Comment by michaelstingl** [comment] 2019-09-23 07:34
Why not just use the command line client?
https://docs.nextcloud.com/desktop/2.5/advancedusage.html#nextcloud-command-line-client

**Comment by esguti** [comment] 2019-09-23 20:10
> Why not just use the command line client?
> https://docs.nextcloud.com/desktop/2.5/advancedusage.html#nextcloud-command-line-client

The command line is very useful for advanced users who know scripting, but for normal users, is better not to mess with the command line, believe me, I have been giving support in a tech company :)

**Comment by esguti** [comment] 2019-09-23 20:28
I have a functional version, not finished yet (specially the interface).
...If someone feels like testing it: https://github.com/esguti/desktop :) and write here your thoughts.

Thanks!

**Comment by howudodat** [comment] 2020-03-10 12:38
Just curious if there is any progress on this.  I see that the code is complete as of 4 months ago

**Comment by esguti** [comment] 2020-03-10 12:51
It is implemented, you can see the progress in [**Feature/scheduler** #1453](https://github.com/nextcloud/desktop/pull/1453), but it is waiting for approval from @camilasan and @misch7 for being merged with the main branch

**Comment by howudodat** [comment] 2020-03-10 15:06
yeah I saw that in 1453, but 4 months, is a bit of a long time :(, I guess I could build it myself

**Comment by esguti** [comment] 2020-03-11 07:23
Yes, check the branch https://github.com/esguti/desktop/tree/feature/scheduler and don't hesitate to open an issue or contact me if you have any problem.

**Comment by aprams** [comment] 2020-03-24 13:41
Also interested in this for a while now. @camilasan and @misch7, would you mind checking @esguti's pull request? Looking at the comment history, he put quite some effort into this :)

**Comment by RiBeneke** [comment] 2020-05-28 13:58
I am keen to see the result. Can start NextCloud in Windows Task Scheduler but it continues to run in a process and stopping it is clumsy and problematic.
Need synchronising at specific times for databases (sync when not in use) and using 3G modems.

**Comment by umbynos** [comment] 2020-07-17 09:51
Any update on this? It's a really nice feature

**Comment by dh-dao** [comment] 2021-03-07 16:43
still no update on the project? I don't want my computer to sync instantly every photo that is uploaded from my smartphone.

**Comment by joshtrichards** [comment] 2024-04-07 16:24
Duplicate of #96

**Closed by joshtrichards** 2024-04-07 16:24 UTC
Labels: enhancement, good first issue, feature-request, feature: :arrows_counterclockwise: sync engine
