### ISSUE TITLE
[Bug]: Nextcloud UI (3.14.1) is broken on Windows  10 (21H2 19044.4894) using dark mode

### ISSUE THREAD

**Issue by PeterTucker** [nextcloud/desktop#7269] opened 2024-10-05 14:49 UTC
### ⚠️ Before submitting, please verify the following: ⚠️

- [x] This is a **bug**, not a question or a configuration issue.
- [x] This issue is **not** already reported on Github (I've searched it).
- [x] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

 Nextcloud UI (3.14.1) is completely broken in Windows 10 (21H2 19044.4894).
![Image](https://github.com/user-attachments/assets/d7824718-895a-44db-8deb-704595c608c4)

### Steps to reproduce

Read above

### Expected behavior

Not broke.

### Which files are affected by this bug

Nextcloud Desktop

### Operating system

Windows

### Which version of the operating system you are running.

Read above

### Package

Official Linux AppImage

### Nextcloud Server version

Not sure

### Nextcloud Desktop Client version

Read above

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 3.4.2 to 3.4.4)

### Are you using the Nextcloud Server Encryption module?

Encryption is Enabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Nextcloud Server logs

Client. No need for server logs.

**Comment by IT-VBFK** [comment] 2024-10-06 06:51
For me: if the Windows dark mode is enabled, the font color changes to white, but the background remains also white.

Windows light mode: seems to fix this...

**Comment by PeterTucker** [comment] 2024-10-06 09:38
Uggh. That's as much as a fix as switching to Dropbox.

**Comment by Leah96xxx** [comment] 2024-10-06 18:22
I tried downgrading and confirmed this bug also exists in 3.14.0. Downgrading further to 3.13.4 resolves it, so looks like the bug started in 3.14.0

**Comment by SnejPro** [comment] 2024-10-07 07:09
Can confirm this,

**Comment by bobobo-git** [comment] 2024-10-07 09:48
can confirm this too .. the darkmode (Systemsetting in Windows10) shows a nearly unusuable Mainwindow . the font color is lightgrey but the the background isn't dark but lighter grey too.
this shouldn't be too hard to fix i guess

**Comment by IT-VBFK** [comment] 2024-10-07 14:47
As this seems to be broken since 3.14.0 I guess it is somewhere around this PR: https://github.com/nextcloud/desktop/pull/4584

**Comment by mgallien** [comment] 2024-10-08 07:13
a quick update from my side
windows 11 light and dark mode are on their way to get a working release
feel free to test this build from the stable branch: https://cloud.nextcloud.com/s/7rm65tyMDLN4CkF
for windows 10, let's use this issue to track the bugs with dark mode (original report from @PeterTucker )
this is currently not working as Qt6 does not switch to dark palette when running on Windows 10 in dark mode
for background, you can read https://www.qt.io/blog/dark-mode-on-windows-11-with-qt-6.5
and sorry for the problems, we are working on it

**Comment by PeterTucker** [comment] 2024-10-08 14:20
@mgallien thank you. If you need someone to test any working dark mode build for Windows 10, feel free to reach out.

**Comment by Luatan** [comment] 2024-10-08 22:10
I have exactly the same issue, since the GUI was reworked.
Using the version 3.14.1

Windows 10 22H2 19045.4894

**Comment by bobobo-git** [comment] 2024-10-10 14:58
The decision to switch to Qt6 without checking the dependencies beforehand is annoying to say the least. Maybe it wasn't even widely known. Whatever the case, it's good that it's going to be fixed 👏 keep on doing the good stuff 😀

**Comment by mgallien** [comment] 2024-10-11 09:28
fixing this is now planned for the 3.14.2 milestone with release date planned for 17/10/2024

**Comment by AndyXheli** [comment] 2024-10-11 21:18
Same on Win 11 23H2 & 24H2

![Image](https://github.com/user-attachments/assets/6ebc538a-db31-4e26-970b-731324bc7d6a)

**Comment by x9t9** [comment] 2024-10-14 05:34
Same here .
Why not just dropp the layovers and leave a "Normal" win UI window ? 
Or at least give the user a choice without forcing any "decorations" that can be desired by one, and hated / buggy for others ?

**Comment by RuizuKun-Dev** [comment] 2024-10-24 08:15
![Image](https://github.com/user-attachments/assets/0e27d81b-e8b2-40b5-b18d-61584641937d)
this is unusable...

**Comment by PeterTucker** [comment] 2024-10-26 13:36
Any news on this?

**Comment by AndyXheli** [comment] 2024-10-26 14:18
Looks like it's fixed with 3.14.2

**Comment by xXFreeFunXx** [comment] 2024-10-29 18:26
Have the same problem, Win10 (22H2) 64x dark theme.
I have installed version 3.14.2.

**Comment by chmutoff** [comment] 2024-11-02 09:31
Same issue here on Windows 10. Switching windows theme to light fixes the issue. Let's hope that NextCloud will fix this issue soon.

**Comment by PeterTucker** [comment] 2024-11-06 23:46
Still broken.

**Comment by PeterTucker** [comment] 2024-11-12 23:09
Since we don't really know the timeline on this (and I see this is now a bug for 3.15), does anyone know the last working version of Nextcloud client? I'd like to downgrade my client. It's okay if it's light themed.

@Rello @claucambra

**Comment by Rello** [comment] 2024-11-13 06:58
Hello,

3.15 has mainly a technical reasons because there was an issue with the versioning in 3.14.
Depending on your urgency, if you can wait another week, you can save yourself the downgrade. we are testing the next version including the fix already internally

**Comment by PeterTucker** [comment] 2024-11-13 12:35
Definitely can wait the week. Good to know the 3.15 fix is on the way. Thanks for updating everyone. 👍

**Comment by pabloneruda1** [comment] 2024-11-17 12:01
This is really annoying, such a stupid bug. Is it really that hard to fix?

**Comment by Rello** [comment] 2024-11-17 13:15
Hi,
its a but in QT. we are currently testing an implemented workaround. stay tuned

**Closed** 2024-11-19 13:13 UTC
Labels: bug, design, os: :door: Windows, 4. to test, hotspot: visual
