### ISSUE TITLE
Attempt to overrite '/etc/Nextcloud/sync-exclude.lst' Linux/Debian

### ISSUE THREAD

**Issue by johansmitsnl** [nextcloud/desktop#1584] opened 2019-11-05 07:22 UTC
### Expected behaviour
Upgrade the package

### Actual behaviour
Halted

### Steps to reproduce
1. apt full-upgrade

### Client configuration
Client version: `2.6.0-1` -> `2.6.0-20191103.090619~eoan1`

Operating system: Debian Testing

OS language: NL

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From Nextcloud or distro) (Linux only): Debian

### Logs

```
Uitpakken van .../libnextcloudsync0_2.6.0-20191103.090619~eoan1_amd64.deb wordt voorbereid...
Bezig met uitpakken van libnextcloudsync0 (2.6.0-20191103.090619~eoan1) over (2.6.0-1) ...
dpkg: fout bij verwerken van archief /var/cache/apt/archives/libnextcloudsync0_2.6.0-20191103.0
90619~eoan1_amd64.deb (--unpack):
 poging tot overschrijven van '/etc/Nextcloud/sync-exclude.lst', wat ook in pakket nextcloud-de
sktop-common 2.6.0-1 zit
dpkg-deb: fout: subproces plakken werd gedood door signaal (Gebroken pijp)
Fouten gevonden tijdens verwerken van:
 /var/cache/apt/archives/libnextcloudsync0_2.6.0-20191103.090619~eoan1_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by agaida** [comment] 2019-11-14 00:27
ppa problem - not an upstream nor an downstream problem

**Comment by daveriedstra** [comment] 2019-11-22 22:55
Problem still persists. I think @ivaradi is the PPA maintainer?

**Comment by ivaradi** [comment] 2019-11-23 18:10
The problem is that you already have a Nextcloud client package installed from a different source, and there are some packaging differences. i.e. the file in question is in a package called `nextcloud-desktop` coming from that other source, but in the PPA version it is in a package with a different name, `libnextcloudsync0`. So it is best to uninstall the other package(s), if you want to use the PPA.

Where have you installed `nextcloud-desktop` from?

**Comment by johansmitsnl** [comment] 2019-11-23 18:21
To my knowledge I have always used the same source. I removed the package and installed them again and now it works. 
If it is now a upgrade concern from this PPA feel free to close it. I just reported it to warn that there might be something that other users might experience.

**Comment by ivaradi** [comment] 2019-11-23 18:27
@johansmitsnl  Do you mean that you have always used the PPA? That is strange, because there is no `nextcloud-desktop-common` package there and never has been.

**Comment by agaida** [comment] 2019-11-23 20:02
@ivaradi - maybe we should sync the debian and the ppa packaging. Otherwise maybe we should not. Period.

It's not the greatest of all ideas to mix ppa and regular repo versions. So what is happend here: I wanted to help a busy friend and packaged 2.6.0 and 2.6.1 - part of it was to add some missed files, sorry if the file in charge is in the wrong package. Nevermind, this could be changed, but the big but is:  For debian and derivatives debian is the only (first) packaging authority (in case a derivative change the packaging, in that case the derivative is the first authority for this derivative), any ppa is third party and not supported. And this goes as far as: If I'm the developer/uploader of an official package and i provide the same package as PPA - the PPA is third party and never will be supported nowhere - that's the deal. Only thing we could do is to prevent file conflicts.

**Comment by agaida** [comment] 2019-11-23 20:31
@ivaradi - i guess from the official repo :P  https://tracker.debian.org/pkg/nextcloud-desktop

**Comment by ivaradi** [comment] 2019-11-26 07:09
@agaida OK, I was not aware that an official package already exists :) 

Do you think that then the build scripts used for the official Debian and Ubuntu packages could be merged into the repo and used for the PPA as well? If there is an official version, the PPA makes sense only IMHO as a more cutting-edge version of the package, and it would be nice if upgrade (and downgrade) were seamless. Also, this way we could avoid duplicating work.

**Comment by agaida** [comment] 2019-11-26 19:12
@ivaradi - it will be in fact the only sane solution - ok, the ppa packages will need some Breaks: and Replaces: - but that should be easy and fine. (Maybe a Conflicts: instead of the Breaks: moved files between packages are not that nice.

**Comment by ivaradi** [comment] 2019-11-27 06:45
@agaida OK, so how do we go about it? :) If I am not mistaken, this is the Git repo used to build the official packages: https://salsa.debian.org/owncloud-team/nextcloud-desktop

It contains the `debian` directory in the root, but in this (the upstream) repository, such OS - and distribution-specific build files are in the `admin` directory (the Debian ones are under `admin/linux/debian`). Is it necessary to maintain a separate Git repository for the official builds, or could you use the upstream repository directly? Or perhaps automate the conversion from the upstream repo to the Debian one?

Also, the various supported Ubuntu releases require slightly different files (mainly the `control` files use somewhat different build dependencies). How do you solve that in an official package?

**Comment by agaida** [comment] 2019-11-27 11:13
well, good question - if you agree we could host the branches for the ppa's (and other things) in salsa - and it's only some code, nothing special, so we can introduce a workflow that fit you best. Disclaimer: I'm not only involved in debian, i'm upstream too so i know these problems :D 

Before i forget - this would include some maint. rights in this repo for you so we should plan and do this carefully

**Comment by agaida** [comment] 2019-11-27 22:37
@ivaradi - might sound nuts but a packaging dir would be one way to go - d/derivatives would not use it and it would be a fine upstream place to have these things at hand. And a big fat ReadMe.md in this special dir would help too. Ok - i don't know your workflow and if this one could fit.

**Comment by ivaradi** [comment] 2019-12-18 15:52
@agaida I had other stuff to do recently, but now I will hopefully have some time to work on the packaging again.

My workflow should be empty :), since I would like to automate of the build procedure as much as possible. Currently the Drone build runs the `admin/linux/debian/drone-build.sh` script. It basically runs a loop over the various distributions. In each iteration ot makes a copy of the git repo and then copies the contents of `admin/linux/debian` directory to the top-level directory of the copy of the repo. Then it copies the contents of the `admin/linux/debian.<distribution>` directory over the `debian` directory in the top-level one. Then it generates a changelog and builds a source package, which it later uploads.

Now, I am not really familiar with the official build procedure or the possibilities there. But perhaps `drone-build.sh` could update the Git repo on `salsa` and somehow trigger a build. Or the build on `salsa` could perform a similar copying operation and then perhaps the build script could at least partially be shared.

What do you think? Shall we discuss it here or via IRC? When my machine is up, I am logged into the freenode #lxqt channel.

**Comment by wurstbrot** [comment] 2020-01-01 18:38
Using Ubuntu 19.10 it happens on trying to perform `apt dist-upgrade`also:

> [...]
> Preparing to unpack .../libnextcloudsync0_2.6.2-20191224.111326~eoan1_amd64.deb ...
> Unpacking libnextcloudsync0 (2.6.2-20191224.111326~eoan1) over (2.5.3-1) ...
> dpkg: error processing archive /var/cache/apt/archives/libnextcloudsync0_2.6.2-20191224.111326~eoan1_amd64.deb (--unpack):
>  trying to overwrite '/etc/Nextcloud/sync-exclude.lst', which is also in package nextcloud-desktop-common 2.5.3-1
> dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
> Errors were encountered while processing:
>  /var/cache/apt/archives/libnextcloudsync0_2.6.2-20191224.111326~eoan1_amd64.deb
> E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by mgallien** [comment] 2021-05-20 07:42
@ivaradi Do you still plan to work on this or should we just close it ?
@johansmitsnl Is the problem still occurring for you ?

**Comment by ivaradi** [comment] 2021-05-20 08:03
I think it can be closed.

**Comment by mgallien** [comment] 2021-05-20 08:56
thanks @ivaradi

**Closed by mgallien** 2021-05-20 08:56 UTC
Labels: needs info
