### ISSUE TITLE
Maintain separate branches of desktop client

### ISSUE THREAD

**Issue by ostasevych** [nextcloud/desktop#7472] opened 2024-11-07 15:04 UTC
Hi! Taking into account new Qt features, and numerous complaints about the latest desktop client 3.14.x, while the version 3.13.4  remains the most stable I suggest to keep the 3.13.4 development separately thus to create two separate branches of the client: 3.13.x stable and 3.14.x unstable.

By now the desktop client is aggressively promoting self-update and I have lost hopes to find the way how to stop do it: each time after the reboot I have to stop the client and install 3.13.4 version manually.

**Comment by claucambra** [comment] 2024-11-08 05:02
Hi, this would seem like a duplicate of #7382 so I will close this issue, thank you!

**Closed by claucambra** 2024-11-08 05:02 UTC
Labels: 0. Needs triage, enhancement
