### ISSUE TITLE
Streamline internal file sharing with direct link to local, offline file (if available)

### ISSUE THREAD

**Issue by bbceg** [nextcloud/desktop#3559] opened 2021-07-16 09:10 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you want to have the same feature implemented.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Feature description
Hello,
I'm hoping to streamline the process of sharing files/folders internally. 

At present using 'Copy internal link' from the context menu requires the recipient of that link to open their browser and download the file/folder. In our case it's highly likely that the file/folder already exists on their filesystem. 

Could the internal link be "smart" enough to attempt to locate the file/folder on the filesystem (perhaps with the help of the sync client) and open it up if found? If not the link could go to the web interface as it does currently.

This would be particularly helpful for sharing cross-platform Windows<->Mac in our case.

I hope that makes sense but if anything's unclear, please let me know.

Thanks!

**Comment by mgallien** [comment] 2021-08-25 10:18
Thanks for your report.
This is a duplicate of https://github.com/nextcloud/desktop/issues/1321

**Closed by mgallien** 2021-08-25 10:18 UTC
Labels: enhancement
