### ISSUE TITLE
NC Desktop Windows crash at startup when server side is restructured

### ISSUE THREAD

**Issue by the-moog** [nextcloud/desktop#1150] opened 2019-03-19 11:06 UTC
### Expected behaviour
Nextcloud should start and then sync

### Actual behaviour
Nextcloud crashes on sync, sync connections have a "File or directory not found" error, even though the sync directory is present and has NC control files in it.
In fact the server side folder had been moved.
Deleting sync connections to 'missing' sync folders prevents crash at startup.

### Steps to reproduce
1. PC1: close NC
2. PC2: restructure folders in NC
3. PC1: open NC which will then crash at startup

### Client configuration
Client version:
2.5.1final (build 20181204)

Operating system:
Windows 10

OS language:
English (Bristish)

Installation path of client:
C:\Program Files (x86)\Nextcloud

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

1. Client logfile: Output of `nextcloud --logwindow` or `nextcloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the Nextcloud directory)
(See also https://docs.nextcloud.com/desktop/2.3/troubleshooting.html#log-files)
Fixed issue before running with logging.

2. Web server error log:

3. Server logfile: nextcloud log (data/nextcloud.log):

**Comment by s1242001** [comment] 2019-04-11 06:45
issue is still in windows 10 client 2.5.2

**Comment by mgallien** [comment] 2021-06-01 06:50
Can you test if you can reproduce with the latest version ?
If the issue is fixed, can you close the issue ?

**Comment by w-e-w** [comment] 2021-06-18 01:31
can't remember the details of this bug, but I tried and failed to reproduce this bug with the current stable version, (at least no crashes)
Windows Client 3.2.2 with Nextcloud 21.0.2
I belive this has been fixed durning the past 2+ years

**Comment by FlexW** [comment] 2021-06-18 07:21
Thanks @w-e-w

**Closed by FlexW** 2021-06-18 07:21 UTC
Labels: bug
