### ISSUE TITLE
Eyery Text is "Benötigt keine Übersetzung, hier wird nur die formelle Übersetzung verwendet (de-DE)"

### ISSUE THREAD

**Issue by Neuroplant** [nextcloud/desktop#5348] opened 2023-01-20 06:56 UTC
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

Since todays update eyery Text is "Benötigt keine Übersetzung, hier wird nur die formelle Übersetzung verwendet (de-DE)"

### Steps to reproduce

1. Seit Language to German (Germany)
2. update Desktop Client

### Expected behavior

Translated Text

### Which files are affected by this bug

no

### Operating system

Windows

### Which version of the operating system you are running.

Windows 11 (22H2)

### Package

Other

### Nextcloud Server version

Nextcloud Hub 3 (25.0.3)

### Nextcloud Desktop Client version

(all menues "Benötigt keine Übersetzung, hier wird nur die formelle Übersetzung verwendet (de-DE)")

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 3.4.2 to 3.4.4)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by Neuroplant** [comment] 2023-01-20 06:56
![next](https://user-images.githubusercontent.com/25515618/213635910-2289168d-cb64-4233-9c01-048ee0dbcdc9.png)

**Comment by nstatrm** [comment] 2023-01-20 07:15
I have the exact same issue after an update today. The app language is also set to German.

**Comment by LeopoldVInfinite** [comment] 2023-01-20 07:44
we had the same bug last year in talk-android
https://github.com/nextcloud/talk-android/issues/2507

**Comment by danielscherzer** [comment] 2023-01-20 08:04
Same bug here.

**Comment by MarcelRei** [comment] 2023-01-20 08:07
Same issue with the last macOS update

**Comment by Scheuerschrauber** [comment] 2023-01-20 08:52
Same here - Windows App - set to german

**Comment by bpunktm** [comment] 2023-01-20 09:04
I got the same Bug here (Windows 10 Pro). What should I do?
![bug_1](https://user-images.githubusercontent.com/32487776/213656789-dbf437b6-8e00-4c46-9701-1029ead4b3e8.png)
![bug_2](https://user-images.githubusercontent.com/32487776/213656795-56859186-73da-43ae-b0b8-68370eb0e920.png)
![bug_3](https://user-images.githubusercontent.com/32487776/213656797-86edf788-8b02-4a3d-8431-f492f7cb3364.png)

**Comment by Dentling** [comment] 2023-01-20 09:08
This is a duplicate of https://github.com/nextcloud/desktop/issues/5339

As mentioned in https://github.com/nextcloud/desktop/issues/5339 version 3.6.6 will be released today with a fix for this issue.

**Comment by Dentling** [comment] 2023-01-20 09:09
> This is a duplicate of #5339
> 
> As mentioned in #5339 version 3.6.6 will be released today with a fix for this issue.

Actually the version 3.6.6 with the fix got released 3 minutes ago.

**Comment by Neuroplant** [comment] 2023-01-20 09:17
> This is a duplicate of #5339
> 
> As mentioned in #5339 version 3.6.6 will be released today with a fix for this issue.

Except this is about the Windows Client not the MacOS one

**Comment by allexzander** [comment] 2023-01-20 09:19
duplicate of https://github.com/nextcloud/desktop/issues/5339

**Closed by allexzander** 2023-01-20 09:19 UTC
Labels: 0. Needs triage

**Comment by camouflage81** [comment] 2023-02-09 20:24
Hi guys, have the same problem.

I just did the latest update (3.7.2) of the Windows client.
For me it also only shows "Benötigt keine Übersetzung...".
All users also have the problem (Windows 10 and 11).
Also newly installed clients bring the same text.

Thanks and greetings

**Comment by Haituga** [comment] 2023-02-21 07:21
Please reopen this issue. This bug is still present in 3.7.2.
![grafik](https://user-images.githubusercontent.com/24953980/220275337-e87ae64b-21c1-4aa1-afed-ef18d57453dc.png)
