### ISSUE TITLE
[Bug]: Main window not showing up

### ISSUE THREAD

**Issue by filemon11** [nextcloud/desktop#7123] opened 2024-09-14 20:37 UTC
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

The main window does not appear with client from the development PPA https://launchpad.net/~nextcloud-devs/+archive/ubuntu/client
Clicking on the bar icon shows a menu with four entries:  Open main window, settings, Help, Close Nextcloud (translated from German). Clicking on Open main window does not have any effect.

### Steps to reproduce

1. sudo add-apt-repository ppa:nextcloud-devs/client
2. sudo apt update
3. sudo apt install nemo-nextcloud
4. Click on the bar icon

### Expected behavior

When clicking on Open main menu the main nextcloud window should show up.

### Which files are affected by this bug

?

### Operating system

Linux

### Which version of the operating system you are running.

Budgie 10.9.1, Ubuntu 24.04.1 LTS

### Package

Official Linux AppImage

### Nextcloud Server version

29.0.5

### Nextcloud Desktop Client version

3.14.0

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Enabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Additional info

Client logs:
[20240914_2235_nextcloud.log.0.txt](https://github.com/user-attachments/files/17003741/20240914_2235_nextcloud.log.0.txt)

**Comment by mgallien** [comment] 2024-09-15 09:14
@ivaradi you may want to check it

**Comment by UnderEu** [comment] 2024-09-15 11:44
Same thing with MATE Desktop - Ubuntu 22.04

**Comment by PhMetzger** [comment] 2024-09-15 13:14
Same here - Ubuntu 22.04.5 LTS
If it can help, I had to install qt6-qpa-plugins package to avoid crash at startup with 3.14

**Comment by MiZoG99** [comment] 2024-09-15 13:35
Same on Linux Mint 22 Cinnamon.
"Open Main dialog" does not work.
though "Settings"  is still accessible.

**Comment by StrangeNoises** [comment] 2024-09-15 14:23
same on Ubuntu (vanilla) 24.04.1 (using wayland) nextcloud-desktop 3.14.0 installed from nextcloud-devs ppa. noted this upgrade last night also upgrading from depending on qt5 to qt6. Settings dialog works (and looks sharp in this fractional scaling mode), but main dialog doesn't open. I get a spinner for the mouse pointer for a bit when I try. Tried logout/login, made no difference.

**Comment by meonkeys** [comment] 2024-09-15 17:15
I upgraded today, and after I tried to run nextcloud from the command line, I saw:

```
qt.qpa.plugin: Could not find the Qt platform plugin "xcb" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Aborted
```

Fix, as mentioned by @PhMetzger above, worked for me: `sudo apt install qt6-qpa-plugins`.

I'm using the desktop client from the [nextcloud-devs ppa](https://launchpad.net/~nextcloud-devs/+archive/ubuntu/client) on Ubuntu 22.04 LTS 64-bit desktop.

**Comment by michnovka** [comment] 2024-09-16 10:05
Same issue on Kubuntu 22.04, here is debug log:
```
superuser@superuser-X570S:~$ export QT_DEBUG_PLUGINS=1
superuser@superuser-X570S:~$ nextcloud
QFactoryLoader::QFactoryLoader() checking directory path "/usr/lib/x86_64-linux-gnu/qt6/plugins/platforms" ...
QFactoryLoader::QFactoryLoader() checking directory path "/usr/bin/platforms" ...
qt.qpa.plugin: Could not find the Qt platform plugin "xcb" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Aborted (core dumped)
```

**Comment by michnovka** [comment] 2024-09-16 10:18
P.S. a workaround seems to be to install

```
sudo apt install qt6-base-dev
```

Then it works

**Comment by ivaradi** [comment] 2024-09-16 10:29
The package dependencies were not updated properly from Qt5 to Qt6, so several packages were possibly missing after installation. This is fixed now, and the current packages in the PPA should work properly.

**Comment by michnovka** [comment] 2024-09-16 10:36
@ivaradi  Can you please share for reference the version which is fixed? I see as latest `3.14.0-20240914.150754.d8fcb9273-1.0~jammy1` and this one is not

**Comment by ivaradi** [comment] 2024-09-16 10:47
@michnovka  the fixed version is `3.14.0-20240916.085658.d8fcb9273-1.0~jammy1`

**Comment by StrangeNoises** [comment] 2024-09-16 10:54
confirmed, that fixes it for me

**Comment by mwildam** [comment] 2024-09-16 12:03
I can also confirm that `3.14.0-20240916.085658.d8fcb9273-1.0~jammy1` fixes the issue. Thanks for the quick solution.

**Comment by michnovka** [comment] 2024-09-16 12:19
Yes, confirmed too

**Comment by mgallien** [comment] 2024-09-16 13:26
@ivaradi thanks for the fixes and your packaging work.
closing the issue given the feedback

**Closed by mgallien** 2024-09-16 13:26 UTC
Labels: 0. Needs triage

**Comment by mwildam** [comment] 2024-09-16 20:16
@StefInP , reopen for me did not work, neither delete caches. Did you try starting "nextcloud" from the commandline? Errors are shown on the console. I definitely had this issue here which is solved as mentioned - with the latest update (from the nextcloud repository https://ppa.launchpadcontent.net/nextcloud-devs/client/ubuntu/).

**Comment by mwildam** [comment] 2024-09-17 07:32
@StefInP , there should be no difference here - Open the terminal and just type "nextcloud" and enter.

**Comment by fsyamala** [comment] 2024-09-18 05:32
Same problem with Windows 11 Pro 23H2 OS built 22631.4169.
Thank you.

**Comment by nyroDev** [comment] 2024-09-19 07:03
> The package dependencies were not updated properly from Qt5 to Qt6, so several packages were possibly missing after installation. This is fixed now, and the current packages in the PPA should work properly.

Is it possible to also update the downloadable appimage on nextcloud website please?
Or is there a link where to download the correct appimage?
I'm facing the exact same issue with missing glib.
