### ISSUE TITLE
Nextcloud 3.3.6 - Windows Context Menu in english instead of german

### ISSUE THREAD

**Issue by kangaroo72** [nextcloud/desktop#4007] opened 2021-11-26 22:08 UTC
Hi,

since a long time I've recognized, that the context menu from Nextcloud Desktop (Windows) appears in english.
The operating system is Windows 10 or 11 in german. See screenshot.

![grafik](https://user-images.githubusercontent.com/6906390/143658101-45565c8f-e462-4351-b73f-54dde3bfb1bc.png)

Thank you

**Comment by allexzander** [comment] 2021-12-09 12:59
Duplicate of https://github.com/nextcloud/desktop/issues/3140

**Closed by allexzander** 2021-12-09 12:59 UTC
Labels: bug, feature: :tongue: language l10n and translations
