### ISSUE TITLE
[Bug]: V3.13.1 - Multiple 0X8007017C errors: The cloud Operation is invalid

### ISSUE THREAD

**Issue by vagner-dias** [nextcloud/desktop#6876] opened 2024-07-03 14:08 UTC
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

After updating NC to V 3.13.1, some clients started to have the error below:

0X8007017C: The cloud Operation is invalid

![explorer_1ET6EBN7dC](https://github.com/nextcloud/desktop/assets/86367839/0ce93a00-ae38-4282-9800-40352283310a)

Our environment:
Windows 10 + Windows 11 Clients
Desktop client: 3.13.1
NC 28.0.6
FIles Lock: 28.0.6
Group Folders: 16.0.7

### Steps to reproduce

Try to open any vfs file after updating the client.

### Expected behavior

this error should not happen

### Which files are affected by this bug

any file

### Operating system

Windows

### Which version of the operating system you are running.

Windows 11 + Windows 10

### Package

Distro package manager

### Nextcloud Server version

28.0.6

### Nextcloud Desktop Client version

3.13.1

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by Mika-6-9** [comment] 2024-07-03 15:03
Idem with 3.13.1 and Windows 11
![image](https://github.com/nextcloud/desktop/assets/82665005/5a86029b-baf6-4e24-b317-b261136688a5)
This is valid for non synchronized files ![image](https://github.com/nextcloud/desktop/assets/82665005/f5bf117a-b295-47d2-a28f-b6390c0fe7dc) and not all the time

**Comment by Digifyseocom** [comment] 2024-07-04 19:57
Seeing the same issue starting 3.13.1 however it fixed with downgrading to 3.12.2

**Comment by ServiceType** [comment] 2024-07-05 07:11
Same here.
The problem is not present for all files.
Few of the affected files can be opened at the second try.
The other files start working again after restarting the syncclient.

**Comment by joEgger** [comment] 2024-07-05 09:38
Same here.
Error 0x8007017C with uptodate Server and DesktopClient

**Comment by Myuuiii** [comment] 2024-07-05 10:37
Same here, running docker image `nextcloud:production-apache` and client `3.13.1`, as stated in an earlier comment, downgrading the client to `3.12.2` fixes the issue, at least for me

**Comment by supern64** [comment] 2024-07-05 13:49
Ditto on 3.13.1 and Windows 11. It seems smaller files (~40KB) don't get this error, while anything beyond 1MB doesn't work at all. (I get ~2MB/s speeds on download)

**Comment by AT-StephenDetomasi** [comment] 2024-07-08 01:48
Does anyone know if this error occurs on folders that have offline sync enabled?

**Comment by vagner-dias** [comment] 2024-07-08 11:26
> I created this build based on my PR #6885: https://cloud.nextcloud.com/s/bRFYRD9kJDJYd9J It didn't fix my error, but you could try and see how it behaves for you. This is a test, so please test with a test account and test user.

HI.  I ran some tests using your image on small (1kb), medium (6kb~50mb) and huge (6GB) files. It works flawlessly

**Comment by vagner-dias** [comment] 2024-07-08 14:21
> > HI. I ran some tests using your image on small (1kb), medium (6kb~50mb) and huge (6GB) files. It works flawlessly
> 
> great to hear, I am releasing the fix in 3.13.2 in a few hours. thanks for the feedback.
> 
> If anyone else has more info/feedback on this, please, still update the issue. We have seen this before, but we are not 100% sure on how to trigger this error. The root cause of this seems to vary.

How can I test the "current" 3.13.2 release to see if I can find any additional errors?

**Comment by vagner-dias** [comment] 2024-07-08 19:21
> I created this build based on my PR #6885: https://cloud.nextcloud.com/s/bRFYRD9kJDJYd9J It didn't fix my error, but you could try and see how it behaves for you. This is a test, so please test with a test account and test user.

 @Mika-6-9 @Digifyseocom @ServiceType @joEgger @Myuuiii @supern64 

Maybe you can test this patch as well? the more people we have to test the more likely the fix will not go sideways

**Comment by Mika-6-9** [comment] 2024-07-09 07:35
Hi.
What is the minimum server version you need to have to use this version of the client (windows-20240709.msi). I have two accounts with two different server versions (V27 and V24). The client closes by itself a few seconds after startup. I have the impression that it is the oldest server that is causing problems.

**Comment by supern64** [comment] 2024-07-09 14:08
Can confirm 3.13.2 fixes the issue for me.

**Comment by vagner-dias** [comment] 2024-07-09 16:08
3.13.2 is working here. I can rename files and folders normally and open then when they are in vfs mode 

THANK YOU, @camilasan !

**Closed** 2024-07-09 16:08 UTC
Labels: 0. Needs triage
