### ISSUE TITLE
Unrendered HTML in macOS update notifications

### ISSUE THREAD

**Issue by willvousden** [nextcloud/desktop#3005] opened 2021-03-14 11:22 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour
When an update is available, I should get a nicely formatted macOS notification with a clickable link.

### Actual behaviour
The notification has unrendered HTML in it:

<img width="345" alt="Screenshot 2021-02-24 at 20 31 15" src="https://user-images.githubusercontent.com/152388/111066450-71ee6180-84bf-11eb-8511-3d7098d7913b.png">

### Steps to reproduce
1. Install an old version of Nextcloud (e.g., 3.1.2)
2. Wait for the update notification to appear

### Client configuration
Client version: 3.1.2 (by its very nature this problem cannot be observed on the latest version)

Operating system: macOS Big Sur 11.2.2

OS language: English (UK)

Installation path of client: `/usr/local/Caskroom/nextcloud/3.1.2` (via Homebrew)

### Logs

I haven't included logs here because this issue is really tedious to reproduce, and I don't think they will help anyway. I can add them if they are really needed.

**Comment by danielcotton** [comment] 2021-03-15 02:58
I believe this is a duplicate of #2200

**Comment by FlexW** [comment] 2021-03-15 08:06
Thanks @danielcotton. Closing this as it is a duplicate of #2200.

**Closed by FlexW** 2021-03-15 08:06 UTC
