### ISSUE TITLE
Virtual file cannot be used

### ISSUE THREAD

**Issue by AP0rPi7uQ9** [nextcloud/desktop#3230] opened 2021-04-29 01:54 UTC
Use virtual files. Unable to sync successfully.

Client
Nextcloud desktop v3.2.0

System
Windows 10 20H2
English

Server
Docker nextcloud 21.0.0

Display:
Nextcloud client show “Error writing metadata to database"

**Comment by FlexW** [comment] 2021-04-29 07:05
Duplicate of #3158

**Closed by FlexW** 2021-04-29 07:05 UTC
Labels: bug
