### ISSUE TITLE
[Bug]: Please do NOT reboot Windows automatically after update. Please ASK USER before doing so. Don't tell this is mandatory to automatically reboot after install, this is not. You are the ONLY app in the market to do so. If user doesn't want to rebbot "NOW" this is his choice and he will have to live with NextCloud not available until next reboot. Don't tell this is just new, it's been around since THREE versions and this is just ONE line of code to add. MANY THANKS

### ISSUE THREAD

**Issue by bonac** [nextcloud/desktop#4883] opened 2022-09-01 23:05 UTC
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

The share dialog is looking incomplete.
...
[Bug]: Please do NOT reboot Windows automatically after update.
Please ASK USER before doing so.
Don't tell this is mandatory to automatically reboot after install, this is not. You are the ONLY app in the market to do so.
If user doesn't want to reboot "NOW" this is his choice and he will have to live with NextCloud not available until next reboot.
Don't tell this is just new, it's been around since THREE versions and this is just ONE line of code to add. MANY THANKS
sorry to be upset, but this is really upseting to have everything closed immediately, + pC not available for a few minutes.

### Steps to reproduce

1. update nextcloud

### Expected behavior

ASK user before rebooting.

### Which files are affected by this bug

PC rebooted

### Operating system

Windows

### Which version of the operating system you are running.

Windows 10

### Package

Appimage

### Nextcloud Server version

doesn't affect bug

### Nextcloud Desktop Client version

3.5.4

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 3.4.2 to 3.4.4)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [X] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by claucambra** [comment] 2022-09-02 09:06
Duplicate of #3551 and already fixed since 3.5.4. Closing

**Closed by claucambra** 2022-09-02 09:06 UTC
Labels: 0. Needs triage

**Comment by r2evans** [comment] 2022-09-07 10:42
This is a dupe, sure, but _"fixed since 3.5.4"_ is patently untrue: it has rebooted for each version up through and including 3.6.0.

If you're going to say that it's fixed, at least say **in a future release**, as cited in a [comment over 5 weeks ago](https://github.com/nextcloud/desktop/issues/3551#issuecomment-1200101476), still not released.
