### ISSUE TITLE
CMake analyze results in out of memory exception

### ISSUE THREAD

**Issue by MaDua** [nextcloud/desktop#527] opened 2018-08-02 12:20 UTC
Hi,

when I open the desktop folder with Visual Studio 2017 (as described here: https://github.com/nextcloud/desktop/wiki/How-to-run-the-desktop-client-on-Visual-Studio) it takes quite a long time while CMake analyzes all the CMakeList.txt´s. After about 1 hour, I get an Out of Memory Exception in the console.

Can anyone tell me if it is correct that it takes so long to analyze and why the exception occurs?

Thank you in advance

**Comment by camilasan** [comment] 2018-08-03 17:11
Hi! Sorry but I didn't experience this with VS and it doesn't take too long to open the project.

**Comment by MaDua** [comment] 2018-08-06 09:16
Alright thank you, Can you tell me than if the correct desktop folder to right click open with VS (first step on: https://github.com/nextcloud/desktop/wiki/How-to-run-the-desktop-client-on-Visual-Studio) is the folder that is checked out from git under https://github.com/nextcloud/desktop.git?
I was wondering if that is correct because inside that folder are the folders branches, logs and trunk and it seems that VS tries to analyze all the CMakeList.txt files in all the branches and the trunk, but I actually need only one "project" opened and build with VS.
So which is the correct folder to right click and open with VS? There is no other "desktop" folder in the checked out repository.

Thank you

**Comment by camilasan** [comment] 2018-08-06 12:33
> the correct desktop folder to right click open with VS (first step on: https://github.com/nextcloud/desktop/wiki/How-to-run-the-desktop-client-on-Visual-Studio) is the folder that is checked out from git under https://github.com/nextcloud/desktop.git?

yes, that is correct.

> I was wondering if that is correct because inside that folder are the folders branches, logs and trunk and it seems that VS tries to analyze all the CMakeList.txt files in all the branches and the trunk, but I actually need only one "project" opened and build with VS.

The rest is included using:
include_directories(
    ${CMAKE_CURRENT_SOURCE_DIR}/src
    ${CMAKE_CURRENT_BINARY_DIR}/src
)

and then in src/CMakeLists.txt:
add_subdirectory(gui)

and so on...

Did you try other ways of building the client? I mean cmake will generate the VS project files... when I opened the desktop client on VS I already had run cmake in the build folder and had successfully compiled it via command line (Git Bash) - see https://github.com/nextcloud/desktop/wiki/How-to-compile-the-desktop-client#32-windows. Maybe that makes a difference? 
I am sorry but my experience with VS only goes so far...

**Comment by MaDua** [comment] 2018-08-09 06:29
Ok thank you very much, that helps me.

But I have to ask if I have to adjust anything in any of the CMakeList.txt files or can I use them as I checked them out?.

The next thing is that I am not sure if I use the correct CMake.exe. I use it from C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\.

On this exe I used the command:
cmake -G "Visual Studio 15 2017 Win64" .. -DCMAKE_INSTALL_PREFIX=C:\...\Nextcloud\install/ -DCMAKE_BUILD_TYPE=Debug -DNO_SHIBBOLETH=1

In which folder I have to navigate to run the cmake command? is ...\trunk\src\cmd correct? I ask this because otherwise I get the error that there is no CMakeList.txt in the folder.

When I run this command I get the error:
CMake Error at C:/.../Qt/5.11.1/winrt_x64_msvc2017/lib/cmake/Qt5/Qt5Config.cmake:28 (find_package):
Could not find a package configuration file provided by
"Qt5WebEngineWidgets" with any of the following names:

Qt5WebEngineWidgetsConfig.cmake
qt5webenginewidgets-config.cmake

Add the installation prefix of "Qt5WebEngineWidgets" to CMAKE_PREFIX_PATH
or set "Qt5WebEngineWidgets_DIR" to a directory containing one of the above
files. If "Qt5WebEngineWidgets" provides a separate development package or
SDK, be sure it has been installed.

I found out that I need the qtwebengine which I downloaded from here:
https://download.qt.io/official_releases/qt/5.6/5.6.0/submodules/

But this not contains a Qt5WebEngineWidgetsConfig.cmake or qt5webenginewidgets-config.cmake.

So I found out that my original Qt installation contains a Qt5WebEngineWidgetsConfig.cmake file.in
C:\...\Qt\5.11.1\msvc2017_64\lib\cmake\Qt5WebEngineWidgets
Now I added to my cmake command the CMAKE_PREFIX_PATH:
cmake -G "Visual Studio 15 2017 Win64" .. -DCMAKE_INSTALL_PREFIX=C:\...\Nextcloud\install/ -DCMAKE_PREFIX_PATH=C:\...\Qt\5.11.1\msvc2017_64\lib\cmake\Qt5WebEngineWidgets -DCMAKE_BUILD_TYPE=Debug -DNO_SHIBBOLETH=1

But this still gets me the same error.

The second option to set the Qt5WebEngineWidgets_DIR confuses me a bit because I don't know where to find this or even how to set it.

Hope you can understand my problem.

Thank you

**Comment by piojo86** [comment] 2018-12-21 11:59
You need to enter the entry in the right way 

-DCMAKE_PREFIX_PATH=C:...\Qt\5.11.1\msvc2017_64\lib\cmake ( without the folder Qt5WebEngineWidgets  ).

cya.

**Comment by piojo86** [comment] 2018-12-21 12:01
You need to enter the entry in the right way :

-DCMAKE_PREFIX_PATH=C:...\Qt\5.11.1\msvc2017_64\lib\cmake ( without the folder in the end ).

Cya.

**Comment by mgallien** [comment] 2021-05-05 07:57
Closing this issue because this is not a bug and not a feature request.
If you still have issues compiling please have a look at documentation and ask on other forum https://help.nextcloud.com/

**Closed by mgallien** 2021-05-05 07:57 UTC
Labels: os: :door: Windows
