### ISSUE TITLE
NC Client Mac 3.1 doesn't start under macOS 11.1 anymore

### ISSUE THREAD

**Issue by dh-connect** [nextcloud/desktop#2738] opened 2020-12-17 18:02 UTC
### Expected behaviour
Client starts normal

### Actual behaviour
Client starts for 1 second and crashes.
Also tried NC client 3.0.3 same behaviour, crash started after macOS upgrade from 11.0.1 to 11.1
All other clients such as Windows clients 3.1 work normal.

### Steps to reproduce
1. Starting NC client

### Client configuration
Client version: 3.1

Operating system: macOS 11.1

OS language: DE

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From Nextcloud or distro) (Linux only):

Installation path of client:

### Server configuration
Nextcloud version: 20.0.4

Storage backend (external storage): no

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile: 
[log.txt](https://github.com/nextcloud/desktop/files/5711275/log.txt)

2. Web server error log:

3. Server logfile: nextcloud log (data/nextcloud.log):

**Comment by dkoeh** [comment] 2020-12-18 08:01
Sounds like #2727 and #2710

**Comment by er-vin** [comment] 2020-12-21 07:28
Yes, sounds very much like a duplicate of #2710 I would need the actual backtrace of the crash to confirm it though.

**Comment by Korsani** [comment] 2020-12-21 12:32
Hi there,
Same problem here : nc 3.1.0, macos 11.1
Here is my crash report : 

[nextcloud_2020-12-21-132445_Moustache.crash.txt](https://github.com/nextcloud/desktop/files/5724294/nextcloud_2020-12-21-132445_Moustache.crash.txt)

**Comment by wcherry** [comment] 2020-12-21 15:40
Tickets #2710 & #2713 have been closed and #2713 had a PR and a new app image posted for it.  What is the process to do the same for MacOS (PR and/or build)?

**Comment by er-vin** [comment] 2020-12-21 16:20
> Hi there,
> Same problem here : nc 3.1.0, macos 11.1
> Here is my crash report :
> 
> [nextcloud_2020-12-21-132445_Moustache.crash.txt](https://github.com/nextcloud/desktop/files/5724294/nextcloud_2020-12-21-132445_Moustache.crash.txt)

Yes, duplicate of #2710 indeed in your case. I'll wait a bit to get the same confirmation from @dh-connect before closing.

**Comment by er-vin** [comment] 2020-12-21 16:21
> Tickets #2710 & #2713 have been closed and #2713 had a PR and a new app image posted for it. What is the process to do the same for MacOS (PR and/or build)?

Unfortunately we don't have the same mechanism for MacOS to have one build per PR so waiting for 3.1.1 will be required. Will be out soon though.

**Comment by dh-connect** [comment] 2020-12-21 19:53
here's my crash report. 
[crash report.txt](https://github.com/nextcloud/desktop/files/5726215/crash.report.txt)

**Comment by er-vin** [comment] 2020-12-22 06:49
Yep, indeed a duplicate of #2710 closing this one.

**Closed by er-vin** 2020-12-22 06:49 UTC
Labels: bug
