### ISSUE TITLE
Nextcloud Client on Windows 7 fails to start

### ISSUE THREAD

**Issue by gadgetguy08** [nextcloud/desktop#1692] opened 2019-12-21 16:29 UTC
# Expected behaviour
Start Nextcloud client and have it start.

### Actual behaviour
Start Nextcloud client and it crashes

### Steps to reproduce
1. Install Nextcloud Client for Windows 2.6.1
2. Attempt to start.
3. Crash reported in Windows Application Event log

### Client configuration
Client version:
2.6.1

Operating system:
Windows 7

OS language:
English

Installation path of client:
C:\Program Files\Nextcloud\nextcloud.exe

### Server configuration

Nextcloud version:

Storage backend (external storage):

### Logs

Windows App Log:
Faulting application name: nextcloud.exe, version: 2.6.1.6017, time stamp: 0x5dc0b373
Faulting module name: atio6axx.dll, version: 6.14.10.9606, time stamp: 0x4b7374ac
Exception code: 0xc0000005
Fault offset: 0x0000000000d1cd83
Faulting process id: 0xc88
Faulting application start time: 0x01d5b815ef5f27a2
Faulting application path: C:\Program Files\Nextcloud\nextcloud.exe
Faulting module path: C:\Windows\system32\atio6axx.dll
Report Id: 2ec41115-2409-11ea-9af4-90fba68a446d

1. Client logfile: 
Unable to obtain.  App doesn't start.

The app was working on version 2.5.1 and stopped when upgrading to 2.6.0.  Upgraded to 2.61 and still failed.  Rolled back to 2.5.1 and would no longer start on that either.  Always shows the same Faulting Module name.

Only changes to environment were Microsoft Security Patches.

**Comment by misch7** [comment] 2019-12-21 18:21
This seems to be a duplicate of #1279.

> Faulting module name: atio6axx.dll

This crash is related to your system's graphics drivers. We've upgraded to Qt 5.12.5 in version 2.6.0 so chances are, there's some incompatibility with your graphic drivers. Please update them and try again.
If that doesn't work then you can only try it on another machine / a freshly installed system on the same machine, or wait until we do the next Qt upgrade which my solve the issue.

**Closed by misch7** 2019-12-21 18:21 UTC
