### ISSUE TITLE
Unable to install client on macOS Catalina

### ISSUE THREAD

**Issue by JezzerPreston** [nextcloud/desktop#1514] opened 2019-10-15 16:01 UTC
### Expected behaviour
Downloaded latest macOS client and double clicked package file. Would expect client to be installed

### Actual behaviour
Installation stops with the following error:
“Nextcloud-2.6.0.20190927.pkg” can’t be opened because Apple cannot check it for malicious software.

![Screenshot 2019-10-15 at 16 59 09](https://user-images.githubusercontent.com/56600641/66848510-230c6780-ef6d-11e9-9da5-679890d3be54.png)

### Steps to reproduce
1. Download latest macOS installer package
2. On Mac running macOS 10.15 Catalina try to install the client
3. Installer stops with error

### Client configuration
Client version:  2.6.0.20190927

Operating system:

OS language: macOS 10.15 Catalina

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From Nextcloud or distro) (Linux only):

Installation path of client:

### Server configuration

Nextcloud version:

Storage backend (external storage):

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile: Output of `nextcloud --logwindow` or `nextcloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the Nextcloud directory)
(See also https://docs.nextcloud.com/desktop/2.3/troubleshooting.html#log-files)

2. Web server error log:

3. Server logfile: nextcloud log (data/nextcloud.log):

**Comment by tflidd** [comment] 2019-10-16 06:11
Duplicate of https://github.com/nextcloud/desktop/issues/1490

**Comment by rakekniven** [comment] 2019-10-16 08:53
Not sure if this is a dup. Providing a dmg was discussed in the past. Can you install finder extensions with an dmg? Remember some threads back in these oc times.

**Comment by tflidd** [comment] 2019-10-16 21:34
Perhaps I was a bit too fast. At least as a packaging issue with OS X, they are a bit related. Preferably, we manage to fix all these issues ;-)

**Comment by misch7** [comment] 2019-10-19 00:40
Hey,

we've just released 2.6.1 RC1 which is built with Qt 5.12.5 on all platforms (also has OpenSSL 1.1.1d, so it features TLS 1.3).

You may give it a try:
https://github.com/nextcloud/desktop/releases/tag/v2.6.1-rc1

I'm working on new build scripts and so I also updated the packaging tool used to build the installer. Perhaps it has solved this issue? :)

**Comment by JezzerPreston** [comment] 2019-10-19 10:29
Hi There....have just downloaded that latest release and tried to install in on macOS Catalina....same problem unfortunately. I'm afraid I am not expert and I'm sure you probably know this, but with the release of macOS 10.15 I think that all apps and installers now MUST be signed by Apple before they can get past the Gatekeeper software....there is no way to say 'yes I trust this developer, let me install his software' anymore.

As an aside, I updated one of my Macs to Catalina which had the Nextcloud client already installed and this is running just fine....you just can't perform a fresh installation of the client on 10.15 at the moment.

**Comment by rakekniven** [comment] 2019-10-19 10:44
@JezzerPreston 
Not sure if this is correct. Please see https://www.wikihow.com/Install-Software-from-Unsigned-Developers-on-a-Mac

**Comment by JezzerPreston** [comment] 2019-10-19 15:45
Ah! Thanks for that Terminal hack....that seems to have worked! Installs and works as expected on macOS 10.15. Not sure everyone would feel happy to completely turn off Gatekeeper from the terminal though!

**Comment by rakekniven** [comment] 2019-10-19 16:14
No, don't do that in general.
Method 1 - Step 1 to 10 should do the job for Nextcloud installer.
Turning off Gatekeeper is not an option IMHO:

**Comment by camilasan** [comment] 2019-10-23 14:12
Thanks @rakekniven, we will look into how to update our pkg.
Let us know @JezzerPreston if you have any further issues!

**Comment by gt-h6k** [comment] 2019-10-31 03:29
Probably need notarization.
For your reference, It has been fixed in owncloud.

[[macOS] Prepare notarization #7007](https://github.com/owncloud/client/pull/7007)

**Comment by misch7** [comment] 2019-11-07 18:26
@gt-h6k Thanks for pointing this out.

We're tweaking our build systems to handle that automatically in the future and will notarize the existing releases as soon as time allows it.

**Comment by misch7** [comment] 2019-11-18 10:01
Notarization works now, I just managed to set-up a Catalina machine to test it :-)

Please use our notarized 2.6.1 release, its bug fixes are worth skipping 2.6.0:
https://download.nextcloud.com/desktop/releases/Mac/Installer/Nextcloud-2.6.1.20191105.pkg

;-)

**Closed by misch7** 2019-11-18 10:01 UTC
Labels: feature: :inbox_tray: install and update, os: :apple: macOS
