### ISSUE TITLE
"VFS" Sync status never changes on Doc or docs 

### ISSUE THREAD

**Issue by AndyXheli** [nextcloud/desktop#3526] opened 2021-07-09 14:07 UTC
Hello seem like when you click on a doc or docx file the sync always stays on like the below picture.

![image](https://user-images.githubusercontent.com/59488153/125090460-f8453980-e094-11eb-9a55-7cd7ab60ab3a.png)

**Comment by andyxheli** [comment] 2021-07-09 16:05
Also I just noticed if you just open the file and don't make changes the status never changes and stays at syncing but if you make a change and save it it changes to green hope this helps

**Comment by FlexW** [comment] 2021-07-12 12:36
Could you please tell us the version which you are using?

**Comment by claell** [comment] 2021-07-12 12:37
I don't have this problem with version 3.2.3.

**Comment by andyxheli** [comment] 2021-07-12 13:09
@FlexW  I'm using version 3.2.4

**Comment by andyxheli** [comment] 2021-07-12 14:13
Once I open the file and make a change and hit save the status changes to green check dose that help?

**Comment by claell** [comment] 2021-07-12 14:16
Yes. It seems this is a duplicate of #3440 and unrelated to the file type. The files probably were in this state on your system before the fix in version 3.2.3. The fix only works for "new items", not already existing problems. Resetting the sync db or re-adding the sync folder will likely have the same effect.

**Comment by andyxheli** [comment] 2021-07-12 14:20
This was a new computer that I installed 3.2.4 on would that make any difference￼?

**Comment by claell** [comment] 2021-07-12 14:35
Indeed, I didn't know that. Can you provide more detailed information about the setup and steps how the files ended up in that state?

Normally the files are available in the cloud, so what did you do? Open them, so they were downloaded and after that they were in that state? Or something else?

**Comment by claell** [comment] 2021-07-12 14:36
Also, I assume you use several machines. Is this reproducible also on the other ones?

**Comment by andyxheli** [comment] 2021-07-12 14:50
On the other workstations I don't have VFS turned on my other computers but on one.  So i installed client 3.2.4 all the VFS files synced then i started to open the files to few them but as soon as i started to open docx file to few something and closed it but the state never change it just shows the syncing so then i said let me open other files like pdfs, photos and see if it dose the same thing and it dose not. SO then i said let me change something in the docx file and see if it changes the sate and it dose so if you just try to open the file and close it the state never changes but it should dose that make sense ?

**Comment by andyxheli** [comment] 2021-07-12 15:34
@claell Please seee video below hope this helps

https://user-images.githubusercontent.com/59488153/125315361-aacb0580-e2fc-11eb-80a1-7d96988dc1dd.mp4

**Comment by claell** [comment] 2021-07-12 16:12
What I observe from the video is that the status icon also changes to a checkmark for Word files when downloading them for a short moment (0:09 just before Word overlaps it, for example). Possibly something makes the sync engine change the status again right after that. I just checked, but for me, doing the same thing with a Word document works (well for one document I got an error from Windows explorer for the download, but that is a different problem).

**Comment by andyxheli** [comment] 2021-07-12 16:44
@claell Check this our video out.  When I create new files.  I created docx, txt, pub

https://user-images.githubusercontent.com/59488153/125325446-8ecc6180-e306-11eb-96ea-053491cd5e5a.mp4

**Comment by andyxheli** [comment] 2021-07-12 18:42
@claell  Also see what happens if you make the folder always locally

https://user-images.githubusercontent.com/59488153/125339476-f12d5e00-e316-11eb-87ae-f56f606ec0ed.mp4

 very strange

**Comment by claell** [comment] 2021-07-13 08:19
My capabilities pretty much end here, so I guess a dev has to look deeper into it.

**Comment by andyxheli** [comment] 2021-07-13 15:47
> My capabilities pretty much end here, so I guess a dev has to look deeper into it.

Thank you for your input @claell

**Comment by alex6480** [comment] 2021-07-18 22:35
I've had a similar issue on two different computers with different versions of Windows, where the status would show the refresh icon forever.

In my case it did not depend on file type. It seemed kind of random which files were affected. Marking the file as "online only" and then downloading the file would sometimes but not always fix the issue.

I cannot provide more information as I've had to disable virtual files on both computers due to other issues.

**Comment by andyxheli** [comment] 2021-08-09 13:24
Still an issue on 3.3.0

**Comment by andyxheli** [comment] 2021-09-20 16:17
Still an issue on 3.3.3

**Comment by mgallien** [comment] 2021-09-21 14:13
> Still an issue on 3.3.3

can you provide your logs ?
without them we cannot understand the problem

**Comment by andyxheli** [comment] 2021-09-21 14:33
@mgallien where would you like me to send the logs or can you create a share i can upload them too

**Comment by andyxheli** [comment] 2021-09-21 17:30
@mgallien Here you go seems to happen more on word files
[Logs.zip](https://github.com/nextcloud/desktop/files/7205104/Logs.zip)

**Comment by andyxheli** [comment] 2021-09-23 14:29
@mgallien did you have a chance to look at the logs ? Where they any help?

**Comment by andyxheli** [comment] 2021-10-06 14:19
@mgallien any news on this issue?

**Comment by andyxheli** [comment] 2021-11-04 17:15
Still an issue

**Comment by dasHorst99** [comment] 2021-11-05 13:07
Still an issue under Version 3.3.6 (Windows)

**Comment by GyrosWookiedaris** [comment] 2021-11-10 10:53
With Win 11 and version 3.3.6 I don't have this problem, with Win 10 and version 3.3.6 the problem occurs.
Deleting the sync db as described solves the problem temporarily.
Even going back to 3.2.2 on Win 10 doesn't resolve the problem.

**Comment by andyxheli** [comment] 2021-11-29 18:40
Hello, just wanted to see if dev has an updates on this ?

**Comment by andyxheli** [comment] 2021-12-09 14:37
@mgallien Anyway we can add this to the 3.4 update ? it very fustrating to see your files sync when they dont need to be synced

**Comment by andyxheli** [comment] 2022-01-11 02:08
Still an issue on 3.4.1

**Comment by andyxheli** [comment] 2022-03-18 15:19
Still an issue on 3.4.4

**Comment by andyxheli** [comment] 2022-04-07 12:21
@mgallien @FlexW  can we please have this fixed! I I know you guys are very busy but it very frustrating that when you open a doc or docx and close it the status away stays at syncing this only happens when you open and close the doc and don't make any changes if you make a change and save it status changes to synced and cycle goes away.

**Comment by andyxheli** [comment] 2022-05-17 16:03
Hi All, This is still an issue on 3.5.1 just tested it. Can we please get some attention on this ticket ? 

![image](https://user-images.githubusercontent.com/59488153/168857043-d287e022-2724-473a-b590-3a5c6a5ede96.png)

![image](https://user-images.githubusercontent.com/59488153/168856964-8205c007-b0c0-44d4-b370-f581b27cb3ce.png)

**Comment by andyxheli** [comment] 2023-01-19 16:06
Still an issue on some file running version 3.6.5

**Comment by andyxheli** [comment] 2023-03-18 12:57
Still an issue on 3.7.4

**Comment by roberix** [comment] 2023-03-18 15:09
Hi.

Got this bevavior exactly as described on 100+ users.

A major issue preventing us to rollout NC as corporate file store solution.

Can we somehow help to solve this issue?

Best regards

Reinhard

**Comment by AXTS01** [comment] 2023-03-21 11:58
@mgallien any thoughts on this ?

**Comment by mgallien** [comment] 2023-03-22 09:26
if this issue is caused by small files being stuck in "pending sync" state, there is a fix for it in 3.7.4
otherwise no update

**Comment by AndyXheli** [comment] 2023-03-22 12:07
@mgallien , 3.7.4 did not fix this issue for me but it did fix  the other issues. Any suggestions? 

Anyone else having this issue on 3.7.4 ?

**Comment by AndyXheli** [comment] 2023-03-22 12:07
@mgallien , 3.7.4 did not fix this issue for me but it did fix  the other issues. Any suggestions? 

Anyone else having this issue on 3.7.4 ?

**Comment by AndyXheli** [comment] 2023-03-31 17:51
Hey @mgallien so looks like  this only happens with file that are password protected all other files that are not password protected change the status to the green check once open and closed and not stuck on blue sync icon any thoughts why it only happens on password protected files ? Tested it also on 3.8.0 same thing.

**Comment by roberix** [comment] 2023-04-01 07:54
Hi. 

@AndyXheli I can see this behavior on all docx files - not only on password protected documents. As soon as I open the file the sync status becomes sync pending. Never changes back unless I am doing and actual change to the document and hit the save button in Word. 

Result is that I got hundreds of word files in sync pending. 

Can u confirm that word file (docx) sync works properly for you (with exception of pw protected file) ?

thx

Regards

Rob

**Comment by AndyXheli** [comment] 2023-04-01 13:04
@roberix

I just tested on a few computers and it all seems to work for me unless its a password protected file then still shows the blue sync icon after closing it.

I'm running Windows 11, Desktop Client 3.8.0. I have not tested it on Windows 10 what version of Windows are you running ?

**Comment by roberix** [comment] 2023-04-19 14:04
@AndyXheli 

Hi. 

Running Windows 10 and Desktop Client 3.7.4

I briefly checked 3.8.0 which did not resolve the issue.

Regards

Rob

**Comment by PhilippSchlesinger** [comment] 2023-07-24 10:34
Maybe this is related to #5889

**Comment by AndyXheli** [comment] 2024-01-31 15:29
Haven't seen any issue with version 3.11.0  running win 11 closing this for now!

**Closed** 2024-01-31 15:29 UTC
Labels: bug, feature: :minidisc: virtual filesystem, approved
