### ISSUE TITLE
[Bug]: Icons too bigh on High-DPI screens

### ISSUE THREAD

**Issue by solracsf** [nextcloud/desktop#6398] opened 2024-01-30 16:55 UTC
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

See screenshot

![image](https://github.com/nextcloud/desktop/assets/12234510/574ae4ce-4209-4282-902e-3d929173fd9d)

On hover

![image](https://github.com/nextcloud/desktop/assets/12234510/5c1dea3b-14ab-4d01-a08c-f920a6dd9a4c)

### Steps to reproduce

NC

### Expected behavior

NC

### Which files are affected by this bug

NC

### Operating system

Windows

### Which version of the operating system you are running.

Windows 10

### Package

Other

### Nextcloud Server version

26.0.11

### Nextcloud Desktop Client version

3.11

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 3.3.6 to 3.4.0)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by viktorix** [comment] 2024-01-30 17:24
Sounds like a duplicate of https://github.com/nextcloud/desktop/issues/6290

Update to 3.11.1. Fixed on my end.
![image](https://github.com/nextcloud/desktop/assets/1692600/1c6030ff-f238-42fd-9312-944a17ca60a5)

**Closed as not planned** 2024-01-30 21:52 UTC
Labels: 0. Needs triage
