### ISSUE TITLE
[Bug]: Unencrypted folders are never deleted as long as E2EE is activated

### ISSUE THREAD

**Issue by bcutter** [nextcloud/desktop#6103] opened 2023-09-28 14:11 UTC
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

See https://github.com/nextcloud/desktop/issues/5918

### Steps to reproduce

See https://github.com/nextcloud/desktop/issues/5918

### Expected behavior

See https://github.com/nextcloud/desktop/issues/5918

### Which files are affected by this bug

Every (!) folder, no matter if empty or not

### Operating system

Windows

### Which version of the operating system you are running.

Windows 10

### Package

Appimage

### Nextcloud Server version

27.1.1

### Nextcloud Desktop Client version

3.10.0

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 3.4.2 to 3.4.4)

### Are you using the Nextcloud Server Encryption module?

Encryption is Enabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Nextcloud Server logs

```shell
Nothing in logs.
```

### Additional info

See https://github.com/nextcloud/desktop/issues/5918 which was closed incorrectly, based on the closer not understanding the actual issue. Affected folders are also NOT-E2EE folders (⚠⚠⚠).

**Comment by joshtrichards** [comment] 2023-10-14 16:28
Re-opened #5918 (the original issue) since it contains more context. Closing this as a duplicate now that it's re-opened.

Duplicate of #5918

**Closed by joshtrichards** 2023-10-14 16:28 UTC
Labels: 0. Needs triage
