### ISSUE TITLE
Nextcloud Desktop 3.1 comes up and vanishes

### ISSUE THREAD

**Issue by vantino** [nextcloud/desktop#2742] opened 2020-12-19 15:12 UTC
Ciao

I am running NC19.0.6 and all worked perfectly. However, I upgraded my win-desktop and 2 win-notebooks with Desktop-3-1 client and the problems began. It worked with desktop-3.0.6 perfect but not with 3.1.

Here are my issues.

1. PC comes back from sleep mode. NC icon is red, no sync working. I need to restart the nc-desktop client and it woks perfect.

2. Installed 3.1 on one of my notebooks, after booting it comes up but vanishes thereafter. Result, no nc client running.
2b) an other user at this notebook can run nc client automatically w/o any issues.

My workarounds so far:

reinstallation and repair option of 3.1 client - no effect

Can I fall back to desktop-3.0.3/6? Where do I get it?

THanks
Vantino

*) Questions any time, I love the product

**Comment by PascalHeynmoeller** [comment] 2020-12-19 22:22
Same here. Uninstalled 3.1 and went back to 3.0.3 which works. Was also effected by #2678 .

**Comment by PenIv** [comment] 2020-12-20 08:58
Same here. Also tried 3.0.82daily-Win64 (build 20201210) with the same crash after start. Debug logs does not show any errors and ends with the last entry `[ debug nextcloud.sync.networkjob.avatar ]	[ OCC::AvatarJob::finished ]:	Retrieved Avatar pixmap!`
Reverted to 3.0.3.

**Comment by er-vin** [comment] 2020-12-21 06:58
Duplicate of #2710 the fix will be released with 3.1.1 in the next few days.

**Closed by er-vin** 2020-12-21 06:58 UTC
