### ISSUE TITLE
[Bug]: Nautilus integration: Nextcloud shares shown twice

### ISSUE THREAD

**Issue by lightonflux** [nextcloud/desktop#6218] opened 2023-11-13 00:03 UTC
- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

The nautilus integration shows nextcloud shares twice:

![image](https://github.com/nextcloud/desktop/assets/1377943/54efa3b3-6b2f-4f53-b2e2-7feef2e46361)

### Steps to reproduce

1. Have nautilus v45.1, Nextcloud Client 3.10.0 (Fedora) and `nextcloud-client-nautilus` (same version, but different package on fedora).  
2. Add two shares / nextcloud targets in the client. (Maybe also happens with one share too).
3. Open nautilus
4. Observe

### Expected behavior

Each share should only be displayed once. Redundancy is not necessary and confusing. 

### Which files are affected by this bug

/usr/share/nautilus-python/extensions/syncstate-Nextcloud.py

### Operating system

Linux

### Which version of the operating system you are running.

Fedora 39

### Package

Distro package manager

### Nextcloud Server version

27.1.3

### Nextcloud Desktop Client version

 3.10.0

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 3.3.6 to 3.4.0)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [X] Default internal user-backend

### Additional info

I wasn't sure if this is a nautilus or nextcloud. So here is the bug report for nautilus: 

https://gitlab.gnome.org/GNOME/nautilus/-/issues/3169

**Comment by mbiebl** [comment] 2023-11-14 19:56
I can reproduce this issue:
![grafik](https://github.com/nextcloud/desktop/assets/3609611/c72bad36-0eb3-4cab-b374-115435851ab7)

Using version Debian sid, nextcloud-desktop is version 3.10.0-1, nautilus is version 44.2.1-2

**Comment by mbiebl** [comment] 2023-11-14 20:09
I've downgraded https://packages.debian.org/unstable/nautilus-nextcloud to 3.7.3-1 (from Debian stable), and the duplicate icons are gone.

**Comment by lightonflux** [comment] 2023-11-18 18:00
The sysncstate.py has not changed between these versions.

**Comment by mbiebl** [comment] 2023-11-20 00:36
Running git bisect shows 28297106af4b3e22e97982c6ee12abfca09ce46c as the first faulty commit

```
28297106af4b3e22e97982c6ee12abfca09ce46c is the first bad commit
commit 28297106af4b3e22e97982c6ee12abfca09ce46c
Author: Corentin Noël <corentin.noel@collabora.com>
Date:   Wed Sep 6 16:04:15 2023 +0200

    Add compatibility with the new libcloudproviders integration
    
    Since libcloudproviders 0.3.3 it is possible to specify the interface name directly
    in the .desktop file, and thus allowing it to be integrated when using a containerized
    client.
    
    Signed-off-by: Corentin Noël <corentin.noel@collabora.com>

 mirall.desktop.in      | 2 +-
 src/gui/CMakeLists.txt | 6 ++++++
 2 files changed, 7 insertions(+), 1 deletion(-)
```

**Comment by mbiebl** [comment] 2023-11-20 00:38
@tintou ^

**Comment by mbiebl** [comment] 2023-11-20 00:39
```
$ apt-cache policy libcloudproviders0 
libcloudproviders0:
  Installiert:           0.3.4-1
  Installationskandidat: 0.3.4-1
  Versionstabelle:
 *** 0.3.4-1 500
        500 http://ftp.debian.org/debian sid/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Comment by mbiebl** [comment] 2023-11-20 07:43
Removing the four lines
```
Implements=org.freedesktop.CloudProviders

[org.freedesktop.CloudProviders]
BusName=com.nextcloudgmbh.Nextcloud
ObjectPath=/com/nextcloudgmbh/Nextcloud
```
from /usr/share/applications/com.nextcloud.desktopclient.nextcloud.desktop fixes the duplicate icons in nautilus.

**Comment by lightonflux** [comment] 2023-11-20 15:29
I just commented out the last 3. So `Implements=org.freedesktop.CloudProviders` can stay in the file.

**Comment by tintou** [comment] 2023-11-20 17:10
The debian package shouldn't install the .in in /usr/share/cloud-providers when there is libcloudproviders 0.3.3+ available in the system as these files are now "legacy"

**Comment by tintou** [comment] 2023-11-20 17:11
This for instance allows the flatpak version of the desktop client to now be working out of the box.

**Comment by mbiebl** [comment] 2023-11-20 17:11
Hm, shouldn't the build system then make the installation of those legacy file conditional?

**Comment by werdahias** [comment] 2023-11-22 14:52
agreed, this could be done by a```
 if(cloudproviders FOUND) && version >= 0.3.3 
...
```
in Cmakelists.txt (paraphrasing the syntax)

**Comment by Thesola10** [comment] 2023-11-24 13:25
idk if it's just that, I'm using the Flatpak and still see duplicate shares.

**Comment by xplosionmind** [comment] 2023-12-09 10:29
Hi to you all! I opened #6243 without being able to find this issue before. Popping in just to report that this is happening for me on Fedora 39 with GNOME, using Nextcloud Desktop client [version 3.10.1](https://packages.fedoraproject.org/pkgs/nextcloud-client/nextcloud-client/fedora-39-updates.html), installed via [the official Fedora package](https://packages.fedoraproject.org/pkgs/nextcloud-client/nextcloud-client).

**Comment by tintou** [comment] 2023-12-09 16:16
Opened #6275

**Comment by slimeyena** [comment] 2023-12-11 13:59
> Hi to you all! I opened #6243 without being able to find this issue before. Popping in just to report that this is happening for me on Fedora 39 with GNOME, using Nextcloud Desktop client [version 3.10.1](https://packages.fedoraproject.org/pkgs/nextcloud-client/nextcloud-client/fedora-39-updates.html), installed via [the official Fedora package](https://packages.fedoraproject.org/pkgs/nextcloud-client/nextcloud-client).

I have the same environment, is there a fix I can perform on my end in the meantime whilst a fix comes through the pipeline into Gnome Software? 

(Other than this minor annoyance it's a great app, thanks to all who worked on it)

**Comment by j-lakeman** [comment] 2023-12-25 17:50
Resolved for me on Debian Sid.

**Comment by xplosionmind** [comment] 2023-12-30 13:05
Not for me on Fedora 39, even after updating to v3.11.

**Comment by tintou** [comment] 2023-12-30 15:44
https://github.com/nextcloud/desktop/pull/6275 has been approved but not merged so no need to give updates until there has been changes.

**Comment by xplosionmind** [comment] 2023-12-30 20:27
> no need to give updates until there has been changes.

I am sorry about that!

**Closed** 2024-01-19 12:01 UTC
Labels: 0. Needs triage

**Comment by noahcub** [comment] 2024-02-05 10:20
Fedora 39 with Gnome 45.3
[mbiebl](https://github.com/mbiebl)'s fix works for me.

**Comment by LostinSpacetime** [comment] 2024-02-06 08:06
> Fedora 39 with Gnome 45.3 [mbiebl](https://github.com/mbiebl)'s fix works for me.

It does, but until the package is fixed, the next update will put both entries back in Nautilus.

**Comment by tintou** [comment] 2024-02-06 10:24
No because as this ticket status stands, it is fixed already

**Comment by mbiebl** [comment] 2024-02-06 10:34
At this point you need to poke your downstream maintainers to include this fix.
I did this for Debian: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1056327

It's fixed from an upstream PoV
