### ISSUE TITLE
Files become zero size when sync dropped due to network issues

### ISSUE THREAD

**Issue by EukalyptusX** [nextcloud/desktop#1323] opened 2019-07-02 20:32 UTC
**### Expected behaviour**
After the connection to the server dropped while syncing, the files which were not downloaded correctly should be deleted and re-downloaded.

**### Actual behaviour**
Files, which were downloaded incompletely, become corrupt and stay empty (zero bytes). Although it says later "successful", when the sync finished.

**### Steps to reproduce**
1. Sync tons of pictures.
2. Drop the connection while syncing. (It needs to be a timeout!)
3. Reconnect.
4. Force sync.
5. After finished sync ("successful sync"): See files with sizes of zero bytes on the client. (On Linux: "find . -size 0 -print")

**### Client configuration**
Client version: **2.5.2git**
Operating system: **Fedora x64 Workstation**
OS language: **German**
Qt version used by client package (Linux only, see also Settings dialog): **Qt 5.12.1**
Client package (From Nextcloud or distro) (Linux only): **Distro (Official Repo)**

Installation path of client: **/usr/bin/nextcloud**

**### Server configuration**
Nextcloud version: 15.0.8

**Comment by EukalyptusX** [comment] 2019-07-02 20:53
Ok, I think it's related to this: [Issue-7995](https://github.com/nextcloud/server/issues/7995)

I just didn't saw that earlier and thought it happened due to the network issue.

**Comment by enoch85** [comment] 2020-07-07 10:36
This is serious and should be looked at. 

Just noticed the same issue for like 400 files (mostly pictures) that dates back so long that I don't have a recent backup. :(

**Comment by ferdiga** [comment] 2020-11-08 18:31
desktop sync tries unsuccessfully to download (sync) the file and reports "file_downloaded" in oc_activities for every try.
NC 19.0.4
 the image file was taken on a Samsung Galaxy S10+ , a found the file size to be 0 Bytes, nevertheless it was somehow synced to the cloud and causes problems there.
probably an Android client issue too.

**Comment by enoch85** [comment] 2021-05-06 17:59
Still an issue.

**Comment by enoch85** [comment] 2021-09-14 19:11
Just curious, any update on this issue? Planned soon, or just approved (could happen in years).

Thanks!

**Comment by joshtrichards** [comment] 2024-08-16 02:24
Duplicate of nextcloud/server#7995

**Closed by joshtrichards** 2024-08-16 02:24 UTC
Labels: bug, feature: :arrows_counterclockwise: sync engine, approved
