### ISSUE TITLE
[Linux] Possibility to get connection status from the app

### ISSUE THREAD

**Issue by Yaakoss** [nextcloud/desktop#6328] opened 2024-01-03 21:37 UTC
I use a window tiling manager (Qtile) and i do not use systray. I would like to have a possibility to get a connection status from the app for example by invoking 
`nextcloud --connection-status`
`Status: Connected` or Disconnected or Error

That would allow to implement a widget that shows the status of the connection.

**Comment by joshtrichards** [comment] 2024-08-18 22:13
Duplicate of #6345 (it contains a bit more traffic)

**Closed by joshtrichards** 2024-08-18 22:13 UTC
Labels: enhancement
