### ISSUE TITLE
Client crashes under Win7 with error in ig75icd64.dll

### ISSUE THREAD

**Issue by ThomasDaheim** [nextcloud/desktop#939] opened 2018-12-12 10:25 UTC
### Expected behaviour
Client starts

### Actual behaviour
Short hourglass cursor and no further activity.

### Steps to reproduce
1. Start nextcloud.exe

### Client configuration
Client version: 2.5.1.61652
Intel driver version: 10.18.10.4425 (updated before testing)

Operating system: Win7

OS language: English

Installation path of client: C:\Program Files (x86)\Nextcloud\nextcloud.exe

### Logs

Error in Event viewer:

```
Faulting application name: nextcloud.exe, version: 2.5.1.61652, time stamp: 0x5c0674e1
Faulting module name: ig75icd64.dll, version: 10.18.10.4425, time stamp: 0x5702a9ad
Exception code: 0xc0000005
Fault offset: 0x000000000017143a
Faulting process id: 0x36c0
Faulting application start time: 0x01d49200d6231e68
Faulting application path: C:\Program Files (x86)\Nextcloud\nextcloud.exe
Faulting module path: C:\WINDOWS\system32\ig75icd64.dll
Report Id: 15a95bb0-fdf4-11e8-9c54-0050b67b252d
```

No output created from `nextcloud --logfile log.txt`.

**Comment by stfast** [comment] 2019-04-26 15:22
Faulting application name: nextcloud.exe, version: 2.5.2.5231, time stamp: 0x5c90e346
Faulting module name: ig9icd64.dll, version: 25.20.100.6323, time stamp: 0x5ba3fd9c
Exception code: 0xc0000005
Fault offset: 0x000000000001f82e
Faulting process id: 0x2718
Faulting application start time: 0x01d4fbf7b9cedc9b
Faulting application path: C:\Program Files (x86)\Nextcloud\nextcloud.exe
Faulting module path: C:\windows\System32\DriverStore\FileRepository\igdlh64.inf_amd64_8a9535cd18c90bc3\ig9icd64.dll
Report Id: d76feb5f-5850-4b5c-9810-06cb96ee2db9
Faulting package full name:
Faulting package-relative application ID:

**Comment by raimund-schluessler** [comment] 2019-11-22 07:54
This is a duplicate of https://github.com/nextcloud/desktop/issues/896.

**Closed by raimund-schluessler** 2019-11-22 07:54 UTC
