### ISSUE TITLE
[Bug]: Font not readable in dark mode on linux (gnome)

### ISSUE THREAD

**Issue by pcace** [nextcloud/desktop#6565] opened 2024-03-21 15:19 UTC
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

The font Color in the last linux Desktop client is not readable when in dark mode. 
https://github.com/nextcloud/desktop/issues/6554

(Nextcloud Desktop-Client 3.12.1 on PopOS 23.10 (GNOME 43 or 44).)

### Steps to reproduce

1. Install latest Nextcloud Desktop-Client 3.12.1 in GNOME 43 or 44
2. swich to dark mode
see: https://github.com/nextcloud/desktop/issues/6554 for images

### Expected behavior

swich font color to a contrast color like in the settings window.

### Which files are affected by this bug

client

### Operating system

Linux

### Which version of the operating system you are running.

GNOME 44 (PopOS, Ubuntu, Debian)

### Package

Appimage

### Nextcloud Server version

28.0.3

### Nextcloud Desktop Client version

3.12.1

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [X] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by joshtrichards** [comment] 2024-03-25 12:42
Duplicate of #6554

**Closed by joshtrichards** 2024-03-25 12:42 UTC
Labels: 0. Needs triage
