### ISSUE TITLE
TLS 1.3 broken with Mac Client 3.4.1

### ISSUE THREAD

**Issue by Steve8291** [nextcloud/desktop#4158] opened 2022-01-09 17:12 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour
TLS 1.3 should work with new client.

### Actual behaviour
Failed SSL Handshake after installing new client. 

### Steps to reproduce
1. On version 3.2.3 or 3.3.6 Mac Desktop Client TLS 1.3 works fine.
2. After updating to Client 3.4.1 TLS 1.3 is broken
3. If I adjust server config to allow TLS 1.2 as well as 1.3 then the new client is able to log in.

### Client configuration
Client version: 3.4.1

Operating system: Mac OS 12.0.1 Monterey (latest)

OS language: Mac OS
On another, less important side note: Desktop Client reports incorrect osx version to be 21.1.0

Installation path of client: /MacintoshHD/Applications/

### Server configuration

Nextcloud version: 22.2.3

Storage backend (external storage):

### Logs

1. Client logfile: 
> |2022-01-08 09:43:52:511 [ warning nextcloud.sync.networkjob /var/folders/yr/9dx0mtfj7kdf4725tmcz6md80000gp/T/macos-8596/src/libsync/abstractnetworkjob.cpp:185 ]:|SslHandshakeFailedError:  SSL handshake failed  : can be caused by a webserver wanting SSL client certificates|
> |---|---|
> |2022-01-08 09:43:52:511 [ warning nextcloud.sync.networkjob /var/folders/yr/9dx0mtfj7kdf4725tmcz6md80000gp/T/macos-8596/src/libsync/abstractnetworkjob.cpp:224 ]:|QNetworkReply::SslHandshakeFailedError SSL handshake failed QVariant(Invalid)|
> |2022-01-08 09:43:52:511 [ warning nextcloud.sync.credentials.webflow /var/folders/yr/9dx0mtfj7kdf4725tmcz6md80000gp/T/macos-8596/src/gui/creds/webflowcredentials.cpp:227 ]:|QNetworkReply::SslHandshakeFailedError|
> |2022-01-08 09:43:52:511 [ warning nextcloud.sync.credentials.webflow /var/folders/yr/9dx0mtfj7kdf4725tmcz6md80000gp/T/macos-8596/src/gui/creds/webflowcredentials.cpp:228 ]:|SSL handshake failed|
> |2022-01-08 09:43:52:511 [ warning nextcloud.sync.networkjob.checkserver /var/folders/yr/9dx0mtfj7kdf4725tmcz6md80000gp/T/macos-8596/src/libsync/networkjobs.cpp:541 ]:|error: status.php replied  0 |
> |2022-01-08 09:43:52:511 [ warning nextcloud.sync.connectionvalidator /var/folders/yr/9dx0mtfj7kdf4725tmcz6md80000gp/T/macos-8596/src/gui/connectionvalidator.cpp:139 ]:|QNetworkReply::SslHandshakeFailedError SSL handshake failed |
> |2022-01-08 09:43:52:511 [ info nextcloud.gui.account.state /var/folders/yr/9dx0mtfj7kdf4725tmcz6md80000gp/T/macos-8596/src/gui/accountstate.cpp:306 ]:|AccountState connection status change:  OCC::ConnectionValidator::Undefined -> OCC::ConnectionValidator::SslError|
> |2022-01-08 09:43:52:512 [ info nextcloud.gui.account.state /var/folders/yr/9dx0mtfj7kdf4725tmcz6md80000gp/T/macos-8596/src/gui/accountstate.cpp:101 ]:|AccountState state change:  Disconnected -> Signed out|
> |2022-01-08 09:43:52:512 [ info nextcloud.gui.folder.manager /var/folders/yr/9dx0mtfj7kdf4725tmcz6md80000gp/T/macos-8596/src/gui/folderman.cpp:721 ]:|Account user@myserver.com disconnected or paused, terminating or descheduling sync folders|

2. Web server error log: None, we never make  it that far.

3. Server logfile: nextcloud log (data/nextcloud.log): Nothing.

**Comment by Steve8291** [comment] 2022-01-10 11:14
@allexzander It's an Intel Mac.

**Comment by dave-kennedy** [comment] 2022-01-11 22:58
Dupe of #4043, which is a dupe of #3974.

**Comment by claell** [comment] 2022-01-18 10:37
Marking as duplicate. Feel free to reopen if that is not correct.

**Comment by claell** [comment] 2022-01-18 10:37
Duplicate of #3974

**Closed by claell** 2022-01-18 10:37 UTC
Labels: bug, regression, os: :apple: macOS
