### ISSUE TITLE
In Activity stream the date string for "ago ..." is incomplete (string parsing)

### ISSUE THREAD

**Issue by RogoTe** [nextcloud/desktop#1780] opened 2020-02-12 22:50 UTC
In clients activity view you have a list of things that happend. Second line for every list entry is the date of this action following how long ago this was. In this string parsing or composition is defect. It displays the parsed "ago time string" only with first part of language string.![Screenshot 2020-02-12 at 23 13 27](https://user-images.githubusercontent.com/45861130/74384195-11d74880-4df1-11ea-9c8c-2a2ec0d225b8.png)

### Expected behaviour
Activity stream shows correct "abc changed xyz. $date (3 hours and 12 minutes ago)"

### Actual behaviour
Activity stream shows "abc changed xyz. $date (3 hours"

### Steps to reproduce
1. Open Nextcloud app
2. Go to Activity stream view

### Client configuration
Client version: 2.6.2

Operating system: MacOS 10.15.3, but also previous at least since 10.14.6

OS language: German and also English (did not test more)

**Comment by misch7** [comment] 2020-02-17 01:21
Hey @RogoTe,

thanks for pointing this out.

I also noticed this behaviour when I worked on the Activity and tried to address it in the PR:
https://github.com/nextcloud/desktop/pull/1687

My first guess was that this would have been caused by Retina vs low-res issues in Qt and a quick fix just worked for me back then:
https://github.com/nextcloud/desktop/pull/1687/commits/420968d2a2b81fd86ee695ebe946adf4a45ee435

Are you a developer and if so, could you have a look and try to get a clue? ;-)

**Comment by misch7** [comment] 2020-03-02 01:58
Fixed by #1824 and will get into the 2.6.4 release.

**Closed by misch7** 2020-03-02 01:58 UTC
Labels: bug, feature: :zap: activity and :bell: notification
