### ISSUE TITLE
Renaming in a synced folder leads to undetermined results and DELETED FILES!

### ISSUE THREAD

**Issue by twatzl** [nextcloud/desktop#1296] opened 2019-06-11 07:02 UTC
### Expected behaviour
Nextcloud client should support renaming of folders and files without deleting files or creating duplicates on the server.

### Actual behaviour
Nextcloud client gets confused when batch renaming files with XnViewMp which leads to duplicates. Hence I have to pause sync when doing major organizing tasks and resume it once I am done. If I have sync running while doing this kind of stuff it also highly degrades performance for me.
However renaming a folder lead to the deletion of over 4000 files for me! Somehow the client got confused and instead of renaming it it just deleted both folders the old ones on the server and the new ones on the client. Might also be that I chose to no longer sync those folders while they were still being synced. It is also strange that a renaming action requires the resync of several GB (we are talking about 50GB) of data.

I think it is absolutely unacceptable, that nextcloud deletes files in whatever circumstances except if I explicitly ordered it to delete files! If the sync task isn't yet completed and I unselect the files (i.e. stop syncing them to my local fs) I expect to run the task until the end and only THEN delete the files on my local machine.

### Steps to reproduce
1. Batch rename several GB of photos using XnView MP, this will lead to duplicates.
2. Rename a folder while syncing is paused or the client is not active, this might lead to the client deleting files.

### Client configuration
Client version: Version 2.5.1final (build 20181204)
Operating system: Windows 10 PRO 17763.503
OS language: English
Installation path of client: G:\Program Files (x86)\Nextcloud

### Server configuration
Nextcloud version: Nextcloud 15
Storage backend (external storage): no external storage in use

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

Client logfile: contains no content
Server logfile: nextcloud log (data/nextcloud.log): can be sent on request. Is 500MB in size.

**Comment by camilasan** [comment] 2021-07-13 14:15
duplicate of #3240

**Closed by camilasan** 2021-07-13 14:15 UTC
