### ISSUE TITLE
Error or warning notification link is dead in setup page

### ISSUE THREAD

**Issue by wahboh** [nextcloud/desktop#2348] opened 2020-08-31 22:25 UTC
### Expected behaviour
When I get a warning about unsolved conflicts, the "golden" warning bar displays that it is a link to details
![image](https://user-images.githubusercontent.com/24376603/91774345-debba180-ebe8-11ea-95ae-d6d0fa365cde.png)

### Actual behaviour
The link is dead. You have to manually open the (tiny, way to small!) log window to (possibly) find the root cause. 

### Steps to reproduce
Every time there is cause for a warning och error

### Client configuration
Client version:
3.0.1

Operating system:
Windows 10 Pro upd 2004 x64
OS language:
Swedish

Installation path of client:
C:\Program\Nextcloud

### Server configuration
N/A

### Logs

N/A

**Comment by er-vin** [comment] 2020-09-01 06:35
Duplicate of #2299

**Closed by er-vin** 2020-09-01 06:35 UTC
