### ISSUE TITLE
High Memory Load from Client with high Access Requests (Apache Access Log)

### ISSUE THREAD

**Issue by Lange23** [nextcloud/desktop#1513] opened 2019-10-15 12:03 UTC
Nextcloud version _(eg, 12.0.2)_: 16.0.5
Nextcloud Client: 2.6.0
Operating system and version _(eg, Ubuntu 17.04)_: Ubuntu 16.04.6
Apache or nginx version _(eg, Apache 2.4.25)_: Apache/2.4.41
PHP version _(eg, 7.1)_: php-fpm-7.1

**The issue you are facing:**

Also see
[https://help.nextcloud.com/t/high-memory-load-from-client-with-high-access-requests-apache-access-log/61120](url)

I have a very high load of memory usage cause of 2 Clients which are accessing the cloud with the nextcloud client very often.

I have multiple Nextclouds on this server but only facing the problem with two clients (different IPs).

My other Nextclouds on this server and the other customer with clients don't produce this amount of accesses.

I am using the newest version of this client. Is there maybe a configuration that is forcing so many requests so that my memory gets on high load ?

For Example:

`    CUSTOMERSERVER - - [01/Oct/2019:14:22:20 +0200] "PROPFIND /remote.php/dav/files/backup/ HTTP/2.0" 207 446 "-" "Mozilla/5.0 (Windows) mirall/2.6.0stable-Win64 (build 20190927) (Nextcloud)"
    CUSTOMERSERVER - - [01/Oct/2019:14:22:22 +0200] "PROPFIND /remote.php/dav/files/backup/Backups/CUSTOMER HTTP/2.0" 207 446 "-" "Mozilla/5.0 (Windows) mirall/2.6.0stable-Win64 (build 20190927) (Nextcloud)"
    CUSTOMERSERVER - - [01/Oct/2019:14:22:27 +0200] "PROPFIND /remote.php/dav/files/backup/Backups/CUSTOMER HTTP/2.0" 207 446 "-" "Mozilla/5.0 (Windows) mirall/2.6.0stable-Win64 (build 20190927) (Nextcloud)"
    CUSTOMERSERVER - - [01/Oct/2019:14:22:32 +0200] "PROPFIND /remote.php/dav/files/backup/Backups/CUSTOMER HTTP/2.0" 207 828 "-" "Mozilla/5.0 (Windows) mirall/2.6.0stable-Win64 (build 20190927) (Nextcloud)"
    CUSTOMERSERVER - - [01/Oct/2019:14:22:37 +0200] "PROPFIND /remote.php/dav/files/backup/Backups/CUSTOMER HTTP/2.0" 207 446 "-" "Mozilla/5.0 (Windows) mirall/2.6.0stable-Win64 (build 20190927) (Nextcloud)"
    CUSTOMERSERVER - - [01/Oct/2019:14:22:42 +0200] "PROPFIND /remote.php/dav/files/backup/Backups/CUSTOMER HTTP/2.0" 207 446 "-" "Mozilla/5.0 (Windows) mirall/2.6.0stable-Win64 (build 20190927) (Nextcloud)"
    CUSTOMERSERVER - - [01/Oct/2019:14:22:47 +0200] "PROPFIND /remote.php/dav/files/backup/Backups/CUSTOMER HTTP/2.0" 207 446 "-" "Mozilla/5.0 (Windows) mirall/2.6.0stable-Win64 (build 20190927) (Nextcloud)"
    CUSTOMERSERVER - - [01/Oct/2019:14:22:52 +0200] "PROPFIND /remote.php/dav/files/backup/Backups/CUSTOMER HTTP/2.0" 207 446 "-" "Mozilla/5.0 (Windows) mirall/2.6.0stable-Win64 (build 20190927) (Nextcloud)"
    CUSTOMERSERVER - - [01/Oct/2019:14:22:52 +0200] "PROPFIND /remote.php/dav/files/backup/ HTTP/2.0" 207 423 "-" "Mozilla/5.0 (Windows) mirall/2.6.0stable-Win64 (build 20190927) (Nextcloud)"
    CUSTOMERSERVER - - [01/Oct/2019:14:22:57 +0200] "PROPFIND /remote.php/dav/files/backup/Backups/CUSTOMER HTTP/2.0" 207 446 "-" "Mozilla/5.0 (Windows) mirall/2.6.0stable-Win64 (build 20190927) (Nextcloud)"
    CUSTOMERSERVER - - [01/Oct/2019:14:23:02 +0200] "PROPFIND /remote.php/dav/files/backup/Backups/CUSTOMER HTTP/2.0" 207 446 "-" "Mozilla/5.0 (Windows) mirall/2.6.0stable-Win64 (build 20190927) (Nextcloud)"
    CUSTOMERSERVER - - [01/Oct/2019:14:23:07 +0200] "PROPFIND /remote.php/dav/files/backup/Backups/CUSTOMER HTTP/2.0" 207 446 "-" "Mozilla/5.0 (Windows) mirall/2.6.0stable-Win64 (build 20190927) (Nextcloud)"
    CUSTOMERSERVER - - [01/Oct/2019:14:23:12 +0200] "PROPFIND /remote.php/dav/files/backup/Backups/CUSTOMER HTTP/2.0" 207 446 "-" "Mozilla/5.0 (Windows) mirall/2.6.0stable-Win64 (build 20190927) (Nextcloud)"
    CUSTOMERSERVER - - [01/Oct/2019:14:23:17 +0200] "PROPFIND /remote.php/dav/files/backup/Backups/CUSTOMER HTTP/2.0" 207 446 "-" "Mozilla/5.0 (Windows) mirall/2.6.0stable-Win64 (build 20190927) (Nextcloud)"
    CUSTOMERSERVER - - [01/Oct/2019:14:23:22 +0200] "PROPFIND /remote.php/dav/files/backup/Backups/CUSTOMER HTTP/2.0" 207 446 "-" "Mozilla/5.0 (Windows) mirall/2.6.0stable-Win64 (build 20190927) (Nextcloud)"
    CUSTOMERSERVER - - [01/Oct/2019:14:23:24 +0200] "PROPFIND /remote.php/dav/files/backup/ HTTP/2.0" 207 446 "-" "Mozilla/5.0 (Windows) mirall/2.6.0stable-Win64 (build 20190927) (Nextcloud)"
    CUSTOMERSERVER - - [01/Oct/2019:14:23:27 +0200] "PROPFIND /remote.php/dav/files/backup/Backups/CUSTOMER HTTP/2.0" 207 446 "-" "Mozilla/5.0 (Windows) mirall/2.6.0stable-Win64 (build 20190927) (Nextcloud)"
    CUSTOMERSERVER - - [01/Oct/2019:14:23:32 +0200] "PROPFIND /remote.php/dav/files/backup/Backups/CUSTOMER HTTP/2.0" 207 446 "-" "Mozilla/5.0 (Windows) mirall/2.6.0stable-Win64 (build 20190927) (Nextcloud)"
    CUSTOMERSERVER - - [01/Oct/2019:14:23:37 +0200] "PROPFIND /remote.php/dav/files/backup/Backups/CUSTOMER HTTP/2.0" 207 446 "-" "Mozilla/5.0 (Windows) mirall/2.6.0stable-Win64 (build 20190927) (Nextcloud)"
    CUSTOMERSERVER - - [01/Oct/2019:14:23:42 +0200] "PROPFIND /remote.php/dav/files/backup/Backups/CUSTOMER HTTP/2.0" 207 446 "-" "Mozilla/5.0 (Windows) mirall/2.6.0stable-Win64 (build 20190927) (Nextcloud)"
    CUSTOMERSERVER - - [01/Oct/2019:14:23:47 +0200] "PROPFIND /remote.php/dav/files/backup/Backups/CUSTOMER HTTP/2.0" 207 446 "-" "Mozilla/5.0 (Windows) mirall/2.6.0stable-Win64 (build 20190927) (Nextcloud)"
    CUSTOMERSERVER - - [01/Oct/2019:14:23:52 +0200] "PROPFIND /remote.php/dav/files/backup/Backups/CUSTOMER HTTP/2.0" 207 446 "-" "Mozilla/5.0 (Windows) mirall/2.6.0stable-Win64 (build 20190927) (Nextcloud)"
    CUSTOMERSERVER - - [01/Oct/2019:14:23:56 +0200] "PROPFIND /remote.php/dav/files/backup/ HTTP/2.0" 207 446 "-" "Mozilla/5.0 (Windows) mirall/2.6.0stable-Win64 (build 20190927) (Nextcloud)"
    CUSTOMERSERVER - - [01/Oct/2019:14:23:57 +0200] "PROPFIND /remote.php/dav/files/backup/Backups/CUSTOMER HTTP/2.0" 207 446 "-" "Mozilla/5.0 (Windows) mirall/2.6.0stable-Win64 (build 20190927) (Nextcloud)"
    CUSTOMERSERVER - - [01/Oct/2019:14:24:02 +0200] "PROPFIND /remote.php/dav/files/backup/Backups/CUSTOMER HTTP/2.0" 207 446 "-" "Mozilla/5.0 (Windows) mirall/2.6.0stable-Win64 (build 20190927) (Nextcloud)"
    CUSTOMERSERVER - - [01/Oct/2019:14:24:07 +0200] "PROPFIND /remote.php/dav/files/backup/Backups/CUSTOMER HTTP/2.0" 207 446 "-" "Mozilla/5.0 (Windows) mirall/2.6.0stable-Win64 (build 20190927) (Nextcloud)"
    CUSTOMERSERVER - - [01/Oct/2019:14:24:12 +0200] "PROPFIND /remote.php/dav/files/backup/Backups/CUSTOMER HTTP/2.0" 207 446 "-" "Mozilla/5.0 (Windows) mirall/2.6.0stable-Win64 (build 20190927) (Nextcloud)"
    CUSTOMERSERVER - - [01/Oct/2019:14:24:17 +0200] "PROPFIND /remote.php/dav/files/backup/Backups/CUSTOMER HTTP/2.0" 207 446 "-" "Mozilla/5.0 (Windows) mirall/2.6.0stable-Win64 (build 20190927) (Nextcloud)"
    CUSTOMERSERVER - - [01/Oct/2019:14:24:22 +0200] "PROPFIND /remote.php/dav/files/backup/Backups/CUSTOMER HTTP/2.0" 207 446 "-" "Mozilla/5.0 (Windows) mirall/2.6.0stable-Win64 (build 20190927) (Nextcloud)"
    CUSTOMERSERVER - - [01/Oct/2019:14:24:27 +0200] "PROPFIND /remote.php/dav/files/backup/Backups/CUSTOMER HTTP/2.0" 207 446 "-" "Mozilla/5.0 (Windows) mirall/2.6.0stable-Win64 (build 20190927) (Nextcloud)"
    CUSTOMERSERVER - - [01/Oct/2019:14:24:28 +0200] "PROPFIND /remote.php/dav/files/backup/ HTTP/2.0" 207 446 "-" "Mozilla/5.0 (Windows) mirall/2.6.0stable-Win64 (build 20190927) (Nextcloud)"
    CUSTOMERSERVER - - [01/Oct/2019:14:24:32 +0200] "PROPFIND /remote.php/dav/files/backup/Backups/CUSTOMER HTTP/2.0" 207 446 "-" "Mozilla/5.0 (Windows) mirall/2.6.0stable-Win64 (build 20190927) (Nextcloud)"
    CUSTOMERSERVER - - [01/Oct/2019:14:24:37 +0200] "PROPFIND /remote.php/dav/files/backup/Backups/CUSTOMER HTTP/2.0" 207 446 "-" "Mozilla/5.0 (Windows) mirall/2.6.0stable-Win64 (build 20190927) (Nextcloud)"
    CUSTOMERSERVER - - [01/Oct/2019:14:24:42 +0200] "PROPFIND /remote.php/dav/files/backup/Backups/CUSTOMER HTTP/2.0" 207 446 "-" "Mozilla/5.0 (Windows) mirall/2.6.0stable-Win64 (build 20190927) (Nextcloud)"
    CUSTOMERSERVER - - [01/Oct/2019:14:24:47 +0200] "PROPFIND /remote.php/dav/files/backup/Backups/CUSTOMER HTTP/2.0" 207 446 "-" "Mozilla/5.0 (Windows) mirall/2.6.0stable-Win64 (build 20190927) (Nextcloud)"`

Is this the first time you've seen this error? _(Y/N)_: Y

Steps to replicate it:

1. Install Clint on PC
2. Watch Access Log

**Comment by alankeny** [comment] 2019-10-15 20:38
Nextcloud version: 17.0.0
Nextcloud client: 2.6.0 and 2.5.3
Operating system and version: Debian GNU/Linux 10
Apache version: Apache 2.4.38-3+deb10u1
PHP version: mod-php7.3

This is happening for me too.  Clients running 2.6.0 and 2.5.3 do a PROPFIND request for every folder sync connection every 5 seconds.  I only noticed it while I was tracking down high CPU load on my server from another process.  These requests also generate large access log files for Apache.

Since I didn't know when the problem started, I tested several versions of the Linux AppImage and MacOS desktop clients.  2.5.2 and earlier only do a PROPFIND every 30 seconds, which is how I understand it's supposed to work.  Version 2.5.3 and 2.6.0 do a PROPFIND every 5 seconds, which makes the load on the server much higher.

**Comment by Lange23** [comment] 2019-10-16 13:56
@alankeny , do you know where to get the older client ?
Couldn't find it on the webpage and like to test with an older version.

Right now, the PROPFIND is killing my multi-customer server with to much requests.

**Comment by alankeny** [comment] 2019-10-16 14:04
This URL will let you browse the folders with several versions of the installer for Linux, MacOS, and Windows:  https://download.nextcloud.com/desktop/releases/

**Comment by andwun** [comment] 2019-10-18 08:57
I created a pending PR in #1456 a few days ago to fix this.
These are the affected client versions that will try to poll for changes every 5 seconds:
v2.6.1-rc1 v2.6.0 v2.6.0-rc1 v2.6.0-fix1 v2.5.3 v2.5.3-rc2

**Comment by Lange23** [comment] 2019-11-11 09:07
Thank you so much !!!!
That really helped me and solved my problem.

Hope they will put it in the default configuration because this is causing me a lot of ressources and my customer are not able to modify their configuration.

**Comment by nursoda** [comment] 2019-11-27 12:59
The path for nextcloud.cfg is ~/.config/Nextcloud on Linux (same on MacOS?).

In Windows the path used to be %LocalAppData%\Nextcloud (in much older client versions) but now is %AppData%\Nextcloud – so make sure to edit the correct file in case the old one is still lurking around.

**Comment by misch7** [comment] 2019-12-01 02:25
> Based on the info in the PR, I added the following to my nextcloud.cfg:
> 
> ```
> [Nextcloud]
> remotePollInterval=30000
> ```
> 
> My 2.6.0 clients are back to polling each folder sync connection every 30 seconds again.
> 

The PR #1456 with the traditional default poll of 30 secs has been merged and will get into the 2.6.2 release.

In addition higher CPU usage with the 2.6.1 release may have been caused by issue https://github.com/nextcloud/desktop/issues/1292#issuecomment-560008811 and this has been solved by PR #1634.

**Comment by misch7** [comment] 2019-12-01 02:32
> The path for nextcloud.cfg is ~/.config/Nextcloud on Linux (same on MacOS?).
> 
> In Windows the path used to be %LocalAppData%\Nextcloud (in much older client versions) but now is %AppData%\Nextcloud – so make sure to edit the correct file in case the old one is still lurking around.

@nursoda The path for nextcloud.cfg on macOS is ~/Library/Preferences/Nextcloud

**Comment by misch7** [comment] 2019-12-06 22:47
Closing here, fixed:
- https://github.com/nextcloud/desktop/pull/1456
- https://github.com/nextcloud/desktop/issues/1292#issuecomment-560008811

Already ported to our upcoming 2.6.2 release :)

**Closed by misch7** 2019-12-06 22:47 UTC

**Comment by misch7** [comment] 2019-12-24 23:20
Ho ho ho! 🎅 🎉

Here is our 2.6.2 release :-)

https://github.com/nextcloud/desktop/releases/tag/v2.6.2
