### ISSUE TITLE
[Bug]: macOS finder extension crashes regularly 

### ISSUE THREAD

**Issue by ataub1** [nextcloud/desktop#6215] opened 2023-11-10 07:07 UTC
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

On macOS the finder extension crashes regularly (multiple times a day). Only terminating the Nextcloud process and restarting nextcloud (or macOS) resolves that the extension works again. But after a few hours the extention crashes again.

I see the following exception in the logs

2023-11-10 07:26:55.719597+0100 0x440158   Default     0x0                  60156  0    FinderSyncExt: (CoreFoundation) *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[1]'
*** First throw call stack:
(
	0   CoreFoundation                      0x00000001810b6800 __exceptionPreprocess + 176
	1   libobjc.A.dylib                     0x0000000180badeb4 objc_exception_throw + 60
	2   CoreFoundation                      0x0000000180fce724 -[__NSPlaceholderDictionary initWithObjects:forKeys:count:] + 728
	3   CoreFoundation                      0x0000000180fce420 +[NSDictionary dictionaryWithObjects:forKeys:count:] + 52
	4   FinderSync                          0x00000001ec24518c -[FIFinderSyncController setBadgeIdentifier:forURL:] + 140
	5   FinderSyncExt                       0x000000010204e1e0 -[FinderSync setResultForPath:result:] + 120
	6   FinderSyncExt                       0x000000010204cfa8 __41-[FinderSyncSocketLineProcessor process:]_block_invoke + 68
	7   libdispatch.dylib <…>
2023-11-10 07:26:55.719620+0100 0x440158   Error       0x0                  60156  0    FinderSyncExt: (AppKit) [com.apple.AppKit:General] An uncaught exception was raised
2023-11-10 07:26:55.720245+0100 0x440158   Error       0x0                  60156  0    FinderSyncExt: (AppKit) [com.apple.AppKit:General] *** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[1]
2023-11-10 07:26:55.720301+0100 0x440158   Error       0x0                  60156  0    FinderSyncExt: (AppKit) [com.apple.AppKit:General] (
	0   CoreFoundation                      0x00000001810b6800 __exceptionPreprocess + 176
	1   libobjc.A.dylib                     0x0000000180badeb4 objc_exception_throw + 60
	2   CoreFoundation                      0x0000000180fce724 -[__NSPlaceholderDictionary initWithObjects:forKeys:count:] + 728
	3   CoreFoundation                      0x0000000180fce420 +[NSDictionary dictionaryWithObjects:forKeys:count:] + 52
	4   FinderSync                          0x00000001ec24518c -[FIFinderSyncController setBadgeIdentifier:forURL:] + 140
	5   FinderSyncExt                       0x000000010204e1e0 -[FinderSync setResultForPath:result:] + 120
	6   FinderSyncExt                       0x000000010204cfa8 __41-[FinderSyncSocketLineProcessor process:]_block_invoke + 68
	7   libdispatch.dylib                   0x0000000180db5cb8 _dispatch_call_block_and_release + 32
	8   libdispatch.dylib                   0x0000000180db7910 _dispatch_client_callout + 20
	9   libdispatch.dylib                   0x0000000180dc5fa8 _dispatch_main_queue_drain + 984
	10  libdispatch.dylib                   0x0000000180dc5bc0 _dispatch_main_queue_callback_4CF + 44
	11  CoreFoundation                      0x000000018108315c __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 16
	12  CoreFoundation                      0x0000000181040a80 __CFRunLoopRun + 1996
	13  CoreFoundation                      0x000000018103fc5c CFRunLoopRunSpecific + 608
	14  HIToolbox                           0x000000018b5b9448 RunCurrentEventLoopInMode + 292
	15  HIToolbox                           0x000000018b5b9284 ReceiveNextEventCommon + 648
	16  HIToolbox                           0x000000018b5b8fdc _BlockUntilNextEventMatchingListInModeWithFilter + 76
	17  AppKit                              0x000000018481ac54 _DPSNextEvent + 660
	18  AppKit                              0x0000000184ff0ebc -[NSApplication(NSEventRouting) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 716
	19  AppKit                              0x000000018480e100 -[NSApplication run] + 476
	20  AppKit                              0x00000001847e53cc NSApplicationMain + 880
	21  libxpc.dylib                        0x0000000180c95cd4 _xpc_objc_main + 800
	22  libxpc.dylib                        0x0000000180ca4904 _xpc_main + 324
	23  libxpc.dylib                        0x0000000180c9580c _xpc_copy_xpcservice_dictionary + 0
	24  Foundation                          0x000000018216714c +[NSXPCListener serviceListener] + 0
	25  PlugInKit                           0x000000018ef61bf0 pkIsServiceAccount + 34540
	26  PlugInKit                           0x000000018ef61748 pkIsServiceAccount + 33348
	27  PlugInKit                           0x000000018ef61f74 pkIsServiceAccount + 35440
	28  ExtensionFoundation                 0x00000001ebc9b08c EXExtensionMain + 304
	29  Foundation                          0x00000001821c3c04 NSExtensionMain + 204
	30  dyld                                0x0000000180be90e0 start + 2360
)

### Steps to reproduce

It doesn't seem to be deterministic, so I cannot re-produce it intentionally

### Expected behavior

-

### Which files are affected by this bug

-

### Operating system

Mac OS

### Which version of the operating system you are running.

Sonoma 14.1

### Package

Appimage

### Nextcloud Server version

23.1

### Nextcloud Desktop Client version

3.10.1

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 3.4.2 to 3.4.4)

### Are you using the Nextcloud Server Encryption module?

Encryption is Enabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [X] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by kmpeterson** [comment] 2023-11-22 02:14
This is biting me as well, though in my case the crash is immediate.  The Finder support - the green checkmarks in Finder windows disappear and the Nextcloud right-click options are unavailable.

**Comment by joshtrichards** [comment] 2024-08-16 05:45
With or without VFS enabled?

**Comment by ataub1** [comment] 2024-08-21 20:49
without VFS enabled.

yes, I'm still experiencing this, but very very rarely, in the meantime the extension runs without crashing for days or weeks

**Comment by ataub1** [comment] 2024-09-20 07:33
Not really, icons never really showed up in my case since I have OneDrive and Google Drive installed, which causes conflicts with icon overlays. The problem was the context menu in Finder not showing up due to a crashed nextcloud finder extension. I mostly use the context menu to create/copy links to files in nextcloud.

**Comment by claucambra** [comment] 2024-10-29 05:58
This is a duplicate of #5193 but thanks for the crash report, it is helpful :)

**Closed by claucambra** 2024-10-29 05:58 UTC
Labels: 0. Needs triage, bug, os: :apple: macOS, crash, feature: 🐚 shell integration
