### ISSUE TITLE
master release blocking issues

### ISSUE THREAD

**Issue by mgallien** [nextcloud/desktop#6774] opened 2024-05-22 07:53 UTC
- [x] https://github.com/nextcloud/desktop/issues/6760
- [x] https://github.com/nextcloud/desktop/issues/6744
- [x] https://github.com/nextcloud/desktop/issues/6770
- [x] https://github.com/nextcloud/desktop/issues/6769
- [x] https://github.com/nextcloud/desktop/issues/6768
- [x] https://github.com/nextcloud/desktop/issues/6992

**Comment by diegodan1893** [comment] 2024-06-16 11:07
Hi, I'm sorry for the spam, but there is a serious bug that was fixed in 3.12.3 but then appeared again in all releases since then. I don't know if it should be added to this list.

The bug is that the Windows client stops syncing moved or renamed files (https://github.com/nextcloud/desktop/issues/6721).

More context:
- [Forum thread from the last time this happened](https://help.nextcloud.com/t/nc-client-3-12-0-not-recognizing-file-renaming-in-windows/183635/8)
- [New forum thread from the regression](https://help.nextcloud.com/t/file-rename-changes-not-synced/193334)

**Closed** 2024-09-06 09:15 UTC
Labels: 1. to develop, bug, overview, regression, approved
