### ISSUE TITLE
Release 3.4.1

### ISSUE THREAD

**Issue by mgallien** [nextcloud/desktop#4089] opened 2021-12-16 11:49 UTC
### :memo: TO DO
 - [x] :arrow_up: Bump VERSION.cmake to 3.4.1 and doc/conf.py (release to 3.4.1) in the corresponding stable branch
 - [x] :label: Create tag from corresponding stable branch on the commit introducing the version bump
```
$ git checkout stable-3.4
$ git pull
$ git tag -s -m "Release 3.4.1" v3.4.1 
$ git push origin --tags
```
- [x] :label: Create tag from corresponding stable branch in client-building. Steps to create the tag are the same as the above.
- :factory: Trigger the builds on brander and wait for them to succeed:
    - [x] :penguin: Linux
    - [x] :apple: Mac OS
    - [x] :door: Windows MSI
- :test_tube: Execute the bugfix release test plan for each build:
    - [x] :penguin: Linux
    - [x] :apple: Mac OS
    - [x] :door: Windows MSI
- [x] :book: Get changelog using [github_helper scripts](https://github.com/nextcloud/github_helper/), with previous 3.4 release as origin point
- :book: Create draft pre-release at:
    - [x] [nextcloud/desktop/releases](https://github.com/nextcloud/desktop/releases) with the changelog
    - [x] [nextcloud-releases/desktop/releases](https://github.com/nextcloud-releases/desktop/releases)
- :package: Upload binaries to:
    - [x] the draft pre-release at [nextcloud/desktop/releases](https://github.com/nextcloud/desktop/releases)
    - [x] the draft pre-release at [nextcloud-releases/desktop/releases](https://github.com/nextcloud-releases/desktop/releases)
    - [x] download.nextcloud.com in the user home directory (so still private)
- [x] :old_key: Sign binaries (`ssh -P 2200` to signing VM, then, `cat how-to-sign`, then `scp -P 2200` to download signatures)
- [x] :bellhop_bell: Notify Marketing that the release is ready
- :rocket: When marketing gives the go then publish the draft pre-releases created previously at:
    - [x] [nextcloud/desktop/releases](https://github.com/nextcloud/desktop/releases)
    - [x] [nextcloud-releases/desktop/releases](https://github.com/nextcloud-releases/desktop/releases)
    - [x] run the publish_desktop.sh script on download.nextcloud.com so that the binaries appear at [download.nextcloud.com/desktop/releases](https://download.nextcloud.com/desktop/releases)
- [x] :up: Change the [updater server](https://github.com/nextcloud/client_updater_server/blob/master/config/config.php) config to serve the release
- [x] :up: Change the [install-clients](https://github.com/nextcloud/nextcloud.com/blob/master/strings.php#L6) config to update the link to the latest release on Nextcloud website

**Comment by PhilippSchlesinger** [comment] 2021-12-16 15:09
Will this release clean up server side mtime problems on files affected by https://github.com/nextcloud/desktop/issues/4016 via restoring previous file versions?

**Comment by allexzander** [comment] 2021-12-27 14:10
> Will this release clean up server side mtime problems on files affected by #4016 via restoring previous file versions?

@PhilippSchlesinger 
Sorry, but, files affected needs to be fixed manually https://github.com/nextcloud/desktop/wiki/Fix-bug-invalid-modification-date

Uploading files with incorrect mtime is fixed in this client version.

**Closed** 2021-12-27 14:12 UTC

**Comment by janseta** [comment] 2021-12-29 11:50
Hi, @PhilippSchlesinger

this script is for MySQL database but I (and meny people) use Nexcloud inside Syncloud, and so we use Postgres database instead of MySQL database

Could you so kind to fix this script (or tell us the changes needed) ?
(My linux and database knolenge is very poor, so I'm not able, but I have 300 Gb of broken files now because of this issue...)

**Comment by ofsahin** [comment] 2022-01-04 22:44
i also use nextcloud and when i try to run the script i got permission error. after searching for a while i found out that it is because my nextcloud folder is mounted with noexec option on docker. tried `mount /config -o remount,exec` but it doesn't work. is there any other way this could be fixed? perhaps with a php script? it would work for other db's as well?

**Comment by Derkades** [comment] 2022-01-04 22:57
> i also use nextcloud and when i try to run the script i got permission error. after searching for a while i found out that it is because my nextcloud folder is mounted with noexec option on docker. tried `mount /config -o remount,exec` but it doesn't work. is there any other way this could be fixed? perhaps with a php script? it would work for other db's as well?

Easy solution: run `bash script.sh` instead of `./script.sh`. Alternatively, tweak your docker volume settings instead of trying to remount while the container is running.

**Comment by ofsahin** [comment] 2022-01-04 23:28
not that easy, already tried `bash /config/www/nextcloud/solvable_files.sh` or inside the dir and `bash solvable_files.sh` i get `find: unrecognized: -newermt`

i use linuxserver io's nextcloud image on alpine

**Comment by ofsahin** [comment] 2022-01-05 12:40
i am trying to rewrite 
`find "$data_dir" -type f ! -newermt "@86400" -exec bash -c 'correct_mtime "$0"' {} \;`
this part with newer instead of newermt i cant figure out what @86400 is
can someone help?

**Comment by lucrito** [comment] 2022-02-07 13:28
What worked for me, without running anything server side (I use docker and running the fix script  would have involved some debugging / research I was not willing to invest time in): 
I had the Problem on two Win 10 clients after the automatic update from Nextcloud to version 3.4.0.

After a brief dig in the internet, I found this thread and tried the script, with the above mentioned result of my laziness ;)

Then I went back to client version 3.3.6 and waited for all syncs to become green.

Then I updated to client version 3.4.2

So far no problems.

**Comment by jfabaf** [comment] 2022-02-21 20:32
> in case anyone else encounters the same problem
> 
> i updated findutils to get newermt functionality and mysql on my nextcloud container
> 
> ```
> apk add --update findutils
> apk add --update mysql mysql-client
> ```
> 
> and ran the code like this: `bash /config/www/nextcloud/solvable_files.sh /data <db_host> <db_user> <db_pwd> <db_name> abc fix` solvable_files.sh <data_dir> <db_host> <db_user> <db_pwd> <db_table> <web_user> <fix,list>

Thank you very much.
Same issue here, I ran this to solve it into linusserver.io nextcloud docker container:
cd /config/www/nextcloud/
apk add --update findutils
apk add --update mysql mysql-client
wget https://raw.githubusercontent.com/nextcloud-gmbh/mtime_fixer_tool_kit/master/solvable_files.sh
chmod a+x solvable_files.sh
./solvable_files.sh /data mysql <dbhost> <dbuser> <dbpass> <dbname> list noscan

And, if list of files are ok:
./solvable_files.sh /data mysql <dbhost> <dbuser> <dbpass> <dbname> fix scan

**Comment by shibacomputer** [comment] 2022-04-21 21:35
https://github.com/nextcloud/desktop/issues/4378 looks like the issue is back.
