### ISSUE TITLE
Connection to server lost after coming back from hybernation on Windows

### ISSUE THREAD

**Issue by muchahagrande** [nextcloud/desktop#2825] opened 2021-01-14 17:42 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour
When Windows comes back from hybernation, Nextcloud Client should reconnect to the server.

### Actual behaviour
Since version 3.1 of the client, it keeps showing a red cross and never reconnect to the server.

### Steps to reproduce
1. Put Windows to hybernate
2. Turn on the PC
3. Login to Windows
4. The Nextcloud client doesn't reconnect to the server

### Client configuration
Client version:

3.1.1

Operating system:
Windows 8.1

OS language:
Spanish

Installation path of client:
"c:\Program Files (x86)\Nextcloud"

### Server configuration

Nextcloud version:
20.0.5

Storage backend (external storage):
SMB

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile: 
Since 3.1: Under the "General" settings, you can click on "Create Debug Archive ..." to pick the location of where the desktop client will export the logs and the database to a zip file.
On previous releases: Via the command line: `nextcloud --logdebug --logwindow` or `nextcloud --logdebug --logfile log.txt`
(See also https://docs.nextcloud.com/desktop/3.0/troubleshooting.html#log-files)

2021-01-14 13:23:41:267 [ warning nextcloud.sync.networkjob ]:	QNetworkReply::UnknownNetworkError "Acceso a la red deshabilitado." QVariant(Invalid)
2021-01-14 13:23:41:267 [ warning nextcloud.sync.credentials.webflow ]:	QNetworkReply::UnknownNetworkError
2021-01-14 13:23:41:267 [ warning nextcloud.sync.credentials.webflow ]:	"Acceso a la red deshabilitado."
2021-01-14 13:23:41:267 [ info nextcloud.sync.networkjob.lscol ]:	LSCOL of QUrl("https://cloud.xxxxx.com/remote.php/dav/files/fjm/") FINISHED WITH STATUS "UnknownNetworkError Acceso a la red deshabilitado."
2021-01-14 13:23:41:267 [ warning nextcloud.sync.discovery ]:	LSCOL job error "Acceso a la red deshabilitado." 0 QNetworkReply::UnknownNetworkError
2021-01-14 13:23:41:268 [ debug nextcloud.sync.discovery ]	[ OCC::DiscoveryMainThread::singleDirectoryJobFinishedWithErrorSlot ]:	5 "Acceso a la red deshabilitado."
2021-01-14 13:23:41:268 [ debug nextcloud.sync.networkjob ]	[ OCC::AbstractNetworkJob::slotFinished ]:	Network job OCC::LsColJob finished for ""
2021-01-14 13:23:41:268 [ debug nextcloud.sync.discovery ]	[ OCC::DiscoveryJob::remote_vio_opendir_hook ]:	OCC::DiscoveryJob(0xfb22bf7170)  ...Returned from main thread
2021-01-14 13:23:41:268 [ debug nextcloud.sync.discovery ]	[ OCC::DiscoveryJob::remote_vio_opendir_hook ]:	5 when opening  msg= "Acceso a la red deshabilitado."
2021-01-14 13:23:41:268 [ warning nextcloud.sync.csync.updater ]:	opendir failed for  - errno 5
2021-01-14 13:23:41:268 [ warning nextcloud.sync.engine ]:	ERROR during  csync_update :  "Se produjo un error al abrir un directorio Acceso a la red deshabilitado."
2021-01-14 13:23:41:268 [ warning nextcloud.gui.activity ]:	Item  "Nextcloud"  retrieved resulted in  "Se produjo un error al abrir un directorio Acceso a la red deshabilitado."
2021-01-14 13:23:41:268 [ info nextcloud.gui.activity ]:	Error successfully added to the notification list:  "Se produjo un error al abrir un directorio Acceso a la red deshabilitado."
2021-01-14 13:23:41:268 [ info nextcloud.sync.database ]:	Closing DB "C:/Users/Usuario/Nextcloud/._sync_34a77c24a58b.db"
2021-01-14 13:23:41:268 [ debug nextcloud.sync.database ]	[ OCC::SyncJournalDb::commitTransaction ]:	No database Transaction to commit
2021-01-14 13:23:41:269 [ info nextcloud.sync.engine ]:	CSync run took  14 ms
2021-01-14 13:23:41:269 [ debug nextcloud.gui.folderwatcher ]	[ OCC::FolderWatcher::pathIsIgnored ]:	* Ignoring file "C:/Users/Usuario/Nextcloud/._sync_34a77c24a58b.db-wal"
2021-01-14 13:23:41:269 [ info nextcloud.gui.folder ]:	Client version 3.1.1stable-Win64 (build 20201222)  Qt 5.12.9  SSL  OpenSSL 1.1.1g  21 Apr 2020
2021-01-14 13:23:41:269 [ warning nextcloud.gui.folder ]:	SyncEngine finished with ERROR
2021-01-14 13:23:41:269 [ info nextcloud.gui.folder ]:	Folder sync result:  2
2021-01-14 13:23:41:270 [ info nextcloud.gui.folder ]:	the last 2 syncs failed
2021-01-14 13:23:41:270 [ debug nextcloud.gui.folder ]	[ OCC::Folder::slotSyncFinished ]:	Sync failed, keeping last sync's local discovery path list
2021-01-14 13:23:41:270 [ info nextcloud.gui.socketapi ]:	Sending SocketAPI message --> "UPDATE_VIEW:C:\\Users\\Usuario\\Nextcloud" to QLocalSocket(0xfb1fb64df0)
2021-01-14 13:23:41:270 [ info nextcloud.gui.application ]:	Sync state changed for folder  "https://cloud.xxxxx.com/remote.php/dav/files/fjm/" :  "Error"

2. Web server error log:
No errors on server side

3. Server logfile: nextcloud log (data/nextcloud.log):
No errors on server side

**Comment by er-vin** [comment] 2021-01-14 18:20
Duplicate of #324

**Closed by er-vin** 2021-01-14 18:20 UTC

**Comment by muchahagrande** [comment] 2021-01-14 18:41
Sorry for the duplicate. I searched for hybernation and not hibernation.
