### ISSUE TITLE
Separate group folders management from external storage management

### ISSUE THREAD

**Issue by pmarini-nc** [nextcloud/desktop#6600] opened 2024-04-01 19:14 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you want to have the same feature implemented.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Feature description

Group folders are a key part of team collaboration and an increasingly used feature in Nextcloud.

As of now their management in the Desktop Client is hidden behind the management of folders defined on a storage area based on External Storage. That is, from the Desktop client user perspective, there is no way to differentiate between a group folder and an external folder.

This is confusing. And even more confusing is that, at first connection, these folders are not synced even if the user explicitly checks the box when asked what to sync.

I'd propose to have:
- the icon in Settings consistent with the one shown in the web ui 
- the wording in the activity flow as specified in #5533

**Comment by marcotrevisan** [comment] 2024-04-10 10:16
Just today I was able to reproduce a weird issue related to this, in group folders and client version 3.12.3 (group folders 15.3.5, NC 27.1.7)  on MacOS:

STEPS
- add an empty folder to a group folder or subfolder;
- check the parent folder on a synchronized client (same user or user in the same group)

Expected: 
- the new folder is available at the client side as well

Observed: 
- the new folder does not show up
- the sync configuration keeps that new folder out of sync and the message says about the folder being "too big or external folder". Too big it's not (it's 0 KB), the other possible cause seems "external". 
- This is a new problem, it never happened 

I'll install the newer verison of group folders (15.3.7) in a few hours and report back.

**Comment by joshtrichards** [comment] 2024-08-16 05:31
Duplicate of #1967

**Closed by joshtrichards** 2024-08-16 05:31 UTC
Labels: enhancement, feature: :minidisc: external storage, feature: :gear: settings
