### ISSUE TITLE
3.0.0 do not start on Windows

### ISSUE THREAD

**Issue by Fl0r3** [nextcloud/desktop#2282] opened 2020-08-18 18:55 UTC
### Expected behaviour
NextCloud client starts

### Actual behaviour
NextCloud client does not start

### Steps to reproduce
[ Have 2.6.5 installed on Windows and uninstall it ]
- Install v.3.0.0
- (Try to) start NextCloud client

### Client configuration
Client version: 3.0.0

Operating system: Windows (latest Update)

OS language: German

Installation path of client: 'C:\Program Files\Nextcloud'

### Server configuration
Not needed

### Logs

1. Client logfile: Output of `nextcloud --logwindow` or `nextcloud --logfile log.txt`
Does not work or provide anything

### Additional info
It was not build by myself but from the Github release (of 3.0.0). Installation processed normally

**Comment by er-vin** [comment] 2020-08-18 20:19
So `nextcloud --logfile log.txt --logdebug` doesn't give you anything?

Is there any message displayed anywhere?

We don't have much information to deal with yet.

**Comment by Fl0r3** [comment] 2020-08-18 21:20
Right, this is very strange.
As it worked before I don´t see a problem at my device.
But of course it´s important to know if others may also affected.
Sadly I haven´t another Windows device for testing.

**Comment by er-vin** [comment] 2020-08-19 09:31
On my end I can't reproduce, but if we don't get any form of output (a log, a crash report, something on the command line) it's going to be impossible to hunt down.

**Comment by CryptoSiD** [comment] 2020-08-23 21:04
I have the same issue on one of my Windows 10 computers.
But it's opening on another one... pretty weird.

I ran "nextcloud --logfile log.txt --logdebug" and it's not writing the log.

I can see the process starting in the task managed but it stops almost instantly.

**Comment by CryptoSiD** [comment] 2020-08-24 00:06
In my case, the issue was related to the Nvidia drivers.

I booted in "safe mode" and Nextcloud 3.0.0 started without issue.

So I rebooted in normal mode and it didn't start... which means the issue is almost likely guaranteed to be caused by a driver.

So I disabled lots of devices and it didn't resolve the issue.

But since I update the Nvidia drivers yesterday I thought this was maybe the cause... so I went back into safe mode... uninstalled the Nvidia drivers and re-installed them in normal mode.

Nextcloud desktop 3.0.0 now starts without issue.

**Comment by VlkaFenryka** [comment] 2020-08-25 17:02
This workflow fixed the crashing app for me:
1. backup the whole directory at `%appdata%/Nextcloud`
2. delete the directory at  `%appdata%/Nextcloud`
3. start the application
4. (manual or copy&paste) reconfig via GUI with settings extracted out of backed up `%appdata%/Nextcloud/nextcloud.cfg`

**Comment by er-vin** [comment] 2020-08-31 07:00
If that's indeed a driver issue as @CryptoSiD seems to imply there won't be much we can do about it.

That said I'm curious about @VlkaFenryka comment. Which of the old nextcloud.cfg key you didn't move over to the new nextcloud.cfg file?

**Comment by Fl0r3** [comment] 2020-09-02 13:24
Deleting `%appdata%/Nextcloud` and also reinstalling in this state doesn´t work for me. Furthermore it´s the same with 3.0.1.
Now I´m running on 2.7.0.15641-rc1 pretty fine.

**Comment by 150d** [comment] 2020-09-04 12:09
Not a driver issue here:

I'm seeing the same issue after update v2 -> v3.0.1 (Client doesn't start, error message in event log.) The machine in question doesn't have NVidia drivers installed.

**Comment by er-vin** [comment] 2020-09-08 11:44
@misch7 does it ring any bell to you?

**Comment by tinkerdudeno1** [comment] 2020-09-13 19:22
I can +1 this issue, same behavior here: No output whatsoever for nextcloud --logdebug --logfile <whatever>,log and no NVidia stuff in the machine. Just a gazillion entries in the event log like such:
`Fehlerbucket , Typ 0
Ereignisname: BEX64
Antwort: Nicht verfügbar
CAB-Datei-ID: 0

Problemsignatur:
P1: nextcloud.exe
P2: 3.0.1.15740
P3: 5f48d634
P4: ntdll.dll
P5: 10.0.18362.1049
P6: b5beef21
P7: 00000000000a1170
P8: c0000409
P9: 000000000000000a
P10: 

Angefügte Dateien:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERED65.tmp.WERInternalMetadata.xml

Diese Dateien befinden sich möglicherweise hier:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportQueue\AppCrash_nextcloud.exe_67bc7dcc4dbcfcac91f92df8d2e6597fbbcdb4c_ce8d0efe_0d6459d8-40ad-4993-bc00-c7799122ca68

Analysesymbol: 
Es wird erneut nach einer Lösung gesucht: 0
Berichts-ID: b8739104-d371-4e9b-8e58-bcd0dbd21bdc
Berichtstatus: 100
Bucket mit Hash: 
CAB-Datei-Guid: 0`

The file that is mentioned in there reads this:

`Version=1
EventType=BEX64
EventTime=132444976183127686
ReportType=2
Consent=1
UploadTime=132444976209971000
ReportStatus=100
ReportIdentifier=86f15273-8c5f-493a-b2b5-1e74f74621d9
IntegratorReportIdentifier=445bb1d5-8ba8-49c5-9c56-46cb67eefdcb
Wow64Host=34404
NsAppName=nextcloud.exe
AppSessionGuid=0000274c-0002-003d-f22c-460d018ad601
TargetAppId=W:000600b962fa8d83a7420aeca418f187856700000908!0000d8d271a3018df742a6236fd280fa2edc0a5d714b!nextcloud.exe
TargetAppVer=2020//08//28:10:02:28!25f968!nextcloud.exe
BootId=4294967295
ServiceSplit=1477574840
TargetAsId=1992
IsFatal=1
EtwNonCollectReason=1
Response.type=4
Sig[0].Name=Anwendungsname
Sig[0].Value=nextcloud.exe
Sig[1].Name=Anwendungsversion
Sig[1].Value=3.0.1.15740
Sig[2].Name=Anwendungszeitstempel
Sig[2].Value=5f48d634
Sig[3].Name=Fehlermodulname
Sig[3].Value=ntdll.dll
Sig[4].Name=Fehlermodulversion
Sig[4].Value=10.0.18362.1049
Sig[5].Name=Fehlermodulzeitstempel
Sig[5].Value=b5beef21
Sig[6].Name=Ausnahmeoffset
Sig[6].Value=00000000000a1170
Sig[7].Name=Ausnahmecode
Sig[7].Value=c0000409
Sig[8].Name=Ausnahmedaten
Sig[8].Value=000000000000000a
DynamicSig[1].Name=Betriebsystemversion
DynamicSig[1].Value=10.0.18363.2.0.0.256.48
DynamicSig[2].Name=Gebietsschema-ID
DynamicSig[2].Value=1031
DynamicSig[22].Name=Zusatzinformation 1
DynamicSig[22].Value=4427
DynamicSig[23].Name=Zusatzinformation 2
DynamicSig[23].Value=4427d14b573cdd75992daf674ca0704b
DynamicSig[24].Name=Zusatzinformation 3
DynamicSig[24].Value=8e3a
DynamicSig[25].Name=Zusatzinformation 4
DynamicSig[25].Value=8e3a30af251df108117dff584f6536e4
UI[2]=C:\Program Files\Nextcloud\nextcloud.exe
LoadedModule[0]=C:\Program Files\Nextcloud\nextcloud.exe
LoadedModule[1]=C:\WINDOWS\SYSTEM32\ntdll.dll
LoadedModule[2]=C:\WINDOWS\System32\KERNEL32.DLL
LoadedModule[3]=C:\WINDOWS\System32\KERNELBASE.dll
LoadedModule[4]=C:\WINDOWS\System32\ucrtbase.dll
LoadedModule[5]=C:\Program Files\Nextcloud\Qt5QuickControls2.dll
LoadedModule[6]=C:\Program Files\Nextcloud\Qt5WebEngineWidgets.dll
LoadedModule[7]=C:\WINDOWS\System32\SHELL32.dll
LoadedModule[8]=C:\WINDOWS\System32\cfgmgr32.dll
LoadedModule[9]=C:\WINDOWS\System32\shcore.dll
LoadedModule[10]=C:\WINDOWS\System32\msvcrt.dll
LoadedModule[11]=C:\WINDOWS\System32\RPCRT4.dll
LoadedModule[12]=C:\WINDOWS\System32\combase.dll
LoadedModule[13]=C:\WINDOWS\System32\bcryptPrimitives.dll
LoadedModule[14]=C:\Program Files\Nextcloud\Qt5Quick.dll
LoadedModule[15]=C:\WINDOWS\System32\windows.storage.dll
LoadedModule[16]=C:\Program Files\Nextcloud\Qt5WebEngineCore.dll
LoadedModule[17]=C:\WINDOWS\System32\msvcp_win.dll
LoadedModule[18]=C:\WINDOWS\System32\USER32.dll
LoadedModule[19]=C:\WINDOWS\System32\win32u.dll
LoadedModule[20]=C:\WINDOWS\System32\sechost.dll
LoadedModule[21]=C:\WINDOWS\System32\ADVAPI32.dll
LoadedModule[22]=C:\WINDOWS\System32\GDI32.dll
LoadedModule[23]=C:\WINDOWS\System32\profapi.dll
LoadedModule[24]=C:\WINDOWS\System32\COMDLG32.dll
LoadedModule[25]=C:\WINDOWS\System32\gdi32full.dll
LoadedModule[26]=C:\WINDOWS\System32\SHLWAPI.dll
LoadedModule[27]=C:\WINDOWS\System32\powrprof.dll
LoadedModule[28]=C:\WINDOWS\System32\UMPDC.dll
LoadedModule[29]=C:\WINDOWS\System32\OLEAUT32.dll
LoadedModule[30]=C:\WINDOWS\System32\kernel.appcore.dll
LoadedModule[31]=C:\Program Files\Nextcloud\Qt5Qml.dll
LoadedModule[32]=C:\WINDOWS\System32\cryptsp.dll
LoadedModule[33]=C:\WINDOWS\System32\PSAPI.DLL
LoadedModule[34]=C:\WINDOWS\System32\WS2_32.dll
LoadedModule[35]=C:\Program Files\Nextcloud\Qt5Svg.dll
LoadedModule[36]=C:\Program Files\Nextcloud\Qt5Xml.dll
LoadedModule[37]=C:\WINDOWS\System32\ole32.dll
LoadedModule[38]=C:\WINDOWS\System32\CRYPT32.dll
LoadedModule[39]=C:\WINDOWS\System32\MSASN1.dll
LoadedModule[40]=C:\Program Files\Nextcloud\nextcloudsync.dll
LoadedModule[41]=C:\Program Files\Nextcloud\Qt5Network.dll
LoadedModule[42]=C:\Program Files\Nextcloud\ocsync.dll
LoadedModule[43]=C:\Program Files\Nextcloud\Qt5Widgets.dll
LoadedModule[44]=C:\Program Files\Nextcloud\qt5keychain.dll
LoadedModule[45]=C:\Program Files\Nextcloud\Qt5Gui.dll
LoadedModule[46]=C:\Program Files\Nextcloud\Qt5Core.dll
LoadedModule[47]=C:\Program Files\Nextcloud\VCRUNTIME140.dll
LoadedModule[48]=C:\Program Files\Nextcloud\MSVCP140.dll
LoadedModule[49]=C:\Program Files\Nextcloud\VCRUNTIME140_1.dll
LoadedModule[50]=C:\Program Files\Nextcloud\Qt5QuickTemplates2.dll
LoadedModule[51]=C:\Program Files\Nextcloud\Qt5WebChannel.dll
LoadedModule[52]=C:\Program Files\Nextcloud\Qt5Positioning.dll
LoadedModule[53]=C:\WINDOWS\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.18362.1082_none_73b2803ad816b43c\COMCTL32.dll
LoadedModule[54]=C:\WINDOWS\SYSTEM32\dbghelp.dll
LoadedModule[55]=C:\WINDOWS\SYSTEM32\USP10.dll
LoadedModule[56]=C:\WINDOWS\SYSTEM32\VERSION.dll
LoadedModule[57]=C:\WINDOWS\SYSTEM32\WINMM.dll
LoadedModule[58]=C:\WINDOWS\SYSTEM32\WINSPOOL.DRV
LoadedModule[59]=C:\WINDOWS\System32\bcrypt.dll
LoadedModule[60]=C:\WINDOWS\SYSTEM32\USERENV.dll
LoadedModule[61]=C:\WINDOWS\SYSTEM32\dhcpcsvc.DLL
LoadedModule[62]=C:\WINDOWS\SYSTEM32\IPHLPAPI.DLL
LoadedModule[63]=C:\WINDOWS\SYSTEM32\ncrypt.dll
LoadedModule[64]=C:\WINDOWS\System32\NSI.dll
LoadedModule[65]=C:\WINDOWS\SYSTEM32\Secur32.dll
LoadedModule[66]=C:\WINDOWS\SYSTEM32\urlmon.dll
LoadedModule[67]=C:\WINDOWS\SYSTEM32\WINHTTP.dll
LoadedModule[68]=C:\WINDOWS\SYSTEM32\DWrite.dll
LoadedModule[69]=C:\WINDOWS\SYSTEM32\dwmapi.dll
LoadedModule[70]=C:\WINDOWS\SYSTEM32\msdmo.dll
LoadedModule[71]=C:\WINDOWS\SYSTEM32\dxgi.dll
LoadedModule[72]=C:\WINDOWS\SYSTEM32\d3d11.dll
LoadedModule[73]=C:\WINDOWS\SYSTEM32\HID.DLL
LoadedModule[74]=C:\WINDOWS\SYSTEM32\dxva2.dll
LoadedModule[75]=C:\WINDOWS\SYSTEM32\d3d9.dll
LoadedModule[76]=C:\Program Files\Nextcloud\zlib.dll
LoadedModule[77]=C:\Program Files\Nextcloud\libcrypto-1_1-x64.dll
LoadedModule[78]=C:\WINDOWS\SYSTEM32\UxTheme.dll
LoadedModule[79]=C:\WINDOWS\SYSTEM32\MPR.dll
LoadedModule[80]=C:\WINDOWS\SYSTEM32\NETAPI32.dll
LoadedModule[81]=C:\WINDOWS\SYSTEM32\WINMMBASE.dll
LoadedModule[82]=C:\WINDOWS\SYSTEM32\DNSAPI.dll
LoadedModule[83]=C:\WINDOWS\SYSTEM32\PROPSYS.dll
LoadedModule[84]=C:\WINDOWS\SYSTEM32\NTASN1.dll
LoadedModule[85]=C:\WINDOWS\SYSTEM32\iertutil.dll
LoadedModule[86]=C:\WINDOWS\SYSTEM32\dxcore.dll
LoadedModule[87]=C:\WINDOWS\SYSTEM32\CRYPTBASE.DLL
LoadedModule[88]=C:\WINDOWS\SYSTEM32\NETUTILS.DLL
LoadedModule[89]=C:\WINDOWS\SYSTEM32\SRVCLI.DLL
LoadedModule[90]=C:\WINDOWS\SYSTEM32\SSPICLI.DLL
LoadedModule[91]=C:\Program Files\Nextcloud\Qt5QuickWidgets.dll
LoadedModule[92]=C:\Program Files\Nextcloud\Qt5PrintSupport.dll
LoadedModule[93]=C:\WINDOWS\System32\IMM32.DLL
LoadedModule[94]=C:\Program Files\Nextcloud\platforms\qwindows.dll
LoadedModule[95]=C:\WINDOWS\SYSTEM32\WTSAPI32.dll
LoadedModule[96]=C:\WINDOWS\SYSTEM32\opengl32.dll
LoadedModule[97]=C:\WINDOWS\SYSTEM32\GLU32.dll
LoadedModule[98]=C:\WINDOWS\System32\MSCTF.dll
LoadedModule[99]=C:\WINDOWS\System32\DriverStore\FileRepository\igdlh64.inf_amd64_82548830eadb8221\ig9icd64.dll
OsInfo[0].Key=vermaj
OsInfo[0].Value=10
OsInfo[1].Key=vermin
OsInfo[1].Value=0
OsInfo[2].Key=verbld
OsInfo[2].Value=18363
OsInfo[3].Key=ubr
OsInfo[3].Value=1082
OsInfo[4].Key=versp
OsInfo[4].Value=0
OsInfo[5].Key=arch
OsInfo[5].Value=9
OsInfo[6].Key=lcid
OsInfo[6].Value=1031
OsInfo[7].Key=geoid
OsInfo[7].Value=94
OsInfo[8].Key=sku
OsInfo[8].Value=48
OsInfo[9].Key=domain
OsInfo[9].Value=0
OsInfo[10].Key=prodsuite
OsInfo[10].Value=256
OsInfo[11].Key=ntprodtype
OsInfo[11].Value=1
OsInfo[12].Key=platid
OsInfo[12].Value=10
OsInfo[13].Key=sr
OsInfo[13].Value=0
OsInfo[14].Key=tmsi
OsInfo[14].Value=569959
OsInfo[15].Key=osinsty
OsInfo[15].Value=3
OsInfo[16].Key=iever
OsInfo[16].Value=11.1082.18362.0-11.0.210
OsInfo[17].Key=portos
OsInfo[17].Value=0
OsInfo[18].Key=ram
OsInfo[18].Value=8072
OsInfo[19].Key=svolsz
OsInfo[19].Value=97
OsInfo[20].Key=wimbt
OsInfo[20].Value=0
OsInfo[21].Key=blddt
OsInfo[21].Value=190318
OsInfo[22].Key=bldtm
OsInfo[22].Value=1202
OsInfo[23].Key=bldbrch
OsInfo[23].Value=19h1_release
OsInfo[24].Key=bldchk
OsInfo[24].Value=0
OsInfo[25].Key=wpvermaj
OsInfo[25].Value=0
OsInfo[26].Key=wpvermin
OsInfo[26].Value=0
OsInfo[27].Key=wpbuildmaj
OsInfo[27].Value=0
OsInfo[28].Key=wpbuildmin
OsInfo[28].Value=0
OsInfo[29].Key=osver
OsInfo[29].Value=10.0.18362.1082.amd64fre.19h1_release.190318-1202
OsInfo[30].Key=buildflightid
OsInfo[30].Value=8e98911c-2910-4350-b85e-bd689da50104
OsInfo[31].Key=edition
OsInfo[31].Value=Professional
OsInfo[32].Key=ring
OsInfo[32].Value=Retail
OsInfo[33].Key=expid
OsInfo[34].Key=containerid
OsInfo[35].Key=containertype
OsInfo[36].Key=edu
OsInfo[36].Value=0
File[0].CabName=WERInternalMetadata.xml
File[0].Path=WER4C7B.tmp.WERInternalMetadata.xml
File[0].Flags=327683
File[0].Type=5
File[0].Original.Path=\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER4C7B.tmp.WERInternalMetadata.xml
FriendlyEventName=Nicht mehr funktionsfähig
ConsentKey=BEX64
AppName=Nextcloud
AppPath=C:\Program Files\Nextcloud\nextcloud.exe
NsPartner=windows
NsGroup=windows8
ApplicationIdentity=5C4EA9851A2165CEE9732EAD51126F28
MetadataHash=1135220395`

3.0.1 running fine on two other W10 PCs, just this one has issues. I reverted to 2.6.5 and everything works like it should. I was doing some reading that some time back there was an issue with Intel graphics cards that resulted in the same "not even a log"-behevior. 
I know this is quite thin but maybe it's of any help...

**Comment by misch7** [comment] 2020-09-14 16:26
> 
> 
> @misch7 does it ring any bell to you?

@er-vin Not really, I only could think of a VC Runtime issue / DLL incompatibility at the moment.

Maybe it's worth trying to install the latest VC 2019 Runtime on those failing machines, then reboot and see if this solves the issue:
https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads

Direct download links:

64-bit: https://aka.ms/vs/16/release/vc_redist.x64.exe
32-bit: https://aka.ms/vs/16/release/vc_redist.x86.exe

**Comment by misch7** [comment] 2020-09-14 16:42
**Alternatively BEFORE installing the VC Redist from above:**

If you're on 64-bit: Could you try to put the `api-ms-win-core-*.dll` files contained in this ZIP to the Nextcloud program folder (`C:\Program Files\Nextcloud`)?

[api-ms-win-core-bin-x64.zip](https://github.com/nextcloud/desktop/files/5219811/api-ms-win-core-bin-x64.zip)

They are taken from `C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\Llvm\x64\bin` and it could be possible that we need them. I suspect conflicting versions could be loaded from the Windows\system32 directory otherwise. Just a shot in the dark ;)

**Comment by tinkerdudeno1** [comment] 2020-09-14 18:16
Thanks for the shot in the dark, but I'm afraid the problem persists: Copying the dlls in the nextcloud program dir does not change anything, neither does installting the latest redist. Still: No logs, just a myriad of event log entries like the one posted above.

I am, however, able to start nextcloud when I boot Windows in safe mode. So maybe it really is a driver issue here. Running this on a Acer Switch SA5-271 with a Intel i5-6200U (HD Graphics 520).  No NVidia stuff going on here.

**Comment by tinkerdudeno1** [comment] 2020-09-14 18:55
Got it! Updated my Intel 520 Graphics driver (damn thing took me 30 minutes: had to manually uninstall, cut off the network, reboot like 10 times before finally being able to install the new driver. The [intel site](https://www.intel.de/content/www/de/de/support/articles/000027538/graphics/graphics-for-7th-generation-intel-processors.html) was very helpful, though) 
Now Nextcloud runs like a charm!

**Comment by er-vin** [comment] 2020-09-15 07:57
OK, I'm tempted to just close it blaming the GPU drivers like I did initially. I'll give it a bit of time for the other people in this ticket to make sure they got up to date intel and nvidia drivers before closing though.

**Comment by 150d** [comment] 2020-09-15 12:05
Is this really a likely root cause for the issue?

@CryptoSiD reported that the error went away for him after changing NVidia drivers.
@tinkerdudeno1 reported that the error went away for him after changing Intel drivers.

Both reporters did not modify the respective "other" driver.

Isn't it much more likely that the issue is neither the NVidia nor the Intel driver, but some dependency that both setups happen to include?

**Comment by er-vin** [comment] 2020-09-15 12:26
> Is this really a likely root cause for the issue?

Actually yes.
 
> @CryptoSiD reported that the error went away for him after changing NVidia drivers.
> @tinkerdudeno1 reported that the error went away for him after changing Intel drivers.
> 
> Both reporters did not modify the respective "other" driver.
> 
> Isn't it much more likely that the issue is neither the NVidia nor the Intel driver, but some dependency that both setups happen to include?

The thing is, the new windows uses QtQuick which in turn uses OpenGL. On Windows this will through the Qt provided ANGLE which will then make the Direct3D calls on the driver. Bugs in the driver can either get it to crash there (since ANGLE might exercise paths that Direct3D only apps won't) or get ANGLE to assert if it detects an inconsistent state.

Can I completely exclude a bug in ANGLE? Obviously not. But IME crashes between ANGLE and the driver are very often due to the driver or disappear on driver update.

**Comment by 150d** [comment] 2020-09-15 12:39
Understood, thanks.

Might there be a way to narrow this down by e.g. outputting an error message (or log entry) or is this impossible because of the runtime failing before any "productive" code is even executed?

**Comment by er-vin** [comment] 2020-09-15 12:50
From the comments in here it really looks like it's bailing out too early for us to catch it.

**Comment by Malspherus** [comment] 2020-10-02 01:28
Hi, I get the same error but with a little less output for some reason and there are more people mentioning it on the forum (https://help.nextcloud.com/t/windows-client-3-0-2-crashes-immediately/93452/8):
```Name der fehlerhaften Anwendung: nextcloud.exe, Version: 3.0.2.15836, Zeitstempel: 0x5f6c9b24
Name des fehlerhaften Moduls: ntdll.dll, Version: 10.0.18362.1049, Zeitstempel: 0xb5beef21
Ausnahmecode: 0xc0000409
Fehleroffset: 0x00000000000a1170
ID des fehlerhaften Prozesses: 0x39b4
Startzeit der fehlerhaften Anwendung: 0x01d6985943f1bb31
Pfad der fehlerhaften Anwendung: C:\Program Files (x86)\Nextcloud\nextcloud.exe
Pfad des fehlerhaften Moduls: C:\WINDOWS\SYSTEM32\ntdll.dll
Berichtskennung: 1454395a-b939-4f3a-bb77-40d2f7f90d66
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist: 
```

I'm on an Acer Switch Alpha 12 with an i7-6500U - which also uses the HD Graphics 520 just like @tinkerdudeno1

**Comment by tinkerdudeno1** [comment] 2020-10-02 17:59
@Malspherus so what's your Intel graphics driver version? Have you tried updating it? I'm running fine now on 100.8691.
![driver](https://user-images.githubusercontent.com/65307209/94954693-c2619c00-04e9-11eb-9550-dff969d813b3.png)

**Comment by Malspherus** [comment] 2020-10-02 19:42
I'm still on 22.20.16.4691, I'll try updating, thanks for the tip!

**Comment by er-vin** [comment] 2020-10-05 08:24
> I'm still on 22.20.16.4691, I'll try updating, thanks for the tip!

Please let us know how this goes, but I really think it'll end up being closed as a driver issue...

**Comment by rottriges** [comment] 2020-10-05 15:12
Hello together, 

I have the same issue here on an acer switch SA5-271 with Intel hd graphics 520 driver version 22.20.16.4691. 

I tried to update on the latest intel driver but it is not possible. 

I got following message: Error=> The driver that is being installed has not been validated for this computer. Get the appropriate driver from the manufacturer of your computer. 

Unfortunately acer does not provide a newer version.

**Comment by nagi121** [comment] 2020-10-05 16:10
I had the same Problem with Intel HD 520. I uninstalled the custom driver, rebooted and installed the intel driver. The Problem remained. After deleting `%appdata%/Nextcloud`, Nextcloud client works as expected.

**Comment by tinkerdudeno1** [comment] 2020-10-05 17:14
@rottriges Had the same problem, just follow the Intel guide I posted above. I had to: Download the driver, cut off my network, uninstall any Intel stuff in programs and features, uninstall the device in the device manager (do this twice because Windows falls back to some legacy driver) and once the device was shown as "Microsoft Basic Display Adapter", I was finally able to install the new driver. In-between reboot like 237 times.

**Comment by rottriges** [comment] 2020-10-06 16:16
@nagi121 and @tinkerdudeno1 : Thank you for your support! 
It was really hard work to un- and re-install the intel stuff but now Nextcloud client works as it should.

**Comment by er-vin** [comment] 2020-10-07 06:17
Alright, since most comments here really seem to point to the GPU drivers I'll just close this. Not much we can do about it unfortunately.

**Closed by er-vin** 2020-10-07 06:17 UTC
Labels: bug, needs info, os: :door: Windows

**Comment by 150d** [comment] 2020-11-21 14:27
Since it is not always possible to update the driver, is there an alternate version of the NextCloud application that does not use the critical components? Will the v2 line continue to be maintained?

**Comment by er-vin** [comment] 2020-11-23 13:18
> Since it is not always possible to update the driver, is there an alternate version of the NextCloud application that does not use the critical components? Will the v2 line continue to be maintained?

I know this can be frustrating but the answers are: no and no.

**Comment by 150d** [comment] 2021-01-09 23:47
I can confirm that on a Intel HD P630, the client version v3.1.1 started fine after I updated the Intel driver version from v22.20.16.4729 to v26.20.100.6951 (download from Microsoft catalog, couldn't find anything on Intel's pages).
