### ISSUE TITLE
nextcloud Dekstop 3.1.0 crashes under macOS 11.1

### ISSUE THREAD

**Issue by dkoeh** [nextcloud/desktop#2727] opened 2020-12-16 06:12 UTC
nextcloud Desktop 3.1.0 starts and closes immediately - no error message, nothing. Version 3.0.3 ran without problems before.

### Expected behaviour
after opening nextcloud Desktop should run

### Actual behaviour
nextcloud Desktop app closes immediately

### Steps to reproduce
1. open nextcloud Desktop 3.1.0
2. nextcloud Desktop 3.1.0 closes after couple seconds
3.

### Client configuration
Client version: 3.1.0

Operating system: macOS 11.1

OS language: English

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From Nextcloud or distro) (Linux only):

Installation path of client:

### Server configuration

Nextcloud version: 20.0.3.2

Storage backend (external storage): none

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile: Also the log window crashes... an Library/Application Support/Nextcloud/logs are empty...

2. Web server error log: no specific entries

3. Server logfile: nextcloud log (data/nextcloud.log): no specific entries

**Comment by er-vin** [comment] 2020-12-16 06:23
Could we have a backtrace? I suspect this might be in fact #2710

**Comment by dkoeh** [comment] 2020-12-16 06:40
[nextcloud_2020-12-16-071745_Dem-Dennis-sein-Dennis-MacBook-Pro-3.txt](https://github.com/nextcloud/desktop/files/5700764/nextcloud_2020-12-16-071745_Dem-Dennis-sein-Dennis-MacBook-Pro-3.txt)

**Comment by er-vin** [comment] 2020-12-16 06:59
Yep, clearly duplicate of #2710

**Closed by er-vin** 2020-12-16 06:59 UTC
Labels: bug, os: :apple: macOS

**Comment by dkoeh** [comment] 2020-12-16 07:17
And when will a fix become available - in a few weeks is not a satisfactory answer, since downgrading now leads to the same error?

**Comment by er-vin** [comment] 2020-12-16 07:21
Yeah well, the bug was present before 3.1.0 in fact. I honestly don't know why it showed up only now. I think this is mostly an unexpected correlation of events (like the timing on how the account states change).

As for 3.1.1 it'll be out before end of the month.

**Comment by vitobotta** [comment] 2020-12-20 21:58
Having the same issue.... @dkoeh did you find a workaround or is it totally unusable at the moment? I just signed up with a Nextcloud hosting provider looking to upload my data, and am stuck :(

**Comment by vitobotta** [comment] 2020-12-20 21:59
BTW I tried the latest daily, it doesn't crash but it gets stuck at "Reconciling changes".

**Comment by vitobotta** [comment] 2020-12-20 22:03
Actually the latest daily seems to work. I had to delete the previous version manually because the installer didn't overwrite it somehow. It's now uploading data.

**Comment by dkoeh** [comment] 2020-12-21 05:38
There is no real workaround, as it is a memory bug - but since a few days ago it is fixed and available in the dailys, so they work again.

**Comment by vitobotta** [comment] 2020-12-21 06:11
@dkoeh gotcha. The daily seems to work well so far :) (fingers crossed... I have renamed a big folder with a big structure containing lots of files, hope it just moves files instead of reuploading everything)
