### ISSUE TITLE
Skip syncing extact file when relinking folder sync connection

### ISSUE THREAD

**Issue by Milokita** [nextcloud/desktop#3651] opened 2021-08-12 09:01 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour
After re-adding sync conection of a synced folder with the server, the desktop client should skip the files just as it once did.

### Actual behaviour
The client try to re-download all the files even if they are identical to those on the cloud. This problem does not exist on latest owncloud desktop client.

### Steps to reproduce
1. Sync a folder which have many sub-folders and files of various size with the cloud (**NO VFS**)
2. Remove the sync connection
3. Re-add the sync connection

### Client configuration
Client version:  V3.3.0

Operating system: Win10

OS language: English

### Server configuration

Nextcloud version:

Storage backend (external storage):

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile: 
Since 3.1: Under the "General" settings, you can click on "Create Debug Archive ..." to pick the location of where the desktop client will export the logs and the database to a zip file.
On previous releases: Via the command line: `nextcloud --logdebug --logwindow` or `nextcloud --logdebug --logfile log.txt`
(See also https://docs.nextcloud.com/desktop/3.0/troubleshooting.html#log-files)

**Comment by mgallien** [comment] 2021-08-13 06:57
This is a duplicate of #1383 .
Closing

**Closed by mgallien** 2021-08-13 06:57 UTC
Labels: bug, feature: :arrows_counterclockwise: sync engine
