### ISSUE TITLE
Nextcloud client won't upload files contained in subfolders

### ISSUE THREAD

**Issue by sliwowitz** [nextcloud/desktop#1995] opened 2020-05-19 23:04 UTC
### Expected behaviour
When adding a local folder to sync into a new folder on the server, the folder structure should be recreated at the server, and all files should be uploaded.

### Actual behaviour
The folder structure is recreated on the server, but all folders except the topmost one are empty - i.e. no files get uploaded to any of the subfolders (except for the topmost one). Even after restarting the client, it is first "Checking for changes" to the folders, then gets stuck at "0 second(s) left, 0 B of 3.1 GB, file 0 of 2149" forever. There are 404 errors generated in the apache logs.

### Steps to reproduce
1. Log into an account with the Nextcloud client
2. Add Folder Sync Connection
3. Select an existing local folder, e.g. "testdir" which contains some non-empty subfolders to sync
4. Create a new remote folder "documents"
5. Wait until the client recreates the folder structure
6. Watch the client hang indefinitely
7. Check there have been no files uploaded to any newly create subfolders "testdir/*" except for the root "testdir/" itself

### Client configuration
Client version: 2.6.2-1build1 from Ubuntu 20.04 repos.
Operating system: Ubuntu 20.04
OS language: English
Client package (From Nextcloud or distro) (Linux only): distro

### Server configuration

Nextcloud version: 18.04

Storage backend (external storage): internal ext4 drive

### Logs

1. Client logfile: https://gist.github.com/sliwowitz/bdde96390ddece465ef2edbb76679e86
2. Web server error log: https://gist.github.com/sliwowitz/27cddb6ea0cd6f8f8b9c9f29ec156b4d

### My guess

The requests getting a 404 response attempt to access a different base URL that those with OK responses. I don't how how it's supposed to work, but they seem to be wrong in that they:
1. start with "/remote.php/webdav/" instead of "/remote.php/dav/"
2. do not include the path to the username and the root folder - i.e. "/testdir/dir1" for user "strazce" is queried as "PROPFIND /remote.php/webdav/dir1" resulting in a 404, while the "MKCOL /remote.php/dav/files/strazce/testdir/dir2" which includes the "/files/strazce/testdir" path succeeds, as does "PUT /remote.php/dav/files/strazce/testdir/f"

**Comment by Robin-Wils** [comment] 2020-06-18 20:48
### Issue can be reproduced on Arch
I have the same problem. I would like to sync a godot project, but I currently can't because of this issue. 

My workaround is uploading files as zips, but that isn't the best solution. Speaking of zip, a unzip option in the webclient would be neat for the future.

**Client config**
- OS: Arch
- Nextcloud version: 2.6.4git

**Server config**
I am not quiet sure. I don't self-host it.

**Comment by Fl0r3** [comment] 2020-08-11 19:28
### Issue can be reproduced on Windows
Subfolders stay in sync loop and the remote subfolders stay empty.

**Client config**

- OS: Windows (Update 2019/08)
- Nextcloud Desktop-Client Version 2.6.5 (Windows)

As common use case this is quite an urgent issue!

**Comment by er-vin** [comment] 2020-08-12 06:43
From the logs provided by the initial reporter, I think it's one of those where the E2EE implementation was tripping up sync for regular folders as well. This should be fixed in 2.7.0-rc1. Please test and let us know.

**Comment by sliwowitz** [comment] 2020-08-14 20:10
@er-vin Yes! I tried the tagged v3.0.0 (zip file from the Github Releases page), and the bug is gone. All files uploading as expected. Thank you :-)

**Comment by er-vin** [comment] 2020-08-17 07:27
Good news, thanks for letting us know. I'm closing this one then.

**Closed by er-vin** 2020-08-17 07:27 UTC
Labels: bug
