### ISSUE TITLE
Add Windows 11 Support

### ISSUE THREAD

**Issue by andyxheli** [nextcloud/desktop#3405] opened 2021-06-04 20:48 UTC
For the near future

**Comment by FlexW** [comment] 2021-06-11 10:53
Is it official? Could you provide a link to an official statement?

**Comment by andyxheli** [comment] 2021-06-11 12:39
June 24 will be the lunch day based on rumors Microsoft will talk about it then 🤞🏼

**Comment by FlexW** [comment] 2021-06-11 13:39
I will close this issue because there is no Windows 11 at the moment thus we can not support it.

**Comment by andyxheli** [comment] 2021-06-11 13:42
> I will close this issue because there is no Windows 11 at the moment thus we can not support it.

No problem! I'll keep an eye on it if I hear more or have docs from MS I will update on this ticket. Will that work ?

**Comment by FlexW** [comment] 2021-06-11 14:49
@andyxheli Yes sure, but maybe it will work out of the box. Let's see.

**Comment by andyxheli** [comment] 2021-06-11 15:25
@FlexW Keeping fingers crossed. Hopefully.

**Comment by andyxheli** [comment] 2021-06-15 19:43
@FlexW check this out when you get some time 

https://www.theverge.com/2021/6/15/22535123/microsoft-windows-11-leak-screenshots-start-menu

**Comment by bgausden** [comment] 2021-11-02 02:34
> So, is windows 11 support planned? I installed nextcloud desktop on PC with windows 11 and during sync the icon disapears. I would guess it chrasing.

Yes. It is crashing.

As a work-around, for those who are desperate, it's possible to run the nextcloudcmd in WSL. Assuming you don't need the GUI, installing the nextcloud-desktop-cmd package and dependencies suffices.

Please note however that some hacking is necessary to run nextcloudcmd in WSL due to the WSL kernel not supporting functionality on which nextcloud's dependency 'libqt5core5a' depends. You'll need to install gnu binutils for the 'strip' utility and then 'sudo strip --remove-section=.note.ABI-tag /usr/lib/x86_64-linux-gnu/libQt5Core.so.5'

Not for the faint of heart, but it does work.

**Comment by andyxheli** [comment] 2021-11-02 13:53
I'm sure they're working on it but as we all know when there's a new Operating System this is to be expected Nextcloud is not the only software that doesn't work well with W11 so please be patient with the process.

**Comment by claell** [comment] 2021-11-24 10:30
I really hope this can get a high priority and gets done soon, so I can upgrade my system :)

I also guess that there might already customers affected who upgraded and are now left with a not working client.

**Comment by allexzander** [comment] 2021-12-09 14:36
@claell @andyxheli Just upgraded my laptop and running Nextcloud 3.3.6 desktop client. Seems to be running fine. What exactly is not working?

**Comment by andyxheli** [comment] 2021-12-09 15:10
@allexzander as of right now I'm not have issues on Win11. I was originally currently running on 3.4.1 RC. I'm not sure if @claell is still having issues.

**Comment by vazquezjm** [comment] 2021-12-09 18:09
Running Nexcloud Desktop Client v3.3.6 on Win11 with no issues so far.

**Comment by andyxheli** [comment] 2021-12-09 18:16
@allexzander should we close this issue and any new issues come up new tickets are be created ?

**Comment by andyxheli** [comment] 2021-12-10 13:01
All since the client is working on win11 I'm going to close this ticket. Since the client is supported with 11.

**Closed** 2021-12-10 13:01 UTC
Labels: enhancement, high, technical debt, os: :door: Windows, win11

**Comment by tobiasKaminsky** [comment] 2021-12-13 14:09
@allexzander can you take care that we then announce this also on our website, etc.?

**Comment by aviallon** [comment] 2021-12-13 21:51
In my case the client is still not starting at all, right after installing and rebooting...

**Comment by allexzander** [comment] 2021-12-14 07:22
> In my case the client is still not starting at all, right after installing and rebooting...

@aviallon Which Windows build number? Did you get all the updates? Any antivirus software is blocking the client? Could you attach logs?(better yet, create a separate issue as it is something specific)

**Comment by allexzander** [comment] 2021-12-14 07:27
> @allexzander can you take care that we then announce this also on our website, etc.?

@tobiasKaminsky We announce Windows 8.1+ on our website, what else do we need? In the System Requirements of the Desktop client, we also announce Windows 8.1+. I can change it to something like Windows 8.1+/Windows 11. But, is this needed? We never had a separate line for Windows 10. On this page we also have Windows 8.1+ https://nextcloud.com/install/#install-clients does it need to be changed?

**Comment by aviallon** [comment] 2021-12-14 16:46
> > In my case the client is still not starting at all, right after installing and rebooting...
> 
> @aviallon Which Windows build number? Did you get all the updates? Any antivirus software is blocking the client? Could you attach logs?(better yet, create a separate issue as it is something specific)

I already created an issue (#3879) some time ago, which was closed for being a duplicate of this one.
The one problem is that it crashes before it outputs any log at all... (at least on the console).  
I tried starting it using powershell `cd C:\Program Files\Nextcloud` and `./nextcloud.exe`, but literally nothing happens. It just returns instantly. Nothing appears in the system tray, and the program blinks in the Task Manager.

**Comment by tobiasKaminsky** [comment] 2021-12-15 07:07
> @tobiasKaminsky We announce Windows 8.1+ on our website, what else do we need? In the System Requirements of the Desktop client, we also announce Windows 8.1+. I can change it to something like Windows 8.1+/Windows 11. But, is this needed? We never had a separate line for Windows 10. On this page we also have Windows 8.1+ https://nextcloud.com/install/#install-clients does it need to be changed?

True, then we do not need to do anything.

**Comment by claell** [comment] 2021-12-15 18:42
@allexzander just adding that I never ran Windows 11 because I saw the issues reported here and wanted to make sure they were fixed before upgrading my OS. So I cannot offer any help here.

**Comment by bgausden** [comment] 2021-12-16 08:32
For anyone who comes after:

I also had crashing at start-up which appeared to be related to the virtual file-system (disabling VFS coincided with the crashes ceasing).

I'm now on Windows 11 Pro 21H2 22000.376 and can report the crashing is no-longer occurring.
