### ISSUE TITLE
Add retry button to offline state

### ISSUE THREAD

**Issue by thgoebel** [nextcloud/desktop#5931] opened 2023-07-27 08:25 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you want to have the same feature implemented.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Feature description

There are a couple of issues where Nextcloud Desktop erroneously thinks it is offline, e.g. #4796 #5466. The workaround often is to quit and reopen Nextcloud Desktop.

Proposal: add a "Retry" button that forces a reconnection attempt.

Similar to the "Sync now" button. Such a Retry button is a much better UX than having to quit+reopen, much faster, and much easier to understand, right there at my fingertips.

Yes, #5621 is a good improvement. But sometimes you are impatient (or you don't know that Nextcloud will retry in 1 minute because you don't read PRs) and then you impatiently go through the quit+retry flow.

### Mockup

<img src=https://github.com/nextcloud/desktop/assets/33295590/f3e40bf7-39f6-4190-bafd-f96b46475c56 width=40%>

### Version

Nextcloud Desktop 3.9.1

**Comment by PhilippSchlesinger** [comment] 2023-07-27 10:36
There is currently a PR https://github.com/nextcloud/desktop/pull/5928 open that checks for server availability repeatedly.

**Comment by thgoebel** [comment] 2023-07-27 10:38
See my edit:

> Yes, https://github.com/nextcloud/desktop/pull/5621 is a good improvement. But sometimes you are impatient (or you don't know that Nextcloud will retry in 1 minute because you don't read PRs) and then you impatiently go through the quit+retry flow.

**Comment by joshtrichards** [comment] 2024-08-15 21:13
Duplicate of #5689

**Closed by joshtrichards** 2024-08-15 21:13 UTC
Labels: enhancement, feature: :key: authentication
