### ISSUE TITLE
[Bug]:  upload slowly when open main dialog 

### ISSUE THREAD

**Issue by VuDn5** [nextcloud/desktop#6230] opened 2023-11-20 05:36 UTC
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

The upload speed decreases significantly upon opening the main dialog.
.
 Under normal upload conditions, the speed test registers 270Mbps and completes within 7 seconds. However, upon opening the main dialog, the speed drops to Kbps and takes 1.5 minutes to complete. I've attempted to resolve this issue by trying a different server in Nextcloud and using the desktop client, but encountered the same problem.
 .
 Has anyone encountered this issue similar to mine?
 

### Steps to reproduce

1: the normal case: 
![photo_2023-11-20_12-02-33](https://github.com/nextcloud/desktop/assets/36143595/4d331939-498c-4710-baa0-6f4486c7d554)

2:: when open tray: " Open main dialog": 
![image](https://github.com/nextcloud/desktop/assets/36143595/312603ea-2631-40c8-adad-c4ac61767888)

### Expected behavior

find the root cause and fix it

### Which files are affected by this bug

File big > 200MB or 1GB to see more

### Operating system

Windows

### Which version of the operating system you are running.

Windows 10 

### Package

Appimage

### Nextcloud Server version

27.0

### Nextcloud Desktop Client version

3.10.1

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 3.4.2 to 3.4.4)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [X] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by PhilippSchlesinger** [comment] 2023-11-20 06:58
This is a duplicate of https://github.com/nextcloud/desktop/issues/4918

**Comment by VuDn5** [comment] 2023-11-20 08:20
> This is a duplicate of #4918

This bug is unbelievable, why icon can do that?

**Comment by joshtrichards** [comment] 2023-11-20 21:18
Please go subscribe to #4918 (and upvote it) if you wish to follow progress.

Closing this issue as a duplicate.

**Closed by joshtrichards** 2023-11-20 21:18 UTC
Labels: 0. Needs triage
