### ISSUE TITLE
Windows Client 3.0.1 - resets folder selection on repaint of window in configuration

### ISSUE THREAD

**Issue by ArjenR** [nextcloud/desktop#2404] opened 2020-09-10 08:22 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour
While setting and unsetting the checkmarks this new state should be committed at once.

### Actual behaviour
While editing the folder subscriptions the client was syncing (another) mapsync subscription. Upon finishing that mapsync it switched to another mapsync and repainted (or something like) that the window and reset the edited selections to the previous state for the whole mapsync subscription.

Also during editing the window contents regularly repositions itself making you click wrong and  having tp renavigate to the folder to edit.

### Steps to reproduce
1. Have multiple mapsync subscriptions
2. Edit while sync is running and about to switch to another mapsync.

### Client configuration
Client version: 3.0.1

Operating system: Window 10

OS language: Dutch

**Comment by er-vin** [comment] 2020-09-10 10:39
Duplicate of #2193

**Closed by er-vin** 2020-09-10 10:39 UTC
