### ISSUE TITLE
[Bug]: newlines in filename break sync

### ISSUE THREAD

**Issue by akallabeth** [nextcloud/desktop#6018] opened 2023-09-02 14:26 UTC
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

when a filename contains a newline the client will fail to sync

### Steps to reproduce

1. create a file or folder with a newline in a synced folder
2. observe the sync breaking

### Expected behavior

well, sync the file to the remote

### Which files are affected by this bug

something\nelse.txt

### Operating system

Linux

### Which version of the operating system you are running.

debian 12

### Package

Distro package manager

### Nextcloud Server version

26

### Nextcloud Desktop Client version

3.7.3

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [X] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Additional info

unix systems allow nearly everything in filenames except `/` so maybe other symbols trigger this as well

**Comment by jospoortvliet** [comment] 2023-09-26 19:48
This might be because a newline is on the ignored files list?  https://docs.nextcloud.com/desktop/3.10/architecture.html#ignored-files

BTW impressive, I didn't know you can put newlines in file names, I sure can't manage to do so in the Dolphin file manager.

But then you can put emoji etc in filenams, too. I'm still from the good old 8.3 capitalized characters time so I wouldn't even THINK about trying such stuff 😏

**Comment by akallabeth** [comment] 2023-09-26 20:02
@jospoortvliet can´t find that on the ignored file list (the link you provided)

and I can understand your amusement, had the same when trying to debug this (was not my machine)
so, the person in question was confusing a filename for an epic, but nonetheless figured out how to put these in ;)

anyway, that should just be ignored, but it did break the sync (as in nothing was synced no more)

**Comment by joshtrichards** [comment] 2024-08-16 16:08
Duplicate of #3613

**Closed by joshtrichards** 2024-08-16 16:08 UTC
Labels: 0. Needs triage, bug, feature: :arrows_counterclockwise: sync engine, hotspot: filename handling
