### ISSUE TITLE
Pause sync on limited connections (mobile data)

### ISSUE THREAD

**Issue by itay-grudev** [nextcloud/desktop#1710] opened 2020-01-06 08:30 UTC
Related to: #243 but does not limit scope to Windows. The Linux NetworkManager provides hints for mobile connections with limited data which can be used to provide the same behaviour on Linux as well.

### Expected behaviour
On a mobile connections with the "Restrict background data usage" flag the Nextcloud client should pause sync. The functionality should work via a platform specific abstraction so drivers for different platforms can be added. The same behaviour should be reproduced for Windows.

### Actual behaviour
Currently the Nextcloud Sync would silently eat your data in a matter of minutes as on Gnome you don't even have a tray icon for the Nextcloud client and you don't even know it's running. This costs a lot of money and double so if you are roaming.

My opinion is that this should be prioritised as it impacts a lot of users in a very direct way.

**Comment by isdnfan** [comment] 2020-10-12 08:30
duplicate of #39 - expected/common behaviour is to pause sync when connected to mobile/metered WIFI network.

**Comment by joshtrichards** [comment] 2024-04-07 16:25
Duplicate of #39

**Closed by joshtrichards** 2024-04-07 16:25 UTC
Labels: enhancement, feature-request, feature: :arrows_counterclockwise: sync engine
