### ISSUE TITLE
Improve app identifier string in "devices and sessions" list 

### ISSUE THREAD

**Issue by johkoenig** [nextcloud/desktop#2113] opened 2020-06-21 09:39 UTC
### Expected behaviour
Connect to your nextcloud with the current desktop client. After the connection has been established, the client shows up in the "Devices & Sessions" list with a name that holds sufficient details to identify the computer, e.g. by "$COMPUTERNAME (Sync Client on $OS_TYPE)"

This is my proposal for a information-rich identifier string:
![grafik](https://user-images.githubusercontent.com/42836313/85221364-a3fce800-b3b3-11ea-854f-d1cfaaed550b.png)

### Actual behaviour
After the connection has been established, the client shows up in the "Devices & Sessions" list with the name "Sync Client - Windows".

This is the current identifier string:
![grafik](https://user-images.githubusercontent.com/42836313/85221336-6bf5a500-b3b3-11ea-9f6a-aa0ef22e71df.png)

### Steps to reproduce
see above

### Client configuration
Client version: Version 2.6.4stable-Win64 (build 20200303
Operating system: Win 10 
OS language: DE

### Server configuration
Nextcloud version: 19.0.0.12

**Comment by splitt3r** [comment] 2020-06-21 19:23
Duplicate of https://github.com/nextcloud/desktop/issues/2016

**Comment by er-vin** [comment] 2020-06-22 07:05
I'm not so sure it is a duplicate though, it's not the same string than the one displayed during auth flow (which is even more confusing). I suspect that'd lead to two different fixes.

**Comment by johkoenig** [comment] 2020-06-22 07:14
I agree with @er-vin. There are two topics to discuss seperately:
* The User Agent String shown during desktop app authentication (reading something like _Mozilla/5.0..._)
* The entry in the devices & sessions list (reading _Sync Client - $OS_ right now)

This enhancement proposal is about the second topic of that list. #2016 handles the first topic, the discussion just led to the same solution: _$PCNAME (Sync Client - $OS)_

btw: I think this identifier works for both topics.

**Comment by er-vin** [comment] 2020-06-23 10:48
Agreed, from the user perspective it should be a single string.

But better track it as two issue tickets even if we end up making just one PR for it. This way we make sure one of the places doesn't fall through the cracks.

**Comment by johkoenig** [comment] 2020-06-23 18:32
I opened a similar feature request for the ios app a couple of days ago, see nextcloud/ios#1313
In my eyes, the string format should be used by every app the same way. Since I don't have an android phone, I cannot say how the android apps (files and talk, +others?) handle this. Maybe we should open similar feature requests there also.

**Closed** 2020-10-08 10:42 UTC
Labels: 0. Needs triage, enhancement
