### ISSUE TITLE
[Bug]: File cannot be synchronized

### ISSUE THREAD

**Issue by Ador-able** [nextcloud/desktop#6745] opened 2024-05-10 07:43 UTC
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

The client displays that the synchronization is complete, but the file is not synchronized

### Steps to reproduce

1. Create a folder
2. Rename the folder
3. Move other files to this folder when the synchronization of the renamed folder is not complete
4. Files that are moved will not be synchronized

### Expected behavior

Moved files should be synchronized normally

### Which files are affected by this bug

null

### Operating system

Windows

### Which version of the operating system you are running.

window 11

### Package

Appimage

### Nextcloud Server version

28.0.3

### Nextcloud Desktop Client version

3.13.0

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by PhilippSchlesinger** [comment] 2024-05-10 08:00
This seems to be a duplicate of https://github.com/nextcloud/desktop/issues/6721

**Comment by vagner-dias** [comment] 2024-05-10 13:04
This also happens to any file you try to rename

**Comment by PhilippSchlesinger** [comment] 2024-05-17 15:47
@Ador-able  If this is a duplicate of #6721, please close it and add your valuable details to the other issue.

**Closed** 2024-05-27 05:43 UTC
Labels: 0. Needs triage
