### ISSUE TITLE
Synchronization Settings lost after 3.0.1 update

### ISSUE THREAD

**Issue by slater0013** [nextcloud/desktop#2395] opened 2020-09-09 08:57 UTC
Hello,

We are experiencing a lost of the synchronization settings after updating to version 3.0.1 of the desktop client (migrating from 2.6.4)

2 Customs synchronization settings before upgrade (1 local folder to 1 remote folder)
![image](https://user-images.githubusercontent.com/49311455/92577085-91939b80-f28a-11ea-8d48-7167c78d57a1.png)

And after upgrade
![image](https://user-images.githubusercontent.com/49311455/92577438-ed5e2480-f28a-11ea-9070-72bf8903da7a.png)

Reinstalling the old 2.6 client reverts the problem back to normal sync settings, which make me think that the settings are not overwritten and still present somewhere.

Thank you !
GS.

**Comment by Castiontone** [comment] 2020-09-09 09:55
can confirm

two additions:
- every time I restart the client, 1 configured folder sync connection comes back
- manually adding a missing folder sync connection causes the client to crash at the next restart

**Comment by Pseudodevincent** [comment] 2020-09-09 10:34
Same issue for me. I reverted back to 2.6.5 waiting for next version.

**Comment by Id3aFly** [comment] 2020-09-09 10:41
This looks like a duplicate of #2279 
If it is, you could close this thread to keep the discussion in the main thread..

**Closed** 2020-09-09 12:45 UTC
