### ISSUE TITLE
Password authentication in the nextcloud-desktopclient on every boot

### ISSUE THREAD

**Issue by 0plan** [nextcloud/desktop#1290] opened 2019-06-05 12:20 UTC
on every boot, i have to type my password in the nextcloud-desktopclient to connect with my nextcloud-server. i see this problem in linux mint and fedora. in kali linux does work.

kind regards

**Comment by pianycist** [comment] 2019-06-16 03:18
I have this same problem on my Arch ARM machine and my Manjaro machine.

**Comment by Nesousx** [comment] 2019-07-04 20:11
Hi,

Probably the same issue than: https://github.com/nextcloud/desktop/issues/1292 (which is newer but more commented).

Maybe someone could merge them, or you could add that your impacted as well in the other thread.

Thanks. :)

**Comment by misch7** [comment] 2019-11-30 02:38
Indeed, duplicate of #1292 - closing this here, since there's more activity.

**Closed by misch7** 2019-11-30 02:38 UTC
