### ISSUE TITLE
Nextcloud3.0.1git from AUR on ArchLinux seg fault in libQt5core when opening settings dialog

### ISSUE THREAD

**Issue by AkechiShiro** [nextcloud/desktop#2473] opened 2020-09-26 13:56 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour
Nextcloud client should not segfault when trying to open settings window.

### Actual behaviour
Nextcloud client segfaults when opening the settings menu using tray icon.

### Steps to reproduce
1. In terminal, launch `nextcloud`.
2. Go over tray icon of `nextcloud` and select `settings`.
3. Behold the segmentation fault.

### Client configuration
Client version: Nextcloud version 3.0.1git
```
Git revision f021db125a0f1f006c4b40d7db0a4b2d0c025de3
Using 'OpenSSL 1.1.1h  22 Sep 2020'
```

Operating system: `Linux username 5.8.10-arch1-1 #1 SMP PREEMPT Thu, 17 Sep 2020 18:01:06 +0000 x86_64 GNU/Linux`

OS language: `en_US`

Qt version used by client package (Linux only, see also Settings dialog): 
```
Using Qt 5.15.1, built against Qt 5.15.1
Using Qt platform plugin 'xcb'
```

Client package (From Nextcloud or distro) (Linux only):  `nextcloud-desktop-git` from [AUR](https://aur.archlinux.org/packages/nextcloud-desktop-git/).

Installation path of client: `nextcloud-desktop-git /usr/bin/nextcloud`

### Logs

1. [Client logfile](https://gist.github.com/AkechiShiro/3165597d36ad05cc952d3b07265373ee) 

2. [Backtrace in gdb](https://gist.github.com/AkechiShiro/182c889175fb02d02c64a455892d6d57)

Something important to note about this issue is that I can `open main dialog` and the crash does not happen even if a window appears to authorize the login, but if I open the `settings` window in the tray icon the seg faults still happens afterwards, this is very specific to the windows `settings` it seems.

If more information is needed I will do everything I can to provide it to further help narrow down the issue.
I'd like to point out that I'm first not using any proxy auto-detect settings, the setting is set to use `system proxy`.
I have also seen other issues about a segfault but none of them seemed to be as exactly as mine is, thus why I'm opening this issue, if I've missed an already open issue, I'll be glad to close this one.

**Comment by er-vin** [comment] 2020-09-29 09:24
I can't reproduce it here but from the backtrace and the client log it looks like it's the chameleon style you're using which goes haywire. Could you use a more common style like fusion or breeze and let us know how this goes?

**Comment by AkechiShiro** [comment] 2020-09-29 12:49
I've had a look at `nextcloud.cfg` in `.config/Nextcloud` but didn't see an option I could change to try others styles you've mentionned, I think that this style is the one by default at least used.

**Comment by er-vin** [comment] 2020-09-29 12:56
I somehow doubt this is the default style. This is not per app in any case that's generally something you set in your desktop environment settings. Which desktop environment are you running btw?

**Comment by AkechiShiro** [comment] 2020-09-29 13:04
I'm currently running i3-gaps at the moment. I've noticed that VLC uses this Chameleon style without any issues but before it wasn't that style by default in VLC neither.

**Comment by er-vin** [comment] 2020-09-29 13:54
For the record I found other apps crashing with that style, I'd advise testing without that style enforced. One thing you could try is starting it with `nextcloud --style fusion`. It should then have a different look and we can see if you still get the crash that way.

**Comment by AkechiShiro** [comment] 2020-09-30 15:12
It works fine with the fusion style I have no seg faults at all. In the end, this problem is related specifically to the Chameleon style, but does this mean that nothing is wrong with the nextcloud client ? Is the bug upstream ?

**Comment by er-vin** [comment] 2020-09-30 15:17
Well, the nextcloud desktop client is known to work with quite a few styles (at least five different ones) on several platforms... so I'm more inclined to blame the style (especially since the stack trace shows the crash a few frames in and I found similar crash reports for other applications when that style is in use).

You should try your luck with whoever provided that style to you. I'll close it to me this is a downstream issue.

**Closed by er-vin** 2020-09-30 15:17 UTC
Labels: bug, feature: :gear: settings, os: :penguin: Linux

**Comment by AkechiShiro** [comment] 2020-11-27 17:32
I just did an upgrade (rebuilt nextcloud-client-git from the AUR).
Here is my new version :
```
Nextcloud version 3.0.82git
Git revision 70dbbbeaa4ebed50f5737174c08873b4ea1b4f9a
Using Qt 5.15.2, built against Qt 5.15.2
Using Qt platform plugin 'xcb'
Using 'OpenSSL 1.1.1h  22 Sep 2020'
Running on Arch Linux, x86_64
```
I am encountering a similar issue but now with both `fusion` style and the `chameleon` one.
Should I open a new issue ? (and post all the debugging information there)

**Comment by er-vin** [comment] 2020-11-30 07:18
Yes please, that's likely something different.
