### ISSUE TITLE
Couldn't remove path/to/file to fulfill dehydration

### ISSUE THREAD

**Issue by Chartman123** [nextcloud/desktop#3156] opened 2021-04-17 21:19 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour
Switch nextcloud folder to virtual file system and remove files locally. All files should be removed without error messages.

### Actual behaviour
I received two errors about files that couldn't be removed properly. These two files are located within a groupfolder where I only have read permissions.

### Steps to reproduce
1. Sync gropufolder with only read permissions
2. Enable virtual filesystem and remove files locally
3. See error during sync that some files couldn't be dehydrated

### Client configuration
Client version: 3.2.0 (Windows)

Operating system: Windows 10 20H2

OS language: German

Installation path of client: C:\Program Files (x86)\Nextcloud\

### Server configuration

Nextcloud version: 21.0.1

Storage backend (external storage):  -

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile: [logs.zip](https://github.com/nextcloud/desktop/files/6330050/logs.zip)

2. Web server error log: -

3. Server logfile: nextcloud log (data/nextcloud.log): Couldn't find anything in the server logs

**Comment by jtagcat** [comment] 2021-04-22 20:55
Same result, but steps to reproduce:
1. Add a locally empty VFS sync folder.
2. Everything is brought in to sync
3. Massive amounts of local files added.
4. ~80% of it has been uploaded
5. User uses 'free up space'
6. All fine, until reboot (when rebooted, used 'exit nextcloud' and had 95% of the transfer done'.
7. No sync, stuck at failing to dehydrate.

**Comment by allexzander** [comment] 2021-04-29 13:46
@Chartman123 

If you go to that folder on your local device and uncheck the "read-only" flag on all the files, will this get fixed? As a temporary workaround.

**Comment by allexzander** [comment] 2021-04-29 13:48
> Same result, but steps to reproduce:
> 
> 1. Add a locally empty VFS sync folder.
> 2. Everything is brought in to sync
> 3. Massive amounts of local files added.
> 4. ~80% of it has been uploaded
> 5. User uses 'free up space'
> 6. All fine, until reboot (when rebooted, used 'exit nextcloud' and had 95% of the transfer done'.
> 7. No sync, stuck at failing to dehydrate.

@jtagcat 

This seems to be something different. Could you create a separate issue for that? Ideally, with screenshots/screen recording of how this looks like. I tried your steps but everything got synced with no problems eventually. Something is missing when I am trying to reproduce it. Appreciate more details.

**Comment by Chartman123** [comment] 2021-04-29 15:16
> @Chartman123 
> 
> If you go to that folder on your local device and uncheck the "read-only" flag on all the files, will this get fixed? As a temporary workaround.

Yes, that worked 👍🏻

**Comment by allexzander** [comment] 2021-04-29 15:21
> > @Chartman123
> > If you go to that folder on your local device and uncheck the "read-only" flag on all the files, will this get fixed? As a temporary workaround.
> 
> Yes, that worked 👍🏻

Thanks. This confirms my idea. Will be working on the fix soon.

**Comment by jtagcat** [comment] 2021-04-30 07:53
> > Same result, but steps to reproduce:
> > 
> > 1. Add a locally empty VFS sync folder.
> > 2. Everything is brought in to sync
> > 3. Massive amounts of local files added.
> > 4. ~80% of it has been uploaded
> > 5. User uses 'free up space'
> > 6. All fine, until reboot (when rebooted, used 'exit nextcloud' and had 95% of the transfer done'.
> > 7. No sync, stuck at failing to dehydrate.
> 
> @jtagcat
> 
> This seems to be something different. Could you create a separate issue for that? Ideally, with screenshots/screen recording of how this looks like. I tried your steps but everything got synced with no problems eventually. Something is missing when I am trying to reproduce it. Appreciate more details.

I did it in a VM, installed the client, and signed in before step 1; nothing else. I don't have anything to add. Not creating an another issue, as It'd be closed as can't reproduce then.

**Comment by allexzander** [comment] 2021-04-30 11:34
> > > Same result, but steps to reproduce:
> > > 
> > > 1. Add a locally empty VFS sync folder.
> > > 2. Everything is brought in to sync
> > > 3. Massive amounts of local files added.
> > > 4. ~80% of it has been uploaded
> > > 5. User uses 'free up space'
> > > 6. All fine, until reboot (when rebooted, used 'exit nextcloud' and had 95% of the transfer done'.
> > > 7. No sync, stuck at failing to dehydrate.
> > 
> > 
> > @jtagcat
> > This seems to be something different. Could you create a separate issue for that? Ideally, with screenshots/screen recording of how this looks like. I tried your steps but everything got synced with no problems eventually. Something is missing when I am trying to reproduce it. Appreciate more details.
> 
> I did it in a VM, installed the client, and signed in before step 1; nothing else. I don't have anything to add. Not creating an another issue, as It'd be closed as can't reproduce then.

@jtagcat We are in a process of making VFS more stable. It would be good if you can create that separate issue later when you have more spare time. I'd appreciate this effort. In the meantime I'll try to reproduce the issue locally a couple of more times. Thx.

**Closed** 2021-05-06 06:26 UTC
Labels: 1. to develop, bug, feature: :minidisc: virtual filesystem
