### ISSUE TITLE
Mac: sidebar icon wrong

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/desktop#4177] opened 2022-01-14 07:45 UTC
Sidebar icon looks wrong, both in dark and light mode
![image](https://user-images.githubusercontent.com/5836855/149470163-2da755fb-cfd9-4501-b686-bb1959566a3b.png)

**Comment by BJKle** [comment] 2022-01-14 11:27
Duplicate for #3695.

**Comment by claell** [comment] 2022-01-18 10:23
Duplicate of #3695

**Closed by claell** 2022-01-18 10:23 UTC
Labels: bug
