### ISSUE TITLE
[Bug]: Desktop client fails to upload but Android/web/dav work just fine (server version 27)

### ISSUE THREAD

**Issue by Morpheu5** [nextcloud/desktop#6117] opened 2023-10-05 12:20 UTC
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

The desktop client stopped syncing correctly when I moved from server 24 to 27 (**fresh install**, not an upgrade)

This carries over from [the forum](https://help.nextcloud.com/t/desktop-client-fails-to-upload-but-android-web-dav-work-just-fine/171513/1) and I suspect there is something wrong with the client, as every other method (Android, web, dav) seems to work fine and also some of the info presented in the client makes little sense.

### Steps to reproduce

1. Install server 27.1.1 from scratch, clean install, dockerized (not AIO), verify that the web UI works – it does – and Android app can connect to it and share and download files – yes indeed.
2. Install desktop client 3.10.0, verify that it can connect to the server
3. Paste a bunch of files in the shared folder and wait…
4. The files aren’t being uploaded
5. Upload a file through Android/web and see it sync through the desktop client correctly.
6. Try to modify the file via desktop: no success – can only delete, anything else is ignored.

### Expected behavior

Syncing works fine. The latest version of the client seemed to work fine with the server version 24.

### Which files are affected by this bug

03.png

### Operating system

Windows

### Which version of the operating system you are running.

13.5.2

### Package

Appimage

### Nextcloud Server version

27.1.1

### Nextcloud Desktop Client version

3.10.0

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 3.4.2 to 3.4.4)

### Are you using the Nextcloud Server Encryption module?

Encryption is Enabled

### Are you using an external user-backend?

- [X] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Nextcloud Server logs

```shell
https://drive.google.com/drive/folders/1O48qKwqxFVRlP1gjNBd2UL_AWKdDV3fA?usp=sharing
```

### Additional info

I installed server 26 and the client appears to be syncing correctly now. This was a long shot suggested from https://github.com/nextcloud/desktop/issues/5519#issuecomment-1758445254 although I am still seeing negative file sizes on occasion. The desktop client is always the latest version.

**Comment by Morpheu5** [comment] 2023-10-05 12:20
![ncclient](https://github.com/nextcloud/desktop/assets/411507/2614905c-42a9-4397-b80d-39ffd2b4a10f)

**Comment by anonbergine** [comment] 2023-10-07 16:25
Negative file size in client window: #5519

**Comment by Morpheu5** [comment] 2023-10-13 09:54
Further info: I tried with server version 26 (latest) as suggested [here](https://github.com/nextcloud/desktop/issues/5519#issuecomment-1759616803) and the client seems a lot happier.

**Comment by joshtrichards** [comment] 2024-08-20 20:00
Since #5519 has been addressed, are you experiencing the problem described in this report any longer?

**Comment by claucambra** [comment] 2024-11-08 08:51
Since there has been needing info for a few months I will go ahead and close the issue, if the problem is still present feel free to reopen!

**Closed by claucambra** 2024-11-08 08:51 UTC
Labels: 0. Needs triage, bug, needs info, feature: :arrows_counterclockwise: sync engine
