### ISSUE TITLE
Folder not synced on Windows with illegal folder name

### ISSUE THREAD

**Issue by xbelt** [nextcloud/desktop#1901] opened 2020-03-27 07:56 UTC
When creating a folder in Nextcloud with an ampersand (or any other illegal folder name in windows), the sync client cannot synchronize the folder

### Expected behaviour
The folder should be synchronized - possibly by removing illegal characters. 

### Actual behaviour
The folder is not synched and no error message is displayed. 

### Steps to reproduce
1. Create a folder in the webbrowser called "Test&Test"
2. Force sync from the client

### Client configuration
Client version: 2.6.4stable-Windowsx64

Operating system: Windows 10 

OS language: german

Installation path of client: not relevant

### Server configuration

Nextcloud version:17.0.1

Storage backend (external storage):

**Comment by alexanderdd** [comment] 2020-04-04 14:36
can confirm & reproduce. This is also true for files. maybe rename this issue to "files/folders with special characters (* : etc) not synced to Windows, no warning "

Seems very **severe** to me because there is not even a warning. Is there a tag to show that this is a severe issue?

For reference: Nextcloud allows to create files/folders with special characters that are not allowed in Windows. These are not allowed in Windows:

```
 < (less than)
 > (greater than)
 : (colon - sometimes works, but is actually NTFS Alternate Data Streams)
 " (double quote)
 / (forward slash)
 \ (backslash)
 | (vertical bar or pipe)
 ? (question mark)
 * (asterisk)
```

Option 1: Nextcloud only allows file and folder names that also work in Windows (should I repost this in server github?)
Option 2: The client warns about every file/folder that cannot be synced due to special characters, and offers a button "rename automatically" that replaces these characters by "-" so that sync can be completed.

**Comment by claell** [comment] 2020-04-04 17:14
This seems to be a duplicate of #464. Please confirm and close this issue if that is the case. Discussion can continued in the original issue then.

**Comment by alexanderdd** [comment] 2020-05-31 10:25
@xbelt see message above?

I think its a duplicate, but I can't close this

**Comment by er-vin** [comment] 2020-08-11 05:51
Duplicate of #464

**Closed by er-vin** 2020-08-11 05:51 UTC
Labels: bug, os: :door: Windows
