### ISSUE TITLE
Issues in desktop client and mobile apps

### ISSUE THREAD

**Issue by shibacomputer** [nextcloud/desktop#4536] opened 2022-04-25 21:40 UTC
**Is your feature request related to a problem? Please describe.**
I'm here because of your CEO's response to the Twitter news, and my feature request is: Don't.

**Describe the solution you'd like**
Finish your half-hearted Dropbox clone before you start work on your half-hearted Twitter clone.

**Describe alternatives you've considered**
A world where Nextcloud has a tight focus, prioritises data integrity, and commits to a cohesive strategic vision instead of branding borderline prototypes as production ready and shipping software updates that endanger user data.

**Additional context**
Fix these first (especially issues that describe data loss) then reconsider again whether Nextcloud should build a Twitter clone:
https://github.com/nextcloud/server/issues
https://github.com/nextcloud/desktop/issues
https://github.com/nextcloud/ios/issues
https://github.com/nextcloud/android/issues

**Comment by jancborchardt** [comment] 2022-05-16 12:06
FYI @tobiasKaminsky @AndyScherzinger transferred to desktop repo, since while also relevant for mobile, it's not fitting in the social repo at all. To be discussed and probably best split into the issues listed.

**Comment by tobiasKaminsky** [comment] 2022-05-19 10:22
Hello,
first of all thanks for taking your time to analyze and collect the topics where you see that our product has problems.
We already try to do as much bug fixing as possible, besides new features.
We try to fix most urgent/annoying ones first. This may either a rare data loss which affects only specific settings, or a "minor" papercut, which affects many users, but has no real consequences.
For this we monitor GitHub bugs, but also check how many reactions/answers a specific bug has.
Thus means that such meta topics collecting different bugs are not helping in terms of helping to prioritize.
Therefore please next time answer in the individual bugs or use reactions on initial post within a bug.
I will close this issue, but will check with my team on those tickets.

Best regards
Tobias

**Closed by tobiasKaminsky** 2022-05-19 10:22 UTC
Labels: enhancement

**Comment by decentral1se** [comment] 2022-05-19 10:30
Classic Stuff :roll_eyes:

**Comment by m4k5ym** [comment] 2022-05-19 11:13
I guess I might look around for an other solution. Nextcloud proofs really nothing. Move it around and then close it in silence. Con fuxk grats guys. May your social stuff make you rich!

**Comment by jaredthirsk** [comment] 2022-05-19 23:43
> Helpful is:
> 
> * Staying positive and friendly in communication (can't stress this enough :)

We want to love Nextcloud.  Please have some empathy for our situation.  I want you to succeed.  You live in a bubble of being inside the development world, and users can be annoying and wrong in how they complain -- I get it, but I hope people in the user world who are having problems can be constructive in suggesting improvements in how to handle a situation like this.  I'm not sure you guys fully get it yet, which is why we are asking for more empathy here, and doing random desperate things like creating a rollup issue on the social project, and asking you to not make a social product -- these are cries for help, even if not articulated precisely.

Situation:
 * Files are being corrupted, by desktop client 3.4.0, with reports of there still being issues in 3.4.4.  We don't know if 3.5.0 fixes it.   Sure there are changelogs, but they are a bit obtuse and we are not the changelog whisperers. (I am a programmer and I couldn't tell.  I could read the code in the commits, but that's not reasonable.)
 * There are a kajillion little gitlab issues and merge commits that are very difficult and time consuming to piece together.
 * What we need is a sort of task force and status page for this kind of issue.
 * There is a wiki page, but it hasn't been updated to acknowledge when or if the issue was resolved, or the status of the six (!) new versions since the wiki page was created. (3.4.1 3.4.2 3.4.3 3.4.4 3.5.0 3.5.1)  A user reported it was still broken in 3.4.4.  I asked in a gitlab issue if it was fixed in 3.5.0 but nobody answered me.
 * There is no single place to discuss the wiki page, or this issue, just a bunch of gitlab issues that are sometimes overly specific to a problem.  Gitlab comments seem too easy to miss.
 * There is one place in the wiki that rubs me the wrong way (honestly, it infuriates me): "In most situations, this is sufficient."  Now this may be entirely true, but what about the rest of us?  I wish there was a status page and blog for major issues like this.  (https://github.com/nextcloud/desktop/wiki/How-to-fix-the-error-invalid-or-negative-modification-date)

> Also keep in mind that it's all a balance – Nextcloud is not and never was just focusing on file sync & share. Calendar & contacts and the app ecosystem have been an integral part of the system from the beginning.

Ok, fine, but this doesn't really help your cause on this issue right now to say this.  How I interpret it: "we care even less about file sync than you thought, and care less about your data loss problems than you thought.  You may care about your ongoing data loss issue, but please be mindful that we are busy at the moment adding more calendar features."

Even for a 100% non-commercial open source project, I would expect some sort of task force response team style communication if a critical emergency sort of issue such as data loss and stoppage of synchronization (potentially leading to more data loss) arose.  But you guys have commercial revenue, so I would expect this even more.

For a 100% non-commercial open source project, there should still be some leadership and diplomatic response shown for critical issues, otherwise, the project should be regarded as unmaintained (and forked by someone who can provide sufficient leadership.)  But you guys have lots of people -- surely someone can show some leadership?

I looked at your job posting board.  It looks like you have a lot of positions to fill.  Here's a random suggestion: 

  * for critical issues, (such as data loss), create an incident in a "Customer Relations Incidents" spreadsheet.
  * Schedule meetings for every two weeks until the issue is resolved.  Discuss customer response, and updates on fixes.
  * People required at the meeting:
     * your future Developer Relations Manager (whose role should perhaps be expanded, if not implied, to monitor and provide initiative on critical gitlab issues such as data loss)
     * Documentation writer, to assist in communicating status to admins (if above person can't handle this)
     * Marketing Manager or delegate
     * Lead Developer or delegate
     * Lead Developer on problem area
     * (One individual may cover multiple roles in some cases, but shouldn't in other cases -- as a developer myself, I suggest letting the developer focus on fixes and nothing else, and taking off burdens of responsibility and stress as much as possible.  Also don't blame the developer for the issue, since testing should be the purview of QA.)
   * Create a status page (a forum post would probably be good enough, if you edit the top post in the thread to keep it updated) to keep people updated, and let people ask for clarification.
   * Link to the status page (or foum post) in the wiki, so that there is a nexus for the problem, rather than a kajillion overly specific gitlab issues that get closed and ignored.

(Post-mortem for me: I manually tracked down modification timestamps for all affected files from client machines and server "versions" folders, and manually set the date from the command line, and didn't lose any data that I know of. Fortunately I only had around 100 files to fix.  I got all my users on 3.5.0.  I let my team know I wasn't happy with how this was handled, and if anyone comes to me with a recommendation for an alternative, I am going to find it difficult to say no.  But if Nextcloud figures out how to respond to a situation like this, it is not too late to convince me.  I am done with this issue, as far as I can tell, and thought I'd share my final thoughts in case it can somehow ease future problems or improve the issue handling response to the extent that it saves me the hassle of migrating off Nextcloud someday, because I don't want to have to do that, because it is extra work for me, and because I love the mission of Nextcloud and want it to succeed.)

**Comment by ThatCoffeeGuy** [comment] 2022-06-17 14:19
> Hello, first of all thanks for taking your time to analyze and collect the topics where you see that our product has problems. We already try to do as much bug fixing as possible, besides new features. We try to fix most urgent/annoying ones first. This may either a rare data loss which affects only specific settings, or a "minor" papercut, which affects many users, but has no real consequences. For this we monitor GitHub bugs, but also check how many reactions/answers a specific bug has. Thus means that such meta topics collecting different bugs are not helping in terms of helping to prioritize. Therefore please next time answer in the individual bugs or use reactions on initial post within a bug. I will close this issue, but will check with my team on those tickets.
> 
> Best regards Tobias

Well, my open issue about data-loss is at 86 reactions now. Is that considered low? Or since it's "only metadata" it doesn't matter as much?:

https://github.com/nextcloud/desktop/issues/4378

**Comment by ph00lt0** [comment] 2022-06-17 15:51
@ThatCoffeeGuy not even just loss of meta data. The solution provided now in the wiki actually doesn't work. At least I can't control what version of the client my users are running, while they share data with each other, so no matter what I can't get this to work in a correct way. No user can update to latest client when that one doesn't sync, but in order to fix the issue everyone needs to be upgraded. Chicken and egg problem.

**Comment by shibacomputer** [comment] 2022-10-30 21:48
Can we please re-open this issue? it appears as though Nextcloud leadership is doubling down on another half-finished feature.
It's hard not to see this as vision-less and reactionary. Nextcloud inserting itself into the complexities of social media while suffering from multiple, serious data-loss bugs is extraordinarily concerning. I appeal to Nextcloud's leadership to divert the resources put into the semi-abandoned Social app, and instead solve some of the issues listed in this issue.
![image](https://user-images.githubusercontent.com/737950/198903039-dd0562f9-2e92-4f06-96d4-613b70bb3139.png)

**Comment by shibacomputer** [comment] 2024-04-09 13:40
Update: now it's Nextcloud's ethical AI. My protest achieved nothing and the worst of the issues still exist. I despair.
