### ISSUE TITLE
Disaster upgrade from 2.6.5 to 3.0 with folder pairs lost and all folder selected in "Choose what to sync"

### ISSUE THREAD

**Issue by godfuture** [nextcloud/desktop#2301] opened 2020-08-21 13:33 UTC
### Expected behaviour
Upgrade should not change my config. This build should not have been released. Quality checks/gates?

### Actual behaviour
Folder pairs gone lost. For the one folder pair that survived the upgrade, all folders have been selected for sync. Damn :(

### Steps to reproduce
1. Install 2.6.5
2. Add three folder pairs
3. Select only one folder from two for sync
4. Upgrade to 3.0

### Client configuration
Client version:

Operating system: win10 x64

OS language: German

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From Nextcloud or distro) (Linux only): 2.6.5

Installation path of client: C:\Program files\Nextcloud

### Server configuration

Nextcloud version: 18.0.5

Storage backend (external storage): local

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile: Output of `nextcloud --logwindow` or `nextcloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the Nextcloud directory)
(See also https://docs.nextcloud.com/desktop/2.3/troubleshooting.html#log-files)

2. Web server error log:

3. Server logfile: nextcloud log (data/nextcloud.log):

**Comment by camilasan** [comment] 2020-08-25 08:49
How did you do the upgrade?

**Comment by godfuture** [comment] 2020-08-27 12:45
> How did you do the upgrade?

I have downloaded setup from Nextcloud, started and followed install wizard (stop current instance of NC, uninstall, install).

**Comment by godfuture** [comment] 2020-08-27 12:49
> Duplicate of #2279 ?

Yes, I guess this is a dub. But my pairs did not come back after restart.

**Comment by lihiniya** [comment] 2020-08-28 07:14
> > How did you do the upgrade?
> 
> I have downloaded setup from Nextcloud, started and followed install wizard (stop current instance of NC, uninstall, install).

I did the same and the same thing happened to me. When I re-selected the folders (exact same as v 2.65) Nextcloud 3.0 started downloading all files again. I ended up terminating the client, deleting C:\Users\###\Nextcloud folder and re-establishing a new sync connection.

**Comment by jospoortvliet** [comment] 2020-08-28 19:46
I'm afraid I saw my client on my laptop do it, too: openSUSE package, built from Git revision ff1750 using Qt 5.15.0, OpenSSL 1.1.1g. Meanwhile, my client on my desktop had no issues and didn't do this at all... Interestingly both sync the same 3 accounts with the same servers...

**Comment by godfuture** [comment] 2020-08-29 16:13
I have updated the client on another win10 x64 machine. Unfortunately the same happened also with 3.0.1. One pair and all folders ticked. 
![nc_client_upgradeFail](https://user-images.githubusercontent.com/4669278/91641229-39a39c00-ea23-11ea-99c7-b29f7ddc31a1.jpg)

**Comment by er-vin** [comment] 2020-08-31 07:04
Duplicate of #2279 indeed. Closing this one, to get the conversation in one place.

**Closed by er-vin** 2020-08-31 07:04 UTC
Labels: 0. Needs triage, needs info
