### ISSUE TITLE
NC CLient 3.0.1 is flipped and upside down on virtualized Win 10

### ISSUE THREAD

**Issue by HATEthePLOT** [nextcloud/desktop#2399] opened 2020-09-10 07:27 UTC
I updated Nextcloud Client to version 3.0.1 in my virtualized Windows 10 pro machine (latest updates are all installed). The virtualization is nothing exotic; just plain Windows to provide some Windows apps on my Linux machine.

### Expected behaviour
The client should launch and be displayed properly.

### Actual behaviour
The display of the client is flipped and upside down. 

<img width="429" alt="nextcloud-client-301" src="https://user-images.githubusercontent.com/24739619/92694484-6a4ed400-f347-11ea-9041-2175426e08b6.png">

### Steps to reproduce
1. Virtualized Win 10 (VirtualBox 6.0.24 with 3D acceletation activated)
2. Upgrade client from 2.6.5 (with prior deinstalling of of client)
3. Behold

### Client configuration
Client version: 3.0.1

Operating system: Windows 10 pro

OS language: German

Qt version used by client package (Linux only, see also Settings dialog): NA

Client package (From Nextcloud or distro) (Linux only): NA

Installation path of client: C:\Program Files\Nextcloud\nextcloud.exe

### Server configuration

Nextcloud version:

Storage backend (external storage):

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile: 
[log.txt](https://github.com/nextcloud/desktop/files/5199866/log.txt)

2. Web server error log:
No Access

3. Server logfile: nextcloud log (data/nextcloud.log):
No Access

####################################################`

**Comment by er-vin** [comment] 2020-09-10 10:54
Oh wow, this one is surprising. Which VM stack is that? For sure I don't have this here in my Windows VM...

**Comment by er-vin** [comment] 2020-09-10 10:56
If I see correctly the icons in your systray, that's VirtualBox? Which settings do you have to the graphics controller? Do you have 3D accel enabled? Here I'm running with VBoxSVGA and no 3D accel.

**Comment by HATEthePLOT** [comment] 2020-09-10 16:05
> If I see correctly the icons in your systray, that's VirtualBox? Which settings do you have to the graphics controller? Do you have 3D accel enabled? Here I'm running with VBoxSVGA and no 3D accel.

Hi,
I use VBoxSVGA and 3D acceleration is activated. I quickly deactivated 3D acceleration and the client is displayed properly. The culprit seems to be somewhere between NC Client and 3D acceleration of Virtualbox (6.0.24).

**Comment by er-vin** [comment] 2020-09-14 12:05
Tested to enable 3D accel here and couldn't reproduce it. This is clearly driver related, nothing we can do about it unfortunately. 

For the record I have only very little trust with 3D acceleration in VMs, especially Virtualbox. I got loads of weird graphical glitches with those over the years depending on the combination of OS/app/guest driver/host driver/GPU.

I'm sorry but I'll close this one.

**Closed by er-vin** 2020-09-14 12:05 UTC
Labels: bug, feature: :cloud: system tray, os: :door: Windows
