### ISSUE TITLE
[Bug]: Nextcloud not launching after 3.5.1 update on Mac OS High Sierra

### ISSUE THREAD

**Issue by Didhuche** [nextcloud/desktop#4588] opened 2022-05-23 11:24 UTC
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

After 3.5.1 update, Nextcloud Desktop does not launch anymore

### Steps to reproduce

1. Right click on the file
2. Click on Share Options
3. The share dialog does not display the option to share by e-mail
...

### Expected behavior

Launch

### Which files are affected by this bug

All

### Operating system

Mac OS

### Which version of the operating system you are running.

High Sierra 10.13.6 (17G14042)

### Package

Official SNAP package

### Nextcloud Server version

23

### Nextcloud Desktop Client version

3.5.1

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [X] Other

**Comment by claucambra** [comment] 2022-05-23 12:01
Hi, this is a duplicate of #4567 so I will close, but I will post here what I posted in the other thread:

>  I'm sorry to say with 3.5.1 we are bumping up our minimum requirements for macOS to 10.14, as the UserNotification system required for actionable notifications in macOS is unavailable on versions <10.14.
>
> If you need the desktop client and are unable to upgrade your OS, we recommend you stick to version 3.5.0 of the desktop client or lower to retain compatibility. Thanks however for reporting

**Closed by claucambra** 2022-05-23 12:01 UTC
Labels: 0. Needs triage
