### ISSUE TITLE
Windows VC Redist unexpected reboot

### ISSUE THREAD

**Issue by simon2plus1** [nextcloud/desktop#961] opened 2018-12-19 16:24 UTC
### Expected behaviour
Tell us what should happen

Next cloud install should install cleanly without reboot

### Actual behaviour
Tell us what happens instead

During the install of NC for windows will reboot without warning after installing the VC redist, I believe this is because on the /quite option is given and not the /norestart this causes the PC to reboot unexpectedly.  Unfortunately this doesnt happen on every PC but I have done about 10-15 installs recently and had this occur 50% of the time

### Steps to reproduce
1. Run nextcloud install
2. 
3.

### Client configuration
Client version: 2.5.1

Operating system:

Windows 10,8,7

OS language:

UK

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From Nextcloud or distro) (Linux only):

Installation path of client:

### Server configuration

Operating system:

Web server:

Database:

PHP version:

Nextcloud version:

Storage backend (external storage):

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

1. Client logfile: Output of `nextcloud --logwindow` or `nextcloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the Nextcloud directory)
(See also https://docs.nextcloud.com/desktop/2.3/troubleshooting.html#log-files)

2. Web server error log:

3. Server logfile: nextcloud log (data/nextcloud.log):

**Comment by jernejs** [comment] 2018-12-23 16:41
Sounds like my problem: https://github.com/nextcloud/desktop/issues/956

**Comment by Lartza** [comment] 2019-01-06 21:35
Duplicate of #831

**Closed by Lartza** 2019-01-06 21:35 UTC
