### ISSUE TITLE
Desktop client crashes on Windows 10 laptop with Intel UHD 620

### ISSUE THREAD

**Issue by go0ran** [nextcloud/desktop#896] opened 2018-11-27 14:08 UTC
### Expected behaviour
Client should start normaly

### Actual behaviour
After start desktop client its crashes

### Steps to reproduce
1. Restart Windows or start Nextcloud manually (doesn't matter).
2. Client crashes.

### Client configuration
Client version: 2.5.0.61560

Operating system:
Widows 10 LTSB 16.07 build 14393.2608

OS language:
Russian

Installation path of client:
C:\Program Files (x86)\Nextcloud

### Logs

Windows journal application log:
Application Name nextcloud.exe, Application Version: 2.5.0.61560, Application Timestamp: 0x5be959aa
Fault Module Name: ig9icd64.dll, Fault Module Version: 25.20.100.6373, Fault Module Timestamp: 0x5bda123a
Exception Code: 0xc0000005
Exception Offset: 0x000000000001fd1e
Faulting process id: 0x2138
Faulting application start time: 0x01d48659439d6b55
Faulting application path: C:\Program Files (x86)\Nextcloud\nextcloud.exe
Faulting module path: C:\Windows\System32\DriverStore\FileRepository\igdlh64.inf_amd64_25e7c5a58c052bc5\ig9icd64.dll

**Comment by TheColin21** [comment] 2018-12-03 11:47
Can confirm. Same crash, Windows 10 Pro 1809 (17763), Intel HD Graphics 630. Client 2.5.0.61560

Name der fehlerhaften Anwendung: nextcloud.exe, Version: 2.5.0.61560, Zeitstempel: 0x5be959aa
Name des fehlerhaften Moduls: ig9icd64.dll, Version: 23.20.16.4973, Zeitstempel: 0x5a96b1e5
Ausnahmecode: 0xc0000005
Fehleroffset: 0x00000000005fbb6b
ID des fehlerhaften Prozesses: 0x1754
Startzeit der fehlerhaften Anwendung: 0x01d48afd9960ca82
Pfad der fehlerhaften Anwendung: C:\Program Files (x86)\Nextcloud\nextcloud.exe
Pfad des fehlerhaften Moduls: C:\WINDOWS\System32\DriverStore\FileRepository\igdlh64.inf_amd64_250db833a1cd577e\ig9icd64.dll
Berichtskennung: c8154bea-67ab-4f3e-a6da-a53541051e86
Vollständiger Name des fehlerhaften Pakets:

**Comment by TheColin21** [comment] 2018-12-03 11:54
> Can confirm. Same crash, Windows 10 Pro 1809 (17763), Intel HD Graphics 630. Client 2.5.0.61560
> 
> Name der fehlerhaften Anwendung: nextcloud.exe, Version: 2.5.0.61560, Zeitstempel: 0x5be959aa
> Name des fehlerhaften Moduls: ig9icd64.dll, Version: 23.20.16.4973, Zeitstempel: 0x5a96b1e5
> Ausnahmecode: 0xc0000005
> Fehleroffset: 0x00000000005fbb6b
> ID des fehlerhaften Prozesses: 0x1754
> Startzeit der fehlerhaften Anwendung: 0x01d48afd9960ca82
> Pfad der fehlerhaften Anwendung: C:\Program Files (x86)\Nextcloud\nextcloud.exe
> Pfad des fehlerhaften Moduls: C:\WINDOWS\System32\DriverStore\FileRepository\igdlh64.inf_amd64_250db833a1cd577e\ig9icd64.dll
> Berichtskennung: c8154bea-67ab-4f3e-a6da-a53541051e86
> Vollständiger Name des fehlerhaften Pakets:

Workaround: Updated to newest Intel Drivers based on the new Modern Windows Driver Model.

**Comment by go0ran** [comment] 2018-12-17 06:06
Update to 2.5.1 b.20181204 solved problem!

**Comment by stfast** [comment] 2019-04-26 15:18
Faulting application name: nextcloud.exe, version: 2.5.2.5231, time stamp: 0x5c90e346
Faulting module name: ig9icd64.dll, version: 25.20.100.6323, time stamp: 0x5ba3fd9c
Exception code: 0xc0000005
Fault offset: 0x000000000001f82e
Faulting process id: 0x2718
Faulting application start time: 0x01d4fbf7b9cedc9b
Faulting application path: C:\Program Files (x86)\Nextcloud\nextcloud.exe
Faulting module path: C:\windows\System32\DriverStore\FileRepository\igdlh64.inf_amd64_8a9535cd18c90bc3\ig9icd64.dll
Report Id: d76feb5f-5850-4b5c-9810-06cb96ee2db9
Faulting package full name:
Faulting package-relative application ID:

**Comment by mjakovina** [comment] 2019-07-27 10:08
I have the samse issue on my laptop with Intel UHD 620 (Acer Aspire 5 A517-51G-546G).
OS is Win10 10 Enterprise 2016 LTSB
But, **when I disable Intel UHD 620 display adapter in Device Manager, Nextcloud client works fine.**
I have discrete NVIDIA Geforce MX150 adapter in laptop, so I can work with UHD 620 disabled.

Obviusly, the problem is with Intel display adapter.

**Comment by mjakovina** [comment] 2019-08-16 16:05
Today I updated to client version 2.5.3
Nextcloud still crashes immediately

**Comment by edmcdonagh** [comment] 2019-09-01 22:47
I have an Intel UHD 620 on a Dell XPS 13 with Windows 1903 Enterprise. 

I have installed the Nextcloud client 2.5.3. The initial sync didn't work properly, then crashed. Every time I restart it, or restart the PC, the client disappears before it can get a list of the folders or sync.

**Comment by Snowman-25** [comment] 2019-09-02 08:50
Same here. Also doesn't work with todays Daily Build.

@camilasan Why is this still at "Needs triage"? This is a critical bug that prevents the application from working on a range of devices!

**Comment by mjakovina** [comment] 2019-10-09 11:12
Bump!
@camilasan, what can we do to make somebody notice this bug again?
It seems it is forgotten. My company cannot move from Dropbox to Nextcloud bocause of this

**Comment by nobarth** [comment] 2019-10-18 08:15
Had a crash on Windows 10  with intel uhd graphics 630.
**Disable Intel UHD 620 display adapter in Device Manager** solve the problem (annoter Nvidia graphic card is installed).

**Comment by Snowman-25** [comment] 2019-10-18 20:39
> **Disable Intel UHD 630 display adapter in Device Manager**
Most people will not have a second graphics card in their Laptop.

**Comment by bunjes** [comment] 2019-11-05 11:16
Same here

**Comment by bunjes** [comment] 2019-11-12 07:18
A possible workaround (at least for our nextcloud 16 here) is to use the [current owncloud client](https://owncloud.com/de/download/#desktop-clients) (version 2.5.4).
Hey nextcloud developers, what does owncloud have that you don't?

**Comment by raimund-schluessler** [comment] 2019-11-21 14:17
This doesn't seem to be a problem unique to the Nextcloud client. I develop an application using Qt 5.13.2 and since I updated the drivers of my graphics card (Intel HD Grapics 520) to version 25.20.100.6576 my application, as well as the Nextcloud client, keeps crashing on startup.

**Comment by raimund-schluessler** [comment] 2019-11-21 15:05
After trying to install Intel driver 26.20.100.6913, which failed because its not compatible with my Windows 10 1607 LTSB and the following restart, it now works even with Intel driver 25.20.100.6576.

**Comment by raimund-schluessler** [comment] 2019-11-22 08:03
This clearly is an issue of the Intel drivers. Please update to a newer version.

I think there is hardly anything reasonable we can do here. We could try to figure out which Qt function call causes the program to crash (for my application it was this line: https://github.com/BrillouinMicroscopy/FPIControl/blob/master/FPIControl/mainwindow.cpp#L195) and try to not use it, but this is a lot of effort and maybe not even possible at all if there is no alternative. I think this is not worth it, since the actual problem lies outside of the client (Intel drivers) and there is a solution to it.

I would tend to close this issue.

**Comment by flummel** [comment] 2020-11-15 11:15
Same issue for me: Nextcloud Client doesn´t start, no error message, simply no reaction. Have re-installed several times.

Windows 10 Pro, Lenovo Thinkpad X270, Intel Core i7-7500U CPU @ 2.70 GHz,  2.90 GHz; OS language: German
Intel (R) HD Graphics 620

Nextcloud Client: 3.0.3 (name of download file).  Installation path: C:\Program Files\Nextcloud

Installation path of client:
C:\Program Files (x86)\Nextcloud

Nextcloud works when: 
1. Intel Graphics 620 is deactivated AND 
2. I start via the nextcloud.exe file

...under other circumstances I don´t get anything. I´d be glad to see that resolved.

**Comment by er-vin** [comment] 2020-11-16 08:58
As mentioned by @raimund-schluessler this is clearly something deep in Qt or the drivers, nothing much we can do about it. Closing it at last.

**Closed by er-vin** 2020-11-16 08:58 UTC
Labels: 0. Needs triage

**Comment by binki** [comment] 2020-12-06 17:58
Does this error happen for people when running `dxdiag`? It seems a lot of programs such as browser or game which use graphics acceleration will silently handle/ignore such errors (and probably fall back to software rendering or something). But `dxdiag` seems like a reliable way to get them to show up/be visible.

When I experienced this on a different system, I found that downgrading the Intel UHD drivers helped with this specific sort of error. I also had different issues because I do have a secondary graphics card but that had stopped showing up in Device Manager. By resetting the mobo by holding down the power button for 30 seconds while the device was unplugged, I was able to get the secondary graphics card to show up in Device Manager again. Sorry for the spam, but maybe this will help someone.

**Comment by Lord-Hambre** [comment] 2020-12-10 16:56
> Same issue for me: Nextcloud Client doesn´t start, no error message, simply no reaction. Have re-installed several times.
> 
> Windows 10 Pro, Lenovo Thinkpad X270, Intel Core i7-7500U CPU @ 2.70 GHz, 2.90 GHz; OS language: German
> Intel (R) HD Graphics 620
> 
> Nextcloud Client: 3.0.3 (name of download file). Installation path: C:\Program Files\Nextcloud
> 
> Installation path of client:
> C:\Program Files (x86)\Nextcloud
> 
> Nextcloud works when:
> 
> 1. Intel Graphics 620 is deactivated AND
> 2. I start via the nextcloud.exe file
> 
> ...under other circumstances I don´t get anything. I´d be glad to see that resolved.

I downloaded drivers from here: https://downloadcenter.intel.com/es/product/80939/Gr-ficos and it worked for me!! :D
PS.: My graphics is Intel HD Graphics 630
Good Luck!
