### ISSUE TITLE
[Bug]: Menu interface became all white (3.14 - Win10)

### ISSUE THREAD

**Issue by VieuFou34** [nextcloud/desktop#7139] opened 2024-09-17 07:10 UTC
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

The Client interface became all white since the 3.11 update. I can see the buttons only when hovering the mouse.
Same with dark or light modes.

### Steps to reproduce

1. Launche Nextcloud desktop
2. Click on the icon near the clock
3. The Nextcloud UI shows up but the colors are not normal

### Expected behavior

The colors should be the same than the last version.

![nextcld bug](https://github.com/user-attachments/assets/e3c5fea2-dc88-4df6-9749-70f8c3710ae6)

### Which files are affected by this bug

Can't say

### Operating system

Windows

### Which version of the operating system you are running.

Windows 10

### Package

Official Windows MSI

### Nextcloud Server version

29.0.7, but unrelated

### Nextcloud Desktop Client version

3.14

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 3.3.6 to 3.4.0)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by tomdereub** [comment] 2024-09-17 13:12
Seems to be a duplicate of https://github.com/nextcloud/desktop/issues/7125.

**Comment by mormegil-cz** [comment] 2024-09-18 13:25
While it might be a duplicate (but note this report is for Windows, while the other one is for Linux), it should be stressed this issue is not only that Nextcloud “is not respecting the system theme”, the problem is that the Nextcloud window is now unusable, as it is now white-on-white. (I.e. maybe the text color does follow the dark mode, while the background does not?)

**Comment by VieuFou34** [comment] 2024-09-18 21:37
Now I have learn no to rush on updates XD

**Comment by fsesterh** [comment] 2024-09-19 06:25
Happens too me on Win10/11 as well. Restart of Nextcloud Desktop does NOT solve the bad UI for me.

**Comment by blinkenlicht** [comment] 2024-09-19 16:21
same here

**Comment by DireMunchkin** [comment] 2024-09-20 12:19
Just FYI as a workaround you can find the last version of desktop, 3.13.4 [over here](https://download.nextcloud.com/desktop/releases/Windows/).

**Comment by scebbers** [comment] 2024-09-21 10:26
I have exactly the same issue after updating to 3.14.0 (Windows desktop client)

**Comment by Leocraft1** [comment] 2024-09-21 17:15
same with me, the ui just looks like sheet

**Comment by VieuFou34** [comment] 2024-09-21 18:43
I will just add a remember, for me the probleme desappeared by itsel. Maybe a graphic card driver occured or I don't know but something happened that I don't remember. Just to to says that now the problem doesn't sho up anymore. Hard to say how comes .

**Comment by VieuFou34** [comment] 2024-09-21 19:32
![Uploading Screenshot_20240920_205346_com.microsoft.office.outlook.jpg…]()

**Closed** 2024-09-21 19:31 UTC
Labels: 0. Needs triage

**Comment by tomdereub** [comment] 2024-09-30 06:57
Still present here on win 10, even after reboot, with nextcloud client 3.14.1.
![image](https://github.com/user-attachments/assets/9a2aed02-12d1-422f-9287-3a445eadf505)

**Comment by fsesterh** [comment] 2024-09-30 08:26
Yep, this one is still open even with 3.14.1

**Comment by rpereyrol** [comment] 2024-10-09 09:42
The same for me with 3.14.1.

**Comment by ryanginn** [comment] 2024-10-19 23:21
Same with 3.14.1

**Comment by ryanginn** [comment] 2024-10-22 08:15
Huh, loads fine on Windows 11 dark mode, but not Windows 10. This is very confusing.

**Comment by bobbolous** [comment] 2024-10-22 08:23
> Huh, loads fine on Windows 11 dark mode, but not Windows 10. This is very confusing.

See this comment: https://github.com/nextcloud/desktop/issues/7378#issuecomment-2428501551

**Comment by ryanginn** [comment] 2024-10-22 08:24
Thanks
