### ISSUE TITLE
Sync Pending - Windows 10

### ISSUE THREAD

**Issue by afzl-wtu** [nextcloud/desktop#4226] opened 2022-01-29 23:53 UTC
This Sync Pending status is very irritating. You can see folder is uploaded to server but it is still showing me it is pending in status.
Also please clean those garbage files with pending status. They keep getting focus. PLease remove .sync_b39e158b5df3.db and other log files in director or do not show pending status.
![image](https://user-images.githubusercontent.com/64379149/151681474-aa522a3d-72d7-41b7-8aa6-cf822b86a530.png)

**Comment by azukaar** [comment] 2022-01-31 12:59
#4201

**Comment by dirrgang** [comment] 2022-02-09 14:32
While possibly related to #4201, it would appear to be a slightly different manifestation. I have the same issue: Files are synchronised properly (as far as I can tell), but all files are shown as *sync pending*.

![grafik](https://user-images.githubusercontent.com/29854606/153221287-4e579c42-244e-4ed1-b4c3-12bcdc0b62ee.png)
![grafik](https://user-images.githubusercontent.com/29854606/153221403-cefa116e-2567-4d99-9460-965d29a592e3.png)

Windows 10,  Nextcloud Desktop-Client Version 3.4.2 (Windows).
I have uploaded the [debug archive](https://nc.dir.li/s/gR3nsLQZeZxe3R3).

**Comment by dirrgang** [comment] 2022-02-28 20:12
Issue persists with client version 3.4.3

**Comment by dirrgang** [comment] 2022-04-02 20:11
I managed to fix it by removing Nextcloud and all Nextcloud files located in AppData as well as the sync folder.

**Comment by pzwahlen** [comment] 2022-04-03 12:57
Hi devs!

Is there anything we can do to help figuring out what is happening here ? I have this problem on new client installations so I am not sure it depends on old files in appdata\{local,roaming}.

I am running 3.4.4 on Win10 21H2 against the official docker image for 23.0.3.

By playing with "Always keep on this device" and then "Free up space", some files would go back to the normal "Available when online" (cloud status icon) and some others would go back to "Sync pending". For those, it would be interesting to know if space is actually freed or not.

Happy to help with debug here and "keep up with the great work!"

**Comment by pzwahlen** [comment] 2022-04-07 19:39
A quick update to let everyone know that 3.5RC3 doesn't help with this problem.

**Comment by pzwahlen** [comment] 2022-04-09 09:49
I think this bug is the same as https://github.com/nextcloud/desktop/issues/4383, except I can see it with many other filetypes.

**Comment by virtaj** [comment] 2022-04-13 16:47
Having same issue with Windows 11.  Desktop client 3.4.4 and Nextcloud 23.0.3 on docker.

**Comment by CoYoNq** [comment] 2022-04-14 17:13
Same issue here, but only with files which size is < 5kb and VFS enabled.
IE, i can create a file (a simple txt with only some chars on it), get it synced, but when i sent it to server, sync state on file still "pending". It only happends with files less than 5kb size. If i add some bytes to the file, it ends getting the right state!
This happends with any kind of file.
I was trying to track this error but with no luck (check full logs of server and client, but no errors found)
Everything performs great (lots of files syncing with no issue, only this little ones fails)
My setup:
Self hosted Nextcloud Hub II (23.0.3) server
20 Win 10 clients (with 3.4.4 version) in an exclusive LAN
About 270gb of files (with any kind of files)

**Comment by pzwahlen** [comment] 2022-04-15 08:47
Now that I read this, I think you are right and this happens on small files. Is there a desktop debug procedure one can follow in order to better understand what is happening ?

**Comment by dnwhoop02** [comment] 2022-04-17 23:33
Same issue here, and it definitely only happens with small files.  In my case there are about 1,600 files under 5KB that stay in the "waiting to sync" state.  These are files that are on the local hard drive, and at some point I told the client to "free up space".  The client freed up all of the bigger files, but left these on the hard drive stuck in this state.  The client periodically tries to sync the 1,600 files again, which is slightly annoying, but the bigger problem with this is that every time I make real changes to other files, or create new files (triggering a sync), the client tries to sync the 1,600 small files first, then it finally gets to the one or two files that actually needed to be sync'd.  I've found that if I right click on these small files and select "Always keep on this device", the status changes to solid green checkmark, then I can right-click them again and clear the checkmark next to "Always keep on this device", and the status changes to green/white checkmark (as it should), and then the sync client will stop worrying about that particular file.  I'm fine with keeping those files on my hard drive since they're small, but unfortunately they are scattered throughout hundreds of folders, so I can't easily select them all and do the "Always keep..." workaround on all of them.

**Comment by pzwahlen** [comment] 2022-05-05 13:18
Hi,

Now that 3.5.0 is out it would be great to tackle this issue. In order to validate and confirm the link with file size, I have done the following.

Wrote a simple Powershell script that writes files with random content. File size is incremented from 0 to 8k in steps of 8 bytes and the file name is the actual content size written in HEX

```ps
$outDir="$PSScriptRoot\nc4226";
if (!(Test-Path -path $outDir)) {new-item -path $outDir -itemtype directory}

for ($i=0; $i -le 8192; $i=$i+8 ) {
  $fSize = $i;
  $fName = $i.ToString("X4");
  $fContent = [Byte[]]::new($fSize);
  $rng = [System.Random]::new();
  $rng.NextBytes($fContent);
  [System.IO.File]::WriteAllBytes("$outDir\$fName", $fContent);
}
```
You can download a zip archive of the output here: <https://cloud-dev.lesz.ch/s/BYT4ktYnqKAkXTL>

When I drop this folder within the NC folder (with Virtual Filesystem enabled) and wait for the initial sync, the folder appears as locally available, as expected:
![image](https://user-images.githubusercontent.com/11704985/166930454-d5955eb0-b19b-4e4d-a9e0-1b5f67567e47.png)

All files within the folder are also locally available, as expected:
![image](https://user-images.githubusercontent.com/11704985/166930513-9fbfea68-a943-43ae-846c-80f8d08d287a.png)

Now if I "Free up space" on the folder, I can see that the empty file gets the correct status but all larger files get the wrong "sync in progress" status:
![image](https://user-images.githubusercontent.com/11704985/166930799-50c05e38-b70f-429c-afcc-dc4f4757738f.png)

I can easily sort the folder by file size and we can see that all files below 4k get the wrong status and all files >4k are showing the correct status:
![image](https://user-images.githubusercontent.com/11704985/166930940-88b08d00-f606-445f-b745-06e02caade5d.png)

Also, any sync activity from this point will trigger a resync of all the file <4k in size (except the empty file).

**Comment by CoYoNq** [comment] 2022-05-22 15:23
Any news regarding this? New Win client (3.5.1) still showing this bug. 
I still trying to track this issue, but can't find any relevant info in server or client log.

**Comment by pzwahlen** [comment] 2022-06-16 12:01
Dear @camilasan @mgallien @allexzander @matthieugallien

According to the repo history you seem to be the devs making changes to the Windows "vfs" and "cfapi" code and therefore you might want to have a look at this bug which (I think) is affecting the entire userbase (Windows+VFS).

I have created a simple reproducer in the issue thread.

Also, I tried to find places where the code would depend on a 4k buffer/size limit and I could only find those two:

https://github.com/nextcloud/desktop/blob/4efe00fecaf88b587c6bcb75f1af17ba1fa12747/shell_integration/windows/NCUtil/CommunicationSocket.cpp#L25

https://github.com/nextcloud/desktop/blob/8f7646d93fe8eea19ceacccf92045bfd77e0dd87/src/gui/folderwatcher_win.cpp#L61

Could one of them be part of the issue ?

Cheers!

**Comment by Dremor** [comment] 2022-07-10 11:02
Interesting note that may or may no be related: even the excluded files get a "pending sync" status icon. Disabling VFS give the correct behaviour.

**Comment by pzwahlen** [comment] 2022-07-18 20:54
I'm just giving a gentle bump to this issue. Could someone add it to the "clients team" board here: https://github.com/orgs/nextcloud/projects/48

This might give it some additional visibility.

**Comment by mgallien** [comment] 2022-07-20 14:36
to be honest, I am working on this but because of poor documentation Microsoft I am struggling to find the exact wrong API call within the desktop client code
but be sure that this is known and not forgotten

**Comment by pzwahlen** [comment] 2022-07-20 15:59
Thx @mgallien, knowing that someone knowledgeable is working on this has made my day! I think we all appreciate the hard work here.

Cheers!

**Comment by BasicUser22** [comment] 2022-08-13 17:27
Hello,
I've got the same problem on about 53000 files.
Nextcloud version

client : 3.5.2
server : 24.0.3
Operating system and version

client : windows 10.0.19044
server : Debian 11
Apache : Apache/2.4.54 (Debian)
PHP version : PHP 8.1.8 (cli) (built: Jul 11 2022 08:55:24) (NTS)

The issue you are facing : I have to keep some files on my desktop because they can’t be “Free up”

Is this the first time you’ve seen this error? (Y/N): Y

Steps to replicate it :
I don’t know actually how to create the problem
But, if I take a problematic file and copy it in a new folder, the problem remains
In the sync.log file (AppData/Roaming/Nextcloud) :

- the initial copy leaves the following trace => the file is stored on the desktop and synchronized

`timestamp 	 duration 	 file 	 instruction 	 dir 	 modtime 	 etag 	 size 	 fileId 	 status 	 errorString 	 http result code 	 other size 	 other modtime 	 X-Request-ID
18:09:22		<file>	8	1	1659990112	5e7d27e78bcf2bd1c22a1ee0999d8adc	1682	00452258oc6lwp0up92s	4		201	0	0	b503a6c9-70ae-4072-9620-80484283c7db`

- when I try to free up the space, I’ve got the following trace :
`[ debug default C:\Users\sysadmin\AppData\Local\Temp\2\windows-10816\client-building\desktop\src\libsync\propagateupload.cpp:300 ]	[ OCC::PropagateUploadFileCommon::slotComputeContentChecksum ]:	Trying to compute the checksum of the file
2022-08-09 20:09:22:925 [ debug default C:\Users\sysadmin\AppData\Local\Temp\2\windows-10816\client-building\desktop\src\libsync\propagateupload.cpp:301 ]	[ OCC::PropagateUploadFileCommon::slotComputeContentChecksum ]:	Still trying to understand if this is the local file or the uploaded one`

I also notice that the desktop client stops suddenly and repeatedly

**Comment by CoYoNq** [comment] 2022-09-04 12:02
Hi!
Any news about this one?
I was trying to see if this bug was related to #3349 but, after a possible fix released, looks like not. Still happening after the bug fix released by @mgallien to solve #3349.
Problem is, syncs continue to try to get the small files in every cycle, and sometimes, depending on the number of files involved, even, crash the client.
Please, give this one some priority, it a very annoying bug that affects the whole vfs system.
Thanks!!!

**Comment by afzl-wtu** [comment] 2022-09-04 19:41
> Hi! Any news about this one? I was trying to see if this bug was related to #3349 but, after a possible fix released, looks like not. Still happening after the bug fix released by @mgallien to solve #3349. Problem is, syncs continue to try to get the small files in every cycle, and sometimes, depending on the number of files involved, even, crash the client. Please, give this one some priority, it a very annoying bug that affects the whole vfs system. Thanks!!!

Major issue of free projects. I switched to Onedrive again.

**Comment by CoYoNq** [comment] 2022-09-04 22:46
> Major issue of free projects. I switched to Onedrive again.
This kind of comments don't collaborate to solve the issue. Devs are working, users try to help reporting issues, collecting/providing info and testing new releases/features.
Thats why free projects are great.
Be patient, i just want to bump the issue and inform that the suspicious related bug was not related (imho).

**Comment by CoYoNq** [comment] 2022-09-10 19:03
Some "new" info:
This issue appears when you efectively download the files <5k. If you dont do that (files are in the server but you never download them) issue is not shown (file appears as "cloud" status correctly)
![Captura de pantalla -2022-09-10 16-01-04](https://user-images.githubusercontent.com/89138154/189497965-458ce001-3339-4618-acc7-8dd7273d3b86.png)
First and second files never was download to the client
Third one was downloaded and sended back. It sticks in sync state (and every resync, client try to resync it, generating a permanent loop against all files in this state)

**Comment by CoYoNq** [comment] 2022-09-21 14:05
bump!
Any news? As workaround, I have to switch all stations to a WebDAV connection and remove NC client due to this (the endless sync attempt don't allow to work with other files making system unusable in production) With a standar WebDAV connection (via file explorer), stations works fine.
Please mark this issue as critical, at least, in a VFS scenario.
Thanks!

**Comment by andyxheli** [comment] 2022-10-09 16:10
Hi all still present in 3.6.0 @mgallien any updates on this?

**Comment by yardbro** [comment] 2022-10-13 14:06
Also dealing with this issue on Windows client version 3.6.0. All the files stuck in the "sync pending" status are some type of text file and <5KB in size.

**Comment by pzwahlen** [comment] 2022-11-05 10:20
Is there anything Joe Average like me can do to help with this issue ? This is really preventing me from migrating from other (commercial) solutions.

**Comment by rgreeott** [comment] 2022-11-13 07:26
As mentioned by several above, I am experiencing the same issue with NC 24.0.5 and sync client 3.6.2.  I have, at any given time, 30-60 attached clients.  All of which are processing/uploading 1000's of image, docs and pdf's.  Once a project is compete, we free up the local space.  This becomes an issue with files that are only a few k in size.  They end up in an endless "sync pending" state.  Since we process 1000's of files (our server has ~ 1.5M files), it can become an issue with circular sync's occurring.  Depending on the individuals HW, the client can consume much of the CPU resource, further hindering workflow.

I would be happy to assist with any information needed or testing to drive this to conclusion.

Thank you NC and community for all your continued efforts and quality work.

**Comment by pzwahlen** [comment] 2022-12-11 09:12
This bug is still present in the latest 3.6.4 and as far as I can tell, it affects every user using the Virtual Filesystem under Windows. Freeing up space for files smaller than 4KB will create endless sync activities for those small files.

We took the time to create a reproducer (see bug history) and the bug has been acknowledged already. At some point @mgallien mentioned he was working on the issue.

All in all, I think we need to keep this issue opened.

**Comment by pzwahlen** [comment] 2022-12-25 12:07
There are now some quiet days ahead and I would be more than happy to take some time and help solve this issue.

I have already looked at the code with my limited knowledge of the sync API and couldn't spot any easy fix. Anyway, I am more than happy to test any alpha/beta client and report back.

Thanks for the continued work on this one, as it is really annoying for me (storing many small config/text files in my Nextcloud)

... and Merry Christmas!

**Comment by anonbergine** [comment] 2023-01-04 21:49
Toggling "Always keep on this device" (from right-click menu on the file) resolves the perma-sync issue for those files, but PITA to have to keep doing this, especially when we have some batch jobs that create lots of small files.

**Comment by pzwahlen** [comment] 2023-01-22 11:26
3.6.6 still doesn't solve this problem. It also looks like 3.7 is around the corner, so how can we help and avoid carrying this bug over to the next major release ?

@mgallien, this was approved back in December, do you know if anyone is looking into this bug ?

**Comment by roberix** [comment] 2023-01-28 14:03
Hi. That issue keeps disorienting our workforce. Imho one of the major bugs which prevents to broadly deploy the client in enterprise environments. Would appreciate if that gets fixed. 

Best regards 

rob

**Comment by ShockHouse5** [comment] 2023-02-07 16:08
Looks like 3.7.1 fixed this issue on my end. I'm able to add a bunch of files under 4 Kb, they'll sync once and not do it again. They show the correct icon as uploaded (or uploaded and on disk) instead of sync 24/7.

**Comment by andyxheli** [comment] 2023-02-07 16:18
Still an issue for me 3.7.1

**Comment by pzwahlen** [comment] 2023-02-07 19:07
I can confirm this issue is *not* fixed in the latest 3.7.1

Freeing up space for small files <4k sends them in an endless sync state (when using virtual filesystem).

This really renders VFS unusable for cases where we try to sync config/markdown (or other small) files between corporate users. I am about to create separate instances of internal Nextcloud installations for VFS (large) vs. non-VFS (small) files, which is nonsense.

@mgallien @allexzander you seem to be the two guardians of the src/libsync/vfs/cfapi kindom, how can we help you on this issue ?

**Comment by roberix** [comment] 2023-02-08 07:31
Hi. I can confirm that is still an issue in 3.7.1 also for me.

I got another weird behavior but I don't know whether this is releated. Once I open a MS office file the sync status also gets pending and never returns to green. I only open the file but not changing anything. Happens also with files larger than 4k.

If we can help in anyway to test further this issue please let me know.

Regards

Rob

**Comment by gschenck** [comment] 2023-02-10 07:46
I can confirm that this is still an issue in 3.7.1.

**Comment by anonbergine** [comment] 2023-02-10 16:35
Still an issue in 3.7.3

**Comment by Jaytie2k7** [comment] 2023-02-22 09:26
I'm also dealing with this bug, mostly with all sorts of files below 1Mb. I guess there also isn't a workaround is it?
I'm about to roll out Nextcloud for a group of people as a backup solution. This stops me from going on right now. I really hope it gets fixed soon. Thank you for you efford!

**Comment by mgallien** [comment] 2023-02-23 12:33
> I'm also dealing with this bug, mostly with all sorts of files below 1Mb. I also encounter it, without virtual folders enabled. I guess there also isn't a workaround is it? I'm about to roll out Nextcloud for a group of people as a backup solution. This stops me from going on right now. I really hope it gets fixed soon. Thank you for you efford!

the currently recommended workaround is really to use classic sync and selectively selecting the folders needed
we are going to have another try at fixing it soon

**Comment by Jaytie2k7** [comment] 2023-02-23 16:07
> the currently recommended workaround is really to use classic sync and selectively selecting the folders needed we are going to have another try at fixing it soon

Sadly, as stated above, I'm facing the same issue when using the classic sync method. (see screenshot) Or is there even another way of syncing?

![NC_screen](https://user-images.githubusercontent.com/63009998/220963603-fa3be98f-ad3a-4c6a-859d-276e313e5d32.jpg)


Glad to hear, that you guys are on it!

**Comment by pzwahlen** [comment] 2023-02-24 11:38
> we are going to have another try at fixing it soon

Hi @mgallien, it is refreshing to read that this bug will get some attention from "the people who know".

**Comment by pzwahlen** [comment] 2023-02-24 11:42
> Sadly, as stated above, I'm facing the same issue when using the classic sync method. (see screenshot) Or is there even another way of syncing?

Hi @Jaytie2k7, I'm not sure i understand what you mean. This bug is really about hydration/dehydration of small files, with dehydratin of files <4k bringing them into a constant "to be sync" status.

I think your screenshot highlights that some file (whatever their size) are missign the overlay icon, which I would say is a completely different issue.

**Comment by roberix** [comment] 2023-02-24 12:19
> > Sadly, as stated above, I'm facing the same issue when using the classic sync method. (see screenshot) Or is there even another way of syncing?
> 
> Hi @Jaytie2k7, I'm not sure i understand what you mean. This bug is really about hydration/dehydration of small files, with dehydratin of files <4k bringing them into a constant "to be sync" status.
> 
> I think your screenshot highlights that some file (whatever their size) are missign the overlay icon, which I would say is a completely different issue.

Hi.

I face this issue also with larger files. Especially msoffice files which stays in sync pending once files is opened (no change). Maybe 2 different issue though and we should separate them – hard for me to judge.

Regards

rob

**Comment by Jaytie2k7** [comment] 2023-02-24 12:35
> I think your screenshot highlights that some file (whatever their size) are missign the overlay icon, which I would say is a completely different issue.

The screenshot shows a testfolder after switching to the classic sync method. NC client says it's in sync while it isn't.
The files lack the overlay-icon because they are not getting synced. These files are actually missing on the serverside (not visible in the WebUI)
Also they are all smaller than 1mb, which seems to be the case mostly.

**Comment by pzwahlen** [comment] 2023-03-05 13:43
> the currently recommended workaround is really to use classic sync and selectively selecting the folders needed
> we are going to have another try at fixing it soon

Just a quick note: it looks like the latest nightly (which includes #5474) solves the problem!

**Comment by mgallien** [comment] 2023-03-08 16:48
@pzwahlen thanks for the notice
I completely overlooked closing this issue when the PR was merged

**Closed by mgallien** 2023-03-08 16:48 UTC
Labels: bug, high, approved

**Comment by ErikUden** [comment] 2023-03-11 19:26
> > the currently recommended workaround is really to use classic sync and selectively selecting the folders needed
> > we are going to have another try at fixing it soon
> 
> Just a quick note: it looks like the latest nightly (which includes #5474) solves the problem!

Sorry to bother you and @mgallien, but when can we expect those being implemented on the beta channel :D? I just downloaded the newest version (3.7.4) and I am on Windows-10.0.19045 and sadly this update didn't fix the error for me! 

It still shows "All synced" with just about every file having the "pending sync" symbol next to it! Force sync etc. doesn't help 

In a week? A month? All is fine by me, I just wanna know at what point, if the error still persists even after an updated client, I should start worrying again :D

**Comment by pzwahlen** [comment] 2023-03-12 08:49
@ErikUden can you take one of those small file and do the following:

- hydrate it (ie right-click->'make always available locally')
- dehydrate it (ie right-click->'free up local space')

In my case, the small file ends up with the correct "cloud" icon/status and not the "sync pending" status anymore.

You may have to do this for all the files problematic files.

**Comment by mgallien** [comment] 2023-03-21 08:27
@ErikUden the fix is already part of 3.7.4
that said, the state of the file on storage is invalid and may indeed require you to make the steps suggested by @pzwahlen

**Comment by rose-a** [comment] 2023-03-22 06:56
I can confirm this has fixed the issue for me in 3.7.4

**Comment by welcometopwn** [comment] 2023-04-04 16:57
This is still an issue for me. The above steps mentioned by @pzwahlen works for files, but the folders still say "sync pending". Removing and re-adding them doesn't work either.

**Comment by afzl-wtu** [comment] 2023-04-12 05:42
Issue is present still in latest version.

**Comment by afzl-wtu** [comment] 2023-04-12 08:31
> > Issue is present still in latest version.
> 
> Issues with the database cannot be fixed via a client update. If a previous client (or precious server version) caused server-side issues, then a client update won't fix it.
> 
> The new client ensures the same issue won't happen **again.**
> 
> Those who already have the issue will need to fix it themselves and then be glad it won't occur again.

How to fix it?

**Comment by mgallien** [comment] 2023-04-12 13:54
the issue is that the state of some virtual files may be incorrect
the solution (apart from running a client version including the fix) is to make files be always offline then wait for the sync to be done then make them online only (and wait for the sync to be done)
starting from now, they should be fine and show the proper status
I do not know if the windows API would allow us to detect the invalid state of some virtual files and fix them

**Comment by welcometopwn** [comment] 2023-04-12 19:12
I did once again try to fix it but some of the folders still have the sync pending icon. I even disabled the virtual files, let everything sync and enabled it again.

**Comment by anonbergine** [comment] 2023-04-17 02:56
I've managed to fix most of the files using the "fix" discussed above, but it does not work for folders. I still have some folder with forever-sync issue.

**Comment by mgallien** [comment] 2023-04-17 12:47
@anonbergine this may be due to ignored files
you can probably get clue by checking the activity list for ignored files/patterns
or you try to dig info about ignored files/folders from the client logs
