### ISSUE TITLE
Can't build version 3.3.3 on Debian 11

### ISSUE THREAD

**Issue by 71GA** [nextcloud/desktop#3795] opened 2021-09-14 22:08 UTC
Version of Nextcloud that comes with the Debian 11 by default is [buggy](https://github.com/nextcloud/desktop/issues/1946). Also the official `.appimage` file from [here](https://nextcloud.com/install/#install-clients) is buggy.

So I the last resort for me is to build from source. I choose to take *release* 3.3.3 from [here](https://github.com/nextcloud/desktop/releases/tag/v3.3.3) and we download it in `.tar.gz` compressed file:

```
┌───┐
│ $ │ ziga > ziga--workstation > Downloads
└─┬─┘ /dev/pts/2
  └─> wget https://github.com/nextcloud/desktop/archive/refs/tags/v3.3.3.tar.gz
  
┌───┐
│ $ │ ziga > ziga--workstation > Downloads
└─┬─┘ /dev/pts/2
  └─> tar -xzf v3.3.3.tar.gz 
  
┌───┐
│ $ │ ziga > ziga--workstation > Downloads
└─┬─┘ /dev/pts/2
  └─> cd desktop-3.3.3/
  
┌───┐
│ $ │ ziga > ziga--workstation > desktop-3.3.3
└─┬─┘ /dev/pts/2
  └─> mkdir build

┌───┐
│ $ │ ziga > ziga--workstation > desktop-3.3.3
└─┬─┘ /dev/pts/2
  └─> cd build

┌───┐
│ $ │ ziga > ziga--workstation > build
└─┬─┘ /dev/pts/2
  └─> sudo apt install pkgconf libqt5webenginewidgets5 cmake g++ qt5-default openssl libssl-dev libzip-dev qtbase5-private-dev qtdeclarative5-dev qtwebengine5-dev qt5keychain-dev qttools5-dev sqlite3 libsqlite3-dev libqt5svg5-dev zlib1g-dev libqt5websockets5-dev qtquickcontrols2-5-dev shared-mime-info inkscape libnextcloudsync-dev
  
┌───┐
│ $ │ ziga > ziga--workstation > build
└─┬─┘ /dev/pts/2
  └─> cmake .. -DCMAKE_INSTALL_PREFIX=/opt/nextcloud/ -DCMAKE_BUILD_TYPE=Debug

┌───┐
│ $ │ ziga > ziga--workstation > build
└─┬─┘ /dev/pts/2
  └─> sudo make install
  
┌───┐
│ $ │ ziga > ziga--workstation > bin
└─┬─┘ /dev/pts/0
  └─> sudo ln -s /opt/nextcloud/bin/nextcloud /usr/local/bin/nextcloud
```

Running the Nextcloud will produce an error:

```
┌───┐
│ $ │ ziga > ziga--workstation > bin
└─┬─┘ /dev/pts/0
  └─> nextcloud 
nextcloud: error while loading shared libraries: libnextcloudsync.so.0: cannot open shared object file: No such file or directory
```

> **Attention:**
> This can be solved by installing package `libnextcloudsync-dev`, but then a new error will occur:
>
> ```
> ┌───┐
> │ $ │ ziga > ziga--workstation > bin
> └─┬─┘ /dev/pts/0
>   └─> nextcloud 
> nextcloud: error while loading shared libraries: libnextcloud_csync.so.0: cannot open shared object file: No such file or directory
> ```
>
> This one can't be fixed, because there is no package to fix this. Probably Debian 11 does not have it. How to fix this???

**Comment by FlexW** [comment] 2021-09-14 23:15
You installed the client to `/opt/nextcloud`. That means the shared libraries that the desktop client ships like `libnextcloud_csync` and so on will also be installed in directories below `/opt/nextcloud`. When you start the Nextcloud desktop client, the dynamic linker searches for the shared libraries that the desktop client needs. The search will fail because the shared libraries that the desktop client needs will be in directories that dynamic linker does not search. Installing the package `libnextcloudsync-dev` will be not a good idea because then you would not use the shared libraries that you compiled yourself. You would again use the libraries from your distro which you wanted to avoid.

You have the following possibilites:
- Configure the dynamic linker to search in the correct directories
- Installl the desktop client in a way that the shared libraries will be in a directory that is on the search list of the dynamic linker.
- Tell the dynamic linker with the `LD_LIBRARY_PATH` environment variable where it should search for the shared libraries.

Here you can learn more about shared libraries https://tldp.org/HOWTO/Program-Library-HOWTO/shared-libraries.html

Having said that, I'm not sure compiling the desktop client yourself will solve your problems. It's the same version.
I will close the ticket because your issue is not a bug, but rather a support question. For support questions you can go to https://help.nextcloud.com

**Closed by FlexW** 2021-09-14 23:15 UTC
Labels: bug
