### ISSUE TITLE
Client just deleted 500GB + of files for no reason

### ISSUE THREAD

**Issue by Vantage-DS** [nextcloud/desktop#703] opened 2018-10-04 19:10 UTC
Server  - 13
Ubuntu 18 LTS

Laptop Client  - 2.3.3
Windows 10 Pro

Also on network - 
Mac Client 2.5 Daily
High Sierra

### Expected behaviour
The 2 clients sync chosen folders with the server. Any changes are synced between the 3 computers.

### Actual behaviour
With no warning, the Windows 10 client deleted over 500GB of files and folders. No reason, no pattern. It just left 3 folders behind.
The Mac client and the Server have not been affected luckily. My data is still intact on the server and mac.
The Windows 10 client thinks it's fine and has a green tick assuming its synced and up to date, but it's obviously not.

### Steps to reproduce
1. Unknown. The client has been fine for days. Nothing was changed on the server or any client.

**Comment by camilasan** [comment] 2018-10-05 08:43
Hi! Could you provide client logs?

**Comment by Vantage-DS** [comment] 2018-10-05 10:17
I'm not at my home computer now but will get logs. Is there anyway other than pressing F12 in the client to get logs because as far as I'm aware this only starts logging after you've pressed F12?

As far as updating, my server only informed me of an update from 13.0.1 > 13.0.6. Now I've just clicked that update its offering 14. Is it ok to do this now without losing the logs you need?

Thanks

**Comment by camilasan** [comment] 2018-10-05 10:29
If there are any client logs you may find it at C:\Users\[username]\AppData\Local\Nextcloud. As for the server logs, I would copy it before updating.

**Comment by Vantage-DS** [comment] 2018-10-05 11:02
There are no logs there unfortunately.

All i have is a screenshot of a list of files being deleted from the client but that's not going to be any help.

I don't think there's anything I can do to give you any info to why this happened is there?

**Comment by camilasan** [comment] 2018-10-05 11:37
Could you try to describe what happened when the client 'decided' to delete your files? Did you update your Windows? Reboot? Renamed or moved files? Etc?

**Comment by cluxter** [comment] 2018-11-13 00:38
@camilasan In my case, all I did was waiting. Nothing else. Sometimes for a long time, sometimes for a short time. It's totally random, it can happen anytime on any data and on any platform (see my link in previous comment). This should be tagged as Critical _right now_.

**Comment by camilasan** [comment] 2018-11-13 08:42
> I posted in [#289 (comment)](https://github.com/nextcloud/desktop/issues/289#issuecomment-438080304) about the same issue. Linux and MacOS are also affected.

https://github.com/nextcloud/desktop/issues/289#issuecomment-438180420

In short: try the 2.5 version of our client (https://download.nextcloud.com/desktop/prereleases/)

**Comment by juliushaertl** [comment] 2018-11-13 09:06
Also please provide sync logs, if the error happens again. 

You can find those in the following locations (for 2.5):

**Linux:**
~/.local/share/Nextcloud/[SyncedFoldName]_ersync.log

**macOS:** 
~/Library/Application Support/Nextcloud/[SyncedFoldName]_sync.log

**Windows:**
C:/Users//AppData/Roaming/Nextcloud/[SyncedFoldName]_sync.log

**Comment by Vantage-DS** [comment] 2018-11-14 00:28
I wouldn't even know what to do to reproduce it either.
When it happend I was working on the Mac editing video and then some photos, after everything had saved I went to my windows laptop to check it had all synced and that's when I saw everything had been deleted.

It's not happened since and the only big change I've made is disabling the Adobe premiere cache folder from being synced (pointless anyway). Its impossible for me to know whether this has anything to do with it.

**Comment by cluxter** [comment] 2018-11-14 00:34
@Vantage-DS Do you have the option "Synchronize hidden files" enabled on the computer which lost your data? And what about the other one?

**Comment by rwat1** [comment] 2018-12-20 14:55
I HAVE THE SAME PROBLEM, OMG I NEED TO REDOWNLOAD 500GB over my terrible internet connection. This is horrendous, how can this be happening? Is this a Beta release, why did I upgrade?

**Comment by Vantage-DS** [comment] 2021-06-11 09:33
This reminds me of another issue I had with bitlocker recently - #3315  
With that problem, files didn't delete themselves, but the Nextcloud client decided at random it would start syncing files I didn't want it too if the Nextcloud client was open *before* I'd unlocked my drive.
Much like #703 but in reverse /shrug

**Comment by mgallien** [comment] 2021-06-14 07:12
@Vantage-DS Can you test with the latest version ?
If you cannot reproduce, can you close the issue ?

In any case, to be able to work we need the desktop client logs as indicated before.

**Closed** 2021-06-14 11:05 UTC
Labels: bug, needs info, os: :door: Windows
