### ISSUE TITLE
"share with" drop-down menu item in English only app 2.6.3 20200217

### ISSUE THREAD

**Issue by tigernero79** [nextcloud/desktop#1794] opened 2020-02-18 07:04 UTC
I installed the update proposed by the application v.2.6.3 of 20200217 and I noticed that in the drop-down menu the item share with remains in English "share via" and is no longer in Italian "Condividi Con Nextcloud" 

I enclose photos translation always in English with red circle and is not in Italian

![Immagine](https://user-images.githubusercontent.com/35575744/74711897-53b72300-5225-11ea-87d7-ab65c19e1961.png)

**Comment by misch7** [comment] 2020-02-18 13:42
Duplicate of #1791

**Closed by misch7** 2020-02-18 13:42 UTC
