### ISSUE TITLE
Enable sharing-features via context menu using virtual files-sync

### ISSUE THREAD

**Issue by sharcslife** [nextcloud/desktop#4182] opened 2022-01-17 15:15 UTC
Hi,

I'm using the desktop app on windows with the virtual files method.
It's great that all files and folders are displayed, but when I want to create a link (-> share), I first need to download the file/folder.

Would it be possible to add these sharing-features to the right-click menu when using virtual files?

I'd love that!

**Comment by allexzander** [comment] 2022-01-20 11:48
@sharcslife You mean, a share option in the file explorer's context menu? We've had some issues with it in 3.3.6 that should've been fixed in 3.4.1.

**Comment by FernandoMarques-Santos** [comment] 2022-03-18 14:08
> Hi,
> 
> I'm using the desktop app on windows with the virtual files method. It's great that all files and folders are displayed, but when I want to create a link (-> share), I first need to download the file/folder.
> 
> Would it be possible to add these sharing-features to the right-click menu when using virtual files?
> 
> I'd love that!

Would you mind changing the title to "Enable sharing-features via context menu (right-click menu) in the desktop client"? I wanted to open the same request but struggled a little bit to find this one. Perhaps this will make it easier for others to find the request and to support it.

**Comment by sharcslife** [comment] 2022-03-18 14:26
@FernandoMarques-Santos I altered the title slighly, hope that helps.
I checked just now and the issue has disappeared for me...

**Comment by FernandoMarques-Santos** [comment] 2022-03-18 15:08
I am glad the issue is gone for you, but I am not sure how the issue disappeared, as there is no right-click menu share option yet. Do you mean that now you can share without downloading it using this menu?

![image](https://user-images.githubusercontent.com/33721644/159028391-6b97aab4-103a-4371-b69b-ebce1f703c65.png)

What me and the others here understood was this:

![image](https://user-images.githubusercontent.com/33721644/159028892-0e00672e-d642-4258-8a84-978c90449ccd.png)


In any case, if the problem is gone, please mark it as solved.

**Comment by sharcslife** [comment] 2022-03-20 18:03
Not quite.

The entries marked in yellow used to be greyed out (unavailable) in the sub-menu before.
Now there are available, even when the files are not synced. 
I always got Nextcloud as an entry in the right-click menu though, there was never an issue with that.

This is Windows 11, running NC 23.0.2

![image](https://user-images.githubusercontent.com/3924964/159175896-186ecbf5-858b-498d-9a61-682de8ca7249.png)

**Is this your issue?** Because if it is, I'll leave it open, but for me it's solved.

**Comment by FernandoMarques-Santos** [comment] 2022-03-20 18:23
Well, that was my issue indeed. Turns out I was missing some features when installing nextcloud. I will describe it here so anyone with the same problem can see it.

I downloaded it again and clicked on "change installation", then add the features as below:
![image](https://user-images.githubusercontent.com/33721644/159176854-0c7f4d42-8f35-47f0-8d7b-4df6328e54f3.png)

I do not know why this didn't install by default. You can close the issue now. Thanks!

**Closed** 2022-03-20 18:27 UTC
Labels: enhancement, feature: :minidisc: virtual filesystem, feature: :busts_in_silhouette: sharing
