### ISSUE TITLE
[Bug]: Incorrect syncing speed in UI

### ISSUE THREAD

**Issue by mjollnir14** [nextcloud/desktop#5294] opened 2022-12-22 05:09 UTC
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

Incorrect average syncing speed
...

### Steps to reproduce

1. Sync a dir with many files that require a long indexing
2. Wait for indexing to complete
3. Mouseover the setting box to read the actual transfer rate. It will show up a abnormal high speed (100 Mbits/s, while my connexion is only capable of 10 Mbits/s). This number will drastically lowers as the average calculation goes down.
...

### Expected behavior

My suspicion is that the timer starts when the indexing is complete, but the actual syncing starts as soon as the indexing starts. The math is not correct as it should start counting time when the syncing begins, not when the indexing completes.
...

### Which files are affected by this bug

/

### Operating system

Linux

### Which version of the operating system you are running.

Distributor ID:	Ubuntu Description:	Ubuntu 22.10 Release:	22.10 Codename:	kinetic

### Package

Official SNAP package

### Nextcloud Server version

not related

### Nextcloud Desktop Client version

3.6.0

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 3.4.2 to 3.4.4)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by joshtrichards** [comment] 2024-08-22 17:44
Duplicate of #4891
Fixed in #4902

**Closed by joshtrichards** 2024-08-22 17:44 UTC
Labels: 0. Needs triage, bug, feature: :gear: settings
