### ISSUE TITLE
Different Sync Handling between Client Types

### ISSUE THREAD

**Issue by ShaunMundy** [nextcloud/desktop#6170] opened 2023-10-25 08:26 UTC
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

Linux and Windows clients have diffent ways in checking what files are up-to-date, and which files are to sync.

### Steps to reproduce

- Have a shared folder, e.g. a nas, 
- give two different clients, linux und windows, access to this folder.
- fill the shared and now synced folder with files and directories
- sync the folderstructure with a linux client, e.g. Ubuntu Desktop Jammy
- sync the folderstructure with a windows client, e.g. Windows 10

I'm using this scenario to sync by night with a linux client, and by day with a windows client.

What happens is the following: _All the (new) files that are uploaded over night with the linux client,
are being downloaded the next day with the windows client._ 

### Expected behavior

The sync processes should check which files and folders to sync, in the same way, regardless of the os.

### Which files are affected by this bug

n/a - the whole filestructure to sync

### Operating system

Linux

### Which version of the operating system you are running.

Ubuntu Jammy Desktop, Windows 10

### Package

Distro package manager

### Nextcloud Server version

Nextcloud Hub 6 (27.1.2)

### Nextcloud Desktop Client version

3.4.2 (linux) - 3.10.0 (win)

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [X] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by joshtrichards** [comment] 2023-11-21 18:33
I don't follow. Can you clarify (or restate in a different way)the following:

- Actual Behavior you're experiencing
- Expected Behavior you're expecting

**Comment by joshtrichards** [comment] 2024-09-07 16:29
Closing since this wasn't valid test scenario (different versions) + there are some difficult to know variables here (different OS issues, some sort of network share shared between two distinct client installations) + this is an edge case I don't currently see us having time to look into further.

**Closed by joshtrichards** 2024-09-07 16:29 UTC
Labels: 0. Needs triage, bug, needs info, feature: :arrows_counterclockwise: sync engine
