### ISSUE TITLE
No App icon in GNOME/Wayland

### ISSUE THREAD

**Issue by lehmanju** [nextcloud/desktop#1435] opened 2019-09-20 20:52 UTC
### Expected behaviour
Show icon in taskbar. It works in GNOME/Xorg and any other window manager.

### Actual behaviour
No icon.

### Steps to reproduce
1. Start application with `QT_QPA_PLATFORM=wayland`

![Bildschirmfoto von 2019-09-20 22-50-11](https://user-images.githubusercontent.com/6310133/65358185-3d1a8a80-dbf9-11e9-8fee-907435675ead.png)

### Client configuration
Client version:
477614b8c954836327eb136be1c035627f09760b

Operating system: Arch Linux

OS language: German

Qt version used by client package (Linux only, see also Settings dialog):
5.13.0

Client package (From Nextcloud or distro) (Linux only):
Distro

Installation path of client:
/usr/bin

**Comment by DominiqueFuchs** [comment] 2019-09-24 18:48
Thanks @lehmanju for reporting this. Considering Wayland I vaguely remember changes regarding the desktop files - due to changes in how the icon is retreived (not per ID & pixmap anymore, but from the desktop file mapping) the desktop file must follow the reverse DNS scheme. 

But this is just an unconfirmed guess, I'll look into this as soon as I find the time.

**Comment by DominiqueFuchs** [comment] 2019-09-26 10:50
Fix on it's way in #1449

**Comment by DominiqueFuchs** [comment] 2019-10-27 17:09
merged #1449 🚀

**Closed by DominiqueFuchs** 2019-10-27 17:09 UTC
Labels: 3. to release, enhancement, os: :penguin: Linux, os: :smiling_imp: FreeBSD
