### ISSUE TITLE
Nextcloud Desktop Version 3.2.2 will not install on W8.1

### ISSUE THREAD

**Issue by WST1811** [nextcloud/desktop#3392] opened 2021-06-01 20:44 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Steps to reproduce
1. Desktop Client 3.1.3 offer me Desktop Client 3.2.2 on Windows 8.1x64. But install fails.
2.
3.

### Client configuration
Client version: 3.1.3

Operating system: Windows 8.1 64 Bit

OS language: German

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From Nextcloud or distro) (Linux only):

Installation path of client: "C:\Program Files\Nextcloud\nextcloud.exe"

### Server configuration

Nextcloud version: 21.0.2

Storage backend (external storage):

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile: 
Since 3.1: Under the "General" settings, you can click on "Create Debug Archive ..." to pick the location of where the desktop client will export the logs and the database to a zip file.
On previous releases: Via the command line: `nextcloud --logdebug --logwindow` or `nextcloud --logdebug --logfile log.txt`
(See also https://docs.nextcloud.com/desktop/3.0/troubleshooting.html#log-files)

2. Web server error log:

3. Server logfile: nextcloud log (data/nextcloud.log):

EDIT: Same Issue only another Desktop Version: https://github.com/nextcloud/desktop/issues/3245

**Comment by Case-Berlin64** [comment] 2021-06-02 07:38
Same Problem with Windows 2016 Std Server?

**Comment by Id3aFly** [comment] 2021-06-02 20:36
I guess this is related to #3083 #3081 #3079
See also #3138

I can't tell how this relates to Windows Server versions.

**Comment by mgallien** [comment] 2021-06-03 12:35
The 3.2 version has an hard requirement on CfApi feature of Windows.
we might make it optional in the future but currently I would prefer to close the issue as this is a maintenance choice of us and not a bug.

**Closed by mgallien** 2021-06-03 12:35 UTC
Labels: bug

**Comment by Case-Berlin64** [comment] 2021-06-03 12:40
cfApi:
REQUIREMENTS
 	 
Minimum supported client	Windows 10, version 1709 [desktop apps only]
Minimum supported server	Windows Server 2016 [desktop apps only]
https://docs.microsoft.com/de-de/windows/win32/api/cfapi/nf-cfapi-cfreferenceprotectedhandle

**Comment by WST1811** [comment] 2021-06-03 16:32
It would be great if there was a new version for all operating systems. No new features, only for the future the query to the MSI whether it is also released for this OS. Or MSI knows it itself and offers no installation. 

But now the error message comes only if you run the MSI manually. With the automatism the installation is executed again and again and again and again.

If then else or select case Build Number can be written, or is that no longer available?

There are so many tickets now for the same problem, why not just get it right once for all future cases?

BTW: Windows 10 1709 is out of support, not Windows 8.1.

**Comment by github-tomster** [comment] 2021-07-10 08:53
@thosetryingtocode
here one can find how to make smart and sustainable decisions:
https://doc.owncloud.com/desktop/2.8/installing.html#system-requirements
`System Requirements`
`Windows 7+ (x86 with 32-bit or x86-64; Native WinVFS available for Windows 10 version 1709 or later)`

**Comment by WST1811** [comment] 2021-08-04 15:27
Today i installed NC Desktop Version 3.3.0, thanks to all who helped to develop this version, for me it works. :)
