### ISSUE TITLE
Empty folder created before enabling End-to-End Encryption app cannot be encrypted

### ISSUE THREAD

**Issue by luixxiul** [nextcloud/desktop#1865] opened 2019-03-21 03:17 UTC
### Description

The empty folder created _before_ enabling End-to-End Encryption app cannot be encrypted, displaying the message below.

### Steps to Reproduce

  1. Let the client run
  2. Set up sync
  3. Create a folder manually inside of the main folder
  4. Enable E2E on Apps
  5. Restart the client
  6. Select the folder inside the main folder
  7. Encrypt it

**Actual result:** The message "Please wait for the folder to sync before trying to encrypt it" is displayed

**Expected result:** The folder should be encrypted soon

Note: If you create another folder _after_ enabling the E2E app, this folder can be encrypted.

### Version

Client 2.5.1 final https://github.com/nextcloud/desktop/commit/b37cbea5cc12b01d9baa0e36a996c873acdeea00

**Comment by georgehrke** [comment] 2020-03-12 13:23
cc @misch7

**Comment by er-vin** [comment] 2020-05-19 15:54
Hello,

Closing as this seems to be a duplicate of #777.

Regards.

**Closed by er-vin** 2020-05-19 15:54 UTC
Labels: 0. Needs triage, bug, feature: :lock: end to end encryption
