### ISSUE TITLE
status wrong for directories when using vfs and nextcloud desktop 3.2.x

### ISSUE THREAD

**Issue by tob123** [nextcloud/desktop#3082] opened 2021-04-11 16:50 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour
a) directories or files that are available locally  (synchronized) should have a green checkmark icon in the status column of windows explorer.
b) directories or files that are not available locally (not syncronized) should have a blue cloud icon in the status column of windows explorer.
c) files or directories should not have a pending sync icon in the status column of windows explorer.

### Actual behaviour
1) good: files that are not available locally have the blue cloud icon.
2) not good: directories always have a pending sync icon.
3) not good: files have a pending sync icon when they are available locally.
4) not good: files never have a green checkmark icon.

### Steps to reproduce
install nextcloud desktop 3.2.0

### Client configuration
Client version: 3.2.0

Operating system:
windows 10 20H2
64 bits.
OS language: US / english.

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From Nextcloud or distro) (Linux only):

Installation path of client:
c:\program files\nextcloud

### Server configuration

Nextcloud version: 21.0.1

Storage backend (external storage):
external storage is in use based on bind mounts in container.
(issue is the same on external storage based files)
### Logs

any recommendations how to anonimize logs ? i cannot share you the logs since it contains filenames of personal files.

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile: 
Since 3.1: Under the "General" settings, you can click on "Create Debug Archive ..." to pick the location of where the desktop client will export the logs and the database to a zip file.
On previous releases: Via the command line: `nextcloud --logdebug --logwindow` or `nextcloud --logdebug --logfile log.txt`
(See also https://docs.nextcloud.com/desktop/3.0/troubleshooting.html#log-files)

2. Web server error log:

3. Server logfile: nextcloud log (data/nextcloud.log):
https://gist.github.com/tob123/ed28340584a0cbe772e583a5091bce4d

**Comment by FlexW** [comment] 2021-04-12 07:11
I can confirm this issue. Actually, after a while the pending sync icon turns into the green locally available icon.

**Comment by tob123** [comment] 2021-04-12 16:18
[20210412_1801_owncloud.log.0.txt](https://github.com/nextcloud/desktop/files/6298176/20210412_1801_owncloud.log.0.txt)
[20210412_1731_owncloud.log.0.txt](https://github.com/nextcloud/desktop/files/6298178/20210412_1731_owncloud.log.0.txt)
[20210412_1745_owncloud.log.0.txt](https://github.com/nextcloud/desktop/files/6298180/20210412_1745_owncloud.log.0.txt)
[20210412_1746_owncloud.log.0.txt](https://github.com/nextcloud/desktop/files/6298181/20210412_1746_owncloud.log.0.txt)
[20210412_1746_owncloud.log.1.txt](https://github.com/nextcloud/desktop/files/6298182/20210412_1746_owncloud.log.1.txt)
[20210412_1800_owncloud.log.0.txt](https://github.com/nextcloud/desktop/files/6298183/20210412_1800_owncloud.log.0.txt)

now with debug log files in a different environment.
actual situation is a bit different now compared to what i mentioned previously:

same behavior:
good: files that are not available locally have the blue cloud icon.
not good: directories always have a pending sync icon.


different:
not good: files never have a green checkmark icon.
not good: files have a pending sync icon when they are available locally.

some files keep the blue pending sync icon (for example files i copied into the nextcloud folder)
some files get the green icon when i open them (the original template files from nextcloud)

**Comment by johkoenig** [comment] 2021-04-14 10:15
Hello everybody,

I have the same issue after upgrading from 3.1.3 to 3.2.0 on Windows and enabling vfs on my synced folder.
Every file and folder has the blue "in progress" sign and in the settings it says something similar like "syncing with local vfs folder". All contents of the folder were available locally before the switch.
I checked the task manager, disk usage is minimal. I assume the process is stuck somewhere. Restarting the PC didn't help.

Would love to see that fixed soon. Vfs is a feature I am really looking forward to!

**Comment by Mickael-Martin** [comment] 2021-04-14 16:15
Hello,

I've got the same issue, everything is with the blue status "wait for sync".

**Comment by stavros-k** [comment] 2021-04-14 16:42
Same problem one account have blue cloud on files and pending sync on dirs, but other account (about 250gb) have pending sync everywhere

**Comment by tob123** [comment] 2021-05-04 10:43
hello team, i upgraded to 3.2.1,
resulted behavior i see is better:
a) new files: works ok. (green icon for synced, pending icon for pending, cloud icon in case the file is only available on the server)
b) new directories: not ok: only the pending blue icon is shown
c) existing files / directories: only pending blue icons.

this test was done on an environment i cannot share logs from (personal data, upgraded from older nc versions, non-vfs etc.)

what is the supposed desired result based on all the commits / merged code?
should i file a new issue based on version 3.2.1 ?
logs needed ?

tobias.

**Comment by mgallien** [comment] 2021-05-04 12:53
> hello team, i upgraded to 3.2.1,
> resulted behavior i see is better:
> a) new files: works ok. (green icon for synced, pending icon for pending, cloud icon in case the file is only available on the server)
> b) new directories: not ok: only the pending blue icon is shown
> c) existing files / directories: only pending blue icons. (also after opening an existing file the icon stays pending)
> d) new files in existing directories: ok. (green icon for synced, pending icon for pending, cloud icon in case the file is only available on the server).
> e) new files in new directories: ok AND the above directory also ok.
> By " new" i mean dirs / files create AFTER upgrading to 3.2.1
> 
> this test was done on an environment i cannot share logs from (personal data, upgraded from older nc versions, non-vfs etc.)
> 
> what is the supposed desired result based on all the commits / merged code?
> should i file a new issue based on version 3.2.1 ?
> logs needed ?
> 
> tobias.

Thanks for the info
We keep using this issue because I had forgotten to close it already
I will check if i can reproduce using only your message and ask for more if I need

**Comment by stavros-k** [comment] 2021-05-04 12:55
> Thanks for the info
> We keep using this issue because I had forgotten to close it already
> I will check if i can reproduce using only your message and ask for more if I need

I have the same exactly effect on 3.2.1

**Comment by emc02** [comment] 2021-05-14 08:11
same problem here...

**Comment by jfabaf** [comment] 2021-05-21 12:35
Same problem here but it also happens with files (not only directories)

**Comment by mattjmeier** [comment] 2021-05-28 18:26
I am curious if this means that any file version conflicts could develop, or if any files are actually in the wrong sync state/not synced? I can live with the icon being visually incorrect... but I would like to confirm that there are no actual implications for file syncing. Anyone with some insight on that?

Also wondering if this impacts all users of VFS or if there are any environment-specific causes based on 1) how Nextcloud is being run (I'm running a docker container on a linux server) or 2) the Windows system running the client (versions of Windows updates, other dependencies, etc).

Thank you,
Matt

**Comment by stavros-k** [comment] 2021-05-28 18:48
> Anyone with some insight on that?

From my experience with daily usage, i can confirm that only the icon have the problem. files are synced correctly.

**Comment by Voakie** [comment] 2021-05-31 10:46
This problem occurs for me after renaming a file locally. The file is synced by Nextcloud and therefore also renamed in the cloud, but the icon stays on the "syncing" icon. The issue can be resolved by using the "Free up space" button in the context menu and downloading the files again. I also had the issues with folders showing a wrong sync state, but that seems to fix itself after a while.

**Comment by tob123** [comment] 2021-06-01 18:32
upgraded to 3.2.2. i see no change compared to 3.2.1. for completeness see behavior below:
a) new files: works ok. (green icon for synced, pending icon for pending, cloud icon in case the file is only available on the server)
b) new directories: not ok: only the pending blue icon is shown
c) existing files / directories: only pending blue icons. (also after opening an existing file the icon stays pending)
d) new files in existing directories: ok. (green icon for synced, pending icon for pending, cloud icon in case the file is only available on the server).
e) new files in new directories: ok AND the above directory also ok.
By " new" i mean dirs / files create AFTER upgrading to 3.2.1 or 3.2.2

**Comment by FlexW** [comment] 2021-06-11 11:02
@tob123 b) is most likley okay. at least it's the same behaviour on OneDrive. See also https://github.com/nextcloud/desktop/issues/3251

**Comment by FlexW** [comment] 2021-06-14 13:51
Should be fine with https://github.com/nextcloud/desktop/pull/3432 merged.

**Closed by FlexW** 2021-06-14 13:51 UTC
Labels: 1. to develop, approved, bug, feature: :arrows_counterclockwise: sync engine, feature: :minidisc: virtual filesystem

**Comment by weeix** [comment] 2022-04-14 09:00
For those who upgraded to a newer version but still have directories with pending sync icons, try resyncing the folder (remove account -> delete Nextcloud folder -> log in and sync your files to an empty folder) again.

**Comment by robertoschwald** [comment] 2022-04-27 15:21
Unfortuntely, even when updating to the latest version, defekt sync icons are not updated automatically. It is enough to free up space on the topmost level and make them available locally again, but that means full resync. Other solution is to rename the affected folder (e.g. add an _) and rename back.
