### ISSUE TITLE
Changing installation leads to setup error related to windows 10 version

### ISSUE THREAD

**Issue by graue70** [nextcloud/desktop#3378] opened 2021-05-28 01:24 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour
Changing the installation on an up-to-date windows version (20H2) should lead to no error. If there is an actual problem, the error message should be correct.

### Actual behaviour
Changing the installation on an up-to-date windows version (20H2) leads to this error: 'This application only runs on Windows 10, version 1709 or higher!'
The message makes no sense because 20H2 is more up-to-date than 1709.

### Steps to reproduce
1. Install on Windows 10 20H2.
2. Run the installer again. Choose 'Change installation'.

### Client configuration
Client version: 3.2.1

Operating system: Windows 10 20H2

OS language: de.DE

Installation path of client: Default

![nextcloud-desktop-change-installation-cut](https://user-images.githubusercontent.com/23035329/119915952-dddf5280-bf63-11eb-8884-b057a0bef6b2.png)

**Comment by mgallien** [comment] 2021-06-23 11:47
@graue70 we can reproduce it
sorry for that, we will fix it for one of the next release

**Comment by crazy4chrissi** [comment] 2021-07-03 17:58
Same here. I guess the problem is introduced with this commit:
https://github.com/nextcloud/desktop/commit/c88e76a4a989279d7630d95665001ff6b63c2828

The condition

    WINDOWSRELEASEID>=1709

does not seem to work for 20H2.

**Comment by mgallien** [comment] 2021-08-25 09:56
This is fixed by the 3.3.1 release.
Closing this issue.

**Closed by mgallien** 2021-08-25 09:56 UTC
Labels: bug, os: :door: Windows, feature: :inbox_tray: install and update, approved
