### ISSUE TITLE
[Bug]: Menu misplaced and unresponsive on MacOS menu bar

### ISSUE THREAD

**Issue by willvousden** [nextcloud/desktop#5121] opened 2022-11-02 09:34 UTC
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

Sometimes the icon in the MacOS menu bar becomes small and blurry.

When this happens, clicking on it reveals a menu that is displaced upward, resulting in most of the interactive parts being cut off by the top of the screen. Those interactive elements that **are** still visible do not respond to input. For example, I cannot type anything into the search box.

In these circumstances it's impossible to access the settings or to quit the client. My only option is to run `killall Nextcloud` in a terminal session and start the client again.

(Note that the attached screenshots show that the client is offline, but this is unrelated. The issue happens when it's connected to the server, too.)

[20221102_1030_owncloud.log](https://github.com/nextcloud/desktop/files/9918960/20221102_1030_owncloud.log)

<img width="691" alt="Screenshot 2022-10-25 at 15 17 53" src="https://user-images.githubusercontent.com/152388/199453360-c13b08d6-6863-4b48-b620-268ffada71ee.png">
<img width="691" alt="Screenshot 2022-10-25 at 15 18 02" src="https://user-images.githubusercontent.com/152388/199453349-50fcb8c1-a42f-494d-8966-4d75833e609e.png">

### Steps to reproduce

I don't know how to reproduce it. There is no obvious pattern to when it happens.

### Expected behavior

The menu bar icon should display properly and the menu bar should be correctly placed and responsive to input.

### Which files are affected by this bug

I don't understand this question

### Operating system

Mac OS

### Which version of the operating system you are running.

12.6

### Package

Other

### Nextcloud Server version

24.0.6

### Nextcloud Desktop Client version

3.6.1git (build 11939)

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 3.4.2 to 3.4.4)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Nextcloud Server logs

```shell
I don't think this is relevant.
```

**Comment by Clashsoft** [comment] 2023-05-13 14:10
I have the same problem. For me it is always shifted down by about menubar width. Always happens after switching from external display to builtin. Have to use `killall Nextcloud`. It's a shame there is no simple right click / native context menu that allows quitting directly..

**Comment by foss-** [comment] 2023-05-13 19:18
Dupe of https://github.com/nextcloud/desktop/issues/4395

**Comment by stephanbogner** [comment] 2024-08-02 12:34
Happens to me all the time. It's easy to reproduce:
1. Plug in external monitor
2. Open the Nextcloud menu and click it away again
3. Detach the monitor
4. Open the menu -> It will now be cut off
5. Use Activity Monitor to force quit the app

**Comment by claucambra** [comment] 2024-10-16 07:25
This has been fixed with the move to Qt 6 in 3.14.0+

**Closed by claucambra** 2024-10-16 07:25 UTC
Labels: 0. Needs triage, bug, os: :apple: macOS
