### ISSUE TITLE
NextCloud PPA client download refers to "owncloud"

### ISSUE THREAD

**Issue by duckartes** [nextcloud/desktop#125] opened 2018-01-16 16:02 UTC
Using: https://launchpad.net/~nextcloud-devs/+archive/ubuntu/client

Found through: https://nextcloud.com/install/#install-clients

![](https://i.redd.it/qo9udex3ica01.png)

**Comment by helmo** [comment] 2018-01-18 11:57
I think this is a duplicate of #4

**Comment by rullzer** [comment] 2018-07-02 18:35
Fixed in master

**Closed by rullzer** 2018-07-02 18:35 UTC
