### ISSUE TITLE
ubuntu 20.4 - No Try Icon - No Main/ Settings Window reachable

### ISSUE THREAD

**Issue by tigexplorer** [nextcloud/desktop#2912] opened 2021-02-08 13:00 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour
After starting, the Nextcloud tray icon may appear in the tray. 
From there, with one click, the main or settings window will start.

### Actual behaviour
Nexcloud client ist runnig, but no icon in the tray.
If I'm launching the the notification window manually, it has no button to access the man window.

### Steps to reproduce
1. Start the machine
2. No Icon
3. Launching manually
4. No button to start the settings window

### Client configuration
Client version:

Nextcloud version 3.1.2-20210128.185328.9398260fb-1.0~focal1
Using Qt 5.12.8, built against Qt 5.12.8
Using Qt platform plugin 'xcb'
Using 'OpenSSL 1.1.1f  31 Mar 2020'
Running on Ubuntu 20.04.2 LTS, x86_64
GNOME Shell 3.36.4

Client package (From Nextcloud or distro) (Linux only):
http://ppa.launchpad.net/nextcloud-devs/client/ubuntu

Installation path of client:
/usr/share/doc/nextcloud-client
/usr/share/doc/nextcloud-client/changelog.Debian.gz
/usr/share/doc/nextcloud-client/copyright
/etc/sysctl.d/101-sync-inotify.conf

**Comment by camilasan** [comment] 2021-02-08 18:27
@ivaradi Could #2764 be related?

**Comment by ivaradi** [comment] 2021-02-08 18:47
The package that was missing as a dependency does not exist in Focal, so I don't think so it is related to that.

But there were issues with the tray icon, which are said to be resolved by a fix to one of the GNOME Shell extensions (I think the appindicators one). I think this one is related to those issues.

**Comment by tpokorra** [comment] 2021-02-09 08:57
It works for me on Fedora 33 with https://extensions.gnome.org/extension/615/appindicator-support/

**Comment by tigexplorer** [comment] 2021-02-09 16:59
> It works for me on Fedora 33 with https://extensions.gnome.org/extension/615/appindicator-support/

Unfortunately, this don't work for me.

**Comment by tigexplorer** [comment] 2021-02-15 22:37
I made a fresh ubuntu 20.4 install and nextcloud-client install via the ppa.
After installing, the Notification Icon is displayed and accessible as expected.
But after a reboot, it's no more displayed in the notification area.

**Comment by ivaradi** [comment] 2021-02-16 05:14
@tigexplorer if you kill the client and restart it, does the tray icon appear?

**Comment by tigexplorer** [comment] 2021-02-16 08:33
> @tigexplorer if you kill the client and restart it, does the tray icon appear?

Yes, it's appear after killing and new starting the client! 
On both machines, the fresh installed and the upgraded from ubuntu 18.
Thanx, this can be a workaround so long.

**Comment by ivaradi** [comment] 2021-02-16 08:51
Great, and it also indicates that it is most likely the same issue as #1977.

**Comment by er-vin** [comment] 2021-02-16 14:10
Thus closing as duplicate of #1977

**Closed by er-vin** 2021-02-16 14:10 UTC
Labels: bug, package: PPA
