### ISSUE TITLE
ETag check keeps server busy

### ISSUE THREAD

**Issue by mnlipp** [nextcloud/desktop#1567] opened 2019-10-27 16:25 UTC
The nextcloud-client (2.6.0) keeps the server busy by continuously issuing "ETag request":

```
[OCC::Folder::slotRunEtagJob 	Trying to check "https://xxxxx.xxx.xx/remote.php/dav/files/xyz/Dokumente" for changes via ETag check. (time since last sync: 21 s)
[OCC::AccessManager::createRequest 	6 "PROPFIND" "https://xxxxx.xxx.xx/remote.php/dav/files/xyz/Dokumente" has X-Request-ID "74907535-90a7-4181-9f43-a94c0f0ad18f"
[OCC::AbstractNetworkJob::start 	OCC::RequestEtagJob created for "https://xxxxx.xxx.xx" + "/Dokumente" "OCC::Folder"
[OCC::WebFlowCredentials::slotFinished 	request finished
[OCC::RequestEtagJob::finished 	Request Etag of QUrl("https://xxxxx.xxx.xx/remote.php/dav/files/xyz/Dokumente") FINISHED WITH STATUS "OK"
[OCC::Folder::slotRunEtagJob 	Trying to check "https://xxxxx.xxx.xx/remote.php/dav/files/xyz/Dokumente" for changes via ETag check. (time since last sync: 26 s)
[OCC::AccessManager::createRequest 	6 "PROPFIND" "https://xxxxx.xxx.xx/remote.php/dav/files/xyz/Dokumente" has X-Request-ID "30725ed7-8527-4b5c-b6ba-82f72c884f4c"
[OCC::AbstractNetworkJob::start 	OCC::RequestEtagJob created for "https://xxxxx.xxx.xx" + "/Dokumente" "OCC::Folder"
[OCC::WebFlowCredentials::slotFinished 	request finished
[OCC::RequestEtagJob::finished 	Request Etag of QUrl("https://xxxxx.xxx.xx/remote.php/dav/files/xyz/Dokumente") FINISHED WITH STATUS "OK"
[OCC::AccessManager::createRequest 	6 "PROPFIND" "https://xxxxx.xxx.xx/remote.php/dav/files/xyz/" has X-Request-ID "f283435a-3a98-43a0-bb50-ede951fca79c"
[OCC::AbstractNetworkJob::start 	OCC::PropfindJob created for "https://xxxxx.xxx.xx" + "/" "OCC::ConnectionValidator"
[OCC::WebFlowCredentials::slotFinished 	request finished
[OCC::PropfindJob::finished 	PROPFIND of QUrl("https://xxxxx.xxx.xx/remote.php/dav/files/xyz/") FINISHED WITH STATUS "OK"
[OCC::Folder::slotRunEtagJob 	Trying to check "https://xxxxx.xxx.xx/remote.php/dav/files/xyz/Dokumente" for changes via ETag check. (time since last sync: 31 s)
[OCC::AccessManager::createRequest 	6 "PROPFIND" "https://xxxxx.xxx.xx/remote.php/dav/files/xyz/Dokumente" has X-Request-ID "639005b9-2884-4ea3-8f10-ace756c863c7"
[OCC::AbstractNetworkJob::start 	OCC::RequestEtagJob created for "https://xxxxx.xxx.xx" + "/Dokumente" "OCC::Folder"
[OCC::WebFlowCredentials::slotFinished 	request finished
[OCC::RequestEtagJob::finished 	Request Etag of QUrl("https://xxxxx.xxx.xx/remote.php/dav/files/xyz/Dokumente") FINISHED WITH STATUS "OK"
```
The "time since last sync" increases by 5 seconds each time.

This happens for each synchronized folder and for each client and sums up to both a base load on the server and a considerable network traffic when using a mobile connection.

I first noticed this after moving a nextcloud instance to another server and thought it was related to this (I did a maintenance:data-fingerprint). But then I noticed that the request is also repeatedly issued against another server that has not been changed.

Operating system: Fedora 30

Client package (From Nextcloud or distro) (Linux only): Tried both distro (2.5.3) and flatpak (2.6.0)

### Server configuration
Nextcloud version: 16.0.5

**Comment by mike2307** [comment] 2019-11-04 21:04
I can confirm this from my side.

```
svc_1    | 172.18.0.3 - mike [04/Nov/2019:20:56:44 +0000] "PROPFIND /remote.php/dav/files/mike/ HTTP/1.1" 207 1080 "-" "Mozilla/5.0 (Linux) mirall/2.6.0git (Nextcloud)"
svc_1    | 172.18.0.3 - mike [04/Nov/2019:20:56:49 +0000] "PROPFIND /remote.php/dav/files/mike/ HTTP/1.1" 207 1080 "-" "Mozilla/5.0 (Linux) mirall/2.6.0git (Nextcloud)"
svc_1    | 172.18.0.3 - mike [04/Nov/2019:20:56:54 +0000] "PROPFIND /remote.php/dav/files/mike/ HTTP/1.1" 207 1080 "-" "Mozilla/5.0 (Linux) mirall/2.6.0git (Nextcloud)"
svc_1    | 172.18.0.3 - mike [04/Nov/2019:20:56:59 +0000] "PROPFIND /remote.php/dav/files/mike/ HTTP/1.1" 207 1080 "-" "Mozilla/5.0 (Linux) mirall/2.6.0git (Nextcloud)"
svc_1    | 172.18.0.3 - mike [04/Nov/2019:20:57:00 +0000] "PROPFIND /remote.php/dav/files/mike/ HTTP/1.1" 207 1100 "-" "Mozilla/5.0 (Linux) mirall/2.6.0git (Nextcloud)"
svc_1    | 172.18.0.3 - mike [04/Nov/2019:20:57:04 +0000] "PROPFIND /remote.php/dav/files/mike/ HTTP/1.1" 207 1080 "-" "Mozilla/5.0 (Linux) mirall/2.6.0git (Nextcloud)"
svc_1    | 172.18.0.3 - mike [04/Nov/2019:20:57:09 +0000] "PROPFIND /remote.php/dav/files/mike/ HTTP/1.1" 207 1080 "-" "Mozilla/5.0 (Linux) mirall/2.6.0git (Nextcloud)"
svc_1    | 172.18.0.3 - mike [04/Nov/2019:20:57:14 +0000] "PROPFIND /remote.php/dav/files/mike/ HTTP/1.1" 207 1080 "-" "Mozilla/5.0 (Linux) mirall/2.6.0git (Nextcloud)"
svc_1    | 172.18.0.3 - mike [04/Nov/2019:20:57:19 +0000] "PROPFIND /remote.php/dav/files/mike/ HTTP/1.1" 207 1080 "-" "Mozilla/5.0 (Linux) mirall/2.6.0git (Nextcloud)"
```

```
nextcloud --version
QSocketNotifier: Can only be used with threads started with QThread
Nextcloud version 2.6.0git
Git revision e0b32c19e4dd641f4edf74fc3fbdba3d86ca9784
Using Qt 5.12.5, built against Qt 5.12.4
Using 'OpenSSL 1.1.1d FIPS  10 Sep 2019'
```

**Comment by mike2307** [comment] 2019-11-04 21:09
Just downgraded to version 2.5.3 (Fedora 31). Same result...
How can we stop this 5-second-interval-madness?

**Comment by gunwald** [comment] 2019-11-10 21:06
I can confirm this behavior as well. The client 2.5.3git keeps my Server busy, sending it requests more than once a minute although no file has been changed. If am couple of clients are online, my small server is completely busy, just handling this requests:
```

│XX.XXX.XX.69 - user [10/Nov/2019:22:00:58 +0100] "PROPFIND /owncloud/remote.php/dav/files/user/Folder1 HTTP/1.1" 207 1151 "-" "Mozilla/5.0 (Linux) mirall/2.5.3git (Nextcloud)"            │
│XX.XXX.XX.69 - user [10/Nov/2019:22:00:59 +0100] "PROPFIND /owncloud/remote.php/dav/files/user/Folder2 HTTP/1.1" 207 1150 "-" "Mozilla/5.0 (Linux) mirall/2.5.3git (Nextcloud)"             │
│XX.XXX.XX.69 - user [10/Nov/2019:22:00:59 +0100] "PROPFIND /owncloud/remote.php/dav/files/user/FolderY HTTP/1.1" 207 1153 "-" "Mozilla/5.0 (Linux) mirall/2.5.3git (Nextcloud)"          │
│XX.XXX.XX.69 - user [10/Nov/2019:22:00:59 +0100] "PROPFIND /owncloud/remote.php/dav/files/user/FolderX%20Who HTTP/1.1" 207 1160 "-" "Mozilla/5.0 (Linux) mirall/2.5.3git (Nextcloud)"   │
│XX.XXX.XX.69 - user [10/Nov/2019:22:01:00 +0100] "PROPFIND /owncloud/remote.php/dav/files/user/Scripta HTTP/1.1" 207 1151 "-" "Mozilla/5.0 (Linux) mirall/2.5.3git (Nextcloud)"            │
│XX.XXX.XX.69 - user [10/Nov/2019:22:01:02 +0100] "PROPFIND /owncloud/remote.php/dav/files/user/FolderA HTTP/1.1" 207 1157 "-" "Mozilla/5.0 (Linux) mirall/2.5.3git (Nextcloud)"      │
│XX.XXX.XX.69 - user [10/Nov/2019:22:01:02 +0100] "PROPFIND /owncloud/remote.php/dav/files/user/FolderZ HTTP/1.1" 207 1151 "-" "Mozilla/5.0 (Linux) mirall/2.5.3git (Nextcloud)"            │
│XX.XXX.XX.69 - user [10/Nov/2019:22:01:03 +0100] "PROPFIND /owncloud/remote.php/dav/files/user/FolderB HTTP/1.1" 207 1150 "-" "Mozilla/5.0 (Linux) mirall/2.5.3git (Nextcloud)"             │
│XX.XXX.XX.69 - user [10/Nov/2019:22:01:03 +0100] "PROPFIND /owncloud/remote.php/dav/files/user/Dir3 HTTP/1.1" 207 1148 "-" "Mozilla/5.0 (Linux) mirall/2.5.3git (Nextcloud)"               │
│XX.XXX.XX.69 - user [10/Nov/2019:22:01:03 +0100] "PROPFIND /owncloud/remote.php/dav/files/user/Folder1 HTTP/1.1" 207 1151 "-" "Mozilla/5.0 (Linux) mirall/2.5.3git (Nextcloud)"            │
│XX.XXX.XX.69 - user [10/Nov/2019:22:01:04 +0100] "PROPFIND /owncloud/remote.php/dav/files/user/Folder2 HTTP/1.1" 207 1150 "-" "Mozilla/5.0 (Linux) mirall/2.5.3git (Nextcloud)"             │
│XX.XXX.XX.69 - user [10/Nov/2019:22:01:04 +0100] "PROPFIND /owncloud/remote.php/dav/files/user/FolderY HTTP/1.1" 207 1153 "-" "Mozilla/5.0 (Linux) mirall/2.5.3git (Nextcloud)"          │
│XX.XXX.XX.69 - user [10/Nov/2019:22:01:04 +0100] "PROPFIND /owncloud/remote.php/dav/files/user/FolderX%20Who HTTP/1.1" 207 1160 "-" "Mozilla/5.0 (Linux) mirall/2.5.3git (Nextcloud)"   │
│XX.XXX.XX.69 - user [10/Nov/2019:22:01:05 +0100] "PROPFIND /owncloud/remote.php/dav/files/user/Scripta HTTP/1.1" 207 1151 "-" "Mozilla/5.0 (Linux) mirall/2.5.3git (Nextcloud)"            │
│XX.XXX.XX.69 - user [10/Nov/2019:22:01:07 +0100] "PROPFIND /owncloud/remote.php/dav/files/user/FolderA HTTP/1.1" 207 1157 "-" "Mozilla/5.0 (Linux) mirall/2.5.3git (Nextcloud)"      │
│XX.XXX.XX.69 - user [10/Nov/2019:22:01:07 +0100] "PROPFIND /owncloud/remote.php/dav/files/user/FolderZ HTTP/1.1" 207 1151 "-" "Mozilla/5.0 (Linux) mirall/2.5.3git (Nextcloud)"            │
│XX.XXX.XX.69 - user [10/Nov/2019:22:01:08 +0100] "PROPFIND /owncloud/remote.php/dav/files/user/FolderB HTTP/1.1" 207 1150 "-" "Mozilla/5.0 (Linux) mirall/2.5.3git (Nextcloud)"             │
│XX.XXX.XX.69 - user [10/Nov/2019:22:01:08 +0100] "PROPFIND /owncloud/remote.php/dav/files/user/Dir3 HTTP/1.1" 207 1148 "-" "Mozilla/5.0 (Linux) mirall/2.5.3git (Nextcloud)"               │
│XX.XXX.XX.69 - user [10/Nov/2019:22:01:08 +0100] "PROPFIND /owncloud/remote.php/dav/files/user/Folder1 HTTP/1.1" 207 1151 "-" "Mozilla/5.0 (Linux) mirall/2.5.3git (Nextcloud) 
```
Please help us stop this. It kills my infrastructure.

**Comment by mnlipp** [comment] 2021-05-26 12:39
Yes, it's 30s in my logs.

**Comment by FlexW** [comment] 2021-05-26 13:49
@mnlipp I think it is expected that the client polls the server every 30 seconds. Otherwise it will not know if files changed. If you want to avoid this polling, then you need to use the push notifications backend https://github.com/nextcloud/notify_push. I would suggest we close this issue, because it works as intended I think.

**Closed by FlexW** 2021-05-26 13:49 UTC
Labels: bug, needs info

**Comment by mnlipp** [comment] 2021-05-26 13:56
Of course. With 30s and just a few clients, the load is no problem.

**Comment by FlexW** [comment] 2021-05-26 14:01
Yes, that's why the push notifications backend was introduced. With that backend, the client will not poll the server every 30 seconds.
