### ISSUE TITLE
Please provide a feature to completely turn off nonsense logs. Just no logs at ll

### ISSUE THREAD

**Issue by sapphirepro** [nextcloud/desktop#6619] opened 2024-04-11 10:22 UTC
I have expensive m.2 drives and I am really tired of app just trashing my device writing nonsense logs with many gigabytes in ~/.congis/nextcloud/logs

I even tried to symlink to /dev/null, but then many windows occur that can not write logs. Please, let this peace of that to turn off. No even single byte of logs. I don't want them! I don't want to collect that trash, I don't care that if reporting bugs it could be useful to you. Just NO LOGS at all. It must really give an option for permanent logs off and ignore all.

Thanks in advance, even I doubt it gets implemented, since it was a problem long ago and no solution so far. On server side same nonsense

**Comment by joshtrichards** [comment] 2024-08-14 20:00
Duplicate of #3312

**Closed by joshtrichards** 2024-08-14 20:00 UTC
Labels: enhancement
