### ISSUE TITLE
3.4.0: no popup when clicking on the taskbar icon

### ISSUE THREAD

**Issue by Moini** [nextcloud/desktop#4017] opened 2021-11-30 19:54 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour
When I click on the Nextcloud icon in my status bar, a popup should appear. When I select "Open main dialog" in the right-click menu of said icon, the same popup should appear.

### Actual behaviour
Nothing happens when I click on the icon.

### Steps to reproduce
1. Click on icon
2. Look around on all attached monitors

### Client configuration
Client version:
3.4.0

Number of monitors: 
2

Operating system:
Linux Mint 20.2 Uma (Xfce)

OS language:
German

Qt version used by client package (Linux only, see also Settings dialog):
I don't see a Qt version info in the settings:
![grafik](https://user-images.githubusercontent.com/3240233/144117462-a3945b82-c531-4c1e-a036-afbaafd6d57c.png)

Client package (From Nextcloud or distro) (Linux only):
http://ppa.launchpad.net/nextcloud-devs/client/ubuntu

Installation path of client:
Standard

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile: 
Since 3.1: Under the "General" settings, you can click on "Create Debug Archive ..." to pick the location of where the desktop client will export the logs and the database to a zip file.
On previous releases: Via the command line: `nextcloud --logdebug --logwindow` or `nextcloud --logdebug --logfile log.txt`
(See also https://docs.nextcloud.com/desktop/3.0/troubleshooting.html#log-files)

Hard requirement or not, this is **private data**. Please let me know which part of it you really need, and I will clean the private parts out. Thanks!

Possibly related: https://github.com/nextcloud/desktop/issues/4005

**Comment by Moini** [comment] 2021-11-30 21:44
I've run the client from command line, too, and nothing was printed out. Alt + Tab does not show any new windows.

**Comment by janvlug** [comment] 2021-12-01 07:47
See also #3867.

**Comment by mgallien** [comment] 2021-12-01 10:35
@Moini can you share your logs ?

**Comment by Moini** [comment] 2021-12-01 13:00
@mgallien That would be the .log[.xx] files in the zip?

**Comment by ghc0000** [comment] 2021-12-01 13:09
I believe I can help a bit, since I have identical problem. I attached a snippet of logs below after cleaning up my info. Just before creating the log I clicked on the status bar icon multiple times and also selected "Open main dialog" from right-click menu multiple times.

As additional info, changing the configuration item `showMainDialogAsNormalWindow` to true (or false) doesn't change anything: the main dialog still doesn't appear.

(There seems to be nothing related on the log, but here goes:)
https://gist.github.com/ghc0000/230a5df3388b38d9fd43f4ed57b01665

**Comment by mgallien** [comment] 2021-12-01 15:27
> @mgallien That would be the .log[.xx] files in the zip?

yes and please do not omit lines because then I will be left wondering which lines are missing and why there is no errors in the log

**Comment by Moini** [comment] 2021-12-01 15:28
Mine is here, I've left all warnings (one per type) since startup, and kept all messages from when I was clicking on the icon 5 times at 15:54. Also cleaned all private data:  
https://gist.github.com/Moini/9c7f967a3ccc56438aab7ce2d29f0206

**Comment by mgallien** [comment] 2021-12-01 15:28
> I believe I can help a bit, since I have identical problem. I attached a snippet of logs below after cleaning up my info. Just before creating the log I clicked on the status bar icon multiple times and also selected "Open main dialog" from right-click menu multiple times.
> 
> As additional info, changing the configuration item `showMainDialogAsNormalWindow` to true (or false) doesn't change anything: the main dialog still doesn't appear.
> 
> (There seems to be nothing related on the log, but here goes:) https://gist.github.com/ghc0000/230a5df3388b38d9fd43f4ed57b01665

your log extract is too small and I cannot do anything useful with it :crying_cat_face:

**Comment by Moini** [comment] 2021-12-01 15:29
Oh... lol. I'm bad at auto-editing long text files, esp. if there is variable info in the lines that needs to be removed, like the cookie data... Not a friend with regexes...

**Comment by ghc0000** [comment] 2021-12-01 16:51
> > I believe I can help a bit, since I have identical problem. I attached a snippet of logs below after cleaning up my info. Just before creating the log I clicked on the status bar icon multiple times and also selected "Open main dialog" from right-click menu multiple times.
> > As additional info, changing the configuration item `showMainDialogAsNormalWindow` to true (or false) doesn't change anything: the main dialog still doesn't appear.
> > (There seems to be nothing related on the log, but here goes:) https://gist.github.com/ghc0000/230a5df3388b38d9fd43f4ed57b01665
> 
> your log extract is too small and I cannot do anything useful with it

Right, my bad, here is newest log file in full:
https://gist.github.com/ghc0000/bfa31d9f64c21289fdd0662be1b009bc
On this there were multiple clicks to status bar icon and "Open main dialog" after timestamp 2021-12-01 18:41:21.

**Comment by mgallien** [comment] 2021-12-16 12:03
> @mgallien Are the pieces of info linked above useful to figure out what the issue may be?

I need to have all the log especially just after you start the desktop client

**Comment by Rudiberto** [comment] 2021-12-20 15:23
Bug also confirmed on Ubuntu 20.04 Linux Mint XFCE with kernel 5.4.0-91
It's a huge problem, because I can't see any conflict details. No way at all! 
So I can't know how to solve them. Had to set up a Windows machine to keep on working on the cloud folders.

**Comment by bugariu** [comment] 2021-12-27 10:13
Bug still exists on Kubuntu 20.04

**Comment by MauroFoti** [comment] 2021-12-27 12:25
Same in linux mint 20.1 with client 3.4.1. Weirdly enough, the bug does not replicate with the appimage (3.4.1) downloaded from https://nextcloud.com/install/#install-clients

**Comment by haarp** [comment] 2021-12-28 11:51
Some facts:

- Issue appeared on 3.1.3 or earlier.
- A freshly started client doesn't show this issue. So everybody claiming it went away after an update might have been wrong.
- Which might indicate that some event triggers this bug. Leaving the client running for a while? Adding/removing monitors while it's running? Suspending the machine? This should be tested.

**Comment by Rudiberto** [comment] 2021-12-28 11:59
Can't confirm that is does not happen on a freshly started client. Happens right away from the start here.

**Comment by Moini** [comment] 2021-12-28 17:44
Same, it's present from the start. I use the web version anyway and never care much about the local mirror...

**Comment by allexzander** [comment] 2021-12-29 15:25
We will release a fix in 3.4.2. See: https://github.com/nextcloud/desktop/issues/4069#issuecomment-1002647579

**Comment by Moini** [comment] 2021-12-29 15:41
@allexzander Those are good news! Thanks to the team for fixing it! Happy new year :)

**Comment by jurgenhaas** [comment] 2022-01-26 17:20
Well, the DEB package still has this problem, the AppImage works OK though.

**Comment by allexzander** [comment] 2022-01-26 18:50
@jurgenhaas Yes, we did not fix it in packages. For now, the workaround is to use AppImage.

**Comment by Rudiberto** [comment] 2022-01-29 15:29
Would be really nice, to fix the packages, because of the usability (Language, System integration…)

**Comment by sokai** [comment] 2022-02-12 17:57
(I think/maybe you can) close this issue in favour of #4069

**Comment by Moini** [comment] 2022-03-13 11:41
Yes, seems to work again. Closing!

**Comment by bugariu** [comment] 2022-05-05 07:28
Seems to be back in 3.5.0 under Kubuntu 20.04

**Comment by mvvvmd** [comment] 2022-05-05 07:49
> Seems to be back in 3.5.0 under Kubuntu 20.04

**https://github.com/nextcloud/desktop/issues/4476#issue-1224161832**

**Comment by Moini** [comment] 2022-05-05 13:23
Confirmed on Linux Mint 20.3.

**Comment by Moini** [comment] 2022-05-05 13:24
Sorry, closing again, there was a new issue opened for it of course, and not marked as a duplicate.

**Closed** 2022-05-17 10:19 UTC
Labels: bug, os: :penguin: Linux, feature: :cloud: system tray

**Comment by Rudiberto** [comment] 2022-07-30 09:12
Since  version 3.5.3 the problem is back on Mint Xfce 20,3
Maintainers can send me the pre-version and I will test it. No problem for me, if it is a problem for them.

**Comment by Moini** [comment] 2022-07-30 13:55
Confirmed.

**Comment by Moini** [comment] 2022-07-30 13:55
(but probably opening yet another issue for it would be more appropriate)
