### ISSUE TITLE
[Bug]: Stupid UI Bug on macOS while switching from external to internal monitor

### ISSUE THREAD

**Issue by idominiki** [nextcloud/desktop#5284] opened 2022-12-19 04:51 UTC
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

I switch between external and internal monitor use a lot during a day. After the first switch, the Nextcloud Menu bar can't showed up correctly.
![Bildschirm­foto 2022-12-19 um 05 47 40](https://user-images.githubusercontent.com/62521486/208350285-8c4c5065-f4da-4504-8cde-e3355279298c.png)

### Steps to reproduce

1. Connect to external
2. Work with the menu bar
3. Disconnect external monitor
4. Click on Menu bar icon

### Expected behavior

Window should be resizing correctly

### Which files are affected by this bug

Menu bar App

### Operating system

Mac OS

### Which version of the operating system you are running.

macOS 13.1 (22C65)

### Package

Appimage

### Nextcloud Server version

*

### Nextcloud Desktop Client version

3.6.4

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 3.4.2 to 3.4.4)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [ ] LDAP/ Active Directory
- [X] SSO - SAML
- [ ] Other

**Comment by tobiasKaminsky** [comment] 2022-12-19 07:48
Probably duplicate of https://github.com/nextcloud/desktop/issues/5268

**Comment by claucambra** [comment] 2022-12-19 11:55
It is a duplicate, yes. I will remind @idominiki to be mindful of community conduct and that the language in the title of this issue is neither constructive nor helpful. Closing

**Closed by claucambra** 2022-12-19 11:55 UTC
Labels: 0. Needs triage
