### ISSUE TITLE
Sync "Access denied" et weird hidden files on Windows

### ISSUE THREAD

**Issue by quentinDupont** [nextcloud/desktop#2835] opened 2021-01-18 10:25 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour
Folder synced correctly

### Actual behaviour
Access denied error for no reason
Empty folders with files in hidden mode and weird extension files.. If I rename the files, i can read the files by the way.

![image](https://user-images.githubusercontent.com/9005817/104902183-b3123b80-597e-11eb-9b54-7afe613aa42d.png)

Issue only on Windows computer : indeed I did the same sync on Ubuntu Linux client (2.6.5) and I had no issue as we can see here :

![image](https://user-images.githubusercontent.com/9005817/104902200-b9081c80-597e-11eb-8f82-1c00c731ead5.png)

### Steps to reproduce
1. Installing last version 3.1.1 Windows client
2. Also try to uninstall, re-install, delete AppData folders for starting from fresh install
3. Sync one folder 

### Client configuration
Client version: 3.1.1

Operating system: Windows

### Server configuration
Nextcloud version: 20.0.4

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile: 
Since 3.1: Under the "General" settings, you can click on "Create Debug Archive ..." to pick the location of where the desktop client will export the logs and the database to a zip file.
On previous releases: Via the command line: `nextcloud --logdebug --logwindow` or `nextcloud --logdebug --logfile log.txt`
(See also https://docs.nextcloud.com/desktop/3.0/troubleshooting.html#log-files)

→ not understand what i should share here with the zip folder i have

**Comment by er-vin** [comment] 2021-01-18 10:56
This is about two issues already reported one being fixed already (fix will be shipped with 3.1.2). Closing then.

**Comment by quentinDupont** [comment] 2021-01-18 12:24
So sorry, I searched with several key words and didn't find issues :/
I search again and didn't find the issues, if you have the issues link, it will be very nice :slightly_smiling_face:

**Comment by er-vin** [comment] 2021-01-18 12:31
I was trying to avoid doing that search myself. ;-)

Here they are: #2678 and #2807

And now I realize it wasn't exactly #2807 you were talking about... Those files you got on Windows look like downloads which occurred and for some reason the final rename to put the file in place didn't happen. Did you have any particular failure before those appeared?

**Comment by quentinDupont** [comment] 2021-01-18 12:39
Yeh sorry, I'm no expert at nextcloud desktop and don't really understand which issues is similar to which issues..

For your question, i'm not sure to answer properly : it's in a colleague computer and we try differents things before I write this issue. I think all the failures were about "Access denied"

**Comment by er-vin** [comment] 2021-01-18 12:44
Alright, let's look into this some more... Where does the "access denied" error you mention appear exactly during sync?

This feels like those final renames are rejected by the OS somehow. Anything "special" about the folder used for syncing? Like is it on an SMB share or similar? Some weird filesystem perhaps?

Obviously fishing because that shouldn't happen and that really looks like something lower in the stack, I'm unsure if we'll be able to do much.

Providing us with the debug logs might help (can use the debug archive button in the settings dialog for that), make sure the error happened less than 24 hours before doing this or it'll be purged from the logs already which won't help us see the error.

**Comment by quentinDupont** [comment] 2021-01-18 12:51
Well in the configuration panel it's all green but on the new menus (the one on the bottom right), it's written several times "Access Denied"

For syncing, i use the default folder path on user folder.

I have the archive bug.zip but don't know what you except in this archive :)

**Comment by er-vin** [comment] 2021-01-18 12:57
Please drop it here (if you trust us with the data in there, obviously it tells a lot about your file names): https://cloud.nextcloud.com/s/7ZSqepBdwCgwnkA

**Comment by quentinDupont** [comment] 2021-01-18 13:16
> Please drop it here (if you trust us with the data in there, obviously it tells a lot about your file names): https://cloud.nextcloud.com/s/7ZSqepBdwCgwnkA

Done :pray:

**Comment by er-vin** [comment] 2021-01-18 13:24
Yes, I confirm this is the OS rejecting the rename for some reason, you got plenty such lines in the logs for said files:
`2021-01-18 10:26:56:492 [ warning nextcloud.sync.filesystem ]: Renaming temp file to final failed:  "Acc?? refus??\r\n"`

This is when the `.FooBar.txt~xxx` gets renamed into `FooBar.txt`.

But you claimed you were able to rename said files manually? Do you have more rights than the nextcloud process somehow? Is there some strange ACLs on the folder locally? Because clearly Windows is letting the process create files in that folder but it doesn't let it rename them.

I'm not sure we can do much about it in any case, the code tries to act as intended it's just that Windows doesn't let the rename to go through and that fails the sync.

**Comment by quentinDupont** [comment] 2021-01-18 15:40
Okeeey !
Well i don't know much about ACLs on Windows..

Yes i confirm that I succeed to rename manually these files.

I'm gonna try to sync Nextcloud in an other folder

**Comment by quentinDupont** [comment] 2021-01-20 10:55
Okey I can't find the issue..
I try to sync my nextcloud folder in differents location in the computer, everything I test that I could write, edit, delete files.
But nextcloud can't do it..

Here is a gif where I sync one folder, the file is here, hidden and i can rename it and read it.

![bug_acl_nextcloud_desktop](https://user-images.githubusercontent.com/9005817/105165040-200c0980-5b16-11eb-885a-324d72609b6c.gif)
 
I don't know what to test more.

The user is an admin user.
I don't understand ACL in Windows (it's written that the folder is readonly which is false and furthermore I compare with a colleague computer and it's also written that it's readonly)

**Comment by er-vin** [comment] 2021-01-20 13:33
Are you sure the nextcloud client is running under the same user? Maybe it's running with less privileges somehow?

**Comment by quentinDupont** [comment] 2021-01-20 14:13
> Are you sure the nextcloud client is running under the same user? Maybe it's running with less privileges somehow?

Not sur.
But I don't know how to get this information ?

**Comment by er-vin** [comment] 2021-01-20 14:21
I think you can see this in the detailed view of Windows task manager.

**Comment by quentinDupont** [comment] 2021-01-21 14:19
> I think you can see this in the detailed view of Windows task manager.

![Capture du 2021-01-21 13-58-56](https://user-images.githubusercontent.com/9005817/105363168-0a710f80-5bfc-11eb-8b87-6836381dd4b2.png)

It seems fine, it's used by `utilisateur` which is the current user

**Comment by er-vin** [comment] 2021-01-21 14:40
Then I'm out of idea... it's really strange, first time I see this and it's really failing at the frontier with the OS which directly says the access rights are missing, not very informative...

**Comment by quentinDupont** [comment] 2021-01-21 15:16
> Then I'm out of idea... it's really strange, first time I see this and it's really failing at the frontier with the OS which directly says the access rights are missing, not very informative...

Shit.
Thanks already for all your ideas !

**Comment by hoymccoy** [comment] 2021-01-30 20:05
Thank god, someone is experiencing the same issue! What I can say is that I'm experiencing this issue with an installation that was working fine before it occured. It seems that I can setup a syncronization for another windows user that is working fine. Can't really say what causes the issue though. I also tried client version 3.1.2 hoping that something got resolved but the issue is still there.

**Comment by davegrabo** [comment] 2021-01-31 07:36
I was experiencing this same issue on a Win7 and a Win10 machine.

Nextcloud logfiles show "access denied" upon the attempt to rename from the temporary filename to the actual filename, after the file has been transferred. Seems to happen only for certain filetypes - documents, images, videos, etc.

I ran ProcMon and can see the "ACCESS DENIED" error occur when the rename is issued.

While searching for a solution, I had the idea to disable my antivirus scanner - AVG.

No more errors! The problem is caused by AVG. I could reliably re-create the problem by turning AVG back on and waiting for a newly created file to sync. Disabling AVG and syncing another new file would work, and would also fix the prior broken file as well.

A permanent fix: add Nextcloud as an exclusion in AVG under "Ransomware protection".

**Comment by er-vin** [comment] 2021-02-01 08:25
> While searching for a solution, I had the idea to disable my antivirus scanner - AVG.
> 
> No more errors! The problem is caused by AVG. I could reliably re-create the problem by turning AVG back on and waiting for a newly created file to sync. Disabling AVG and syncing another new file would work, and would also fix the prior broken file as well.
> 
> A permanent fix: add Nextcloud as an exclusion in AVG under "Ransomware protection".

Seriously I'd have never guessed that... Could the other person affected let us know if they're using that same antivirus scanner? Or if it's related to antivirus as well?

**Comment by quentinDupont** [comment] 2021-02-01 15:37
Apparently it may have fix the issue to disable Avast in my colleague computer !!! :pray: 
More information later, i have to confirme that !

**Comment by davegrabo** [comment] 2021-02-01 20:10
Avast and AVG are fairly similar products made by the same parent company. Avast bought AVG in 2016.

**Comment by er-vin** [comment] 2021-02-02 07:28
Alright, so nothing we can do about and root cause found: the antivirus getting in the way. I'll close this one then.

In any case thanks everyone for your efforts and patience to nail that one down!

**Closed by er-vin** 2021-02-02 07:28 UTC
Labels: bug, feature: :arrows_counterclockwise: sync engine, os: :door: Windows

**Comment by quentinDupont** [comment] 2021-02-02 13:03
At first i tried to add in Avast an app exception with Nexcloud but it didn't solve the problem
BUT Adding an exception on Nextcloud folder in Avast also solve my issue ! :tada: 

![screenshot_fix_nexctcloud](https://user-images.githubusercontent.com/9005817/106604006-55c1e100-655f-11eb-8a73-d6dcd2c6b119.png)
