### ISSUE TITLE
Run certain Nextcloud actions from local desktop's file manager

### ISSUE THREAD

**Issue by 9662** [nextcloud/desktop#86] opened 2017-12-10 14:01 UTC
As a Nextcloud user, in order to improve integration between the Nextcloud desktop client and the web interface, and for more effective collaboration between users, I would like to have the ability to carry out the following actions from my desktop file manager:

 * Obtain any file or directory's direct URL (e.g., `https://cloud.example.com/f/16350`)
 * ~~Change the sharing status of any file or directory (e.g., share with another user or group, create a public link)~~ (it's already there!!! 🎉🎊😀)

Additionally, it may be desirable insofar as client-desktop integration permits, to:

 * Have an indication (e.g., via a decorator on the corresponding icon) of a local file's sharing status on Nextcloud (shared internally, shared via link, …)

**Comment by 9662** [comment] 2017-12-10 14:01
See also https://github.com/nextcloud/server/issues/6005

**Comment by 9662** [comment] 2017-12-10 14:12
I have tried to mock this up via [KDE actions](https://store.kde.org/browse/cat/102/) but I could not find where (or whether) or how the desktop client stores its password. Otherwise, the information in `$HOME/.local/share/data/Nextcloud/nextcloud.cfg` is sufficient to correlate the local path with the corresponding Nextcloud server and user, and to determine whether the file the action was called on is a synchronised file in the first place.

**Comment by michaelstingl** [comment] 2017-12-10 17:10
See https://github.com/owncloud/client/issues/5023#issuecomment-315327491

**Comment by juliushaertl** [comment] 2018-06-20 15:54
> Obtain any file or directory's direct URL

Fixed with https://github.com/nextcloud/desktop/pull/358

> Have an indication (e.g., via a decorator on the corresponding icon) of a local file's sharing status on Nextcloud (shared internally, shared via link, …)

Closing as a duplicate of https://github.com/nextcloud/desktop/issues/122 then ;)

**Closed by juliushaertl** 2018-06-20 15:54 UTC
