### ISSUE TITLE
Crash on network state changed

### ISSUE THREAD

**Issue by dolohow** [nextcloud/desktop#980] opened 2018-12-27 15:02 UTC
### Expected behaviour
Nextcloud does not crash

### Actual behaviour
Nextcloud crashed when network state changed.  openVPN was disconnected.

### Steps to reproduce
1. Run Nextcloud client with openVPN connected.
2. Disconnect from VPN.
3. Observe crash

### Client configuration
Client version: 2.5.1

Operating system: Arch Linux

OS language: Polish

Qt version used by client package (Linux only, see also Settings dialog): 5.12

Client package (From Nextcloud or distro) (Linux only): community/nextcloud-client

Installation path of client: nextcloud: /usr/bin/nextcloud /usr/lib/nextcloud /usr/share/nextcloud /usr/share/man/man1/nextcloud.1.gz

```
Application: nextcloud (nextcloud), signal: Segmentation fault
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[Current thread is 1 (Thread 0x7f0d67a50b40 (LWP 24729))]

Thread 20 (Thread 0x7f0d30dea700 (LWP 18892)):
#0  0x00007f0d7408ec21 in poll () at /usr/lib/libc.so.6
#1  0x00007f0d737ec540 in  () at /usr/lib/libglib-2.0.so.0
#2  0x00007f0d737ec62e in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#3  0x00007f0d747605c4 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Core.so.5
#4  0x00007f0d7470958c in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Core.so.5
#5  0x00007f0d7454d5c9 in QThread::exec() () at /usr/lib/libQt5Core.so.5
#6  0x00007f0d7454e9cc in  () at /usr/lib/libQt5Core.so.5
#7  0x00007f0d73f84a9d in start_thread () at /usr/lib/libpthread.so.0
#8  0x00007f0d74099b23 in clone () at /usr/lib/libc.so.6

Thread 19 (Thread 0x7f0d0effd700 (LWP 24788)):
#0  0x00007f0d7379a3b9 in g_mutex_lock () at /usr/lib/libglib-2.0.so.0
#1  0x00007f0d737ec525 in  () at /usr/lib/libglib-2.0.so.0
#2  0x00007f0d737ec62e in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#3  0x00007f0d747605c4 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Core.so.5
#4  0x00007f0d7470958c in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Core.so.5
#5  0x00007f0d7454d5c9 in QThread::exec() () at /usr/lib/libQt5Core.so.5
#6  0x00007f0d7454e9cc in  () at /usr/lib/libQt5Core.so.5
#7  0x00007f0d73f84a9d in start_thread () at /usr/lib/libpthread.so.0
#8  0x00007f0d74099b23 in clone () at /usr/lib/libc.so.6

Thread 18 (Thread 0x7f0d31ffb700 (LWP 24746)):
#0  0x00007f0d740944ed in syscall () at /usr/lib/libc.so.6
#1  0x00007f0d7454ec66 in QBasicMutex::lockInternal() () at /usr/lib/libQt5Core.so.5
#2  0x00007f0d7454ef74 in  () at /usr/lib/libQt5Core.so.5
#3  0x00007f0d756a87d1 in QNetworkConfigurationManagerPrivate::configurationChanged(QExplicitlySharedDataPointer<QNetworkConfigurationPrivate>) () at /usr/lib/libQt5Network.so.5
#4  0x00007f0d7573d454 in  () at /usr/lib/libQt5Network.so.5
#5  0x00007f0d74735b62 in QObject::event(QEvent*) () at /usr/lib/libQt5Core.so.5
#6  0x00007f0d7470a8d7 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/libQt5Core.so.5
#7  0x00007f0d7470d998 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () at /usr/lib/libQt5Core.so.5
#8  0x00007f0d74760fd4 in  () at /usr/lib/libQt5Core.so.5
#9  0x00007f0d737eaa2f in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#10 0x00007f0d737ec5e9 in  () at /usr/lib/libglib-2.0.so.0
#11 0x00007f0d737ec62e in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#12 0x00007f0d747605a9 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Core.so.5
#13 0x00007f0d7470958c in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Core.so.5
#14 0x00007f0d7454d5c9 in QThread::exec() () at /usr/lib/libQt5Core.so.5
#15 0x00007f0d7454e9cc in  () at /usr/lib/libQt5Core.so.5
#16 0x00007f0d73f84a9d in start_thread () at /usr/lib/libpthread.so.0
#17 0x00007f0d74099b23 in clone () at /usr/lib/libc.so.6

Thread 17 (Thread 0x7f0d327fc700 (LWP 24745)):
#0  0x00007ffcc33b7a29 in  ()
#1  0x00007ffcc33b7c29 in clock_gettime ()
#2  0x00007f0d740a79f2 in clock_gettime () at /usr/lib/libc.so.6
#3  0x00007f0d7475feb2 in  () at /usr/lib/libQt5Core.so.5
#4  0x00007f0d7475e69a in QTimerInfoList::updateCurrentTime() () at /usr/lib/libQt5Core.so.5
#5  0x00007f0d7475ec96 in QTimerInfoList::timerWait(timespec&) () at /usr/lib/libQt5Core.so.5
#6  0x00007f0d7476030f in  () at /usr/lib/libQt5Core.so.5
#7  0x00007f0d737ebe0a in g_main_context_prepare () at /usr/lib/libglib-2.0.so.0
#8  0x00007f0d737ec466 in  () at /usr/lib/libglib-2.0.so.0
#9  0x00007f0d737ec62e in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#10 0x00007f0d747605c4 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Core.so.5
#11 0x00007f0d7470958c in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Core.so.5
#12 0x00007f0d7454d5c9 in QThread::exec() () at /usr/lib/libQt5Core.so.5
#13 0x00007f0d7f4feba6 in  () at /usr/lib/libQt5DBus.so.5
#14 0x00007f0d7454e9cc in  () at /usr/lib/libQt5Core.so.5
#15 0x00007f0d73f84a9d in start_thread () at /usr/lib/libpthread.so.0
#16 0x00007f0d74099b23 in clone () at /usr/lib/libc.so.6

Thread 16 (Thread 0x7f0d32ffd700 (LWP 24744)):
#0  0x00007f0d73f8aafc in pthread_cond_wait@@GLIBC_2.3.2 () at /usr/lib/libpthread.so.0
#1  0x00007f0d5e880004 in  () at /usr/lib/dri/radeonsi_dri.so
#2  0x00007f0d5e87fd28 in  () at /usr/lib/dri/radeonsi_dri.so
#3  0x00007f0d73f84a9d in start_thread () at /usr/lib/libpthread.so.0
#4  0x00007f0d74099b23 in clone () at /usr/lib/libc.so.6

Thread 15 (Thread 0x7f0d337fe700 (LWP 24743)):
#0  0x00007f0d73f8aafc in pthread_cond_wait@@GLIBC_2.3.2 () at /usr/lib/libpthread.so.0
#1  0x00007f0d5e880004 in  () at /usr/lib/dri/radeonsi_dri.so
#2  0x00007f0d5e87fd28 in  () at /usr/lib/dri/radeonsi_dri.so
#3  0x00007f0d73f84a9d in start_thread () at /usr/lib/libpthread.so.0
#4  0x00007f0d74099b23 in clone () at /usr/lib/libc.so.6

Thread 14 (Thread 0x7f0d33fff700 (LWP 24742)):
#0  0x00007f0d73f8aafc in pthread_cond_wait@@GLIBC_2.3.2 () at /usr/lib/libpthread.so.0
#1  0x00007f0d5e880004 in  () at /usr/lib/dri/radeonsi_dri.so
#2  0x00007f0d5e87fd28 in  () at /usr/lib/dri/radeonsi_dri.so
#3  0x00007f0d73f84a9d in start_thread () at /usr/lib/libpthread.so.0
#4  0x00007f0d74099b23 in clone () at /usr/lib/libc.so.6

Thread 13 (Thread 0x7f0d50ff9700 (LWP 24741)):
#0  0x00007f0d73f8aafc in pthread_cond_wait@@GLIBC_2.3.2 () at /usr/lib/libpthread.so.0
#1  0x00007f0d5e880004 in  () at /usr/lib/dri/radeonsi_dri.so
#2  0x00007f0d5e87fd28 in  () at /usr/lib/dri/radeonsi_dri.so
#3  0x00007f0d73f84a9d in start_thread () at /usr/lib/libpthread.so.0
#4  0x00007f0d74099b23 in clone () at /usr/lib/libc.so.6

Thread 12 (Thread 0x7f0d517fa700 (LWP 24740)):
#0  0x00007f0d73f8aafc in pthread_cond_wait@@GLIBC_2.3.2 () at /usr/lib/libpthread.so.0
#1  0x00007f0d5e880004 in  () at /usr/lib/dri/radeonsi_dri.so
#2  0x00007f0d5e87fd28 in  () at /usr/lib/dri/radeonsi_dri.so
#3  0x00007f0d73f84a9d in start_thread () at /usr/lib/libpthread.so.0
#4  0x00007f0d74099b23 in clone () at /usr/lib/libc.so.6

Thread 11 (Thread 0x7f0d51ffb700 (LWP 24739)):
#0  0x00007f0d73f8aafc in pthread_cond_wait@@GLIBC_2.3.2 () at /usr/lib/libpthread.so.0
#1  0x00007f0d5e880004 in  () at /usr/lib/dri/radeonsi_dri.so
#2  0x00007f0d5e87fd28 in  () at /usr/lib/dri/radeonsi_dri.so
#3  0x00007f0d73f84a9d in start_thread () at /usr/lib/libpthread.so.0
#4  0x00007f0d74099b23 in clone () at /usr/lib/libc.so.6

Thread 10 (Thread 0x7f0d527fc700 (LWP 24738)):
#0  0x00007f0d73f8aafc in pthread_cond_wait@@GLIBC_2.3.2 () at /usr/lib/libpthread.so.0
#1  0x00007f0d5e880004 in  () at /usr/lib/dri/radeonsi_dri.so
#2  0x00007f0d5e87fd28 in  () at /usr/lib/dri/radeonsi_dri.so
#3  0x00007f0d73f84a9d in start_thread () at /usr/lib/libpthread.so.0
#4  0x00007f0d74099b23 in clone () at /usr/lib/libc.so.6

Thread 9 (Thread 0x7f0d52ffd700 (LWP 24737)):
#0  0x00007f0d73f8aafc in pthread_cond_wait@@GLIBC_2.3.2 () at /usr/lib/libpthread.so.0
#1  0x00007f0d5e880004 in  () at /usr/lib/dri/radeonsi_dri.so
#2  0x00007f0d5e87fd28 in  () at /usr/lib/dri/radeonsi_dri.so
#3  0x00007f0d73f84a9d in start_thread () at /usr/lib/libpthread.so.0
#4  0x00007f0d74099b23 in clone () at /usr/lib/libc.so.6

Thread 8 (Thread 0x7f0d537fe700 (LWP 24736)):
#0  0x00007f0d73f8aafc in pthread_cond_wait@@GLIBC_2.3.2 () at /usr/lib/libpthread.so.0
#1  0x00007f0d5e880004 in  () at /usr/lib/dri/radeonsi_dri.so
#2  0x00007f0d5e87fd28 in  () at /usr/lib/dri/radeonsi_dri.so
#3  0x00007f0d73f84a9d in start_thread () at /usr/lib/libpthread.so.0
#4  0x00007f0d74099b23 in clone () at /usr/lib/libc.so.6

Thread 7 (Thread 0x7f0d53fff700 (LWP 24735)):
#0  0x00007f0d73f8aafc in pthread_cond_wait@@GLIBC_2.3.2 () at /usr/lib/libpthread.so.0
#1  0x00007f0d5e880004 in  () at /usr/lib/dri/radeonsi_dri.so
#2  0x00007f0d5e87fd28 in  () at /usr/lib/dri/radeonsi_dri.so
#3  0x00007f0d73f84a9d in start_thread () at /usr/lib/libpthread.so.0
#4  0x00007f0d74099b23 in clone () at /usr/lib/libc.so.6

Thread 6 (Thread 0x7f0d58ce5700 (LWP 24734)):
#0  0x00007f0d73f8aafc in pthread_cond_wait@@GLIBC_2.3.2 () at /usr/lib/libpthread.so.0
#1  0x00007f0d5e880004 in  () at /usr/lib/dri/radeonsi_dri.so
#2  0x00007f0d5e87fd28 in  () at /usr/lib/dri/radeonsi_dri.so
#3  0x00007f0d73f84a9d in start_thread () at /usr/lib/libpthread.so.0
#4  0x00007f0d74099b23 in clone () at /usr/lib/libc.so.6

Thread 5 (Thread 0x7f0d594e6700 (LWP 24733)):
#0  0x00007f0d73f8aafc in pthread_cond_wait@@GLIBC_2.3.2 () at /usr/lib/libpthread.so.0
#1  0x00007f0d5e880004 in  () at /usr/lib/dri/radeonsi_dri.so
#2  0x00007f0d5e87fd28 in  () at /usr/lib/dri/radeonsi_dri.so
#3  0x00007f0d73f84a9d in start_thread () at /usr/lib/libpthread.so.0
#4  0x00007f0d74099b23 in clone () at /usr/lib/libc.so.6

Thread 4 (Thread 0x7f0d59e3d700 (LWP 24732)):
#0  0x00007f0d73f8aafc in pthread_cond_wait@@GLIBC_2.3.2 () at /usr/lib/libpthread.so.0
#1  0x00007f0d5e880004 in  () at /usr/lib/dri/radeonsi_dri.so
#2  0x00007f0d5e87fd28 in  () at /usr/lib/dri/radeonsi_dri.so
#3  0x00007f0d73f84a9d in start_thread () at /usr/lib/libpthread.so.0
#4  0x00007f0d74099b23 in clone () at /usr/lib/libc.so.6

Thread 3 (Thread 0x7f0d65835700 (LWP 24731)):
#0  0x00007f0d7408ec21 in poll () at /usr/lib/libc.so.6
#1  0x00007f0d6d595630 in  () at /usr/lib/libxcb.so.1
#2  0x00007f0d6d5972db in xcb_wait_for_event () at /usr/lib/libxcb.so.1
#3  0x00007f0d6698e96b in  () at /usr/lib/libQt5XcbQpa.so.5
#4  0x00007f0d7454e9cc in  () at /usr/lib/libQt5Core.so.5
#5  0x00007f0d73f84a9d in start_thread () at /usr/lib/libpthread.so.0
#6  0x00007f0d74099b23 in clone () at /usr/lib/libc.so.6

Thread 2 (Thread 0x7f0d67a45700 (LWP 24730)):
#0  0x00007f0d73f8aafc in pthread_cond_wait@@GLIBC_2.3.2 () at /usr/lib/libpthread.so.0
#1  0x00007f0d743b6cd1 in __gthread_cond_wait (__mutex=<optimized out>, __cond=<optimized out>) at /build/gcc/src/gcc-build/x86_64-pc-linux-gnu/libstdc++-v3/include/x86_64-pc-linux-gnu/bits/gthr-default.h:864
#2  0x00007f0d743b6cd1 in std::condition_variable::wait(std::unique_lock<std::mutex>&) (this=<optimized out>, __lock=...) at /build/gcc/src/gcc/libstdc++-v3/src/c++11/condition_variable.cc:53
#3  0x00007f0d77b4bf54 in  () at /usr/lib/libQt5WebKit.so.5
#4  0x00007f0d77b4c079 in  () at /usr/lib/libQt5WebKit.so.5
#5  0x00007f0d743bd063 in std::execute_native_thread_routine(void*) (__p=0x55dc978c5360) at /build/gcc/src/gcc/libstdc++-v3/src/c++11/thread.cc:80
#6  0x00007f0d73f84a9d in start_thread () at /usr/lib/libpthread.so.0
#7  0x00007f0d74099b23 in clone () at /usr/lib/libc.so.6

Thread 1 (Thread 0x7f0d67a50b40 (LWP 24729)):
[KCrash Handler]
#6  0x00007f0d58369fa6 in  () at /usr/lib/qt/plugins/bearer/libqnmbearer.so
#7  0x00007f0d583774db in  () at /usr/lib/qt/plugins/bearer/libqnmbearer.so
#8  0x00007f0d756a7039 in QNetworkConfigurationManagerPrivate::defaultConfiguration() const () at /usr/lib/libQt5Network.so.5
#9  0x00007f0d756a3b7f in QNetworkConfigurationManager::defaultConfiguration() const () at /usr/lib/libQt5Network.so.5
#10 0x00007f0d7562de82 in  () at /usr/lib/libQt5Network.so.5
#11 0x00007f0d7562e44d in  () at /usr/lib/libQt5Network.so.5
#12 0x00007f0d7473528c in QMetaObject::activate(QObject*, int, int, void**) () at /usr/lib/libQt5Core.so.5
#13 0x00007f0d756a37a6 in QNetworkConfigurationManager::configurationChanged(QNetworkConfiguration const&) () at /usr/lib/libQt5Network.so.5
#14 0x00007f0d756a3ee2 in  () at /usr/lib/libQt5Network.so.5
#15 0x00007f0d74735b62 in QObject::event(QEvent*) () at /usr/lib/libQt5Core.so.5
#16 0x00007f0d750d2e34 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/libQt5Widgets.so.5
#17 0x00007f0d750da671 in QApplication::notify(QObject*, QEvent*) () at /usr/lib/libQt5Widgets.so.5
#18 0x00007f0d7470a8f9 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/libQt5Core.so.5
#19 0x00007f0d7470d998 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () at /usr/lib/libQt5Core.so.5
#20 0x00007f0d74760fd4 in  () at /usr/lib/libQt5Core.so.5
#21 0x00007f0d737eaa2f in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#22 0x00007f0d737ec5e9 in  () at /usr/lib/libglib-2.0.so.0
#23 0x00007f0d737ec62e in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#24 0x00007f0d747605a9 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Core.so.5
#25 0x00007f0d7470958c in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Core.so.5
#26 0x00007f0d74711896 in QCoreApplication::exec() () at /usr/lib/libQt5Core.so.5
#27 0x000055dc95742479 in main ()
[Inferior 1 (process 24729) detached]
```

**Comment by dolohow** [comment] 2019-01-05 17:14
@MorphBonehunter I updated the title accordingly.

**Comment by javierllorente** [comment] 2019-01-14 22:45
Duplicate of #970

**Closed by javierllorente** 2019-01-14 22:45 UTC
