### ISSUE TITLE
[Bug]: Virtual files - Status icons from shortcuts don't get updated

### ISSUE THREAD

**Issue by DerFranke** [nextcloud/desktop#5825] opened 2023-06-20 08:10 UTC
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

The status icon of shortcuts and .lnk files (also shortcuts) always shows "sync in progress". The synchronization itself works without any problems. It also doesn't matter if the shortcuts are synced to the server or from the server. The problem only occurs when virtual files are enabled.

The same happens to files on the exclude list.

### Steps to reproduce

1. Setup Nextcloud with virtual files
2. Put some shortcuts or .lnk-files in the local folder
3. The files get synced, but the icons stay at "sync in progress"

### Expected behavior

The file should get a green tick or cloud icon.

### Which files are affected by this bug

Neues Textdokument.txt - Verknüpfung

### Operating system

Windows

### Which version of the operating system you are running.

Windows 10 Enterprise

### Package

Other

### Nextcloud Server version

26.0.2

### Nextcloud Desktop Client version

3.9.0

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [X] Default internal user-backend
- [ ] LDAP/ Active Directory
- [X] SSO - SAML
- [ ] Other

### Nextcloud Server logs

```shell
there are no related errors on the server
```

### Additional info

![lnk](https://github.com/nextcloud/desktop/assets/78349773/445382db-8469-480c-a550-63197341148d)

[Debug archive](https://github.com/nextcloud/desktop/files/11797411/log.zip)

**Comment by PhilippSchlesinger** [comment] 2023-07-07 07:33
See corresponding issues https://github.com/nextcloud/desktop/issues/5594 and https://github.com/nextcloud/desktop/issues/5524.
There is also a pull request (https://github.com/nextcloud/desktop/pull/5853) that may close these issues.

**Comment by m7913d** [comment] 2023-07-09 13:39
Duplicate of #5594

**Closed** 2023-07-20 13:01 UTC
Labels: 0. Needs triage

**Comment by PhilippSchlesinger** [comment] 2023-07-26 18:16
With nextcloud client release 3.9.1 this doesn't seem to work:

![grafik](https://github.com/nextcloud/desktop/assets/2735628/b0c066b2-c16c-4e43-b74e-35c5fced6a8a)

I would expect no syncing icon as for other excluded files.

**Comment by m7913d** [comment] 2023-07-26 20:14
I don't think the fix is already included in 3.9.1. I guess it will be in 3.9.2 or you can try some nightly build.

**Comment by m7913d** [comment] 2023-07-26 20:48
Does it work if you add a new link file?

**Comment by DerFranke** [comment] 2023-07-27 05:58
It works for me with new files. Links and ignored files don't have a status icon now.  
However, existing files are not updated.  

But the problem is another one: The links do get synced, so I think a cloud or green tick icon should be the right one.  

![Screenshot](https://github.com/nextcloud/desktop/assets/78349773/a356e85e-7682-4a82-b9ec-8e01085a4316)

**Comment by PhilippSchlesinger** [comment] 2023-07-27 07:53
@DerFranke I can confirm what you describe.

Additionally, it shows 'excluded' in file details dialog for a new link, which seems wrong as that file is synchronised:
![grafik](https://github.com/nextcloud/desktop/assets/2735628/cc24ffb7-5fc8-496e-8f62-f0a4a271641a)

There is no way for existing links to stop them showing the syncing icon. Cycling 'always keep on this device' and 'free up space' also does not work.

**Comment by PhilippSchlesinger** [comment] 2023-07-27 10:34
> There is no way for existing links to stop them showing the syncing icon. Cycling 'always keep on this device' and 'free up space' also does not work.

I have to correct that. Existing link files get updated if the link target is valid.
Link files with invalid targed show the syncing icon forever.

**Comment by m7913d** [comment] 2023-07-27 21:37
For now, we are indeed considering link files as excluded files concerning the virtual file system, as link files are currently synced as regular files (just as would be done if the virtual file system is not used) due to limitations of an internally used library (qt5). After upgrading this library we could sync them using the virtual file system and show the   correct sync state. I'm not aware of the timeline of this upgrade as I'm not affiliated to Nextcloud. 

In the meantime, I think it is better to show no sync icon (=excluded state), as a syncing icon also affects the reported syncing state of the parent folders. This is implemented in my PR and merged in release 3.9.1.

@mgallien Maybe we should reopen this issue, until we have fully fixed the issue:
 - show synced (green tick/cloud icon) icon when appropriate 
 - correctly handle old/invalid links.
Sorry that I marked it as closed in my PR.

**Comment by PhilippSchlesinger** [comment] 2023-07-28 09:32
@m7913d thank you for your great work on all those syncing issues, this improves the reliability of nextcloud client a lot!

There seems to be much activity in https://github.com/nextcloud/desktop/pull/4584 recently, so hopefully it will be possible to handle links consistently via vfs.

Nextcloud client still states that symbolic links are not synced (marked green), which does not seem to be true any more.
![grafik](https://github.com/nextcloud/desktop/assets/2735628/99fd3504-8acb-4e40-b5a5-fc919e55f7d5)

It will be a good improvement to handle stale/invalid links correctly and show that in the UI.
