### ISSUE TITLE
adding command line options to the Nextcloud client setup exe or create a msi setup file

### ISSUE THREAD

**Issue by finius** [nextcloud/desktop#59] opened 2017-11-24 13:37 UTC
I would suggest to add a support of command line installation options to the Windows Nextcloud client to make administrators able to predefine some basic config settings (like server URL, authentication/username, sync options, etc) to enhance user experience as no GPO package is available to autoconfig Nextcloud after installation on an enterprise level.

**Comment by michaelstingl** [comment] 2017-12-10 22:54
Related: https://github.com/owncloud/client/issues/1419#issuecomment-321276717

**Comment by Square252** [comment] 2018-01-30 09:38
+1, major drawback for many of our customers. We got around 2.000 possible client to deploy in one environment. The complete lack of automated install or configuration options is one major reason our nextcloud instance isn't used that much... Some customers are even switching to crappy stuff like cryptshare :/

**Comment by mathiasconradt** [comment] 2018-07-30 11:23
@camilasan Is this feature request currently on the roadmap (if so, is there an approx. target date) or not with a fixed schedule yet?

**Comment by mathiasconradt** [comment] 2018-07-30 12:40
@aTanCS yes, I also meant the .msi package :)

**Comment by camilasan** [comment] 2018-07-30 12:54
@mathiasconradt It is currently not in the roadmap but of course we can prioritize it if there is such  demand. We will make time for it ;)

**Comment by finius** [comment] 2018-07-30 12:58
+1

Am 30.07.2018 um 14:54 schrieb Camila Ayres <notifications@github.com<mailto:notifications@github.com>>:


@mathiasconradt<https://github.com/mathiasconradt> It is currently not in the roadmap but of course we can prioritize it if there is such demand. We will make time for it ;)

**Comment by cyber035** [comment] 2018-08-23 13:14
+1

**Comment by 11harveyj** [comment] 2018-08-27 21:37
+1

**Comment by carloscaballero** [comment] 2018-08-31 09:02
+1 
I would like to be able to modify all nextcloud clients: Windows, Linux, Android, Apple

**Comment by maghog** [comment] 2018-10-16 08:46
+1

**Comment by johnripper1** [comment] 2018-11-08 22:59
+1

**Comment by mjuddi** [comment] 2018-11-28 12:55
+1

**Comment by bluikko** [comment] 2019-01-30 07:35
Any updates on the MSI installer file? Should definitely be on the roadmap in my opinion.

It would be very inconvenient to deploy the desktop client for Windows manually.

**Comment by User867** [comment] 2019-03-11 16:26
Hello people,

Big +1, as we want to deploy Nextcloud on all our machines. Cannot be done manually... Is anyone working on the MSI actually ?

**Comment by johnripper1** [comment] 2019-03-11 19:13
As there is would be an improvment and there is no two year long discussion why this feature is not required at all.  

EOLing nextcloud here.

**Comment by ndom91** [comment] 2019-04-04 19:26
For those of you trying to provision the nextcloud client to Windows workstations, maybe checkout chocolatey: https://chocolatey.org/packages/nextcloud-client

It is an apt-get / npm / pip like package manager for windows through which you can deploy software (incl. exe's!) via AD as well.

**Comment by BloodyIron** [comment] 2019-05-06 19:12
There's a very big drive for nextCloud working well in the corporate/org space, and being able to not only deploy nextCloud desktop clients en-masse, but also have it automatically configured based on the user being installed for (or perhaps SSO via kerberos on the local system) would have very high value for many installations of any size. Be it 50, or 50,0000.

Why aren't we prioritizing this? This tangibly leads to increased installations, especially for very large environments. There's no way very large environments are going to do this without the ability to automate the installation and initial configuration (let alone central management of that).

**Comment by bluikko** [comment] 2019-05-07 03:31
> Why aren't we prioritizing this? This tangibly leads to increased installations, especially for very large environments. There's no way very large environments are going to do this without the ability to automate the installation and initial configuration (let alone central management of that).

This is so correct. MSI is **the** standard way to deploy software on Windows. For corporate installations it is a hard requirement.

**Comment by johnripper1** [comment] 2019-05-07 08:08
A rollout via e.g. SCCM with basic configuration options is possible already. Not very conviniant but its possible.

The more bigger issue is a centralized configuration.

I'm just not able to do manual configuration for my organization and therefore I will set this to production.

**Comment by BloodyIron** [comment] 2019-05-07 16:21
Also, how exactly do we handle the desktop client on a system where multiple people login? Can we get the client to auth via local Kerberos ticket, or session, or?

**Comment by Highview-Lucas** [comment] 2019-05-16 23:20
> A rollout via e.g. SCCM with basic configuration options is possible already. Not very conviniant but its possible.

So much this. It seems every release of the client needs it's own testing cycle to see which switches can be passed in to the installer to have it both install, and not irritate the users. (2.3.something rebooted without warning!)

SCCM + MSI == Easy Mode. 
SCCM + MSI + GPOs would be perfect - but it's GPOs, I'd understand if you didn't want to support them. Being able to pass in a config would be so, so so nice.

**Comment by User35123** [comment] 2019-08-16 06:59
+1

**Comment by bluikko** [comment] 2019-08-16 07:35
> Being able to pass in a config would be so, so so nice.

What configuration does this "pass in a config" refer to?

In my opinion, ideally passing any files to install should not be needed:
- If you mean configuration for setup - it'd be an MSI file, just use a transform.
- If you mean configuration for the program like where is the server - a file could be passed with GPP or, even better, the program could be configured with registry/GPO. I assume it is a cross-platform application and support for Windows registry might not fit. But surely that would be the standard way of doing things in Windows.

**Comment by Highview-Lucas** [comment] 2019-08-19 23:21
> What configuration does this "pass in a config" refer to?

Ideally, it would mean "my users never see the first-run wizard because by the time they click on the NC desktop icon, it's already been done"

As it stands the first thing they have to do is answer a question between "login" or "register" and then some extra details they do know, but pretend not to, and the a whole page of options that basically boil down to "it's irrelevant, press next"

(side question: why do we even have a register button?) 

The client is mostly fine for people that want to install nextcloud on their desktops. It's completely not for someone that wants to deploy it to several hundred devices at once, and have the end users _use_ it.

**Comment by bluikko** [comment] 2019-08-20 02:50
Understood. I totally agree. There must be a way to deploy it automatically.

**Comment by gvansanden** [comment] 2019-10-07 08:26
+1

**Comment by it25fg** [comment] 2019-10-14 13:12
A simple question: Would it be simpler instead of creating a full-fledged installer if the desktop client could act upon some environment variables? Just like the ones documented in https://docs.nextcloud.com/desktop/2.5/advancedusage.html#environment-variables ? Nearly every prospect or customer is asking me about how to deploy the desktop client with predefined defaults, and the only remaining answer is "generate some config and deploy it before installing the client".

**Comment by gvansanden** [comment] 2019-10-14 13:23
@it25fg I'd like that too...

**Comment by BloodyIron** [comment] 2019-10-14 16:52
Also, I'd like to point out this functional need should not just be scoped for Windows. We should figure out a way to do the same functional aspects for Linux and OSX users (have the client install with pre-defined parameters already). So that there is a consistent UX from one OS to another.

One thought, maybe make it so you can download an "installer for this user" or something like that? Whereby the admin can download for a user on their behalf, or the user can download when logged into the web interface.

There are some scenarios where this doesn't work though, such as if the users don't have access to install stuff, or if there are very large number of users to be setup. We would need to figure out a way to do that en-masse too.

Just some thoughts, but I do think this is something very desirable to controlled IT environments of any org (biz or otherwise).

**Comment by johnripper1** [comment] 2019-10-14 17:45
Two year and absolutly nothing happend. 

Ive been asked a lot of times too, how to deploy and config the client with WSUS, SCCM or simular.

Just lost another project to the onedrive, fully integrated client with all the benefits of deployment, sso, and auto config.

Frustrating...

**Comment by Highview-Lucas** [comment] 2019-10-14 21:37
> A simple question: Would it be simpler instead of creating a full-fledged installer if the desktop client could act upon some environment variables? 

Please no. that _guarantees_ you need to reboot the machine, and I can guarantee 50% of my users won't, so it won't actually change the outcome. 


> Two year and absolutly nothing happend.

There have been a couple of quick new major versions lately, so I popped over to check the commit logs. there are a lot that say "loop optimisation". It's getting to the point where I'm going to have to fork it to make it do the things I need, what I don't have is time!

**Comment by it25fg** [comment] 2019-10-15 09:16
> Please no. that _guarantees_ you need to reboot the machine, and I can guarantee 50% of my users won't, so it won't actually change the outcome.

Who would need a reboot? The Nextcloud client is not a service. If the admin _feels_ he must force client machines to reboot on every single installation, he should use some framework that enforces that (which, i would presume, will exist in companies interested in automatic software rollout anyway).

As a side note: they already tried to incorporate such "functionality" but did not get it right: https://github.com/nextcloud/desktop/issues/1040

To clarify: my question is about users being (at least) adventorous, and when they see the client for the first time, deciding the wrong things (for instance, 'sign up for a service' even though their account was already provisioned). That way, an admin or help desk has to repair mistakes of users. I have asked for a means that the admin can use to predefine things that are usually predefined (company defaults: user drive letter, default server, login name).

**Comment by BloodyIron** [comment] 2019-10-15 15:31
To be fair, if you're managing a suite of Windows systems and you don't have a reboot schedule, well then you're not properly applying security updates, and you have bigger problems.

I'm not saying the NC agent should require a reboot, but more that it is a moot point.

**Comment by Highview-Lucas** [comment] 2019-10-15 22:31
> Who would need a reboot?

environment variables tend not to exist prior to a reboot. given you can completely replace a GFX driver without a reboot in windows 10 now, forcing a reboot from something as non-essentilal as a sync client isn't a reason to need a reboot. 

but, we're arguing the same side of the same argument: the client does nothing to make life easier as an admin. 


> To be fair, if you're managing a suite of Windows systems

I am, and i deliver the NC client via SCCM, which means there's one standard place to get one standard version for all of my users, which they can add or remove as they see fit. 

but you are correct, it is a moot point. the software needs to _function better._ .... which was the topic of the thread 2 years ago, and we're still asking for the same thing.

**Comment by BloodyIron** [comment] 2019-10-16 03:33
Configuration Management systems (SCCM, Puppet, etc) are a primary reason this aspect needs to be developed. If we can get NC to be rolled out to a limitless number of users in an organisation, this will massively improve NC adoption.

Come on devs!

**Comment by johnripper1** [comment] 2019-10-16 13:44
To all using SCCM: How do you handel the update of the client on the user Desktop?

Pushing out an update of the client, results in the shutdown of the application within the user context and then the update of the nextcloud client by SCCM/Software Center. Of course all silent.
BUT the problem is that afterwards the client is not started automatically. 
So in many enviroments I force a restart of the maschine to make sure the client is up and syncing. On the first wave I didnt do that, was resulted in an out of sync directories, while the user didnt notice that, as everything was run in the background.

Another big issue of nextcloud client.

Like saied: compared to OneDrive, the nextcloud application is really missing a lot of Integration in a professional environment.

**Comment by Highview-Lucas** [comment] 2019-10-16 22:19
in short: poorly. 

create a new app, supersede old version, deploy with "uninstall old" and "available" (instead of required). with the current version if you follow it's prompts just reinstalls the old version instead of the new version. 

I detect on the version number of nextcloud.exe and added the random return code (1223) as a success  - if you don't do that it stays on "failed, retry" forever. i use the uninstall.exe in the installed nextcloud directory - but it's currently asking questions even with /S

As for why it does not run - i'm halfway thinking of making some kind service that runs the sync client for me - the client also crashes silently, i'm thinking with a service i can check to make sure it's running periodically

**Comment by FEKJHhrgfre** [comment] 2019-10-18 09:25
The MSI is needed, the GPO's would be welcome.

**Comment by it25fg** [comment] 2019-10-18 09:37
> The MSI is needed, the GPO's would be welcome.

MSI and GPO's -- a Micro$~1-only thing... wouldn't it be better to ask for a portable mechanism such as environment variables which could be set up by every system nowadays?

**Comment by bluikko** [comment] 2019-10-18 10:27
This issue is not so good because it conflates two different issues.

It should be split into two:
- Environment variables for configuration.
- MSI installer.

**Comment by ndom91** [comment] 2019-10-18 10:32
@bluikko - very good point. 

I think an MSI installer should be a separate issue as well. 

It would then make sense to devise a way to configure the roll out platform independently, i.e. Env variables as has been suggested before, or a config file. The MSI installer could consume these on windows, and on Linux/Mac, for example, the config file could just be placed in the correct dir or env variables set.

**Comment by BloodyIron** [comment] 2019-10-18 18:27
Env variables aren't a way to streamline the process of authentication setup though, as that could be retrieved by another app and reversed to get credentials.

Also, this needs to be planned for a way to set it up so multi-user on the same system works. Whereby, the logged-in session are the creds used for nextCloud, be it kerberos or otherwise.

**Comment by BloodyIron** [comment] 2019-10-18 18:29
The fact it ignores silent for uninstall clearly demonstrates it is not properly written for an environment like that, or even Linux configuration management environments. This aspect too is a problem. And the upgrade of the agent should be done in-place and not involve an uninstall/reinstall, unless you're using a package management system like Aptitude/Yum/whatever (which is not Windows). To reiterate, in Windows, the upgrade process should be done in-place.

> i use the uninstall.exe in the installed nextcloud directory - but it's currently asking questions even with /S
> 
> As for why it does not run - i'm halfway thinking of making some kind service that runs the sync client for me - the client also crashes silently, i'm thinking with a service i can check to make sure it's running periodically

**Comment by johnripper1** [comment] 2019-10-18 19:23
"Env variables aren't a way to streamline the process of authentication setup though, as that could be retrieved by another app and reversed to get credentials."
What a bullshit!
Env. variables are not used for auth, just how the software behave.
Of course the auth is done with user cred. 
And if you consider this unsave: onedrive is doing exactly that.

**Comment by wiswedel** [comment] 2019-10-18 21:05
@johnripper1 please watch your language

**Comment by it25fg** [comment] 2019-10-21 08:37
@BloodyIron 

> Env variables aren't a way to streamline the process of authentication setup though, as that could be retrieved by another app and reversed to get credentials.

You misunderstood my point, to a degree. I wanted to propose that environment variables could be used for predefining a connection (URL or server), a login name (whatever is configured as default login scheme in Nextcloud) and optionally a default position of the local folder (depending on company standards about drive mappings/home etc.). 

Regarding credentials, I agree with you: Credentials don't belong into the environment; these should be asked for, just the same way as it would happen when credentials have changed: the client pops up the password dialog.

**Comment by BloodyIron** [comment] 2019-10-21 16:05
I think Env variables could work for non-credential aspects (username should not be included)

However, I think one of the challenges there is making it so that those parameters don't cause problems for multi-user single systems (think, factory floor). Whereby:
1. You don't grant access to stuff when you switch your Windows session to another user (that they shouldn't have access to)
2. When you switch Windows session to another user (switch user) it "mounts" the NC content for the user it just switched into
3. The NC agent/daemon/service/client sync's content accurately for all users logged in

Generally, I'm not sure how to account for all scenarios, but to make it multi-user aware, not just for Windows, but Linux, OSX, even Android/IOS.

I think this is also a critical part of expanding the parameter aspects of the nextCloud installation. Bit of a mouth full, sorry.

> @BloodyIron
> 
> > Env variables aren't a way to streamline the process of authentication setup though, as that could be retrieved by another app and reversed to get credentials.
> 
> You misunderstood my point, to a degree. I wanted to propose that environment variables could be used for predefining a connection (URL or server), a login name (whatever is configured as default login scheme in Nextcloud) and optionally a default position of the local folder (depending on company standards about drive mappings/home etc.).
> 
> Regarding credentials, I agree with you: Credentials don't belong into the environment; these should be asked for, just the same way as it would happen when credentials have changed: the client pops up the password dialog.

**Comment by Highview-Lucas** [comment] 2019-10-21 22:42
please stop saying "environment variables", it means you're thinking about them, and they're a terrible solution - especially when the request was "command line options, or a OS-Native install method"

**Comment by loxK** [comment] 2019-11-13 13:41
Don't hold your breath it is a paid feature: https://nextcloud.com/blog/branded-nextcloud-clients/

**Comment by johnripper1** [comment] 2019-11-13 15:58
Okay so this means that the msi installer will the permanently paied feature.

This means we will retire nextcloud with end of 16.

**Comment by bluikko** [comment] 2019-11-16 04:05
OwnCloud seems to have MSI package for OwnCloud Desktop.

Strange that NextCloud has decided that it is only for paid clients if OwnCloud provides it for the community edition.

We'll probably be going that way also.

**Comment by Highview-Lucas** [comment] 2019-11-17 21:33
I'm pleased to report the ownCloud client actually works with a nextcloud server (16.x)

This is exactly what I needed!

**Comment by Trinity-Dan** [comment] 2019-11-18 19:01
This decision to only allow paid subscribers to use the MSI installer is a deal breaker for me. When I chose Nextcloud over Owncloud I read a few articles to determine which was the best choice. Had I known of this severe limitation of Nextcloud, I certainly would not have chosen Nextcloud. I hope the powers that be rethink this terrible decision. In the meantime I will be working on an Owncloud installation for our organization.

**Comment by Highview-Lucas** [comment] 2019-11-28 00:42
Update to my previous comments.

I've been using the ownCloud client in place of the NC client on several machines for my own account, including using it as a scratch folder for several multi-hundred MB files across a pretty slow link.

It's not given me any issues, **_at all_**. 
It does not crash on a daily basis like the NC client does. 
It does not randomly end up with files that have changed too often and can't be sync'd.
There is an MSI installer. 
The installer is literally 1/4 the size.

I did actually reach out to the sales people about getting the MSI installer - a) it's not available yet, b) its going to be more expensive than onedrive and google drive. (combined) - we are a school, so we do get better pricing than most people for most things - but NC are not even in the ballpark here!

**Comment by BloodyIron** [comment] 2019-11-28 15:45
Wow...

**Comment by Dennis1993** [comment] 2020-08-19 20:16
Any News here?
We are a little school and I installed Nextcloud for us because corona...
Now I want to install the client on the school conputers for our teachers. I have installed the client on all 12 computers manually and updated it every time. Today the next version 3.0... 

Thats a bad way in 2020 and my colleges wont use the client any more.

I think the default client should be downloadable as a msi file and the customization can be paid by users. Only the basic should be for free. If no msi will be downloadable soon the users looking for another cloud software. Thats a basic function!

Sorry, we use nextcloud only for video calls since last week because its to complicated to update all manually

**Comment by loxK** [comment] 2020-08-20 05:13
@Dennis1993 Dead end. See my previous comment https://github.com/nextcloud/desktop/issues/59#issuecomment-553408963

**Comment by BloodyIron** [comment] 2020-08-20 12:47
Yeah with the new client coming out we really need CLI interaction to automate/streamline the installation of the client en-masse on Windows systems.

**Comment by LukBukkit** [comment] 2020-11-01 11:30
Good news everyone, the latest release [3.0.3](https://github.com/nextcloud/desktop/releases/tag/v3.0.3) ships with an .msi installer which can be configured. [More information](https://github.com/nextcloud/desktop/blob/master/doc/installing.rst#customizing-the-windows-installation)
Pull request: #2500

**Comment by gvansanden** [comment] 2020-11-01 11:38
As far as I can see it does not allow provisioning an account...





-----Original message-----

**Comment by bluikko** [comment] 2020-11-02 04:06
It is an excellent start at least.

I hope account provisioning is looked into next. It should be made as easy as possible for the user - for example in an unprovisioned state clicking the tray icon should just ask for username & password or other authentication type.

**Comment by wiswedel** [comment] 2020-11-02 07:42
This thread has become quite some hard to overlook discussion.
Since msi is available now and the initial request has been served, I'm closing this issue. Please open new issues with specific functionality requests if necessary.

**Closed by wiswedel** 2020-11-02 07:42 UTC
Labels: enhancement, feature-request
