### ISSUE TITLE
Windows 10 Client Limit LTE SIM Card use Mobile Data (see owncloud Client

### ISSUE THREAD

**Issue by jonathanmmm** [nextcloud/desktop#243] opened 2018-04-11 05:39 UTC
Here the copy of the issue:
https://github.com/owncloud/client/issues/6445

### Expected behaviour
I am using Windows 10 with a SIM Card with LTE
I have enabled in windows that background and so on is limited, so that e.g. OneDrive won't sync automatically over my SIM Card.
Problem, I don't see such an option like in the Android App etc. that you can only sync via LAN or WLAN or that the service recognizes the setting under: (I am trying to translate german to english, don't know if the name is excactly the same)
settings->Network and Internet -> Datausage (above Proxy, the circle with the piece). -> Datausage limit in background and I have chosen "Always"

### Actual behaviour

It uploaded e.g. a ~800MB file and I didn't want that.
The option with the limit setting this to 0MB folder size would not recognize the difference with LTE or WLAN or LAN.

### Server configuration
Operating system:
Debian Stretch
Web server: 
13.0.1 (Nextcloud)
Database:
MariaDB
PHP version:
7.x
### Client configuration
Client version:
2.3.3 (Nextcloud Client
Operating system:
Windows 10 1709
OS language:
German

**Comment by camilasan** [comment] 2018-04-16 11:33
Considering the comments and extra info given in the oc issue, I believe this issue is a matter of prioritizing (unless someone in the community wants to work on it :) and picking the most doable implementation.

**Comment by camilasan** [comment] 2018-04-20 10:48
A feature #198 would be easier to implement and would solve this issue too.

**Comment by jonathanmmm** [comment] 2018-04-20 15:12
This would solve it somehow.
But the time most people will use LTE and Wi-Fi aren't bound to strict hours.
E.g. a trip or just a few hours on a day.

Many Apps are following the restriction setting of Windows 10 so Windows is telling the device which network is Limited.
Could be also a WiFi Hotspot from a friends phone and you can choose that this WiFi is Limited, because the Laptop doesnt know that the WiFi comes from a Sim Card originally.
-- 
Diese Nachricht wurde von meinem Android Mobiltelefon mit WEB.DE Mail gesendet.Am 20.04.18, 12:48, Camila Ayres <notifications@github.com> schrieb:
A feature #198 would be easier to implement and would solve this issue too.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/nextcloud/client","title":"nextcloud/client","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/nextcloud/client"}},"updates":{"snippets":[{"icon":"PERSON","message":"@camilasan in #243: A feature #198 would be easier to implement and would solve this issue too."}],"action":{"name":"View Issue","url":"https://github.com/nextcloud/client/issues/243#issuecomment-383059415"}}}

**Comment by johnripper1** [comment] 2018-11-21 21:53
#198 doesnet solve the problem at all.

How about different sync settings based in the connected networked?
Cloud be identfied by system given ID. If the ID is new, client ask how to proceed (maybe).

**Comment by isdnfan** [comment] 2020-10-12 08:31
duplicate of #39 - sync should stop on mobile/metered WiFi connection

**Closed** 2021-02-15 17:57 UTC
Labels: enhancement, epic, feature-request, help wanted
