### ISSUE TITLE
Empty files blocks sync activity.

### ISSUE THREAD

**Issue by koppd** [nextcloud/desktop#4157] opened 2022-01-08 18:05 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour
Empty files are synced.

### Actual behaviour
Empty files are not synced and furthermore blocks syncing of other files as well.
(as soon as the empty file contain at least one byte -> syncing works great again!)

### Steps to reproduce
1. Windows client 3.4.1: Create emtpy file
2. Wait for sync or force sync
3. There are errors in the server logs. (And files ar not synced)

### Client configuration
Client version:
3.4.1

Operating system:
Win 10

OS language:
German 

Installation path of client:

Virtual files are activated. (And bulk upload as well, because server has > v23.0.0

### Server configuration

Nextcloud version:
v23.0.1 RC1
Storage backend (external storage):

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile: 
Since 3.1: Under the "General" settings, you can click on "Create Debug Archive ..." to pick the location of where the desktop client will export the logs and the database to a zip file.
On previous releases: Via the command line: `nextcloud --logdebug --logwindow` or `nextcloud --logdebug --logfile log.txt`
(See also https://docs.nextcloud.com/desktop/3.0/troubleshooting.html#log-files)

2. Web server error log:
[nclog.txt](https://github.com/nextcloud/desktop/files/7833719/nclog.txt)

3. Server logfile: nextcloud log (data/nextcloud.log):
[Server_empty_files.txt](https://github.com/nextcloud/desktop/files/7833646/Server_empty_files.txt)

The file "Datei mit Inhalt.txt" has content and has been created first.
Then the empty file "datei ohne Inhalt.txt" second.
The third file "Datei mit Inhalt - Kopie" (with content) was created last. Only the first files has been synced.

**Comment by koppd** [comment] 2022-01-09 16:19
And here the client log file:
[emtpy.zip](https://github.com/nextcloud/desktop/files/7835425/emtpy.zip)

**Comment by claell** [comment] 2022-01-18 10:39
@koppd Do you know whether this worked before with older client versions? It might also be interesting to see whether virtual files and/or bulk upload play a role in this.

**Comment by koppd** [comment] 2022-01-20 20:17
To be more precise: The synchronizations stops only for the folder which contains new empty files. Other folders are synchronized. In other words: The sync stop for any folder which contains empty files.

And to answer your question:
For version 3.4.1 the bug exists both both cases: with enabled Virtual Files as well as with disabled Virtual Files.
Downgrade to version 3.3.6 (with virtual files) doesn't show the bug.
From my point of view I would say it has something to do with the new bulk upload feature.

**Comment by Murgeye** [comment] 2022-01-24 09:28
I can confirm this issue on 3.4.1. As soon as there is an empty file in a directory, Nextcloud stops syncing. Noticed this because it broke my KeePass Database syncing, as KeePassXC stores temporary 0 byte files in the directory of the database. As soon as I disable this and delete any 0 byte files, syncing resumes.

**Comment by claell** [comment] 2022-01-24 10:15
Thanks for the update!

Ping @mgallien @allexzander

**Comment by Razza2018** [comment] 2022-01-26 05:33
I'm on version 3.4.1 (Windows 10) and this issues is happening to me as well.

As soon as an empty file (in my case a .txt file) is in a directory, that file and all other files in the directory don't sync.

This is happening whether or not virtual file support is on.

I think empty files should still be synced between devices.

**Comment by claell** [comment] 2022-01-31 12:45
Adding the approved label, since three people see this reproducible.

**Comment by ztiziano** [comment] 2022-02-15 09:27
Hi everyone,

I'm wondering if there are any news on this topic, since I'm having the same issue on my setup as well, 0-byte files don't synchronize properly.

Nextcloud Server: 23.0.0 / 23.0.1 (tested both versions)
Nextcloud Client: 3.4.1 / 3.4.2 (tested both versions on Windows 10)

I noticed the sync issue is one-way, namely 0-byte files created locally (on local host with NC client installed) won't sync to the server, and even worst those files freeze the NC client's synchronization process. The other way around, 0-byte files on the server, are consistently synchronized down (this scenario is easily tested with external storage mounts or by using the workaround described at the bottom).

The 0-byte issue exists both with native storage managed by NC server, or with mounted storages (through external storage. In this case I only tested SMB shares).

To note is that 0-byte files synchronized down from the server to the local host will then be properly handled by the NC client. For example renaming locally one of those files results in a correct synchronization back to the server, even though the file's size is still 0-byte.

Every time the NC client attempts to synchronize a 0-byte file the following _Fatal Message_ for the _App webdav_ is triggered "**Sabre\DAV\Exception**: Unknown error while seeking content" (see attachment for details).

A **workaround** to this issue is using an older version of the NC client, as already suggested by many (thank you guys). I'm currently using version 3.3.6 and it works just fine with 0-byte files, even though I'm not benefiting of the newest features Nextcloud 23 is offering...

I gladly provide any information you might need to fix this issue, and I take this opportunity to thank the Nextcloud dev team for their wonderful job!

Cheers,
happy user since 2019

[Fatal_Webdav_SabreDAVException.txt](https://github.com/nextcloud/desktop/files/8067652/Fatal_Webdav_SabreDAVException.txt)

**Comment by ztiziano** [comment] 2022-02-18 08:06
This bug seems to be FIXED with the new server version of Nextcloud 23.0.2.

I tested using Nextcloud client 3.4.2 and it promptly synchronizes 0-byte files with the server.

Cheers,
Tiziano

**Comment by koppd** [comment] 2022-08-31 16:16
> This bug seems to be FIXED with the new server version of Nextcloud 23.0.2.
Well, this bug isn't really fixed. 
The bulk upload (which triggers this error) has been disabled. https://github.com/nextcloud/server/pull/31171/commits/58cec19291ac7f1b10b22286c27e3ab052e9514d
If you manually re-enable the bulk upload, this error will be triggered again.

**Comment by plantroon** [comment] 2023-03-18 18:27
Uploading an empty file still triggers errors. The file is uploaded to the server, but an error is shown (that I can't view because it disappears immediately on Windows).

Same as the above disabling bulk upload makes it stop showing the error. This bug is reintroduced every time somebody changes the default for this option. 

It scared me a little because for a while I thought Nextcloud zeroed out my files. That did not happen luckily, they were empty all along.

NC Desktop 3.7.1, NC Server 25.0.4

(might be similar to issue #5035)

**Comment by koppd** [comment] 2023-09-16 17:44
fixed by https://github.com/nextcloud/desktop/pull/5871
tested with release 3.10.0

**Comment by PhilippSchlesinger** [comment] 2023-09-16 18:08
@koppd:
👍 so you could close the issue yorself

**Closed** 2023-09-16 18:54 UTC
Labels: bug, high, regression, feature: :arrows_counterclockwise: sync engine, approved
