### ISSUE TITLE
Client 2.5.2git on Ubuntu 18.04: Folder tree doesn't open/close

### ISSUE THREAD

**Issue by fraber** [nextcloud/desktop#1249] opened 2019-05-10 11:16 UTC
Hi!

I'm moving from Windows 7 to Ubuntu with Win10 in a virtual machine, so I installed the latest client on both on Ubuntu 18.04 and on Windows 10. Everything OK with Win10. 

However, there are several issues with Ubuntu:
- The initial sync was incomplete. Several (smaller...) folders are missing.
- Now the open/close foldable folder tree doesn't react to mouse clicks anymore. It reads "Nextcloud / Synchronized with local folder / Nextloud" and there is the greyed-out button "Add Folder Sync Connection" .

Other parts of the Ubuntu client seem fine (Activities, General, Network).

I can provide you with remote access to my Ubuntu via GoToMeeting if you want. Just send me an email to fraber@fraber.de.

Client version: 2.5.2git

Operating system: Ubuntu 18.04

OS language: English

Qt version used by client package (Linux only, see also Settings dialog): Not sure. Ubuntu 18.04 out of the box...

Client package (From Nextcloud or distro) (Linux only): I also got a local install, but the same version:
root@lemgo:~# apt list --installed | grep -i nextcloud
libnextcloudsync0/bionic,now 2.5.2-20190319.015224~bionic1 amd64 [installed,automatic]
nextcloud-client/bionic,now 2.5.2-20190319.015224~bionic1 amd64 [installed]
nextcloud-client-l10n/bionic,bionic,now 2.5.2-20190319.015224~bionic1 all [installed,automatic]

Server Operating system: CentOS 7

Web server: Apache

Database: PostgreSQL

1. Client logfile: I just get a single line in the log window when opening the Sync:
[OCC::Application::slotParseMessage 	Running for 39.579 sec

**Comment by mgallien** [comment] 2021-06-01 06:49
Can you test if you can reproduce with the latest version ?
If the issue is fixed, can you close the issue ?

**Comment by fraber** [comment] 2021-06-01 07:37
Sorry, no, will not be able to, dropped Nextcloud because of the slow reaction to this bug.

**Closed** 2021-06-01 09:41 UTC
Labels: bug, needs info
