### ISSUE TITLE
Sync error: “Server stopped accepting new streams before this stream was established”

### ISSUE THREAD

**Issue by kmorber** [nextcloud/desktop#7136] opened 2024-09-16 23:09 UTC
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

Nextcloud client has connection losses.

Sync error: “Server stopped accepting new streams before this stream was established”](https://help.nextcloud.com/t/sync-error-server-stopped-accepting-new-streams-before-this-stream-was-established/59209)

### Steps to reproduce

1. Right click on the file
2. Click on Share Options
3. The share dialog does not display the option to share by e-mail
...

### Expected behavior

no connection losses

### Which files are affected by this bug

all

### Operating system

Windows

### Which version of the operating system you are running.

Windows 11

### Package

Official Windows MSI

### Nextcloud Server version

30.0.0

### Nextcloud Desktop Client version

3.14.0

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [X] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Additional info

[log.zip](https://github.com/user-attachments/files/17021027/log.zip)

**Comment by thalunil** [comment] 2024-09-17 07:55
With a fresh sync, i have the same issue with the version 3.14.0 on Windows.
Version [3.13.4](https://github.com/nextcloud-releases/desktop/releases/tag/v3.13.4) works as expected.

**Comment by PhilippSchlesinger** [comment] 2024-09-17 10:00
@mgallien 
Is this issue caused by https://github.com/nextcloud/desktop/pull/6986, always enabling http2?
There is an ancient bug https://github.com/nextcloud/desktop/issues/1503#issuecomment-593191875 on the same issue, at that time solved via a PR https://github.com/nextcloud/desktop/pull/1823 that disabled http2 due to Qt bugs.

**Comment by kmorber** [comment] 2024-09-17 10:14
I have disabled http2, but same issues.

**Comment by mbentley** [comment] 2024-09-17 10:20
> I have disabled http2, but same issues.

Could you share your web server config?  If you're having this issue but are not using http2, that would be very surprising from what I understand.


I also noticed that doing an initial sync triggered this for me yesterday on macOS using the 3.14.0 client.  I previously had http2 turned on in nginx so I've had to disable it for nextcloud now to allow the sync to work.  I re-installed the 3.12.7 macOS nextcloud client and as expected, it works fine whether I have http2 turned off or on.  That version appears to be one of the last since #6986 was merged.

**Comment by nursoda** [comment] 2024-09-17 11:11
I have enabled http2 (and not http3/quic) in NGINX. I see the issue on Windows 11 23H2v2 with NC Desktop 3.14.0.

Arch Linux still is on 3.13.4, so I can't tell for KDE/Plasma (Qt). I could test AppImage if devs ask for it.

I think the Windows issue should be addressed first, then the fixed release should be tested on all platforms.

**Comment by webneo82** [comment] 2024-09-17 12:17
Same issue here since update the client to V. 3.14.0.

Windows 11 22631.4169
Nextcloud Server 29.0.7 with NGiNX and http/2 enabled. Disabling http/2 will also cause synchronization errors. However, "Server stopped accepting new streams before this stream was established will not appear", but "Connection timeout".

With Nextcloud Client V 3.13.4 all works fine.

**Comment by osiktech** [comment] 2024-09-17 13:48
I ran into the same issue on macOS 14.7 with a fresh sync. I downgraded my client back to 3.13.4 and everything is back to normal.

One more finding (maybe related): My nextcloud server was continuesly deactivating my user account although I allowed my ip address through bruteforce settings.

**Comment by timirons** [comment] 2024-09-17 13:58
Same issue here with a new install today, using Ionos server.

**Comment by mgallien** [comment] 2024-09-17 15:06
we will revert the change and try to find another solution
we did this change because when http1.1 is broken and http2 is working, having to define an env variable is far from obvious as a fix

**Comment by charliehoward** [comment] 2024-09-18 14:17
I'm also having this issue running NextCloudCMD on Ubuntu

**Comment by Stoony1** [comment] 2024-09-18 15:08
same problem here

**Comment by albert-a** [comment] 2024-09-18 15:52
Same problem with Nextcloud AIO 29.0.6 and Desktop client 3.14.0 (Mac)
Subjectively the 3.14.0 client is very very slow and always shows this error.
I removed Desktop client 3.14.0, and installed 3.13.4 and now everything works again, fast and smooth.

**Comment by prrar** [comment] 2024-09-18 21:13
Same problem here. Clean macOS Sequoia 15.0 install, Nextclkoud AIO 29.0.6 and Desktop Client 3.14.0 Mac. I've followed @albert-a 's suggestion and downgraded to 3.14.4. So far, so good.

**Comment by DDQW** [comment] 2024-09-18 22:33
raising the value of keepalive requests (in case of nginx) should help with this. default value is 1000 i raised it to 9999 which seems to be enough for our usecase (no error reported since i made the adjustment) be aware that this increases nginxs ram usage and your system needs to be ready for this.

**Comment by eurovisionfanatic** [comment] 2024-09-19 02:25
Same issues here, everything works fine on 3.13 but 3.14 won't sync.  Disabling HTTP2 causes the Connection Timeout issue.  Has anyone found any mitigations for this?

**Comment by charliehoward** [comment] 2024-09-19 08:59
I unfortunately do not have access to the server side, as I pay for it to be hosted

**Comment by GarmischWg** [comment] 2024-09-19 11:55
> I am having the very same issue. Fresh sync using 3.14 throws this error. V 3.13.4 works smoothly
> 
> [EDIT] Repeatedly Forcing new synchronizations causes a crash in the desktop client.
> 
> ![image](https://private-user-images.githubusercontent.com/86367839/368150061-b5e9f819-a5d8-4b84-a090-f5bb81677455.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY3NDcwODAsIm5iZiI6MTcyNjc0Njc4MCwicGF0aCI6Ii84NjM2NzgzOS8zNjgxNTAwNjEtYjVlOWY4MTktYTVkOC00Yjg0LWEwOTAtZjViYjgxNjc3NDU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE5VDExNTMwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg3YzY3YjMwNGE5ZTZiYzA0YjZlZDI5ZGEzYTE2ZDgwNGRlMjNmN2ZjZTk5MTdjYzlmYmJjYTEyZmNmOWFlZWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jb4WRgbNemIdUvUxbtUFFJOpCGNQ8yH309LkGs4rHZ0)

encoutering the same issue, the solution provided did not solve the issue unfortunately

**Comment by Xenthys** [comment] 2024-09-19 12:15
Same problem here, I almost blamed my hosting provider. Downgrading to 3.13.4 fixed my stream issue.

**Comment by Thomas6013** [comment] 2024-09-19 19:39
I've the same issue with the same configuration

**Comment by GitTimeraider** [comment] 2024-09-19 22:25
Starting receiving notifications that large files could not be uploaded.. tried fixes, nothing helped. Downgraded the client from 3.14 to a lower version (in this case 3.13 to be sure) and that one works perfectly fine

**Comment by Belledonne0** [comment] 2024-09-20 09:00
same error. One Fix is in way ?!

**Comment by charliehoward** [comment] 2024-09-20 09:01
How can I downgrade the client on linux with no GUI? Seems apt only has the current version and 3.11

**Comment by jamesstanw** [comment] 2024-09-20 09:01
Same as reported above

**Comment by osiktech** [comment] 2024-09-20 10:54
@charliehoward you could use the appimage package from here https://github.com/nextcloud-releases/desktop/releases/tag/v3.13.3 depending on the distro you could also download an older version directly from a mirror and do an apt-pinning.

**Comment by charliehoward** [comment] 2024-09-20 13:15
I ran apt list -a nextcloud-desktop but I only get two options -
`nextcloud-desktop/noble,now 3.14.0-20240916.085658.d8fcb9273-1.0~noble1 amd64 [residual-config]
nextcloud-desktop/noble 3.11.0-1.1build4 amd64 [residual-config]`

Unless you can suggest a source with older versions? Specifically 3.13.x

**Comment by xataz** [comment] 2024-09-20 23:26
> For people who run an nginx server this can be fixed serverside:
> 
> raising the value of keepalive_requests should help with this. default value is 1000 i raised it to 99999 (a debug value you should adjust that to your needs) which seems to be enough for our usecase (no error reported since i made the adjustment) be aware that this increases nginxs ram usage and your system needs to be ready for this.
> 
> i also adjusted keepalive timeout in nginx to 600 (10 minutes) from 1 minute. Maybe something for the nginx default config
> 
> http {
> 
> ```
>     ##
>     # Basic Settings
>     ##
> 
>     sendfile on;
>     tcp_nopush on;
>     types_hash_max_size 2048;
>     # server_tokens off;
>     client_max_body_size 512G;
>     # server_names_hash_bucket_size 64;
>     # server_name_in_redirect off;
>     keepalive_requests 99999;
>     keepalive_timeout 600;
>     include /etc/nginx/mime.types;
>     default_type application/octet-stream;
> ```
> 
> So it appears that the client needs a limit to the connections it tries to create and/or not bug out when a connection is refused and just use the ones it got.

Works for me, for a new installation
I pass keepalive_requests from 100 to 1000 and  keepalive_timeout from 15 to 60

**Comment by charliehoward** [comment] 2024-09-21 14:45
I don't have access to serverside, and given the number of issues being raised by others it's just an issue with 14, that may fix the issue temporarily but NextCloud needs to fix the issue now, been way too long without a fix

**Comment by edmundpartacz** [comment] 2024-09-21 16:14
The same problem I have. Cant use Desktop Aplication. Help needed.

**Comment by samjwylam** [comment] 2024-09-21 20:27
also having the same issue on a new windows laptop

**Comment by samjwylam** [comment] 2024-09-21 20:45
FYI I ended up rolling back to an older version of the desktop client

https://download.nextcloud.com/desktop/releases/Windows/

**Comment by edmundpartacz** [comment] 2024-09-21 20:48
Yeah, me, too. Works well.
  

  

  

  
  
  
  
  
>

**Comment by jamesstanw** [comment] 2024-09-22 04:24
> > For people who run an nginx server this can be fixed serverside:
> > raising the value of keepalive_requests should help with this. default value is 1000 i raised it to 99999 (a debug value you should adjust that to your needs) which seems to be enough for our usecase (no error reported since i made the adjustment) be aware that this increases nginxs ram usage and your system needs to be ready for this.
> > i also adjusted keepalive timeout in nginx to 600 (10 minutes) from 1 minute. Maybe something for the nginx default config
> > http {
> > ```
> >     ##
> >     # Basic Settings
> >     ##
> > 
> >     sendfile on;
> >     tcp_nopush on;
> >     types_hash_max_size 2048;
> >     # server_tokens off;
> >     client_max_body_size 512G;
> >     # server_names_hash_bucket_size 64;
> >     # server_name_in_redirect off;
> >     keepalive_requests 99999;
> >     keepalive_timeout 600;
> >     include /etc/nginx/mime.types;
> >     default_type application/octet-stream;
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > So it appears that the client needs a limit to the connections it tries to create and/or not bug out when a connection is refused and just use the ones it got.
> 
> Works for me, for a new installation I pass keepalive_requests from 100 to 1000 and keepalive_timeout from 15 to 60

Thanks - this was also mentioned above as a potential solution.  However it was voted down.  I'm not sure why?

**Comment by jamesstanw** [comment] 2024-09-22 04:25
> > How can I downgrade the client on linux with no GUI? Seems apt only has the current version and 3.11
> 
> @charliehoward you could use the appimage package from here https://github.com/nextcloud-releases/desktop/releases/tag/v3.13.3 depending on the distro you could also download an older version directly from a mirror and do an apt-pinning.

This is what I did for the Windows older version.  All working again.  However, it starts with a nag to upgrade - so avoid that!

**Comment by charliehoward** [comment] 2024-09-22 11:55
> > > For people who run an nginx server this can be fixed serverside:
> > > raising the value of keepalive_requests should help with this. default value is 1000 i raised it to 99999 (a debug value you should adjust that to your needs) which seems to be enough for our usecase (no error reported since i made the adjustment) be aware that this increases nginxs ram usage and your system needs to be ready for this.
> > > i also adjusted keepalive timeout in nginx to 600 (10 minutes) from 1 minute. Maybe something for the nginx default config
> > > http {
> > > ```
> > >     ##
> > >     # Basic Settings
> > >     ##
> > > 
> > >     sendfile on;
> > >     tcp_nopush on;
> > >     types_hash_max_size 2048;
> > >     # server_tokens off;
> > >     client_max_body_size 512G;
> > >     # server_names_hash_bucket_size 64;
> > >     # server_name_in_redirect off;
> > >     keepalive_requests 99999;
> > >     keepalive_timeout 600;
> > >     include /etc/nginx/mime.types;
> > >     default_type application/octet-stream;
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > So it appears that the client needs a limit to the connections it tries to create and/or not bug out when a connection is refused and just use the ones it got.
> > 
> > 
> > Works for me, for a new installation I pass keepalive_requests from 100 to 1000 and keepalive_timeout from 15 to 60
> 
> Thanks - this was also mentioned above as a potential solution. However it was voted down. I'm not sure why?

Because it's not a fix that works for everyone, if you don't have access to the server then you can't do it

**Comment by paradonym** [comment] 2024-09-22 12:38
Is there any way to remove the default auto-recognized update to 3.14 in the 3.13.4 client version? 
I don't know if it auto-updates during usual PC reboots when the new version already shown in the settings screen. Despite having  the option to check for updates disabled

**Comment by Belledonne0** [comment] 2024-09-23 06:41
> Is there any way to remove the default auto-recognized update to 3.14 in the 3.13.4 client version? I don't know if it auto-updates during usual PC reboots when the new version already shown in the settings screen. Despite having the option to check for updates disabled

On windows i can disable on this version 3.13.4.
so which os ?

**Comment by SavasTheodoropoulos** [comment] 2024-09-23 09:33
I am having the same problem using Desktop Client 3.14.0 for Windows

**Comment by stefan2904** [comment] 2024-09-23 12:50
![image](https://github.com/user-attachments/assets/06a324d6-ceee-4dda-ac86-2aa5dfe40739)

apparently the 3.13 release is only uploaded for mantic

**Comment by charliehoward** [comment] 2024-09-23 12:58
Do you know of a way to do it via apt?
Or of course, someone at NC could have used the past week to actually fix it

**Comment by osiktech** [comment] 2024-09-23 13:13
for apt users, please have look here: https://askubuntu.com/questions/138284/how-to-downgrade-a-package-via-apt-get this might help you, with downgrading.

**Comment by charliehoward** [comment] 2024-09-23 13:15
> for apt users, please have look here: https://askubuntu.com/questions/138284/how-to-downgrade-a-package-via-apt-get this might help you, with downgrading.



> I ran apt list -a nextcloud-desktop but I only get two options - `nextcloud-desktop/noble,now 3.14.0-20240916.085658.d8fcb9273-1.0~noble1 amd64 [residual-config] nextcloud-desktop/noble 3.11.0-1.1build4 amd64 [residual-config]`
> 
> Unless you can suggest a source with older versions? Specifically 3.13.x

**Comment by stefan2904** [comment] 2024-09-23 13:16
> for apt users, please have look here: https://askubuntu.com/questions/138284/how-to-downgrade-a-package-via-apt-get this might help you, with downgrading.

@osiktech This does not help if no package version is available to downgrade to. ;-) 
See output of `sudo apt-cache policy nextcloud-desktop`

**Comment by charliehoward** [comment] 2024-09-23 14:01
Yep that does work
`sudo add-apt-repository ppa:xtradeb/apps
sudo apt update`

Then you have to specify the version you want
`sudo apt install nextcloud-desktop=3.13.4-1xtradeb1.2404.1`

I also had to install libnextcloudsync0, doc and cmd
`sudo apt install libnextcloudsync0=3.13.4-1xtradeb1.2404.1
sudo apt install nextcloud-desktop-doc=3.13.4-1xtradeb1.2404.1
nextcloud-desktop-cmd=3.13.4-1xtradeb1.2404.1`

**Closed** 2024-09-23 14:24 UTC
Labels: 1. to develop, approved

**Comment by charliehoward** [comment] 2024-09-23 14:27
I wouldn't say it's completed, this is a workaround, it still needs fixing lol

**Comment by nursoda** [comment] 2024-09-23 18:52
@xataz wrote:
> Works for me, for a new installation
> I pass keepalive_requests from 100 to 1000
> and keepalive_timeout from 15 to 60

That's strange since the [defaults](https://nginx.org/en/docs/http/ngx_http_core_module.html#keepalive_requests) are
> keepalive_requests 1000;
> keepalive_timeout 75s;

So, if you stuck to defaults, this should work. I use defaults, but it didn't wfm. I tried the [fixed AppImage](https://github.com/nextcloud/desktop/pull/7182#issuecomment-2367928105), and it no longer yielded the OP error, yet some [other strange behavior](https://github.com/nextcloud/desktop/pull/7182#issuecomment-2368867108).

**Comment by nursoda** [comment] 2024-09-23 19:30
I'm on arch and was struck by this issue using [repo package](https://archlinux.org/packages/extra/x86_64/nextcloud-client/) nextcloud-client `3.14.0-1`. So I temporarily downgraded all my machines to `3.13.4-1`. After confirming that the fixed AppImage works for me (see above), I tried the current repo version `3.14.0-5`. This also seems to work for me! Now I'm a bit baffled what the difference is. Probably a look on the [arch package mantainer's change log](https://gitlab.archlinux.org/archlinux/packaging/packages/nextcloud-client/-/commits/main) gives ideas to devs here?

**Comment by GerritLionMountain** [comment] 2024-09-24 07:46
I have the same problem, but i'm using a Mac

**Comment by egge96** [comment] 2024-09-24 09:59
Yes, I have the problem as well - also using a Mac - problem exists with MAC version of Nextcloud Client but also on Windows run in Parallels VM

**Comment by egge96** [comment] 2024-09-24 10:00
> Yes, I have the problem as well - also using a Mac - problem exists with MAC version of Nextcloud Client but also on Windows run in Parallels VM

My solution is currently a downgrade to 3.13.4

**Comment by GerritLionMountain** [comment] 2024-09-24 10:03
Is it possible to use an older version of the desktop client in the hope that it will then work?

**Comment by egge96** [comment] 2024-09-24 10:29
> Is it possible to use an older version of the desktop client in the hope that it will then work?

Yes, that seems to be the only solution at the moment.

**Comment by GerritLionMountain** [comment] 2024-09-24 11:24
> > Is it possible to use an older version of the desktop client in the hope that it will then work?
> 
> Yes, that seems to be the only solution at the moment.

okay, do you know where to get the earlier ones? I couldn't find anything on nextcloud itself from the earlier versions

**Comment by GerritLionMountain** [comment] 2024-09-24 12:53
> If you don't want to figure your package manager out on how to install the older version and stuff: Here ist the directory with all Nextcloud builds online: https://download.nextcloud.com/desktop/releases/
> 
> I just downloaded the Mac installer from there and when I know that this bug is fixed I will uninstall it and use Homebrew to get the latest version as usual. In theory I think you can do the same on other OSs.

okay i will try it also

**Comment by GerritLionMountain** [comment] 2024-09-25 06:34
> > okay, do you know where to get the earlier ones? I couldn't find anything on nextcloud itself from the earlier versions
> 
> If you don't want to figure your package manager out on how to install the older version and stuff: Here ist the directory with all Nextcloud builds online: https://download.nextcloud.com/desktop/releases/
> 
> I just downloaded the Mac installer from there and when I know that this bug is fixed I will uninstall it and use Homebrew to get the latest version as usual. In theory I think you can do the same on other OSs.

Which version worked for you? I have now downloaded several and it still does not synchronize

**Comment by brunobeeee** [comment] 2024-09-25 08:34
> Which version worked for you? I have now downloaded several and it still does not synchronize

Sorry to hear that. Version 3.13.4 works just fine for me and it seems to work for many others in this thread.

**Comment by vagner-dias** [comment] 2024-09-25 21:36
@mgallien  – It seems that a fix for this issue has already been merged. It might be a good idea to make a "beta 3.14.1" release available so that the people in this thread can test it before the production release?

**Comment by Bluejanis** [comment] 2024-09-26 05:54
@mgallien Could you please reopen this issue? It is still not working, using the latest version.

**Comment by Electrenator** [comment] 2024-09-26 07:40
> @xataz wrote:
> 
> > Works for me, for a new installation
> > I pass keepalive_requests from 100 to 1000
> > and keepalive_timeout from 15 to 60
> 
> That's strange since the [defaults](https://nginx.org/en/docs/http/ngx_http_core_module.html#keepalive_requests) are
> 
> > keepalive_requests 1000;
> > keepalive_timeout 75s;
> 
> So, if you stuck to defaults, this should work. I use defaults, but it didn't wfm.
> 
> I tried the [fixed AppImage](https://github.com/nextcloud/desktop/pull/7182#issuecomment-2367928105), and it no longer yielded the OP error, yet some [other strange behavior](https://github.com/nextcloud/desktop/pull/7182#issuecomment-2368867108).

May be related to #7171. Got the errors shown there when I increased the timeout values back to the defaults within my proxy, except when large client unknown folders are trying to be synced. Getting the error here again then with the

**Comment by tootbrute** [comment] 2024-09-29 13:33
This issue is closed but it seems many people still have this problem. Can we reopen the issue? I don't like messing around with nginx because I don't understand it that well.

I have this issue on one of my systems.

All my Bluefin (Silverblue spin) machines are all fine but my Bazzite machine has a problem syncing a large 11 GB folder that has many litle files in it.

```
$ flatpak list | grep nextcloud
Nextcloud Desktop	com.nextcloud.desktopclient.nextcloud	3.14.0	stable	system
```
```
$ rpm-ostree status
State: idle
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-gnome:stable
                   Digest: sha256:b72a876be97a559b1783cac2a708d0d488f50ca2bcbda37e0653dcc31ddb927b
                  Version: 40.20240922.0 (2024-09-23T05:00:35Z)
          LayeredPackages: ibus-chewing
            LocalPackages: lact-libadwaita-0.5.6-0.x86_64
```

It doesn't show the progress very well either.
![image](https://github.com/user-attachments/assets/b428e920-3ca6-4a9f-abfa-d8e5f53f1915)

Then it fails with the stream error that many others are experiencing.
![image](https://github.com/user-attachments/assets/e3b6644c-5c82-4045-b841-e83dfa6dc5a9)

**Comment by kmorber** [comment] 2024-09-29 14:09
solved with desktop client 3.14.1

**Comment by timirons** [comment] 2024-09-30 16:00
We are still having sync issues with 3.14.1 and Ionos hosting.

**Comment by albert-a** [comment] 2024-10-01 12:41
@DDQW wrote:
> For people who run an nginx server this can be fixed serverside:
>  ...
>     keepalive_requests 99999;
>     keepalive_timeout 600;
>  ...

Thanks for sharing! I'm running AIO behind Nginx reverse proxy (latest Debian 12 distro version) configured using official AIO manual: https://github.com/nextcloud/all-in-one/blob/main/reverse-proxy.md#nginx-freenginx-openresty
And this fixed it. Tested over the last 3 days on 3 different computers with version 3.14.0

@charliehoward wrote:
>> ...
>> Thanks - this was also mentioned above as a potential solution. However it was voted down. I'm not sure why?
>
> Because it's not a fix that works for everyone, if you don't have access to the server then you can't do it

Strange logic.... I read it like this: "If it does not help ME then I will downvote it without even commenting, I don't care if this can help others or developers"

**Comment by DDQW** [comment] 2024-10-01 14:18
glad it helped.

you certainly explained better what i wanted people to do. I was so free to add them to my post so it is a bit better to understand.

**Comment by albert-a** [comment] 2024-10-01 14:18
Glad it helped you!
I actually didn't changed anything in Nextcloud AIO instance itself. I only modified the config on the reverse proxy. I just added these two lines to the beginning of the  `server { ... }` block in /etc/nginx/sites-available/cloud.mydomain.tld which is proxy configuration for the Nextcloud AIO instance.
