### ISSUE TITLE
[Bug]: Nextcloud is changing all folders permission to full (777)

### ISSUE THREAD

**Issue by talesam** [nextcloud/desktop#6988] opened 2024-08-10 17:18 UTC
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

The share dialog is looking incomplete.
...
When I create a folder, if it is in Nextcloud synchronization it is changing the folders to full permission, 777. The problem is that I am synchronizing my /home and this has made a mess on my system.

### Steps to reproduce

1. Right click on the file
2. Click on Share Options
3. The share dialog does not display the option to share by e-mail
...
Create a folder using any file manager or in the terminal with mkdir, if nextcloud is syncing, it will automatically change the folder permission to 777

### Expected behavior

When clicking on the share dialog, share by e-mail should be an option.
...
Do not give full permissions to folders/directories

### Which files are affected by this bug

All

### Operating system

Linux

### Which version of the operating system you are running.

Biglinux

### Package

Distro package manager

### Nextcloud Server version

28.0.6

### Nextcloud Desktop Client version

3.13.2-1

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 3.4.2 to 3.4.4)

### Are you using the Nextcloud Server Encryption module?

Encryption is Enabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Additional info

**Debug file**
https://cloud.talesam.org/s/n8AfdcsqtjpNZmG

**Comment by joshtrichards** [comment] 2024-08-12 21:01
Duplicate of #6863

**Closed** 2024-08-12 21:01 UTC
Labels: 0. Needs triage, bug
