### ISSUE TITLE
Ubuntu 20.04, flatpak, Theme wants to show vfs mode, but no vfs plugins are available

### ISSUE THREAD

**Issue by dpalic** [nextcloud/desktop#5740] opened 2023-05-29 20:13 UTC
### Bug description

added in [General]
showExperimentalOptions=true

running it as flatpak
Nextcloud Desktop                                    com.nextcloud.desktopclient.nextcloud                            3.8.2                 stable

2023-05-29 21:49:27:007 [ warning nextcloud.gui.application /run/build/nextcloud-client/src/gui/application.cpp:364 ]:  Theme wants to show vfs mode, but no vfs plugins are available

I have no clue, what here needs to be done. Neither any google results helped nor trying to understand the code at the position.

What plugin is referred here?
What package is maybe missing to be installed, on flatpak or as debian package?
Anything else required to do?

Or simply is it a bug?

if I run it via AppImage the option
showExperimentalOptions=true
is working and syncing
BUT
I cannot use the .nextcloud files properly, nor could I find a way to link the .nextcloud files to run the nextcloud client. So switched to recommended flatpak installation.

So neither the one not the other way is working. What shall I do?

### Steps to reproduce

see previously

### Expected behavior

When clicking on the share dialog, share by e-mail should be an option.
...
after enabling either as AppImage or as Flatpak to be able to use the .nextcloud files like under windows
and to see the options virtual files on configuration (in Flatpak)

### Which files are affected by this bug

all, since virtual files not working

### Operating system

Linux

### Which version of the operating system you are running.

Ubuntu 20.04 x64

### Package

Other

### Nextcloud Server version

26.0.1

### Nextcloud Desktop Client version

3.8.2 (flatpak and AppImage)

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [X] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by joshtrichards** [comment] 2024-08-16 03:14
Duplicate of #3668

**Closed by joshtrichards** 2024-08-16 03:14 UTC
Labels: 0. Needs triage, os: :penguin: Linux, feature: :minidisc: virtual filesystem, package: flatpak
