### ISSUE TITLE
[Bug]: Sync panel sometimes shows negative size while uploading

### ISSUE THREAD

**Issue by anonbergine** [nextcloud/desktop#5519] opened 2023-03-12 07:21 UTC
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

Sometimes, while uploading, the filesize under the progress bar goes negative:

![Screenshot 2023-03-12 071644](https://user-images.githubusercontent.com/120770250/224530187-a99ca4d6-dbf7-413e-94d7-76553ba6b107.png)

### Steps to reproduce

It's intermittent. Just every so often the display shows negative bytes during a sync.

Notably, it's often on relatively small files so it's unlikely to be an `bigint` (I assume?) overflow.

### Expected behavior

File size should never be negative.

### Which files are affected by this bug

Random files.

### Operating system

Windows

### Which version of the operating system you are running.

windows-10.0.19045

### Package

Appimage

### Nextcloud Server version

Unknown but was updated by admin 2-3 days ago

### Nextcloud Desktop Client version

3.7.4 (Windows)

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 3.4.2 to 3.4.4)

### Are you using the Nextcloud Server Encryption module?

Encryption is Enabled

### Are you using an external user-backend?

- [X] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Nextcloud Server logs

```shell
Unable to obtain.
```

### Additional info

The bug is rare, and doesn't seem to cause any major problems.

I've noticed this bug for a while - it's cropped up several times over past 6 months. It's not caused due to a recent update, it seems to be a long-standing issue.

**Comment by LorbusChris** [comment] 2023-04-28 17:15
Also happening on Fedora (Version 3.7.4 (Fedora))

**Comment by allexzander** [comment] 2023-06-13 21:20
duplicate of https://github.com/nextcloud/desktop/issues/5519

**Comment by TobiGr** [comment] 2023-07-16 16:35
The bug is still present in Nextcloud client 3.9.0 (linux) with server 26. I encountered the bug after adding many files to one of the synced folders and starting Nextcloud client afterwards:
![nextcloud_client_sync_bug](https://github.com/nextcloud/desktop/assets/17365767/725713ba-4250-468e-b4b1-b71f14aac303)

**Comment by karthikiyengar** [comment] 2023-08-13 11:46
Still present, 26.0.3 + client version 3.9.2 on ubuntu, no encryption.

**Comment by zachsmith** [comment] 2023-09-06 23:47
I'm seeing this as well with Flatpak com.nextcloud.desktopclient.nextcloud version 3.9.3  on Debian 12.

**Comment by lorenzohess** [comment] 2023-09-13 02:31
Still present:
```bash
$ Nextcloud-3.9.4-x86_64.AppImage --version
Nextcloud version 3.9.4 (build 17551)
Git revision c8fec0118f90f6297a7af1fec4f7b44f3e6b3821
Using Qt 5.15.10, built against Qt 5.15.10
Using Qt platform plugin 'xcb'
Using 'OpenSSL 3.0.10 1 Aug 2023'
Running on Debian GNU/Linux 11 (bullseye), x86_64
```

**Comment by msviba** [comment] 2023-09-23 08:26
Same experience with Version 3.10.0stable-Win64 (build 20230915)

**Comment by Krinkle** [comment] 2023-10-02 02:42
I used Nextcloud Desktop for the first time today and upon replacing a few files, I noticed this issue.

Client Version 3.10.0 (`osx-22.5.0`).

<img height="160" src="https://github.com/nextcloud/desktop/assets/156867/cfb20247-260b-468d-b93f-fb697e68c2ae">
<img height="150" src="https://github.com/nextcloud/desktop/assets/156867/f3bb6af1-0695-46ad-aed5-e1ac32c366f7">

**Comment by nickdavies92** [comment] 2023-10-02 17:24
I'm running the latest version and have the same issue. Everytime I try and sync a new folder, it will get majority of the way through and then keep looping as others have described above (negative b number > 0b, cycles 100 files at a time, repeats this until the max number of files in the folder has been reached, and then starts again). Restarting both the nextcloud host and nextcloud client doesn't help. 

I'm going to try the Nextcloudpi image but in the past I've not had any issues running it on Buster and installing manually. 
I used this guide: https://pimylifeup.com/raspberry-pi-nextcloud-server/

In this current state, nextcloud is unusable.

NextCloud Desktop Client 3.4.1
Windows-10.0.19045

**Comment by mgallien** [comment] 2023-10-03 06:43
@nickdavies92 I recommend that you upgrade to our latest release and test again. We no longer fix bug i the 3.4 release series. In this stable branch 3.4.1 is also not the latest release and we would not backport a fix to this old version (like doing a `3.4.1.1` release)

**Comment by Morpheu5** [comment] 2023-10-07 17:30
Can confirm the bug is present on macOS, latest clients and servers, but for me this is also part of a larger problem, as reported in https://github.com/nextcloud/desktop/issues/6117

**Comment by ax1036** [comment] 2023-10-10 19:31
Same for with latest versions. Client use 100% for one CPU and gui freeze.
Upload with web interface work fine. and client download file without issue.

Client version:
Nextcloud version 3.10.0 (build 17672)
Git revision ad2cf1b575e45c2adb2832f6b8642bb9f79d105b
Using Qt 5.15.10, built against Qt 5.15.10
Using Qt platform plugin 'xcb'
Using 'OpenSSL 3.0.10 1 Aug 2023'
Running on Debian GNU/Linux 12 (bookworm), x86_64

Server Version: 27.1.2 / debian 12

**Comment by ax1036** [comment] 2023-10-11 20:01
More infos:
with `head -c 2M /dev/urandom > 2m.file` on my server, negative size and client freeze/crash.

but with same client 3.10.0 same generated file on [drive.shadow.tech](https://drive.shadow.tech/) will work fine (positive size & upload done)
current server version « Nextcloud 26.0.4.3 » (from [scan.nextcloud.com](https://scan.nextcloud.com/results/9a920130-30fb-4e15-97c8-84d8126cba81))

**Comment by Morpheu5** [comment] 2023-10-12 13:29
I haven't tried an earlier version of the server but I might, at this point. If that works, it means the negative size bug and the issue I'm experiencing with the client not syncing correctly at all may be somewhere in between the client and the latest version of the server.

**Comment by Morpheu5** [comment] 2023-10-13 09:58
I tried installing version 26 of the server and I still get the negative size bug, but at least I'm able to sync again (see #6117 )

**Comment by ax1036** [comment] 2023-11-18 15:54
Some new tests with "my server" and "drive.shadow.tech" with proxying it.
Server with negative use this endpoint: "POST /remote.php/dav/bulk HTTP/1.1"
Server working fine use this one: "PUT /remote.php/dav/files/<username>/2M.file"

Question is why are differents ?

**Comment by allexzander** [comment] 2023-11-27 14:51
Fixed in https://github.com/nextcloud/desktop/pull/6227

**Closed by allexzander** 2023-11-27 14:51 UTC
Labels: 1. to develop, bug
