### ISSUE TITLE
[Bug]: MIssing function to delete account in PPA-version

### ISSUE THREAD

**Issue by scroom** [nextcloud/desktop#5593] opened 2023-04-11 16:41 UTC
- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

As described above. In the PPA-Version there is no function to delete an account which leads to problems when you can no longer use an account.
...

### Steps to reproduce

1.There are no steps
...

### Expected behavior

There should be a way to delete an account from the list.
...

### Which files are affected by this bug

all files

### Operating system

Linux

### Which version of the operating system you are running.

Ubuntu 22.10

### Package

Other

### Nextcloud Server version

24.0.11

### Nextcloud Desktop Client version

3.8.0

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 3.4.2 to 3.4.4)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [X] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by joshtrichards** [comment] 2023-11-26 17:09
Sounds like something to bring up with the PPA maintainers unless you can reproduce this in the AppImage distributed from here.

That's weird though. Is the `...` menu for an existing account missing entirely?

**Comment by joshtrichards** [comment] 2024-08-16 05:24
Closing after >9 months without requested follow-up info. Cannot reproduce in official packages and presuming fixed.

**Closed by joshtrichards** 2024-08-16 05:24 UTC
Labels: 0. Needs triage, bug, feature: :key: authentication, package: PPA
