### ISSUE TITLE
Missing account button in 3.0.2 - no way to add a new account (void linux and Windows 10)

### ISSUE THREAD

**Issue by adymorz** [nextcloud/desktop#2608] opened 2020-10-31 09:55 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour
According to the [documentation](https://docs.nextcloud.com/desktop/3.0/navigating.html#systray-icon) there should by a button "Account" in the sync client, which can be used to add a new account.

### Actual behaviour
On the linux void version and the Windows version the button "Account" is missing. On Windows 10, I was able to add an account over the context menu of the systray icon, but on linux void, there is no context menu visible on the systray icon.

Screenshot from void linux:
![image](https://user-images.githubusercontent.com/1993680/97776326-68dfa200-1b67-11eb-9187-86bd3a83190b.png)

### Steps to reproduce
1. Open the settings window
2. Click on the first account
3. Search for the button "Account"

### Client configuration
Client version:
3.0.2

Operating system:
Windows 10, Void Linux

OS language:
Windows 10: EN
Void Linux: DE

Qt version used by client package (Linux only, see also Settings dialog):
Qt 5.15.1

Client package (From Nextcloud or distro) (Linux only):
https://github.com/void-linux/void-packages/tree/master/srcpkgs/nextcloud-client

Installation path of client:

### Server configuration
Not relevant for this issue.

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile: 
Output of `nextcloud --logdebug --logwindow` or `nextcloud --logdebug --logfile log.txt`
I created the log file, but it contains to much information I do not want to share.

2. Web server error log:
Not relevant

3. Server logfile: nextcloud log (data/nextcloud.log):
Not relevant

**Comment by ifrh** [comment] 2020-11-01 21:57
If you open the main Window from task symbol context menue, than you can add an account
![NextCloud_AddAccounts](https://user-images.githubusercontent.com/3845055/97816427-65e2cf80-1c95-11eb-8d69-e9cdda5578b6.png)

**Comment by er-vin** [comment] 2020-11-02 08:32
Duplicate of #2334

**Closed by er-vin** 2020-11-02 08:32 UTC
