### ISSUE TITLE
Font Size too small

### ISSUE THREAD

**Issue by hr1232** [nextcloud/desktop#5691] opened 2023-05-14 16:36 UTC
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

This might be just cosmetic, but it's still quite annoying. About 2 or 3 automatic updates ago, font size in the Windows app was reduced to a tiny value that is just crazy.

![nextcloud](https://github.com/nextcloud/desktop/assets/24797275/684c58cf-77f4-408b-bd42-803982d8e591)

Also the status window was reduzed in size in such an extent, that text overlaps and the window is completely useless. Why isn't there an option to resize it?

![nextcloud2](https://github.com/nextcloud/desktop/assets/24797275/e8bf2feb-d321-43ba-8b02-65694fb82944)

### Expected behavior

Maybe you could make font sizes even smaller, so People would definitely need a microscope to read the text...

### Which files are affected by this bug

none

### Operating system

Windows

### Which version of the operating system you are running.

Windows 11 Pro 22H2

### Package

Distro package manager

### Nextcloud Server version

26.0.1

### Nextcloud Desktop Client version

Unkown, I don't have a microscope ready to read the dialog, Please use your own to look at my screenshot

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 3.4.2 to 3.4.4)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Nextcloud Server logs

```shell
not relevant, client GUI error
```

### Additional info

-

**Comment by joshtrichards** [comment] 2024-08-15 15:02
Duplicate of #5207 & #5373

**Closed by joshtrichards** 2024-08-15 15:02 UTC
Labels: 0. Needs triage, os: :door: Windows, feature: :gear: settings, feature: :cloud: system tray
