### ISSUE TITLE
Nextcloud 3.2.0 Explorer Navigation Pane Missing after enabling virtual file support 

### ISSUE THREAD

**Issue by andyxheli** [nextcloud/desktop#3113] opened 2021-04-13 17:21 UTC
Hello the Explorer Navigation Pane is check in the settings I even unchecked and rechecked it still nothing. It dose work if you have virtual file support off as soon as you enable virtual file support it disappears. 

![image](https://user-images.githubusercontent.com/59488153/114594282-b43bc780-9c52-11eb-8fbc-8da6c9627c5e.png)

![image](https://user-images.githubusercontent.com/59488153/114594252-ab4af600-9c52-11eb-81fd-d454f3a2971a.png)

**Comment by axheli** [comment] 2021-04-13 18:24
@FlexW What do you think about this?

**Comment by FlexW** [comment] 2021-04-14 07:56
I can confirm the issue partially. On my instance it was the opposite: If I changed from non-vfs to vfs the entry was gone. This needs some more research but there is something off.

**Comment by andyxheli** [comment] 2021-04-14 14:20
If you need anything let me know happy to test.

**Comment by stavros-k** [comment] 2021-04-14 16:07
Btw, if you have multiple accounts, it only disappears for the specific account you enable VFS.

**Comment by Numrollen** [comment] 2021-04-15 11:56
same here. even when i roll back to "normal filesystem" it doesnt show up anymore.

**Comment by mayank1470** [comment] 2021-04-15 12:47
Same here, I did a clean installation of the software and since then no account is displayed in the navigation pane of the windows explorer. I have one on local LAN and one is on a server, just if it helps someone debug.

**Comment by timo-ecm2** [comment] 2021-04-15 13:31
I have something similar. If I open an ad random folder in W10 and check the Explorer Navigation Pane, I can't see the NextCloud icon for an account. See the left part of the screenshot below. When I click first on the System tray, then on the Green Next Cloud Icon and after that in the Nextcloud pop-up on the Next cloud-folder Icon, I can see the Blue NextCloud Icon in the Explorer Navigation Pane. That's the right part of the screenshot.

![Naamloos](https://user-images.githubusercontent.com/51777898/114877230-60baac80-9dff-11eb-90ac-2d9ab4b477d7.png)

**Comment by allexzander** [comment] 2021-04-15 13:33
This will get fixed in 3.2.1

**Closed** 2021-04-16 07:43 UTC
Labels: approved, bug, feature: :arrows_counterclockwise: sync engine, feature: :minidisc: virtual filesystem

**Comment by SupaYoshi** [comment] 2021-04-17 15:06
> 
> 
> This will get fixed in 3.2.1

Thank you, very helpful because I'm missing it!
