### ISSUE TITLE
folders incorrectly created at top-level

### ISSUE THREAD

**Issue by JuangDse** [nextcloud/desktop#233] opened 2018-03-27 18:31 UTC
Suppose you do:

on the server:
1. create a folder srvfoo

on the client:
1. create folders foo and foo/subfoo
2. start nextcloud-client from scratch
3. configure it to sync srvfoo with foo

result after syncing:
on the server:
a folder subfoo is created at top-level
on the client:
subfoo os populated with all top-level _files_ from the server.

expected result:
subfoo is created as a subfolder of srvfoo

----
server: Nextcloud 13.0.0
client: nextcloud-client 2.3.3-1 (Arch Linux)

**Comment by camilasan** [comment] 2018-04-16 15:49
With my my nc server 13, opensuse nc client 2.3.3:
- tried with my current folders syncing.
- tried with a clean setup, from scratch. 
- tried to pick the folder to sync on set up 
- tried to skip configuration and added folder later. 

It all worked as expected. Can you repeat it?

**Comment by JuangDse** [comment] 2018-04-16 19:18
hmm.. I just repeated all steps with an all-new server (13.0.1) and client (2.3.3.1) setup. All things turned out exactly as I had originally reported.

- did you start with an all-new server and client instance?
- in the client setup, did you
  - define subfoo as a subfolder of foo (locally)?
  - pick "choose what to sync"?

The error I see is very likely related to the fact that after setup, "Add folder sync connection" is grayed in the client, mentioning that I am already syncing all my files - this despite me having unchecked "Sync everything from server" and checking "choose what to sync".

Thanks for checking!

**Comment by DominiqueFuchs** [comment] 2019-09-25 17:28
Hey @JuangDse , thanks for reaching out here! It's been quite some time, the client (and server) code has gone through significant changes and improvements. Does the issue still persist for you (are you still there? 😄 )? I was not able to reproduce this with the latest stable client (2.5.3 and a NC 15 instance).

**Comment by JuangDse** [comment] 2019-09-26 08:26
except for one change, everything is still as reported. That is,

on the server, the folder subfoo is created
on the client, the folder foo is populated with all **files** of the server. Before, the folder subfoo had been populated that way.

It is important to select "choose what to sync" in the beginning.
Still very confusing!

**Comment by mgallien** [comment] 2021-05-05 07:51
I cannot reproduce. The issue is old. I am closing it.

**Closed by mgallien** 2021-05-05 07:51 UTC
Labels: bug

**Comment by JuangDse** [comment] 2021-05-18 15:58
The issue is still there.

In the current version (3.2.0) it occurs when **syncing manually**. That is, at the start, skip folder configuration, then sync manually and proceed as described.
