### ISSUE TITLE
Folders with trailing space seems to be invisible for the desktop client

### ISSUE THREAD

**Issue by dartcafe** [nextcloud/desktop#2651] opened 2020-11-19 13:34 UTC
### Expected behaviour
All subfolders of a groupfolder should be syncronisable

### Actual behaviour
* I have a subfolder with a trailing space in a groupfolder 
* The list with folders from the server does not contain these folders (they are somehow missing in the settings)
* Renaming the folder via the web frontend (removed the trailing space) solved the problem; subfolder is visible and synchronisation can be activated. 
* No errors before and after renaming

Client version:
3.0.3

Operating system:
Windows

OS language:
German

Installation path of client:
Programs folder

### Server configuration

Nextcloud version:
19.0.3

Group folders version: 
7.1.1

Storage backend (external storage):
local filesystem

### Logs
I assume not necessary

**Comment by deajan** [comment] 2020-11-19 14:56
I second this error report.
I have made a couple of tests for this error, and found out the following:

When having subfolder names like "SOME FOLDER " (notice the trailing slash) in a group folder, they appear correct in the Nextcloud web interface (trying to rename them shows the ending slash), but will not appear in the syncable folder list of a windows client.

Only the windows client seems affected.
The MacOS client syncs files with trailing space characters without any problems.

I've checked Nextcloud clients 3.0.0 > 3.0.3 (and Owncloud client 2.6.5), they all seem affected on Windows.

Please find below an example of subfolders, where the folder '04' and '06' are missing in the client due to them finishing with a trailing space:

![image](https://user-images.githubusercontent.com/4681318/99682631-b91f9500-2a7f-11eb-98c4-aae31ba9a95b.png)
![image](https://user-images.githubusercontent.com/4681318/99682653-c2106680-2a7f-11eb-856c-8c28f23fd076.png)
![image](https://user-images.githubusercontent.com/4681318/99682642-bd4bb280-2a7f-11eb-94ea-10b0b42a63f7.png)



Environment:
Server: CentOS 8.2 x64, PHP 7.4.11
Nextcloud verison: 19.0.4, and 19.0.5
Group folders version: 7.1.0 and 7.1.1
Client: OS Win 10 x64 2004, Clients 3.0.0, 3.0.1, 3.0.2 and 3.0.3

**Comment by deajan** [comment] 2020-11-25 09:07
Could one of the team members tell us if this issue should be reported for the client or for group folders module ?

**Comment by er-vin** [comment] 2020-11-25 12:52
I suspect this is client side. Also IIRC Windows doesn't like file names (or folder names) ending with a space, so even if that'd appear you'd have other issues down the line I think.

**Comment by k9t9** [comment] 2021-01-05 03:57
Reported a similar problem ( trailing DOT - e.g. "`.` " a bout a year ago ..
https://github.com/nextcloud/server/issues/18066

**Comment by er-vin** [comment] 2021-01-05 08:14
Duplicate of #707

**Closed by er-vin** 2021-01-05 08:14 UTC
Labels: bug, feature: :gear: settings
