### ISSUE TITLE
Linux client setup stops with internal server error

### ISSUE THREAD

**Issue by shoodle** [nextcloud/desktop#985] opened 2018-12-30 14:57 UTC
### Expected behaviour
Setup of nextcloud-client is successful.

### Actual behaviour
After installation of the latest version of nextcloud-client under Ubuntu I tried to connect to my own Nextcloud server. After login with my user into the server the setup process stops with the message "Weiterleitung" and nothing happens further.

Going back and trying again ends up with this message:

```
Interner Serverfehler

Der Server konnte die Anfrage nicht fertig stellen.
Sollte dies erneut auftreten, senden Sie bitte die nachfolgenden technischen Einzelheiten an Ihren Server-Administrator.
Weitere Details können im Server-Protokoll gefunden werden.
Technische Details

Entfernte Adresse: 192.168.14.11
Anfragekennung: pdC9Ts4yYsSY8SG6vFNx
```

### Client configuration
Client version: nextcloud-client/bionic,now 2.5.1-20181204.111806~bionic1 amd64

Operating system: Ubuntu

OS language: German

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From Nextcloud or distro) (Linux only):

Installation path of client: /usr/bin/nextcloud

### Server configuration

Operating system: Debiian

Web server: Apache2

Database: mysql

PHP version: 7.0.30-0+deb9u1

Nextcloud version: 14.0.4

Storage backend (external storage):

### Logs

1. Client logfile: Output of `nextcloud --logwindow` or `nextcloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the Nextcloud directory)
(See also https://docs.nextcloud.com/desktop/2.3/troubleshooting.html#log-files)

2. Web server error log:

3. Server logfile: nextcloud log (data/nextcloud.log):

nextcloud.log:

```
{"reqId":"pdC9Ts4yYsSY8SG6vFNx","level":3,"time":"2018-12-30T12:58:59+00:00","remoteAddr":"192.168.14.11","user":"--","app":"index","method":"GET","url":"\/nextcloud\/\/index.php\/login\/flow","message":{"Exception":"Exception","Message":"The requested uri(\/nextcloud\/index.php\/login\/flow) cannot be processed by the script '\/nextcloud\/\/index.php')","Code":0,"Trace":[{"file":"\/var\/www\/nextcloud\/lib\/base.php","line":930,"function":"getRawPathInfo","class":"OC\\AppFramework\\Http\\Request","type":"->","args":[]},{"file":"\/var\/www\/nextcloud\/index.php","line":42,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"\/var\/www\/nextcloud\/lib\/private\/AppFramework\/Http\/Request.php","Line":742,"CustomMessage":"--"},"userAgent":"Mozilla\/5.0 (Linux) mirall\/2.5.1git (Nextcloud)","version":"14.0.4.2"}
nextcloud.log:{"reqId":"pdC9Ts4yYsSY8SG6vFNx","level":0,"time":"2018-12-30T12:58:59+00:00","remoteAddr":"192.168.14.11","user":"--","app":"core","method":"GET","url":"\/nextcloud\/\/index.php\/login\/flow","message":"Scss is disabled for \/var\/www\/nextcloud\/core\/css\/jquery-ui-fixes.scss, ignoring","userAgent":"Mozilla\/5.0 (Linux) mirall\/2.5.1git (Nextcloud)","version":"14.0.4.2"}
nextcloud.log:{"reqId":"pdC9Ts4yYsSY8SG6vFNx","level":0,"time":"2018-12-30T12:58:59+00:00","remoteAddr":"192.168.14.11","user":"--","app":"core","method":"GET","url":"\/nextcloud\/\/index.php\/login\/flow","message":"Scss is disabled for \/var\/www\/nextcloud\/core\/css\/server.scss, ignoring","userAgent":"Mozilla\/5.0 (Linux) mirall\/2.5.1git (Nextcloud)","version":"14.0.4.2"}
nextcloud.log:{"reqId":"pdC9Ts4yYsSY8SG6vFNx","level":0,"time":"2018-12-30T12:58:59+00:00","remoteAddr":"192.168.14.11","user":"--","app":"core","method":"GET","url":"\/nextcloud\/\/index.php\/login\/flow","message":"Scss is disabled for \/var\/www\/nextcloud\/core\/css\/css-variables.scss, ignoring","userAgent":"Mozilla\/5.0 (Linux) mirall\/2.5.1git (Nextcloud)","version":"14.0.4.2"}
nextcloud.log:{"reqId":"pdC9Ts4yYsSY8SG6vFNx","level":0,"time":"2018-12-30T12:58:59+00:00","remoteAddr":"192.168.14.11","user":"--","app":"core","method":"GET","url":"\/nextcloud\/\/index.php\/login\/flow","message":"Scss is disabled for \/var\/www\/nextcloud\/core\/css\/jquery.ocdialog.scss, ignoring","userAgent":"Mozilla\/5.0 (Linux) mirall\/2.5.1git (Nextcloud)","version":"14.0.4.2"}
nextcloud.log:{"reqId":"pdC9Ts4yYsSY8SG6vFNx","level":0,"time":"2018-12-30T12:58:59+00:00","remoteAddr":"192.168.14.11","user":"--","app":"core","method":"GET","url":"\/nextcloud\/\/index.php\/login\/flow","message":"Scss is disabled for \/var\/www\/nextcloud\/core\/search\/css\/results.scss, ignoring","userAgent":"Mozilla\/5.0 (Linux) mirall\/2.5.1git (Nextcloud)","version":"14.0.4.2"}
nextcloud.log:{"reqId":"pdC9Ts4yYsSY8SG6vFNx","level":0,"time":"2018-12-30T12:58:59+00:00","remoteAddr":"192.168.14.11","user":"--","app":"core","method":"GET","url":"\/nextcloud\/\/index.php\/login\/flow","message":"Scss is disabled for \/var\/www\/nextcloud\/core\/css\/styles.scss, ignoring","userAgent":"Mozilla\/5.0 (Linux) mirall\/2.5.1git (Nextcloud)","version":"14.0.4.2"}
nextcloud.log:{"reqId":"pdC9Ts4yYsSY8SG6vFNx","level":0,"time":"2018-12-30T12:58:59+00:00","remoteAddr":"192.168.14.11","user":"--","app":"core","method":"GET","url":"\/nextcloud\/\/index.php\/login\/flow","message":"Scss is disabled for \/var\/www\/nextcloud\/core\/css\/header.scss, ignoring","userAgent":"Mozilla\/5.0 (Linux) mirall\/2.5.1git (Nextcloud)","version":"14.0.4.2"}
nextcloud.log:{"reqId":"pdC9Ts4yYsSY8SG6vFNx","level":3,"time":"2018-12-30T12:58:59+00:00","remoteAddr":"192.168.14.11","user":"--","app":"no app in context","method":"GET","url":"\/nextcloud\/\/index.php\/login\/flow","message":{"Exception":"Symfony\\Component\\Routing\\Exception\\RouteNotFoundException","Message":"Unable to generate a URL for the named route \"theming.Theming.getImage\" as such route does not exist.","Code":0,"Trace":[{"file":"\/var\/www\/nextcloud\/lib\/private\/Route\/Router.php","line":337,"function":"generate","class":"Symfony\\Component\\Routing\\Generator\\UrlGenerator","type":"->","args":["theming.Theming.getImage",{"key":"logo","useSvg":true,"v":"23"},1]},{"file":"\/var\/www\/nextcloud\/lib\/private\/Route\/CachingRouter.php","line":60,"function":"generate","class":"OC\\Route\\Router","type":"->","args":["theming.Theming.getImage",{"key":"logo","useSvg":true,"v":"23"},false]},{"file":"\/var\/www\/nextcloud\/lib\/private\/URLGenerator.php","line":79,"function":"generate","class":"OC\\Route\\CachingRouter","type":"->","args":["theming.Theming.getImage",{"key":"logo","useSvg":true,"v":"23"}]},{"file":"\/var\/www\/nextcloud\/apps\/theming\/lib\/ThemingDefaults.php","line":227,"function":"linkToRoute","class":"OC\\URLGenerator","type":"->","args":["theming.Theming.getImage",{"key":"logo","useSvg":true,"v":"23"}]},{"file":"\/var\/www\/nextcloud\/lib\/public\/Defaults.php","line":187,"function":"getLogo","class":"OCA\\Theming\\ThemingDefaults","type":"->","args":[true]},{"file":"\/var\/www\/nextcloud\/core\/templates\/layout.guest.php","line":34,"function":"getLogo","class":"OCP\\Defaults","type":"->","args":[]},{"file":"\/var\/www\/nextcloud\/lib\/private\/Template\/Base.php","line":179,"args":["\/var\/www\/nextcloud\/core\/templates\/layout.guest.php"],"function":"include"},{"file":"\/var\/www\/nextcloud\/lib\/private\/Template\/Base.php","line":151,"function":"load","class":"OC\\Template\\Base","type":"->","args":["\/var\/www\/nextcloud\/core\/templates\/layout.guest.php",null]},{"file":"\/var\/www\/nextcloud\/lib\/private\/legacy\/template.php","line":207,"function":"fetchPage","class":"OC\\Template\\Base","type":"->","args":[null]},{"file":"\/var\/www\/nextcloud\/lib\/private\/legacy\/template.php","line":238,"function":"fetchPage","class":"OC_Template","type":"->","args":[null]},{"file":"\/var\/www\/nextcloud\/lib\/private\/Template\/Base.php","line":132,"function":"fetchPage","class":"OC_Template","type":"->","args":[]},{"file":"\/var\/www\/nextcloud\/lib\/private\/legacy\/template.php","line":359,"function":"printPage","class":"OC\\Template\\Base","type":"->","args":[]},{"file":"\/var\/www\/nextcloud\/index.php","line":69,"function":"printExceptionErrorPage","class":"OC_Template","type":"::","args":[{"__class__":"Exception"},500]}],"File":"\/var\/www\/nextcloud\/3rdparty\/symfony\/routing\/Generator\/UrlGenerator.php","Line":113,"CustomMessage":"--"},"userAgent":"Mozilla\/5.0 (Linux) mirall\/2.5.1git (Nextcloud)","version":"14.0.4.2"}
```

**Comment by javierllorente** [comment] 2019-01-10 22:55
It looks like a duplicate of #718 to me.
Have you tried entering your Nextcloud URL without the trailing slash on the desktop client?

**Comment by adbeels** [comment] 2019-01-14 21:04
thanks @javierllorente  that worked for me.

**Comment by javierllorente** [comment] 2019-01-14 22:00
You're welcome!

**Comment by javierllorente** [comment] 2019-01-14 22:01
Duplicate of #718

**Closed by javierllorente** 2019-01-14 22:01 UTC
