### ISSUE TITLE
2.7.0 beta: forgets all folder synchronisation status

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/desktop#1750] opened 2020-01-22 06:32 UTC
- use 2.6.x
- have some folders not scheduled for sync
- upgrade to 2.7.0 beta
- see that client wants to sync everything
- verify that all folders are scheduled for sync

**Comment by doits** [comment] 2020-01-26 19:22
Looks like it downloads everything again, too, even if files are present/unchanged.

**Comment by mr-manuel** [comment] 2020-02-02 14:57
After upgrading from 2.6.2 to Version 2.7.0beta1-Win64 (build 20200119) I had to quit and start Nextcloud Desktop app 7 times to be able to display all synced folders (7 folders). After every restart of the Nextcloud Desktop app one more folder appeared.

In my case a resync of all files did not happen.

Additionally the right click on the tray icon doesn't work anymore.

**Comment by thejulian** [comment] 2020-09-28 21:18
Faced this issue today on one of our employees. Updated from 2.x.x to 3.0.2. 
Is there a solution to this? Or a file someone can backup on daily basis which contains sync-information?

**Comment by er-vin** [comment] 2020-09-29 08:37
Looks like an older duplicate of #2279

@thejulian I will close this one (and #2279) is closed as well because we did a fix for it. What concerns me is that said fix made it for 3.0.2 and was reported to work, I wonder if you hit something different. Might be worth making a new full fledged report with as many details as possible... I understand it's harder to upgrade time events though.

**Closed by er-vin** 2020-09-29 08:37 UTC
Labels: bug, feature: :arrows_counterclockwise: sync engine, high, regression
