### ISSUE TITLE
[Bug]: undefined symbol: _ZNK3OCC5Theme23multipleOverrideServersEv

### ISSUE THREAD

**Issue by stevefalco** [nextcloud/desktop#7230] opened 2024-09-27 15:29 UTC
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

I tried updating to desktop-3.14.1 on a Fedora 40 Linux system.  The code builds but when I try to run it I get:

`/usr/bin/nextcloud: symbol lookup error: /usr/bin/nextcloud: undefined symbol: _ZNK3OCC5Theme23multipleOverrideServersEv`

The previous version, desktop-3.14.0, works fine, so this is a regression.

### Steps to reproduce

1) Build desktop-3.14.1 on a Fedora 40 system
2) Try to run it, and you will get the above error message

### Expected behavior

It should run properly.

### Which files are affected by this bug

N/A

### Operating system

Linux

### Which version of the operating system you are running.

Fedora 40, XFCE, X11

### Package

Compiled it myself

### Nextcloud Server version

30.0.0

### Nextcloud Desktop Client version

3.14.1

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [X] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Nextcloud Server logs

```shell
The client doesn't run, so nothing is logged...
```

**Comment by mgallien** [comment] 2024-09-28 12:05
@stevefalco I am closing this as this is not a bug.
You are very much welcome to self build the desktop client on your own. I encourage you to keep doing that
If you have issues doing so, I suggest reaching out for help via https://help.nextcloud.com/ forum or via the Desktop client community Talk room https://cloud.nextcloud.com/call/d8k2r6p6

**Closed by mgallien** 2024-09-28 12:05 UTC
Labels: 0. Needs triage
