### ISSUE TITLE
3.14RC1 Mac OS: sync icons not showing

### ISSUE THREAD

**Issue by jospoortvliet** [nextcloud/desktop#7056] opened 2024-08-29 14:06 UTC
Hi team,

Mac OS: 3.14Rc1 is often not showing icons and share menu in synced folders (while the sync process seems to proceed as usual). Seems to happen pretty reliably after sleep of laptop.

debug archive (internal link): https://cloud.nextcloud.com/index.php/f/10268210

**Comment by claucambra** [comment] 2024-10-29 05:57
Duplicate of #5193 so closing, but thanks for the debug archive :)

**Closed by claucambra** 2024-10-29 05:57 UTC
Labels: bug, stable-3.14
