### ISSUE TITLE
Nextcloud client 3.4.0 - Invalid date

### ISSUE THREAD

**Issue by ehribeiro** [nextcloud/desktop#4035] opened 2021-12-03 12:10 UTC
After run automatic upgrade client to 3.4.0 version, we noticed a lot of re-synchronization files of many users, and it was found a issue in many files dates where even windows explorer or web interface have not identified those correct date of creation / modification with "Invalid Date" . Link of issues screenshots:
![Screenshot_1](https://user-images.githubusercontent.com/95479006/144600389-57ab245f-1296-4d24-96e6-dc636d393910.jpg)

![Screenshot_2](https://user-images.githubusercontent.com/95479006/144600400-ecbbb4ed-6fb8-4676-ba03-ff7642cb8b14.jpg)
![Screenshot_3](https://user-images.githubusercontent.com/95479006/144600408-e53e87f8-5a21-4c55-b8b8-cd8572416512.jpg)

**Comment by eibex** [comment] 2021-12-03 12:21
#4016

**Comment by biva** [comment] 2021-12-03 13:37
Could it be related to https://github.com/nextcloud/desktop/issues/4029 ?

**Comment by Githopp192** [comment] 2021-12-05 22:42
i was/being affected by the the same issue

See also here: 

https://github.com/nextcloud/desktop/issues/4016#issuecomment-986024350

Now a new problem popped-up:

* 2.12.2021: got message from Windows Desktop Client on "stable channel !" to upgrade 3.4.0
* 2.12.2021: after upgrade to 3.4.0 - tons of file with change date:1970, needed to restore all my user files (after agent downgrade to 3.3.6)
* 5.12.2021: NC Server Upgrade from 21.0.5 to 21.0.7 and to 22.0.3
* 5.12.2021: Just saw, that some same files from other users get synchronzied all the time ( running in a indefinite loop), which
cause a lot of traffic and load to the server

**Comment by Githopp192** [comment] 2021-12-06 08:51
it shows now, that the never-ending sync loop causes file versions with ending "*.v-3600".
That means - there are thousand of files with the same ending, which are created ever and ever. 
I'm running "LSYNCD" (it's some kind of rsync daemon) - and LSYCNC is now syncing file versions files with ending *.v-3600 in a never-ending-loop.

**Comment by iniOr** [comment] 2021-12-06 10:23
I confirm this issue with client version 3.4 on Windows 10, files are randomly changed and then they loose their date information (reset to epoch 01/01/1970) :
`ls -al` give this result on a "impacted" file :

`-rw-r--r-- 1 www-data www-data 31880 Jan  1  1970 <redacted>.pdf`

File content is intact but date is gone.

File(s) must be restored from backup to restore date properties, this is a big problem.

```
Operating system: Linux 5.10.0-9-amd64 #1 SMP Debian 5.10.70-1 (2021-09-30) x86_64

Webserver: Apache/2.4.51 (Debian) (apache2handler)

Database: mysql 10.5.12

PHP version: 7.4.26

Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, sodium, apache2handler, mysqlnd, PDO, xml, apcu, bcmath, bz2, calendar, ctype, curl, dom, mbstring, FFI, fileinfo, ftp, gd, geoip, gettext, gmp, iconv, igbinary, imagick, imap, intl, json, maxminddb, exif, msgpack, mysqli, pdo_mysql, apc, posix, readline, shmop, SimpleXML, soap, sockets, sysvmsg, sysvsem, sysvshm, tidy, tokenizer, xmlreader, xmlrpc, xmlwriter, xsl, zip, Phar, memcached, Zend OPcache

Nextcloud version: 22.2.3 - 22.2.3.0
```

**Comment by isdnfan** [comment] 2021-12-06 11:43
> File(s) must be restored from backup to restore date properties,

depending on your hosting option you may want to restore the whole installation from backup as bad sync results in multiple versions of same file created on the server and filling storage..

**Comment by claell** [comment] 2021-12-06 13:06
Duplicate of #4016

**Closed by claell** 2021-12-06 13:06 UTC
Labels: bug
