### ISSUE TITLE
upload/download broken with E2EE app enabled

### ISSUE THREAD

**Issue by Pilzinsel64** [nextcloud/desktop#2050] opened 2020-05-30 17:50 UTC
### Expected behaviour
The sync just should start to sync as fast as without E2EE app enabled AND should even upload and download files and don't just stay with `0 Seconds left, 0B of xyKB`. I am talking about unencrypted folders, btw.

### Actual behaviour
The client tries to sync the files between server and client (upload and download) and after a long time it results in this view without any progress and without end. This happens as soon as the app "End-to-End encryption" is enabled on the server.
![grafik](https://user-images.githubusercontent.com/23138465/83335791-82767800-a2af-11ea-934d-235dfcb66213.png)

### Steps to reproduce
1. Enable end-to-end encryption app on Nextcloud Server
2. Restart Desktop Client.
3. Put a file to any unencrypted folder locally or on server and let it sync.

### Client configuration
Client version: Version 2.6.4 Stable

Operating system: Windows 10

OS language: German

Installation path of client: C:\Programme\Nextcloud

### Server configuration

Nextcloud version: 18.0.4.2, 19.0.0.11

**Comment by georgehrke** [comment] 2020-05-31 10:57
There is some additional info in https://github.com/nextcloud/end_to_end_encryption/issues/159

**Comment by Pilzinsel64** [comment] 2020-06-01 14:02
I found out that this happens to subfolders only. It still doesn't matter if the parent folder of that sub folder is encrypted or not. All files in any sub folder will not be uploaded or downloaded and the client sucks at the view of the screenshot.

**Comment by er-vin** [comment] 2020-06-02 18:27
This looks an awful lot like a duplicate of #1417 indeed. I'll thus close this one. At least this one helps us confirm it stills shows up with 2.6.4 and on Windows. Thanks for that!

**Closed by er-vin** 2020-06-02 18:27 UTC
Labels: 0. Needs triage, bug, feature: :lock: end to end encryption
