### ISSUE TITLE
3.3.0 Can not create new account when using LDAP

### ISSUE THREAD

**Issue by v2km** [nextcloud/desktop#3628] opened 2021-08-04 13:14 UTC
Cant connect to Nextcloud since 3.3.0 ... 3.2.4 worked ... 3.3.0 drops with following error:

No connection to Nextcloud to https://xxx.xxx.xx; Server answered "404 Not Found" "PROPFIND https://xx.xxxx.xx/remote.php/dav/files/email@adress.xx/* (Principal with name email@adress.xx not found)

Server is connected to an LDAP usind E-Mailadresses for login ... tried using the AD-Username too ... same issue.

Everything worked fine with 3.2.4

Edit: Sorry for messing up the title

**Comment by schneif2** [comment] 2021-08-04 14:39
I can confirm issue new Desktop Version 3.3.0.

Started with Version 3.2.4 adding account and works well.
Then upgraded to Version 3.3.0 existing account still works.
When i add same account again, there is dav_user Variable missing.

We use UUID from Active Directory as identifier but samaccountname for login. 

Here snipped from Desktop Configuration C:\Users\<user>\AppData\Roaming\Nextcloud\nextcloud.cfg

0\ = Set up with Version 3.2.4
1\ = Set up with Version 3.3.0

Also tried with complete fresh installation on different computer.

```
[General]
clientVersion=3.3.0stable-Win64 (build 20210729)
updateSegment=97
optionalServerNotifications=true
showInExplorerNavigationPane=true

[Accounts]
0\FoldersWithPlaceholders\1\localPath=C:/Users/<user/samaccountname>/Nextcloud/
version=2
0\FoldersWithPlaceholders\1\journalPath=.sync_8789c7341e5d.db
0\version=1
0\FoldersWithPlaceholders\1\targetPath=/
0\url=https://<serveraddress>
0\FoldersWithPlaceholders\1\paused=false
0\dav_user=<user/uuid>
0\FoldersWithPlaceholders\1\ignoreHiddenFiles=false
0\serverVersion=21.0.3.1
0\webflow_user=<user/samaccountname>
0\FoldersWithPlaceholders\1\virtualFilesMode=wincfapi
0\authType=webflow
0\FoldersWithPlaceholders\1\version=3
0\FoldersWithPlaceholders\1\navigationPaneClsid=@Variant(\0\0\0\x1e\xb2\x9f\xb5\x11$\xc6\x46\xef\x8a\xabWQ\x85K:\xbe)
0\user=@Invalid()

1\FoldersWithPlaceholders\2\localPath=C:/Users/<user/samaccountname>/Nextcloud2/
1\FoldersWithPlaceholders\2\journalPath=.sync_8789c7341e5d.db
1\FoldersWithPlaceholders\2\targetPath=/
1\FoldersWithPlaceholders\2\paused=false
1\FoldersWithPlaceholders\2\ignoreHiddenFiles=false
1\webflow_user=<user/samaccountname>
1\FoldersWithPlaceholders\2\virtualFilesMode=wincfapi
1\authType=webflow
1\FoldersWithPlaceholders\2\version=3
1\FoldersWithPlaceholders\2\navigationPaneClsid=@Variant(\0\0\0\x1e\xca\xe3^\x86~UN\xcd\x8b\x9dy\x9c\x95\x91\xba\x2)
1\version=1
1\url=https://<serveraddress>
1\dav_user=
1\serverVersion=21.0.3.1
```

penultimate line from config 1\ dav_user is empty and in 0\ configuration there is existing uuid from account identifier

Workaround:
Close Desktop Client, Change dav_user to user identifier (in my case uuid from active directory or folder name in data directory) in configuration.cfg, start Desktop Client again and it works.

Environment:
 - Server: Ubuntu 20.04 LTS, Nextcloud 21.0.3.1 with LDAP Plugin for Authentication
 - Client: Nextcloud 3.2.4 / 3.3.0 on Windows 10

Maybe affected by this change?
https://github.com/nextcloud/desktop/pull/3592

**Comment by michael-andreev** [comment] 2021-08-04 15:48
I'm having the same issue with NextCloud 3.3.0 and LDAP user. I'm using login name instead of email address (@FlexW). The error text is:

> No connection to Nextcloud to https://xxx.xxx.xx; Server answered "404 Not Found" "PROPFIND https://xx.xxxx.xx/remote.php/dav/files/username/" (Principal with name __username__ not found)

I found that this URL from the error description doesn't exist:

https://xx.xxxx.xx/remote.php/dav/files/username/

The URL with `UID` (instead `username`) exists:

https://xx.xxxx.xx/remote.php/dav/files/XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX

**Comment by tensor5g** [comment] 2021-08-05 00:48
Same issue, using LDAP. It appears to be trying to use my username instead of my UUID for DAV

**Comment by schneif2** [comment] 2021-08-05 06:33
> Could you try to log in with your login name instead of your email address? The issue with the email address is known #3617
> 
> The issue is because the change in #3541 uncovered a longtime undetected bug.

Hello FlexW,
for login we use username / samaccount name and not email address. It seams that an empty dav_user in configuration will be overwritten to usename / samaccount name instead of foldername in our case uuid for active directory.

**Comment by Doev** [comment] 2021-08-05 15:40
same here

**Comment by splitt3r** [comment] 2021-08-05 20:31
@v2km could you give this issue a more descriptive title? So others can find this issue.

**Comment by Doev** [comment] 2021-08-06 05:28
3.3.0 is no more in the stable update channel, thank you.

**Comment by FlexW** [comment] 2021-08-06 09:46
@v2km @Doev @tensor5g @schneif2 I created a draft pull request which could resolve the problem. Are you willing to test it? If yes, please tell me for which operating system you need a build.
https://github.com/nextcloud/desktop/pull/3632

**Comment by Doev** [comment] 2021-08-06 09:49
Windows 64bit.

**Comment by v2km** [comment] 2021-08-06 10:33
@FlexW Yeah same ... Windows 10 64 Bit,

we tested the 3.3.0 client a bit further the last days

we reconized that no all LDAP Users where affected, and we even had one server with no issues at all with the 3.3.0 client

altough the AD had all the same configurations and even between the users we didnt found any difference in configuration

all in all pretty strange effect.

We will be able to test the new draft build.
Thx for your hard work so far. We really love Nextcloud

**Comment by FlexW** [comment] 2021-08-06 12:08
@Doev @v2km Thanks :) Here you go https://cloud.nextcloud.com/s/a7J6rDet5xe8qCk

**Comment by Doev** [comment] 2021-08-06 12:09
Our Serverversion is: 21.0.2
and we filter the ldap user with a given OU.

**Comment by Doev** [comment] 2021-08-06 12:26
> 
> 
> @Doev @v2km Thanks :) Here you go https://cloud.nextcloud.com/s/a7J6rDet5xe8qCk

works

**Comment by meichthys** [comment] 2021-08-06 13:07
> 
> 
> @Doev @v2km Thanks :) Here you go https://cloud.nextcloud.com/s/a7J6rDet5xe8qCk

This works for me as well 👍

**Comment by schneif2** [comment] 2021-08-09 12:07
> @Doev @v2km Thanks :) Here you go https://cloud.nextcloud.com/s/a7J6rDet5xe8qCk

Yes also tried and now webflow_user and dav_user in nextcloud.cfg are correct with our UUID from LDAP. 👍 Thank you

**Comment by DanScharon** [comment] 2021-08-09 12:10
I can also confirm the corrected behavior. Could this be released as soon as possible via 3.3.1?

**Comment by gavindi** [comment] 2021-08-10 02:03
I've tried the AppImage above for Ubuntu and while it does indeed solve the issue when you have one LDAP enabled account but I have two Nextcloud servers both with LDAP and when I add the 2nd account, I have the same error for the 2nd account although the 1st one added continues to work.

**Comment by FlexW** [comment] 2021-08-10 07:24
@gavindi Thanks for the feedback. Is it also impossible for you to add the second account after you restarted the app? Which server versions are you using?

**Comment by FlexW** [comment] 2021-08-10 08:28
@gavindi Could you please also provide me your logs? You can drop them here https://cloud.nextcloud.com/s/6w5abTCtdHJQjrw

**Comment by HamburgerJungeJr** [comment] 2021-08-10 11:00
For me the problem is solved, too. At first the DisplayName didn't work and I saw the AD-ID but after a few minutes the correct name was displayed.

**Comment by FlexW** [comment] 2021-08-10 11:07
@HamburgerJungeJr Could you please tell me where exactly you saw the AD-ID in the GUI?

**Comment by HamburgerJungeJr** [comment] 2021-08-10 11:38
I saw it in the Main window:
![](https://user-images.githubusercontent.com/11501266/128860451-9c9e848d-e8fd-4030-a1d4-aaca8a64b0df.png)

**Comment by FlexW** [comment] 2021-08-10 12:01
@HamburgerJungeJr okay thanks. Was it after a restart of the app again visible?

**Comment by Chadarius** [comment] 2021-08-10 18:32
I've just dropped back to 3.2.4 until this issue is resolved. I use OpenLDAP and this issue is affecting me as well. Thanks for working on it! :)

**Comment by gavindi** [comment] 2021-08-10 18:33
> @gavindi Thanks for the feedback. Is it also impossible for you to add the second account after you restarted the app? Which server versions are you using?

@FlexW Restarting the client app yields the same result of the 1st account added working and the 2nd account not working.  The server version of the 1st Nextcloud server is 22.1.0 and the server version of the 2nd is 20.0.8.1.

**Comment by HamburgerJungeJr** [comment] 2021-08-11 10:56
@FlexW After a reboot the LDAP-Accounts requested a login which failed. Also the AD-ID was visible instead of the name.
So we also reverted back to 3.2.4

**Comment by patit72** [comment] 2021-08-11 11:03
Same problem here. Reverted to 3.2.4 as well

**Closed** 2021-08-11 14:17 UTC
Labels: 1. to develop, bug, regression, approved

**Comment by dcrobertson01** [comment] 2021-08-13 08:22
Hi - just downloaded and installed version 3.3.0 of the client, and have the same problem. The fancy pants account configuration is great when it works, but there seems to be no way to check or edit the client settings. or to manually enter account details. 
Why is the link on Nextcloud still pointing to a version that does not work? Where do I get the old version? Or is Nextcloud just unavailable until this problem gets fixed?
