### ISSUE TITLE
Smaller default window size

### ISSUE THREAD

**Issue by monreal** [nextcloud/desktop#275] opened 2018-04-30 16:57 UTC
The Nextcloud client (latest flatpak release built from https://github.com/owncloud/client/commit/57bc7918d7b0650c116f3512787f7677d4e5ab17) unfortunately does not fit on a my notebook's screen (1366x768). As I am using GNOME with a top panel, the bottom row of the window is cut off, including the "close" button. 

I think the window size was chosen in order to fit the largest page without scrolling. This seems to be the "General" page. An easy way to reduce the size would be to move the "About" and "Updates" section to a new page, as they don't really fit with the rest of that page anyway.

Another, maybe even better approach would be moving "General" and "Network" to a Preferences window where they actually belong and merge the Account page and Activity tabs. That way you could also get rid of the huge Account / Activity / General / Network "tabs".

**Comment by ykgmfq** [comment] 2018-05-16 14:53
Duplicate of #91

**Comment by juliushaertl** [comment] 2018-06-18 17:38
Closing as a duplicate of https://github.com/nextcloud/desktop/issues/91

**Closed by juliushaertl** 2018-06-18 17:38 UTC
Labels: design, discussion, enhancement
