### ISSUE TITLE
[Bug]: Synchronization jumps to a negative number

### ISSUE THREAD

**Issue by kc8iqw** [nextcloud/desktop#6270] opened 2023-12-08 01:49 UTC
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

During synchronization of a large amount of data, prior to changing to GB the number will flip from positive to negative.

### Steps to reproduce

Open the desktop popup on initial sync or after changing over 2,048MB of data.  Personally I had 20+ GB of data to sync as it was a new setup.

### Expected behavior

The progress counter will count up to about 2,048,000,000 and then jump to -2,048,000,000 and start counting to 0.  Once it reaches 0, it will flip to GB.
![nextcloud float error](https://github.com/nextcloud/desktop/assets/8919746/14be25a9-68de-491c-8d38-80b28ec9e0d2)

### Which files are affected by this bug

This appears to be a cosmetic bug.

### Operating system

Windows

### Which version of the operating system you are running.

Windows 10 Home 22H2 19045.3693

### Package

Official SNAP package

### Nextcloud Server version

27.1.3snap1

### Nextcloud Desktop Client version

3.10.1

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by PhilippSchlesinger** [comment] 2023-12-08 08:30
This is a duplicate of https://github.com/nextcloud/desktop/issues/5519 that got closed recently by a fix implemented in https://github.com/nextcloud/desktop/issues/5519.
The fix will be part of the future 3.10.x and 3.11 releases.
So you may want to close this issue.

**Closed** 2023-12-08 20:07 UTC
Labels: 0. Needs triage
