### ISSUE TITLE
[Bug]: NextCloud 3.5.1 crashes on MacOS 10.13.6

### ISSUE THREAD

**Issue by EmmanuelLazard** [nextcloud/desktop#4591] opened 2022-05-23 15:06 UTC
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

Upgrading from NextCloud 3.5.0 to 3.5.1 crashes on launch on my Mac. I'm running MacOS 10.13.6

### Steps to reproduce

Just try to launch Nextcloud

### Expected behavior

It should work...

### Which files are affected by this bug

Nexcloud 3.5.1

### Operating system

Mac OS

### Which version of the operating system you are running.

MacOS 10.13.6

### Package

Appimage

### Nextcloud Server version

23.0.3

### Nextcloud Desktop Client version

3.5.1

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 3.4.2 to 3.4.4)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Additional info

Process:               Nextcloud [36926]
Path:                  /Applications/nextcloud.app/Contents/MacOS/Nextcloud
Identifier:            com.nextcloud.desktopclient
Version:               3.5.1git [build 10326] (3.5.1.10326)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Nextcloud [36926]
User ID:               501

Date/Time:             2022-05-23 16:54:29.329 +0200
OS Version:            Mac OS X 10.13.6 (17G14042)
Report Version:        12
Anonymous UUID:        2AC5A12F-928B-8D4D-FC22-B193CA9491B2

Sleep/Wake UUID:       46B4A7F4-7B90-4EB8-9C55-26C354029BEF

Time Awake Since Boot: 77000 seconds
Time Since Wake:       11000 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderArray initWithObjects:count:]: attempt to insert nil object from objects[0]'
terminating with uncaught exception of type NSException
abort() called

Application Specific Backtrace 1:
0   CoreFoundation                      0x00007fff4e3f4bbb __exceptionPreprocess + 171
1   libobjc.A.dylib                     0x00007fff75806c76 objc_exception_throw + 48
2   CoreFoundation                      0x00007fff4e435e44 _CFThrowFormattedException + 202
3   CoreFoundation                      0x00007fff4e2f027e -[__NSPlaceholderArray initWithObjects:count:] + 238
4   CoreFoundation                      0x00007fff4e2f7c54 +[NSArray arrayWithObjects:count:] + 52
5   Nextcloud                           0x000000010cff1b1b _ZN3OCC30registerNotificationCategoriesERK7QString + 187
6   Nextcloud                           0x000000010ceb759e _ZN3OCC7SystrayC2Ev + 430
7   Nextcloud                           0x000000010ceb7055 _ZN3OCC7SystrayC1Ev + 21
8   Nextcloud                           0x000000010ceb6ff6 _ZN3OCC7Systray8instanceEv + 54
9   Nextcloud                           0x000000010cd4f697 _ZN3OCC14AccountManager13createAccountEv + 279
10  Nextcloud                           0x000000010cd4afe1 _ZN3OCC14AccountManager17loadAccountHelperER9QSettings + 705
11  Nextcloud                           0x000000010cd49586 _ZN3OCC14AccountManager7restoreEv + 1974
12  Nextcloud                           0x000000010cd79eb4 _ZN3OCC11ApplicationC2ERiPPc + 6644
13  Nextcloud                           0x000000010cd7fdc5 _ZN3OCC11ApplicationC1ERiPPc + 37
14  Nextcloud                           0x000000010cd113aa main + 682
15  libdyld.dylib                       0x00007fff76424015 start + 1
16  ???                                 0x0000000000000001 0x0 + 1

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	0x00007fff76574b66 __pthread_kill + 10
1   libsystem_pthread.dylib       	0x00007fff7673f080 pthread_kill + 333
2   libsystem_c.dylib             	0x00007fff764d01ae abort + 127
3   libc++abi.dylib               	0x00007fff743c7f8f abort_message + 245
4   libc++abi.dylib               	0x00007fff743c812b default_terminate_handler() + 265
5   libobjc.A.dylib               	0x00007fff75808ea3 _objc_terminate() + 97
6   libc++abi.dylib               	0x00007fff743e37c9 std::__terminate(void (*)()) + 8
7   libc++abi.dylib               	0x00007fff743e326f __cxa_throw + 121
8   libobjc.A.dylib               	0x00007fff75806da5 objc_exception_throw + 351
9   com.apple.CoreFoundation      	0x00007fff4e435e44 _CFThrowFormattedException + 202
10  com.apple.CoreFoundation      	0x00007fff4e2f027e -[__NSPlaceholderArray initWithObjects:count:] + 238
11  com.apple.CoreFoundation      	0x00007fff4e2f7c54 +[NSArray arrayWithObjects:count:] + 52
12  com.nextcloud.desktopclient   	0x000000010cff1b1b OCC::registerNotificationCategories(QString const&) + 187
13  com.nextcloud.desktopclient   	0x000000010ceb759e OCC::Systray::Systray() + 430
14  com.nextcloud.desktopclient   	0x000000010ceb7055 OCC::Systray::Systray() + 21
15  com.nextcloud.desktopclient   	0x000000010ceb6ff6 OCC::Systray::instance() + 54
16  com.nextcloud.desktopclient   	0x000000010cd4f697 OCC::AccountManager::createAccount() + 279
17  com.nextcloud.desktopclient   	0x000000010cd4afe1 OCC::AccountManager::loadAccountHelper(QSettings&) + 705
18  com.nextcloud.desktopclient   	0x000000010cd49586 OCC::AccountManager::restore() + 1974
19  com.nextcloud.desktopclient   	0x000000010cd79eb4 OCC::Application::Application(int&, char**) + 6644
20  com.nextcloud.desktopclient   	0x000000010cd7fdc5 OCC::Application::Application(int&, char**) + 37
21  com.nextcloud.desktopclient   	0x000000010cd113aa main + 682
22  libdyld.dylib                 	0x00007fff76424015 start + 1

Thread 1:
0   libsystem_kernel.dylib        	0x00007fff7657528a __workq_kernreturn + 10
1   libsystem_pthread.dylib       	0x00007fff7673c009 _pthread_wqthread + 1035
2   libsystem_pthread.dylib       	0x00007fff7673bbe9 start_wqthread + 13

Thread 2:
0   libsystem_kernel.dylib        	0x00007fff7657528a __workq_kernreturn + 10
1   libsystem_pthread.dylib       	0x00007fff7673c009 _pthread_wqthread + 1035
2   libsystem_pthread.dylib       	0x00007fff7673bbe9 start_wqthread + 13

Thread 3:
0   libsystem_kernel.dylib        	0x00007fff7657528a __workq_kernreturn + 10
1   libsystem_pthread.dylib       	0x00007fff7673c20e _pthread_wqthread + 1552
2   libsystem_pthread.dylib       	0x00007fff7673bbe9 start_wqthread + 13

Thread 4:
0   libsystem_kernel.dylib        	0x00007fff7657528a __workq_kernreturn + 10
1   libsystem_pthread.dylib       	0x00007fff7673c009 _pthread_wqthread + 1035
2   libsystem_pthread.dylib       	0x00007fff7673bbe9 start_wqthread + 13

Thread 5:: com.apple.CFSocket.private
0   libsystem_kernel.dylib        	0x00007fff76574cf2 __select + 10
1   com.apple.CoreFoundation      	0x00007fff4e3a954b __CFSocketManager + 635
2   libsystem_pthread.dylib       	0x00007fff7673c661 _pthread_body + 340
3   libsystem_pthread.dylib       	0x00007fff7673c50d _pthread_start + 377
4   libsystem_pthread.dylib       	0x00007fff7673bbf9 thread_start + 13

Thread 6:: Qt bearer thread
0   libsystem_kernel.dylib        	0x00007fff7657609a poll + 10
1   org.qt-project.QtCore         	0x000000010f79f8ee qt_safe_poll(pollfd*, unsigned int, timespec const*) + 94
2   org.qt-project.QtCore         	0x000000010f7a115b QEventDispatcherUNIX::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) + 795
3   org.qt-project.QtCore         	0x000000010f73dd66 QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) + 502
4   org.qt-project.QtCore         	0x000000010f577d6c QThread::exec() + 140
5   org.qt-project.QtCore         	0x000000010f578c38 0x10f555000 + 146488
6   libsystem_pthread.dylib       	0x00007fff7673c661 _pthread_body + 340
7   libsystem_pthread.dylib       	0x00007fff7673c50d _pthread_start + 377
8   libsystem_pthread.dylib       	0x00007fff7673bbf9 thread_start + 13

Thread 7:: Thread (pooled)
0   libsystem_kernel.dylib        	0x00007fff76574a16 __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff7673d589 _pthread_cond_wait + 732
2   org.qt-project.QtCore         	0x000000010f580d2c 0x10f555000 + 179500
3   org.qt-project.QtCore         	0x000000010f580a2e 0x10f555000 + 178734
4   org.qt-project.QtCore         	0x000000010f580984 QWaitCondition::wait(QMutex*, QDeadlineTimer) + 84
5   org.qt-project.QtCore         	0x000000010f57d24e 0x10f555000 + 164430
6   org.qt-project.QtCore         	0x000000010f578c38 0x10f555000 + 146488
7   libsystem_pthread.dylib       	0x00007fff7673c661 _pthread_body + 340
8   libsystem_pthread.dylib       	0x00007fff7673c50d _pthread_start + 377
9   libsystem_pthread.dylib       	0x00007fff7673bbf9 thread_start + 13

Thread 8:: Thread (pooled)
0   libsystem_kernel.dylib        	0x00007fff76574a16 __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff7673d589 _pthread_cond_wait + 732
2   org.qt-project.QtCore         	0x000000010f580d2c 0x10f555000 + 179500
3   org.qt-project.QtCore         	0x000000010f580a2e 0x10f555000 + 178734
4   org.qt-project.QtCore         	0x000000010f580984 QWaitCondition::wait(QMutex*, QDeadlineTimer) + 84
5   org.qt-project.QtCore         	0x000000010f57d24e 0x10f555000 + 164430
6   org.qt-project.QtCore         	0x000000010f578c38 0x10f555000 + 146488
7   libsystem_pthread.dylib       	0x00007fff7673c661 _pthread_body + 340
8   libsystem_pthread.dylib       	0x00007fff7673c50d _pthread_start + 377
9   libsystem_pthread.dylib       	0x00007fff7673bbf9 thread_start + 13

Thread 9:: Thread (pooled)
0   libsystem_kernel.dylib        	0x00007fff76574a16 __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff7673d589 _pthread_cond_wait + 732
2   org.qt-project.QtCore         	0x000000010f580d2c 0x10f555000 + 179500
3   org.qt-project.QtCore         	0x000000010f580a2e 0x10f555000 + 178734
4   org.qt-project.QtCore         	0x000000010f580984 QWaitCondition::wait(QMutex*, QDeadlineTimer) + 84
5   org.qt-project.QtCore         	0x000000010f57d24e 0x10f555000 + 164430
6   org.qt-project.QtCore         	0x000000010f578c38 0x10f555000 + 146488
7   libsystem_pthread.dylib       	0x00007fff7673c661 _pthread_body + 340
8   libsystem_pthread.dylib       	0x00007fff7673c50d _pthread_start + 377
9   libsystem_pthread.dylib       	0x00007fff7673bbf9 thread_start + 13

Thread 10:: Thread (pooled)
0   libsystem_kernel.dylib        	0x00007fff76574a16 __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff7673d589 _pthread_cond_wait + 732
2   org.qt-project.QtCore         	0x000000010f580d2c 0x10f555000 + 179500
3   org.qt-project.QtCore         	0x000000010f580a2e 0x10f555000 + 178734
4   org.qt-project.QtCore         	0x000000010f580984 QWaitCondition::wait(QMutex*, QDeadlineTimer) + 84
5   org.qt-project.QtCore         	0x000000010f57d24e 0x10f555000 + 164430
6   org.qt-project.QtCore         	0x000000010f578c38 0x10f555000 + 146488
7   libsystem_pthread.dylib       	0x00007fff7673c661 _pthread_body + 340
8   libsystem_pthread.dylib       	0x00007fff7673c50d _pthread_start + 377
9   libsystem_pthread.dylib       	0x00007fff7673bbf9 thread_start + 13

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000000  rbx: 0x00007fffaed1c380  rcx: 0x00007ffee2ef49c8  rdx: 0x0000000000000000
  rdi: 0x0000000000000307  rsi: 0x0000000000000006  rbp: 0x00007ffee2ef4a00  rsp: 0x00007ffee2ef49c8
   r8: 0x00007ffee2ef4890   r9: 0x00007ffee2ef4a60  r10: 0x0000000000000000  r11: 0x0000000000000206
  r12: 0x0000000000000307  r13: 0x0000000000000030  r14: 0x0000000000000006  r15: 0x000000000000002d
  rip: 0x00007fff76574b66  rfl: 0x0000000000000206  cr2: 0x00007fffaecf9168
  
Logical CPU:     0
Error Code:      0x02000148
Trap Number:     133

**Comment by EmmanuelLazard** [comment] 2022-05-23 15:09
Just realized the minimum version number is now 10.14 but then  it should not propose upgrade !

**Comment by claucambra** [comment] 2022-05-23 15:59
Since this is a duplicate of https://github.com/nextcloud/desktop/issues/4567 I will close.

> Just realized the minimum version number is now 10.14 but then it should not propose upgrade !

You're right -- unfortunately we can't retroactively change the update behaviour of the 3.5.0 release, but we will take this into account for future updates :)

**Closed by claucambra** 2022-05-23 15:59 UTC
Labels: 0. Needs triage
