### ISSUE TITLE
Enable Encryption of Top Level Folders

### ISSUE THREAD

**Issue by Vortex-TH** [nextcloud/desktop#1147] opened 2019-03-17 20:55 UTC
### Expected behaviour
It should be possible to encrypt and decrypt top-level folders with the desktop client. 

### Actual behaviour
It is not possible to encrypt top-level folders with the desktop client. When creating a new top-level folder (by clicking 'Add Folder Sync Connection'), it is possible to select and connect with a folder from the server that is already encrypted. However, in this case the desktop client is not able to decrypt the files from the folder. Contrarily, files will be uploaded but not encrypted if they are placed in this folder on the desktop client.

### Steps to reproduce
1. Install End-to-End encryption
2. Create an encrypted folder on the Server (for example by using the mobile client)
3. On the desktop client, add a new top-level folder with 'Add Folder Sync Connection'
4. Select the encrypted folder from the server to connect to
5. Notice that encryption/decryption of top-level folders does not work (Picture 1). It only works for subfolders (Picture 2). Notice that connecting with encrypted folders is still possible but leads to some undesirable behaviour.

Client version: 2.5.1
Operating system: Linux

Note: Issue addresses #1063 which was wrongfully closed.

![Picture 1](https://user-images.githubusercontent.com/3118243/54497754-a0e89180-48fe-11e9-8f12-2d9fb07c10fe.png)

![Picture 2](https://user-images.githubusercontent.com/3118243/54497757-a514af00-48fe-11e9-942c-b4d5ef681ef4.png)

**Comment by claell** [comment] 2020-04-08 20:12
@Vortex-TH thanks for opening this. I guess you opened this, because #1063 was wrongly closed. I reopened #1063 now, so can you move your additional description from here to the description of #1063? Then we can close this as a duplicate and track your issue further in #1063.

**Comment by misch7** [comment] 2020-05-18 12:59
Thanks for coordinating and moving this to the original issue @Vortex-TH and @claell .

I'll close this issue as duplicate then, so we have a better overview - we already have a lot of E2EE issues open.

**Closed by misch7** 2020-05-18 12:59 UTC
Labels: bug, feature: :lock: end to end encryption

**Comment by claell** [comment] 2020-05-20 13:01
Duplicate of #1063
