### ISSUE TITLE
[Bug]: 3.5.1.10326 on macOS does not start

### ISSUE THREAD

**Issue by workflowsguy** [nextcloud/desktop#4579] opened 2022-05-19 15:57 UTC
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

After opening Nextcloud Desktop Client, it immediately vanishes again without any visible error message.
After each unsuccessful opening attempt, in the macOS log file there is an entry like this:
```
May 19 16:37:29 Guys-iMac com.apple.xpc.launchd[1] (com.nextcloud.desktopclient.FinderSyncExt[95537]): Service exited due to signal: Illegal instruction: 4 sent by exc handler[0]
```

Previous versions of the Desktop Client up to 3.5.0.10063 worked without problems on this machine.

### Steps to reproduce

1. open Nextcloud Desktop Client either by double clicking the app in Finder or call 'open -a /Applications/Nextcloud.app' 

### Expected behavior

The Nextcloud icon appears in the menu bar

### Which files are affected by this bug

Nextcloud.app

### Operating system

Mac OS

### Which version of the operating system you are running.

10.13.6

### Package

Appimage

### Nextcloud Server version

22.2.7

### Nextcloud Desktop Client version

3.5.1.10326

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 3.4.2 to 3.4.4)

### Are you using the Nextcloud Server Encryption module?

Encryption is Enabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by ingorichter** [comment] 2022-05-20 03:23
I get crashes during the day for the last couple of days. The call stack might provide helpful information
[Nextcloud Crash Log.txt](https://github.com/nextcloud/desktop/files/8735663/Nextcloud.Crash.Log.txt)

**Comment by houdini69** [comment] 2022-05-20 09:27
Exact same issue for me on macOS 10.13.6. Ins system.log:
May 20 09:27:34 xxxxxxxxxx-macmini com.apple.xpc.launchd[1] (com.nextcloud.desktopclient.FinderSyncExt[999]): Service exited due to signal: Segmentation fault: 11 sent by exc handler[0]
and in user report:
ath:                  /Applications/Nextcloud.app/Contents/PlugIns/FinderSyncExt.appex/Contents/MacOS/FinderSyncExt
Identifier:            com.nextcloud.desktopclient.FinderSyncExt
    __TEXT                 0000000100fa7000-0000000100fb3000 [   48K] r-x/r-x SM=COW  L [/Applications/Nextcloud.app/Contents/PlugIns/FinderSyncExt.appex/Contents/MacOS/FinderSyncExt]
1   com.nextcloud.desktopclient.FinderSyncExt	0x0000000100fabcd7 -[LocalSocketClient closeConnection] + 70
2   com.nextcloud.desktopclient.FinderSyncExt	0x0000000100fabbb5 -[LocalSocketClient restart] + 44
3   com.nextcloud.desktopclient.FinderSyncExt	0x0000000100fabaae -[LocalSocketClient start] + 1334
4   com.nextcloud.desktopclient.FinderSyncExt	0x0000000100fada24 -[FinderSync init] + 1021
       0x100fa7000 -        0x100fb2ffb +com.nextcloud.desktopclient.FinderSyncExt (1.0 - 1) <F2EC2FAE-D3D7-3FDA-B646-A53A7D8097BA> /Applications/Nextcloud.app/Contents/PlugIns/FinderSyncExt.appex/Contents/MacOS/FinderSyncExt

I had to reinstall previous version 3.5.0.

**Comment by claucambra** [comment] 2022-05-20 11:08
Hey folks, this is a duplicate of #4567 so I will close, butI will post here what I posted in the other thread:

>  I'm sorry to say with 3.5.1 we are bumping up our minimum requirements for macOS to 10.14, as the UserNotification system required for actionable notifications in macOS is unavailable on versions <10.14.
>
> If you need the desktop client and are unable to upgrade your OS, we recommend you stick to version 3.5.0 of the desktop client or lower to retain compatibility. Thanks however for reporting

**Closed by claucambra** 2022-05-20 11:08 UTC
Labels: 0. Needs triage

**Comment by workflowsguy** [comment] 2022-05-20 14:03
@claucambra 

> I'm sorry to say with 3.5.1 we are bumping up our minimum requirements for macOS to 10.14, as the UserNotification system required for actionable notifications in macOS is unavailable on versions <10.14.

the info.plist of the app should contain a "Minimum system version" key. This will prevent the app from installing on unsupported macOS versions.

Also, in an app that uses semantic versioning, I do not expect such a breaking change to be introduced in a release where only the patch number is incremented.
