### ISSUE TITLE
[Bug]: Nextcloud client makes directories world-writeable

### ISSUE THREAD

**Issue by mod20388** [nextcloud/desktop#6875] opened 2024-07-03 13:05 UTC
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

The client messes up with permissions on newly created directories, making them world-writeable (777).

### Steps to reproduce

1. Create new directory in Nextcloud sync folder
2. Wait for client to synchronize
3. Check directory permissions

### Expected behavior

The client should not mess with permissions.

### Which files are affected by this bug

?

### Operating system

Linux

### Which version of the operating system you are running.

Arch Linux

### Package

Distro package manager

### Nextcloud Server version

29.0.1

### Nextcloud Desktop Client version

2:3.13.1

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 3.4.2 to 3.4.4)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [X] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by PhilippSchlesinger** [comment] 2024-07-03 13:33
This seem to be a duplicate of #6863.

**Comment by joshtrichards** [comment] 2024-07-08 20:47
Duplicate of #6863

**Closed by joshtrichards** 2024-07-08 20:47 UTC
Labels: 0. Needs triage
