### ISSUE TITLE
[Bug]: 100% of CPU usage

### ISSUE THREAD

**Issue by cjdg** [nextcloud/desktop#5381] opened 2023-01-31 16:48 UTC
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

Nextcloud desktop takes 100% cpu usage, latest update 3.6.6-20230120.115834.ff2293824-1.0~jammy1, on ubuntu 22.04, even notification icon and gui has lags of minutes after clicking something on them, cant enable logging function
...

### Steps to reproduce

Boot or launch with linux session, stands at "Preparing for sync", 
Check cpu usage

### Expected behavior

Not to eat all cpu
...

### Which files are affected by this bug

nextcloud-desktop

### Operating system

Linux

### Which version of the operating system you are running.

22.04

### Package

Other

### Nextcloud Server version

25.0.2

### Nextcloud Desktop Client version

3.6.6-20230120.115834.ff2293824-1.0~jammy1

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 3.4.2 to 3.4.4)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [X] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by Hightmar** [comment] 2023-02-03 13:24
Duplicate -> https://github.com/nextcloud/desktop/issues/5381

**Comment by Hightmar** [comment] 2023-02-03 13:24
Duplicate -> https://github.com/nextcloud/desktop/issues/5094

**Comment by solracsf** [comment] 2023-02-20 14:54
Closing as duplicate of https://github.com/nextcloud/desktop/issues/5094

**Closed by solracsf** 2023-02-20 14:54 UTC
Labels: 0. Needs triage
