### ISSUE TITLE
Client marks file on ignore list and symbolic links as "conflicts"

### ISSUE THREAD

**Issue by despens** [nextcloud/desktop#882] opened 2018-11-23 15:19 UTC
### Expected behaviour
After updating the client, files should be synced as before.

### Actual behaviour
Yellow exclamation mark appears, claiming there are "unresolved conflicts". When examining these conflicts, it turns out they are just files on the ignore list or symbolic links. Since typically file systems are full of files on the ignore list (lock files, Mac OS X metadata files, etc), it makes no sense to clean the file system from them. The yellow exclamation mark can appear or disappear while the client is running.

### Steps to reproduce
1. Update client to 2.5
2. Sync

### Client configuration
Client version: 2.5.0git

Operating system: Ubuntu 18.04

OS language: English

Qt version used by client package (Linux only, see also Settings dialog): Settings dialog doesn't show Qt version.

Client package (From Nextcloud or distro) (Linux only): `nextcloud-client/bionic,now 2.5.0-20181111.015125~bionic1 amd64 [installed]` from `deb http://ppa.launchpad.net/nextcloud-devs/client/ubuntu bionic main`

Installation path of client: `/usr/bin/nextcloud`

**Comment by camilasan** [comment] 2018-11-27 16:40
Hi! 

> Yellow exclamation mark appears, claiming there are "unresolved conflicts"

Where do they appear? Are you talking about the Activities list? Could you share some screenshots?

Thanks!

**Comment by jancborchardt** [comment] 2018-11-27 17:07
For me the symlinks were not the issue, they don’t cause a yellow warning or "!" icon. It must be the files on the ignore list or something else for you?

Symlink syncing is tracked at https://github.com/nextcloud/desktop/issues/250

**Comment by despens** [comment] 2018-11-27 17:38
This is what I'm seeing on the client's main screen:
![selection_2018-11-27_18 30 58](https://user-images.githubusercontent.com/571494/49099896-e7907e00-f272-11e8-9929-e615d61b22dc.png)

Upon "click for details" I'm getting to activities with a list of hundreds of yellow exclamation mark signs, some excerpts:
![selection_2018-11-27_18 31 12](https://user-images.githubusercontent.com/571494/49099910-f2e3a980-f272-11e8-8881-3599f6472982.png)

![selection_2018-11-27_18 32 31](https://user-images.githubusercontent.com/571494/49099942-0abb2d80-f273-11e8-98b1-a70126f6d794.png)

So the exclamation mark is given for
- Files on the ignore list
- Files on the blacklist (what's the difference to ignore list?)
- Symbolic Links

None of these raised an error/warning before. Files on the ignore list and symbolic links were just not synced. Now it seems like the client suggests that I should go in and weed out all the problematic files, but that's kind of impossible. I'm regularly exchanging files and directories with folks using Mac OS or Windows, and these operating systems automatically create all kinds of hidden files. Lock files that are the results of editor crashes or an unfortunate system shutdown are not ultimately valuable, but the Nextcloud client seems the wrong place to point them out to me :smile:

**Comment by camilasan** [comment] 2018-11-27 18:04
Thanks @despens! That is the same problem @jancborchardt  also have.

**Comment by Railsimulatornet** [comment] 2019-01-29 08:55
Thanks same problem here 👍

**Comment by tjakobi** [comment] 2019-02-13 10:08
Also see this behavior since upgrading to the 2.5 branch.

**Comment by ar-ml** [comment] 2019-05-21 13:16
Same problem here.
I like to hide subfolders that I do not want to sync, In the past, there were no errors with this method. Now nextvloud is complaining about every file which is recognized by the ignore ilist.
Why? 
Any solutions?

**Comment by keunes** [comment] 2019-10-13 08:11
Duplicate of #566 (?)

**Comment by er-vin** [comment] 2020-06-11 10:00
This should be solved with the upcoming new GUI in 2.7.

**Closed by er-vin** 2020-06-11 10:00 UTC
Labels: approved, bug, design
