### ISSUE TITLE
3.0.1 new activity feed does not show filenames

### ISSUE THREAD

**Issue by OdinsAuge** [nextcloud/desktop#2363] opened 2020-09-04 11:08 UTC
### Expected behaviour
If I read an entry in the activity feed, I want to know which file caused the entry.

### Actual behaviour
The feed does not show the file name. It displays the file name including the path (with sync folder as root), but the path is cut as it is to long for the feed. As it is cut at the end, the file name is not readable at all.
There is also no baloon tooltip that shows the full path.

### Steps to reproduce
1. Open activity feed (click once on the task bar/info bar icon)
2. Look at any activity entry

### Client configuration
Client version: 3.0.1

Operating system: Windows 10

OS language: German

Installation path of client: C:\Program FIles\Nextcloud

### Logs

As this is a design issue, logs do not make sense.

**Comment by workingmachine** [comment] 2020-09-06 14:22
I have the same issue, please fix this annoying behavior,

**Comment by er-vin** [comment] 2020-09-07 11:51
I think we have a couple similar to that one, this is a recurring theme. @jancborchardt guidance is welcome.

**Comment by jancborchardt** [comment] 2020-09-11 16:07
Yeah, so a better structure for the file messages would be:
> **Filename.pdf**
> Edited 4 hours ago · Documents / Project / Customer A

If it’s by someone else:
> **Design review call – Text app.md**
> Added by Julius · 2 days ago · Documents / Project / Customer A

Yes, this can now of course cause the path to ellipsize. That is fine though. Also, we could middle-ellipsize the path so that both start and end is visible? What is definitely more important is what the file name is and who changed it.

**Comment by jancborchardt** [comment] 2020-09-15 11:09
Actually closing this as duplicate of https://github.com/nextcloud/desktop/issues/2325, copying the design spec over and applying the milestone and labels there.

**Closed by jancborchardt** 2020-09-15 11:09 UTC
Labels: design, enhancement, feature: :cloud: system tray, feature: :zap: activity and :bell: notification
