### ISSUE TITLE
Enabling e2e encryption causes clients to issue extremely expensive PROPFIND requests

### ISSUE THREAD

**Issue by as-com** [nextcloud/desktop#2552] opened 2020-10-14 18:26 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour
Enabling end to end encryption allows syncing to happen normally.

### Actual behaviour
Enabling end to end encryption causes client to issue an infinite depth PROPFIND request which on an account with access to a large amount of files (such as through external storages) takes ~2 minutes on the server to process, pegging 1 CPU core at 100%, and creating a response that is tens of megabytes long.

This is the request as captured by Fiddler that the client issues in addition to the normal PROPFIND requests when end to end encryption is enabled:

```
PROPFIND https://[redacted]/remote.php/webdav HTTP/1.1
Host: [redacted]
OCS-APIREQUEST: true
Depth: infinity
Authorization: Basic [redacted]
User-Agent: Mozilla/5.0 (Windows) mirall/3.0.1stable-Win64 (build 20200828) (Nextcloud)
Accept: */*
Content-Type: text/xml; charset=utf-8
X-Request-ID: cf545295-140b-4634-b90d-cb93dfb9fbb0
Cookie: oc_sessionPassphrase=[redacted]; __Host-nc_sameSiteCookielax=true; __Host-nc_sameSiteCookiestrict=true; ocnwrqh103sw=[redacted]
Content-Length: 114
Connection: Keep-Alive
Accept-Encoding: gzip, deflate
Accept-Language: en-US,*

<d:propfind xmlns:d="DAV:"> <d:prop xmlns:nc="http://nextcloud.org/ns"> <nc:is-encrypted/> </d:prop> </d:propfind>
```

This request happens every single time the client wants to sync, which delays syncing by minutes.

(I know the client here is 3.0.1, but the same behavior appears on 3.0.2 on a Mac client too, so nothing changed with this behavior between the versions)

### Steps to reproduce
1. Enable e2e encryption support plugin
2. Activate encryption on mobile (may work through other clients; didn't test)
3. Open client on desktop
4. Enter encryption passphrase
5. Observe _awful_ syncing delays and high server CPU

### Client configuration
Client version: 3.0.1, 3.0.2

Operating system: Windows 10, macOS 10.15.7

OS language: English

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From Nextcloud or distro) (Linux only):

Installation path of client: C:\Program Files\Nextcloud\, /Applications

### Server configuration

Nextcloud version: 19.0.4

Storage backend (external storage): Local filesystem

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile: 

Output of `nextcloud --logdebug --logwindow` or `nextcloud --logdebug --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the Nextcloud directory)
(See also https://docs.nextcloud.com/desktop/2.3/troubleshooting.html#log-files)

https://gist.github.com/as-com/600fe1676ac141cb8f19342290ad9081

2. Web server error log: No messages printed

3. Server logfile: nextcloud log (data/nextcloud.log): No messages printed

**Comment by er-vin** [comment] 2020-10-15 05:31
Duplicate of #2347

**Closed by er-vin** 2020-10-15 05:31 UTC

**Comment by bcutter** [comment] 2020-10-16 20:16
> Duplicate of #2347

Well this issue is much more precise while the one you set as original one talks about NO sync at all.

At the end it probably doesn't really matter cause nobody is working on any of those desktop client E2EE sync shitty bug. Pretty frustrating.
