### ISSUE TITLE
Sync fails when webdav shared folder unavailable

### ISSUE THREAD

**Issue by PriceChild** [nextcloud/desktop#1300] opened 2019-06-11 18:48 UTC
### Expected behaviour
Fastmail is currently down. I it pulled in as a webdav shared folder. The Nextcloud client should continue sync'ing everything else and ignore the failed folder.

### Actual behaviour
Nothing gets synced.

Client logs in the activity window "A HTTP transmission error happened. The server file discovery reply is missing data."

### Steps to reproduce
1. Set up a webdav shared folder.
2. Make the webdav server unavailable
3. Try to use the desktop sync client

### Client configuration
Client version:
2.5.2git

Operating system:
Ubuntu 19.04

OS language:
British English

Qt version used by client package (Linux only, see also Settings dialog):
Not shown? 
![image](https://user-images.githubusercontent.com/1044068/59297988-6c783d80-8c81-11e9-886b-51c0c93a552e.png)

Client package (From Nextcloud or distro) (Linux only):
APT-Sources: http://ppa.launchpad.net/nextcloud-devs/client/ubuntu disco/main amd64 Packages

Installation path of client:
NA

### Server configuration

Nextcloud version:
16.0.1

Storage backend (external storage):
webdav - fastmail
### Logs

```
[webdav] Fatal: Sabre\DAV\Exception\ServiceUnavailable:  at <<closure>>

 0. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Tree.php line 76
    OCA\DAV\Connector\Sabre\Directory->getChild("fastmail")
 1. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 967
    Sabre\DAV\Tree->getNodeForPath("files/pricey/fastmail")
 2. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 1666
    Sabre\DAV\Server->getPropertiesIteratorForPath("files/pricey/fastmail", ["{DAV:}resource ... "], 1)
 3. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php line 355
    Sabre\DAV\Server->generateMultiStatus(Generator {}, false)
 4. <<closure>>
    Sabre\DAV\CorePlugin->httpPropFind(Sabre\HTTP\Reque ... "}, Sabre\HTTP\Response {})
 5. /var/www/nextcloud/3rdparty/sabre/event/lib/EventEmitterTrait.php line 105
    undefinedundefinedcall_user_func_array([Sabre\DAV\CorePlugin {},"httpPropFind"], [Sabre\HTTP\Requ ... }])
 6. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 479
    Sabre\Event\EventEmitter->emit("method:PROPFIND", [Sabre\HTTP\Requ ... }])
 7. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 254
    Sabre\DAV\Server->invokeMethod(Sabre\HTTP\Reque ... "}, Sabre\HTTP\Response {})
 8. /var/www/nextcloud/apps/dav/lib/Server.php line 316
    Sabre\DAV\Server->exec()
 9. /var/www/nextcloud/apps/dav/appinfo/v2/remote.php line 35
    OCA\DAV\Server->exec()
10. /var/www/nextcloud/remote.php line 163
    undefinedundefinedrequire_once("/var/www/nextcl ... p")

PROPFIND /remote.php/dav/files/pricey/fastmail
from ip_address_here by pricey at 2019-06-11T18:33:46+00:00
```

**Comment by PriceChild** [comment] 2019-06-11 18:53
Flipping the "Check for changes" option to "Never" allows syncing...

**Comment by brunt82** [comment] 2019-10-14 08:48
Sounds like #908

**Comment by bottee** [comment] 2020-01-12 19:17
Duplicate of #14797

**Comment by camilasan** [comment] 2021-07-13 14:38
Hi, Could you try to run the most recent desktop client and server to check if you still have this issue? The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients) and [https://nextcloud.com/install/#instructions-server](https://nextcloud.com/install/#instructions-server) respectively.

If you still have this problem with the latest desktop client, please re-open the issue.

Thanks!

**Closed by camilasan** 2021-07-13 14:38 UTC
