### ISSUE TITLE
Auto pause sync in a Metered Connection

### ISSUE THREAD

**Issue by Jiaocz** [nextcloud/desktop#3519] opened 2021-07-07 03:20 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you want to have the same feature implemented.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Feature description
In Windows 10/11, a connection (like WIFI or something) can be set to Metered connections. [The official link](https://support.microsoft.com/en-us/windows/metered-connections-in-windows-10-7b33928f-a144-b265-97b6-f2e95a87c408?ivk_sa=1024320u) of this kind of connection says that some apps will work differently to reduce data usage. Like onedrive, it will auto pause sync to save data usage. 

So I hope Nextcloud desktop could **auto pause aync in a metered connection**, or user could choice whether to auto pause in settings.

**Comment by camilasan** [comment] 2021-07-07 06:46
Duplicate of #39

**Closed by camilasan** 2021-07-07 06:46 UTC
Labels: enhancement
