### ISSUE TITLE
Please add the ability to set the language of the client

### ISSUE THREAD

**Issue by NekoSilverFox** [nextcloud/desktop#4101] opened 2021-12-20 16:54 UTC
I am using a system version of Mac OS 12 and the system language is Chinese. But after installing the client program, the language of the client is Russian and I can't even use it properly.

I can't find any place where I can set the language of the client program, please let me know if there is such a feature; if not I would like to add the feature to change the language of the client program in a future version

As you can see in the picture below, the language of the client is Russian and not my system language
![image](https://user-images.githubusercontent.com/46406730/146803437-e4e8903f-5395-4b0f-8cc5-3630e163f7d3.png)

**Comment by allexzander** [comment] 2021-12-28 08:41
@NekoSilverFox We do not have any estimate on when we can implement this. You might want to try changing your region to China in mac's Region settings.

**Comment by claell** [comment] 2022-01-03 10:50
Duplicate of #111

**Closed by claell** 2022-01-03 10:50 UTC
Labels: enhancement, feature: :tongue: language l10n and translations
