### ISSUE TITLE
Cant upgrade to 3.1.1

### ISSUE THREAD

**Issue by pilsnerbeer** [nextcloud/desktop#2830] opened 2021-01-17 12:37 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour
Smooth upgrade from 3.0.3 to 3.1.1

### Actual behaviour
Can't upgrade by:
- restarting the app to start update process
- manually downloading 3.1.1 installer and installing it
- uninstalling 3.0.3 and installing 3.1.1 (apparently nextcloud can't be uninstalled, it just sticks around)

OS: Windows 10

**Comment by er-vin** [comment] 2021-01-18 08:15
I'm slightly confused, you mention both 3.0.3 and 3.0.1 as starting point. So which is it?

If everything else fails, you should be able to uninstall by doing the following:
 1. stopping the client
 1. running the uninstaller
 1. manually remove the install folder in case there would be stale files in there
 1. rebooting

**Comment by er-vin** [comment] 2021-01-18 08:16
@allexzander @camilasan I guess this beastie is not completely slain?

**Comment by allexzander** [comment] 2021-01-18 09:10
@er-vin I've tried reproducing it. With no luck under normal conditions. The only case when this may happen is when using different types of installers for the old version vs the new version.  Let's say, the app was installed with MSI, and then the new versions' installer used is an EXE. In this case, we may end up having 2 versions installed - the first one 3.0.3 installed with MSI, and the second one 3.1.1 installed with an .EXE.

@pilsnerbeer By the way, do you by any chance remember if you've used MSI or EXE installer for 3.0.3?

**Comment by pilsnerbeer** [comment] 2021-01-18 10:09
> I'm slightly confused, you mention both 3.0.3 and 3.0.1 as starting point. So which is it?

Sorry, I meant 3.0.3.

>By the way, do you by any chance remember if you've used MSI or EXE installer for 3.0.3?

Considering https://nextcloud.com/install/#install-clients leads to MSI installer now, it must've been MSI. Unless it was different 
for the 3.0.3

I remember having this problem when upgrading to 3.0.3 coming from earlier version. Back then I had in fact two installed nextcloud versions at two different locations but none of them worked. I had to manually remove everything and then install 3.0.3. Of course I didnt expect I would have to do this again and then again with each new update.

**Comment by allexzander** [comment] 2021-01-18 13:03
@pilsnerbeer 

I see. The thing is, we'll be getting rid of .EXE installer soon and will only provide .MSI installer in one of the nearest releases (I am not sure when exactly, but @er-vin can provide more info). Currently, your described case happens for me only if I upgrade via the settings menu inside the app. The installer that gets downloaded is always .EXE even though you may have installed the app through .MSI.  This is a bug and it shouldn't be like that, but, since we are switching to MSI soon, I guess this will be fixed when we remove .EXE installers from the updater storage.

@pilsnerbeer  Did the manual uninstallation work for you? Also, were there 2 versions visible in the "Applications" menu while you were encountering the issue?

I'd like to know all available details about this issue so I'd be able to figure out if this is some other scenario, different from what I've mentioned before. Updating the version installed via MSI to a version that will get installed via EXE and vice versa will always result in this behavior as these 2 installers are incompatible.

Still, this can be a problem for many users who update from 3.0.3 to 3.1.1 via the in-app "Restart and update" button @er-vin .

**Comment by er-vin** [comment] 2021-01-18 13:28
> I see. The thing is, we'll be getting rid of .EXE installer soon and will only provide .MSI installer in one of the nearest releases (I am not sure when exactly, but @er-vin can provide more info).

The plan is to have MSI only for 3.2.0 and up.

> Currently, your described case happens for me only if I upgrade via the settings menu inside the app. The installer that gets downloaded is always .EXE even though you may have installed the app through .MSI.

Yes, that's because only 3.1.0 and up know how to deal with MSI during updates. 3.0.3 and older don't so only setup.exe can be delivered to those clients.

So there's a tiny window when we provided MSI installers for versions which couldn't themselves execute those MSI installs... but it's a bit chicken and egg, we had to make the MSIs before we had the updater learn how to deal with them.

**Comment by pilsnerbeer** [comment] 2021-01-18 17:36
I manually removed Nextcloud (as it could not be uninstalled the classic way) and installed 3.1.1 via the MSI installed. Everything ok, app shows 3.1.1 as current version. it upgraded but it's not picking up any of my current sync'd files & tries to download them again so I'll have to deal with that.


>@pilsnerbeer Did the manual uninstallation work for you? Also, were there 2 versions visible in the "Applications" menu while you were encountering the issue?

This time only 1 version

**Comment by er-vin** [comment] 2021-01-19 07:32
OK, I'll consider it closed then. In any case, despite the trouble I'd like to thank you for being one of the early adopters of MSI. It helps to have people test things.

**Closed by er-vin** 2021-01-19 07:32 UTC
Labels: bug, feature: :inbox_tray: install and update, os: :door: Windows
