### ISSUE TITLE
[Bug]: Finder Intergrations fails silently 

### ISSUE THREAD

**Issue by p-sims** [nextcloud/desktop#6009] opened 2023-08-29 13:40 UTC
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

That said, ever since I updated to 3.5.2 a year ago I've had an issue where the finder intergeneration disappears silently. After boot or restarting nextcloud client finder looks like this:
![](https://user-images.githubusercontent.com/64636731/258636760-48df5231-5135-499b-97c6-96e233f5de9e.png)

However after a while (currently not been able to observe or trigger change) the green ticket disappear and 'nextcloud' submenu in the right click menu disappears. This is annoying but easily worked round by restarting client.

I've proved that sleeping computer doesn't trigger this, but not sure what does. All I can see is that it always happens within a few days.

I've not updated to v3.9.3 and issue still exists.

### Steps to reproduce

1. Launc Nextcloud Client
2. Prove it looks like this in finder and 'Nextcloud' side click menu is present.
![Screenshot 2023-08-27 at 10 17 43](https://github.com/nextcloud/desktop/assets/64636731/94a7592b-c97e-4dc6-811d-1f282f3c2e81)
3. Wait in for unspecified amount of time (a few days is normally enough)
4. Finder intergation will partially fail silently (ticks disappear and right click menu disspears):
![Screenshot 2023-08-27 at 10 17 22](https://github.com/nextcloud/desktop/assets/64636731/c933ffa5-e6e2-4cab-b7a3-5a864c9464e7)

### Expected behavior

Finder intergration should still be working with ticks shown and right click menu looking like this:
![Screenshot 2023-08-29 at 14 32 35](https://github.com/nextcloud/desktop/assets/64636731/7db4091f-6bbc-47b7-804c-8b78440e9b3f)

### Which files are affected by this bug

All files

### Operating system

Mac OS

### Which version of the operating system you are running.

10.14.6

### Package

Appimage

### Nextcloud Server version

24.0.12

### Nextcloud Desktop Client version

3.9.3

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 3.3.6 to 3.4.0)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [X] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Nextcloud Server logs

```shell
N/A
```

### Additional info

Client Logs debug archive are 73mb which is too big up load, but I can share via next cloud if useful

**Comment by p-sims** [comment] 2023-08-29 13:41
I first reported this as a comment on this issue:
https://github.com/nextcloud/desktop/issues/3012

**Comment by jospoortvliet** [comment] 2023-09-26 19:53
I very occasionally see the same, and I've got a debug file on my laptop 🚀 

Will share @mgallien once it has uploaded!

**Comment by JMoVS** [comment] 2023-09-28 13:01
After the last update, I have this bug every other day. Something in the last 1 or 2 releases changed that made that bug appear way mor eoften (or macOS 13.6, either or) - it is very annoying though.

**Comment by jospoortvliet** [comment] 2023-09-28 16:12
Debug log etc (internal share, nc desktop crew has access):
https://cloud.nextcloud.com/index.php/f/7862122

**Comment by limatus** [comment] 2024-02-21 08:17
I can confirm that we encounter the same issue in Windows 11 and Windows 10 (different versions - client and windows; NC 28.0.2.).

**Comment by JMoVS** [comment] 2024-04-22 19:03
This bug is still happening for us very often, many times per day. Is there something we can do to fix this or enable a fix?

**Comment by claucambra** [comment] 2024-11-26 05:22
Since this is a duplicate of #5193 I will close in favour of that, thank you for reporting!

**Closed by claucambra** 2024-11-26 05:22 UTC
Labels: 0. Needs triage
