### ISSUE TITLE
Tray icon squeezed on macOS with dual screen

### ISSUE THREAD

**Issue by tex0l** [nextcloud/desktop#2642] opened 2020-11-16 12:34 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour
The tray icon should always be of the same size.

### Actual behaviour
When using a dual screen on macOS, the icon is sometimes squeezed : 
<img width="340" alt="Capture d’écran 2020-11-16 à 13 27 26" src="https://user-images.githubusercontent.com/7548264/99252797-d64e2c80-280f-11eb-9319-3604a3533e76.png">

It happens on the screen that doesn't have to window in focus.

### Steps to reproduce
1. Have a secondary screen ;
2. Click on a window on a screen ;
3. Look at the Nextcloud tray icon on the other screen

### Client configuration
Client version: 3.0.3

Operating system: 11.0.1, but it happened as well on the latest Catalina version

OS language: French

Installation path of client: /Applications/nextcloud.app

**Comment by msbsh** [comment] 2020-11-18 12:07
Having the same behaviour since updating to Big Sur (11.0.1).

**Comment by mc256** [comment] 2020-11-23 22:56
#2584 
Same issue here. I think it can be fixed by reducing the size of the icon.

**Comment by pakkpl** [comment] 2020-12-29 09:57
Multiple monitors, one is active, other not:
<img width="102" alt="Screenshot 2020-12-29 at 10 55 48" src="https://user-images.githubusercontent.com/13785488/103275449-7af18b80-49c4-11eb-8665-addc10159e77.png">
<img width="99" alt="Screenshot 2020-12-29 at 10 55 56" src="https://user-images.githubusercontent.com/13785488/103275451-7c22b880-49c4-11eb-980b-f4a2a4c520f0.png">

**Comment by elsiehupp** [comment] 2021-01-18 05:52
There is a strong possibility that this is a bug inherited from Qt. If you'd like to see actual movement on this issue, you could provide additional information on [my bug report on the Qt JIRA](https://bugreports.qt.io/browse/QTBUG-90370) or open a related bug report specific to the stretched/squeezed icon.

**Comment by er-vin** [comment] 2021-01-18 08:10
Duplicate of #2584

**Closed by er-vin** 2021-01-18 08:10 UTC
Labels: bug, feature: :cloud: system tray, os: :apple: macOS
