### ISSUE TITLE
[MacOS]The client was terminated unexpectedly when the client was reopened

### ISSUE THREAD

**Issue by isshe** [nextcloud/desktop#674] opened 2018-09-13 12:39 UTC
# [MacOS]The client was terminated unexpectedly when the client was reopened

### Expected behaviour
The client is opened normally

### Actual behaviour
The client was terminated unexpectedly。

### Steps to reproduce
1. Run client
2. Click `settings...` to open the client
![image](https://user-images.githubusercontent.com/13636347/45488103-dca96f80-b792-11e8-9fae-990af5d24c30.png)
3. Close Client UI
![image](https://user-images.githubusercontent.com/13636347/45488177-1f6b4780-b793-11e8-9473-c6a6bcb239db.png)
4. Reopen
![image](https://user-images.githubusercontent.com/13636347/45488210-44f85100-b793-11e8-83be-2d1e2df4abe5.png)

### Client configuration
Client version: `2.5.0 git`
![image](https://user-images.githubusercontent.com/13636347/45488282-8426a200-b793-11e8-86e2-449d50802c78.png)

Operating system: `macOS 10.13.6`

OS language: `English`

Qt version used by client package (Linux only, see also Settings dialog): `5.11`

Installation path of client: `Compiled by myself`

### Appendix
* So, is this bug mentioned in the comments? `I can not sure...`
![image](https://user-images.githubusercontent.com/13636347/45488538-4b3afd00-b794-11e8-8fee-088a1e675f20.png)

thanks ;-)
isshe

**Comment by isshe** [comment] 2018-09-14 02:09
Stable version(2.3.3) does not have this problem.
![image](https://user-images.githubusercontent.com/13636347/45525577-3008d580-b806-11e8-900f-075e7eb2cc02.png)

**Comment by isshe** [comment] 2018-09-14 10:38
Qt5.9.5 does not have this problem.

**Comment by hiiamok** [comment] 2018-12-17 08:14
The crash itself is happening in the following line of `macpreferenceswindow.mm`:
`NSRect frame = view.window.frame;`

It seems like `window` is not there anymore. Or there is a generell problem with the `view`.
The problem is only happening for newer Qt versions (I suspect 5.10+).
Maybe @camilasan has an idea why this happens.

**Comment by yan12125** [comment] 2018-12-17 08:30
This appears to be an issue inherited from owncloud-client https://github.com/owncloud/client/issues/1947

**Comment by hiiamok** [comment] 2018-12-18 15:03
I might found a "workaround". It's working for me, but might raise some other issues (e.g. correct window sizing)

If you comment every line in the `MacPreferencesWindowPrivate::displayPanel` which is accessing the `NSView *view` or `NSRect frame ` and comment every line in the `MacWindow::bringToFront`, the Settings GUI is working normally for me. Sizing is not working as before (since this code part is commented now). Not sure if other issues might come up as well.

**Comment by mgallien** [comment] 2021-06-08 06:56
Can you still reproduce this bug with the latest version ?
If this is fixed, can you close this issue ?

**Closed** 2021-06-09 13:50 UTC
Labels: bug, crash, needs info, os: :apple: macOS
