### ISSUE TITLE
horizontally flipped main dialogue on VirtualBox VM with Windows 10 Pro

### ISSUE THREAD

**Issue by rokkitlawnchair** [nextcloud/desktop#2924] opened 2021-02-11 17:58 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour
The main dialogue gets displayed with correct orientation after clicking the "nextcloud desktop client" **tray icon** and displays the latest synchronization log entries.

### Actual behaviour
The main dialogue gets displayed flipped horizontally and vertically. Characters are missing and the dialogue is blurred.

[screenshot](https://ignion.net/s/NQDaMQ2eMCzKRTc), [screenshot2](https://ignion.net/s/KYFM2bkPe33X5iW)

### Steps to reproduce
1. leftclick the tray icon

### Client configuration
Client version: 

Version 3.1.2stable-Win64 (build 20210128) git-Revision [939826](https://github.com/nextcloud/desktop/commit/9398260fb3742212fb98ee4c2b35c20b45dd9b6d), Qt 5.12.9, OpenSSL 1.1.1g  21 Apr 2020

Operating System:
Debian 10 Buster (4.19.0-14-amd64 #1 SMP Debian 4.19.171-2 (2021-01-30) x86_64 GNU/Linux)

Virtualization:
virtualbox-6.1/unknown,now 6.1.18-142142~Debian~buster amd64 (https://download.virtualbox.org/virtualbox/debian buster contrib)
Oracle VM VirtualBox Guest Additions 6.1.16
Graphics Controller: VboxSVGA with 3D Acceleration enabled

Virtual Machine Operating system:
Windows 10 Pro 64 Bit (clean install, no additional software)
20H2
Build: 19042.804
Windows Feature Experience Pack: 120.2212.551.0
OS language: German

Installation path of client in VM:
C:\Program Files\Nextcloud

### Logs
I haven't found any log entries related to GUI interaction between the nextcloud desktop client and Windows. I will provide the logs if necessary.

**Comment by er-vin** [comment] 2021-02-12 08:22
Duplicate of #2399

**Closed by er-vin** 2021-02-12 08:22 UTC
