### ISSUE TITLE
The try icon of nextcloud client is shown up side down and flipped

### ISSUE THREAD

**Issue by SomeStrangeName** [nextcloud/desktop#2743] opened 2020-12-19 15:57 UTC
I am running nextcloud client version Nextcloud-3.1.0-x64 inside Windows 10 Home inside a Virtual Box 6.1 instance.

The try dialog is show up side down (my system locales are German).
I can't see any locale settings and could not found any related issue yet - does someone else have this?

![issue](https://user-images.githubusercontent.com/19815019/102693472-24918980-421b-11eb-8348-6b0ccf24df56.png)

I removed some data by cutting it out so the white boxes are because of this.
Looks like the words are also somehow flipped.

So seems to be rotated by 180° and inverted.

Also the version before looked like this and a re-installation of the client was not fixing this.

**Comment by er-vin** [comment] 2020-12-21 07:23
Yes, this is some duplicate of an issue which got reported a while back when 3.0.0 went out. It turns out this is an issue in the gpu drivers in virtual box and how they interact with the drivers of the host. Disabling 3D acceleration for that VM should be enough to workaround the issue. We can't do much about it unfortunately.

**Closed by er-vin** 2020-12-21 07:23 UTC
