### ISSUE TITLE
MacOS Virtual File (Experimental) - Image Preview

### ISSUE THREAD

**Issue by snowwolf3388** [nextcloud/desktop#4335] opened 2022-03-05 15:45 UTC
### Feature description
Tell us how the feature should work

It would be really nice to be able to preview images that are virtual in both the Windows and Mac Desktop Clients. I would be happy to store a decent size local cache along side my installation for this feature. If there is a concern that not everyone wants this, it could be another option in the Nextcloud Context menu in Windows Explorer and Mac Finder below "Make always available locally" and "Free up local space". We could add a "load image previews for this folder" button, which starts the server generating those thumbnails for just that one folder. Might be easier to chunk it off like that in small sections on demand rather than just automatically forcing the implementation server-wide. Finally, I'm sure a "clear Virtual File preview local cache" button would be nice for people to be able to clear up space and start over if they have loaded a lot of previews over time (again, probably only an issue for very large data stores).

**Comment by PhilippSchlesinger** [comment] 2022-03-10 10:12
for Windows see https://github.com/nextcloud/desktop/issues/3407

**Comment by HeyWatchOutDude** [comment] 2022-04-29 18:08
Do it like on the iOS App (Disable local caching) - image previews are still generated.

**Comment by kelke** [comment] 2022-09-16 12:11
I would also love this feature. Searching for a single photo in a large folder is currently almost impossible without downloading the entire folder, or reverting to the browser.

**Comment by PhilippSchlesinger** [comment] 2023-04-14 11:12
@rakekniven 
see issue https://github.com/nextcloud/desktop/issues/1337 for details on FileProvider API (VFS) in macOS.
A build is linked in the announcement comment https://github.com/nextcloud/desktop/issues/1337#issuecomment-1478386641.
Development takes place in PR https://github.com/nextcloud/desktop/pull/5527.

**Comment by claucambra** [comment] 2023-08-16 04:03
This is implemented in the new VFS implementation using FileProvider. Closing :)

**Closed by claucambra** 2023-08-16 04:03 UTC
Labels: enhancement

**Comment by mgallien** [comment] 2023-08-18 08:40
@rakekniven my understanding is that we tried to release it already but due to bugs being detected at release candidate stage, we had to delay its availability
I cannot promise anything right now as we may still find other release blockers despite the good work of @claucambra

**Comment by robermad1986** [comment] 2023-08-20 17:33
I am very happy to see progress on this issue. Recently aquired a macbook and I feel the lack of this function. 
I also found kinda tricky to activate the experimental features that lead to the Virtual File System, but I got it now.
Please keep the work up. Big thanks to everyone who is involved on this. 
Special thanks to @claucambra @mgallien @snowwolf3388

**Comment by JensVanhooydonck** [comment] 2023-11-01 14:47
> Hello @mgallien @claucambra Do you have any update for the community? And me? :-)

Can be enabled by enabling `showExperimentalOptions=true` in this config file: [https://docs.nextcloud.com/desktop/3.2/advancedusage.html#configuration-file](https://docs.nextcloud.com/desktop/3.2/advancedusage.html#configuration-file)

**Comment by claucambra** [comment] 2023-11-13 07:05
> Hello @mgallien @claucambra Do you have any update for the community? And me? :-)

Currently working on the configuration interface for the file provider stuff. Once this is done and we iron out a few kinks with initial sync, we'll be rolling out a proper release with this fature :)

**Comment by Grongrilla** [comment] 2025-05-05 15:04
@claucambra Stumbled upon this issue while searching on if and when this feature will be available. Could you give an update on the current status? The issue is closed, but I don't see an option in my desktop client
