### ISSUE TITLE
Client autostarting maximized in Gnome and Cinnamon

### ISSUE THREAD

**Issue by JanKrAppel** [nextcloud/desktop#99] opened 2017-12-21 13:41 UTC
I've installed the Nextcloud client via the PPA. I set it up and selected it to start at system startup. After I log on, the client sometimes appears maximized, without a system tray icon. This does not happen on every startup, although I don't change my setup in between. To me, the expected behaviour would be to always autostart the client with just a system tray icon.

* Nextcloud client: 2.3.2 from the PPA
* OS:
  * System 1:
    * Debian stretch, Cinnamon 3.2.7
  * System 2 and 3:
    * Debian buster, Gnome Shell 3.26

I have been able to reproduce this issue both using Xorg and Wayland. If any more information is required, I'd be happy to provide it.

(Edited to fix Markdown)

**Comment by JanKrAppel** [comment] 2018-01-03 15:03
Update: I've since observed the same behaviour on KDE Plasma 5.10.5.

**Comment by raneon** [comment] 2018-02-07 15:52
I have this issue as well. After starting Plasma-Wayland the Nextcloud-Client window will be shown, as auto start is activated. But I would expect that the Nextcloud-Client appears only in the task bar, like on X11.

Is this a bug of Nextcloud-Client or Plasma-Wayland?

Tested with Nextcloud-Client 2.3.3 git revision 57bc79 and Plasma 5.12.

**Comment by JanKrAppel** [comment] 2018-02-07 15:54
> Is this a bug of Nextcloud-Client or Plasma-Wayland?

I believe it can't be a Plasma bug, since I have also observed it on Gnome Shell and Cinnamon. It could probably still be a bug in some other part of the windowing system. I filed it against Nextcloud because that's the only software I use that shows this behaviour.

**Comment by raneon** [comment] 2018-02-07 20:04
According to this bug report https://bugs.kde.org/show_bug.cgi?id=390013 it is the task of the application to start correctly to tray. So I think it is a bug in Nextcloud-Client when running on Plasma-Wayland.

**Comment by samtygier** [comment] 2018-02-24 11:08
Also in Fedora 27 GNOME3 with nextcloud-client-2.3.3-2.fc27.x86_64

If I close the main nextcloud window there is no way to get it back and no tray icon.

**Comment by fredrikekelund** [comment] 2018-03-21 14:01
#105 seems to be a possible duplicate

**Comment by JanKrAppel** [comment] 2018-03-26 06:56
As suggested in #105, delaying Nextcloud start seems to solve the issue on Cinnamon, although the Nextcloud tray icon does not always show. `ps` confirms Nextcloud is running, though.

I have yet to test it on KDE, and the Gnome installation mentioned in my initial report is no longer accessible to me.

**Comment by toxiclung** [comment] 2018-04-03 12:12
+1

**Comment by kernel23** [comment] 2018-06-16 17:38
Any news ?

**Comment by DudleyDursley** [comment] 2018-08-31 07:58
Same here (Fedora 28, GNOME3), though at the moment I would consider this a feature and not a bug. Starting the client in the background (as it normally should) would be a problem unless [#203](https://github.com/nextcloud/desktop/issues/203) is fixed first.

**Comment by shtrom** [comment] 2018-08-31 10:05
Actually, this doesn't happen to me anymore with the AppImage [Version 2.5.0daily (build 20180701), install from AUR)]

**Comment by ukos-git** [comment] 2019-09-17 13:39
I am using `2.5.1git` and nextcloud client *always* pops up a window after system start which is pretty unnecessary for a sync  client that can already [push important notifications](https://help.gnome.org/users/gnome-help/stable/shell-notifications.html.en) to the system anyway.

GNOME Shell `3.30.2` on debian 10 running x11

**Comment by kenogo** [comment] 2019-10-03 15:18
This issue still isn't fixed, but there are two workarounds. The first one is to install the AppIndicator GNOME shell extension (but I don't want to do this because I don't like app icons). So I came up with [this workaround](https://gitlab.com/snippets/1900741). It's quite a hack but it works: It's a script that launches nextcloud, grabs the PID, uses xdotool to enter a while loop to search for a window corresponding to the PID, and finally closes the window.

It should be noted that you probably should modify the while loop a bit to exit after a specified number of counts, in case something goes wrong and the nextcloud settings window doesn't open up, so that you don't enter an infinite loop. I might edit that later.

**Comment by rasmus91** [comment] 2019-10-08 08:35
This also happens on elementary OS

**Comment by mrclrchtr** [comment] 2019-10-11 18:46
Any news?

**Comment by minfaer** [comment] 2019-11-17 14:21
> This issue still isn't fixed, but there are two workarounds.
I found the nextcloud client sports an option to start in the background since version 2.5.2. Just add --background to the Exec key in the corresponding .desktop file in ~/.config/autostart .
For me:
`Exec=/usr/bin/nextcloud --background`

**Comment by bmhorn** [comment] 2020-03-28 09:57
> I found the nextcloud client sports an option to start in the background since version 2.5.2. Just add --background to the Exec key in the corresponding .desktop file in ~/.config/autostart .
> For me:
> `Exec=/usr/bin/nextcloud --background`

Thank you for sharing this. I would propose this to be the default configuration.

**Comment by joshtrichards** [comment] 2023-11-27 13:39
Fixed in #2055

**Closed by joshtrichards** 2023-11-27 13:39 UTC
Labels: enhancement, os: :penguin: Linux
