### ISSUE TITLE
Nextcloud client 2.6.4. Mac, login not possible

### ISSUE THREAD

**Issue by criro** [nextcloud/desktop#1925] opened 2020-04-14 11:39 UTC
Hello,
I am using Nextcloud 2.6.4 on a Macbook Air, german OS with latest Catalina 10.15.4.
When trying to log in, the login-Window is not displayed properly, there is just a “blue line” displayed, as shown in the screenshot.
So it is not possible to enter the username and password.
Any ideas??
(I could solve it using 2.5.3 for log in and then updating to 2.6.4)
Here a link to a screenshot of the window:
https://rcn.owncube.com/index.php/s/K5rjnZMzBDfZ34Y

**Comment by criro** [comment] 2020-04-14 11:43
Sorry, I didn't see this issue that describes the same problem:
https://github.com/nextcloud/desktop/issues/1924

**Comment by jonatansteller** [comment] 2020-04-14 12:23
There is a previous bug report on the same issue that is already triaged: https://github.com/nextcloud/desktop/issues/1888

**Comment by criro** [comment] 2020-04-14 13:13
ok, is there a way to delete the issue? I didn' find it...

**Comment by jonatansteller** [comment] 2020-04-14 14:06
> ok, is there a way to delete the issue? I didn' find it...

I think you need to be a collaborator on the repository to close issues, so I guess someone else will have to do it. I've added another bug report from February in the above comment. Let's hope the issue'll be resolved soon 🤞

**Comment by claell** [comment] 2020-04-16 10:02
Thanks for pointing out the duplicates. There is no need to delete this issue, it can just be closed. @jonatansteller btw: closing should also be working for the issue author.

**Comment by claell** [comment] 2020-04-16 10:02
Duplicate of #1793

**Closed by claell** 2020-04-16 10:02 UTC
Labels: bug, feature: :key: authentication, os: :apple: macOS, regression
