### ISSUE TITLE
Desktop 3.1 | Can't add a new account

### ISSUE THREAD

**Issue by Lars1963** [nextcloud/desktop#2736] opened 2020-12-17 07:06 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour
Adding new account should be possibile

### Actual behaviour
`+ Konto hinzufügen` closes immediately on clicking. Therefore adding a new account is not possible

![Unbenannt](https://user-images.githubusercontent.com/45886938/102454777-d0ca4900-403e-11eb-8408-8e759439d7d2.png)

### Client configuration
Client version: 3.1.0 MSI

Operating system:
Windows 10

OS language:
German

Nextcloud version: 2.04 installed on Debian 10.7

**Comment by er-vin** [comment] 2020-12-17 08:08
Duplicate of #2706

**Closed by er-vin** 2020-12-17 08:08 UTC
