### ISSUE TITLE
Deletion/Renaming of encrypted folders

### ISSUE THREAD

**Issue by gerion0** [nextcloud/desktop#2882] opened 2021-01-28 12:59 UTC
### Expected behaviour
I'm just tried to use E2E on the desktop client.
I wanted to encrypt an existing folder, let's name it `bar`.
First thing, I have discovered that only empty folder can be encrypted.
So I created an empty folder `foo`, encrypted it, moved my data from `bar` to `foo` and waited for synchronisation.
Then I deleted `bar` and renamed `foo` to `bar`.

My expected behaviour is that this works.

### Actual behaviour
The client reports: "DELETE https://mycloud/.../foo is not allowed on the server" and does not recover.
Multiple resynchronisations do not help. The `foo` folder is not resynced.
Only way for me was to delete all files in `foo` on my smartphone, unflag `foo` as encrypted, then delete `foo`.

### Steps to reproduce
1. Create empty folder.
2. Mark as encrypted.
3. Delete it on the disk.
4. Wait for the client to synchronize.

### Client configuration
Client version: 3.1.1.

Operating system: Gentoo Linux

OS language: German

Qt version used by client package (Linux only, see also Settings dialog): 5.15.2

Client package (From Nextcloud or distro) (Linux only): distro

Installation path of client: Various

### Server configuration

Nextcloud version: 20.0.6

Storage backend (external storage):

### Additional
Suggestion: Please enable either renaming of encrypted folders (is there a conceptual reason, why this does not work?) or resynchronize the folder in this case so the server/client is consistent. Maybe it is also possible, to catch this special case and display a warning like this: "Warning: You tried to delete (or rename) an encrypted folder. This is not possible currently, resyncing..."

**Comment by er-vin** [comment] 2021-01-28 14:14
Duplicate of #2342

**Closed by er-vin** 2021-01-28 14:14 UTC
