### ISSUE TITLE
Issues with special chars on Windows and other operating systems

### ISSUE THREAD

**Issue by fabianfrz** [nextcloud/desktop#464] opened 2018-07-01 08:45 UTC
The sync client may have issues with special chars like ":" on Windows. The character is perfectly valid on Linux/BSD systems and allowed by all file systems I know.

The sync client may respect OS limitations in file names by renaming them locally on Windows clients:

For reference - see: opnsense/core#2498

File name template I use in OPNsense for config files: config-&lt;Hostname&gt;.&lt;Domain Name&gt;-&lt;Date&gt;_&lt;Time&gt;.xml

Currently there seems to be no error message on Windows for this, see #1723.

**Comment by TwiggyWan** [comment] 2020-08-25 13:03
> there will be always one OS that causes troubles and sometimes you do not even know that os
What does that mean? doesn't this project support a finite list of OSes?

Where is it written what characters are forbidden on the server?
I create a demo instance, go in the brower to create a file : 
![opera_2020-08-25_14-58-03](https://user-images.githubusercontent.com/5596799/91177108-8c0f5080-e6e3-11ea-8a73-ab1593089588.png)
Okay, slashes forbidden, that makes sense.

but now i create 'test\iss'(or 'test\\iss', same behavior), i do not get the same pop up telling me the file can't be named that way, but i get an error : 
![opera_2020-08-25_15-00-27](https://user-images.githubusercontent.com/5596799/91177267-bc56ef00-e6e3-11ea-91b5-dd8df24aa16a.png)

So this file name should be legit because it is legit on linux but is somehow forbidden on the server already, when 'test:iss' is allowed. What gives?

**Comment by Aldaris1985** [comment] 2020-08-27 03:51
Maybe just one thing to add which I mentioned in #1723 : the issue is also that those forbidden characters are not properly reported. At least in the past version, files with the forbidden character had been ignored but the sync was shown as successful (please have a look at the issue, the log file is there). Although it is visible in the log files but which user apart from us freaks is digging through that? ;) It would be very helpful to point non-synced filed clearly to the user including the ones not synced due to forbidden character.

**Comment by fabianfrz** [comment] 2020-08-28 21:25
@TwiggyWan you can use NextCloud with any operating system, that has a working TCP stack and supports http. That means that there are also operating systems like OS/2 (for example used at ATMs), FreeDOS (yes that supports networking), Symbian (old nokia phone OS), Tizen (for example used on smart TV), and much more.

All of them can upload files but the sync client needs to be able to handle all of them.  Also if there are users of different countries, you might have even some special characters in the file name. Maybe you have a Chinese filename and want to write that to a file system that is not Unicode capable. The only system that has that information is the host running the sync client.

**Comment by TwiggyWan** [comment] 2020-08-29 16:21
Okay. AFAIK there is a notion of server capabilities in case of a sync up but nothing regarding client capability in case of a sync down : 
https://github.com/nextcloud/desktop/blob/78fa448c7eb34f35099e8b9140c4f1b60124c089/src/libsync/syncengine.cpp#L1094

And this is probably why there is no error message given to the user in #1723 as the error seems to be raised only for sync up.

According to what is in place, there is no notion of replacing characters valid on the client and invalid on the server, the sync just fails. What you suggested above @fabianfrz would mean that for sync down, we would perform renaming, but not for sync up. Wouldn't that just be confusing for the users?

**Comment by fabianfrz** [comment] 2020-09-02 19:18
@TwiggyWan in case of sync up I think this can be handled under the hood by the server. Nobody says that the filename on the real file system must match the one stored on disk. For example the server running on windows could just accept a file called test:file.txt, store it as {b0693f9e-9ea8-4886-8c57-7823cd564677} and in the directory listing and on access it can offer it as test:file.txt again. Usually the servers are running on Linux or BSD so usually they have some modern file systems that can handle strange file names. In general, there should be anything allowed that is compliant to the WebDAV standard and any common operating system (no file you can create on Linux, Windows or Mac OS should be rejected because of the file name).

**Comment by claell** [comment] 2020-09-18 13:08
I edited the description to reflect what @Aldaris1985 mentioned (no error message on Windows - #1723).

Also changed the title, since this issue seems to be treated like some meta issue now for any special character related problems on any operating system. I'd rather suggest not to do that, since the underlying problems might be pretty different, but for now at least the title correctly reflects again what this issue is about (now).

Also added the labels high (because there is no notificaiton of a failed sync on Windows in that case) and technical debt (since dealing with special characters should have been done directly when implementing, not afterwards).

**Comment by Githopp192** [comment] 2020-12-02 10:09
When i downloaded those Files with COLON ":" directly from the NC-Web Gui - Nextcloud did a rename in that Nextcloud Web Gui did replace the ":" (Colon) with "_" (underscore).

The question is ..why not to trigger this behave to the Agent also ?

(in my case Level 1 should had do the job --> replace ":" with "_" on the iPhone App Level)

At least - as this is not fixed - the Nextcloud Agent on Windows (or anywhere else) should report an Error.

(as **claell** also already commented)

But this will not happen - Windows Agent is ok - so the users will not be aware of that issue and this could be risk, if users or applicatioin will expect those files properly synchronized.

**Comment by fabianfrz** [comment] 2020-12-06 20:46
@Githopp192 this is not done by nextcloud. This is behaviour by for example Firefox.

**Comment by Githopp192** [comment] 2020-12-07 09:51
Thx Fiabanfrz .. yes ..this could be true. In my case it is MS Edge

**Comment by k9t9** [comment] 2021-01-05 04:10
Reported a similar problem ( trailing DOT - e.g. "`.` " about a year ago - but was reported on server repo 

nextcloud/server#18066

At the moment I installed the latest release yesterday - and now have also problem with HASH symbol - e.g. `#` 

A folder name like `#SYNCH#` created on the server will be synched like `SYNCH` ( hash characters stripped ) and if created or existing on local - will be ignored . ( win 10 - client 3.1.1-x64 )

By the look of the other open issues - there seems to be some problems with all kind of characters like HASH `#` , DOT `.` WHITESPACE ` ` etc..

**Comment by Pit-Storm** [comment] 2021-03-25 21:15
I had a related behaviour with a file valid on iOS but not synching to windows client. It is really confusing, that there is no message shown by the sync client showing that some file(s) hadn't been synced...

A notification should basically be implemented. So UX is been guaranteed and you are winning time to implement a overall solution. (My opinion as a private user :-) )

Thanks for that very cool product!

**Comment by claell** [comment] 2021-11-24 10:05
Please don't forget to vote on the issue description to make this more prominent.

**Comment by PhilippSchlesinger** [comment] 2022-03-11 10:14
@claell, @FlexW
is https://github.com/nextcloud/desktop/issues/3991 indeed a duplicate of this bug?

Since there is a resolution dialog for invalid filenames (https://github.com/nextcloud/desktop/pull/3760), I get warnings on every new clients release for hundrets of filenames containing invalid chars (":", ",", "?", ...) as my mother tried to use filenames to describe image content in full sentences ;-)
**But** after resolving only a few of the listed filename problems, the list of problems disappears after the next sync even if there would be lots of remaining invalid filenames.

I'd be happy to provide more info or logs if needed.

**Comment by labor4** [comment] 2022-04-28 14:52
**Note on the colon on Macos**
":" are illegal on the Macos GUI and prevented from entering, but valid on the Shell (Terminal)
Putting a ":" in Terminal will result in a "/" in the GUI.
Putting a "/" in GUI will result in a ":" in the Terminal.
It may be an inconsitency in iOS to allow entering ":" in iOS GUI.
Background:
Macos GUI use**D** ":" to communicate path-delimiters
Macos Terminal use**S** "/" to communicate path-delimiters (as in Linux)
... I could not find a way to enter "/", as in `touch oh\/dear.txt`, in Macos Terminal.

**Note on combining diaeresis (Umlauts)**
Further in "Macos Char weirdnesss" I place here a char-related note on 
"Macos construction of a dual-characters for Umlauts", also present in other "accents" like in "é",
because the specific reason for it proofed hard to find on the net.
It may be though, that this is only present in older filenames (from older Macos'es), 
as I could not reconstruct it in Macos Mojave (10.14).
**If some Umlaut files cannot be grabbed, it may be for that reason!**

[https://superuser.com/a/1196604](https://superuser.com/a/1196604)

**Comment by mgallien** [comment] 2022-12-14 08:36
@tobiasKaminsky

**Comment by FernandoMarques-Santos** [comment] 2023-01-10 12:57
Since any solution above is not acceptable in every scenario and may cause headaches, we may give each user a choice via user configuration: say, under settings/user/sync-clients ('Mobile & Desktop' config page). Then inside we have these checkboxes:

- [ ] Compatibility sync: automatically renames files with illegal characters for Windows on the Server side.
- [ ] Send a notification when a rename is triggered

A simple script in a workflow-like rule may rename these files when they arrive.

**Comment by sm18lr88** [comment] 2023-01-25 19:07
I keep getting sync errors for my second NTFS partition in Windows 11, because of a hidden folder named $Recycle.bin

I'd appreciate this being solved and not constantly seeing a sync error.

**Comment by mgallien** [comment] 2023-06-15 08:05
related PRs
https://github.com/nextcloud/desktop/pull/5783
https://github.com/nextcloud/desktop/pull/5232
https://github.com/nextcloud/desktop/pull/4454
https://github.com/nextcloud/desktop/pull/5801

this cover invalid characters that would be refused by the server and handling of leading/trailing spaces and case clash conflicts
we are still missing a way to download on windows files with invalid names (as far as windows is concerned) and rename them directly from desktop client

**Comment by mgallien** [comment] 2023-06-15 10:07
I am closing this one as we may not want to download files with invalid characters in their name and substitute those invalid characters as it would be hard to make this work in every corner cases
alternatively we want to enable the user to rename them
if someone wants to not rename them, windows clients can be configured to ignore those files with invalid names

**Comment by Githopp192** [comment] 2023-06-15 10:11
@mgallien : as i wrote once : 

at least - the Agent should report an error.

Because, if the agent does not report an error - the user isn't aware of it.

**Comment by Githopp192** [comment] 2023-06-15 12:14
All of those has to do with "data consistency" (Error Reporting). At the end this means:

1.) Desktop Agents Reports reports an error
2.) Desktop Agent does NOT SHOW GREEN STATUS !

**Closed** 2023-06-15 12:36 UTC
Labels: bug, high, technical debt, discussion, feature: :arrows_counterclockwise: sync engine, approved
