### ISSUE TITLE
[Bug]: Don't ring when "do not disturb"

### ISSUE THREAD

**Issue by PVince81** [nextcloud/desktop#4639] opened 2022-06-14 13:03 UTC
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

Desktop client rings audibly and shows the popup despite my status being "do not disturb".

### Steps to reproduce

1. Set self to "do not disturb"
2. Have someone start a call in a group chat

### Expected behavior

No ringing, just leave me alone!

### Which files are affected by this bug

N/A

### Operating system

Linux

### Which version of the operating system you are running.

openSUSE Tumbleweed 20220602

### Package

Distro package manager

### Nextcloud Server version

24.0.1

### Nextcloud Desktop Client version

3.5.1

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 3.3.6 to 3.4.0)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by claucambra** [comment] 2022-06-15 10:18
Hi @PVince81 this is a duplicate of #4607 and was fixed with #4611 so I will close, but thanks for reporting :)

**Closed by claucambra** 2022-06-15 10:18 UTC
Labels: 0. Needs triage
