### ISSUE TITLE
Nextcloud Desktop Linux 3.1 - Can't add account from main view

### ISSUE THREAD

**Issue by aslmx** [nextcloud/desktop#2744] opened 2020-12-19 18:08 UTC
### Expected behaviour
When i click the "+" Icon in the account chooser of the main view in Nextcloud desktop (under all available accounts), i expect the add account dialog to open.

### Actual behaviour
Nothing happens.

But the add account dialog is available via the Tray Notification icon context menu - at least.

### Steps to reproduce
1. Click on Nextcloud Desktop Tray icon - Nextcloud Popup-Window with overview opens
2. Click on used account to open account list - Account list expands and shows "+ Add Account"
3. Cilck on "+ Add Account - nothing happens

### Client configuration
Client version: 3.1 

Operating system: Linux Mint 20, XFCE edition

OS language: English

Qt version used by client package (Linux only, see also Settings dialog): apparently not shown on settings dialog :(

Client package (From Nextcloud or distro) (Linux only):  from nextcloud-devs PPA

Installation path of client: /usr/bin/nextcloud

### Server configuration
I would guess irrelevant here. If necessary I will share it upon request.

**Comment by er-vin** [comment] 2020-12-21 07:21
Duplicate of #2706. Workaround for now is to open the settings dialog at least once first. Fix for this will be delivered with 3.1.1 in the next few days.

**Closed** 2021-01-27 15:46 UTC
