### ISSUE TITLE
[2.5.3] nextcloud-client: std::__atomic_base<QMutexData*>::compare_exchange_strong(): nextcloud killed by SIGSEGV

### ISSUE THREAD

**Issue by Germano0** [nextcloud/desktop#1218] opened 2019-04-23 13:51 UTC
Fedora nextcloud-client maintainer here. This is an upstream clone of bugreport https://bugzilla.redhat.com/show_bug.cgi?id=1702290

### Actual behaviour
Client crash

Qt version used by client package (Linux only, see also Settings dialog):
Should be 5.11.3

Client package (From Nextcloud or distro) (Linux only):
nextcloud-client-2.5.2-1.fc29

Operating system:
Fedora 29

### Logs

Backtrace
https://gist.github.com/Germano0/c9417f97bc70fb4b5d1646957c9f09a2

**Comment by camilasan** [comment] 2019-05-08 18:29
Do you have the same with 2.5.3rc1?

**Comment by Germano0** [comment] 2019-05-08 18:37
> Do you have the same with 2.5.3rc1?

I am not the affected person. The Fedora bugreport was opened by another user. As soon 2.5.3 will be released we can ask him. I don't have the time to package the release candidate

**Comment by mr700** [comment] 2019-05-30 12:46
I got here from https://bugzilla.redhat.com/show_bug.cgi?id=1689109 , which was identified as duplicate of my problem. I have nextcloud-client-2.5.2-2.fc29.x86_64. In my case I changed the web server name and was trying to find a way to edit the account (url to the server). While clicking around I got segmentation fault in std::__atomic_base<QMutexData*>::compare_exchange_strong ...

**Comment by Germano0** [comment] 2019-09-24 09:06
2.5.3 is affected too

**Comment by janvlug** [comment] 2019-12-23 12:48
This just happened also on version 2.6.1git on Fedora 31 for me.

**Comment by claucambra** [comment] 2022-09-09 14:16
Hi, since it has been a long time since this bug was opened I will close. If this is still reproducible in the latest version of the client please reopen

**Closed by claucambra** 2022-09-09 14:16 UTC
Labels: 0. Needs triage
