### ISSUE TITLE
Feature request: Dark mode for windows client

### ISSUE THREAD

**Issue by CountOmega** [nextcloud/desktop#1914] opened 2020-04-08 12:09 UTC
Hi all,
I´m really enjoying NC itself and also the client. Keep up the great work. You guys are awesome. As the title says, I´d like a dark mode for the windows sync client. Maybe you could make this feature dependent on the Windows Settings of the app mode (dark/light).

**Comment by claell** [comment] 2020-04-08 19:16
@CountOmega There has already been an issue for macOS that I now edited to cover nextcloud in general: #1287
There is a PR that will implement the requested functionality: #1439. So I guess we can close this as duplicate. Feel free to reopen if you think otherwise.

**Comment by claell** [comment] 2020-04-08 19:17
Duplicate of #1287

**Closed** 2020-04-08 19:17 UTC
Labels: design, feature-request
