### ISSUE TITLE
Suggestion/improvement: Placeholder files for un-synced folders

### ISSUE THREAD

**Issue by Yournished** [nextcloud/desktop#1048] opened 2019-01-28 19:13 UTC
Currently it's possible to do selective sync in each client, which is great because not every machine may have enough space to sync the entire account or it may not be practical due to bandwidth constraints.

However, an issue is that if you mark a folder or file deep inside a complex folder hierarchy to not be synced, you can forget that the folder exists but isn't synced, and mistakenly try to create one with the same name. Granted, Nextcloud handles conflicts somewhat gracefully so accidental name collision is not a huge problem. Knowing at a glance that "X folder doesn't exist" as opposed to "X folder exists, but I remember that I marked it not synced" is not as easily solved, unless your memory is good or your data not complex.

As a solution, I suggest the following: When a file or folder is marked as "not synced", it is replaced with a placeholder file that has the same name and contains a note like "This is a placeholder file, do not edit or delete." The client then knows to ignore files that contain this note instead of trying to sync them. But the use is informed about the presence of unsynced file folders by their placeholders, and is prevented from creating conflicts because their OS will prevent them from creating files or folders with duplicated names.

**Comment by meichthys** [comment] 2020-08-24 02:53
@Yournished could we close this in favor of #184 ?

**Comment by er-vin** [comment] 2020-08-31 09:26
Yes, looks like a duplicate of #184 indeed.

**Closed by er-vin** 2020-08-31 09:26 UTC
