### ISSUE TITLE
Electron wrapper for Nextcloud Talk

### ISSUE THREAD

**Issue by HammyHavoc** [nextcloud/desktop#127] opened 2018-01-17 20:24 UTC
Hey all,

Seems like one of the final things left from making Nextcloud the go-to solution for most enterprise situations is a lack of a desktop app for Nextcloud Talk that could integrate with native notifications. Using it in the browser is fine, but having a dedicated app ala RocketChat is definitely useful.

Anything on the roadmap for this? If not, would be interested in getting involved.

**Comment by jancborchardt** [comment] 2018-02-02 17:45
@HammyHavoc I don’t think that’s on the roadmap. Would be very cool if you want to get involved – best join the #nextcloud-talk IRC channel. :) also cc @nextcloud/talk

**Comment by nathanael-h** [comment] 2020-04-22 13:40
Hello @HammyHavoc this issue is quite old, but you could be interesting in looking at this https://github.com/fds2610/NCT-Desktop/ : someone started a Nextcloud Talk notification app for desktop. 

Maybe we could also close this one, I think it is a duplicate of https://github.com/nextcloud/spreed/issues/1100

**Comment by nathanael-h** [comment] 2020-10-24 20:52
Just found this repo today, but didn't try: https://github.com/indev29/nextcloud-talk-desktop

**Comment by jancborchardt** [comment] 2024-03-19 10:04
In case you haven’t seen it yet: There is a repository and releases for a Nextcloud Talk desktop app since some time now, so closing this :)
https://github.com/nextcloud/talk-desktop/

**Closed by jancborchardt** 2024-03-19 10:04 UTC
Labels: enhancement, feature-request
