### ISSUE TITLE
STOP using Apple Keychain for Nextcloud instance passwords wtf

### ISSUE THREAD

**Issue by Oclair** [nextcloud/desktop#2768] opened 2020-12-24 16:59 UTC
You guys use the Mac OS keychain to store Nextcloud instance credentials for your Desktop app on mac os, this is WRONG dont do it.
nuff said
Have a nice day!
Oclair

### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Steps to reproduce
1.
2.
3.

### Client configuration
Client version:

Operating system:

OS language:

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From Nextcloud or distro) (Linux only):

Installation path of client:

### Server configuration

Nextcloud version:

Storage backend (external storage):

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile: 

Output of `nextcloud --logdebug --logwindow` or `nextcloud --logdebug --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the Nextcloud directory)
(See also https://docs.nextcloud.com/desktop/2.3/troubleshooting.html#log-files)

2. Web server error log:

3. Server logfile: nextcloud log (data/nextcloud.log):

**Comment by kesselb** [comment] 2020-12-25 23:08
Is this another report for https://github.com/nextcloud/desktop/issues/1732?

https://github.com/frankosterfeld/qtkeychain is used to store the credentials. Why should we use something different to store the credentials?

> Your iCloud Keychain is encrypted when transmitted to your devices and when stored in iCloud, and cannot be read by Apple.

https://support.apple.com/en-us/HT210689. That might be true or false. I'm not able to judge but Apple is actually known for taking privacy serious. 

I don't think that a custom store for the credentials is on the roadmap. Perhaps @er-vin or @camilasan can tell you.

**Comment by er-vin** [comment] 2020-12-28 08:33
Nope, not on the roadmap. Also clearly a duplicate of #1732 so closing as such.

**Closed by er-vin** 2020-12-28 08:33 UTC
Labels: 0. Needs triage, discussion, needs info
