### ISSUE TITLE
[Bug]: Nextcloud.exe can‘t start properly, Exception code: 0xc0000005, Error Module Name: nextcloud_csync.dll

### ISSUE THREAD

**Issue by c9yydm** [nextcloud/desktop#7235] opened 2024-09-28 11:38 UTC
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

I can successfully complete the configuration and compilation, and generate the nextcloud.exe, but the startup app crashes,the following table describes the log viewing results:
Error App Name: nextcloud.exe, Version: 3.14.0.0, Timestamp: 0x66f68a74
Error Module Name: nextcloud_csync.dll, Version: 0.0.0.0, Timestamp: 0x66f68725
Exception code: 0xc0000005
Error Offset: 0x000000000007f560
Error Process ID: 0x473c
Error App Startup Time: 0x01db1199d7eb1add
Error application path: D:\InstantMessage\desktop\build\bin\nextcloud.exe
Error module path: D:\InstantMessage\desktop\build\bin\nextcloud_csync.dll
Report ID: 8dfad012-7af8-4569-9d3d-e42d84330285
Full name of the error package: 
Error Package Relative Application ID: 

### Steps to reproduce

1. Follow the steps on the URL (https://github.com/nextcloud/desktop-client-blueprints) to download the dependencies and configure the environment to generate an executable nextcloud.exe
2. Double-click or use the command line to launch the application nextcloud.exe
3. The application crashes, and a look at the logs will reveal the error described above.

### Expected behavior

Double-click on the app nextcloud.exe to open the app.

### Which files are affected by this bug

nextcloud.exe nextcloud_csync.dll

### Operating system

Windows

### Which version of the operating system you are running.

Windows 10

### Package

Compiled it myself

### Nextcloud Server version

28.0.3

### Nextcloud Desktop Client version

3.14.0

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by mgallien** [comment] 2024-09-28 12:03
@c9yydm I am closing this as this is not a bug.
You are very much welcome to self build the desktop client on your own. I encourage you to keep doing that
If you have issues doing so, I suggest reaching out for help via https://help.nextcloud.com forum or via the Desktop client community Talk room https://cloud.nextcloud.com/call/d8k2r6p6

**Closed by mgallien** 2024-09-28 12:03 UTC
Labels: 0. Needs triage
