### ISSUE TITLE
Installation Nextcloud 3.0.3 on Windows 10 20H2

### ISSUE THREAD

**Issue by ifrh** [nextcloud/desktop#2639] opened 2020-11-14 22:32 UTC
### Expected behaviour
Nextcloud-3.0.3-setup.exe should close and update a former installation of Nextcloud Client 3.0.2.
All file attributes inside the nextcloud folder should modifyed by setup correctly. 

### Actual behaviour
on Windows 10 20H2
Nextcloud-3.0.3-setup.exe running as local Admin
cannot overwrite
=> c:\Program Files (86)\Nextcloud\shellext\NCContextMenu.dll
=> c:\Program Files (86)\Nextcloud\shellext\NCOverlays.dll

Tell us what happens instead
Message box about unoverridable dlls.

### Steps to reproduce
1. Stop synchronising 3.0.2 
2. quit nextcloud cliend 3.0.2 so that is not running (check with ProcessExplorer)
3. start as Admin Nextcloud-3.0.3-setup.exe

Operating system: Windows 10 20H2 (Home, 64 bit)

OS language: German

Installation path of client:
%ProgramFiles(x86)%=C:\Program Files (x86)
C:\Program Files (x86)\Nextcloud

### Server configuration

Nextcloud version:

Storage backend (external storage):

### Logs

No  logs from  Nextcloud-3.0.3-setup.exe

**Comment by neshanjo** [comment] 2020-11-16 07:57
I'm experiencing exactly the same issue.

**Comment by Reseko** [comment] 2020-11-16 09:12
I'm experiencing exactly the same issue

**Comment by er-vin** [comment] 2020-11-16 11:06
Duplicate of #2606

**Closed by er-vin** 2020-11-16 11:06 UTC

**Comment by andrewbernard** [comment] 2020-11-16 11:39
Not a duplicate of #2606. That si where it says errors about uninstaller. This relates to not being able to write DLL's.

**Comment by andrewbernard** [comment] 2020-11-16 11:41
The issue is that the Nextcloud process is running and the installer does not detect this whereas it should stop the process before proceeding. Or similar.

If you manually kill the Nextcloud process and manually remove the Program Files/Nextcloud directory, the installation proceeds.
But that is only a workaround.

**Comment by StealUrKill** [comment] 2020-11-16 15:50
> I'm experiencing exactly the same issue.

Using Process Explorer and searching for NCOverlays.dll yields it being in use by explorer.exe. I assume this is the little NextCloud image under the quick access pane. To overcome this, have your installer up and on the part where it says to retry overwriting the dll. Then open your task manager and kill explorer.exe (Windows Explorer). Hit retry on the nextcloud installer and it will work.

**Comment by StealUrKill** [comment] 2020-11-16 15:52
> I'm experiencing exactly the same issue.



> The issue is that the Nextcloud process is running and the installer does not detect this whereas it should stop the process before proceeding. Or similar.
> 
> If you manually kill the Nextcloud process and manually remove the Program Files/Nextcloud directory, the installation proceeds.
> But that is only a workaround.

I know this is a workaround as well.


Using Process Explorer and searching for NCOverlays.dll yields it being in use by explorer.exe. I assume this is the little NextCloud image under the quick access pane. To overcome this, have your installer up and on the part where it says to retry overwriting the dll. Then open your task manager and kill explorer.exe (Windows Explorer). Hit retry on the nextcloud installer and it will work.
