### ISSUE TITLE
[Bug]: Server app icons invisible/missing

### ISSUE THREAD

**Issue by keunes** [nextcloud/desktop#5949] opened 2023-08-02 20:18 UTC
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

In the 'main window', the server apps icon (of the overflow menu) is missing. Clicking on it, does work, however.
![afbeelding](https://github.com/nextcloud/desktop/assets/11229646/f1810fe6-02b7-448f-ac62-4dd494e21b2b)

### Steps to reproduce

1. Open the 'main window'
2. The window has the issue (no button visible)

### Expected behavior

When clicking on the share dialog, share by e-mail should be an option.
![afbeelding](https://github.com/nextcloud/desktop/assets/11229646/06d6a07c-22d7-4885-aaff-d5d70f5a9e9e) (cropping from an upload from another ticket).

### Which files are affected by this bug

No idea (I'm not a developer)

### Operating system

Linux

### Which version of the operating system you are running.

Ubuntu 23.04

### Package

Other

### Nextcloud Server version

26.0.0

### Nextcloud Desktop Client version

Versie 3.9.1 (KDE)  org.kde.Platform-6.2.0-26-generic

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Enabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Additional info

I installed the Desktop client via Flathub: https://flathub.org/en/apps/com.nextcloud.desktopclient.nextcloud

**Comment by cappuMUC** [comment] 2023-08-11 07:46
I'm facing the same issue with the Flatpak image on Fedora 38.

**Comment by MacKarp** [comment] 2023-08-15 19:46
same here with flathub flatpak: 
3.9.2 (KDE)
org.kde.Platform-6.4.8-202.fsync.fc38.x86_64
![Zrzut ekranu z 2023-08-15 21-36-19](https://github.com/nextcloud/desktop/assets/13783448/ae237afd-9e01-4b3b-a370-1b0600565244)

**Comment by develroo** [comment] 2024-01-24 12:49
**BUMP**

Same here on Debian Testing/Gnome. I thought it was something to do with theming but faffed around and it is still the same. Changing to the default theme makes white text on white backgrounds. So something weird is going on. 
I've tried setting the theme in the flatpak itself to Adwaita-Dark which really should work as a default Gnome theme, but no joy so I cannot change status or edit folder preferences.

**Comment by Thesola10** [comment] 2024-02-29 16:45
Big bump, this makes the app virtually unusable

**Comment by joshrandall8478** [comment] 2024-03-17 22:15
dealing with the same issue here. On Arch, nextcloud 3.12, using KDE 6. Dolphin context menu isnt showing too

**Comment by GeraldSoellinger** [comment] 2024-03-24 13:10
I found a temporary solution for my problem: 
https://github.com/flathub/com.nextcloud.desktopclient.nextcloud/pull/130#issuecomment-1903355255

**Comment by joshrandall8478** [comment] 2024-03-24 17:01
> I found a temporary solution for my problem: [flathub/com.nextcloud.desktopclient.nextcloud#130 (comment)](https://github.com/flathub/com.nextcloud.desktopclient.nextcloud/pull/130#issuecomment-1903355255)

So, switching to hyprland temporarily does fix my issue here. It may be something with KDE 6 theming, thats my initial guess. Unsure if KDE or nextcloud has to fix this.

![image](https://github.com/nextcloud/desktop/assets/39863829/82f19c41-b49e-4165-8d8c-6c42247be847)

**Comment by YamiDoesDev** [comment] 2024-03-24 17:03
I am using 
* KDE Plasma Version 6.0.2
* Arch Linux / Kernel Version 6.8.1 
* nextcloud-client 2:3.12.1-1

I have the issue, that some icons are not showing, and I was not able to add another account. Furthermore, I tried to manually add an account by manipulating the “.config/Nextcloud/nextcloud.cfg”. Adding a second account worked, but I suddenly had a lot of synchronizing issues.

I tried the solution, mentioned in [flathub/com.nextcloud.desktopclient.nextcloud#130 (comment)](https://github.com/flathub/com.nextcloud.desktopclient.nextcloud/pull/130#issuecomment-1903355255) as well, without any success.

Currently, I am using the “Nextcloud-3.12.1-x86_64.AppImage”, which has been working like a charm. I don't know why, but maybe my comment can somehow contribute to finding a solution for some issues.

**Comment by joshrandall8478** [comment] 2024-04-08 04:42
unsure what happened, but my issue here has been fixed for about 1-2 weeks.
![Screenshot_20240408_004239](https://github.com/nextcloud/desktop/assets/39863829/1b017b0e-c93a-44b3-b697-30a733d4212d)

**Comment by floli** [comment] 2024-04-19 19:41
I was able to work around starting nextcloud like that:
```
QT_QPA_PLATFORMTHEME=qt5ct:qt6ct nextcloud
```
(Arch Linux, KDE Plasma 6, Wayland, binary nextcloud client version)

**Comment by joshrandall8478** [comment] 2024-06-16 01:37
All issues related to this (including dolphin icons showing) in KDE 6 have been fixed for a while now. This issue can be closed if necessary

**Comment by binarykitchen** [comment] 2024-06-25 11:34
Just arrived here after a fresh Arch Linux install. Sorry to say, this issue sucks. Should I go back to Ubuntu?

**Comment by joshrandall8478** [comment] 2024-06-25 12:40
> Issue still exists:
> 
> 
> 
> - QT_QPA_PLATFORMTHEME environment variable/flatpak override does not solve the issue.
> 
> 
> 
> - "sudo flatpak remove org.kde.PlatformTheme.QGnomePlatform org.kde.WaylandDecoration.QAdwaitaDecorations org.kde.WaylandDecoration.QGnomePlatform-decoration" does not solve the issue.
> 
> 
> 
> OS: Arch Linux x86_64  
> 
> Kernel: 6.9.6-arch1-1
> 
> DE: GNOME 
> 
> WM: Mutter 
> 
> WM Theme: Adwaita 
> 
> Theme: Adwaita-dark [GTK2/3] 
> 
> Icons: Adwaita [GTK2/3]

I'm gonna try to replicate your settings in a VM and see what I find

**Comment by binarykitchen** [comment] 2024-06-25 12:46
@joshrandall8478 Good on you, hope you'll find the cause ... thanks

**Comment by azuredusk10** [comment] 2024-06-25 13:28
Myself and others are also having the same issue and the workarounds no longer work, as reported in the Flathub repo:
https://github.com/flathub/com.nextcloud.desktopclient.nextcloud/pull/130

Thank you for looking into this

**Comment by joshrandall8478** [comment] 2024-06-25 14:25
So: after using a fresh install of arch on gnome, and using the binary `nextcloud-client` from pacman, i do not experience the issue.

![Screenshot_20240625_093739](https://github.com/nextcloud/desktop/assets/39863829/26e95bef-828b-47cd-a774-58d9bd590147)
![Screenshot_20240625_100332](https://github.com/nextcloud/desktop/assets/39863829/e242daf4-a41d-4e88-bc05-

The issue however still persists on the flatpak `com.nextcloud.desktopclient.nextcloud`.
![Screenshot_20240625_102047](https://github.com/nextcloud/desktop/assets/39863829/9405e861-1014-4efb-87db-6074b0c430c1)
![Screenshot_20240625_102215](https://github.com/nextcloud/desktop/assets/39863829/557033de-c60c-49ee-978c-7608bf04e3f0)

When choosing `org.nextcloud.Nextcloud` instead, it stated that it is end of life. 
![Screenshot_20240625_102345](https://github.com/nextcloud/desktop/assets/39863829/531c669b-0325-4877-8305-59cad80e1a72)

My conclusion is this:
- Most up to date provided binary package will work, at least on Arch on both KDE and Gnome.
- The flatpak (and potentially some of its libraries) msut be updated, as its issue is still persisting.

I hope this helps 🙏🏼

**Comment by septatrix** [comment] 2024-06-25 14:57
> My conclusion is this:
> 
>     * Most up to date provided binary package will work, at least on Arch on both KDE and Gnome.

At least on Fedora+KDE the latest binary (3.13.0) still has the icons missing

**Comment by joshrandall8478** [comment] 2024-06-25 15:00
My next step would be to potentially compile from source, at least for now

**Comment by azuredusk10** [comment] 2024-06-25 15:38
> > My conclusion is this:
> > ```
> > * Most up to date provided binary package will work, at least on Arch on both KDE and Gnome.
> > ```
> 
> At least on Fedora+KDE the latest binary (3.13.0) still has the icons missing

I just tried installing the Fedora Linux RPM package (v 3.13.0) via GNOME Software and the text is visible.

I also tried installing the AppImage from the Nextcloud website and the text is also visible there:
https://nextcloud.com/install/#install-clients

If the RPM doesn't work for you @septatrix  try the AppImage. A shame the flatpak is broken but I'll put a link to @joshrandall8478 's response there in case someone is able to fix it. I tried to look into it but I couldn't make sense of what needs changing.

**Comment by joshtrichards** [comment] 2024-08-12 20:17
Duplicate of flathub/com.nextcloud.desktopclient.nextcloud#115

**Closed by joshtrichards** 2024-08-12 20:17 UTC
Labels: 0. Needs triage, bug, os: :penguin: Linux

**Comment by septatrix** [comment] 2024-08-12 22:30
> Duplicate of [flathub/com.nextcloud.desktopclient.nextcloud#115](https://github.com/flathub/com.nextcloud.desktopclient.nextcloud/issues/115)

This is not a duplicate of the flatpak bug as I can still reproduce it with the RPM package, i.e. *without* flatpak or any other sandboxing which might affect the theming

**Comment by septatrix** [comment] 2024-08-12 22:38
> > > My conclusion is this:
> > > ```
> > > * Most up to date provided binary package will work, at least on Arch on both KDE and Gnome.
> > > ```
> > 
> > 
> > At least on Fedora+KDE the latest binary (3.13.0) still has the icons missing
> 
> I just tried installing the Fedora Linux RPM package (v 3.13.0) via GNOME Software and the text is visible.
> 
> I also tried installing the AppImage from the Nextcloud website and the text is also visible there: https://nextcloud.com/install/#install-clients
> 
> If the RPM doesn't work for you @septatrix try the AppImage. A shame the flatpak is broken but I'll put a link to @joshrandall8478 's response there in case someone is able to fix it. I tried to look into it but I couldn't make sense of what needs changing.

The AppImage is also not working! Again, this is with normal Fedora+KDE Plasma, in Weston it is working normally so I expect some packaging issue where the desktop client does not use/find the correct icons when running under KDE Plasma

**Comment by azuredusk10** [comment] 2024-08-12 22:54
I can confirm that the icons in the RPM version is no longer working. There seems to have been a regression since I last commented saying it was working.

**Comment by marco-calautti** [comment] 2024-09-20 08:25
The issue is also present on Arch+Plasma Wayland using the nextcloud-client package from the official arch repos.

**Comment by septatrix** [comment] 2024-10-29 10:22
This is now finally working for me on an up-to-date Fedora system with KDE Plasma

**Comment by arthurroos** [comment] 2025-01-09 04:05
this is still present on Arch+Plasma Wayland using both the nextcloud-client package and the flathub package

**Comment by arthurroos** [comment] 2025-01-09 04:07
> * Most up to date provided binary package will work, at least on Arch on both KDE

this is still present on Arch+Plasma Wayland using both the nextcloud-client package and the flathub package. all up to date. What info could I provide to help identify the issue?

**Comment by joshrandall8478** [comment] 2025-01-09 04:17
> > * Most up to date provided binary package will work, at least on Arch on both KDE
> 
> this is still present on Arch+Plasma Wayland using both the nextcloud-client package and the flathub package. all up to date. What info could I provide to help identify the issue?

can confirm i'm having this issue on some areas of the app, especially when i'm sharing an item.

**Comment by BatmansGehilfe** [comment] 2025-02-13 10:22
> > > * Most up to date provided binary package will work, at least on Arch on both KDE
> > 
> > 
> > this is still present on Arch+Plasma Wayland using both the nextcloud-client package and the flathub package. all up to date. What info could I provide to help identify the issue?
> 
> can confirm i'm having this issue on some areas of the app, especially when i'm sharing an item.

Can confirm this on Tumbleweed with the RPM from the repositories as well.

**Comment by majneb** [comment] 2025-02-22 15:29
Still broken in Fedora RPM, Fedora 41, KDE 6.3 : 

![Image](https://github.com/user-attachments/assets/a98146dd-2ad2-4646-a45f-fb227725238b)

Please, re-open the issue.
