### ISSUE TITLE
Yellow notification unsolved conflicts is not clickable

### ISSUE THREAD

**Issue by faulix** [nextcloud/desktop#1080] opened 2019-02-11 19:49 UTC
The client shows me unsolved conflicts and I should click for more details.

### Expected behaviour
Show list of conflicts if I click on it.

### Actual behaviour
Nothing happens with a single click, double click opens the list of subfolders.

### Steps to reproduce
1. Synchronize with conflicts (ignored files might also do it)
2. Open the nextcloud GUI
3. Click on the yellow notification (and try again and again and again :D )

### Client configuration
Client version: 2.5.1 build 20181204

Operating system: macOS Mojave 10.14.3 (18D109)

OS language: German

Client package (From Nextcloud or distro) (Linux only): downloaded from nextcloud.org

Installation path of client: ‎⁨OS⁩/Applications

### Activity overview

Can't find any conflicts there, just ignored files. Might also be connected with
https://github.com/nextcloud/desktop/issues/566

**Comment by HackintoshHD** [comment] 2019-02-13 17:59
I can confirm this. Same configuration as above, except for the OS, which is macOS 10.13.6 (17G5019) High Sierra in my case.

A screenshot of the English GUI dialogs is in #872.

**Comment by csommers79** [comment] 2019-03-26 11:50
Same issue. macOS 10.14.3 with Nextcloud Mac Client Version 2.5.1final (build 20181204)

**Comment by tsueri** [comment] 2019-03-28 15:24
Same here on Version 2.5.1final (build 20181204).

**Comment by EmmanuelLazard** [comment] 2019-03-29 14:31
Same with me when trying to synchronize between two computers via nextcloud server.
It appears the conflict issues are due to the .DS_Store files in folders. That's why there is no yellow dots on non-hidden files.

**Comment by tsueri** [comment] 2019-04-01 07:31
> Same with me when trying to synchronize between two computers via nextcloud server.
> It appears the conflict issues are due to the .DS_Store files in folders. That's why there is no yellow dots on non-hidden files.

and this makes it very hard to review possible errors... But the sign "There are unresolved conflicts. Click for details" doesn't work anyway.

**Comment by TheNeuromarketingLabs** [comment] 2019-04-01 10:04
Same here: macOS 10.13.6, Nextcloud Client Version 2.5.1final (build 20181204)
Clicking the olivegreen Bar "Es existieren ungelöste Konflikte. Für Details klicken." nothing happens.
Searching for files with name containing "conflict" yields nothing. 
"Activity" shows a bunch of ignored files, but no conflicts.

**Comment by bunjes** [comment] 2019-04-01 10:11
> Same with me when trying to synchronize between two computers via nextcloud server.
> It appears the conflict issues are due to the .DS_Store files in folders. That's why there is no yellow dots on non-hidden files.

Executing [dot_clean ](https://ss64.com/osx/dot_clean.html) on the local Nextcloud folder helped for me, since it removes the hidden files like .DS_Store.

**Comment by ClaireSoftware** [comment] 2019-04-21 02:06
For me, deleting the "Photos library" folder in the Pictures folder worked.

**Comment by sbliven** [comment] 2019-05-10 07:28
@bunjes @ClaireSoftware Those are possible ways to remove the conflicts, but the point is that the nextcloud client should to tell the user where the errors are.

**Comment by AhabHyde** [comment] 2019-05-20 16:31
I have the same issue, macOS Mojave 10.14.5 (Nextcloud 2.5.2git)

**Comment by cweiske** [comment] 2019-05-22 18:06
Duplicate of #566.

**Comment by faulix** [comment] 2019-05-27 06:27
@cweiske just partially. #566 is a bug causing (not needed) yellow boxes, this is a bug that the message is not clickable even though it says that you should click on it for more information. I think normally the log window should open, therefore 2 different bugs from my perspective.

**Comment by markshep** [comment] 2019-06-20 08:56
Any plans to fix this bug?  It's been present for quite some time.

**Comment by HackintoshHD** [comment] 2019-07-24 09:55
I would like to second @markshep 's statement and appreciate it if fixing this design error could receive a higher priority on the desktop client's roadmap. It has become a real 'deal breaker' for the Desktop Client versions ≥ 2.5.0 insofar as everybody with the slightest conflict in his/her sync history will have to revert to version 2.3.3.84 to preserve a proper synchronisation status.

**Comment by zippytiff** [comment] 2019-10-25 08:43
agreed, MAJOR issue also on Windows

**Comment by ra-pha** [comment] 2019-12-31 23:21
Still an issue in 2020. Would highly appreciate a resolution of this annoying bug.

**Comment by techitint** [comment] 2020-01-15 22:06
Definitely still happening with version 2.6.2stable.
Clicking on the sticky yellow alert doesn't give any result.
Can't find anything in the log either.
@zippytiff WINDOWS is a major issue itself LOL

**Comment by bunjes** [comment] 2020-02-05 09:25
Seems to be resolved for me with Version 2.6.2stable (build 20191224).

**Comment by veddox** [comment] 2020-06-18 14:41
Still the case with the latest build:

Nextcloud version 2.7.0git
Git revision afac668d9c877ff4e60df484f1d5752e22450e23
Using Qt 5.12.8, built against Qt 5.12.8
Using Qt platform plugin 'xcb'
Using 'OpenSSL 1.1.1f  31 Mar 2020'
Running on Ubuntu 20.04 LTS, x86_64

**Comment by guidopilato** [comment] 2020-06-19 19:10
Same Error,

Nextcloud Version 2.7.0beta1-Win64 (build 20200119). 
Git revision 03cdda
Qt 5.12.5
OpenSSL 1.1.1d 10 Sep 2019
WINDOWS 8.1

**Comment by veddox** [comment] 2020-07-16 14:16
Duplicate of #1195, moving discussion there.

**Closed by veddox** 2020-07-16 14:16 UTC
Labels: bug, feature: :gear: settings, feature: :zap: activity and :bell: notification

**Comment by helmut72** [comment] 2020-08-19 18:28
Same error with Nextcloud Desktop 3.0

**Comment by treysis** [comment] 2020-09-02 15:21
Same with 3.0.1 on Windows. Can't even read the whole error message in the taskbar popup.

**Comment by kusmi** [comment] 2020-09-06 19:40
And experienced the same on 3.0.1 on Mac

**Comment by szyszyszyszy** [comment] 2020-09-25 14:51
Same. 3.0.1 on windows.

**Comment by DavideAG** [comment] 2020-09-29 22:51
Same here using 3.0.2 on Windows 10

**Comment by totalcaos** [comment] 2020-09-30 01:40
Same here using 3.0.2 on Windows 10

**Comment by bernd-wechner** [comment] 2020-10-01 22:13
Same on 3.0.2 on Linux Mint 20 Cinnamon.

Egads how hard can this be to fix. What spark of genius does it need to have a menu item on the right click menu for example. We click and click Here as asked and nothing happens. So now we have unresolved conflicts and don't know where?

**Comment by ginkeltjes** [comment] 2020-10-02 07:27
Same problem here on MacOS Catalina 10.15.7, Nextcloud 3.0.2

**Comment by Freeedim** [comment] 2020-10-03 16:53
Same in 3.0.2 Windows and 3.0.1 Linux (Debian)

**Comment by mister-crypto** [comment] 2020-10-08 14:22
Confirmed with NC Version -3.0.2 and Windows v2004 Build 19041.508

I would imagine with the client open, viewing the unresolved conflicts in yellow. A pointer link to what is already available to show in the notification taskbar when clicked should be an easy short-term consideration. 
Long-term - a list log generated recursively after each sync could open a submenu or window that works in the same manner when creating a new sync connection and selecting the directory. It would simply be a secondary production of what already exists within the desktop client when clicking the nextcloud taskbar notification icon, but providing in a new NC window. 

Having the sync indicators on files on the local filesystem works great, use this in conjunction with the conflict list provided via the taskbar notification area to identify common conflict types.

From the NC menu via notification taskbar, the conflicting files are visible with left-click, you can use this to identify the common files and/or extensions that are of conflict. When clicking the conflict in question, the explorer window will show exactly what files/directory have the conflicts (using the sync indicators). Locally, you can exclude such files from the upload; you can uncheck "sync hidden files." You can deduce common conflict types, use exclusion rules overall in all sync connections you create, or by absolute and setting said exclusions in specific subdirectories of those sync connections.

**Comment by lofma** [comment] 2020-12-06 09:31
I can confirm the issue for 3.0.3 (macOS).

**Comment by er-vin** [comment] 2020-12-07 11:04
Yes, fix is coming in 3.1.0

**Comment by aryehassbian** [comment] 2021-01-07 21:35
I have the yellow exclamation mark with version 3.1.1 on windows 8.1 - Still not able to remove it and I don't even know what is the conflict since it does NOT show

**Comment by ry167** [comment] 2021-01-19 21:13
I encountered this today and while it sucks that the yellow button doesn't work, you may be able to resolve the conflicts by searching your local Nextcloud folder for "conflict" and manually removing conflicted files. I found that answer here: https://help.nextcloud.com/t/unresolved-conflicts-click-for-details-nothing-happens/100463
The yellow notification will then go away.

I encountered this in 3.1.1 on Pop OS / Ubuntu
