### ISSUE TITLE
Linux client 2.5 crashes on start - requires GLX 1.3 ?

### ISSUE THREAD

**Issue by lhurt** [nextcloud/desktop#846] opened 2018-11-17 06:25 UTC
New client 2.5 crashes right after start with the following error.

```QXcbConnection: Failed to initialize XRandr
[20664:20723:1117/071512.984975:ERROR:gl_surface_qt.cpp(241)] GLX 1.3 or later is required.
[20664:20723:1117/071512.985011:ERROR:gl_surface_qt.cpp(371)] GLContextHelper::getEGLDisplay() failed.
WARNING: Application calling GLX 1.3 function "glXCreatePbuffer" when GLX 1.3 is not supported!  This is an application bug!
[20664:20723:1117/071513.152429:ERROR:gl_surface_qt.cpp(667)] Requested OpenGL implementation is not supported. Implementation: 0
*** stack smashing detected ***: <unknown> terminated
Aborted (core dumped)
```

System environment is Ubuntu 18 LTS, XFCE window manager.
glxinfo (excerpt)
```
name of display: :1.0
display: :1  screen: 0
direct rendering: Yes
server glx vendor string: SGI
server glx version string: 1.2
...
```

any help would be gladly appreciated.

Nov 21: The application is currently unusable for me. As I'm heavily relying on Nextcloud this is a major issue for me

**Comment by linuxrrze** [comment] 2018-11-30 09:14
Same thing here:

I'm using x2go to connect to a remote server.
X2go only supports glx version 1.2 and causes nextcloud client 2.5 to crash.

I tried the workaround mentioned here:
https://wiki.x2go.org/doku.php/wiki:development:glx-xlib-workaround

```
# apt install libdrm-dev  libx11-dev python-mako libx11-xcb-dev libxcb-dri2-0-dev libxcb-glx0-dev libxxf86vm-dev libxfixes-dev libxdamage-dev libxext-dev libexpat1-dev flex bison
# git clone https://gitlab.freedesktop.org/mesa/mesa.git
# cd mesa/mesa
# scons libgl-xlib
# export LD_LIBRARY_PATH=$PWD/build/linux-x86_64-debug/gallium/targets/libgl-xlib/:${LD_LIBRARY_PATH}
# nextcloud
```

For now nextcloud seems to run fine. 
However I still need to integrate this into the autostart procedure

**Comment by linuxrrze** [comment] 2018-11-30 09:20
This seems to work (mind the modified Exec: line):

```
# cat ~/.config/autostart/Nextcloud.desktop
[Desktop Entry]
Name=Nextcloud
GenericName=File Synchronizer
#Exec=/usr/bin/nextcloud
Exec=env LD_LIBRARY_PATH=/opt/mesa/build/linux-x86_64-debug/gallium/targets/libgl-xlib/:${LD_LIBRARY_PATH} /usr/bin/nextcloud
Terminal=false
Icon=nextcloud
Categories=Network
Type=Application
StartupNotify=false
X-GNOME-Autostart-enabled=true

```

**Comment by lhurt** [comment] 2018-12-03 16:05
The workaround did it for me. Nevertheless it shouldn't be necessary.

**Comment by Linutux** [comment] 2019-06-19 22:39
I have the same issue, also using x2go on a remote server.
Does some one have the packages names for the workaround using Fedora?

**Comment by stratoss** [comment] 2020-01-20 05:20
I have the same issue with nextcloud client over x2go

```
Mesa warning: Window 37748741 has no colormap!

[9209:9272:0120/071754.848332:ERROR:gl_surface_glx_qt.cpp(186)] glXCreatePbuffer failed.
Received signal 11 SEGV_MAPERR 000000000000

```

```
glxinfo | grep glx
server glx vendor string: Brian Paul
server glx version string: 1.4 Mesa 18.3.6
server glx extensions:
client glx vendor string: Brian Paul
client glx version string: 1.4 Mesa 18.3.6
client glx extensions:
```

**Comment by fpl** [comment] 2021-01-22 10:40
It definitively depends on the local GPU, I work with different servers via x2go: with the same releases and GLX 1.2 it works on a server with an Intel GPU, but fails on one with a Matrox GPU.

**Comment by er-vin** [comment] 2021-01-25 09:00
OK, it's clear the problem is lower in the stack and we can't do much about it. I'll thus close this one.

**Closed by er-vin** 2021-01-25 09:00 UTC
Labels: 0. Needs triage
