### ISSUE TITLE
more consistant first view of the Account Settings tab

### ISSUE THREAD

**Issue by TP75** [nextcloud/desktop#1549] opened 2019-10-22 19:20 UTC
### Expected behaviour

The NC desktop client by it's 'Account Settings tab' should:
- after the first initial sync show
  + either an opened list with
    * the grey arrow icon pointing down
    * an appropriate and non-empty list of files & folders 
  + or alternatively a closed list with
    * the grey arrow icon pointing right
    * no list or empty list of files & folders 
- always present information in conformance to the general GUI design
- present information as consistant through all stages as is reasonably possible

Furthermore, a more prominent symbol e.g., a bigger arrow icon could improve the design features and the visibility of GUI response.

### Actual behaviour

Some older version and certainly the current intermediate Version **2.6.1rc1** of the NC desktop client in a Mac OS X / macOS environment after the first initial sync shows:
- a misleading 'Account Settings tab' without presentation of the already synced folders
- the grey arrow icon pointing down as if a list of files & folders would be presented
- no list of synced folders is presented in contradiction to the orientation of the grey arrow icon

The experienced user may easily select and deselect the view to update the GUI status to a more correct presentation. However, this is a first use scenario after installation and normal users and certainly first adopters of the NC desktop may get a false impression and can get confused by the misleading status presentation of the  'Account Settings tab'.

### Steps to reproduce

1. Make a fresh install of the NC desktop client on OS (1.), (2.) or (3.)
1. Configure as applicable.
1. Perform the first synchronisation and oberserve the 'Account Settings tab'

see the screenshot below

### Client configuration

Client version: 

- _Version **2.6.1rc1** (build 20191018)_

Operating system: 

1. _Mac OS X / macOS Mojave 10.14.6_
1. _Mac OS X / macOS HighSierra 10.13.6_
1. _Mac OS X / macOS Sierra 10.12.6_

OS language: 

1. _German (Deutsch / DE)_
1. _Dutch (Nederlands / NL)_
1. _German (Deutsch / DE)_

Qt version used by client package: 

- _Qt 5.12.5_

### Server configuration

Nextcloud version: _16.0.5.1_

### Brief description:

View is given for the NL locale and is similar between OS (1.) - (3.) and locales. 
The deviation of the grey arrow icon is marked red. 

![screenshot_client-NL_2019-10-21a01_failsync](https://user-images.githubusercontent.com/31193257/67315754-7f403000-f507-11e9-9d2d-dafd9f60013e.png)

Please note the list of sync files appears as if opened for view (the grey arrow icon points down) but incorrectly as if files & folders would be emtpy. There should be several files & folders which are synced successfully in this stage already and should be shown but unfortunately are not presented.

**Comment by TP75** [comment] 2019-11-08 17:55
awaits triage for _2.6.1stable_

**Comment by er-vin** [comment] 2020-05-20 12:01
Could you please confirm if that's still the case on 2.6.4? Thanks in advance.

**Comment by FlexW** [comment] 2021-06-18 18:16
I will close the issue because the user interface has changed a lot in the meantime and the issue is not anymore applicable.

**Closed by FlexW** 2021-06-18 18:16 UTC
