### ISSUE TITLE
Windows 10 Client 3.2.1 keep crashing

### ISSUE THREAD

**Issue by kenvix** [nextcloud/desktop#3243] opened 2021-04-30 12:48 UTC
### Expected behaviour

Sync my files normally

### Actual behaviour

It crashes after connected to server

### Steps to reproduce
1. Launch nextcloud desktop
2. Wait for it to connect with the server 
3. It crashed.

### Client configuration
Client version: 3.2.1

Operating system: Windows 10 20H2

OS language: zh_CN

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From Nextcloud or distro) (Linux only):

Installation path of client: C:\Program Files\Nextcloud

### Server configuration

Nextcloud version: latest docker fpm version (image was pulled yesterday)

Storage backend (external storage): default

### Logs

I even had to disconnect my network to enable logging :(

1. Client logfile: 

[log.zip](https://github.com/nextcloud/desktop/files/6405396/log.zip)

Messages from windows event viewer

```xml
- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Application Error" /> 
  <EventID Qualifiers="0">1000</EventID> 
  <Version>0</Version> 
  <Level>2</Level> 
  <Task>100</Task> 
  <Opcode>0</Opcode> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2021-04-30T12:43:38.8203629Z" /> 
  <EventRecordID>27557</EventRecordID> 
  <Correlation /> 
  <Execution ProcessID="0" ThreadID="0" /> 
  <Channel>Application</Channel> 
  <Computer>EXCALIBUR</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data>nextcloud.exe</Data> 
  <Data>3.2.1.25340</Data> 
  <Data>6089359f</Data> 
  <Data>KERNELBASE.dll</Data> 
  <Data>10.0.19041.906</Data> 
  <Data>2f2f77bf</Data> 
  <Data>c0000005</Data> 
  <Data>000000000002ae08</Data> 
  <Data>2598</Data> 
  <Data>01d73dbdd64e5bfd</Data> 
  <Data>C:\Program Files\Nextcloud\nextcloud.exe</Data> 
  <Data>C:\WINDOWS\System32\KERNELBASE.dll</Data> 
  <Data>608bae21-ce02-460d-842e-e71b2d6d6bcc</Data> 
  <Data /> 
  <Data /> 
  </EventData>
  </Event>
```

**Comment by Archangel001** [comment] 2021-04-30 14:40
same for me, only if enable virtual file

OS: Windows 10 20H2

tried reinstall client but no success

**Comment by allexzander** [comment] 2021-04-30 16:20
@kenvix 

I can see the known problem of 3.2.0 in your logs. It was fixed in 3.2.1.

However, it seems that the running app's version is still 3.2.0 according to your logs.

Could you try the following:
- Make sure to completely remove your Nextcloud desktop client
- Temporarily rename the folder: "C:/Users<your_user_name>/AppData/Roaming/Nextcloud" to "C:/Users<your_user_name>/AppData/Roaming/**~**Nextcloud" while not having the app running
- Run the app again, connect it to your server and choose a sync folder
- Let me know if the issue is still there
- Attach logs from the app (if the issue is still present)
- Feel free to rename your "Nextcloud" data folder "C:/Users<your_user_name>/AppData/Roaming/**~**Nextcloud" back to "C:/Users<your_user_name>/AppData/Roaming/Nextcloud"

With the steps above, you'll make sure you're running the latest 3.2.1 release. Also, you'll make sure the broken state of 3.2.0 is not affecting the latest 3.2.1 installation.

@mgallien ping

**Comment by allexzander** [comment] 2021-04-30 16:22
> same for me, only if enable virtual file
> 
> OS: Windows 10 20H2
> 
> tried reinstall client but no success

@Archangel001 

Same could be true for your case. If you've been running the Nextcloud release 3.2.0 before 3.2.1, the local state might have been broken and is still affecting 3.2.1 making the 3.2.0 issue to happen. I suggest you try the steps from my previous comment and let me know how it goes.

**Comment by kenvix** [comment] 2021-04-30 23:41
@allexzander

 I have completely reinstall nextcloud as your follows and rebooted my computer. It crashes again after connected to server.

Log: 
[LOG2.zip](https://github.com/nextcloud/desktop/files/6408492/LOG2.zip)


I have ensured that the client version is 3.2.1 
![image](https://user-images.githubusercontent.com/4546175/116763497-29c7d600-aa50-11eb-9c3d-4872885f931d.png)

**Comment by Archangel001** [comment] 2021-05-03 08:28
> > same for me, only if enable virtual file
> > OS: Windows 10 20H2
> > tried reinstall client but no success
> 
> @Archangel001
> 
> Same could be true for your case. If you've been running the Nextcloud release 3.2.0 before 3.2.1, the local state might have been broken and is still affecting 3.2.1 making the 3.2.0 issue to happen. I suggest you try the steps from my previous comment and let me know how it goes.




> > same for me, only if enable virtual file
> > OS: Windows 10 20H2
> > tried reinstall client but no success
> 
> @Archangel001
> 
> Same could be true for your case. If you've been running the Nextcloud release 3.2.0 before 3.2.1, the local state might have been broken and is still affecting 3.2.1 making the 3.2.0 issue to happen. I suggest you try the steps from my previous comment and let me know how it goes.

I ve clean uninstalled Nextcloud app with RevoUninstaller, removed any related folder, registry, ecc..   installed 3.2.1 but no success


[Nextcloud_log_cleaninstall.zip](https://github.com/nextcloud/desktop/files/6413682/Nextcloud_log_cleaninstall.zip)
[Event1.txt](https://github.com/nextcloud/desktop/files/6413684/Event1.txt)

**Comment by sgtpepperaut** [comment] 2021-05-05 06:00
same issue, it appears to happen to happen when there is a large "difference" in files to be synced.
This is also happens with or without virtual file system. I wonder if some of those programs running besides could be an issue: "google backups and sync, acronis backup, mountaind duck". Of course they are using different folders but just thought i mention it.

**Comment by ocyrus99** [comment] 2021-05-05 18:03
I have the same crashing problem when using Virtual File System. It seems to work for a little bit then crashes when I try and access a file.  Here's the windows event log:

**Comment by nicrame** [comment] 2021-05-05 20:01
For me 3.2.1 had straaange symptom. I made update, then just go out, and after i came back (hour or so) laptop had fans turned on (usually it is quiet). What i observed (in taskmanager) was - Nextcloud eat 30-35% of CPU power doing nothing (files were synced already, and computer wasn't used). When i try to turn it off using right click on Nextcloud icon on system tray, cpu was still used, and there still was Nextcloud.exe process eating CPU. I didn't have time to play with this, because i like silent laptop :)
I'm using Win10 20H2 Pro, Intel(R) Core(TM) i7-9750H CPU, and 64,0 GB RAM, also there is nvme SSD, so for sure low hardware specs is not problem here.
Now there is client v 3.1.3 and laptop is silent :)

**Comment by weiw11** [comment] 2021-05-05 20:10
@sgtpepperaut That's what I thought too as I'm using Google FS and Cryptomator but I've already uninstalled them to check and it still doesn't work. Does explorer.exe still work for you when you have the client open? Mines won't open any new explorer windows unless I force quit the client. Disabling the .dll files loaded by Nextcloud to explorer prevents this from happening but client still has the cpu issue regardless.

**Comment by allexzander** [comment] 2021-05-06 07:56
@weiw11 @sgtpepperaut @Archangel001 

While I am looking into this issue, it would be great if one of you could also try running a clean VM (possibly of the same Windows build that you are running physically) and install the Nextcloud 3.2.1 client in the VM. Then, you'd try to sync to your server from there. I am wondering if it is indeed a conflict with some other cloud-sync software. This may require some effort from you, so, I am not insisting, but, that would be nice to check that too. Asking this, as, at the moment I wasn't able to reproduce the issue on my physical and VM OS. Will study logs today.

**Comment by allexzander** [comment] 2021-05-06 10:06
> For me 3.2.1 had straaange symptom. I made update, then just go out, and after i came back (hour or so) laptop had fans turned on (usually it is quiet). What i observed (in taskmanager) was - Nextcloud eat 30-35%...

@nicrame Do you remember if the VFS mode was turned on during that time, by any chance?

**Comment by nicrame** [comment] 2021-05-06 10:39
> @nicrame Do you remember if the VFS mode was turned on during that time, by any chance?

I didn't use VFS. Last night 3.1.3 crashed few times, so i did back to version 3.0.1 and now it is stable and quiet.
When i will have some more time i will try to diagnose it more.

**Comment by Alomon31** [comment] 2021-05-06 19:10
> @weiw11 @sgtpepperaut @Archangel001 @kenvix
> 
> While I am looking into this issue, it would be great if one of you could also try running a clean VM (possibly of the same Windows build that you are running physically) and install the Nextcloud 3.2.1 client in the VM. Then, you'd try to sync to your server from there. I am wondering if it is indeed a conflict with some other cloud-sync software. This may require some effort from you, so, I am not insisting, but, that would be nice to check that too. Asking this, as, at the moment I wasn't able to reproduce the issue on my physical and VM OS. I am gonna study logs today.

I am facing the same behaviour with 3.2.1 since I reactivated Onedrive, which makes me think it could be a conflict with other cloud-sync software, as you suggested. Unfortunately, I have no possibility of using any log right now as I am just moving, but I will ASAP.
By the way, Nextcloud client runs in Windows 10, I have no virtual file system.
Thanks.

**Comment by weiw11** [comment] 2021-05-08 05:55
@allexzander I haven't been able to get my VM to work with windows but I have tested it on another machine with the same Windows build and it works fine. 

I'm not sure if it'll help but the image below lists the modules associated with explorer.exe which is freezing for me when nextcloud freezes. My other machine also has RTSS, WinSCP, and Nextcloud as well but not too sure about the system32 dlls though.
https://user-images.githubusercontent.com/62213594/117528151-b9b0d700-af9e-11eb-9035-3f00c48f4cd6.png

**Comment by funky123** [comment] 2021-05-09 16:05
Same Problem here, i tried to use sereral Nextcloud Versions, but no Luck so far.

`Quelle
Nextcloud

Zusammenfassung
Nicht mehr funktionsfähig

Datum
‎09.‎05.‎2021 17:02

Status
Der Bericht wurde gesendet.

Beschreibung
Pfad der fehlerhaften Anwendung:	C:\Program Files\Nextcloud\nextcloud.exe

Problemsignatur
Problemereignisame:	APPCRASH
Anwendungsname:	nextcloud.exe
Anwendungsversion:	3.0.3.16114
Anwendungszeitstempel:	5fc7914c
Fehlermodulname:	ocsync.dll
Fehlermodulversion:	0.0.0.0
Fehlermodulzeitstempel:	5fc78fc1
Ausnahmecode:	c0000005
Ausnahmeoffset:	0000000000017900
Betriebsystemversion:	10.0.19042.2.0.0.256.48
Gebietsschema-ID:	1031
Zusatzinformation 1:	0f1e
Zusatzinformation 2:	0f1ecb6805ff8866029e7512c2587195
Zusatzinformation 3:	f9c4
Zusatzinformation 4:	f9c48f28765b4b01faae6f495d63b36e

Weitere Informationen über das Problem
Bucket-ID:	1ceefb435ee18148ebc9c9084dedc5c7 (2002352546847245767)
`

**Comment by allexzander** [comment] 2021-05-09 16:27
@funky123 

Was it always like that with 3.0.3? Or, did this start to happen after trying 3.2.1?

**Comment by funky123** [comment] 2021-05-09 19:10
It startet after the first Update to 3.2.1!
After that i tryied to rollback to all other versions.

**Comment by allexzander** [comment] 2021-05-09 19:46
> It startet after the first Update to 3.2.1!
> After that i tryied to rollback to all other versions.

@funky123 A workaround is to rename the folder `C:/Users/<your_user_name>/AppData/Roamin/Nextcloud`, or, to completely remove that folder. Just make sure you backup your sync folder in case some files are not synced to the server yet.

**Comment by funky123** [comment] 2021-05-09 19:54
@allexzander thanks alot! i will try this after my System is backed up (currently running)

I have serveral files modified while the sync client is/was offline.
What is the best to get them all synced without have to download all files from server and then replace them with my local saved folder

i think
1. Rename current NC Data folder on my system to "D:\NCpriv\" to "D:\NCpriv_old"
2. Rename the folder that you named `C:/Users/<your_user_name>/AppData/Roamin/Nextcloud `
3. Re-Install Nextcloud with latest version
4. At NC Client, de-select all folders to sync
5. copy my renamed folder content from  "D:\NCpriv_old" to "D:\NCpriv\" 
6. enable the just de-selected folders to sync at my NV Client

is that best way to save re-syncing time or do i miss someting?

**Comment by allexzander** [comment] 2021-05-12 09:10
@funky123 It should be enough to just select your old folder when connecting a newly installed client. Just make sure you choose "Keep files" when adding a sync folder. Then, the client should sync everything normally. The database file is inside the old sync folder, so, the information about synced/non-synced files is still there. The client should be able to pick it up. But, anyways, better do a backup of the sync folder/or subfolders that were modified, just in case.

**Comment by kenvix** [comment] 2021-05-19 00:56
Has anyone attempted to use *junctions* (`mklink /J`) and *symbolic links* `mklink /D`? It seems that NextCloud Desktop has compatibility issues working with junctions and symbolic links. 

* What will happened if we make a *junction* to a directory located out of nextcloud folder?
* What will happened if there is a link loop?
* What will happened if we make *junction* shared by nextcloud and other sync engine like OneDrive?

**Comment by Deebster** [comment] 2021-05-24 06:55
I am also having this issue. On initially adding the sync it works as expected, but after a reboot it just sits there burning CPU. I left it for over 24 hours and no progress or further log messages. I have a virtual files sync to the root of my 177gb account, mostly flac files.

I am seeing nearly 800 B/sec being written to C:\Windows\System32\LogFiles\Cloudfiles\CldFlt3.etl. Joplin on the desktop/Android is able to sync so the Nextcloud instance itself seems fine.

    2021-05-24 13:45:26:426 [ info nextcloud.gui.application ]:	"################## Nextcloud locale:[en_GB] ui_lang:[] version:[3.2.1stable-Win64 (build 20210428)] os:[Windows 10 (10.0)]"
    2021-05-24 13:45:26:445 [ info nextcloud.gui.application ]:	Using "en_GB" translation
    2021-05-24 13:45:26:457 [ info nextcloud.gui.application ]:	VFS windows plugin is available
    2021-05-24 13:45:26:457 [ info nextcloud.gui.application ]:	VFS suffix plugin is available
    2021-05-24 13:45:26:463 [ debug nextcloud.gui.socketapi ]	[ OCC::SocketApi::SocketApi ]:	creating "//./pipe" true
    2021-05-24 13:45:26:463 [ info nextcloud.gui.socketapi ]:	server started, listening at  "\\\\.\\pipe\\nextcloud-micro"
    2021-05-24 13:45:26:464 [ info nextcloud.gui.folder.manager ]:	setting remote poll timer interval to 30000 msec
    2021-05-24 13:45:26:590 [ info nextcloud.gui.account.manager ]:	Account for QUrl("https://REDACTED") using auth type "webflow"
    2021-05-24 13:45:26:591 [ info nextcloud.sync.credentials.webflow ]:	Get QNAM
    2021-05-24 13:45:26:592 [ info nextcloud.gui.account.manager ]:	Restored:  0  unknown certs.
    2021-05-24 13:45:26:610 [ debug nextcloud.gui.activity ]	[ OCC::User::setNotificationRefreshInterval ]:	Starting Notification refresh timer with  300  sec interval
    2021-05-24 13:45:26:709 [ info nextcloud.gui.folder.manager ]:	Setup folders from settings file
    2021-05-24 13:45:26:711 [ info plugins ]:	Created VFS instance for: "win"
    2021-05-24 13:45:26:712 [ info nextcloud.sync.database ]:	Detected filesystem "NTFS" for "d:/nextcloud/.sync_e7b8ae9d9552.db"
    2021-05-24 13:45:26:713 [ debug nextcloud.gui.folder ]	[ OCC::Folder::checkLocalPath ]:	Checked local path ok
    2021-05-24 13:45:26:715 [ info nextcloud.sync.configfile ]:	Adding user defined ignore list to csync: "C:/Users/micro/AppData/Roaming/Nextcloud/sync-exclude.lst"

**Comment by andyxheli** [comment] 2021-06-14 20:32
Same issue Windows 10 Pro 20H2 client 3.2.2 seems to happen when having virtual file support

**Comment by bones1014** [comment] 2021-06-15 00:04
I have the same problem with 3.2.2 in windows 10. It crashes almost immediately. I deleted the folder in appdata and I emptied the sync folder so there wouldn't be anything for it to do.

**Comment by weiw11** [comment] 2021-06-15 00:07
Look at the issue I referenced. It's because of the sync exclude file in your nextcloud folder.

**Comment by bones1014** [comment] 2021-06-15 00:22
> Look at the issue I referenced. It's because of the sync exclude file in your nextcloud folder.

I deleted that file and ran it again with no other changes and it runs until I add something to the sync folder.

**Comment by weiw11** [comment] 2021-06-15 23:48
You have to make sure to select that file to always be downloaded. Otherwise it'll freeze.

I just ended up moving it outside of my folder until the patch comes out.

**Comment by bones1014** [comment] 2021-06-18 17:39
That file isn't in my syncing folder. It's in  appdata\roaming\nextcloud

**Comment by weiw11** [comment] 2021-06-18 17:42
The freeze is caused by the file in the syncing folder. Do a search for the file on syncing folder and delete/move any found. Or just right click and set them to be always downloaded.

**Comment by allexzander** [comment] 2021-07-18 08:18
@weiw11 Is the issue still present in 3.2.4? The .sync-exclude file is now always downloaded with no way to make it virtual. This should fix the problem.

**Comment by weiw11** [comment] 2021-07-18 17:58
No, it's not present as the crash was due to the sync file.

**Comment by allexzander** [comment] 2021-07-19 07:55
https://github.com/nextcloud/desktop/pull/3390

**Closed by allexzander** 2021-07-19 07:55 UTC
Labels: bug, crash, feature: :minidisc: virtual filesystem

**Comment by godfuture** [comment] 2021-07-23 18:14
The client 3.2.4 (and previous) is very unstable freezing a lot of times when using and clicking in the GUI. Sync is not working reliably. Issues when trying to open files directly.

This thing is not usable. Will there be a big bug fix release?
