### ISSUE TITLE
[Bug]: Unresponsive Solve All Conflicts Window when too large for screen

### ISSUE THREAD

**Issue by djamn** [nextcloud/desktop#6340] opened 2024-01-08 11:44 UTC
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

After having multiple file conflicts to solve in my Desktop Sync Client, the opened Window to solve all issues at once does not adapt to my screen size and the buttons do not appear within my screen.

### Steps to reproduce

Have multiple file conflicts
Click on the button "Solve conflicts" in the Desktop Client
If you have a too little screen, the popup wont be fully visible
Hint: This issue is also existent when trusting a new certificate

Hardware: Acer Switch 5 (Resolution 2160x1440)

### Expected behavior

The solve all conflicts window must adapt to the screen size

### Which files are affected by this bug

-

### Operating system

Windows

### Which version of the operating system you are running.

Windows 11

### Package

Other

### Nextcloud Server version

26.0.10

### Nextcloud Desktop Client version

3.11.0

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [X] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Additional info

[debug_archive_08012024.zip](https://github.com/nextcloud/desktop/files/13859494/debug_archive_08012024.zip)
![Screenshot_143](https://github.com/nextcloud/desktop/assets/87384392/296ba819-edd1-4f9f-9ab8-2fe939807e3c)

**Comment by tomdereub** [comment] 2024-07-09 06:54
Same as https://github.com/nextcloud/desktop/issues/5846

**Comment by joshtrichards** [comment] 2024-08-16 05:48
Duplicate of #5846

**Closed by joshtrichards** 2024-08-16 05:48 UTC
Labels: 0. Needs triage, bug, feature: :cloud: system tray, hotspot: visual
