### ISSUE TITLE
[Bug]: v3.5.0 (release), Macos 10.13.6, Finder extension troubles

### ISSUE THREAD

**Issue by labor4** [nextcloud/desktop#4527] opened 2022-05-13 22:11 UTC
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

**Right-Click Context Menu** is inconsistent (disappears after some minutes, tested: 3mins)
**File's status symbols** are inconsistent (disappears after some minutes, tested: 3mins)

### Steps to reproduce

- had latest 3.4.4 installed
- installed Macos pkg OVER current installation (didn't delete Nextcloud.app first)
- restarted Nextcloud.app
- began browsing into the NC folders (may be the trigger, instead of the minutes)

Problem gone after downgrade to 3.4.4.
Confirmed again, updating from a fresh 3.4.4 install (deleted Nextcloud.app first)

### Expected behavior

- Right-Click Context Menu should stay visible
- Symbols should stay visible

### Which files are affected by this bug

Context Menu in Macos

### Operating system

Mac OS

### Which version of the operating system you are running.

10.13.6 High Sierra, Client Package: Github Release Download

### Package

Other

### Nextcloud Server version

Nextcloud Hub II (23.0.4)

### Nextcloud Desktop Client version

3.5.0

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 3.3.6 to 3.4.0)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [X] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by claucambra** [comment] 2022-05-16 12:05
Hi, since this is a duplicate of #4459 I will close this issue, thanks however for your report

**Closed by claucambra** 2022-05-16 12:05 UTC
Labels: 0. Needs triage

**Comment by claucambra** [comment] 2022-05-16 15:46
> oops. how did i not see that!

No worries, it happens :)
