### ISSUE TITLE
Green check showing when status is Preparing for sync

### ISSUE THREAD

**Issue by skewty** [nextcloud/desktop#678] opened 2018-09-17 04:05 UTC
Green check, I believe, is for fully synched up.
I thought the small folder I told it to sync was already finished, but it turns out the sync process on a brand new install of NC hadn't even started yet.  Perhaps just setting another icon initially if nothing is configured to sync or on first run to prevent this somewhat false indication.

Thanks!

**Comment by camilasan** [comment] 2018-10-01 16:02
Hi! What is the operating system? Is it one of the daily builds?

**Comment by skewty** [comment] 2018-10-01 16:49
Client was 2.3.3 and OS was Elementary Juno 5.0b (Ubuntu 18.04 base) when I filed that report.

**Comment by camilasan** [comment] 2018-10-01 16:55
Then I would suggest you to try one of the daily builds with a test account to check if this is still happening. 
https://download.nextcloud.com/desktop/daily/
Thanks!

**Comment by timmersr** [comment] 2018-12-01 10:40
I'm using client v2.5.0 (build 20181112). I have multiple accounts and mapsyncs. On startup the tray icon shows green. This will be mistaken for "syncing has finished". It then changes a couple of times back and forth from green to the blue syncing icon, and stay there when it starts to sync larger folders. Finally it turns green, but actually it will still be syncing:

![1](https://user-images.githubusercontent.com/31093459/49327148-ac859780-f55d-11e8-91de-94d02f7dfb85.png)

**Comment by michaelstingl** [comment] 2018-12-01 18:34
Very old discussion in the upstream project: https://github.com/owncloud/client/issues/2432

**Comment by camilasan** [comment] 2021-02-12 15:48
Hi, Could you try to run the most recent desktop client and server to check if you still have this issue? The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients) and [https://nextcloud.com/install/#instructions-server](https://nextcloud.com/install/#instructions-server) respectively.

If you still have this problem with the latest desktop client, please re-open the issue.

Thanks!

**Comment by LukeOwlclaw** [comment] 2021-04-05 10:09
This problem still persists with version 3.1.3.

![image](https://user-images.githubusercontent.com/2737900/113563279-b6c17000-9607-11eb-890d-cf04d5cc7d66.png)

**Comment by LukeOwlclaw** [comment] 2021-04-05 10:11
Closing because this issue is a duplicate of https://github.com/nextcloud/desktop/issues/619

**Closed by LukeOwlclaw** 2021-04-05 10:11 UTC
