### ISSUE TITLE
Windows Desktop Client Can't Login

### ISSUE THREAD

**Issue by systemlevel** [nextcloud/desktop#1221] opened 2019-04-26 00:41 UTC
### Expected behaviour

Be able to Log in

### Actual behaviour

Endless loop from the underworld.

### Steps to reproduce
1) Type in username and password
2) Enjoy the show.

Using latest version of Windows Desktop Client.

**Comment by dagomar** [comment] 2019-04-26 10:11
I am running the linux client (manjaro) and experience the same issue. 
Client is 2.5.2
Nextcloud is 15.0.2

Any help much appreciated!

**Comment by systemlevel** [comment] 2019-04-26 16:19
> I am running the linux client (manjaro) and experience the same issue.
> Client is 2.5.2
> Nextcloud is 15.0.2
> 
> Any help much appreciated!

Same versioning here as well.

**Comment by dasmaeh** [comment] 2019-04-28 15:40
Same problem for me with 
Client 2.5.2 (on arch linux)
Nextcloud 15.0.7 snap install on debian

Using an app token alternatively fails with error 405

**Comment by dagomar** [comment] 2019-05-03 06:23
I've been able to troubleshoot by running the application from the command line and looking at the debug logs. ($ nextcloud --logwindow --logdebug)

I found that there was a problem with https/http. The login page was loading over https, but the form action pointed at http. I was able to fix this by adding the following options to my config.php on the webserver:

`
'overwrite.cli.url' => 'https://your-url.com',
'overwriteprotocol' => 'https',
'forcessl' => true,
 'forceSSLforSubdomains' => true,
`

I'm not 100% sure all of the above is necessary but it did the trick for me. Note that 'overwrite.cli.url' was on the http version when I first looked, which confirmed my suspicion of a wrong configuration on the server.

The only problem I have now is that I am running the docker container server, and I am not mounting the config folder, which means that on an upgrade of the server this config will be lost for me. If anyone knows if it's possible to influence these settings through docker env vars that would be of great help.

In any case, I'd wager all of you are having the same issue, so I hope this helps!

**Comment by dasmaeh** [comment] 2019-05-03 14:57
I can confirm 
```
'overwrite.cli.url' => 'https://your-url.com',
'overwriteprotocol' => 'https',
```
does the trick for me.
This is probably a problem in all kinds of setups where nextcloud is running behind a proxy that does tls termination.

**Comment by lucrito** [comment] 2019-05-03 14:58
I can confirm, that adding `'overwriteprotocol' => 'https',` to config.php did the trick for me.
I already had `'overwrite.cli.url' => ...` and `'forcessl' => true,`. 
I didn't add `'forceSSLforSubdomains' => true,`
After a restart of Nextcloud I could finaly log in with a client > 2.5.x
I run Nextcloud 16 on Docker behind a nginx proxy.

**Comment by camilasan** [comment] 2019-05-07 19:57
Interesting. I will close it since it is a server configuration issue.

**Closed by camilasan** 2019-05-07 19:57 UTC

**Comment by garywu520** [comment] 2019-12-19 09:48
> 通过从命令行运行应用程序并查看调试日志，我已经能够进行故障排除。（$ nextcloud --logwindow --logdebug）
> 
> 我发现https / http有问题。登录页面正在通过https加载，但是表单操作指向http。我可以通过在网络服务器上的config.php中添加以下选项来解决此问题：
> 
> ```
> 'overwrite.cli.url' => 'https://your-url.com',
> 'overwriteprotocol' => 'https',
> 'forcessl' => true,
> 'forceSSLforSubdomains' => true,
> ```
> 
> 我不是100％确信以上所有内容都是必要的，但这确实帮了我大忙。请注意，当我初次查看时，“ overwrite.cli.url”在http版本上，这证实了我对服务器配置错误的怀疑。
> 
> 我现在唯一的问题是我正在运行Docker容器服务器，并且没有安装config文件夹，这意味着在服务器升级时，该配置将对我丢失。如果有人知道是否有可能通过docker env vars影响这些设置，那将有很大的帮助。
> 
> 无论如何，我都会下注所有人都遇到同样的问题，所以我希望这会有所帮助！

I ran it on Docker, these 3 lines of configuration solved my problem, thanks!

**Comment by garywu520** [comment] 2019-12-19 09:49
> I've been able to troubleshoot by running the application from the command line and looking at the debug logs. ($ nextcloud --logwindow --logdebug)
> 
> I found that there was a problem with https/http. The login page was loading over https, but the form action pointed at http. I was able to fix this by adding the following options to my config.php on the webserver:
> 
> ```
> 'overwrite.cli.url' => 'https://your-url.com',
> 'overwriteprotocol' => 'https',
> 'forcessl' => true,
> 'forceSSLforSubdomains' => true,
> ```
> 
> I'm not 100% sure all of the above is necessary but it did the trick for me. Note that 'overwrite.cli.url' was on the http version when I first looked, which confirmed my suspicion of a wrong configuration on the server.
> 
> The only problem I have now is that I am running the docker container server, and I am not mounting the config folder, which means that on an upgrade of the server this config will be lost for me. If anyone knows if it's possible to influence these settings through docker env vars that would be of great help.
> 
> In any case, I'd wager all of you are having the same issue, so I hope this helps!



I ran it on Docker, these 3 lines of configuration solved my problem, thanks!
