### ISSUE TITLE
Mac Menu Bar Icon Size

### ISSUE THREAD

**Issue by donnydark0** [nextcloud/desktop#3752] opened 2021-09-06 10:35 UTC
The menu bar icon is too large. Please reduce the size to fit the other menu bar icons in MacOS Big Sur and Monterey.

**Comment by BJKle** [comment] 2021-09-06 14:36
Guess it is a duplicate of #3549.
It will disappear, with a native M1 build.

**Comment by mgallien** [comment] 2021-09-06 16:03
> Guess it is a duplicate of #3549.
> It will disappear, with a native M1 build.

thanks for the hint
so closing due to being a duplicate indeed of #3549

**Comment by elsiehupp** [comment] 2021-09-07 07:18
This is also a duplicate of the much older #2584.

**Closed by elsiehupp** 2021-09-07 07:18 UTC
Labels: bug
