### ISSUE TITLE
Login prompt broken broken on macOS since release 2.6.3

### ISSUE THREAD

**Issue by realrolfje** [nextcloud/desktop#1793] opened 2020-02-17 14:04 UTC
Installed Registration Wizard 2.6.3, build 2020217 on MacOS, tried to register a second account.

### Expected behaviour
After filling in the url of my owncloud server, I expect the login page to appear in the registration wizard.

### Actual behaviour
The login page loads (I checked that my server serves it), the wizard blinks the login page briefly, but then collapses it into a 4 pixel high blue bar at the top of the window, making all the UI components invisible and unusable.

### Steps to reproduce
1. Install Sync Client 2.6.3 build 20200217 on MacOS 10.15.3 Catalina
2. Open Sync client
3. Click on "Account" top right, and select "Add new"
4. Fill in the server url, click next.
5. A window with an embedded browser appears, but the browser immediately collapses to a bar at the top of the window.

### Client configuration
Client version: 2.6.3 build 20200217 64 bit for MacOS

Operating system: MacOS 10.15.3 Catalina

OS language: English

Qt version used by client package (Linux only, see also Settings dialog): n/a

Client package (From Nextcloud or distro) (Linux only): n/a

Installation path of client: Applications folder

### Server configuration
NextCloud 15.0.14, updated today. Older Sync Client did succesfully display the login page

**Comment by misch7** [comment] 2020-02-18 01:26
> ### Expected behaviour
> 
> After filling in the url of my owncloud server, I expect the login page to appear in the registration wizard.

> ### Server configuration
> 
> NextCloud 15.0.14, updated today. Older Sync Client did succesfully display the login page

To clarify: Are you using ownCloud or Nextcloud server?

**Comment by realrolfje** [comment] 2020-02-18 06:50
Sorry for the typo. It is a NextCloud 15.0.14. (Force of habbit; I used to run an OwnCloud server years ago)

**Comment by devi69** [comment] 2020-03-03 08:12
Hi,

I confirmed that I could not connect. I will experience the same symptoms as reported in this issue.

With the same desktop client configuration, I could not connect to Nextcloud 14.0.7, but it worked fine with Nextcloud 17.0.2. From the situation, I guessed that the connection status was different depending on the Nextcloud version. Is Nextcloud 15 or below no longer supported?

* Client version: 2.6.3 (build 20200217)
* Operating system: MacOS 10.15.3 Catalina

**Comment by mitsol** [comment] 2020-03-04 19:30
exactly the same issue here!

- client version: Version 2.6.4stable (build 20200303)
- operating system: MacOS 10.15.3

**Comment by jokuha** [comment] 2020-04-16 06:02
Realizing this issue now, which I apparently duplicated in #1888, let me point out the _workaround_ described there that works: Install the client in version 2.6.2, authorize, then upgrade to 2.6.4 again.

**Comment by claell** [comment] 2020-04-16 09:55
I added labels and edited the title to outline the problem better. I hope I got it right and #1888 is a duplicate of this.

**Comment by wilhelm10405** [comment] 2020-05-04 14:02
<img width="952" alt="Bildschirmfoto 2020-05-04 um 16 02 12" src="https://user-images.githubusercontent.com/21079930/80974135-a06fca80-8e20-11ea-92e6-ecc830f43e08.png">

Got the same problem! 10.15.1 on MacBook Pro 13"

**Comment by boualidev** [comment] 2020-05-04 16:32
Got the same problem.

<img src="https://i.imgur.com/y2Cil6u.png" alt="Kitten" />

**Comment by psoluch** [comment] 2020-05-28 18:57
Hi. I have the same issue. Any chance to get a solution soon?

**Comment by jokuha** [comment] 2020-05-28 20:13
> Any chance to get a solution soon?

see workaround [above](https://github.com/nextcloud/desktop/issues/1793#issuecomment-614433531)

**Comment by jaseeverett** [comment] 2020-06-11 02:43
Same problem here with 2.6.4stable (build 20200303) installed on macOS Catalina. I had previously been using Nextcloud successfully, but today I was logged out of the NextCloud app, and now can't log back in with the same issue as the users with a new install. I will downgrade for the moment I guess.

**Comment by soto97** [comment] 2020-06-19 20:44
I continue to have the problem reported above, even when I tried the workaround. Neither v2.6.1 nor v2.6.2 will let me successfully connect. I am using macOS Catalina 10.15.3 on a MacBook Pro. After entering the server address, the login screen flashes up for a few seconds and then I end up with a screen just like the one shown by wilhelm10405 above.

Hopefully this will get fixed sometime soon. Thanks!

**Comment by frederic-bonjour** [comment] 2020-07-08 07:18
As @jokuha said, install version 2.6.2, log in to your account(s) and then upgrade to latest version.
Version 2.6.2 that works can be downloaded fro here:
https://download.nextcloud.com/desktop/releases/Mac/Installer/
Enjoy :)

**Comment by tumkir** [comment] 2020-07-21 09:41
Same problem with 2.7beta3 on macOS 10.15.6

**Comment by liz3** [comment] 2020-08-02 15:38
Can also confirm on 2.6.5, collapses into a small bar at the top

**Comment by milkomeda** [comment] 2020-08-07 08:25
Same problem here

**Comment by camilasan** [comment] 2020-08-07 11:48
Hi All, could you share your logs? Run the client with --logdebug.
https://docs.nextcloud.com/desktop/2.6/troubleshooting.html#log-files
thanks1

**Comment by scgu0003** [comment] 2020-08-15 07:47
Sure.
[NC-no-login-log.txt](https://github.com/nextcloud/desktop/files/5078328/NC-no-login-log.txt)

**Comment by jokuha** [comment] 2020-08-15 08:30
see https://github.com/nextcloud/desktop/issues/1793#issuecomment-614433531

**Comment by pugnari** [comment] 2020-09-05 13:04
The same problem persists on 3.0.1, at least for me.

**Comment by camilasan** [comment] 2020-09-15 13:22
Hi All, could you try https://download.nextcloud.com/desktop/daily/Mac/Installer/Nextcloud-qt5.12.9-3.1.0.20200915daily.pkg and let me know if you still have the issue?
Thanks!

**Comment by jaseeverett** [comment] 2020-09-16 01:22
Hi @camilasan 
No it doesn't fix it for me. It looks nice when I first install but if I log out and try and log back in, I get the same screen with the login window a few pixels high.
Back to the 2.6.2 for me.... 

<img width="790" alt="Screen Shot 2020-09-16 at 11 20 09 am" src="https://user-images.githubusercontent.com/6644980/93281059-9ae2b200-f80e-11ea-974f-2f12e6680642.png">

**Comment by jokuha** [comment] 2020-09-16 05:56
I have not tried this special version, but I could login when I upgraded to regular 3.0 as it directed me to the browser, authenticated there, then the client run.

**Comment by pugnari** [comment] 2020-09-16 23:31
Thank you @camilasan. I tried this version, but it still suffers from the same phenomenon. 
Is it related to the preference files of older versions?
<img width="908" alt="スクリーンショット 2020-09-17 8 19 48" src="https://user-images.githubusercontent.com/70806958/93402592-29fbd280-f8c0-11ea-8729-f5fc42ddf1c6.png">


> Hi All, could you try https://download.nextcloud.com/desktop/daily/Mac/Installer/Nextcloud-qt5.12.9-3.1.0.20200915daily.pkg and let me know if you still have the issue?
> Thanks!

**Comment by jaseeverett** [comment] 2020-09-16 23:49
@pugnari @camilasan I just tried completely removing all previous versions of NextCloud (including prefs etc) using AppCleaner. Restarted and reinstalled NextCloud but it still goes straight to the same blue line for the login window.

**Comment by camilasan** [comment] 2020-09-18 11:28
We have fixed it:
https://download.nextcloud.com/desktop/daily/Mac/Installer/Nextcloud-qt5.12.9-3.1.0.20200918daily.pkg

This is just a daily build but the fix will be included in the 3.0.2 release next week.

**Closed by camilasan** 2020-09-18 11:28 UTC
Labels: approved, bug, feature: :key: authentication, high, os: :apple: macOS, regression
