### ISSUE TITLE
[Bug]: Windows is positioning incorrectly on MacOS

### ISSUE THREAD

**Issue by karlitschek** [nextcloud/desktop#5268] opened 2022-12-13 08:02 UTC
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

The window is positioned incorrectly on MacOS. The top of the windows is off screen so that the client can't be closed. Force quit and reopen solves it. This happend to me several times already.

![positioning](https://user-images.githubusercontent.com/867445/207259331-7e682f09-9f74-47c3-beab-08beb5cb80ef.png)

### Steps to reproduce

1. Right click on the file
2. Click on Share Options
3. The share dialog does not display the option to share by e-mail
...

### Expected behavior

When clicking on the share dialog, share by e-mail should be an option.
...

### Which files are affected by this bug

no files

### Operating system

Mac OS

### Which version of the operating system you are running.

MacOS Ventura

### Package

Other

### Nextcloud Server version

25.0.2

### Nextcloud Desktop Client version

36.50

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 3.4.2 to 3.4.4)

### Are you using the Nextcloud Server Encryption module?

Encryption is Enabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by claucambra** [comment] 2022-12-13 11:30
This is most likely an upstream issue in Qt as we are taking the position of the tray window icon and the dimensions of the current screen from values provided by a Qt API. It seems ike this error appears on machines with more than one screen with different DPIs

So the fix we have in the works is generally a migration to Qt6 which might fix this. That PR is open and waiting for review #4584

**Comment by karlitschek** [comment] 2022-12-14 10:23
This was only using one screen. And it was gone after killing the client and relaunching. It's possible that this bug happened since 5 days ago when I actually had a second screen plugged in. not sure.

**Comment by rinal13** [comment] 2023-02-10 00:04
> This is most likely an upstream issue in Qt as we are taking the position of the tray window icon and the dimensions of the current screen from values provided by a Qt API. It seems ike this error appears on machines with more than one screen with different DPIs

I have this issue also, but I can confirm it happens when I change from the external monitor back to the internal,
probably because the have different DPIs.
When i restart  the app the position is aligned again

**Comment by jospoortvliet** [comment] 2023-10-20 14:22
So I am having this, pretty reliably, after I plugged in a screen and then - a while later, take it out. Screenshot is similar:
<img width="686" alt="Screenshot 2023-10-20 at 13 51 31" src="https://github.com/nextcloud/desktop/assets/551757/b22f5e0b-83b9-498e-b8a6-da2cc870072c">

**Comment by karlitschek** [comment] 2023-10-21 21:42
yes. same here. It somehow remembers the geometry wrongly when the screens change. A related problem is that the size of the menubar on top is different if you have an M2 Macbook with the camera in the menubar (it's a bit bigger) or an external screen were the menubar is a bit smaller. This can lead to the result that the Desktop Client windows is a few pixels below the menubar when unplugging an external screen.

**Comment by toto** [comment] 2023-11-07 08:22
Same. It makes using nextcloud with multiple screens super annoying since you can't even reach the (horribly named) "Exit" menu in many cases to restart and fix the issue.

**Comment by jospoortvliet** [comment] 2023-11-10 07:45
> Same. It makes using nextcloud with multiple screens super annoying since you can't even reach the (horribly named) "Exit" menu in many cases to restart and fix the issue.

yup, have to use the process manager/monitor app.

**Comment by claucambra** [comment] 2023-11-13 07:23
Unfortunately this is not a bug in our codebase but in `QSystemTrayIcon` provided by Qt

Once we are able to compile against Qt 6 (#4584) we should be able to check if this is fixed upstream; if not I can see if there is something we can work on upstream

**Comment by jospoortvliet** [comment] 2023-11-14 18:57
Ok, understood. Hope Qt6 comes soon then ;-)

**Comment by tram98** [comment] 2024-01-09 08:00
Happens on my machine, too. :( Looking forward to a fix! ;)

**Comment by tobiasKaminsky** [comment] 2024-03-14 06:03
top panel: bug: change screen resolution, when adding/removing external display
if in middle, then not responsive

**Comment by claucambra** [comment] 2024-10-16 07:49
This has been fixed with the change to Qt 6 in 3.14.0

**Closed by claucambra** 2024-10-16 07:49 UTC
Labels: 0. Needs triage, bug, feature: :cloud: system tray, Qt 6, hotspot: visual
