### ISSUE TITLE
Windows Desktop Client consider all .lnk files as symbolic link, although this is a regular file 

### ISSUE THREAD

**Issue by steve-s-71** [nextcloud/desktop#4023] opened 2021-12-02 08:05 UTC
### Expected behaviour
Windows Desktop Client should consider regular files NOT as symbolic link

### Actual behaviour
Windows Desktop Client consider all .lnk files (this is spelled lower case "L", lower case "N", lower case "K")  as symbolic link, although this is a regular file such as .exe .doc .jpg etc. 

### Steps to reproduce
1. create a file with file ending .lnk (this is spelled lower case "L", lower case "N", lower case "K")
2. open Desktop main window and watch the error "symbolic link are not synced"

### Client configuration
Client version: 3.4.0 (Windows)

Operating system:
Win 10

OS language:
Ger

Installation path of client:
C:\Program Files\Nextcloud\nextcloud.exe

**Comment by allexzander** [comment] 2021-12-03 10:34
duplicate of https://github.com/nextcloud/desktop/issues/3244

**Closed by allexzander** 2021-12-03 10:34 UTC
Labels: bug
