### ISSUE TITLE
Silently skips directories with invalid names, doesn't report error

### ISSUE THREAD

**Issue by vasyugan** [nextcloud/desktop#3991] opened 2021-11-20 14:25 UTC
This is related to #464. Today, I spent a long time trying to understand why a neighbour's Nextcloud desktop client failed to download and sync certain shared directories. 

After a while I understood that the reason was the : in their names. I would have saved quite a bit of time and effort, if the client had alerted me to the reason. Even after deleting and re-creating the folder synchronisation, there was no alert. So it was completely by accident that I remembered that I had seen instances in the past, where the desktop client had actually reported an error. 

### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour
 
The desktop client should report the reason why the directories are not synced.

### Actual behaviour
 
Directories are skipped , no error is reported.

### Steps to reproduce
1. Have a directory with : in the name on the server.
2. force re-sync of the folder. 
### Client configuration
Client version: 3.3.6

Operating system:
Windows 10

OS language:

German

**Comment by claell** [comment] 2021-11-24 10:01
Marking as duplicate of #464. Please add your comments there. If relevant, they might be included in the description there as well.

**Comment by claell** [comment] 2021-11-24 10:01
Duplicate of #464

**Closed** 2021-11-24 10:03 UTC
Labels: bug
