### ISSUE TITLE
Nextcloud desktop client on a 4K 15" monitor (Ubuntu 20.04 LTS)

### ISSUE THREAD

**Issue by wincotec** [nextcloud/desktop#2782] opened 2020-12-30 23:08 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour
After a restart, the messages from the desktop client should be displayed larger.

### Actual behaviour
The display of the desktop client on a 4K 15" monitor is so small that you can no longer read what is written there.

### Steps to reproduce
1. 
2.
3.

### Client configuration
Client version: 3.1.1

Operating system: Ubuntu 20.04 LTS

OS language: German

Qt version used by client package (Linux only, see also Settings dialog): 

Client package (From Nextcloud or distro) (Linux only): Nextcloud

Installation path of client:

### Server configuration

Nextcloud version: 20.0.4

Storage backend (external storage): mysql

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile: 

Output of `nextcloud --logdebug --logwindow` or `nextcloud --logdebug --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the Nextcloud directory)
(See also https://docs.nextcloud.com/desktop/2.3/troubleshooting.html#log-files)

2. Web server error log:

3. Server logfile: nextcloud log (data/nextcloud.log):

**Comment by er-vin** [comment] 2021-01-04 13:58
Duplicate of #2295

**Closed by er-vin** 2021-01-04 13:58 UTC
