### ISSUE TITLE
Nextcloud Update notification wrongly formatted on macOS

### ISSUE THREAD

**Issue by phol** [nextcloud/desktop#2361] opened 2020-09-03 21:34 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour

The link should be clickable or instructions on how to update should be provided

### Actual behaviour
An HTML link which isn't parsed is shown, please refer to the following image for an example:

<img width="330" alt="Screenshot 2020-09-03 at 23 27 12" src="https://user-images.githubusercontent.com/1392118/92176013-efb12080-ee3d-11ea-84f3-73159b33ba69.png">

### Steps to reproduce
1. Install macOS sync client
2. Enable desktop notifications
3. Wait for new Nextcloud desktop client release

### Client configuration
Client version: 3.0.0

Operating system: macOS 10.15.6

OS language: en_UK
Installation path of client: Applications

**Comment by er-vin** [comment] 2020-09-08 12:45
Duplicate of #1844

**Closed by er-vin** 2020-09-08 12:45 UTC
