### ISSUE TITLE
"Couldn't update placeholder info" Version 3.9.1stable-Win64 (build 20230725)

### ISSUE THREAD

**Issue by HEtchevers** [nextcloud/desktop#5955] opened 2023-08-04 19:48 UTC
This issue STILL exists with a slightly different error message in version 3.9.1: Couldn't update placeholder info. It has happened for (nearly) all of my nearly 6000 files and they all try to synchronize constantly and fruitlessly. They seem to be present on the server though.

![image](https://github.com/nextcloud/desktop/assets/45430373/92ff8771-018b-4a09-b17f-445947be5407)

--

Follow-up: in the "activity" bar online, it lists that I have either "changed" or "created" the individual files. I have been able to upload and sync some new files since, though, since this problem appeared a few days ago. 

In refusing the client update on my office desktop so far, I do not have any of these error messages and all appears to be normally sync'd with what is already on the server or new files I create. 

However, from my laptop, new data is not correctly uploaded and sync'd to the server.

_Originally posted by @HEtchevers in https://github.com/nextcloud/desktop/issues/4401#issuecomment-1663366396_

**Comment by allexzander** [comment] 2023-08-07 10:23
@HEtchevers 

What happens if you pause the sync of the current folder (in the Settings dialog context menu), and then add only that specific folder from the screenshot as the remote root as the second sync folder and uncheck "Use virtual files"? Do you have all those files synced, or are there errors displayed in that scenario too? Asking this for the sake of checking if the issue is with VFS or with how files are handled in case of general error.

**Comment by dancrick** [comment] 2023-08-14 13:29
I see the same warning messages (Couldn't update placeholder info), but only for files recently created. Any updates please? I am on version 3.9.2 (windows-10.0.19044). Thanks.

**Comment by HEtchevers** [comment] 2023-08-14 13:34
> @HEtchevers
> 
> What happens if you pause the sync of the current folder (in the Settings dialog context menu), and then add only that specific folder from the screenshot as the remote root as the second sync folder and uncheck "Use virtual files"? Do you have all those files synced, or are there errors displayed in that scenario too? Asking this for the sake of checking if the issue is with VFS or with how files are handled in case of general error.

Apologies for not getting back to this quickly. I ended up simply removing Nextcloud from the problematic computer (which changes my workflow) waiting for another version. However, given @dancrick 's posting, I will go back and try with 3.9.2. When I paused the sync before as requested, @allexzander , I did have the same error even without the use of virtual files. I'll try again tonight when I can. Meanwhile, on my office computer, I'm sticking with a functioning 3.9.0 for now.

**Comment by Wonderkitten** [comment] 2023-08-15 09:27
Same issue on 3.9.2 windows-10.0.19045 - but was localised to files within a certain folder. 

It was resolved by manually creating another folder and moving the files across (all within the web interface). Desktop client is now syncing everything happily.

**Closed** 2023-08-16 13:05 UTC
