### ISSUE TITLE
Conflicted files visibility

### ISSUE THREAD

**Issue by Aesculapius** [nextcloud/desktop#1332] opened 2019-07-08 08:50 UTC
### Expected behaviour
When a confllict exists for the desktop client, it gives a warning in the client (yellow exclamation mark). Clicking on that specific line then takes you to the activity tab, where one would expect to see what the exact conflict is and how to best resolve it.

### Actual behaviour
When getting to the activity tab, one sees a gigantic list of warnings about hidden files and files on the ignore lists. You have to scroll down endlessly and hope to not have a refresh of the list to be able to find the conflicting line.

Then even if you've found that line, there's too little information to solve the issue. You're not seeing the complete filename (missing the extention) and double clicking on it brings you to the folder in question but with a lot of files in there, still difficult to resolve. 

Even then it is unsure how to best resolve the conflict. Most of the time I end up renaming local files and merging stuff together manually.

### Steps to reproduce
1. Generate a conflict by editint a file at the same time on multiple machines...
2. Watch the GUI of desktop client and activity tab

### Client configuration
Client version: 2.5.2git (build 20190319)

Operating system: Windows 10

OS language: English

Installation path of client: "C:\Program Files (x86)\Nextcloud\nextcloud.exe"

### Server configuration
Nextcloud version: 16.0.1

Storage backend (external storage): local

Screenshot: 

![nextcloud-client-1](https://user-images.githubusercontent.com/617061/60796670-202ff880-a16e-11e9-9a49-368b3ebcc959.jpg)

![nextcloud-client-2](https://user-images.githubusercontent.com/617061/60796678-24f4ac80-a16e-11e9-9749-9d2383383b81.jpg)

**Comment by vvombat** [comment] 2019-08-02 11:18
I was going to open a new issue for my feature request: But I think this would get merged with this one anyways:

In addition to maybe hightlight the conflicting files or jumping to the regarding line(s) in the activity tab, having a checkbox of sorts "Show ignored files." on top would make the activity tab much more readable. If I added a file to the ignore list, I want to ignore and therefore not see it anymore.

_If you want me to open a new issue for my feature request please let me know - I will do so. Sorry if I hijacked this issue in that case._

**Comment by wolfspyre** [comment] 2019-08-05 18:02
I wholeheartedly concur with this. It is near impossible to identify what is causing the desktop client grief, from my perspective.  This has kinda always been the case... but I would sincerely LOVE to see this mechanism capable of steering the user to the root of the problem with enough information to be able to resolve it... 

As is, it’s sorta like having someone take you frantically into a room, screaming that they can’t find the key they are looking for, and inside that room, there are huge piles of key blanks of many different sizes shapes and colors... the person then says ‘can you find the key I need please? I can’t continue without it’ and then goes completely mute...

You have no information to move forward, are surrounded by noise, and told to find the problem herself....

At best, this is irritating. Usually it compels one to give up because there is no clear path... hell there isn’t even a semi-obvious but treacherous path... to homeostasis.

**Comment by jancborchardt** [comment] 2019-08-15 08:33
This is a duplicate of **Activity tray and activity list design improvements #889**, and as written there:

> - Warnings for symlinks should be grouped into only one row. `Symbolic links are not supported in syncing: keeporsweep.py, nextcloud-update.sh, and 3 others`. Alternatively, symlinks on macOS and Linux should just be synced. #605 
> - Warnings for ignored files should not even be there? Because they are ignored, they should be ignored everywhere. (At most, again just one row: `Files not synced because of ignore list rules: ._DS_Store, .gitblasomething, and 200 more`)

**Closed by jancborchardt** 2019-08-15 08:33 UTC
