### ISSUE TITLE
Virtual folder: rename a file deletes it

### ISSUE THREAD

**Issue by biva** [nextcloud/desktop#3434] opened 2021-06-11 13:57 UTC
On 3.2.2, under Windows 10, I did these steps:

1. In the Windows Explorer, go to a virtual folder, where files are not available locally
2. Click on a file, wait, click again to rename it
3. Rename it, press Enter
4. Wait a few seconds
5. The file disappears

Server version 21.0.2

**Comment by biva** [comment] 2021-06-11 14:23
This leads to data loss: files are not in the deleted files on the Web UI, and they are not in the Recycle Bin in Windows :(

**Comment by biva** [comment] 2021-06-11 14:28
After a few minutes, I could recover the files in the **Deleted** folder

**Comment by biva** [comment] 2021-06-11 14:29
If I make the files available locally, then rename it, the files are not deleted.

**Comment by FlexW** [comment] 2021-06-11 15:34
Duplicate of https://github.com/nextcloud/desktop/issues/3379

**Closed by FlexW** 2021-06-11 15:34 UTC
Labels: bug

**Comment by biva** [comment] 2021-06-11 19:22
Hello @FlexW Maybe there's something I don't understand, but how is this issue a duplicate of #3379? My situation does not involve any encrypted folder and it's not about moving but about renaming.

Maybe I miss something?

**Comment by FlexW** [comment] 2021-06-11 19:34
Yes,it's a little bit misleading because this issue was originally about encryptes files. I adjusted the headline of the issue but didn't changed the description, but the issues are about the same problem. I will adjust the description too.

**Comment by biva** [comment] 2021-06-11 20:10
Thanks for your quick answer, I understand now. This is a very critical issue as far as I understand: I'm surprised that it's discovered only now. Thanks for being involved on it ;)

**Comment by biva** [comment] 2021-07-21 16:32
For information, this is solved on 3.2.4
