### ISSUE TITLE
Nextcloud client notifications using owncloud branding on Ubuntu 18.04 lock screen

### ISSUE THREAD

**Issue by despens** [nextcloud/desktop#414] opened 2018-06-12 07:10 UTC
![img_20180612_0859592](https://user-images.githubusercontent.com/571494/41275036-db27e798-6e1f-11e8-9748-d2ad91fdd535.jpg)

On Gnome's lock screen, Nextcloud notifications are shown as owncloud notifications.

The same seems to be true for the notification area:

![screenshot from 2018-06-12 09-07-35](https://user-images.githubusercontent.com/571494/41275174-549d6fb2-6e20-11e8-9992-6fba499335ee.png)

**Comment by juliushaertl** [comment] 2018-06-18 17:29
Duplicate of #28 
This is already fixed on master and will available be in the next client release.

**Closed by juliushaertl** 2018-06-18 17:29 UTC
