### ISSUE TITLE
[Bug]: Nextcloud_sync.log file keeps being recreated in .local/share/Nextcloud

### ISSUE THREAD

**Issue by closingin** [nextcloud/desktop#6791] opened 2024-06-04 08:34 UTC
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

Hello there :wave: 

It seems like the client refuses to keep its `Nextcloud_sync.log` file in the `/home/[user]/.config/Nextcloud` directory. No matter what I do, the client keeps re-creating its log file in `.local/share/Nextcloud`, even after total directory deletion.

### Steps to reproduce

1. Delete the old `.local/share/Nextcloud` directory
2. Start Nextcloud
3. Everything starts correctly (no output error), but the `.local/share/Nextcloud` is recreated with the `Nextcloud_sync.log`
4. Restart Nextcloud, this output shows up :
```
nextcloud.gui.application: Migrating old config from "/home/[user]/.local/share/Nextcloud" to "/home/[user]/.config/Nextcloud"
nextcloud.gui.application: Failed to move the old config directory to its new location ( "/home/[user]/.local/share/Nextcloud" to "/home/[user]/.config/Nextcloud" )
nextcloud.gui.application: Will move the individual files ("Nextcloud_sync.log")
```
6. Everything starts correctly, a new `Nextcloud_sync.log` is created in `.config/Nextcloud`, but only the one in `.local/share/Nextcloud` gets updated
7. Restart Nextcloud, this output shows up :
```
nextcloud.gui.application: Migrating old config from "/home/[user]/.local/share/Nextcloud" to "/home/[user]/.config/Nextcloud"
nextcloud.gui.application: Failed to move the old config directory to its new location ( "/home/[user]/.local/share/Nextcloud" to "/home/[user]/.config/Nextcloud" )
nextcloud.gui.application: Will move the individual files ("Nextcloud_sync.log")
nextcloud.gui.application: Fallback move of  "Nextcloud_sync.log" also failed
```
8. Everything starts correctly, the `.local/share/Nextcloud_sync.log` gets updated, the `.config/Nextcloud` one is left abandoned, without being updated
9. Rinse and repeat

### Expected behavior

I think the log file should now be `.config/Nextcloud/Nextcloud_sync.log`, the `.local/share/Nextcloud` one should not be recreated if it doesn't exist anymore.

### Which files are affected by this bug

.config/Nextcloud/Nextcloud_sync.log

### Operating system

Linux

### Which version of the operating system you are running.

Arch Linux

### Package

Distro package manager

### Nextcloud Server version

Unknown

### Nextcloud Desktop Client version

3.13.0

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 3.4.2 to 3.4.4)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [X] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by mgscreativa** [comment] 2024-06-04 14:27
the same here!

**Comment by claucambra** [comment] 2024-06-07 03:44
Can reproduce

**Comment by joshtrichards** [comment] 2024-08-14 21:24
Duplicate of #6201

**Closed by joshtrichards** 2024-08-14 21:24 UTC
Labels: 0. Needs triage
