### ISSUE TITLE
Client always asks for authentication

### ISSUE THREAD

**Issue by epsilontheta** [nextcloud/desktop#1716] opened 2020-01-11 14:24 UTC
### Expected behaviour
After authenticating once with the browser based scheme it should remember the credentials and use that when starting the client the next time.

### Actual behaviour
It always asks for credentials at start.

### Steps to reproduce
1. Start nextcloud client first time
2. Browser opens that requests login
3. Authenticate
4. Close client
5. Open client

### Client configuration
Client version: 2.6.2

Operating system: Fedora 31

OS language: English

Qt version used by client package (Linux only, see also Settings dialog): Qt 5.13.2

Client package (From Nextcloud or distro) (Linux only): nextcloud-client-2.6.2-1.fc31.src.rpm

Installation path of client: /usr/bin/nextcloud

### Server configuration

Nextcloud version: 17.0.2.1

Storage backend (external storage):

### Logs

1. Client logfile: https://gist.github.com/epsilontheta/6ddfd7b1057e19562a57e061a7f4abb6

2. Web server error log:

3. Server logfile: nextcloud log (data/nextcloud.log):

**Comment by veddox** [comment] 2020-01-15 18:06
This has been troubling me too for the past two weeks or so, although sometimes it does work.

Server version: 15.0.13
Client version: 2.6.2
Distro: elementary OS
Sanitised client log: https://gist.github.com/veddox/9e294ef45b61cf9510b8e53b247eab0b

Both log files contain the error `Unable to read "user_clientCaCertificatePEM0:https://cloud.example.com/:0" chunk "0"`

In my case, the app segfaults immediately after login.

**Comment by Croydon** [comment] 2020-01-16 06:49
I have similar behaviour on Windows 10 with Client 2.6.2

I don't need to login after every single client restart, but every 1-2 day or so

This didn't happen with older Nextcloud client versions

**Comment by toxpal** [comment] 2020-01-18 10:03
This issue is known for long time and devs claimed it was fixed in 2.6.2 (so they closed these issues), but problem was never fixed:

https://github.com/nextcloud/desktop/issues/1292
https://github.com/nextcloud/desktop/issues/1655

Hopefully it will be fixed...

**Comment by fab4x** [comment] 2020-01-27 16:59
I'm having the same issue on Linux Mint 19.3 (Xfce if that matters in any case) which is based on Ubuntu 18.04.1. After every reboot Nextcloud is asking for authentication. libgnome-keyring0(was a dependency so it came preinstalled) and libgnome-keyring-common won't fix it. Didn't try the AppImage yet but that's not really an alternative for me. If you need any further details (logfiles e.g.) let me know.

**Comment by Zulan** [comment] 2020-01-27 18:33
Can confirm with
Version 2.6.2git. For more information please click here.
This release was supplied by Nextcloud GmbH
Built from Git revision 1d7455 on Dec 24 2019, 12:35:56 using Qt 5.14.0, OpenSSL 1.1.1d 10 Sep 2019
on
Archlinux / Xfce

**Comment by clawoflight** [comment] 2020-01-30 15:07
I have the same problem.

**Comment by epsilontheta** [comment] 2020-01-31 15:19
Does not happen on my other machine (Arch) also running 2.6.2git but with the difference that I set it up using an older client and server version.

**Comment by ramonreschke** [comment] 2020-02-14 21:10
Same issue here on macOS.
Client version: 2.6.2
Server version: 18.0.0.10

**Comment by mhbates** [comment] 2020-02-19 17:08
Same issue, Windows 10. Happens every 1-2 days. Started once server was updated from 16 to 17, although it could still be tied to client version.

Client version: 2.6.3
Server version: 17.0.3

**Comment by toxpal** [comment] 2020-02-28 10:11
Also upgraded from 2.6.2 to 2.6.3, problem still exists.

**Comment by rochelmeyer** [comment] 2020-03-09 13:14
Same here with KDE neon 5.18.2, clients 2.6.3 and 2.6.4. I have 5 accounts at the moment and need to re-authorize those at each and every boot - can we upvote this as "Most Annoying Bug"?

**Comment by jartigag** [comment] 2020-03-09 13:42
It was debugged some time ago https://github.com/nextcloud/desktop/issues/1292#issuecomment-560008811, but it seemed to be fixed only in Fedora.

It certainly is a very annoying bug, pretty extended.. It may be worthwhile investing a little more time on it :)

**Comment by toxpal** [comment] 2020-03-09 14:16
Honestly, I already lost hope on this... :)

**Comment by rochelmeyer** [comment] 2020-03-10 15:16
In the meantime i was able to mitigate this problem by installing gnome-keyring - anyway, not certain which side effects this might have.

**Comment by MadFatVlad** [comment] 2020-03-23 09:54
I am having this problem on Arch Linux machine, while everything is ok on 2 Win10 machines.
Client version 2.6.3

**Comment by claell** [comment] 2020-04-04 19:41
@epsilontheta and the others, can you confirm that this is a duplicate of #1292?

**Comment by mhbates** [comment] 2020-04-04 19:44
I'm no longer getting this issue, most likely since update 17.0.4.

**Comment by claell** [comment] 2020-04-04 20:01
How about the others? Most seemed to be using Linux setups.

**Comment by toxpal** [comment] 2020-04-05 07:06
Still have the same problem on all (3) KDE machines.

**Comment by ramonreschke** [comment] 2020-04-05 07:14
I don't know actually.
The behaviour of my application seems a little bit different. My app shows simply "signed out from mydomain.tld as user" after few days of use (no restart of computer).
I cannot reproduce this issue currently.

OS: macOS
Client Version: 2.6.4 (updated from 2.6.2)
Server Version: 18.0.0.10

**Comment by rochelmeyer** [comment] 2020-04-05 08:41
KDE key storage seems to differ frome GNOME. Might be Nextcloud only handles the GNOME way correctly. This would explain why installing GNOME packages seems to solve the problem. Correct me, if I'm wrong.

**Comment by epsilontheta** [comment] 2020-04-05 09:04
@claell yes that is the same bug except that I did not have this delay where it shows "no connection". Also: after installing `libgnome-keyring` the problem seems to be gone for my setup.

**Comment by toxpal** [comment] 2020-04-05 09:28
The same here (gnome-keyring "fixes" the problem) - https://github.com/nextcloud/desktop/issues/1292#issuecomment-609370244 - but I really don't want to install this stuff on my KDE system just for NC to work.

**Comment by claell** [comment] 2020-04-05 13:28
Hm, I am not sure how to track this, as it might have a different cause than #1292. Currently it seems unclear, whether #1292 was actually fixed but there are issues with other environments (then it might be closed and the issue on other environments can be tracked here) or whether #1292 was not fixed properly (then this would be a duplicate and all should be tracked in #1292). I will leave both issues open for now.

**Comment by marvinjuette** [comment] 2020-04-19 20:47
Can confirm the problem for both of my systems.
One is a Arch Linux setup using the newest sync-client.
The other one is a Windows10 Computer also using the newest version of the client.

**Comment by mickmattes** [comment] 2020-04-21 12:16
Same issue with Gentoo Linux and i3 WindowManager. Extremely annoying.

**Comment by maehne** [comment] 2020-04-23 15:14
I observe this issue with the latest version of the Nextcloud client on Windows 10, Debian Buster with KDE Plasma, and macOS 10.13. It is a very annoying behaviour. I never experienced this behaviour with the OwnCloud client, where I could explicitly specify the app-specific credentials in the client.

**Comment by mickmattes** [comment] 2020-04-23 15:33
Please, give us an option to store credentials encrypted inside the application.

**Comment by veddox** [comment] 2020-05-02 10:40
> KDE key storage seems to differ frome GNOME. Might be Nextcloud only handles the GNOME way correctly. This would explain why installing GNOME packages seems to solve the problem. Correct me, if I'm wrong.

Confirm this. I've just switched from elementary OS (with the Pantheon desktop) to Ubuntu 20.04 (with GNOME), and the issue is gone.

**Comment by mickmattes** [comment] 2020-05-04 19:58
> Same issue with Gentoo Linux and i3 WindowManager. Extremely annoying.

Same setup here. You might want to look into rclone.

**Comment by Okanda** [comment] 2020-05-20 11:53
Same issue on Manjaro Stable (Fluxbox Desktop). 
Installing **gnome-keyring** solved the problem. . . but this is not a suitable fix for me. 
Tried with **kwallet-manager** but didn't work.

**Comment by BMTTeam** [comment] 2020-06-08 08:56
Win10 with desktop client v2.6.4stable-Win64 (build 20200303); NC v18.0.4 and the problem persist

**Comment by rubyco-me** [comment] 2021-01-06 22:39
Same issue with version 3.1.1. Running arch with swaywm. Installed libgnome-keyring after reading up on the issue tracker. It didn't help. Got libsecret and qtkeychain installed. Really annoying issue, as this really defeats the whole point of the desktop client.

**Comment by wasv** [comment] 2021-01-06 23:40
I was actually debugging a separate issue, and managed to fix this (at least in my case, there seems to be many different causes).

I was running my server behind an nginx ingress in Kubernetes and kept getting errors about an insecure redirect from https to http when authorizing new apps. I fixed that by adding
```
  'overwriteprotocol' => 'https',
```

to my config.php, and after adding that, my clients were able to consistently sync again. No keychain or libsecret changes.

**Comment by MeisterLLD** [comment] 2021-03-27 17:00
I'm still having this issue with Arch Linux. Even with gnome-kering and libgnome-keyring.

**Comment by FlexW** [comment] 2021-03-27 17:25
@MeisterLLD are you sure your keyring is configured correctly and gets unlocked properly? [libgnome-keyring is deprecated you should use libsecret instead](https://wiki.archlinux.org/index.php/GNOME/Keyring). I use ArchLinux with gnome-keyring too and don't have this problem.

**Closed** 2021-03-27 17:32 UTC
Labels: bug, feature: :key: authentication

**Comment by MeisterLLD** [comment] 2021-03-28 11:57
You are right, my bad, after another verification I found out that my keyring was not properly configured.

**Comment by georgmittendorfer** [comment] 2021-09-30 16:20
Just for reference in case someone stumbles over this issue: on my Debian system (11 with i3wm) I had to install the package `libsecret-tools` to make the client authentication work. Before that I had to authenticate on every start.

**Comment by mrschaal** [comment] 2022-02-14 10:26
Still experiencing this issue on Windows 10 and Windows 11 machines with the latest client version

**Comment by mophilly** [comment] 2022-02-14 16:53
This is happening with client 3.4.2 (macos) on MacOS Monterey (12.2.1).

**Comment by heschy2** [comment] 2023-09-20 20:45
I just experienced the same issue on Arch Linux, although, a reboot solved it (for now, but I hope it won't come back).
However, I am new to Arch Linux and a lot things don't work properly yet, but I thought it might be helpfull to just mention that I am experiencing it too.

**Comment by robertogerola** [comment] 2024-10-06 09:13
I solved this too on Tuxedo OS with KDE. KDE Wallet subsytem was not enabled. After I have enabled it, everything worked correctly.
