### ISSUE TITLE
Nextcloud Windows 10 Agent (3.0.3) - Sync Issues

### ISSUE THREAD

**Issue by Githopp192** [nextcloud/desktop#2679] opened 2020-12-01 14:42 UTC
**Steps to reproduce**
Transferring new pdf to Nextcloud iPhone Agent (3.0.15).

**Expected behaviour**
Syncing to the Cloud, Re-Syncing to the Windows Agent.
Syncing should work

**Actual behaviour**
Date from the iPhone (iPhone SE 2020/Gen2, IOS 14.2) will be transferred properly to the Cloud.
But the Cloud does not resync these Files to the Desktop NC Agent (Version: 3.0.3).

Also Restart of the Windows Dekstop Client (NC) does not help.

**Server configuration detail**
Operating system: Linux 4.18.0-193.19.1.el8_2.x86_64 

Webserver: Apache (fpm-fcgi)

Database: mysql 10.3.17

PHP version:

7.4.11
**Modules loaded**: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, cgi-fcgi, bcmath, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, gmp, iconv, intl, json, ldap, exif, mysqlnd, PDO, Phar, posix, shmop, SimpleXML, sockets, sodium, sqlite3, sysvmsg, sysvsem, sysvshm, tokenizer, xml, xmlwriter, xsl, mysqli, pdo_mysql, pdo_sqlite, xmlreader, apcu, igbinary, imagick, msgpack, smbclient, zip, memcached, redis, libsmbclient, Zend OPcache

**Nextcloud version**: 19.0.4 - 19.0.4.2

Updated from an older Nextcloud/ownCloud or fresh install:

Update from 19.0.3

Where did you install Nextcloud from: Nextcloud source

Signing status
List of activated apps
Configuration (config/config.php)
Are you using external storage, if yes which one: no

Are you using encryption: no

Are you using an external user-backend, if yes which one: no

**Client configuration**
Sync Agent version: 3.0.2

Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.80 Safari/537.36 Edg/86.0.622.43

Operating system: W10

Logs
Web server error log
Nextcloud log
Browser log

**Comment by er-vin** [comment] 2020-12-01 14:48
But the file is still on the server right? In that sense no data got lost, or the desktop client killed said file somehow?

In any case it would be nice to have the debug logs of a sync while you reproduce the error. This can be achieve by starting the application with `--logdebug --logfile C:\nextcloud-desktop-log.txt` on the command line.

**Comment by Githopp192** [comment] 2020-12-01 14:51
yes Kevin, you're right. But for me .. data loss could happen, if client, i.e. gets incomplete data, like an application an can crash.
So - missed or uncomplete synced data from the Cloud the clients can produce data inconsistencies.

yes ..wait .. will check if the logs are there ..

**Comment by Githopp192** [comment] 2020-12-01 15:05
did restart Agent -->

C:\Program Files\Nextcloud>nextcloud --logdebug --logfile C:\Windows\debug\nextcloud-desktop-log.txt

No log so far .. 

When i check the NextCloud_sync.log, then i see, that newly created files are synced but not the  PDFs, which still are on the Cloud into this folder (DoIt/TMPDocs)

#=#=#=#=# Propagation starts 2020-12-01T14:25:27Z (last step: 2435 msec, total: 2435 msec)
14:25:27||DoIt/TMPDocs/Termsheet.pdf|INST_NEW|Down|1606832706|db602d25856c1393a7e3ab8f7f5fd385|338750|01519647ocnudqtqmhau|4||0|0|0||||
#=#=#=# Syncrun finished 2020-12-01T14:25:30Z (last step: 3286 msec, total: 5721 msec)
#=#=#=# Syncrun started 2020-12-01T14:26:06Z
#=#=#=#=# Propagation starts 2020-12-01T14:26:09Z (last step: 3712 msec, total: 3712 msec)
14:26:10||DoIt/TMPDocs/Termsheet.pdf|INST_REMOVE|Up|1606832706|db602d25856c1393a7e3ab8f7f5fd385|338750|01519647ocnudqtqmhau|4||204|0|0||||
#=#=#=# Syncrun finished 2020-12-01T14:26:10Z (last step: 301 msec, total: 4013 msec)
#=#=#=# Syncrun started 2020-12-01T14:26:54Z
#=#=#=#=# Propagation starts 2020-12-01T14:26:57Z (last step: 3133 msec, total: 3133 msec)
#=#=#=# Syncrun finished 2020-12-01T14:26:57Z (last step: 120 msec, total: 3253 msec)
#=#=#=# Syncrun started 2020-12-01T14:33:25Z
#=#=#=#=# Propagation starts 2020-12-01T14:33:26Z (last step: 1203 msec, total: 1203 msec

**Comment by Githopp192** [comment] 2020-12-01 15:14
ok Kevin .. i do not exclude .. that due to high Load onto the Cloud, the maybe a Delay .. checking the Database, i see there are some locks, but i do not know, if this could have an impact !?

+----------+------+----------------------------------------+------------+
| id       | lock | key                                    | ttl        |
+----------+------+----------------------------------------+------------+
| 19364557 |    1 | files/57b15275c6ed0d16943fc1e2d1f11056 | 1606838415 |
| 22256219 |    1 | files/88bf3b24ec8dd9af977e58b60d467be5 | 1606839086 |
| 22256220 |    1 | files/fd3b9256f0f25accfbb9d7a152be6274 | 1606839086 |
| 22256221 |    1 | files/b96e5004e9dda5f2184ca0c242d888a0 | 1606839086 |
| 22256235 |    1 | files/2155a74f26572b71701324152f45443d | 1606839086 |
| 22257017 |    1 | files/16b371ff37e668f2e9250a3f0674c002 | 1606839086 |
| 22257985 |    1 | files/9979341176691add2285b742edf93620 | 1606839086 |
| 22258618 |   -1 | files/395a960f68f632b243d0229f2a1fecd6 | 1606839086 |
+----------+------+----------------------------------------+------------+

**Comment by Githopp192** [comment] 2020-12-01 15:27
now tried this again with new Screeshot file on the iPhone & then upload to the Cloud.
This will work (file is on the cloud) & also will be synced immediately to the Windows Desktop agent.

=#=#=#=# Propagation starts 2020-12-01T15:25:14Z (last step: 2868 msec, total: 2868 msec)
15:25:15||DoIt/TMPDocs/IMG_5293.PNG|INST_NEW|Down|1606836300|85f3046d082a3ba11b7e68ccdc6da383|216320|01519915ocnudqtqmhau|4||0|0|0||||
#=#=#=# Syncrun finished 2020-12-01T15:25:18Z (last step: 3400 msec, total: 6268 msec)

**Comment by Githopp192** [comment] 2020-12-01 15:47
so .. tried again with some app from the iPhone to transfer PDFs to the Cloud.
Transfer Process on the iPhone is ok - new PDF also seen on the iPhone App (NC) - also on the Cloud ok - but not on the Windows NC Agent (Explorer). 

When clicking on "Details" on the iPhone NC App .. and then comments .. then ERROR 405 will appear . maybe this is another bug .. 
![ScreenShot1038](https://user-images.githubusercontent.com/32612067/100762803-b4020480-33f4-11eb-86df-42f044928f52.jpg)

(The error itself indicates it's an issue on "Teilen", but i clicked on "Comments" )

So some files (i.e. *.png-Files seems to work .. some files like *.pdf does not sync anymore). 

Any idea ?

**Comment by Githopp192** [comment] 2020-12-01 16:51
Kevin .. i think i've found the BUG --> it's the COLON into the FILE NAME.

So all the files, which could transferred from the iPhone Agent to Cloud, but not from the Cloud to the Windows Agent have got some kind of the following name into:

So this File will work on the three Levels -->
Level 1: iPhone NC Agent (Transfer from a iPhone App internally to the NC App on the iPhone)
Level 2: Transfer from the iPhone NC App to the Cloud
Level 3: Transfer from the Cloud to the Windows NC Agent

![IMG_5296](https://user-images.githubusercontent.com/32612067/100770048-1e1ea780-33fd-11eb-9a69-7e7bd7f2ee1a.jpg)

And this File will work on Level 1 & 2, bot on Level 3!!

![IMG_5297](https://user-images.githubusercontent.com/32612067/100770115-342c6800-33fd-11eb-9adb-942b5e89a0db.jpg)

On the Cloud Server it looks like that -->

![ScreenShot1042](https://user-images.githubusercontent.com/32612067/100770321-6d64d800-33fd-11eb-9343-0c2ed7273d76.jpg)

But also Files like 'TEST:THISFILE' will not work.

So, there might be really an issue with the COLONS ":" .. Nextcloud is not able to SYNC with COLONS in it !

**Comment by Githopp192** [comment] 2020-12-01 16:59
https://github.com/nextcloud/desktop/issues/1537

**Comment by Githopp192** [comment] 2020-12-01 17:24
When i downloaded those Files with COLON ":" directly from the NC-Web Gui - Nextcloud did a rename in that Nextcloud Web Gui did replace the ":" (Colon) with "_" (underscore).

The question is ..why not to trigger this behave to the Agent also ?

(in my case Level 1 should had do the job --> replace ":" with "_" on the iPhone App Level)

**Comment by er-vin** [comment] 2020-12-02 06:50
Yes, duplicate of #464 then.

**Closed by er-vin** 2020-12-02 06:50 UTC
Labels: bug, feature: :arrows_counterclockwise: sync engine, os: :door: Windows
