### ISSUE TITLE
3.1.0 Appimage segfaults on Ubuntu 20.04.1

### ISSUE THREAD

**Issue by matt-twam** [nextcloud/desktop#2729] opened 2020-12-16 11:13 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour
3.1.0 Desktop Client Appimage should start, version 3.0.3 works as expected.

### Actual behaviour
The Appimage segfaults, see the logfile below.

### Steps to reproduce
1. Download the 3.1.0 Appimage from https://github.com/nextcloud/desktop/releases/download/v3.1.0/Nextcloud-3.1.0-x86_64.AppImage
2. chmod +x Nextcloud-3.1.0-x86_64.AppImage
3. ./Nextcloud-3.1.0-x86_64.AppImage

### Client configuration
Client version:
3.1.0git (build 4216)
Git revision 7f4ffd0f72482b6cf42e74335f3a360c3058f023
Using Qt 5.12.9, built against Qt 5.12.9
Using Qt platform plugin 'xcb'
Using 'OpenSSL 1.1.1g  21 Apr 2020'

Operating system: Ubuntu 20.04.1 LTS, x86_64

Client package (From Nextcloud or distro) (Linux only): Nextcloud Appimage

Installation path of client: ~/appimages/

### Logs

1. Client logfile: 
[log.txt](https://github.com/nextcloud/desktop/files/5702186/log.txt)
[gdb.txt](https://github.com/nextcloud/desktop/files/5702254/gdb.txt)

**Comment by MinhHaDuong** [comment] 2020-12-16 12:53
Same here:
```
haduong@doudou:~$ nextcloud -v
Nextcloud version 3.1.0-20201214.180315.7f4ffd0f7-1.0~focal1
Using Qt 5.12.8, built against Qt 5.12.8
Using Qt platform plugin 'xcb'
Using 'OpenSSL 1.1.1f  31 Mar 2020'
Running on Ubuntu 20.04.1 LTS, x86_64

```

**Comment by chli1** [comment] 2020-12-16 16:26
I think this is a duplicate of #2710 
Meanwhile I'm using the AppImage from the backport pull request here: #2715

**Comment by er-vin** [comment] 2020-12-16 18:00
Duplicate of #2710 indeed

**Closed by er-vin** 2020-12-16 18:00 UTC
