### ISSUE TITLE
Client 3.2.x Virtual Files Sync status never changes

### ISSUE THREAD

**Issue by andyxheli** [nextcloud/desktop#3391] opened 2021-06-01 18:42 UTC
When creating a new file with in the folder and you have virtual  files enable the sync icon always always shows  syncing never changes Also, Sync status never changes back to offline when moving files from folder to another. Just stays at syncing. 

![image](https://user-images.githubusercontent.com/59488153/118016913-9928aa00-b31b-11eb-979d-b16b4cb2f453.png)

Also wanted to add even if I exit out the nextcloud client the status still shows syncing 

![image](https://user-images.githubusercontent.com/59488153/118018298-39330300-b31d-11eb-99af-3a226ca40398.png)

**Comment by johkoenig** [comment] 2021-06-03 20:58
similar to #3148

**Comment by ronikeller** [comment] 2021-06-04 18:24
I have a very similar issue (most probably the same cause).
Some files stay forever in the "Sync" state.

To reproduce it, I do the following using the file explorer of Windows:
1. Open the context menu (right click) in a folder that has "virtual files" enabled
2. Choose "New" and "Text document" (since I use a German Windows, I am not sure about the exact wording)
3. The new file is generated (size of 0 bytes) and immediately synced with the Nextcloud server
4. Open the file (e.g. with notepad), enter some text and save it
5. The edited file has now a file size larger than 0 bytes (since it contains some text) but remains in the "Sync" state
6. However it seems to be copied to the server (I can verify it by opening it on the server) but its status remains in the "Sync" state nevertheless

This can also be reproduced by using a any other file that is created with a size of 0 bytes (e.g. a BMP file).
However, it does not happen if the file is initially created with a size larger than 0 bytes (e.g. a XLS file).

Nextcloud server: 21.0.2
Nextcloud desktop client: 3.2.2 (Windows)

**Comment by andyxheli** [comment] 2021-06-09 17:45
@allexzander Any suggestions on this ?

**Comment by allexzander** [comment] 2021-06-10 06:20
This is a known issue, but, thank you for adding more details. My colleague will soon be working on it, but, we don't really have any ETA.

@FlexW FYI

**Comment by FlexW** [comment] 2021-06-14 13:51
Should be fine with https://github.com/nextcloud/desktop/pull/3432 merged

**Closed by FlexW** 2021-06-14 13:51 UTC
Labels: bug
