### ISSUE TITLE
[Bug]: Updater should NOT restart Windows without user confirmation

### ISSUE THREAD

**Issue by DanielLaberge** [nextcloud/desktop#4747] opened 2022-07-17 02:07 UTC
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

While installing a Nextcloud app update, I was very annoyed to find out it initiated a system restart without any input from my part. 

That is NOT acceptable.

### Steps to reproduce

1. Install an update.

### Expected behavior

No restart unless the user confirms.

### Which files are affected by this bug

N/A

### Operating system

Windows

### Which version of the operating system you are running.

Windows 11

### Package

Other

### Nextcloud Server version

N/A

### Nextcloud Desktop Client version

3.5.2

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 3.4.2 to 3.4.4)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [X] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Nextcloud Server logs

```shell
N/A
```

### Additional info

Event Log proof: 
The process msiexec.exe has initiated the restart of computer REDACTED on behalf of user NT AUTHORITY\SYSTEM for the following reason: No title for this reason could be found
 Reason Code: 0x80030002
 Shut-down Type: restart
 Comment: The Windows Installer initiated a system restart to complete or continue the configuration of 'Nextcloud'.

**Comment by bigbrozer** [comment] 2022-07-18 07:57
Experienced the same with 2 machines (Win 10) from 3.5.1 update.

**Comment by claucambra** [comment] 2022-07-18 09:13
This has been resolved in 3.5.2 (#4566), so future updates after 3.5.2 should no longer exhibit this behaviour. Thanks for reporting!

**Closed by claucambra** 2022-07-18 09:13 UTC
Labels: 0. Needs triage

**Comment by laovong** [comment] 2022-08-05 01:52
> This has been resolved in 3.5.2 (#4566), so future updates after 3.5.2 should no longer exhibit this behaviour. Thanks for reporting!

Version 3.5.4 and Nextcloud client update still fore my computer restart without user confirmation.

**Comment by claucambra** [comment] 2022-08-05 02:19
We released an interim update (3.5.4) specifically to include the patch to stop force-updating. This means that future updates should no longer force reboot. Apologies for the annoyance -- forced reboots should not happen any longer

**Comment by allexzander** [comment] 2022-08-08 15:09
> We released an interim update (3.5.4) specifically to include the patch to stop force-updating. This means that future updates should no longer force reboot. Apologies for the annoyance -- forced reboots should not happen any longer

More specifically, this will start to work normally when updating from 3.5.4 and up. If you want to avoid rebooting when updating to 3.5.4, you need to run the MSI manually. The calling code is a part of the desktop client, so, it is something we have to deal with only this time.

**Comment by AnrDaemon** [comment] 2022-08-12 09:05
Finally. Will test.

**Comment by laovong** [comment] 2022-10-20 01:53
20 Oct
Client version: 3.6.1
OS: Windows 10 Pro
Require restart when update come back.
Nextcloud client has been uninstalled.

**Comment by allexzander** [comment] 2022-10-20 06:38
> 20 Oct Client version: 3.6.1 OS: Windows 10 Pro Require restart when update come back. Nextcloud client has been uninstalled.

Could not reproduce. Updated from 3.6.0 to 3.6.1 without force restart.

**Comment by AnrDaemon** [comment] 2022-10-21 13:34
Same, last two updates went without a restart.
