### ISSUE TITLE
Feature request: Automatic update

### ISSUE THREAD

**Issue by OliverAbraham** [nextcloud/desktop#2507] opened 2020-10-04 06:55 UTC
AS IS: Everytime I want to update my nextcloud windows client, the updater forces me to click 15 times until the update is done. There are silly questions like “do you want to remove the old version”.

TO BE: When there is a new update, i want to click once. I don’t want to download something. The NC client should download the required files by itself, not going through a complete uninstall/install procedure. After successful update, he might say “the update was installed”. But then close the notification automatically after one minute. Silly questions like “files have to be deleted” should be avoided . Customers asked me if they loose their files when they do the update.

99 percent of the users simply want to get the update done, nothing more. They are not interested in the ongoings under the hood. They are annoyed by all the silly questions. The best would be to have the option "dont ask me again", not to be asked about updates at all. It should simply work.

Steps to repeat:
Wait for the next NC client update.

Expected technical behaviour:
When there's a new update, windows client should download and install the required files by itself. Not using the browser. It should not ask the user until all is downloaded and ready to install. Then, the user should be prompted once, giving the option to have future updates without any prompts. After successful/unsuccesful update, a taskbar notification should give a note about the update, not requiring any mouse clicks.

**Comment by ifrh** [comment] 2020-10-04 09:25
But there should be an option to NOT-update automatically and if done an update, than there should be a log file, which files has been modified

**Comment by dreamflasher** [comment] 2020-10-05 12:12
Duplicate of: https://github.com/nextcloud/desktop/issues/1798
Auto updates haven't been working for years, despite many reports. Seems nextcloud devs don't prioritize according to user demand.

**Comment by jospoortvliet** [comment] 2021-01-18 06:00
@OliverAbraham can you check if this is fixed with the new MSI installer? If so, pls close the issue :+1:

**Comment by er-vin** [comment] 2021-01-18 08:22
Indeed, duplicate of #1798 so let's close this one.

**Closed by er-vin** 2021-01-18 08:22 UTC
Labels: bug, feature: :inbox_tray: install and update
