### ISSUE TITLE
Desktop Client show incorrect time under activity 

### ISSUE THREAD

**Issue by AndyXheli** [nextcloud/desktop#3874] opened 2021-10-07 01:42 UTC
Via web the activity is showing the correct time but under the desktop app is showing different both the server and desktops are on the same time zone  

Desktop Client Picture
![image](https://user-images.githubusercontent.com/59488153/136307032-7557178e-9264-4d6d-a7a8-6906c3eaff48.png)

Via Web Picture
![image](https://user-images.githubusercontent.com/59488153/136306979-7934cb27-6dad-4c58-bb53-044bc812c103.png)

**Comment by DAVe3283** [comment] 2022-01-01 00:27
This is still present in the Windows client version 3.4.1.

**Comment by joshtrichards** [comment] 2024-08-16 15:27
Sounds like #971

**Comment by AndyXheli** [comment] 2024-08-16 17:20
Looks like it

**Comment by joshtrichards** [comment] 2024-09-01 15:49
Duplicate of #971

**Closed by joshtrichards** 2024-09-01 15:49 UTC
Labels: bug, feature: :zap: activity and :bell: notification, approved
