### ISSUE TITLE
Feature Request: Smart Sync

### ISSUE THREAD

**Issue by kurteknikk** [nextcloud/desktop#2625] opened 2020-11-11 16:06 UTC
It would be very nice if we have a feature where we can see all the files on our desktop without the files taking up hard disk space. This is a pain to use/manage for people who have huge cloud environments & are always on the go.

P.S. I made this issue as a follow up of: Smart Sync #4717 (from the nextcloud/server project, which was open since 2017).
https://github.com/nextcloud/server/issues/4717

**Comment by michaelstingl** [comment] 2020-11-11 21:08
Sounds like https://github.com/nextcloud/desktop/issues/184

**Comment by er-vin** [comment] 2020-11-12 08:49
Duplicate of #184 indeed.

**Closed by er-vin** 2020-11-12 08:49 UTC
