### ISSUE TITLE
Nextcloud 3.2.0  enabling virtual file status not changing

### ISSUE THREAD

**Issue by axheli** [nextcloud/desktop#3114] opened 2021-04-13 17:36 UTC
Hello i enabled make always available locally for two folder and the files did download but the status still should the icon that its syncing and dose not show the screen check box wired how it only shows on one file. Just wanted to bring this up 

![image](https://user-images.githubusercontent.com/59488153/114596063-c1f24c80-9c54-11eb-95f4-cc2880e8a11a.png)

![image](https://user-images.githubusercontent.com/59488153/114596490-565caf00-9c55-11eb-9f7a-c441dcc58170.png)

**Comment by FlexW** [comment] 2021-04-13 17:53
I think that is a duplicate of https://github.com/nextcloud/desktop/issues/3082

**Closed by FlexW** 2021-04-13 17:53 UTC

**Comment by axheli** [comment] 2021-04-13 18:06
@FlexW looks like it is.
