### ISSUE TITLE
Add "Share label" option to Share dialog 

### ISSUE THREAD

**Issue by brainchild0** [nextcloud/desktop#3483] opened 2021-06-24 12:12 UTC
The web interface but not the Nemo shell extension  currently allows the user to give a short title to each share. Requested is adding this option to the shell integration.

Closely related to #2672.

**Comment by joshtrichards** [comment] 2023-11-25 01:58
Duplicate of #3103

Let's consolidate there.

**Closed by joshtrichards** 2023-11-25 01:58 UTC
Labels: enhancement, approved
