### ISSUE TITLE
Desktop release unexpectedly signed with new PGP key

### ISSUE THREAD

**Issue by christoph-schneegans** [nextcloud/desktop#3545] opened 2021-07-14 01:40 UTC
It seems that the assets of the current desktop release 3.2.4 have been signed with a different PGP key than previous releases. A similar problem was reported some time ago in https://github.com/nextcloud/server/issues/22783.

### Expected behaviour

Assets of the previous release 3.2.3 could easily be verified using the public key published at https://nextcloud.com/nextcloud.asc:

```
gpg.exe --verify Nextcloud-3.2.3-x86.msi.asc
gpg: assuming signed data in 'Nextcloud-3.2.3-x86.msi'
gpg: Signature made 2021-06-25 11:53:49 W. Europe Daylight Time
gpg:                using RSA key 28806A878AE423A28372792ED75899B9A724937A
gpg: Good signature from "Nextcloud Security <security@nextcloud.com>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 2880 6A87 8AE4 23A2 8372  792E D758 99B9 A724 937A
```

### Actual behaviour
The current release can no longer be verified in this way:

```
gpg.exe --verify Nextcloud-3.2.4-x86.msi.asc
gpg: assuming signed data in 'Nextcloud-3.2.4-x86.msi'
gpg: Signature made 2021-07-08 12:54:35 W. Europe Daylight Time
gpg:                using RSA key A438DC095967A1F11601CC42B69CB7F1069B3399
gpg: Can't check signature: No public key
```

### Steps to reproduce
1. Import the public key from https://nextcloud.com/nextcloud.asc
2. Download https://github.com/nextcloud/desktop/releases/download/v3.2.4/Nextcloud-3.2.4-x86.msi
3. Download https://github.com/nextcloud/desktop/releases/download/v3.2.4/Nextcloud-3.2.4-x86.msi.asc
4. Use `gpg --verify` to verify the asset.

**Comment by FlexW** [comment] 2021-07-14 07:06
You can find the correct asc files on the release page https://github.com/nextcloud/desktop/releases/tag/v3.2.4 here for now. Please also see the discussion here https://github.com/nextcloud/desktop/issues/3533 why you don't need to verify the macOS and Windows installer.

**Comment by dhruv** [comment] 2021-07-14 16:55
I am experiencing the same problem with the `.Appimage` client 3.2.4 release. The asc files from https://github.com/nextcloud/desktop/releases/tag/v3.2.4 and https://github.com/nextcloud/desktop/releases/download/v3.2.4 seems identical. Can you please help me verify the release?

**Comment by FlexW** [comment] 2021-07-15 08:53
@dhruv Does the key https://github.com/nextcloud/desktop/releases/tag/v3.2.4 not work?

**Comment by dhruv** [comment] 2021-07-15 21:00
@FlexW Didn't work for me. I believe it is the same issue mentioned [here](https://github.com/nextcloud/server/issues/22783#issuecomment-690418088), i.e. the signing sub key is being picked up.

```shell
$ curl -sSL https://github.com/nextcloud/desktop/releases/download/v3.2.4/Nextcloud-3.2.4-x86_64.AppImage -o Nextcloud-3.2.4-x86_64.AppImage
$ curl -sSL https://github.com/nextcloud/desktop/releases/download/v3.2.4/Nextcloud-3.2.4-x86_64.AppImage.asc -o Nextcloud-3.2.4-x86_64.AppImage.asc
$ gpg --list-keys 28806A878AE423A28372792ED75899B9A724937A
pub   rsa4096 2016-06-14 [SC]
      28806A878AE423A28372792ED75899B9A724937A
uid           [ unknown] Nextcloud Security <security@nextcloud.com>
sub   rsa4096 2016-06-14 [E]

$ gpg --verify Nextcloud-3.2.4-x86_64.AppImage.asc Nextcloud-3.2.4-x86_64.AppImage
gpg: Signature made Thu 08 Jul 2021 03:54:36 AM PDT
gpg:                using RSA key A438DC095967A1F11601CC42B69CB7F1069B3399
gpg: Can't check signature: No public key
```

**Comment by activefog** [comment] 2021-07-21 05:44
Same issue here. I have some comfort given that this was confirmed by a core contributor to be a sub key in https://github.com/nextcloud/server/issues/22783, but it still gives me some pause. 

`gpg --import nextcloud.asc
gpg: key D75899B9A724937A: "Nextcloud Security <security@nextcloud.com>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1

gpg --verify Nextcloud-3.2.4-x86_64.AppImage.asc Nextcloud-3.2.4-x86_64.AppImage
gpg: Signature made Thu 08 Jul 2021 05:54:36 AM CDT
gpg:                using RSA key A438DC095967A1F11601CC42B69CB7F1069B3399
gpg: Can't check signature: No public key`

**Comment by FlexW** [comment] 2021-07-21 07:14
Just wanted to note that the issue is probably the same as the one back then with the server and we are working on a solution.

**Comment by mgallien** [comment] 2021-08-25 10:13
as far as I know the 3.3.1 release is now using the proper key.
Closing the issue.
please open a new issue if that comes back and thanks for the report

**Closed by mgallien** 2021-08-25 10:13 UTC
Labels: bug, approved
