### ISSUE TITLE
During software update files and folder deleted

### ISSUE THREAD

**Issue by salagula** [nextcloud/desktop#2857] opened 2021-01-22 16:01 UTC
Hi, we are syncing on my Windows 10 PC's the "desktop" and "my documents" content and did this week some Desktop app update to 3.x on > 500 PC's. On 10 PC's the locally synced folders were totally gone (ca 10GB each) - fortunately server versions were still there but sync was not started anymore automatically. Only opt-out and opt-in of the folder sync locations solved that. Strange issue - but also in the past randomly big chunks were gone from local PC's. Has someone seen similar issues?

**Comment by er-vin** [comment] 2021-01-25 09:48
I think this is a duplicate of #260

**Closed by er-vin** 2021-01-25 09:48 UTC
