### ISSUE TITLE
Nextcloud Desktop Client upside down (Windows)

### ISSUE THREAD

**Issue by julyusito** [nextcloud/desktop#2805] opened 2021-01-07 19:14 UTC
Helo,

When i left click the nextcloud icon in the taskbar, the interface opens upside down.

Nextcloud desktop client 3.1.1
Windows 10 Home 1909 Compilation 18363.1256
Virtualbox 6.1.16 r140961 (Qt5.6.3) on MAC High Sierra

![Captura de pantalla 2021-01-07 a la(s) 12 18 27 p  m](https://user-images.githubusercontent.com/69789966/103933886-0d470d00-50f2-11eb-889f-e6b888324845.png)

The top bar shows OK:
![Captura de pantalla 2021-01-07 a la(s) 12 20 20 p  m](https://user-images.githubusercontent.com/69789966/103933926-22bc3700-50f2-11eb-9668-2f4fc337857d.png)

The blue bar seems to be in the right place, but looks inverted.
When you press on white top bar, the menu shows.
I can see the fonts are miss characters too.

Thanks

**Comment by er-vin** [comment] 2021-01-11 08:04
Yes, duplicate of an old 3.0 bug. This is a problem in the 3D accelerated drivers of VirtualBox depending what they're combined with on the host. We can't do anything about it unfortunately, only workaround is to disable the 3D acceleration in the VM settings.

**Closed by er-vin** 2021-01-11 08:04 UTC

**Comment by julyusito** [comment] 2022-04-06 21:46
Thanks
