### ISSUE TITLE
Win7 Immediate Crash, Release version 3.1.0.16122

### ISSUE THREAD

**Issue by affinityv** [nextcloud/desktop#2751] opened 2020-12-20 16:51 UTC
Had 3.0.3 client installed, worked without issues.

Installed 3.1.0.16122 -- client crashes every time it is started.  Tried to do a reboot to see if that would make any difference; it didn't.

Uninstalled 3.1.0.16122 and re-installed 3.0.3 version -- back to working situation. no crashes.

These are the crash details from eventvwr:

Log Name:      Application
Source:        Application Error
Date:          21/12/2020 2:28:37 AM
Event ID:      1000
Task Category: (100)
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      office-PC-3
Description:
Faulting application name: nextcloud.exe, version: 3.1.0.16122, time stamp: 0x5fd25484
Faulting module name: nextcloud.exe, version: 3.1.0.16122, time stamp: 0x5fd25484
Exception code: 0xc0000005
Fault offset: 0x00000000000a9be7
Faulting process id: 0x26fc
Faulting application start time: 0x01d6d6e4c6c91db0
Faulting application path: C:\Program Files (x86)\Nextcloud\nextcloud.exe
Faulting module path: C:\Program Files (x86)\Nextcloud\nextcloud.exe
Report Id: 070c8a6c-42d8-11eb-a5ed-00248c485aba
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Level>2</Level>
    <Task>100</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2020-12-20T15:28:37.000000000Z" />
    <EventRecordID>229569</EventRecordID>
    <Channel>Application</Channel>
    <Computer>office-PC-3</Computer>
    <Security />
  </System>
  <EventData>
    <Data>nextcloud.exe</Data>
    <Data>3.1.0.16122</Data>
    <Data>5fd25484</Data>
    <Data>nextcloud.exe</Data>
    <Data>3.1.0.16122</Data>
    <Data>5fd25484</Data>
    <Data>c0000005</Data>
    <Data>00000000000a9be7</Data>
    <Data>26fc</Data>
    <Data>01d6d6e4c6c91db0</Data>
    <Data>C:\Program Files (x86)\Nextcloud\nextcloud.exe</Data>
    <Data>C:\Program Files (x86)\Nextcloud\nextcloud.exe</Data>
    <Data>070c8a6c-42d8-11eb-a5ed-00248c485aba</Data>
  </EventData>
</Event>

### Expected behaviour
New client should work as good as old client, if not better ;-)
There should be no crash.

### Actual behaviour
After install, could not run the NC client without it crashing shortly after.

### Client configuration
Client version:
3.1.0.16122

Operating system:
Windows 7 64 bit pro

OS language:
English

Qt version used by client package (Linux only, see also Settings dialog):
Standard Windows NC installer for 3.1.0.16122

Further details in the eventvwr output above.

### Logs

Further details in the eventvwr output above.

1. Client logfile: 
Output of `nextcloud --logdebug --logwindow` or `nextcloud --logdebug --logfile log.txt`

(On Windows using `cmd.exe`, you might need to first `cd` into the Nextcloud directory)
(See also https://docs.nextcloud.com/desktop/2.3/troubleshooting.html#log-files)

NOT DONE, had to get working client re-installed.

2. Web server error log:
None expected.

3. Server logfile: nextcloud log (data/nextcloud.log):
Not captured.

**Comment by er-vin** [comment] 2020-12-21 06:54
Could we have a backtrace of the crash please? I suspect this is a duplicate of #2710

**Comment by xames81** [comment] 2020-12-21 17:40
Same here with windows 10. Back to 3.0.3 x86, because x64 more problems.

**Comment by affinityv** [comment] 2020-12-29 16:27
3.1.1.16134 seems to be fine.  I never had time to try 3.1.0 again and provide logs.

**Comment by er-vin** [comment] 2020-12-29 16:38
OK, assuming duplicate of #2710 then

**Closed by er-vin** 2020-12-29 16:38 UTC
Labels: bug
