### ISSUE TITLE
New button to keep folder empty when emptied

### ISSUE THREAD

**Issue by binarykitchen** [nextcloud/desktop#1198] opened 2019-04-10 23:53 UTC
### Expected behaviour
1. I empty the Instant Uploads folder locally
2. Expect this to be synced to the server and it's empty there too

### Actual behaviour
1. Client won't let me. Only ask me to re-download them or to keep the local ones. See screenshot:
<img width="471" alt="Screen Shot 2019-04-11 at 11 50 47" src="https://user-images.githubusercontent.com/177641/55921301-508bf780-5c50-11e9-8bca-3956fc7422a7.png">

### Steps to reproduce
See above

### Client configuration
Client version: 2.5.2git
Operating system: MacOS

I think a third button would be good to actually confirm emptying the whole directory.

**Comment by 0xd800** [comment] 2019-04-13 20:41
Download new files does exactly what you want.

**Comment by binarykitchen** [comment] 2019-04-14 23:28
Hmm, I think this text "Download new files" isn't really clear. Usability. I couldn't guess what it does in this case. Downloading doesn't mean emptying directory.

Can we improve button text in this case for better usability?

**Comment by camilasan** [comment] 2019-04-23 16:54
On 2.5.3 rc1 you won't get this message anymore. This is preventing problems on the server of affecting the client files. Could you try 2.5.3 rc1? https://download.nextcloud.com/desktop/prereleases/Mac/Nextcloud-qt5.9.2-2.5.3.20190412rc1.pkg
Thanks

**Comment by gabrielklein** [comment] 2019-06-04 21:11
Thank you for the change. I was finding the message confusing too.

**Comment by darmbrust** [comment] 2019-06-21 21:48
This error message is the most confusing bit of mess I've ever encountered from a file sync app. The two options provided have no wording in common with the question asked.  First off, get rid of the part about "restored".  That is a completely different operation, which only serves to confuse in this context.

And the two options provided are non-sensical in this case, doing the opposite of what someone might expect them to do.

The THREE options that should be provided in this case are:

- Sync (push)  Deletes to Server - with a tooltip or extended explanation that says that this operation will leave the files removed locally, and also remove them from the server.
- Restore the local files from the server - with a tooltip or extended explanation that says that this operation will download the files from the server to the local folder again
- Stop syncing the folder - with a tooltip or extended explanation that says that this operation will leave the files removed locally, will leave the files on the server as they were, and this folder will no longer be synchronized locally.


Furthermore, there is another case with this dialog coming up where it is completely wrong an unintuitive.  If I have a local folder synchronized, which I no longer with to have synchronized, and I uncheck the box for sync - when I'm checking an unchecking boxes for sync, it will tell me that "unchecked folders will be removed from your local file system, and will not be synced to this computer anymore".... a perfectly reasonable thing.  However, at this time, it doesn't ask you want you want to do with the content in the local folders.  Then you hit OK, and this dialog come up.  And you have no clue what it is going to do with either option.  I mean, I just told it to stop syncing the folder, and now its asking me if it should delete the files from the server.  That shoudn't even be an option in this case.  And it says my local folder is empty, when it isn't.... And, the other option is telling me it will redownload from the server, for a folder that isn't even supposed to be sync'ed anymore.

This is quite a disaster of usability for a file syncing app, with no clear explanations, confusing and backwards options, and the consequence of clicking the wrong buttons could result in dataloss for people.

Has anyone put together a flowchart of the various scenarios where the client will propmpt the user, with the text and options used in each case?  I think it would be very helpful to put all of these bugs together in an overall review of the use cases, and the wording presented to the user in each one (and the options presented)

**Comment by darmbrust** [comment] 2021-05-12 02:00
go away bot.  I don't believe anything has been done with this confusing mess of a dialog.

**Comment by FlexW** [comment] 2021-05-31 14:47
I think this issue is resolved. You only get the dialog like @binarykitchen describes when you set `promptDeleteAllFiles=true` in `nextcloud.cfg` in the section `[General]`, and then delete all files on the server. In this case I think the phrasing of the dialog is correct and not confusing. If you delete all the files locally, you get different buttons with "Keep files" and "Remove all files".

There was also an pr that fixed a part of that dialog, but I can not find it anymore. Please test with the newest version (3.2.2) if the issue is resolved for you too. I will close the issue for now. If you still have problems. Please ask to open the issue again or open a new one.

**Closed by FlexW** 2021-05-31 14:47 UTC
Labels: 0. Needs triage, needs info

**Comment by darmbrust** [comment] 2021-06-01 01:53
Have you tested the case I described above, of the behavior when you disable sync for a local folder?
And have you looked at the other two issues linked to this one, which are still open?  There were far more than one use case that tied to this disaster of a dialog.  The fact that you think the dialog, as pictured at the beginning of this bug makes any sense as written for any use case is part of the problem....  The dialog clearly asks a question that should have a yes/no style answer, and provides no button that signifies yes or no.

**Comment by FlexW** [comment] 2021-06-01 16:03
@darmbrust What you describe in your comment is not really the same bug or has an much wider scope than that was the author of the issue described. Could you please open a new issue for this, so we can keep the bug reports focused?

**Comment by darmbrust** [comment] 2021-06-01 16:14
The whole point of my comment was that this dialog was written for a specific purpose.  And then mis-used for about 5 more purposes where it makes no sense.

One cannot "tweak" this dialog and make it work properly for any use case, unless someone actually looks at all the use cases where the dialog is used.

It seems rather odd to say that we think a change went in, we think it was fixed... if there are other cases, open new bugs.  And shows that whatever change was made likely didn't consider all the use cases.

There are already at least 4 different bugs open about this.  It needs a top-to-bottom eval, of where the dialog is used in the code.  I'm not sure how opening another bug is going to help get that done.

**Comment by FlexW** [comment] 2021-06-01 16:49
I can not see that there is an open issue about the problem you describe. If you want to move this forward, you can check if the already opened issues are resolved. If they are resolved, please close them or ask someone to do so. You can then create a new issue with what is left to do. The problem with the current situation is that your comment made a good point, but it will get lost because the original issue was about something else.
