### ISSUE TITLE
Use "normal" filename for install/update

### ISSUE THREAD

**Issue by andreapx** [nextcloud/desktop#3784] opened 2021-09-12 18:03 UTC
When I started the last update it executed a file named 18d7ef0.msi. Maybe it always happened, but I've never noticed this.
At first I was worried. I decided to download the Windows 0 client directly from the Nextcloud website and it executed the same file.
Since in this period cryptoviruses are spreading worst then the corona, I think that a "normal" file name would be really better!!!
Andrea

**Comment by mgallien** [comment] 2021-09-13 07:56
The name you see in the popup comes from internal mechanism of the installer that is split into two parts:
- the first with the name you downloaded is using normal use privileges
- the second with the autogenerated name is using elevated privileges (the name is generated by the MSI generator framework)

we will have to research if there is a way not to have such a name

are you able to help us ?

**Comment by andreapx** [comment] 2021-09-13 08:13
Unfortunatly I can't code at all...sorry.
I can help doing tests.

**Comment by claell** [comment] 2021-09-13 11:34
This is likely a duplicate of #2947 and #3735.

**Comment by andreapx** [comment] 2021-09-13 12:08
Sorry, I searched before posting, but...evidently not enough!

**Comment by claell** [comment] 2021-09-13 12:10
No problem :) Now this one can help others find the existing issues easier.

**Comment by claell** [comment] 2021-09-13 12:10
Duplicate of #2947

**Closed** 2021-09-13 12:10 UTC
Labels: enhancement, approved
