### ISSUE TITLE
MacOS Client File Download Error Massage cause of UTF-8 Symbol 🔒

### ISSUE THREAD

**Issue by MatzeFix** [nextcloud/desktop#2263] opened 2020-08-12 10:44 UTC
### Expected behaviour
The MacOS Client should download new files also with UTF-8 Symbol

### Actual behaviour
MacOS Client shows an error because of the UTF-8 Symbol 🔒.
Attached you can find the error Message (in German) and also Client-OS and Nextcloud-Client Versions
![Fehlermeldung_Nextcloud_Client](https://user-images.githubusercontent.com/50321392/90006621-86ece300-dc99-11ea-9274-2a5236d622a4.png)

### Steps to reproduce
1. Create a File in Nextcloud GUI with UTF-8 Symbol 🔒 in the Name of the File
2. Sync this File with a MacOS-Client
3. See Error Message

### Client configuration
Client version:

Operating system:
MacOS Catalina Version 10.15.5
(See Screenshot)
![Betriebssystemversion](https://user-images.githubusercontent.com/50321392/90006611-818f9880-dc99-11ea-8dce-4f0578afe992.png)

OS language:
German

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From Nextcloud or distro) (Linux only):
(see Screenshot for Version)
![Nextcloud-Clientversion](https://user-images.githubusercontent.com/50321392/90006603-7d637b00-dc99-11ea-85a8-18b86eb63867.png)

Installation path of client:

### Server configuration

Nextcloud version:
18.0.2

Storage backend (external storage):
No

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile: Output of `nextcloud --logwindow` or `nextcloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the Nextcloud directory)
(See also https://docs.nextcloud.com/desktop/2.3/troubleshooting.html#log-files)
No client Logs

2. Web server error log:
No Webserver Logs

3. Server logfile: nextcloud log (data/nextcloud.log):
No Server Logs

**Comment by er-vin** [comment] 2020-08-12 11:03
I wonder how related that is to #464 and friends...

**Comment by MatzeFix** [comment] 2020-08-12 15:00
> 
> 
> I wonder how related that is to #464 and friends...

Yeah - you are right -> It seems to be very similiar. 
Do you have some background information why some characters are not allowed (I wonder because my UTF-8 symbol has nothing to do with path-creation or something like that)?

Is this a problem - we have to live with or is it already in the pipeline?

Big thank 👍

**Comment by er-vin** [comment] 2020-08-12 15:39
Well in some way it is a problem you have to live with: OS forbid some characters in filenames there is no way around that. Where it gets tricky is that those characters are not the same for the each OS...

Now, admittedly we could do a better job at preventing such interoperability problems but a proper approach is yet to be decided upon.

Anyway, I'll close this one as duplicate of #464

**Closed by er-vin** 2020-08-12 15:39 UTC
Labels: bug, os: :apple: macOS
