### ISSUE TITLE
macOS Nextcloud Desktop Client generates kernel errors

### ISSUE THREAD

**Issue by egaudrain** [nextcloud/desktop#2763] opened 2020-12-22 10:44 UTC
### Expected/Actual behaviour

I am using Nextcloud Desktop Client v3.0.3 on macOS Mojave 10.14.6 and I see this activity in my Console log when the client is open:

```
error	11:16:16.198036 +0100	kernel	compat_ifmu_ulist: en0 copyin() error 14
error	11:16:16.198449 +0100	kernel	compat_ifmu_ulist: en6 copyin() error 14
error	11:16:16.198552 +0100	kernel	compat_ifmu_ulist: ap1 copyin() error 14
error	11:16:16.198566 +0100	kernel	compat_ifmu_ulist: en1 copyin() error 14
error	11:16:16.198572 +0100	kernel	compat_ifmu_ulist: p2p0 copyin() error 14
error	11:16:16.198577 +0100	kernel	compat_ifmu_ulist: awdl0 copyin() error 14
error	11:16:16.198585 +0100	kernel	compat_ifmu_ulist: en2 copyin() error 14
error	11:16:16.198593 +0100	kernel	compat_ifmu_ulist: en3 copyin() error 14
error	11:16:16.198599 +0100	kernel	compat_ifmu_ulist: en4 copyin() error 14
error	11:16:16.198605 +0100	kernel	compat_ifmu_ulist: en5 copyin() error 14
error	11:16:16.198914 +0100	kernel	compat_ifmu_ulist: en0 copyin() error 14
error	11:16:16.198925 +0100	kernel	compat_ifmu_ulist: en6 copyin() error 14
error	11:16:16.198931 +0100	kernel	compat_ifmu_ulist: ap1 copyin() error 14
error	11:16:16.198941 +0100	kernel	compat_ifmu_ulist: en1 copyin() error 14
error	11:16:16.198946 +0100	kernel	compat_ifmu_ulist: p2p0 copyin() error 14
error	11:16:16.198951 +0100	kernel	compat_ifmu_ulist: awdl0 copyin() error 14
error	11:16:16.198957 +0100	kernel	compat_ifmu_ulist: en2 copyin() error 14
error	11:16:16.198965 +0100	kernel	compat_ifmu_ulist: en3 copyin() error 14
error	11:16:16.198970 +0100	kernel	compat_ifmu_ulist: en4 copyin() error 14
error	11:16:16.198977 +0100	kernel	compat_ifmu_ulist: en5 copyin() error 14
```

These errors are not supposed to happen and occur every 10s.

### Steps to reproduce
1. Just start the Nexcloud Desktop Client and login.
2. Open the Console.

### Client configuration
Client version: v3.0.3 (macOS)

Operating system: macOS Mojave 10.14.6

OS language: en

Installation path of client: /Applications/nextcloud.app

### Logs

Here's the Nextcloud log between 11:28:17 and 11:31:29: https://gist.github.com/egaudrain/b54deddbf4b944fbf968cdde4d627b15

The series of kernel errors occurred at (only pasting the first line to get the timestamp, but it's always the same as above): https://gist.github.com/egaudrain/ddbd8aa31fab46914a6ae1ead92248af

You can compare the timestamps to see if it is related to anything Nextcloud is doing...?

**Comment by er-vin** [comment] 2020-12-22 11:02
Duplicate of #2237

**Closed by er-vin** 2020-12-22 11:02 UTC
