### ISSUE TITLE
Nextcloud client crashing upon start

### ISSUE THREAD

**Issue by Konrad982** [nextcloud/desktop#3168] opened 2021-04-19 09:56 UTC
### Expected behaviour
The nextcloud client should start

### Actual behaviour
The nextcloud client does not start. In command line, the following lines appear:
`Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
Segmentation fault (core dumped)`

EDIT: This happens also on xorg:
`Segmentation fault (core dumped)`

### Steps to reproduce
1. start nextcloud in command line by `nextcloud`

The error happened after upgrade to ubuntu 21.04 from ubuntu 20.10 and using wayland instead of xorg.

**Comment by FlexW** [comment] 2021-04-19 11:37
Duplicate of https://github.com/nextcloud/desktop/issues/3090

**Closed by FlexW** 2021-04-19 11:37 UTC
