### ISSUE TITLE
[Bug]: Mac Finder extension crashes when renaming a folder that has uploading items in it.

### ISSUE THREAD

**Issue by thysm00** [nextcloud/desktop#6488] opened 2024-02-24 21:59 UTC
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

the finder extension (small icons next to the files) crashes when you rename a folder that has files in it that are uploading/syncing.

### Steps to reproduce

create a folder, put a few rather big files in it, wait for the sync to start, then while it's syncing, just change the name of the folder. The sync works just fine, but It will crash the finder extension.

### Expected behavior

The finder extension should not crash.

### Which files are affected by this bug

Any file.

### Operating system

Mac OS

### Which version of the operating system you are running.

Sonoma latest

### Package

Appimage

### Nextcloud Server version

latest

### Nextcloud Desktop Client version

3.12.0 but happens also in the previous versions)

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [X] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by claucambra** [comment] 2024-11-10 14:07
Hi @thysm00 I am not able to reproduce this on 3.13.4, would you be able to test this client version and see if the issue still happens?

@jospoortvliet Would you be able to send me the crash report from the Console app? This might help get to the root of the issue, thanks!

**Comment by claucambra** [comment] 2024-11-26 05:21
Okay, since this is inconclusive I will close this issue as a duplicate of #5193 -- thanks for reporting!

**Closed by claucambra** 2024-11-26 05:21 UTC
Labels: 0. Needs triage, bug, os: :apple: macOS, feature: 🐚 shell integration
