### ISSUE TITLE
No Windows 10 Explorer integration in Oracle VM VirtualBox

### ISSUE THREAD

**Issue by gabiol199711** [nextcloud/desktop#1356] opened 2019-07-24 19:05 UTC
### Expected behaviour
Windows Explorer integration works: there are green checkmarks on the folders, files, there are additional items in the context menu.

### Actual behaviour
Windows Explorer integration doesn’t work: there are no green checkmarks on the folders, files, there are no additional items in the context menu.

### Steps to reproduce
1.Download  Nextcloud-2.5.2-setup.exe from https://nextcloud.com/install/#install-clients
2.Install Nextcloud with choosing “Integration for Windows Explorer"
3.After signing in, client syncs successfully, but Windows Explorer integration doesn’t work
![Снимок экрана (52)](https://user-images.githubusercontent.com/52456730/61820235-4c7d9180-ae5d-11e9-8299-12c95957d3e8.png)
![Снимок экрана (54)_LI](https://user-images.githubusercontent.com/52456730/61820237-4c7d9180-ae5d-11e9-9a15-c8534b3c6031.jpg)
![Снимок экрана (55)](https://user-images.githubusercontent.com/52456730/61820240-4c7d9180-ae5d-11e9-90b0-45c49f53b56b.png)
![Снимок экрана (55)_LI](https://user-images.githubusercontent.com/52456730/61820242-4c7d9180-ae5d-11e9-9253-c4e269ca7d67.jpg)
![Снимок экрана (56)](https://user-images.githubusercontent.com/52456730/61820243-4d162800-ae5d-11e9-8119-2e5158e87abf.png)
![Снимок экрана (57)](https://user-images.githubusercontent.com/52456730/61820244-4d162800-ae5d-11e9-9ed5-a4d6f68fb9a2.png)

### Client configuration
Client version: 2.5.2

Virtual machine: Oracle VM VirtualBox Extension Pack 6.0.8r130520 from https://www.virtualbox.org/wiki/Downloads
Operating system: Windows 10 
I tried these OS versions: Windows 10 1903 Home (Build 18362) from https://www.getmyos.com/windows-10-1903-may-2019-update-home-pro-education-free-download,
 Windows 10 1903 Pro (Build 18362) from
 https://www.getmyos.com/windows-10-1903-may-2019-update-home-pro-education-free-download,
 Windows 10 1809 Home (Build 17763) from
 https://www.getmyos.com/windows-10-1809-nov-home-pro-education-32-64-bit-free-download ,
 Windows 10 1809 Pro (Build 17763) from
 https://www.getmyos.com/windows-10-1809-nov-home-pro-education-32-64-bit-free-download,
 Windows 10 1703 Home (Build 15063) from
 https://www.getmyos.com/windows-10-1703-home-pro-education-32-64-bit-free-download, 
 Windows 10 1703 Pro (Build 15063) from
 https://www.getmyos.com/windows-10-1703-home-pro-education-32-64-bit-free-download ,
 Windows 10 1507 Home (Build 10240) from
 https://www.getmyos.com/windows-10-1507-home-pro-education-32-64-bit-free-download

I attach an image of a virtual machine (ova file archive) with two snapshots (“clean” and “with Nextcloud 2.5.2”).  http://sr38.org/tmp/win10_1809_Pro_Eng.ova

OS language:English US

Installation path of client:C:\Program Files (x86)\Nextcloud

**Comment by unix0r** [comment] 2019-07-30 16:52
Duplicate of https://github.com/nextcloud/desktop/issues/978

**Comment by mgallien** [comment] 2021-05-11 07:24
I believe this bug is fixed.
I will close it and you can always open a new one if you experience it again.

**Closed by mgallien** 2021-05-11 07:24 UTC
