### ISSUE TITLE
[ENHANCEMENT] Improved Error Handling

### ISSUE THREAD

**Issue by c0fe** [nextcloud/desktop#244] opened 2018-04-11 12:11 UTC
Currently i have Nextcloud desktop client running on Windows 10 Professional and I have the Nextcloud directory on an external hard drive. If say I had multiple files (let's say Adobe Illustrator files) by coping over the directory, at times I will see errors that appear in the icon while the rest of the files show that there were no errors. In other words, 10 files total, 1 file has red error icon and the other 9 have a green ok icon.

When I go back to the client to see the error I do not see any errors though the log seems to be somewhat limited. My suggestion would be split between files that have been ignored and files that have errored out.

**Comment by michaelstingl** [comment] 2018-04-11 19:04
@c0fe You mean in the "Activity" tab?

In version 2.4.1 (from [upstream project](https://github.com/owncloud/client)), entries from warnings or ignored files can be hidden:

![owncloud](https://user-images.githubusercontent.com/214010/38637488-8fbaa0f4-3dcb-11e8-8d7c-989b5673d891.png)

**Comment by c0fe** [comment] 2018-04-12 16:57
There is also an issue where certain files do not sync because of "Internal Server Error" but I check that only in the Windows 10 notification dialog that appears briefly but nothing is in the log:

https://i.imgur.com/KeYfdHf.png

https://i.imgur.com/tlJXNwA.png

**Comment by DominiqueFuchs** [comment] 2019-09-25 17:24
Duplicate of own issue #228 , please continue there if this is still an issue for you - thanks!

**Closed by DominiqueFuchs** 2019-09-25 17:24 UTC
Labels: enhancement, feature-request
