### ISSUE TITLE
[Bug]: popup window partly hidden under StartAllBack taskbar

### ISSUE THREAD

**Issue by zeroxx1986** [nextcloud/desktop#5898] opened 2023-07-18 12:39 UTC
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

When using windows 11 + StartAllBack (3rd party taskbar replacement) and moving the taskbar to the left side of the screen (to be vertical), when I press the NextCloud icon in the system tray, it's partially hidden behind the taskbar, and it's unmovable.

![image](https://github.com/nextcloud/desktop/assets/4190724/9c5c94f2-b793-4185-bc31-67370f52fe8d)

### Steps to reproduce

1. Use StartAllBack to enable taskbar to be placed to the left side of the screen vertically (windows 11)
2. Click on the tray icon of nextcloud app

### Expected behavior

The popup is not under the system tray; or at least it's movable after it pops up.

### Which files are affected by this bug

-

### Operating system

Windows

### Which version of the operating system you are running.

Windows 11

### Package

Appimage

### Nextcloud Server version

27

### Nextcloud Desktop Client version

3.9.0

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by toastbrotch** [comment] 2023-07-29 17:32
same here.

**Comment by erentar** [comment] 2023-11-02 14:08
The same issue occurs when using ExplorerPatcher to allow docking taskbar to the left edge.
Is there some way to allow the window to be moved (perhaps via a menu setting)?

**Comment by mongojarle** [comment] 2024-08-04 01:33
Workaround, works on win11. I use startallback to get vertical taskbar, but I suspect this works universally:
- Open Regedit, navigate to HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\StuckRects3
- Double-click settings, find byte 13. This will either be 00, 01, 02 or 03 (most likely 03).
- Double-click on byte 13, so it is selected as picture below. Write 00 for taskbar left, 01 for top, 02 for right or 03 for bottom.
- Click OK and close regedit.
- Open task manager, find Windows Explorer and End task.
- Click File - Run new task... Write explorer, click ok.
- 
![image](https://github.com/user-attachments/assets/d1b304bd-2155-47c3-a9b4-a5d59f3532f5)

**Comment by joshtrichards** [comment] 2024-08-16 22:19
Duplicate of #4481

**Closed by joshtrichards** 2024-08-16 22:19 UTC
Labels: 0. Needs triage, hotspot: visual

**Comment by DonPicciotto** [comment] 2025-02-12 05:55
> Workaround, works on win11. I use startallback to get vertical taskbar, but I suspect this works universally:
> 
>     * Open Regedit, navigate to HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\StuckRects3
> 
>     * Double-click settings, find byte 13. This will either be 00, 01, 02 or 03 (most likely 03).
> 
>     * Double-click on byte 13, so it is selected as picture below. Write 00 for taskbar left, 01 for top, 02 for right or 03 for bottom.
> 
>     * Click OK and close regedit.
> 
>     * Open task manager, find Windows Explorer and End task.
> 
>     * Click File - Run new task... Write explorer, click ok.
> 
> 
> ![image](https://github.com/user-attachments/assets/d1b304bd-2155-47c3-a9b4-a5d59f3532f5)

THANKS!
