### ISSUE TITLE
Support syncing macOS Finder file tags

### ISSUE THREAD

**Issue by alexhaas** [nextcloud/desktop#71] opened 2017-11-27 06:43 UTC
As far as I can tell, Nextcloud does not support syncing tags that are added to files in Finder on macOS (https://support.apple.com/en-us/HT202754). Since Dropbox supports syncing these tags, I think it would be extremely beneficial to add this to the Nextcloud feature set.

### Steps to reproduce

1. Install Nextcloud on more than one Mac.
2. Add a tag to a synced file.
3. Tag never syncs to other computers.

### Expected behaviour

The tags should be synced (like Dropbox).

### Actual behaviour

Nothing happens.

**Comment by crobarcro** [comment] 2018-06-29 10:29
One method of implementing local tagging would be to use a hidden folder in the nextcloud top level directory, e.g. _.nextcloud/tags_ where tags for all the user's files are synced. Then use this in some interface to add or view the tags. This would then be cross-platform.

An open source program which takes the local database approach is TMSU (GPLv3):

https://github.com/oniony/TMSU

Ideally to add tags on the various operating systems there would be a right-click menu option in the file browser to add tags, or view tags for the file. The biggest issue would be Linux users because of the fragmented desktop experience (but we are more willing to set up such things ourselves).

**Comment by MorrisJobke** [comment] 2018-07-19 08:30
Duplicate of #206

**Closed by MorrisJobke** 2018-07-19 08:30 UTC
Labels: feature request, macOS

**Comment by helmut72** [comment] 2018-11-15 08:39
@jospoortvliet: great 👍

Btw, it's not only macOS but also iOS, if Nextcloud on iOS supports tags anytime 😉

**Comment by alexhaas** [comment] 2018-11-15 15:08
@jospoortvlient Thanks for the reply. This isn’t just about supporting, or special-casing one system, like macOS. Nextcloud ignores all extended file attributes during sync, which is causing data loss. 

http://en.wikipedia.org/wiki/Extended_file_attributes
