### ISSUE TITLE
Nextcloud client complains about missing keyring service

### ISSUE THREAD

**Issue by thorian93** [nextcloud/desktop#990] opened 2019-01-02 11:39 UTC
### Expected behaviour
On logon the Nextcloud clients starts automatically and unlocks the gnome keychain in the background enabling syncing without user interaction.

### Actual behaviour
Since some time (I can not really tell when I experienced this first) when I freshly install the nextcloud client from the fedora repositories it installs and works as expected after the initial password prompt until I login in after a reboot. It then tells me, that there is no keyring service available.

### Steps to reproduce
1. Install nextcloud-client from Fedora Repositories
2. Log into a server
3. Reboot (or relogin)
4. See nexcloud GUI

### Client configuration
Client version: 2.3.3

Operating system: Fedora 29/28

OS language: English

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From Nextcloud or distro) (Linux only): QT 5.11.1

Installation path of client: /usr/bin/nextcloud

### Server configuration

Operating system: Ubuntu 16.04

Web server: Apache

Database: MySQL

PHP version: 7.0

Nextcloud version: 14

### Proposed Solution
I fixed the issue by simply installing libgnome-keyring from the Fedora repositories. Maybe this is a missing dependency?

Thanks and regards,
Thorian

**Comment by juliushaertl** [comment] 2019-08-20 14:30
The client uses qtkeychain which is already capable of using libsecret. So this is most likely a packaging issue of the fedora version.

**Comment by juliushaertl** [comment] 2019-08-20 14:32
Lets close this as a duplicate of https://github.com/nextcloud/desktop/issues/427

**Closed** 2019-08-20 14:33 UTC
