### ISSUE TITLE
[Bug]: macOS scrollbar for recent changes not easily selectable. 

### ISSUE THREAD

**Issue by gennaios** [nextcloud/desktop#5835] opened 2023-06-22 02:08 UTC
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

I think the scroll bar is too small and I am unable to select it to scroll long lists. 

### Steps to reproduce

1. Try selecting scroll bar so one can scroll view as with any other window on macOS. 
...

### Expected behavior

Scroll bar control should be selectable. 

### Which files are affected by this bug

None

### Operating system

Mac OS

### Which version of the operating system you are running.

Ventura

### Package

Appimage

### Nextcloud Server version

27

### Nextcloud Desktop Client version

3.9.0

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 3.4.2 to 3.4.4)

### Are you using the Nextcloud Server Encryption module?

Encryption is Enabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by narFnarF** [comment] 2024-08-02 14:54
Same issue on Linux Fedora, in the Gnome desktop environment.

![image](https://github.com/user-attachments/assets/33def7e7-57c2-40b2-aa35-df9e7f6186ae)


The only way to grab the scrollbar is to grab it exactly on the edge on the left side. You need to be extra-precise, which is annoying and unintuitive.

![image](https://github.com/user-attachments/assets/bb97e477-fe14-4674-b8f7-c3255d26010b)

**Comment by joshtrichards** [comment] 2024-08-16 05:50
Duplicate of #5536

**Closed by joshtrichards** 2024-08-16 05:50 UTC
Labels: 0. Needs triage
