### ISSUE TITLE
Button "There are unsolved conflicts. Press here.." is dead 

### ISSUE THREAD

**Issue by wahboh** [nextcloud/desktop#2516] opened 2020-10-05 20:51 UTC
### Expected behaviour
The yellowish notification button "There are unsolved conflicts. Press here..." should open up a log, or possibly the folder, where there are conflicts.

### Actual behaviour
The notification/button is dead. Nothing happens when pressing it. 

### Steps to reproduce
1. Get conflicts
2.
3.

### Client configuration
3.0.2

Operating system:
Windows 10 2004

OS language:
Swedish

**Comment by er-vin** [comment] 2020-10-06 05:54
Duplicate of #1195

**Closed** 2020-10-06 05:54 UTC
