### ISSUE TITLE
[Bug]: random en-masse file & folder deletion?

### ISSUE THREAD

**Issue by thomas725** [nextcloud/desktop#5581] opened 2023-04-07 06:01 UTC
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [x] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

Every few months I believe my Nextcloud desktop client (currently Version 3.4.2 Linux, on Linux Mint kernel 5.19.0.38) deletes massive amounts of data. I've found I can restore them from trash using the "occ" cli at least, but I'd prefer it if nothing get's deleted unless a user manually truly deletes it...

### Steps to reproduce

I don't really know sadly, it happens very infrequently. It happened sometime around December/January, and again now on 24th of March. Unsure if it happened more than those two times.

### Expected behavior

Files should only be deleted if a user deletes them.

### Which files are affected by this bug

*

### Operating system

Linux

### Which version of the operating system you are running.

Linux Mint 20.3

### Package

Distribution

### Nextcloud Server version

Nextcloud Hub 3 (25.0.5)

### Nextcloud Desktop Client version

3.4.2

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 3.3.6 to 3.4.0)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [X] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Nextcloud Server logs

```shell
I just noticed that it happened again on 24th of March, the logs don't reach that far back sadly..
```

### Additional info

The "Create Debug Archive ..." Button of my Desktop-Client sadly doesn't seem to do anything.

**Comment by StyXman** [comment] 2023-04-16 07:16
Sounds like a dupe of https://github.com/nextcloud/desktop/issues/5400

**Comment by k00ni** [comment] 2023-05-25 06:41
It sounds like the same a client of mine is experiencing. They report that since months they randomly loose files and entire folders. 

Whats also strange is the fact, **that the given user of the deletion was not even active at the time of the deletion**. Either activity app is faulty or there is a bug, which confuses users and their actions sometimes. My related report: https://github.com/nextcloud/activity/issues/980

**The setup:**
* Server v25.0.5.1 (foreign hoster)
* NC Clients v3.8.x (mostly Windows 10/11)

Here one entry of related log entries about the deletion (some data replaced for privacy reasons):

`{"reqId":"ZGsgquguEFnFoLo3lTieaAAAAAg","level":1,"time":"2023-05-22T07:58:34+00:00","remoteAddr":"xxx.yyy.zzz.11","user":"XXXXXXXX","app":"admin_audit","method":"DELETE","url":"/remote.php/dav/files/XXXXXXXX/Konten/Dateien%20zu%20%C3%BCberweisen_temp.%20Kopien/120-15.5.%20Zirkus/YYYYYYYY%2020%E2%82%AC%20zur%C3%BCck.pdf","message":"File deleted: \"/Konten/Dateien zu \u00fcberweisen_temp. Kopien/120-15.5. Zirkus/XXXXXXXX 20\u20ac zur\u00fcck.pdf\"","userAgent":"Mozilla/5.0 (Windows) mirall/3.8.1stable-Win64 (build 20230419) (Nextcloud, windows-10.0.19045 ClientArchitecture: x86_64 OsArchitecture: x86_64)","version":"25.0.5.1","data":{"app":"admin_audit"}}
`

Hoster run extensive logging, so we may provide further logs, if that is of any help.

**Comment by joshtrichards** [comment] 2024-09-07 16:17
Hi @thomas725 - Are you still experiencing this?

**Comment by claucambra** [comment] 2024-11-08 08:52
Hello, since no new info has been provided for a few months I will go ahead and close the issue. If the issue reappears, please do reopen the issue and we will take a look into it

**Closed by claucambra** 2024-11-08 08:52 UTC
Labels: 0. Needs triage, bug, needs info, feature: :arrows_counterclockwise: sync engine, stable-3.4

**Comment by k00ni** [comment] 2024-11-08 09:58
I am a bit confused. Sure there was no activity for months, but nobody responded to @thomas725's or my comment. I provided a screenshot and metadata, but there was no feedback about it. The tag "needs info" was added in September, but no one provided any information what "info" was needed to work on this issue.

**Comment by akrea** [comment] 2025-04-13 20:03
Ok, this happend to a friend of mine of mine today. 

![Image](https://github.com/user-attachments/assets/58ac18c3-b7ea-4eb5-afd8-19cad44b120b)

These folders were not deleted actively (unless user error) by my friend. He mentioned that he noted it when his the nc client started to pop up sync issues ("not able to find the folder") according to him while he did not change anything in any folder which is synced to the server. The same issue happened a week ago to him already - see last time in the picture "7 days" ago.

In summer 2024 I also had an incidence, where "from" another users client shared folders were deleted. I attributed this to user error. But now I am not so sure anymore as my fried generally knows what he is doing.

I asked him to provide  a screenshot of his activity panel when he logs in next time. To perhaps get some more info.

In the logs i did not see suspicious entries that would fit the timeframe. Let me know what I should look for and I will paste the logs here.

To follow protocol:

### Steps to reproduce
1. unknown

### Expected behaviour
not deleting files and folders at random

### Actual behaviour
for no reason known to us folders and files get deleted.

### Server configuration

**Web server:**
nginx

**Database:**
Art: mysql
Version: 11.4.5
Größe: 1.7 GB

**PHP version:**
PHP
Version: 8.3.17
Speicherlimit: 5 GB
Maximale Ausführungszeit: 3600
Maximale Größe zum Hochladen: 2 GB
OPcache-Revalidierungshäufigkeit: 60
Erweiterungen: Core, date, libxml, pcre, zlib, filter, hash, json, random, readline, Reflection, SPL, session, cgi-fcgi, bcmath, bz2, ctype, curl, dom, fileinfo, ftp, gd, gmp, iconv, standard, intl, ldap, mbstring, openssl, pcntl, PDO, pgsql, posix, imap, SimpleXML, sockets, sodium, sqlite3, sysvsem, xml, xmlwriter, zip, exif, mysqlnd, pdo_pgsql, pdo_sqlite, Phar, xmlreader, pdo_mysql, apcu, msgpack, igbinary, redis, memcached, imagick, mcrypt, smbclient, libsmbclient, Zend OPcache

**Nextcloud version:** 
30.0.6 provided by linuxserver

**OS**
```
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.5 LTS
Release:        22.04
Codename:       jammy
```

**Docker**
```
Client: Docker Engine - Community
 Version:           28.0.0
 API version:       1.48
 Go version:        go1.23.6
 Git commit:        f9ced58
 Built:             Wed Feb 19 22:10:30 2025
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          28.0.0
  API version:      1.48 (minimum version 1.24)
  Go version:       go1.23.6
  Git commit:       af898ab
  Built:            Wed Feb 19 22:10:30 2025
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.7.25
  GitCommit:        bcc810d6b9066471b0b6fa75f557a15a1cbf31bb
 runc:
  Version:          1.2.4
  GitCommit:        v1.2.4-0-g6c52b3f
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```


<details>
<summary>List of activated apps</summary>

```
  - activity: 3.0.0
  - admin_audit: 1.20.0
  - announcementcenter: 7.1.0
  - app_api: 4.0.6
  - bruteforcesettings: 3.0.0
  - calendar: 5.2.0
  - cloud_federation_api: 1.13.0
  - comments: 1.20.1
  - contacts: 7.0.4
  - contactsinteraction: 1.11.0
  - cookbook: 0.11.3
  - dashboard: 7.10.0
  - dav: 1.31.1
  - deck: 1.14.4
  - federatedfilesharing: 1.20.0
  - federation: 1.20.0
  - files: 2.2.0
  - files_accesscontrol: 1.20.1
  - files_downloadactivity: 1.17.0
  - files_downloadlimit: 3.0.0
  - files_external: 1.22.0
  - files_pdfviewer: 3.0.0
  - files_reminders: 1.3.0
  - files_sharing: 1.22.0
  - files_trashbin: 1.20.1
  - files_versions: 1.23.0
  - firstrunwizard: 3.0.0
  - logreader: 3.0.0
  - lookup_server_connector: 1.18.0
  - mail: 4.3.3
  - memories: 7.5.2
  - news: 25.3.1
  - nextcloud_announcements: 2.0.0
  - notes: 4.11.0
  - notifications: 3.0.0
  - oauth2: 1.18.1
  - onlyoffice: 9.7.0
  - password_policy: 2.0.0
  - passwords: 2025.3.20-build5674
  - photos: 3.0.2
  - polls: 7.4.1
  - previewgenerator: 5.8.0
  - privacy: 2.0.0
  - provisioning_api: 1.20.0
  - quota_warning: 1.21.0
  - recognize: 8.2.0
  - recommendations: 3.0.0
  - related_resources: 1.5.0
  - serverinfo: 2.0.0
  - settings: 1.13.0
  - sharebymail: 1.20.0
  - spreed: 20.1.5
  - support: 2.0.0
  - survey_client: 2.0.0
  - systemtags: 1.20.0
  - tasks: 0.16.1
  - text: 4.1.0
  - theming: 2.6.0
  - twofactor_backupcodes: 1.19.0
  - twofactor_nextcloud_notification: 4.0.0
  - twofactor_totp: 12.0.0-dev
  - updatenotification: 1.20.0
  - user_ldap: 1.21.0
  - user_status: 1.10.0
  - viewer: 3.0.0
  - weather_status: 1.10.0
  - webhook_listeners: 1.1.0-dev
  - workflowengine: 2.12.0
Disabled:
  - analytics: 5.2.4 (installed 5.2.4)
  - apporder: 0.15.0 (installed 0.15.0)
  - audioplayer: 3.4.1 (installed 3.4.1)
  - breezedark: 29.0.0 (installed 29.0.0)
  - circles: 30.0.0 (installed 0.21.4)
  - encryption: 2.18.0 (installed 2.8.1)
  - facerecognition: 0.9.60 (installed 0.9.60)
  - files_antivirus: 5.6.1 (installed 5.6.1)
  - files_fulltextsearch_tesseract: 27.0.1 (installed 27.0.1)
  - files_rightclick: 1.6.0 (installed 1.6.0)
  - integration_discourse: 2.3.0 (installed 2.3.0)
  - integration_twitter: 1.0.7 (installed 1.0.7)
  - maps: 1.5.0 (installed 1.5.0)
  - ransomware_protection: 1.14.0 (installed 1.14.0)
  - registration: 2.6.0 (installed 2.6.0)
  - suspicious_login: 8.0.0
  - video_converter: 1.0.6 (installed 1.0.6)
  - workflow_ocr: 1.30.1 (installed 1.30.1)
```
</details>

<details>
<summary>Nextcloud configuration</summary>

```
{
    "system": {
        "memcache.local": "\\OC\\Memcache\\APCu",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "192.168.0.10:7300",
            "nextcloud.akrea.ch",
            "onlyoffice.akrea.ch"
        ],
        "dbtype": "mysql",
        "version": "30.0.6.2",
        "overwrite.cli.url": "https:\/\/nextcloud.akrea.ch",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "maintenance": false,
        "theme": "",
        "loglevel": 1,
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "ssl",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "encryption.legacy_format_support": false,
        "encryption.key_storage_migrated": false,
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
        "default_phone_region": "CH",
        "enable_previews": true,
        "enabledPreviewProviders": [
            "OC\\Preview\\Movie",
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\BMP",
            "OC\\Preview\\XBitmap",
            "OC\\Preview\\MP3",
            "OC\\Preview\\MP4",
            "OC\\Preview\\TXT",
            "OC\\Preview\\MarkDown",
            "OC\\Preview\\PDF"
        ],
        "log_type": "file",
        "logfile": "\/config\/log\/nextcloud\/nextcloud.log",
        "log_rotate_size": 104857600,
        "filelocking.enabled": "true",
        "memcache.locking": "\\OC\\Memcache\\APCu",
        "app_install_overwrite": [
            "news"
        ],
        "upgrade.disable-web": true,
        "maintenance_window_start": "4",
        "memories.exiftool": "\/config\/www\/nextcloud\/apps\/memories\/bin-ext\/exiftool-amd64-musl",
        "memories.vod.path": "\/config\/www\/nextcloud\/apps\/memories\/bin-ext\/go-vod-amd64",
        "memories.vod.ffmpeg": "\/usr\/bin\/ffmpeg",
        "memories.vod.ffprobe": "\/usr\/bin\/ffprobe",
        "memories.db.triggers.fcu": true,
        "preview_max_x": 1024,
        "preview_max_y": 1024,
        "memories.gis_type": 1,
        "opcache.memory_consumption": 256
    }
}```
