### ISSUE TITLE
3.0.1 Click on activity entry just opens webinterface

### ISSUE THREAD

**Issue by OdinsAuge** [nextcloud/desktop#2362] opened 2020-09-04 11:02 UTC
### Expected behaviour
It is not an actual issue as the behavior is on purpose I guess but the behavior is quite useless.
If I click on an entry in the activity list (click once on the task bar icon) I expect the local folder to be opened to e.g. fix conflict issues.

### Actual behaviour
If you click on an activity entry e.g. a conflict notification, the web interface opens.
It does not even open the affected file, it just opens the web interface. As the entry does not show the actual file name (only the beginning part of the path) it is not possible to find out which file is affected.

### Steps to reproduce
1. Click once on the task bar/info bar icon.
2. Click on any activity entry
3.See how the web interface opens

### Client configuration
Client version: 3.0.1
Operating system: Windows 10
OS language: German
Installation path of client: C:\Program FIles\Nextcloud

### Logs

As this is just a design issue an not an actual bug, log files don't make sense.
If this is an actual bug or you need certain parts of log files, please notify me.

**Comment by thejulian** [comment] 2020-09-07 11:56
Same issue an macOS with Client 3.0.1. 
Can't resolve conflicts because the tab is missing.

**Comment by er-vin** [comment] 2020-09-07 11:58
Looks like a duplicate of #2349 isn't it?

**Comment by jospoortvliet** [comment] 2020-09-08 13:39
yeah, it's a duplicate. Can you close it, Odin, or clarify what's different about it compared to #2349

**Closed** 2020-09-09 18:06 UTC
