### ISSUE TITLE
Windows client 3.0.1 - import configuration of earlier version ignores folder subscriptions

### ISSUE THREAD

**Issue by ArjenR** [nextcloud/desktop#2403] opened 2020-09-10 08:12 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour
On upgrade the configuration of previous version should be imported and applied.

### Actual behaviour
Apart from the issue of it not importing until repetetivly restarting the client it will decide on it's own to unsubscribe from large folders. The buttons to allow syncing will subscribe to all folders, also unsubscribed folders.

### Steps to reproduce
1. Upgrade
2. Restart client
3. Choose to allow sync of large folders when reported.

### Client configuration
Client version: 3.0.1
Operating system: Windows 10

OS language: Dutch

**Comment by er-vin** [comment] 2020-09-10 10:41
Duplicate of #2279

**Closed by er-vin** 2020-09-10 10:41 UTC
