### ISSUE TITLE
same sharing options in desktop- and web-app

### ISSUE THREAD

**Issue by Flo-MF** [nextcloud/desktop#4411] opened 2022-04-04 13:53 UTC
Hi,

is it possible, to add the same sharing options into the context menue of the desktop clients as available in the webinterface?

we are currently missing the option "Hide Download", which is availalable in the webinterface.

We use Basically MacOS with the current release 3.4.4.
Nextcloud Server: 22.2.5

Thanks!

Client:
<img width="284" alt="Bildschirmfoto 2022-04-04 um 15 49 10" src="https://user-images.githubusercontent.com/66617442/161558417-bd2a5b81-5e23-4df6-bc26-80b9c0c4e250.png">

Web:
<img width="315" alt="Bildschirmfoto 2022-04-04 um 15 50 10" src="https://user-images.githubusercontent.com/66617442/161558616-3a17bc55-df9a-4c65-ad66-cd4f5482beb5.png">

**Comment by joshtrichards** [comment] 2023-11-22 14:54
Duplicate of #2672

More importantly, fixed in #5622

**Closed by joshtrichards** 2023-11-22 14:54 UTC
Labels: enhancement
