### ISSUE TITLE
Conflict notification: Clicking on "For details click here" does not do anything

### ISSUE THREAD

**Issue by svenb1234** [nextcloud/desktop#2510] opened 2020-10-05 05:14 UTC
### Expected behaviour
Clicking on "For details click here" should open some dialogue to resolve the conflicts.

### Actual behaviour
Nothing.

### Steps to reproduce
1. Let the desktop app create/detect some conflict
2. Open the app's settings window. This shows the nextcloud folders and a yellow notification at the top which states: Unresolved conflicts exist. For details click here.
3.Click on the notification.

### Client configuration
Client version:
3.0.2

Operating system:
Windows 10

OS language:
German

### Server configuration
Nextcloud version:
19.0.3

**Comment by er-vin** [comment] 2020-10-05 08:16
Duplicate of #1195

**Closed by er-vin** 2020-10-05 08:16 UTC
Labels: bug, feature: :gear: settings
