### ISSUE TITLE
Continuous high CPU usage (~15%) in all versions

### ISSUE THREAD

**Issue by tobizviz** [nextcloud/desktop#1601] opened 2019-11-13 05:23 UTC
The NextCloud desktop client will consume 15% CPU continuously on start until you open a webview (e.g., Account -> Add new -> Register with provider) and then close it.
I have experienced this bug since initially installing at version 2.5 (now 2.6.1). It really doesn't seem like it should be hard to fix.

My OS: Window 7. My Qt Version: 5.12.5.

**Comment by dkohtes** [comment] 2019-11-16 18:03
On Mac it is depending on an active sync. If all sync are inactive CPU usage is low again.

**Comment by dkohtes** [comment] 2019-11-16 18:06
BTW, opening a webview didn't change anything on CPU usage on Mac OS 10.15.1

**Comment by nursoda** [comment] 2019-11-26 22:23
https://github.com/nextcloud/desktop/issues/1513

**Comment by misch7** [comment] 2019-12-01 02:34
Indeed, duplicate of #1513.

**Closed by misch7** 2019-12-01 02:34 UTC
