### ISSUE TITLE
[Bug]: kernel: [ 3455.369213] nextcloud[2156]: segfault at ffffffffffffffff ip 00007f70e2ff87b1 sp 00007ffff81bb118 error 5 in libgobject-2.0.so.0.7200.4[7f70e2fce000+33000]

### ISSUE THREAD

**Issue by picarica** [nextcloud/desktop#5259] opened 2022-12-09 09:56 UTC
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

The share dialog is looking incomplete.
...
so my Nextcloud version 3.6.4-20221208.195402.3ffb9827b-1.0~jammy1
i installed it via ppa on linux mint 21
the problem is, that nextcloud takes up to 7GB of ram when starting and is unresponsive, then it crashes and asks me to force stop
these errors are in my syslog
https://dpaste.org/v6VPA here are all my logs i could find

### Steps to reproduce

1. just install and run nextcloud, i already have like 4 sync connections but those work fine on my home machine
...

### Expected behavior

actualy work sync and start instead of crashing
...

### Which files are affected by this bug

idk

### Operating system

Linux

### Which version of the operating system you are running.

Linux mint 21 jammy

### Package

Other

### Nextcloud Server version

 25.0.1

### Nextcloud Desktop Client version

3.6.4

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [X] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Nextcloud Server logs

```shell
couldnt find these files but i have ouput from syslog
```

### Additional info

here i uploadex nextcloud debug log, its 100 MB in size so i couldnt embed it https://files.catbox.moe/yyvjcw.zip

**Comment by joshtrichards** [comment] 2023-11-26 13:22
Hi @picarica - Thanks for the report. 

1. Are you still experiencing this with newer versions?
2. Can you reproduce this issue with the AppImage?

Any chance you experienced the same matter as #5267 (which has since been fixed by #5680)?

**Comment by joshtrichards** [comment] 2024-08-16 04:47
No response after >6 months. Presuming fixed.

**Closed by joshtrichards** 2024-08-16 04:47 UTC
Labels: 0. Needs triage, bug, needs info, package: PPA, crash
