### ISSUE TITLE
Desktop client 2.3.3 unusable on 1024x600 screens, buttons outside of screen

### ISSUE THREAD

**Issue by rschr** [nextcloud/desktop#218] opened 2018-03-15 22:19 UTC
The current desktop clients (here: 2.3.3 on Linux, Ubuntu Mate 16.04 LTS, and 2.3.3.1 on Windows 7) cannot be resized anymore to become small enough to fit on a 1024x600 (netbook) screen, let alone one with a start bar/task bar visible. As the application window cannot be moved upwards outside of the screen, either, the command buttons on the lower edge of the client become permanently invsible, so making changes in the client becomes impossible.

I cannot say when the change happened, but the "2.3.2 beta" client that I just updated on the Windows netbook was still ok. I'm attaching screenshots for both Windows 7 and Linux (Ubuntu Mate 16.04 LTS) with the latest clients. 

![nc-cl233-ubuntumate](https://user-images.githubusercontent.com/2419967/37493970-26ca5c80-28a7-11e8-8761-c6e2a883da9a.png)
![nc-cl-2331-win7](https://user-images.githubusercontent.com/2419967/37493971-26f3232c-28a7-11e8-84f3-57baa7d718a5.png)

**Comment by TerraRoot** [comment] 2018-04-13 09:19
I came here to post the same, if i drag the window as high as i can then scroll down, i can just see the edge of the "add folder sync connection" button, can't read it but can click on it, no hope of reaching the close button.

**Comment by ykgmfq** [comment] 2018-05-16 14:50
Diplicate of #91

**Comment by juliushaertl** [comment] 2018-06-18 17:38
Closing as a duplicate of https://github.com/nextcloud/desktop/issues/91

**Closed by juliushaertl** 2018-06-18 17:38 UTC
Labels: 0. Needs triage
