### ISSUE TITLE
[Bug]: File Was Not Uploaded

### ISSUE THREAD

**Issue by MatsG23** [nextcloud/desktop#4604] opened 2022-05-30 13:49 UTC
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

On 28th May 2022 around the time of 15:55, I finalized a document.
Today I noticed that all progress from that day is gone.

### Steps to reproduce

If I knew...

### Expected behavior

The edited file version from the client should have been uploaded to the server.

### Which files are affected by this bug

Dokumente/Schule/Englisch/Our green planet/Analyzing a cartoon.docx

### Operating system

Windows

### Which version of the operating system you are running.

Windows 11

### Package

Appimage

### Nextcloud Server version

23.0.5

### Nextcloud Desktop Client version

3.5.1

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 3.4.2 to 3.4.4)

### Are you using the Nextcloud Server Encryption module?

Encryption is Enabled

### Are you using an external user-backend?

- [X] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Nextcloud Server logs

```shell
None for that time
```

### Additional info

[debug-archive.zip](https://github.com/nextcloud/desktop/files/8798790/debug-archive.zip)

I think the edited file version was never updated to the server as I could not find anything for the time around 15:55 in the server logs.
Did the client download and overwrite that file from the server?

**Comment by joshtrichards** [comment] 2023-11-23 14:13
Hi @MatsG23 - I'm sorry to hear you encountered this.

Unfortunately your debug logs don't quite go back to that time frame so it's impossible to identify what occurred based on those.

Your web server access logs, at the time, would have shown what transactions took place with your Nextcloud instance. For example, if the document was re-downloaded from the server. Unfortunately a lot of time has now passed so not sure if you have those logs.

It's possible you may have a recoverable version under *Details->Versions* for that file in the NC Web UI.

Hopefully you found some assistance through another path - such as the Nextcloud Help Forum at https://help.nextcloud.com. In the future, that might be a more timely channel if you haven't utilized it before.

**Comment by joshtrichards** [comment] 2024-09-03 20:16
Closing for the time being since there's enough here to isolate the cause.

**Closed by joshtrichards** 2024-09-03 20:16 UTC
Labels: 0. Needs triage, bug, feature: :arrows_counterclockwise: sync engine
