### ISSUE TITLE
[Bug]: Windows client causes Windows Explorer crash

### ISSUE THREAD

**Issue by rasmus8484** [nextcloud/desktop#6575] opened 2024-03-23 12:53 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

As the title reads this is a the nextcloud client for windows causing Windows Explorer to crash. More specifically the shell extension causes Windows Explorer to crash whenever I right-click anything within Windows Explorer.

Specs:
 - Windows 10 (AMD Processor)
 - Nextcloud client version 3.12.2
 - Nextcloud server version 28.0.1 (Truenas Scale)

### Steps to reproduce

1. Open Windows Explorer
2. Right-click file or folder
3. Be sad because it crashed :(

### Expected behavior

Display context menu with the nextcloud shell extension working I guess.

### Installation method

None

### Nextcloud Server version

28

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by SleepyLaiyla** [comment] 2024-03-23 16:00
This problem also happens in Windows 11.

**Comment by EzekialSA** [comment] 2024-03-23 17:29
I was able to download a fresh install of the installer and run the repair mode and it fixed it for windows 11. At least for now.

**Comment by cho0p** [comment] 2024-03-23 19:18
I can confirm that the explorer crashes when doing a right-click on a file. Windows 11 Pro 23H2 22631.3296, Nextcloud client 3.12.2

**Comment by recolic** [comment] 2024-03-24 03:53
I'm hitting the same problem after upgrading to Nextcloud 3.12.2
Nextcloud client is running perfectly fine, but when I right-click any file in Nextcloud folder, it will freeze for 1 sec, then explorer crashed.

OS: Windows 10 Pro 22H2

**Comment by BlueFisher** [comment] 2024-03-24 10:28
After upgrading to 3.12.2. The explorer crashes and restart automatically when click explorer from the taskbar.
But  after downgrading to 3.12.1. The problem solved.

Windows 11 23H2 22631.3296

**Comment by Kybeer** [comment] 2024-03-24 11:00
I have the same problem after upgrading to Nextcloud 3.12.2

It's intermittent for me though.

**Comment by pzwahlen** [comment] 2024-03-24 11:17
Corresponding WinEvent log:
```
Faulting application name: Explorer.EXE, version: 10.0.22621.3296, time stamp: 0x48d2cb32
Faulting module name: NCContextMenu.dll_unloaded, version: 3.0.0.47, time stamp: 0x65fae7f1
Exception code: 0xc0000005
Fault offset: 0x0000000000001010
Faulting process id: 0x0x5254
Faulting application start time: 0x0x1DA7DD01EFAAC6A
Faulting application path: C:\Windows\Explorer.EXE
Faulting module path: NCContextMenu.dll
Report Id: 17e0164c-a20d-4d71-82c3-b1d0c1d6f2c4
Faulting package full name: 
Faulting package-relative application ID: 
```

**Comment by vagner-dias** [comment] 2024-03-24 11:18
I see a PR which seems to be related to this issue.

https://github.com/nextcloud/desktop/pull/6573

**Comment by acisternino** [comment] 2024-03-24 12:31
Same here.  Nextcloud client 3.12.2 on the latest Windows 10.

**Comment by Riggs0** [comment] 2024-03-24 14:28
Also experiencing this, and on two different machines. Both latest Win 11 and 3.12.2

**Comment by ulht-a22102503** [comment] 2024-03-24 15:05
This seems to be a duplicate of #6566

**Comment by RavingSombra** [comment] 2024-03-24 15:06
This seems to be a duplicate of #6566

**Comment by joshtrichards** [comment] 2024-03-25 12:34
Duplicate of #6566

**Closed by joshtrichards** 2024-03-25 12:34 UTC
Labels: 0. Needs triage, bug
