### ISSUE TITLE
Desktop client requests to grant access every day

### ISSUE THREAD

**Issue by bnjbvr** [nextcloud/desktop#4095] opened 2021-12-16 20:59 UTC
### Expected behaviour

After logging in a first time with the Web client, subsequent logins shouldn't require me to log in via the Web interface after every reboot of my machine.

### Actual behaviour

Well... the client does ask for a new login (opening the Web browser window, asking to confirm my log in via Nextcloud's web interface) every time I reboot my machine. Seems to match the relatively recent experience of https://help.nextcloud.com/t/windows-agent-require-to-grant-access-every-day/123052 or also https://www.mail-archive.com/misc@openbsd.org/msg179569.html.

### Client configuration

```
> nextcloud --version
Nextcloud version 3.3.6git
Git revision 6d3270dd251db42293233d5622a610ea172dabef
Using Qt 5.15.2, built against Qt 5.15.2
Using Qt platform plugin 'xcb'
Using 'OpenSSL 1.1.1l  24 Aug 2021'
Running on Arch Linux, x86_64
```

installed from https://archlinux.org/packages/community/x86_64/nextcloud-client/

### Server configuration

Nextcloud version: Nextcloud Hub II (23.0.0)
Storage backend (external storage): none

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile: 

(snipped to only contain lines that contain `credentials`, as i saw a few errors, and replaced usernames/domains:)

<details>

```
2021-12-16 21:43:41:283 [ info nextcloud.sync.credentials.webflow ]:	Get QNAM
2021-12-16 21:43:42:103 [ info nextcloud.sync.credentials.webflow ]:	Fetch from keychain!
2021-12-16 21:43:42:150 [ warning nextcloud.sync.credentials.keychainchunk ]:	Unable to read "USERNAME_clientCertificatePEM:https://nextcloud.example.com/:0" chunk "0" "Entry not found"
2021-12-16 21:43:42:151 [ warning nextcloud.sync.credentials.keychainchunk ]:	Unable to read "USERNAME_clientKeyPEM:https://nextcloud.example.com/:0" chunk "0" "Entry not found"
2021-12-16 21:43:42:151 [ warning nextcloud.sync.credentials.webflow ]:	Unable to read client key "Entry not found"
2021-12-16 21:43:42:152 [ warning nextcloud.sync.credentials.keychainchunk ]:	Unable to read "USERNAME_clientCaCertificatePEM0:https://nextcloud.example.com/:0" chunk "0" "Entry not found"
2021-12-16 21:43:42:152 [ warning nextcloud.sync.credentials.webflow ]:	Unable to read client CA cert slot "0" "Entry not found"
2021-12-16 21:43:42:268 [ warning nextcloud.sync.credentials.keychainchunk ]:	Unable to read "USERNAME_clientCertificatePEM:https://nextcloud.example.com/" chunk "0" "Entry not found"
2021-12-16 21:43:42:268 [ warning nextcloud.sync.credentials.keychainchunk ]:	Unable to read "USERNAME_clientKeyPEM:https://nextcloud.example.com/" chunk "0" "Entry not found"
2021-12-16 21:43:42:268 [ warning nextcloud.sync.credentials.webflow ]:	Unable to read client key "Entry not found"
2021-12-16 21:43:42:269 [ warning nextcloud.sync.credentials.keychainchunk ]:	Unable to read "USERNAME_clientCaCertificatePEM0:https://nextcloud.example.com/" chunk "0" "Entry not found"
2021-12-16 21:43:42:269 [ warning nextcloud.sync.credentials.webflow ]:	Unable to read client CA cert slot "0" "Entry not found"
2021-12-16 21:43:42:270 [ info nextcloud.gui.account.state ]:	Fetched credentials for "https://nextcloud.example.com" attempting to connect
2021-12-16 21:43:42:270 [ info nextcloud.sync.credentials.webflow ]:	Get QNAM
2021-12-16 21:43:42:272 [ info nextcloud.sync.credentials.webflow ]:	request finished
2021-12-16 21:43:42:272 [ warning nextcloud.sync.credentials.webflow ]:	QNetworkReply::HostNotFoundError
2021-12-16 21:43:42:272 [ warning nextcloud.sync.credentials.webflow ]:	"Host nextcloud.example.com not found"
2021-12-16 21:43:42:272 [ warning nextcloud.sync.credentials.webflow ]:	QNetworkReply::HostNotFoundError
2021-12-16 21:43:42:272 [ warning nextcloud.sync.credentials.webflow ]:	"Host nextcloud.example.com not found"
2021-12-16 21:43:51:202 [ info nextcloud.sync.credentials.webflow ]:	Get QNAM
2021-12-16 21:43:51:306 [ info nextcloud.sync.credentials.webflow ]:	request finished
2021-12-16 21:43:51:306 [ info nextcloud.gui.account.state ]:	Invalid credentials for "https://nextcloud.example.com" asking user
2021-12-16 21:43:51:307 [ debug nextcloud.sync.credentials.webflow ]	[ OCC::WebFlowCredentials::askFromUser ]:	User needs to reauth!
2021-12-16 21:43:51:387 [ info nextcloud.sync.credentials.webflow ]:	request finished
2021-12-16 21:43:51:446 [ info nextcloud.sync.credentials.webflow ]:	request finished
2021-12-16 21:43:51:451 [ info nextcloud.sync.credentials.webflow ]:	request finished
2021-12-16 21:43:51:451 [ warning nextcloud.sync.credentials.webflow ]:	QNetworkReply::AuthenticationRequiredError
2021-12-16 21:43:51:452 [ warning nextcloud.sync.credentials.webflow ]:	"Host requires authentication"
2021-12-16 21:43:51:563 [ info nextcloud.sync.credentials.webflow ]:	request finished
2021-12-16 21:43:51:807 [ info nextcloud.sync.credentials.webflow ]:	request finished
2021-12-16 21:43:51:807 [ info nextcloud.sync.credentials.flow2auth ]:	setting remote poll timer interval to 30000 msec
2021-12-16 21:44:05:689 [ info nextcloud.sync.credentials.webflow ]:	request finished
2021-12-16 21:44:05:689 [ info nextcloud.sync.credentials.flow2auth ]:	Success getting the appPassword for user:  "USERNAME" , server:  "https://nextcloud.example.com"
2021-12-16 21:44:05:689 [ info nextcloud.sync.credentials.webflow ]:	Obtained a new password
2021-12-16 21:44:05:696 [ info nextcloud.sync.credentials.webflow ]:	Get QNAM
2021-12-16 21:44:05:697 [ debug nextcloud.sync.credentials.webflow ]	[ OCC::WebFlowCredentials::slotAskFromUserCancelled ]:	User cancelled reauth!
2021-12-16 21:44:05:697 [ info nextcloud.sync.credentials.webflow ]:	Get QNAM
2021-12-16 21:44:05:798 [ info nextcloud.sync.credentials.webflow ]:	request finished
```

</details>

2. Web server error log:
don't think they're relevant here?

3. Server logfile: nextcloud log (data/nextcloud.log):
don't think they're relevant here?

Thanks for your all work!!

**Comment by dafi87** [comment] 2021-12-18 08:37
People are experiencing the same problem on MacOS too, since at least September. Hope someone will look into it.

https://github.com/nextcloud/desktop/issues/3820

**Comment by claell** [comment] 2022-01-03 10:37
Closing as duplicate of #3820 now. Feel free to reopen if this is not correct.

**Comment by claell** [comment] 2022-01-03 10:38
Duplicate of #3820

**Closed by claell** 2022-01-03 10:38 UTC
Labels: bug, regression, feature: :key: authentication
