### ISSUE TITLE
Nextcloud GDPR client

### ISSUE THREAD

**Issue by PenguinFreeDom** [nextcloud/desktop#56] opened 2017-11-23 13:00 UTC
Hi would it be possible to make a GDPR version of the nextcloud client.

One that audits all read/write delete shareing copying even though the client is offline (The client would then send the logs to the server when the client is online agian).

Maby also with the feature to notifi the client user when certian data has been cheched out for a X period of time, if the law requires you to remove (uncheck) the data on the client after a period of time. 

https://help.nextcloud.com/t/nextcloud-gdpr-client/23786/2

**Comment by jospoortvliet** [comment] 2018-05-15 09:38
So the requested features are:
* audit logging on the client, not just the server, and also if offline
* automatically remove content even if client is offline (following server retention policy)

I don't think either are very GDPR related but they're compliance features that could be implemented. I haven't heard any demand from (prospective) customers for now so until there is - bottom of priority list.

**Comment by camilasan** [comment] 2021-02-01 11:55
> * 
> 
> * automatically remove content even if client is offline (following server retention policy)

this is remote wipe, right?

And doesn't admin_audit covers this kind of logging? 

I think this is a duplicate of #286.

**Closed by camilasan** 2021-02-01 11:55 UTC
Labels: 1. to develop, enhancement, feature-request, low
