### ISSUE TITLE
Nextcloud client for WIndows Ver3.3 crash

### ISSUE THREAD

**Issue by hnagasawa** [nextcloud/desktop#3643] opened 2021-08-10 09:20 UTC
We upload files from Nextcloud desktop client for Windows(Ver3.3) to Nextcloud(ver21.03)

Nextcloud desktop client for Windows(Ver3.3) crashed during files upload

Windows Event viewer messages next.

Analytical symbol:
Reconfirming the solution: 0
Report ID: ef3e57dc-8aac-4437-a7ae-edb78250a59a
Report status: 268435456
Hashed bucket: b072ae18ae51b47b8c20d52cb480c64d
Cab GUID: 0 "
Error, 2021/08/10 11:46:58, Application Error, 1000, (100), "Failed application name: nextcloud.exe, version: 3.3.0.25641, time stamp: 0x61026f49
Failed module name: CLDAPI.dll, version: 10.0.17763.1554, timestamp: 0xea1966db
Exception code: 0xc0000005
Fault offset: 0x00000000000128da
The failing process ID: 0x151c
Failed application start time: 0x01d78d90f045e38b
Failed application path: C: \ Program Files \ Nextcloud \ nextcloud.exe
Failed module path: C: \ Windows \ SYSTEM32 \ CLDAPI.dll
Report ID: ef3e57dc-8aac-4437-a7ae-edb78250a59a
The full name of the failing package:
Application ID associated with the failing package: "
Info, 2021/08/10 11:12:07, Windows Error Reporting, 1001, None, "Failure Bucket 2026854220300338765, Type 4
Event name: APPCRASH
Response: Not available
Cab ID: 0

Issue signature:
P1: nextcloud.exe
P2: 3.3.0.25641
P3: 61026f49
P4: CLDAPI.dll
P5: 10.0.17763.1554
P6: ea1966db
P7: c0000005
P8: 00000000000128da
P9:
P10:

**Comment by FlexW** [comment] 2021-08-10 10:44
Probably a duplicate of https://github.com/nextcloud/desktop/issues/3550. Can you provide your logs there or upload them to https://cloud.nextcloud.com/s/6w5abTCtdHJQjrw

**Closed by FlexW** 2021-08-10 10:45 UTC
Labels: bug
