### ISSUE TITLE
After upgrade to 3.0.0, most sync folders are not set up anymore

### ISSUE THREAD

**Issue by despens** [nextcloud/desktop#2326] opened 2020-08-27 07:21 UTC
### Expected behaviour
Upon upgrading the desktop client, all synced connections should remain set up.

### Actual behaviour
Upon upgrading from the previous stable 2.6 version, all sync connections except two have vanished from the client.

### Steps to reproduce
1. Have a dozen sync connections set up in client 2.6.x
2. Upgrade to 3.0
3. See connections vanish

### Client configuration
Client version: 3.0.0 (Ubuntu)
Operating system: Ubuntu 20.04
OS language: US English
Qt version used by client package (Linux only, see also Settings dialog): n/a, installed via official deb repository
Client package (From Nextcloud or distro) (Linux only): nextcloud-desktop 3.0.0-20200821.171045.ff175088a-1.0~focal1 amd64
Installation path of client: /usr/bin/nextcloud

### Server configuration
Nextcloud version: 18.0.6 and 19.0.1

Storage backend (external storage): Local file storage (default), s3 via minio

**Comment by Id3aFly** [comment] 2020-08-27 13:58
Might be a duplicate of #2279 and #2301

**Comment by despens** [comment] 2020-08-27 14:12
Yes I can now observe the same behavior as described in #2279 and #2279

**Comment by er-vin** [comment] 2020-08-31 07:04
Duplicate of #2279 indeed. Closing this one, to get the conversation in one place.

**Closed by er-vin** 2020-08-31 07:04 UTC
