### ISSUE TITLE
macOS: smaller menu bar icons

### ISSUE THREAD

**Issue by jmml97** [nextcloud/desktop#424] opened 2018-06-16 12:29 UTC
The icons on the menu bar of macOS are too big when compared with other icons (third party and system icons) and they should be made smaller for better consistency.
<img width="279" alt="captura de pantalla 2018-06-16 a las 14 17 37" src="https://user-images.githubusercontent.com/2082283/41498581-8f4bbe9e-7171-11e8-99a5-ef9f52b73635.png">

**Comment by juliushaertl** [comment] 2018-06-18 17:39
Duplicate of https://github.com/nextcloud/desktop/issues/16

**Closed by juliushaertl** 2018-06-18 17:39 UTC
Labels: bug, design
