### ISSUE TITLE
Direct mail to an external address 

### ISSUE THREAD

**Issue by in-session** [nextcloud/desktop#2529] opened 2020-10-08 09:00 UTC
Hello together,

we are quite new to Nextcloud and are currently facing the problem that we can't send a direct mail address to an external party via Nextcloud desktop client.

Nextcloud: 19.0.3
Nextcloud Client: 3.0.1 Windows

Error:
Sharing error from server 403 "Sharing of Nextcloud.png failed because info@mail.de was not found. Possibly the server is not reachable or uses a self-certified certificate".

The Nextcloud is connected via LDAPS this works as far as everything is correct and mail goes out. Sending by e-mail also works via web interface. We deactivated the Federated Cloud Sharing App for testing purposes, which did not involve any changes.

Sharing with LPADS users via Nextcloud Desktop-Client is possible.
Can it be that Nextcloud does not support this? Or do the mail addresses within the contacts have to be saved first?

Thanks for your help, greetings Christoph

![119906ad0e7833df45f19d02c7b2b4cf854931a5](https://user-images.githubusercontent.com/16542619/95437471-489c3900-0955-11eb-9d90-a308db3f7d47.png)
![2664fd38d66adf274a51d4bdea9e23577e05c884](https://user-images.githubusercontent.com/16542619/95437480-4a65fc80-0955-11eb-82b6-cfdfc9d94a28.png)
![e171f7343f594670ad4de0a7f42d31edc7816fd6](https://user-images.githubusercontent.com/16542619/95437492-4df98380-0955-11eb-9b8a-0f515d865412.png)

**Comment by er-vin** [comment] 2020-10-08 09:31
Thanks for the report. This is correct, only federated share is available on the client right now. We got another report for mail shares, I'll thus close this one.

Duplicate of #1180

**Closed by er-vin** 2020-10-08 09:31 UTC
