### ISSUE TITLE
Right-click on taskbar entry - expanding menu entries

### ISSUE THREAD

**Issue by hannes101** [nextcloud/desktop#1328] opened 2019-07-04 14:13 UTC
Everytime one right-clicks on the icon in the taskbar, to for example stop the synchronization. After the menu appears it takes a short while and an additional menu entry appears, thus changing the position of all entries and it often happens that the position of the mouse selects a different menu entry from the originally intended one.

### Expected behaviour
The menu should be extended with all entries, whenever it is opened and should stay this way.

### Actual behaviour
The menu is not extended to all entries right away, but it rather takes some seconds to add the "Apps" entry and then all lower menu entries are pushed down and the mouse position has to be adjusted.

### Steps to reproduce
1. Right-Click on the nextcloud icon
2. Hover mouse over the menu
3. Click on any item in the menu and it most probably will be the wrong one.

### Client configuration
Client version:
2.5.2

Operating system:
Windows 
OS language:
German

**Comment by florianwgnr** [comment] 2019-07-16 06:57
Same result, quite annoyning when i want to close the client and right before clicking the "Apps" overview loads, the menu expands and i click on "stop synchronisation". 

Would be better if "Apps" stays in the menu and only the content of "Apps" sub-menu loads after a right click.

**Comment by bgoodmansf** [comment] 2019-10-06 20:43
In addition, on Windows 7 (not sure about others) this causes the "Quit Nextcloud" menu item to be pushed completely offscreen so it is inaccessible. See attached screenshot.
![Nextcloud Menu Fail](https://user-images.githubusercontent.com/4819742/66275612-33bb3000-e83f-11e9-98f4-115ef183f63d.jpg)

**Comment by bgoodmansf** [comment] 2019-10-11 16:55
Confirmed that the same behavior (right-click menu goes offscreen) occurs in Windows 10, too.

**Comment by hannes101** [comment] 2019-11-19 19:21
Is it fixed in the latest version 2.6.1? I can't replicate it with this version in Xfce on linux.

**Comment by bgoodmansf** [comment] 2019-11-19 19:53
> Is it fixed in the latest version 2.6.1? I can't replicate it with this version in Xfce on linux.

It seems to be fixed in Windows 7, Windows 10 and Ubuntu MATE.

**Comment by hannes101** [comment] 2019-11-28 06:01
This is a duplicate of https://github.com/nextcloud/desktop/issues/833 and was fixed with https://github.com/nextcloud/desktop/pull/1477

**Closed** 2019-11-28 06:00 UTC
