### ISSUE TITLE
Extend the "external storage" restriction wordings to "group folders" (which are technically considered in the same way as external storage)

### ISSUE THREAD

**Issue by Jerome-Herbinet** [nextcloud/desktop#5533] opened 2023-03-17 12:50 UTC
### Problem description

**Group folders**, which are increasingly used in Nextcloud, **are technically considered the same as external storage by the desktop sync client**. 

**The problem** is that they are never mentioned (only external storages are mentioned in the wording).

**I therefore suggest the following changes to the labels used in the desktop synchronization client :**

### Solution

_I found these 5 wordings in Transifex._

![2023-03-17_13-47](https://user-images.githubusercontent.com/33763786/225908779-d3196a5e-8a93-4172-8304-49abd2bc6e06.png)

#### Before (currently) : 
- Ask for confirmation before synchronizing external storages
- Ask before syncing external storages
- A folder from an external storage has been added.
- There are folders that were not synchronized because they are external storages: 
- There are folders that were not synchronized because they are too big or external storages: 

#### After : 
- Ask for confirmation before synchronizing external storages **or group folders**
- Ask before syncing external storages **or group folders**
- A folder from an external storage **or a group folder** has been added.
- There are folders that were not synchronized because they are external storages **or group folders**: 
- There are folders that were not synchronized because they are too big or external storages **or group folders**:

**Comment by Jerome-Herbinet** [comment] 2024-05-24 12:28
@claucambra what do you think about this suggestion I made last year ?

**Comment by joshtrichards** [comment] 2024-08-16 05:31
Duplicate of #1967

**Closed by joshtrichards** 2024-08-16 05:31 UTC
Labels: enhancement, feature: :minidisc: external storage, feature: :tongue: language l10n and translations
