### ISSUE TITLE
Segfault on start in 2.3.3-4.2 on Linux 4.17.14-1

### ISSUE THREAD

**Issue by Ozymandias42** [nextcloud/desktop#575] opened 2018-08-22 19:40 UTC
## Details
`nextcloud` segfaults in openSUSE Tumbleweed in Version 2.3.3-4.2 on Kernel 4.17.14-1

The AppImage works.

## Steps to reproduce 
1. Install `nextcloud` via `sudo zypper in nextcloud-client`
2. Start `nextcloud` directly after installation from either terminal or via a launcher

**Comment by DominiqueFuchs** [comment] 2019-09-25 16:55
Closing this as a duplicate of #241  (if it's not, lets first find out there by digging through the information)

**Closed by DominiqueFuchs** 2019-09-25 16:55 UTC
