### ISSUE TITLE
Nextcloud 3.0.1 Windows client doesn't show/recognize all sync folders

### ISSUE THREAD

**Issue by Gizmokid2005** [nextcloud/desktop#2366] opened 2020-09-04 19:24 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour
Upon upgrading to and using the 3.0.1 windows desktop client, all of the previous folder sync connections should exist and be used with the client.

### Actual behaviour
The client is only showing one folder (extra) per launch of the client. That is on the first launch after upgrading, only one folder from each of my two accounts showed. Upon closing and relaunching, each account showed one more folder. Upon closing and relaunching another folder connection was added (I confirmed this twice). I have a lot of sync connections that makes it nigh impossible to go through a "restart loop" to get all of my folder sync connections back.

### Steps to reproduce
1. Have multiple sync connections with a <3.x client.
2. Upgrade to 3.x client.
3. Note that folder sync connections aren't all there, only one extra per launch since upgrade (starting at one folder).

### Client configuration
Client version:
3.0.1 Windows

Operating system:
Windows 10 Pro 2004

OS language:
English

Installation path of client:
C:\Program Files\Nextcloud

**Comment by Id3aFly** [comment] 2020-09-04 22:18
I guess this is a duplicate of #2279, #2326 and #2301

**Comment by Gizmokid2005** [comment] 2020-09-04 23:27
> 
> 
> I guess this is a duplicate of #2279, #2326 and #2301

Correct. I didn't look back a few weeks for this issue, I suspected it would've been only a new one, sorry about that. This does sound like the same as #2279 for sure.

**Comment by Id3aFly** [comment] 2020-09-05 10:45
You should close this issue such that the developers can keep the issue regarding discussion in one thread. Thanks

**Closed** 2020-09-05 16:39 UTC
