### ISSUE TITLE
Linux latest version doesn't have status bar icon

### ISSUE THREAD

**Issue by xen0m0rph2020** [nextcloud/desktop#2811] opened 2021-01-11 09:41 UTC
Hi all
On latest app image version for Linux next cloud client no longer gets added to status bar. Also bug with the new UI being tiny on 4k is still present.
I'm running Ubuntu 20/pop OS 20.10.
Gnome version 3.381

**Comment by er-vin** [comment] 2021-01-11 10:17
Duplicate of other issues already reported, thus closing.

**Closed by er-vin** 2021-01-11 10:17 UTC
