### ISSUE TITLE
Add option to not sync hidden files when creating a new account

### ISSUE THREAD

**Issue by Verhoeckx** [nextcloud/desktop#3783] opened 2021-09-10 21:14 UTC
After adding the expression `.*` to list of files to ignore (1), the number of files to synchronize went from 120.000 to 33.000 , and the synchronization time from days to a few hours!!

By default the desktop application syncs all hidden files: files the user may now want (or are not needed) to synchronize. 
The dialog `Add account` doesn't offer a way to exclude hidden files and therefore a lot of unnecessary files are synchronized and  a lot of time and energy is wasted.

I think the solution is to not synchronize hidden files by default and to add an option to add hidden files. This way the most important files are always synchronized and if the user does want to synchronize hidden files, he/she can do that.

Th advantage of not synchronizing hidden files is that it will speed up the synchronization time tremendously. 
<br>

1\) I had to add the expression `.*` manually because of [this bug](https://github.com/nextcloud/desktop/issues/3782).

**Comment by joshtrichards** [comment] 2023-11-21 22:35
Historical context: #405

**Comment by joshtrichards** [comment] 2023-11-22 14:45
Duplicate of #1346

**Closed by joshtrichards** 2023-11-22 14:45 UTC
Labels: enhancement
