### ISSUE TITLE
Main dialog window does not open - Ubuntu

### ISSUE THREAD

**Issue by RomeroVerde** [nextcloud/desktop#4069] opened 2021-12-11 20:53 UTC
### Expected behaviour
Main dialog window should open when clicking either on:
- Open main dialog or
- See conflicts in setting window

### Actual behaviour
Main dialog does not open.

### Steps to reproduce
1.a Click in Next cloud logo  > Open main dialog
1.b (from settings window) Click on see conflicts.

### Client configuration
Client version: Desktop 3.4.0 (Ubuntu)

Operating system: Ubuntu 20.04

OS language: English

**Comment by ajoana** [comment] 2021-12-12 04:08
Same here with current Mint Mate 20.3 in German.

**Comment by RomeroVerde** [comment] 2021-12-12 07:44
It appears to be the same as: 
https://github.com/nextcloud/desktop/issues/4017

**Comment by RomeroVerde** [comment] 2021-12-12 07:49
Sorry, I open this issue again, as the other is closed and I do not know if it will have any attention.

**Comment by Apromixately** [comment] 2021-12-13 08:06
I have the same issue with the settings window. Should I create a separate issue?

**Comment by schworak** [comment] 2021-12-17 14:21
Appears to be the same for Mint. I have nextcloud-desktop 3.4.0 installed and the "open main dialog" does nothing.

**Comment by k3tan172** [comment] 2021-12-17 21:20
> Appears to be the same for Mint. I have nextcloud-desktop 3.4.0 installed and the "open main dialog" does nothing.

Same for Pop!_OS. "Open main dialog" does nothing.

**Comment by mrmatteastwood** [comment] 2021-12-19 18:06
Confirmed on Linux Mint 20.2 Cinnamon. Nextcloud client 3.4.0 from nextcloud-devs/client PPA.

**Comment by MegaV0lt** [comment] 2021-12-27 08:01
Bug still exists with 3.4.1 on Linux Mint

**Comment by k3tan172** [comment] 2021-12-27 08:07
Can confirm bug still exists with 3.4.1 on Pop!_OS. Interestingly, if you try the AppImage for 3.4.1, it works as expected.

**Comment by bugariu** [comment] 2021-12-27 10:11
Bug still exists on Kubuntu 20.04

**Comment by MauroFoti** [comment] 2021-12-27 12:25
Same in linux mint 20.1 with client 3.4.1. Weirdly enough, the bug does not replicate with the appimage (3.4.1) downloaded from https://nextcloud.com/install/#install-clients

**Comment by bugariu** [comment] 2021-12-27 15:12
Wondering if it has something to do with commit 12c6d6e3bd  (esp. line 63:     
~~~cpp
_trayEngine->setNetworkAccessManagerFactory(&_accessManagerFactory);
~~~

Had myself problems using this on Kubuntu 20.04 with stock Qt 5.12 since according to https://github.com/KDE/kdeclarative/blob/master/src/kdeclarative/kdeclarative.cpp#L88 the own NetworkAccessManagerFactory gets deleted. When I was using Qt 5.14 from `/opt` there was not such a problem.

This may explain why the appimage works (own Qt libraries?)

I would test it myself, but I can't compile on Ubuntu 20.04

**Comment by resoli** [comment] 2021-12-27 15:23
> Same in linux mint 20.1 with client 3.4.1. Weirdly enough, the bug does not replicate with the appimage (3.4.1) downloaded from https://nextcloud.com/install/#install-clients

Same here (Ubuntu 20.04)

**Comment by allexzander** [comment] 2021-12-29 15:25
We will release a fix in 3.4.2. Ubuntu 20.04 https://pkgs.org/download/libqt5quick5 comes with Qt Quick 5.12 while we need 5.15 which comes in the most recent Ubuntu. For now, the only way is to either use 3.3.6, or use 3.4.1 via AppImage/flatpak/snap.

**Comment by k3tan172** [comment] 2022-02-10 05:24
Upgraded to 3.4.2 via apt package manager and still the same issue. "Open main dialog" window does not appear.

**Comment by mad73923** [comment] 2022-02-10 06:06
Same here :(

**Comment by mrmatteastwood** [comment] 2022-02-10 06:57
FWIW, I discovered that if you leave everything from the repos installed, but then download the AppImage and run that, everything works perfectly. Both the dropdown as well as file manager integration (Nemo, in my case) continue to work.

This is on Linux Mint 20.2.

The AppImage puts its config files into the same location as the repo version, so what I did was, I un-checked the "launch on system startup" option in NC's settings and manually put the AppImage into my startup programs.

**Comment by despens** [comment] 2022-02-10 09:24
If the client is dependent on a library that is not available in a LTS version of a distro as popular as Ubuntu, perhaps you could distribute it via Flatpak or snap instead?

**Comment by MegaV0lt** [comment] 2022-02-10 09:25
Menu and language still not working with 3.4.2 on Mint Cinnamon 20.3

**Comment by jurgenhaas** [comment] 2022-02-10 09:29
Confirmed, just updated to the packages version 3.4.2 on Ubuntu, the client works but the popup still doesn't show up.

**Comment by mrmatteastwood** [comment] 2022-02-10 09:36
> If the client is dependent on a library that is not available in a LTS version of a distro as popular as Ubuntu, perhaps you could distribute it via Flatpak or snap instead?

The client is, in fact, available as a snap or flatpak. To my understanding, though, you can't have file manager integration if you run either of these.

**Comment by despens** [comment] 2022-02-10 15:17
@mrmatteastwood For the AppImage version the file manager integration works just fine.

The [snap release of the desktop client](https://snapcraft.io/nextcloud-desktop-client) is an "unofficial" build and as far as I understand from the description depends on Ubuntu Core instead of providing its own libraries (so the wrong QT version would still be used). It also states it doesn't support file manager integration. So for now using the AppImage is probably the best compromise.

**Comment by jeensg** [comment] 2022-02-10 22:22
> Does anybody see a way on updating this package in Ubuntu LTS? (maybe through ppa or something ... even stable debian does have newer version :-D)

Actually I don't think so: https://www.ubuntuupdates.org/pm/libqt5quick5 -> only with new Ubuntu-LTS in April (and for updating safely probably in August). [Here](https://unix.stackexchange.com/questions/481063/ubuntu-18-04-1-lts-x64-how-to-update-qt-5-10-from-qt-5-9-5) are some advices on how to maybe update Qt, but it seems actually not advisable if we don't know exactly what we are doing :-D

**Comment by ajoana** [comment] 2022-02-11 23:06
I switched to the appimage which works fine and will wait until it's fixed and reported here. Thx for all your work :)

**Comment by marbx** [comment] 2022-02-13 18:21
I needed to access the main dialog to add another site.
Exited Version 3.4.2 (Ubuntu)
Downloaded and started AppImage, accessed the main dialog and exited the Appimage with Ctrl-C
Reboot

**Comment by MegaV0lt** [comment] 2022-02-14 08:13
appimage is not localiced in mint cinnamon

**Comment by jeensg** [comment] 2022-02-14 11:16
> appimage is not localiced in mint cinnamon

This is kind of no question :-D what do you mean with localized?
The AppImage ist located [here for download](https://github.com/nextcloud/desktop/releases/download/v3.4.2/Nextcloud-3.4.2-x86_64.AppImage).

**Comment by MegaV0lt** [comment] 2022-02-14 12:50
Language is english but os language is german#

**Comment by despens** [comment] 2022-02-14 13:39
@MegaV0lt, @jeensg, I think this is not the right issue to discuss localization issues with the AppImage. You should open a new issue for that.

**Comment by NielBuys** [comment] 2022-02-15 14:46
Can't the ppa for Ubuntu 20.04 be changed to the 3.3.6 version. I was not successful in downgrading my apt package to the 3.3.6 version.
Not sure if there is another way to downgrade via the ppa "https://launchpad.net/~nextcloud-devs/+archive/ubuntu/client".

**Comment by MegaV0lt** [comment] 2022-02-16 16:13
there is no 3.3.6 for focal in the ppa

**Comment by ledufakademy** [comment] 2022-02-23 09:46
Why the nextcloud team do not fix this AWFULL  bug ?
i cannot  add another NC account.

**Comment by mrmatteastwood** [comment] 2022-02-23 10:11
> Why the nextcloud team do not fix this AWFULL bug ? i cannot add another NC account.

@ledufakademy I had the same problem, and the AppImage provides a good workaround. Check out my post above:
https://github.com/nextcloud/desktop/issues/4069#issuecomment-1034560484

Just need to download the AppImage here: https://github.com/nextcloud/desktop/releases/download/v3.4.2/Nextcloud-3.4.2-x86_64.AppImage

Then mark as executable in the file properties, run, add your account. If you like, you can also replace the repo version with it: just close the AppImage, run the regular Nextcloud client that you already have installed, go to Settings and disable "Launch on System Startup". Then, open "Startup Applications" (in Mint, might be called differently in other distros) and add the AppImage there manually.

**Comment by Bug-Ninja** [comment] 2022-02-28 14:34
> > Why the nextcloud team do not fix this AWFULL bug ? i cannot add another NC account.
> 
> @ledufakademy I had the same problem, and the AppImage provides a good workaround. Check out my post above: [#4069 (comment)](https://github.com/nextcloud/desktop/issues/4069#issuecomment-1034560484)
> 
> Just need to download the AppImage here: https://github.com/nextcloud/desktop/releases/download/v3.4.2/Nextcloud-3.4.2-x86_64.AppImage
> 
> Then mark as executable in the file properties, run, add your account. If you like, you can also replace the repo version with it: just close the AppImage, run the regular Nextcloud client that you already have installed, go to Settings and disable "Launch on System Startup". Then, open "Startup Applications" (in Mint, might be called differently in other distros) and add the AppImage there manually.

I confirm that this workaround is working (Linux Mint 20.3 -XFCE). However, it simply should be working when you install it (from repo/PPA) or fixed soon. I also notice that the font in the main dialog is tiny and the settings dialog themed properly.

**Comment by mvv588** [comment] 2022-02-28 19:02
Same issue with v3.4.3, we deploy software using apt to our (100+) users on Ubuntu 18/20.04, the snap version is not usable, using the Appimage is not feasible. Please fix the version in the ppa, it is going to take several years before our users migrate to Ubuntu 22.04 after it comes out, thank you.

**Comment by mgallien** [comment] 2022-03-02 11:37
sorry to hear that has not been solved
can you all confirm that you get the package from a PPA archive and confirm the version of the package you use ?
we have provided patches to allow packagers to downgrade the requirement on the Qt version
packages from us only are provided as AppImage that should be fully working and are built against the required Qt version (5.15)
the proper Qt version is unavailable on Ubuntu 20.04 and hence require extra patches to be built
we have provided help there

**Comment by jurgenhaas** [comment] 2022-03-02 12:44
Yes, I can confirm that I've installed 3.4.3 from PPA on Ubuntu 20.04 and the main dialog still doesn't show up.

**Comment by jurgenhaas** [comment] 2022-03-02 13:38
@mgallien there is quite some sensitive data in that log. What exactly are you looking for?

**Comment by ivaradi** [comment] 2022-03-02 15:36
I think the bug has something to do with the fact the Qt 5.12 is used on Ubuntu 20.04. So perhaps there is some code related to the main window that compiles on Qt 5.12, but does not work as expected. I am not really familiar with Qt, but if you can give me some hints as to where to look in the code, I might be able to experiment.

**Comment by antoineguichard** [comment] 2022-03-03 14:07
As far as I understand, the "Settings" window continues to open fine for everyone using Right-click >> Settings.

So would that not be simple and make sense to just replicate the functionality of the main dialog within the "Settings" window?  

For example : 
- In the top banner of the Settings window, have a link to adding a new account, to the right of the list of current accounts (not being able to add new NC accounts IS a big stumbling block)
- add a tab for Conflicts
- etc.

The client would remain usable for everyone, whether or not they have the current QT bug and any possible future bug to the same effect. 

Could we have that?

**Comment by mrmatteastwood** [comment] 2022-03-03 14:41
> As far as I understand, the "Settings" window continues to open fine for everyone using Right-click >> Settings.
> 
> So would that not be simple and make sense to just replicate the functionality of the main dialog within the "Settings" window?
> 
> For example :
> 
> * In the top banner of the Settings window, have a link to adding a new account, to the right of the list of current accounts (not being able to add new NC accounts IS a big stumbling block)
> * add a tab for Conflicts
> * etc.
> 
> The client would remain usable for everyone, whether or not they have the current QT bug and any possible future bug to the same effect.
> 
> Could we have that?

**YES PLEASE.** I 1000% agree!

**Comment by ivaradi** [comment] 2022-03-06 15:47
I have updated the patch used for Qt 5.12 so that the main dialog can be opened on Focal as well. Version 3.4.3 has been recompiled with the fixes. Please, let me know your results.

**Comment by mvv588** [comment] 2022-03-06 17:18
> I have updated the patch used for Qt 5.12 so that the main dialog can be opened on Focal as well. Version 3.4.3 in the PPA has been recompiled with the fixes. Please, let me know your results.

Works on Mint 20.3, thanks, big relief to see this working again.

**Comment by antoineguichard** [comment] 2022-03-06 17:52
> I have updated the patch used for Qt 5.12 so that the main dialog can be opened on Focal as well. Version 3.4.3 in the PPA has been recompiled with the fixes. Please, let me know your results.
Works for me on Ubuntu 20.04, Thanks! :+1:

**Comment by MegaV0lt** [comment] 2022-03-07 08:37
Mint 20.3 with ncclient 3.4.3 is working here too.

**Comment by Bug-Ninja** [comment] 2022-03-07 11:14
> Mint 20.3 with ncclient 3.4.3 is working here too.

Yes, same here! Glad this has been solved, thanks!

**Comment by mad73923** [comment] 2022-03-07 16:26
Works for me now again! Thanks for the fix!

**Comment by resoli** [comment] 2022-03-07 16:52
Works for me under Ubuntu Focal.

**Comment by jeensg** [comment] 2022-03-07 21:51
> I have updated the patch used for Qt 5.12 so that the main dialog can be opened on Focal as well. Version 3.4.3 in the PPA has been recompiled with the fixes. Please, let me know your results.

Works here on xUbuntu 20.04 also, thank you very very much!!!

**Comment by masakkre** [comment] 2022-03-09 09:11
> I have updated the patch used for Qt 5.12 so that the main dialog can be opened on Focal as well. Version 3.4.3 in the PPA has been recompiled with the fixes. Please, let me know your results.

In Ubuntu Mate 20.04 is not working the main dialog. Perhaps I must upgrade QT with repositorys or something like that?
Thank you so much for your great work

**Comment by claucambra** [comment] 2022-04-19 10:43
Since this bug has now ben fixed, closing -- thanks all for your comments

**Closed by claucambra** 2022-04-19 10:43 UTC
Labels: bug, approved

**Comment by avatar1024** [comment] 2022-07-29 09:29
I have this problem again when using the repo version of the nextcloud client. I wonder if this has to do with the version of Qt on my system:

Nextcloud Desktop: 3.5.2 from stable ppa (but it's broken at least since 3.5.1, possibly before)
Operating System: KDE neon 5.25
KDE Plasma Version: 5.25.3
KDE Frameworks Version: 5.96.0
**Qt Version: 5.15.5**
Kernel Version: 5.15.0-41-generic (64-bit)
Graphics Platform: X11
Processors: 8 × Intel® Core™ i5-8350U CPU @ 1.70GHz
Memory: 15.4 GiB of RAM
Graphics Processor: Mesa Intel® UHD Graphics 620

**Comment by avatar1024** [comment] 2022-07-29 10:21
Sorry the answer is actually provided here #4476
