### ISSUE TITLE
Nextcloud + Always-on VPN = trouble (network access is disabled)

### ISSUE THREAD

**Issue by pilsnerbeer** [nextcloud/desktop#2628] opened 2020-11-12 12:12 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour
NC should connect on PC wake (from sleep / hibernation) and be ready to sync

### Actual behaviour
Nextcloud windows client 3.0.3 cant connect to the server each time my PC wakes from sleep. The error is "network access not allowed" (translated). Client restart required every time

### Steps to reproduce
(always on vpn needed that will block network access until the vpn is connected).
1. PC sleep or hibernate
2. Wake up
3. observe NC status. try creating new folder / file . Wont sync.

NOTE: 
This issue has been observed before 3.0.3 (i might have reported on this). But before, it would only throw an error and if you tried syncing something, it would sync a file/folder without problems. Now, the client has become more stubborn and it will not sync anything until it is restarted.

### Client configuration
Client version: 3 0 3 
Operating system: windows 10

**Comment by pilsnerbeer** [comment] 2020-11-12 12:14
https://github.com/nextcloud/desktop/issues/1375 
my old report from over a year ago proves this has been a problem before

**Comment by sircharlo** [comment] 2020-11-13 13:46
Same issue here; screenshot of error attached.
![image](https://user-images.githubusercontent.com/1275666/99078611-a80cea80-258c-11eb-8026-9eda0ebb2480.png)

**Comment by kesselb** [comment] 2020-11-13 14:46
> #1375
> my old report from over a year ago proves this has been a problem before

So this report is technically a duplicate of #1375?

**Comment by pilsnerbeer** [comment] 2020-11-14 14:47
@kesselb No, it's not. The issue of 1375 reports on an issue that seems to be purely cosmetical and not functional. This issue is different, as it forces the user to restart the client every single time their PC is powered up.

**Comment by er-vin** [comment] 2020-11-16 11:23
That's odd, there's nothing I see in the 3.0.2 -> 3.0.3 diff which would explain a different behavior there.

**Comment by er-vin** [comment] 2020-11-16 11:24
Oh also, debug logs from the client would be of use (see --logdebug and --logfile on the command line)

**Comment by fefrei** [comment] 2020-11-16 12:07
Is there a chance this change is related to upgrading Windows 10 to version 20H2?
I didn't take note on when I did that, upgraded Nextcloud, and when this issue started appearing, but the timelines roughly match.

**Comment by pilsnerbeer** [comment] 2020-11-16 12:15
@fefrei That's an interesting observation as I have also upgraded to 20H2. 
Just few minutes ago I decided to reinstall NC client but apparently it can't be uninstalled. Even if the wizard said it was removed successfully, it's still on my computer. Somehow it upgraded itself to 3.0.3 (I rolled back to 3.0.2 2 days ago), language changed to english (which is not my system language) and the main dialog (activity log) can't be opened. Looks like there's more trouble on the way..

**Comment by er-vin** [comment] 2020-11-16 12:33
> @fefrei That's an interesting observation as I have also upgraded to 20H2.
> Just few minutes ago I decided to reinstall NC client but apparently it can't be uninstalled. Even if the wizard said it was removed successfully, it's still on my computer. Somehow it upgraded itself to 3.0.3 (I rolled back to 3.0.2 2 days ago), language changed to english (which is not my system language) and the main dialog (activity log) can't be opened. Looks like there's more trouble on the way..

Yes, we got a report of the uninstaller having issues in 3.0.2 and 3.0.3. Workaround would be to stop nextcloud manually and eventually explorer as well prior to uninstalling. A fix is in the work.

**Comment by zoomix** [comment] 2020-11-27 06:07
For what it's worth, the same issue exists on MacOS. 3.0.3. Has been the same since 2.x IIRC

Seems like a timing issue. I've sometimes seen it popup a window saying that the stored certificate doesn't match the server certificate. The certificate that pops up is the certificate of my unify router, so it appears to try and connect to the server before the dhcp config has been fully re-applied from the disconnecting/connecting VPN. 

.. and when the connection fails, it doesn't attempt to retry. It just.. sulks. The finder integration stops working to - the "sync status" icons next to filenames disappear.

**Comment by zoomix** [comment] 2020-11-27 09:24
Ok, so I just realized I'm not getting the exact same error. I may be posting this in the issue. Sorry. Nevertheless:

This is the sequence of events.
1. disconnecte one vpn, connect to another too quickly.
2. Certificate window pops up. 
![Untrusted_Certificate_and_Tunnelblick](https://user-images.githubusercontent.com/813082/100432821-6c991280-309a-11eb-9a7f-9ea9bc2a15e8.png)
3. I click cancel, since it's the reasonable thing to do
4. The icon in my menubar changes from the reassuting "checkmark" to this
![Item-0_and_Item-0_and_Item-0](https://user-images.githubusercontent.com/813082/100432861-7de21f00-309a-11eb-9942-18f1d55451d8.png)
5. Clicking on settings I can still see:
![Nextcloud_and_Slack___Threads___The_Techno_Creatives](https://user-images.githubusercontent.com/813082/100432954-9ce0b100-309a-11eb-9699-095fee243733.png)
6. Checkmark never comes back, the integration with finder is offline and now files are synced until i restart nextcloud

**Comment by pilsnerbeer** [comment] 2020-12-08 10:03
OK so I decided to disable VPN for a couple of days to see if I can get a functional app again. As it turns out, the issue still very much exists without the use of VPN. Once again, manual client restart is required to get the app going. Anybody else?

**Comment by sircharlo** [comment] 2020-12-08 12:30
Yep, same

**Comment by johkoenig** [comment] 2020-12-26 20:29
Hi everybody,
the issue with "network access not allowed" came up recently on my computer, after upgrading to nextcloud desktop v3.1.1 and Windows 10 20H2. After playing with the settings, I switched the proxy settings from "system proxy" to "no proxy", which seems to solve the issue. This is weird, since I don't use a system proxy. I have a standard home user setup with my computer, a router and that's it. Here are my windows proxy settings:
![grafik](https://user-images.githubusercontent.com/42836313/103158728-4bbefc80-47c1-11eb-8771-3395097dcace.png)
Maybe this helps to nail down the problem. Almost all users of my nextcloud are facing it and it is pretty annoying.
Regards, jk

**Comment by mduller** [comment] 2020-12-31 00:32
I can confirm what @johkoenig said. The issue only appeared on my two Windows 10 machines after upgrading to 20H2. Waking up from sleep the Nextcloud client would show "Network access is disabled" and only stopping and starting the Nextcloud client would get it to work again (tried "Force Sync Now" - didn't help).
Setting proxy to "No proxy" in Nextcloud immediately solved the problem on both machines - sync started right away and was successful.
I also agree with @johkoenig's comment that this is pretty annoying as all users of Nextcloud on Win10 20H2 with default settings are facing this issue.

**Comment by pilsnerbeer** [comment] 2021-01-04 10:15
I've had 'No proxy' set all this time and it still doesn't work. Switching between system proxy/no proxy also does not do anything for me.

**Comment by ronenb75** [comment] 2021-01-05 20:07
Same here.
3.1.1 on Windows 10 and everytime I'm coming out of long sleep - it'll come up with "Network access is disabled".
Happened basically since I moved to 3. I thought it'll be fixed, but it still happens, on 3 different machines.

Shutting down and restarting the client solves the issue (so no network issue).
However, changing from "no proxy" (my default setting) to "system proxy" and back to "no proxy" solves it as well.
I have no system proxy.

**Comment by arjan-s** [comment] 2021-01-14 14:37
Same issue here with version 3.1.1 on several Windows 10 laptops.

**Comment by er-vin** [comment] 2021-01-14 15:54
I'm starting to wonder if that's a duplicate of #324, #482 and #2678 that we fixed recently (to be shipped soon).

**Comment by briareosiso** [comment] 2021-01-20 16:58
Same thing in 3.1.0...

**Comment by mikalauskas** [comment] 2021-01-24 12:47
Same issue, 3.1.1
1. PC sleep or hibernate
2. Wake up
3.
![image](https://user-images.githubusercontent.com/2268118/105630594-eddb0e80-5e6b-11eb-8b00-28d3a63824bd.png)

my os:
![image](https://user-images.githubusercontent.com/2268118/105630648-2b3f9c00-5e6c-11eb-938a-f8cf2fdd483f.png)

**Comment by johkoenig** [comment] 2021-01-26 11:21
Hello everybody,
the problems is still there, the workaround I proposed earlier (proxy settings) didn't help out for long time. However, I discovered another workaround: I can reproduce the error by setting the PC to energy saving mode and waking up again. Now, if I quit the nextcloud service in the tray and start it again, everything works fine again.
My setup is NC 20.0.6, Windows 10 x64 20H2, NC client 3.1.1.

Now, my new theory is: Directly after waking up, the nextcloud client is trying to access the list of folders. That happens even before Windows is able to reconnect the network. For some reason, the client thinks he is locked out (instead of no connection) and keeps this state until it will be shut down by the user. Once the client is shut down and started again, the network connection is available and everything works fine again.

My proposal is:

1. The client should check access to the folder list regularly and not stay in the state of "operation not permitted" or "network access is disabled" only because it happened once
2. The client should wait some time (e.g. 15 seconds) after coming out of energy saving mode before it tries to connect the cloud

**Comment by johkoenig** [comment] 2021-01-29 17:47
Hey guys,
I just installed the new version 3.1.2 on two computers and I can't reproduce the problem anymore. I even could set the proxy settings back to "System proxy" (=no proxy in my case). I put the PC to sleep several times and every time it came back, everything worked fine.
@mikalauskas @briareosiso @mduller @pilsnerbeer maybe you wanna check with the new version of the client.

**Comment by er-vin** [comment] 2021-02-01 08:30
That would confirm this was a duplicate of #324, #482 and #2678 as I suspected. This got fixed for 3.1.2. I'll close this one as well then.

**Closed by er-vin** 2021-02-01 08:30 UTC
Labels: bug, feature: :arrows_counterclockwise: sync engine

**Comment by mduller** [comment] 2021-02-01 14:25
@johkoenig, thanks for the heads-up on 3.1.2. I installed it a day ago and can confirm it has resolved the issue. The 3.1.2 client is able to connect successfully after the computer wakes from sleep. Thanks everyone for addressing this swiftly!

**Comment by zoomix** [comment] 2021-02-03 14:04
For what it's worth, the mac client still exhibits the same behavior. 

Not saying to re-open this (as it is strictly speaking reported for windows),  just in case this gets linked in some other issue.
