### ISSUE TITLE
Windows Client 2.5 with new account fails to setup end-to-end-encryption with CSR

### ISSUE THREAD

**Issue by sfxn** [nextcloud/desktop#977] opened 2018-12-26 16:10 UTC
### Expected behaviour
After successful registration the client should start with folder syncronization.

### Actual behaviour
The client registers successful but shows as status:
"Keine Verbindung zu Nextcloud auf https://***.your-next.cloud"
translated from german: "No Connection to Nextcloud at https://***.your-next.cloud"

### Steps to reproduce
1. Install Client on Windows
2. Sucessfully Login with your existing Account
3. Check Sync Status / Logfiles

### Client configuration
Client version:
2.5.1 and 2.5.0
Operating system:
Windows 10 Home 64bit
OS language:
German

Installation path of client:
C:\Program Files (x86)\Nextcloud

### Server configuration

Operating system:
Linux
Web server:
nginx
Database:
mysql 10.3.11
PHP version:
7.2.12
Nextcloud version:
14.0.4.2
Storage backend (external storage):

### Logs

** this might be the relevant lines **

    [OCC::ClientSideEncryption::getPublicKeyFromServer::::operator() 	No public key on the server
    [OCC::ClientSideEncryption::generateKeyPair 	No public key, generating a pair.
    [OCC::ClientSideEncryption::generateKeyPair 	Key correctly generated
    [OCC::ClientSideEncryption::generateKeyPair 	Storing keys locally
    [OCC::ClientSideEncryption::generateKeyPair 	Keys generated correctly, sending to server.
    [OCC::ClientSideEncryption::generateCSR 	Getting the following array for the account Id "MYUSER"
    [OCC::ClientSideEncryption::generateCSR 	Returning the certificate
    [OCC::ClientSideEncryption::generateCSR 	"-----BEGIN CERTIFICATE REQUEST-----\nMIICqjCCAZICAQEwZTELMAkGA1UEBhMCREUxGzAZBgNVBAgMEkJhZGVuLVd1ZXJ0\ndGVtYmVyZzESMBAGA1UEBwwJU3R1dHRnYXJ0MRIwEAYDVQQKDAlOZXh0Y2xvdWQx\nXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\nAQEA5HlCZ20o+nLFQi1Nv+YMfoTiWGqoojZI41XuKCbZm4kWLerdOM8CsDS52dvQ\nQL6UsgViPvu8P5/3E+1n6X8kQJFyvW4ehlAMrwwlKY+VkTSB8ss8wmnePNYHrfDE\nElGmuuBp6x/dduhrdeBCMM/9XviGenzdqRM5Y7ymQGe36RfIyUXBdB0/6QwygVvb\nLdj3xnuL+MnL+gblpjuqFARvi/2z0VYxq+w+F38ic1CVezVwUB1Xtz1neHfBC5YE\nBZ95B+bh9tfxn3SjtAHT8Ov1EzB/ZsvlIa+RPDwwugWCIVt6jXT9eCtYr7+TOwIv\nyQluy5cc3tmztZmnbxgcEUWKOQIDAQABoAAwDQYJKoZIhvcNAQEFBQADggEBAC0e\nYRGZi7H6dZ7XVLn6j4+4GQ+MK6/O3PZlvr6dxWAq5rePaX8v1ISSFcBf5qVw2ZD8\njzYNQLyrBFNAhLJZHQXh2lpcEI0fr5RncmRDBKdpDBhNdCTfGQdP1jl2nsn0PI7z\n0kS1XXp6EpVZPO2fY1vedt+wlZyC8Pa6gcqXQg49Wx9mtm91d/5h2lY56Vv2cYuu\nbgC4nA2ljredGU3I5UsLEkqQMxH9c/9BiMsNPkXd5xLJsncpeYgD+sH+jpkvcrX6\nEt+ZecyK1pPIaq55qUay//l6HmrlI9x3MVoZZthNYn2oagAORCpC1pJhiACbd0Ib\n4UUaEPrJQis65cg71sI=\n-----END CERTIFICATE REQUEST-----\n"
    [OCC::SignPublicKeyApiJob::start 	Sending the CSR "csr=-----BEGIN%20CERTIFICATE%20REQUEST-----%0AMIICqjCCAZICAQEwZTELMAkGA1UEBhMCREUxGzAZBgNVBAgMEkJhZGVuLVd1ZXJ0%0AdGVtYmVyZzESMBAGA1UEBwwJU3R1dHRnYXJ0MRIwEAYDVQQKDAlOZXh0Y2xvdWQx%0AXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX%0AAQEA5HlCZ20o%2BnLFQi1Nv%2BYMfoTiWGqoojZI41XuKCbZm4kWLerdOM8CsDS52dvQ%0AQL6UsgViPvu8P5%2F3E%2B1n6X8kQJFyvW4ehlAMrwwlKY%2BVkTSB8ss8wmnePNYHrfDE%0AElGmuuBp6x%2FdduhrdeBCMM%2F9XviGenzdqRM5Y7ymQGe36RfIyUXBdB0%2F6QwygVvb%0ALdj3xnuL%2BMnL%2BgblpjuqFARvi%2F2z0VYxq%2Bw%2BF38ic1CVezVwUB1Xtz1neHfBC5YE%0ABZ95B%2Bbh9tfxn3SjtAHT8Ov1EzB%2FZsvlIa%2BRPDwwugWCIVt6jXT9eCtYr7%2BTOwIv%0AyQluy5cc3tmztZmnbxgcEUWKOQIDAQABoAAwDQYJKoZIhvcNAQEFBQADggEBAC0e%0AYRGZi7H6dZ7XVLn6j4%2B4GQ%2BMK6%2FO3PZlvr6dxWAq5rePaX8v1ISSFcBf5qVw2ZD8%0AjzYNQLyrBFNAhLJZHQXh2lpcEI0fr5RncmRDBKdpDBhNdCTfGQdP1jl2nsn0PI7z%0A0kS1XXp6EpVZPO2fY1vedt%2BwlZyC8Pa6gcqXQg49Wx9mtm91d%2F5h2lY56Vv2cYuu%0AbgC4nA2ljredGU3I5UsLEkqQMxH9c%2F9BiMsNPkXd5xLJsncpeYgD%2BsH%2BjpkvcrX6%0AEt%2BZecyK1pPIaq55qUay%2F%2Fl6HmrlI9x3MVoZZthNYn2oagAORCpC1pJhiACbd0Ib%0A4UUaEPrJQis65cg71sI%3D%0A-----END%20CERTIFICATE%20REQUEST-----%0A"
    [OCC::AccessManager::createRequest 	4 "" "https://***.your-next.cloud/ocs/v2.php/apps/end_to_end_encryption/api/v1/public-key?format=json" has X-Request-ID "a6b34a3f-92f8-4841-9ca9-a0cd9468df32"
    [OCC::AbstractNetworkJob::start 	OCC::SignPublicKeyApiJob created for "https://***.your-next.cloud" + "ocs/v2.php/apps/end_to_end_encryption/api/v1/public-key" "OCC::ClientSideEncryption"
    [OCC::WebFlowCredentials::slotFinished 	request finished
    [OCC::AbstractNetworkJob::slotFinished 	QNetworkReply::NetworkError(ProtocolInvalidOperationError) "Error transferring https://***.your-next.cloud/ocs/v2.php/apps/end_to_end_encryption/api/v1/public-key?format=json - server replied: " QVariant(int, 400)
    [OCC::WebFlowCredentials::stillValid 	Still valid?
    [OCC::WebFlowCredentials::stillValid 	QNetworkReply::NetworkError(ProtocolInvalidOperationError)
    [OCC::WebFlowCredentials::stillValid 	"Error transferring https://***.your-next.cloud/ocs/v2.php/apps/end_to_end_encryption/api/v1/public-key?format=json - server replied: "
    [OCC::SignPublicKeyApiJob::finished 	Sending CSR ended with "ocs/v2.php/apps/end_to_end_encryption/api/v1/public-key" "Error transferring https://***.your-next.cloud/ocs/v2.php/apps/end_to_end_encryption/api/v1/public-key?format=json - server replied: " QVariant(int, 400)
    [OCC::ClientSideEncryption::generateCSR::::operator() 	400

** full log **

    [OCC::Application::setupLogging 	"################## Nextcloud locale:[de_DE] ui_lang:[] version:[2.5.1final (build 20181204)] os:[Windows 10 (10.0)]"
    [OCC::Application::setupTranslations 	Using "de_DE" translation
    [OCC::SocketApi::SocketApi 	server started, listening at  "\\\\.\\pipe\\ownCloud-MYUSER"
    [OCC::FolderMan::FolderMan 	setting remote poll timer interval to 30000 msec
    [unknown 	QSslSocket: cannot resolve SSL_CONF_CTX_new
    [unknown 	QSslSocket: cannot resolve SSL_CONF_CTX_free
    [unknown 	QSslSocket: cannot resolve SSL_CONF_CTX_set_ssl_ctx
    [unknown 	QSslSocket: cannot resolve SSL_CONF_CTX_set_flags
    [unknown 	QSslSocket: cannot resolve SSL_CONF_CTX_finish
    [unknown 	QSslSocket: cannot resolve SSL_CONF_cmd
    [unknown 	QSslSocket: cannot resolve SSL_set_alpn_protos
    [unknown 	QSslSocket: cannot resolve SSL_CTX_set_alpn_select_cb
    [unknown 	QSslSocket: cannot resolve SSL_get0_alpn_selected
    [OCC::AccountManager::loadAccountHelper 	Account for QUrl("https://***.your-next.cloud") using auth type "webflow"
    [OCC::WebFlowCredentials::createQNAM 	Get QNAM
    [OCC::ownCloudGui::setupContextMenu 	Tray menu workarounds: noabouttoshow: false fakedoubleclick: false showhide: false manualvisibility: false
    [OCC::AccessManager::createRequest 	6 "GET" "https://***.your-next.cloud/ocs/v2.php/core/navigation/apps?absolute=true&format=json" has X-Request-ID "3b88f70d-0fa2-4e33-92f8-5d512c5f36db"
    [OCC::AbstractNetworkJob::start 	OCC::OcsNavigationAppsJob created for "https://***.your-next.cloud" + "ocs/v2.php/core/navigation/apps" ""
    [unknown 	QString::arg: Argument missing: Wenn diese Option aktiviert ist und keine andere Protokollierung konfiguriert ist, werden die Protokolle in einen temporären Ordner geschrieben und verfallen nach einigen Stunden. Diese Einstellung bleibt bei Client-Neustarts erhalten. Protokolle werden in % 1 geschrieben, C:/Users/MYUSER/AppData/Local/Temp/Nextcloud-logdir
    [OCC::FolderMan::setupFolders 	Setup folders from settings file
    [OCC::defaultJournalMode 	Detected filesystem "NTFS" for "C:/Users/MYUSER/Nextcloud/._sync_9489c7d5593a.db"
    [OCC::ConfigFile::setupDefaultExcludeFilePaths 	Adding user defined ignore list to csync: "C:/Users/MYUSER/AppData/Roaming/Nextcloud/sync-exclude.lst"
    [OCC::FolderMan::addFolderInternal 	Adding folder to Folder Map  OCC::Folder(0x1a591f20270) "1"
    [OCC::FolderMan::scheduleFolder 	Schedule folder  "1"  to sync!
    [OCC::FolderMan::scheduleFolder 	Folder is not ready to sync, not scheduled!
    [OCC::ownCloudGui::slotSyncStateChange 	Sync state changed for folder  "https://***.your-next.cloud/remote.php/webdav/" :  "Not yet Started"
    [OCC::SyncJournalDb::checkConnect 	sqlite3 version "3.24.0"
    [OCC::SyncJournalDb::checkConnect 	sqlite3 journal_mode= "wal"
    [OCC::ClientProxy::setupQtProxyFromConfig 	Set proxy configuration to use system configuration
    [OCC::WebFlowCredentials::fetchFromKeychain 	Fetch from keyhchain!
    [OCC::AccountState::slotCredentialsFetched 	Fetched credentials for "https://***.your-next.cloud" attempting to connect
    [OCC::WebFlowCredentials::createQNAM 	Get QNAM
    [OCC::ConnectionValidator::systemProxyLookupDone 	No system proxy set by OS
    [OCC::AccessManager::createRequest 	2 "" "https://***.your-next.cloud/status.php" has X-Request-ID "5df5ae70-7036-4c11-84fe-fae22a0b4a57"
    [OCC::AbstractNetworkJob::start 	OCC::CheckServerJob created for "https://***.your-next.cloud" + "status.php" "OCC::ConnectionValidator"
    [OCC::WebFlowCredentials::slotFinished 	request finished
    [OCC::WebFlowCredentials::stillValid 	Still valid?
    [OCC::WebFlowCredentials::stillValid 	QNetworkReply::NetworkError(NoError)
    [OCC::WebFlowCredentials::stillValid 	"Unbekannter Fehler"
    [OCC::CheckServerJob::finished 	status.php returns:  QJsonDocument({"edition":"","installed":true,"maintenance":false,"needsDbUpgrade":false,"productname":"Nextcloud","version":"14.0.4.2","versionstring":"14.0.4"})   QNetworkReply::NetworkError(NoError)  Reply:  QNetworkReplyHttpImpl(0x1a59202e7a0)
    [OCC::ConnectionValidator::slotStatusFound 	** Application: ownCloud found:  QUrl("https://***.your-next.cloud")  with version  "14.0.4" ( "14.0.4.2" )
    [OCC::ConnectionValidator::setAndCheckServerVersion 	QUrl("https://***.your-next.cloud") has server version "14.0.4.2"
    [OCC::AccessManager::createRequest 	6 "PROPFIND" "https://***.your-next.cloud/remote.php/webdav/" has X-Request-ID "bcae1836-823d-4eef-bee0-787eca9a24d3"
    [OCC::AbstractNetworkJob::start 	OCC::PropfindJob created for "https://***.your-next.cloud" + "/" "OCC::ConnectionValidator"
    [OCC::WebFlowCredentials::slotFinished 	request finished
    [OCC::WebFlowCredentials::stillValid 	Still valid?
    [OCC::WebFlowCredentials::stillValid 	QNetworkReply::NetworkError(NoError)
    [OCC::WebFlowCredentials::stillValid 	"Unbekannter Fehler"
    [OCC::PropfindJob::finished 	PROPFIND of QUrl("https://***.your-next.cloud/remote.php/webdav/") FINISHED WITH STATUS "OK"
    [OCC::AccessManager::createRequest 	2 "" "https://***.your-next.cloud/ocs/v1.php/cloud/capabilities?format=json" has X-Request-ID "03322323-19de-401c-b7e8-4e635c2ebc3a"
    [OCC::AbstractNetworkJob::start 	OCC::JsonApiJob created for "https://***.your-next.cloud" + "ocs/v1.php/cloud/capabilities" "OCC::ConnectionValidator"
    [OCC::AccessManager::createRequest 	2 "" "https://***.your-next.cloud/ocs/v1.php/config?format=json" has X-Request-ID "3b5aeda3-7cec-4bc4-9b87-cc0492785ddb"
    [OCC::AbstractNetworkJob::start 	OCC::JsonApiJob created for "https://***.your-next.cloud" + "ocs/v1.php/config" ""
    [OCC::WebFlowCredentials::slotFinished 	request finished
    [OCC::WebFlowCredentials::stillValid 	Still valid?
    [OCC::WebFlowCredentials::stillValid 	QNetworkReply::NetworkError(NoError)
    [OCC::WebFlowCredentials::stillValid 	"Unbekannter Fehler"
    [OCC::JsonApiJob::finished 	JsonApiJob of QUrl("https://***.your-next.cloud/ocs/v1.php/cloud/capabilities?format=json") FINISHED WITH STATUS "OK"
    [OCC::ConnectionValidator::slotCapabilitiesRecieved 	Server capabilities QJsonObject({"activity":{"apiv2":["filters","filters-api","previews","rich-strings"]},"bruteforce":{"delay":0},"core":{"pollinterval":60,"webdav-root":"remote.php/webdav"},"dav":{"chunking":"1.0"},"end-to-end-encryption":{"api-version":"1.0","enabled":true},"files":{"bigfilechunking":true,"blacklisted_files":[".htaccess"],"undelete":true,"versioning":true},"files_sharing":{"api_enabled":true,"default_permissions":31,"federation":{"expire_date":{"enabled":true},"incoming":true,"outgoing":true},"group":{"enabled":true,"expire_date":{"enabled":true}},"group_sharing":true,"public":{"enabled":true,"expire_date":{"enabled":false},"password":{"enforced":false},"send_mail":false,"upload":true,"upload_files_drop":true},"resharing":true,"sharebymail":{"enabled":true,"expire_date":{"enabled":true},"password":{"enabled":true},"upload_files_drop":{"enabled":true}},"user":{"expire_date":{"enabled":true},"send_mail":false}},"notifications":{"admin-notifications":["ocs","cli"],"ocs-endpoints":["list","get","delete","delete-all","icons","rich-strings"],"push":["devices","object-data"]},"ocm":{"apiVersion":"1.0-proposal1","enabled":true,"endPoint":"https://***.your-next.cloud/ocm","shareTypes":[{"name":"file","protocols":{"webdav":"/public.php/webdav/"}}]},"password_policy":{"enforceNonCommonPassword":true,"enforceNumericCharacters":false,"enforceSpecialCharacters":false,"enforceUpperLowerCase":false,"minLength":8},"theming":{"background":"https://***.your-next.cloud/core/img/background.png?v=0","background-default":true,"background-plain":false,"color":"#0082c9","color-element":"#0082c9","color-text":"#ffffff","logo":"https://***.your-next.cloud/core/img/logo.svg?v=0","name":"Nextcloud","slogan":"ein sicherer Ort für all Deine Daten","url":"https://nextcloud.com"}})
    [OCC::AccessManager::createRequest 	2 "" "https://***.your-next.cloud/ocs/v1.php/cloud/user?format=json" has X-Request-ID "b897a3cc-3ceb-4a1d-89f5-7bfe2d59b94d"
    [OCC::AbstractNetworkJob::start 	OCC::JsonApiJob created for "https://***.your-next.cloud" + "ocs/v1.php/cloud/user" "OCC::ConnectionValidator"
    [OCC::WebFlowCredentials::slotFinished 	request finished
    [OCC::WebFlowCredentials::stillValid 	Still valid?
    [OCC::WebFlowCredentials::stillValid 	QNetworkReply::NetworkError(NoError)
    [OCC::WebFlowCredentials::stillValid 	"Unbekannter Fehler"
    [OCC::JsonApiJob::finished 	JsonApiJob of QUrl("https://***.your-next.cloud/ocs/v1.php/config?format=json") FINISHED WITH STATUS "OK"
    [OCC::ConnectionValidator::ocsConfigReceived 	Determined user-visible host to be "***.your-next.cloud"
    [OCC::WebFlowCredentials::slotFinished 	request finished
    [OCC::WebFlowCredentials::stillValid 	Still valid?
    [OCC::WebFlowCredentials::stillValid 	QNetworkReply::NetworkError(NoError)
    [OCC::WebFlowCredentials::stillValid 	"Unbekannter Fehler"
    [OCC::JsonApiJob::finished 	JsonApiJob of QUrl("https://***.your-next.cloud/ocs/v1.php/cloud/user?format=json") FINISHED WITH STATUS "OK"
    [OCC::AccessManager::createRequest 	2 "" "https://***.your-next.cloud/remote.php/dav/avatars/MYUSER/128.png" has X-Request-ID "5f37776d-1475-4978-8c4d-2c99fbb2ed34"
    [OCC::AbstractNetworkJob::start 	OCC::AvatarJob created for "https://***.your-next.cloud" + "" "OCC::ConnectionValidator"
    [OCC::WebFlowCredentials::slotFinished 	request finished
    [OCC::WebFlowCredentials::stillValid 	Still valid?
    [OCC::WebFlowCredentials::stillValid 	QNetworkReply::NetworkError(NoError)
    [OCC::WebFlowCredentials::stillValid 	"Unbekannter Fehler"
    [OCC::ClientSideEncryption::initialize 	Initializing
    [OCC::ClientSideEncryption::getPublicKeyFromServer 	Retrieving public key from server
    [OCC::AccessManager::createRequest 	2 "" "https://***.your-next.cloud/ocs/v2.php/apps/end_to_end_encryption/api/v1/public-key?format=json" has X-Request-ID "a4d8ebaf-9106-4e8c-b958-12ac560a0a7b"
    [OCC::AbstractNetworkJob::start 	OCC::JsonApiJob created for "https://***.your-next.cloud" + "ocs/v2.php/apps/end_to_end_encryption/api/v1/public-key" "OCC::ClientSideEncryption"
    [OCC::WebFlowCredentials::slotFinished 	request finished
    [OCC::AbstractNetworkJob::slotFinished 	QNetworkReply::NetworkError(ContentNotFoundError) "Error transferring https://***.your-next.cloud/ocs/v2.php/apps/end_to_end_encryption/api/v1/public-key?format=json - server replied: " QVariant(int, 404)
    [OCC::WebFlowCredentials::stillValid 	Still valid?
    [OCC::WebFlowCredentials::stillValid 	QNetworkReply::NetworkError(ContentNotFoundError)
    [OCC::WebFlowCredentials::stillValid 	"Error transferring https://***.your-next.cloud/ocs/v2.php/apps/end_to_end_encryption/api/v1/public-key?format=json - server replied: "
    [OCC::JsonApiJob::finished 	JsonApiJob of QUrl("https://***.your-next.cloud/ocs/v2.php/apps/end_to_end_encryption/api/v1/public-key?format=json") FINISHED WITH STATUS "ContentNotFoundError Error transferring https://***.your-next.cloud/ocs/v2.php/apps/end_to_end_encryption/api/v1/public-key?format=json - server replied: "
    [OCC::JsonApiJob::finished 	Network error:  "ocs/v2.php/apps/end_to_end_encryption/api/v1/public-key" "Error transferring https://***.your-next.cloud/ocs/v2.php/apps/end_to_end_encryption/api/v1/public-key?format=json - server replied: " QVariant(int, 404)
    [OCC::ClientSideEncryption::getPublicKeyFromServer::::operator() 	No public key on the server
    [OCC::ClientSideEncryption::generateKeyPair 	No public key, generating a pair.
    [OCC::ClientSideEncryption::generateKeyPair 	Key correctly generated
    [OCC::ClientSideEncryption::generateKeyPair 	Storing keys locally
    [OCC::ClientSideEncryption::generateKeyPair 	Keys generated correctly, sending to server.
    [OCC::ClientSideEncryption::generateCSR 	Getting the following array for the account Id "MYUSER"
    [OCC::ClientSideEncryption::generateCSR 	Returning the certificate
    [OCC::ClientSideEncryption::generateCSR 	"-----BEGIN CERTIFICATE REQUEST-----\nMIICqjCCAZICAQEwZTELMAkGA1UEBhMCREUxGzAZBgNVBAgMEkJhZGVuLVd1ZXJ0\ndGVtYmVyZzESMBAGA1UEBwwJU3R1dHRnYXJ0MRIwEAYDVQQKDAlOZXh0Y2xvdWQx\nXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\nAQEA5HlCZ20o+nLFQi1Nv+YMfoTiWGqoojZI41XuKCbZm4kWLerdOM8CsDS52dvQ\nQL6UsgViPvu8P5/3E+1n6X8kQJFyvW4ehlAMrwwlKY+VkTSB8ss8wmnePNYHrfDE\nElGmuuBp6x/dduhrdeBCMM/9XviGenzdqRM5Y7ymQGe36RfIyUXBdB0/6QwygVvb\nLdj3xnuL+MnL+gblpjuqFARvi/2z0VYxq+w+F38ic1CVezVwUB1Xtz1neHfBC5YE\nBZ95B+bh9tfxn3SjtAHT8Ov1EzB/ZsvlIa+RPDwwugWCIVt6jXT9eCtYr7+TOwIv\nyQluy5cc3tmztZmnbxgcEUWKOQIDAQABoAAwDQYJKoZIhvcNAQEFBQADggEBAC0e\nYRGZi7H6dZ7XVLn6j4+4GQ+MK6/O3PZlvr6dxWAq5rePaX8v1ISSFcBf5qVw2ZD8\njzYNQLyrBFNAhLJZHQXh2lpcEI0fr5RncmRDBKdpDBhNdCTfGQdP1jl2nsn0PI7z\n0kS1XXp6EpVZPO2fY1vedt+wlZyC8Pa6gcqXQg49Wx9mtm91d/5h2lY56Vv2cYuu\nbgC4nA2ljredGU3I5UsLEkqQMxH9c/9BiMsNPkXd5xLJsncpeYgD+sH+jpkvcrX6\nEt+ZecyK1pPIaq55qUay//l6HmrlI9x3MVoZZthNYn2oagAORCpC1pJhiACbd0Ib\n4UUaEPrJQis65cg71sI=\n-----END CERTIFICATE REQUEST-----\n"
    [OCC::SignPublicKeyApiJob::start 	Sending the CSR "csr=-----BEGIN%20CERTIFICATE%20REQUEST-----%0AMIICqjCCAZICAQEwZTELMAkGA1UEBhMCREUxGzAZBgNVBAgMEkJhZGVuLVd1ZXJ0%0AdGVtYmVyZzESMBAGA1UEBwwJU3R1dHRnYXJ0MRIwEAYDVQQKDAlOZXh0Y2xvdWQx%0AXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX%0AAQEA5HlCZ20o%2BnLFQi1Nv%2BYMfoTiWGqoojZI41XuKCbZm4kWLerdOM8CsDS52dvQ%0AQL6UsgViPvu8P5%2F3E%2B1n6X8kQJFyvW4ehlAMrwwlKY%2BVkTSB8ss8wmnePNYHrfDE%0AElGmuuBp6x%2FdduhrdeBCMM%2F9XviGenzdqRM5Y7ymQGe36RfIyUXBdB0%2F6QwygVvb%0ALdj3xnuL%2BMnL%2BgblpjuqFARvi%2F2z0VYxq%2Bw%2BF38ic1CVezVwUB1Xtz1neHfBC5YE%0ABZ95B%2Bbh9tfxn3SjtAHT8Ov1EzB%2FZsvlIa%2BRPDwwugWCIVt6jXT9eCtYr7%2BTOwIv%0AyQluy5cc3tmztZmnbxgcEUWKOQIDAQABoAAwDQYJKoZIhvcNAQEFBQADggEBAC0e%0AYRGZi7H6dZ7XVLn6j4%2B4GQ%2BMK6%2FO3PZlvr6dxWAq5rePaX8v1ISSFcBf5qVw2ZD8%0AjzYNQLyrBFNAhLJZHQXh2lpcEI0fr5RncmRDBKdpDBhNdCTfGQdP1jl2nsn0PI7z%0A0kS1XXp6EpVZPO2fY1vedt%2BwlZyC8Pa6gcqXQg49Wx9mtm91d%2F5h2lY56Vv2cYuu%0AbgC4nA2ljredGU3I5UsLEkqQMxH9c%2F9BiMsNPkXd5xLJsncpeYgD%2BsH%2BjpkvcrX6%0AEt%2BZecyK1pPIaq55qUay%2F%2Fl6HmrlI9x3MVoZZthNYn2oagAORCpC1pJhiACbd0Ib%0A4UUaEPrJQis65cg71sI%3D%0A-----END%20CERTIFICATE%20REQUEST-----%0A"
    [OCC::AccessManager::createRequest 	4 "" "https://***.your-next.cloud/ocs/v2.php/apps/end_to_end_encryption/api/v1/public-key?format=json" has X-Request-ID "a6b34a3f-92f8-4841-9ca9-a0cd9468df32"
    [OCC::AbstractNetworkJob::start 	OCC::SignPublicKeyApiJob created for "https://***.your-next.cloud" + "ocs/v2.php/apps/end_to_end_encryption/api/v1/public-key" "OCC::ClientSideEncryption"
    [OCC::WebFlowCredentials::slotFinished 	request finished
    [OCC::AbstractNetworkJob::slotFinished 	QNetworkReply::NetworkError(ProtocolInvalidOperationError) "Error transferring https://***.your-next.cloud/ocs/v2.php/apps/end_to_end_encryption/api/v1/public-key?format=json - server replied: " QVariant(int, 400)
    [OCC::WebFlowCredentials::stillValid 	Still valid?
    [OCC::WebFlowCredentials::stillValid 	QNetworkReply::NetworkError(ProtocolInvalidOperationError)
    [OCC::WebFlowCredentials::stillValid 	"Error transferring https://***.your-next.cloud/ocs/v2.php/apps/end_to_end_encryption/api/v1/public-key?format=json - server replied: "
    [OCC::SignPublicKeyApiJob::finished 	Sending CSR ended with "ocs/v2.php/apps/end_to_end_encryption/api/v1/public-key" "Error transferring https://***.your-next.cloud/ocs/v2.php/apps/end_to_end_encryption/api/v1/public-key?format=json - server replied: " QVariant(int, 400)
    [OCC::ClientSideEncryption::generateCSR::::operator() 	400
    [OCC::OCUpdater::backgroundCheckForUpdate 	Checking for available update
    [OCC::AccessManager::createRequest 	2 "" "https://updates.nextcloud.org/client/?version=2.5.1.20181204&platform=win32&oem=Nextcloud&versionsuffix=final" has X-Request-ID "e68bade5-3f98-4ce7-b9ef-f6f91a10c8f4"
    [OCC::NSISUpdater::versionInfoArrived 	Client is on latest version!
    [OCC::AccountState::checkConnectivity 	ConnectionValidator already running, ignoring "MYUSER@***.your-next.cloud"
    [OCC::AccountState::checkConnectivity 	ConnectionValidator already running, ignoring "MYUSER@***.your-next.cloud"
    [OCC::AccountState::checkConnectivity 	ConnectionValidator already running, ignoring "MYUSER@***.your-next.cloud"
    [OCC::AccountState::checkConnectivity 	ConnectionValidator already running, ignoring "MYUSER@***.your-next.cloud"
    [OCC::AccountState::checkConnectivity 	ConnectionValidator already running, ignoring "MYUSER@***.your-next.cloud"
    [OCC::AccessManager::createRequest 	6 "GET" "https://***.your-next.cloud/ocs/v2.php/core/navigation/apps?absolute=true&format=json" has X-Request-ID "f20acbb2-f6e4-4048-93e6-0a6514fe76ee"
    [OCC::AbstractNetworkJob::start 	OCC::OcsNavigationAppsJob created for "https://***.your-next.cloud" + "ocs/v2.php/core/navigation/apps" ""
    [OCC::WebFlowCredentials::slotFinished 	request finished
    [OCC::WebFlowCredentials::stillValid 	Still valid?
    [OCC::WebFlowCredentials::stillValid 	QNetworkReply::NetworkError(NoError)
    [OCC::WebFlowCredentials::stillValid 	"Unbekannter Fehler"
    [OCC::AccessManager::createRequest 	6 "GET" "https://***.your-next.cloud/ocs/v2.php/core/navigation/apps?absolute=true&format=json" has X-Request-ID "a130327c-8b18-4b94-be6e-17d1b151e474"
    [OCC::AbstractNetworkJob::start 	OCC::OcsNavigationAppsJob created for "https://***.your-next.cloud" + "ocs/v2.php/core/navigation/apps" ""
    [OCC::WebFlowCredentials::slotFinished 	request finished
    [OCC::WebFlowCredentials::stillValid 	Still valid?
    [OCC::WebFlowCredentials::stillValid 	QNetworkReply::NetworkError(NoError)
    [OCC::WebFlowCredentials::stillValid 	"Unbekannter Fehler"
    [OCC::AccountManager::saveAccount 	Saving account "https://***.your-next.cloud"
    [OCC::AccountManager::saveAccountHelper 	Saving  0  unknown certs.
    [OCC::AccountManager::saveAccountHelper 	Saving cookies. "C:/Users/MYUSER/AppData/Local/Nextcloud/cookies0.db"
    [unknown 	QIODevice::write (QFile, "C:\Users\MYUSER\AppData\Local\Nextcloud\cookies0.db"): device not open
    [OCC::AccountManager::saveAccount 	Saved account settings, status: QSettings::Status(NoError)
    [OCC::AccountManager::saveAccountHelper 	Saving  0  unknown certs.
    [OCC::AccountManager::saveAccountHelper 	Saving cookies. "C:/Users/MYUSER/AppData/Local/Nextcloud/cookies0.db"
    [unknown 	QIODevice::write (QFile, "C:\Users\MYUSER\AppData\Local\Nextcloud\cookies0.db"): device not open
    [OCC::AccountManager::save 	Saved all account settings, status: QSettings::Status(NoError)
    [OCC::SyncJournalDb::close 	Closing DB "C:/Users/MYUSER/Nextcloud/._sync_9489c7d5593a.db"
    [unknown 	Could not parse stylesheet of object 0x1a58f31f2c0
    [OCC::WebViewPage::WebViewPage 	Time for a webview!
    [unknown 	Could not parse stylesheet of object 0x1a58f31f2c0
    [unknown 	Could not parse stylesheet of object 0x1a58f31f2c0

2. Web server error log:
n/a
3. Server logfile: nextcloud log (data/nextcloud.log):
n/a

**Comment by Kombustor** [comment] 2019-03-03 22:38
I have the exact same problem. Any news on this?

**Comment by DominiqueFuchs** [comment] 2019-09-25 14:09
Duplicate of original issue [desktop/#830](https://github.com/nextcloud/desktop/issues/830) and fixed by [desktop/PR#1420](https://github.com/nextcloud/desktop/pull/1420)

**Closed by DominiqueFuchs** 2019-09-25 14:09 UTC
Labels: 4. to test, bug, feature: :lock: end to end encryption
