### ISSUE TITLE
Tray icon squished on multi-monitor setup with macOS

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/desktop#2891] opened 2021-02-01 15:31 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour
The tray icon is always round.

### Actual behaviour
On a multi-monitor setup with a new MacBook Air and a 1920*1080 external monitor, it looks like this on _one_ of the screens:
<img width="177" alt="Desktop client tray icon MacBook Air when connected to 1080 p display" src="https://user-images.githubusercontent.com/925062/106479523-b3e0bc80-64aa-11eb-87dd-a3a9799c1dbc.png">

Then when you click it and the tray menu opens, it looks fine again.
<img width="143" alt="Desktop client tray icon open" src="https://user-images.githubusercontent.com/925062/106479525-b4795300-64aa-11eb-8f25-da5ff9f029d7.png">

But then the _other_ one looks squished. :D 

### Client configuration
Client version: 3.1.2

Operating system: macOS

OS language: German

Installation path of client: default macOS

**Comment by er-vin** [comment] 2021-02-01 15:41
Duplicate of #2584

**Closed by er-vin** 2021-02-01 15:41 UTC
Labels: bug, feature: :cloud: system tray
