### ISSUE TITLE
Sync of subfolders not working with e2e enabled

### ISSUE THREAD

**Issue by flocke** [nextcloud/desktop#1417] opened 2019-09-13 10:58 UTC
I am trying to sync a subfolder of my server to a local directory. I can successfully add the new sync folder but the files to not get downloaded. This is most likely due to a wrong remote path used in the `GetFolderEncryptStatusJob`. See the Logs section for more details.

### Expected behaviour

Subfolders get synced successfully

### Actual behaviour

Empty folders get created locally but no files from the server get synced

### Steps to reproduce
0. Enable E2E encryption on your server (I also enabled and set it up for my account on my Android phone)
1. Set up the client as usual, but don't add any folders during setup
2. Manually add a subfolder to sync ('**/Documents/**' in my case, synced to `/home/flocke/data/documents/`)
3. Try to sync

### Client configuration
Client version: `2.5.3, 2.6.0-rc1 and current git`

Operating system: `Arch Linux`

OS language: `en_US.UTF-8`

Qt version used by client package (Linux only, see also Settings dialog): `5.13.1`

Client package (From Nextcloud or distro) (Linux only): `nextcloud-client (2.5.3, official Arch Linux package), 2.6.0-rc1 and git are built by me (based on the official package)`

Installation path of client: `/usr/bin/nextcloud`

### Logs

In the Logs there is the following line for each folder that should be synced:
```
[OCC::GetFolderEncryptStatusJob::finished 	GetFolderEncryptStatus of QUrl("https://cloud.shadowice.org/remote.php/webdav/Work/Application/Forms/Raw") finished with status QNetworkReply::ContentNotFoundError "Error transferring https://cloud.shadowice.org/remote.php/webdav/Work/Application/Forms/Raw - server replied: "
[OCC::GetFolderEncryptStatusJob::finished 	*not* successful, http result code is 404 ""
```
Here the client is trying to get the encryption status of the folder `Work/Application/Forms/Raw`, which is wrong. It should be `Documents/Work/Application/Forms/Raw` (note the missing **Documents/**). The paths seem to be checked relative to the root folder of my user, not to the subfolder I am actually trying to sync.

**Comment by carlfriedrich** [comment] 2019-10-01 13:17
This seems to be the same as #876.

**Comment by er-vin** [comment] 2020-06-02 18:28
#2050 was a duplicate of this one, but at least confirmed that a) it still shows up with 2.6.4 and b) it affects Windows users as well.

**Comment by 0liu** [comment] 2020-06-24 16:15
This affects both Linux and Mac 2.6.4 clients syncing with my 18.0.6 home server.

**Closed** 2020-07-01 17:10 UTC
Labels: approved, bug, feature: :lock: end to end encryption
