### ISSUE TITLE
Client stuck in sync

### ISSUE THREAD

**Issue by EchoDev** [nextcloud/desktop#199] opened 2018-02-28 03:14 UTC
I'm running Nextcloud 13 with E2E enabled. I first had this issue with the techpreview Windows client. I grabbed the source from the E2E encryption branche and built the windows client and I still have the same issue.

I can't see what the client is trying to sync and I don't see anything on the server logs. Anyone knows what it could be or how I could find out what is causing it.

**Comment by EchoDev** [comment] 2018-03-10 00:12
Ok so I had some time to test the issue and it seems to be an issues with edited files being synced.

To reproduce this issue:

1. Have E2EE enabled on your server and desktop client
2. Place a (text) file in one of your encrypted folders and let the desktop client sync
3. Confirm via mobile client or via an other pc that the file has been synced correctly
4. Edit the (text) file on PC
5. The desktop client will be stuck in sync mode

**Comment by tcanabrava** [comment] 2018-03-11 23:54
On Sat, Mar 10, 2018 at 1:12 AM, EchoDev <notifications@github.com> wrote:

> Ok so I had some time to test the issue and it seems to be an issues with
> edited files being synced.
>
> To reproduce this issue:
>
>    1. Have E2EE enabled on your server and desktop client
>    2. Place a (text) file in one of your encrypted folders and let the
>    desktop client sync
>    3. Confirm via mobile client or via an other pc that the file has been
>    synced correctly
>    4. Edit the (text) file on PC
>    5. The desktop client will be stuck in sync mode
>
>
Thanks. This really helps.
I'm debugging and trying to understand where it's failing.

**Comment by EchoDev** [comment] 2018-04-27 18:50
I built the client from master but it just seems to crash on login/sync. (I couldn't build from the v4 branch since it is deleted)

**Comment by camilasan** [comment] 2018-04-27 19:07
Could you share your logs? Where does it crash? Was it with a new user or an existing user?

**Comment by dantti** [comment] 2018-04-27 19:12
Hmm I didn't know about the v4 branch merge, it is crashing on Windows?

**Comment by EchoDev** [comment] 2018-04-27 19:17
There is nothing in the server logs regarding the crash. Does the client produce logs somewhere?

I did the following:

1. Try to log in with existing user A that had E2EE enabled and has passphrase entered previously -> client crashes
2. Create new user B, log in with it -> I get the encryption phrase -> I click Ok -> Crash
3. Try to log in with new user B -> Crash

If I go back to the tech preview client it doesn't crash but the issue of stuck in sync remains.

**Comment by camilasan** [comment] 2018-04-27 19:44
could you send the backtrace and which version of openssh you have @EchoDev?

**Comment by EchoDev** [comment] 2018-04-27 21:07
@camilasan reverting the following commits fixed the crashes for me

https://github.com/nextcloud/client/commit/faf64958ec1f74c3842aa1f37716231057902077

https://github.com/nextcloud/client/commit/40b1f051a4d968e45556817272e132054c91aeba

I need some time to see if the syncing issue is fixed (Not being able to revoke and generate new E2EE passphrases is really a pita.)

**Comment by tabp0le** [comment] 2018-04-27 23:52
So, I am also having issues with the latest merge of the E2E. (besides the issue with the logs, which is easily remedied by reverting one commit)

The sync will not complete, especially for large folders. It seems also to sync the root folder, and folder structure, but not the items contained in the folders. Nextcloud 13, master branch of client. Windows and Linux.

**Comment by EchoDev** [comment] 2018-04-28 00:05
Same for me. The latest version has become worse than the techpreview. 

I have the same problems as @tabp0le first time sync won't even work now. (It just stop randomly stop after syncing a few small files)

When I try to open the files from the Android client it gives me a "Locked" reply. I'm assuming the client isn't finishing the files it is uploading and locks up/stops?

**Comment by tabp0le** [comment] 2018-04-28 00:11
To follow up on what @EchoDev said, I've noticed the locking too. While it's trying to sync, an error in the server log shows up: "Cannot find file $filename" (Obviously I substituted $filename for the real list of files. It's really logspam, just spews for every single directory) I tried wiping redis, all caches, dropped the locking tables from the database. Nothing solves the issue.

Additionaly another weird error that shows up (for each file): `"GOAWAY received, cannot start a request"`

**Comment by tcanabrava** [comment] 2018-04-28 06:39
The biggest issue is the spec, it makes the end to end encryption single
 threaded and because of a client limitation and I can only send one file
per time (no concurrent uploads, so it will be much slower). The locking
problem I need more info. I think I know what can be causing this but I’m
unsure if it’s the root cause.

**Comment by camilasan** [comment] 2018-05-07 15:46
Nothing else we can improve @tcanabrava? Besides moving the metadata to the file?

**Comment by dantti** [comment] 2018-05-07 18:39
@camilasan AFAIK webdav support attributes per file, which would make things a lot better than maintaining the single JSON file, while OTOH making more HTTP requests, still if we could discuss this new spec again we could release something more solid, when it was drafted there was no implementation to prove if it would work well.

**Comment by camilasan** [comment] 2018-05-07 19:29
@dantti @tcanabrava the issues described here are related to the e2ee being slow or this could just be a different bug?

**Comment by jospoortvliet** [comment] 2018-05-07 19:39
Guys, let's focus on making it stable, performance comes next. Obviously, locking the E2E folder, uploading a file, unlocking again, locking again, uploading, unlocking - that serializes server access and makes it slower. We can perhaps change the protocol later to allow uploading multiple files at once.

But for now, being slow is not a problem for the first release. Losing files is. Let's just make it stable, if we have to tell people:
1. it will be slower in syncing
2. it can handle only 50 files in a single E2E folder before performance becomes cripling

that is fine.

The attributes per file means a whole new design, the choice for a single JSON file was made for a reason so let's stick with that for now. We can discuss changes at the Nextcloud conference, provided we released this before then.

**Comment by dantti** [comment] 2018-05-07 19:54
@jospoortvliet sure, but I have in mind a few important problems that aren't about performance, not sure discussing here is a good place.

**Comment by jospoortvliet** [comment] 2018-05-07 19:56
Sure, if there are fundamental problems with the design/protocol that block implementation or make it insecure, they should be discussed here:
https://github.com/nextcloud/end_to_end_encryption_rfc/issues

**Comment by camilasan** [comment] 2018-09-04 12:30
@EchoDev Could you try this build - please make sure to have a clean configuration - https://download.nextcloud.com/desktop/daily/Windows/Nextcloud-2.5.0.61352-daily-20180904.exe?
It solved a lot of known connecting and syncing issues.

**Comment by EchoDev** [comment] 2018-09-04 18:45
Did some more tests, all tests done on encrypted folders ofcourse

Test 1: Sync with the desktop client, only a few files get synced before the client locks up

E2EE Files synced from desktop are not accessible on mobile (Android). Only some of the files that are supposed to be synced show up in the Android client and when you try to download those files the client gives the error "Download failed - The file is no longer available on the server"

Test 2: Sync with the mobile Android client, the upload completed partially.
E2EE files and folders created and uploaded from the mobile client also have issues with the desktop client when the desktop client is active? I uploaded 20+ files at the same time but the desktop client seems to try to grab the files early? The desktop client says 

Server replied "423 Locked" to "GET https://server/remote.php/dav/files/username/folder/-random-numbers-and-letters"

Random numbers and letters are probably the encrypted filenames on server. After a while this causes the mobile client uploads to be corrupted. I had to set the folder to unencrypted to be able to delete the files.

Test 3: Upload a single file from Android client and sync it with the desktop client
Creating and uploading 1 file from the mobile client seems to not cause any issues in the desktop client. Upload from mobile 

Test 4: Upload multiple files from the Android client while the desktop client is turned off and sync the files after upload on mobile is done.
Again the uploads from Android got borked, after 10-15 files the client says it failed uploading files to the server, tho this time the original filenames were kept as they were. The files were again corrupted.


At this point I'm not sure if this is an desktop client issue or just an e2ee/nextcloud server software issue. Syncing single files seems to work okay but throwing 20+ files at either of the clients cause the files to become corrupted (on the server).

**Comment by mcronce** [comment] 2018-11-20 18:29
Uhh...interesting.  Maybe it was just spending a long time trying to process the list of changes.  (It was pegging one CPU core when it appeared to be hanging.)  Immediately after I posted that it stopped hanging and started downloading files.  Maybe I posted that prematurely.

**Comment by mlaverdiere** [comment] 2018-12-17 14:45
Same problem on Windows with ND client version 2.5.1final (build 20181204), with NS server 14.0.4, i.e. client stuck on sync when adding a file in a E2EE folder.

**Comment by Alphakilo** [comment] 2019-01-28 09:42
I get this behavior across:
* iOS (2.22.8.20),
* Android,
* Fedora 29 (2.5.1-1.fc29 from updates-testing),
* Ubuntu / Mint (Flatpak), 
* Windows 10 (2.5.1) 

when trying to sync E2E folders with my Nextcloud server (Nextcloud 15.0.2.0, Ubuntu 18.04, PHP 7.3, apache2 compiled with h2 and tls-1.3). The issue is consistent across multiple users.

Funny enough, the client that initially uploaded the E2EE folder can access it's contents afterwards.
All other sync clients fail. The Windows version crashes, leaving behind only an error in the Windows Eventlog.

The Apache Access log shows this:
`192.168.0.50 - - [28/Jan/2019:10:06:08 +0100] "GET /remote.php/dav/files/user/E2EE-folder/subfolder/file.pdf HTTP/2.0" 423 258 "-" "Mozilla/5.0 (Linux) mirall/2.5.1git (Nextcloud)"`

The sync client on Fedora shows this in the log window:
```
[OCC::WebFlowCredentials::stillValid    "Error transferring https://cloud.my.domain.tld/remote.php/dav/files/user/E2EE-folder/subfolder/file.txt - server replied: "
[OCC::SyncJournalDb::setErrorBlacklistEntry     Setting blacklist entry for  "E2EE-folder/subfolder/file.txt" 11 "Error transferring https://cloud.my.domain.tld/remote.php/dav/files/user/E2EE-folder/subfolder/file.txt - server replied: " 1548667448 0 1514381889 "78bb2317ea76d49ab6c3c12f706b5af6" "" 0
[OCC::blacklistUpdate   escalating soft error on  "E2EE-folder/subfolder/file.txt"  to normal error,  423
[OCC::PropagateItemJob::done    Could not complete propagation of "E2EE-folder/subfolder/file.txt" by OCC::PropagateDownloadFile(0x62bf55922840) with status 2 and error: "Error transferring https://cloud.my.domain.tld/remote.php/dav/files/user/E2EE-folder/subfolder/file.txt - server replied: "
[OCC::ActivityWidget::slotItemCompleted         Item  "E2EE-folder/subfolder/file.txt"  retrieved resulted in  "Error transferring https://cloud.my.domain.tld/remote.php/dav/files/user/E2EE-folder/subfolder/file.txt - server replied: "
[OCC::ActivityWidget::slotItemCompleted         Item  "E2EE-folder/subfolder/file.txt"  retrieved resulted in error  "Error transferring https://cloud.my.domain.tld/remote.php/dav/files/user/E2EE-folder/subfolder/file.txt - server replied: "
```

Both the nextcloud.log and the Apache error.log contain no further information.

@camilasan May I ask you to reconsider the `closed` status on this issue?

**Comment by DC7IA** [comment] 2020-04-26 21:45
Problem still seems to persist in the current version.

**Comment by Pilzinsel64** [comment] 2020-05-31 08:58
Maybe my issue is related to this also?
https://github.com/nextcloud/server/issues/21169

**Comment by er-vin** [comment] 2020-06-03 16:26
I sounds a lot like this one and #1862 are related.

**Comment by camilasan** [comment] 2020-07-11 15:56
I am still experiencing it with the current desktop client from master (build 11.07), end to end encryption app master too and Nextcloud 17.

**Comment by camilasan** [comment] 2020-07-12 15:17
- I have created a fresh user, set up everything on Linux, created new folder, encrypted it, added a file to it.
- On Windows, it got stuck syncing everything.
- Restarted the client in Windows and got this at first: 2020-07-12 16:36:07:821 [ critical nextcloud.sync.propagator.download.encrypted ]:      Failed to find encrypted metadata information of remote file "bank files"
- Added another folder under the encrypted folder from Linux and added file in it - client on windows got stuck, Linux doesn't see the new files from Windows yet.
- Eventually synced but the file under the subfolder of an encrypted folder did not sync and Linux and Windows are reporting that everything got synced (green check icon) 

Windows (see file is there)
![windows](https://user-images.githubusercontent.com/241266/87249496-bb356f80-c45f-11ea-8366-60cd91425b39.png)

Linux (file is not there)
![Linux](https://user-images.githubusercontent.com/241266/87249497-bbce0600-c45f-11ea-9ca2-16102502e3d8.png)

- Edited this file under the subfolder of an encrypted folder to try to trigger sync again. Also the files under the encrypted folder are not marked as encrypted in the database (expected?)

- Windows client it is stuck syncing again.
- Forcing sync again gives me the green check icon but file it is still missing on Linux... and a few seconds later it gets stuck again.
- Restarting the client also doesn't help.

Will upload the logs later.

**Comment by er-vin** [comment] 2020-07-13 12:49
From your logs it looks like there is something wrong on the server side. For some reason it rejects any folder locking attempt with a 403 (on both the Linux and the Windows sides). I think we need to find out why before you can try to reproduce the issue reported here, it's something different getting in your way.

**Comment by camilasan** [comment] 2020-07-14 15:00
I am still able to reproduce this issue. This is now in my localhost, server 19, end to end encryption from master:  I still have a bunch of 403 in the logs of Windows and Linux.

**Comment by DominiqueFuchs** [comment] 2020-07-14 21:28
Testing report:

Nextcloud daily master 20200714; everything default + SSL,HTTP2
E2EE master d3471e1
Desktop Client master 5c442af

Client1, Client2; Both Windows

1. Add testuser (Web Admin)
2. Connect Client1 w/ testuser
3. Enable E2EE / mnemonic
4. Create folder e2ee-sync-test
5. Check encrypt folder in client
6. Create file test.txt in e2ee-sync-test
7. All fine, synced
8. Opened file, typed text, saved
9. All fine, synced
10. Added dummy files in e2ee-sync.test (50x2MB, 40x8MB, filled with 0)
11. All fine, synced, log is clean/error-free
12. Connect Client2 w/ testuser (Client1 still running on other machine)
13. All fine, synced, can see and edit encrypted files, logs clean
14. Open test.txt in Client2, edit text, save but leaving file opened in editor
15. All fine, client syncs, changes appear in Client1
16. Open test.txt in Client1, edit text, save but leaving file opened in editor
17. All fine, client syncs, sync attempt in Client2 but changes not appearing b/c still opened, no error (this is by design)
18. Closing file on Client 2, check back few mins later, changes from 16 wer synced down

No problems that way. I can throw in another client tomorrow on a different platform. No android devices here but spinning up a Linux distro with Client3 should be possible

// @camilasan 

[nextcloud-server.log.zip](https://github.com/nextcloud/desktop/files/4921604/nextcloud-server.log.zip)

**Comment by NewRedsquare** [comment] 2020-07-14 22:26
I think that E2E itself can work but it's not trustworthy :/

**Comment by camilasan** [comment] 2020-07-15 12:52
I am closing this issue because I managed to get the syncing working by not using https. It was an SSL issue on my side. it works like a charm now.

**Closed by camilasan** 2020-07-15 12:52 UTC
Labels: approved, bug, discussion, feature: :lock: end to end encryption
