### ISSUE TITLE
PPA install: Dependency resolution issue on KDE neon 20.04 regarding QT 5.15.2

### ISSUE THREAD

**Issue by TimJay** [nextcloud/desktop#2722] opened 2020-12-15 16:24 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour
Being able to update the package nextcloud-desktop in version 3.1.0 from the “Nextcloud development” team PPA at https://launchpad.net/~nextcloud-devs/+archive/ubuntu/client on a KDE neon 20.04 system.

### Actual behaviour
Attempting to update the package nextcloud-dekstop on KDE neon 20.04 resultet in a dependency resolution issue:
```
The following packages have unmet dependencies:
 nextcloud-desktop : Depends: qtbase-abi-5-12-8
```

### Steps to reproduce
1. On a current KDE neon 20.04
2. `sudo apt update`
3. `sudo apt install nextcloud-desktop`

### Client configuration
Client version: 3.1.0

Operating system: KDE neon 20.04

OS language: english

Qt version used by client package (Linux only, see also Settings dialog): **5.15.2**

Client package (From Nextcloud or distro) (Linux only): nextcloud-desktop from “Nextcloud development” team PPA

Installation path of client: ?

**Comment by er-vin** [comment] 2020-12-15 16:35
Duplicate of #2711 ?

**Comment by bovender** [comment] 2020-12-16 09:39
Same here, this morning's system upgrade left me without a Nextcloud desktop client on my workhorse :-(

```
Operating System: KDE neon 5.20
KDE Plasma Version: 5.20.4
KDE Frameworks Version: 5.77.0
Qt Version: 5.15.2
Kernel Version: 5.4.0-58-generic
OS Type: 64-bit
Processors: 8 × Intel® Core™ i5-8250U CPU @ 1.60GHz
Memory: 23,4 GiB of RAM
Graphics Processor: Mesa Intel® UHD Graphics 620
```

**Comment by TimJay** [comment] 2020-12-16 10:15
@er-vin sorry for the noise, #2722 can be closed as a duplicate of #2711

**Comment by er-vin** [comment] 2020-12-16 18:03
Alright, closing as duplicate of #2711 then.

**Closed by er-vin** 2020-12-16 18:03 UTC
Labels: bug, package: PPA

**Comment by TimJay** [comment] 2020-12-17 13:43
As a brief summary a quote from #2711:
"So this means that the PPA does not support KDE Neon, only standard Ubuntu and those derivates that do not perform such incompatible alterations." @ivaradi

Which I think is reasonable considering the nature of KDE neon.
I guess for the time being, AppImage will have to do.

**Comment by avatar1024** [comment] 2021-01-12 08:34
This issue with the AppImage is that there is no inegration with file manager (say Dolphin). Is there a way around it?

**Comment by itsjustarumour** [comment] 2021-01-23 06:17
This issue report has been closed as a duplicate of #2711, however a later comment on #2711 says it is a separate issue and therefore it's not a duplicate of this issue #2722 (and #2711 has now been closed).

Can this therefore be re-opened?  This issue still exists on KDE Neon 20.04, and installing the AppImage isn't a workable solution for some people due (as **avatar1024** says) the lack of integration with the Dolphin file manager.

**Comment by er-vin** [comment] 2021-01-25 09:54
> Can #2722 therefore be re-opened? This issue still exists on KDE Neon 20.04, and installing the AppImage isn't a workable solution for some people due (as **avatar1024** says) to the lack of integration with the Dolphin file manager.

Let's summon @ivaradi is it something we can and are willing to support? I honestly doubt this can fly properly and it's likely that KDE Neon needs to package Nextcloud themselves.

**Comment by ivaradi** [comment] 2021-01-25 10:33
I don't think this can be reasonably supported. Unless KDE Neon has some packaging service, like Launchpad, where we could easily upload our source packages to have it built with the correct Qt package versions.

**Comment by cypx** [comment] 2021-01-31 17:40
qtbase-abi is just a virtual package for libqt5core5a which is provided On Neon
https://packages.ubuntu.com/focal/qtbase-abi-5-12-8
Is it not possible to use directly libqt5core5a as dependence.

Flatpak or AppImage system integration are a bit limited for this kind of application so I revert and stick to previous version provided by official focal repo.

```bash
sudo apt install nextcloud-desktop=2.6.2-1build1 libnextcloudsync0=2.6.2-1build1
sudo apt-mark hold nextcloud-desktop libnextcloudsync0
```

**Comment by antanicus** [comment] 2021-02-12 10:15
> 
> 
> qtbase-abi is just a virtual package for libqt5core5a which is provided On Neon
> https://packages.ubuntu.com/focal/qtbase-abi-5-12-8
> Is it not possible to use directly libqt5core5a as dependence.
> 
> Flatpak or AppImage system integration are a bit limited for this kind of application so I revert and stick to previous version provided by official focal repo.
> 
> ```shell
> sudo apt install nextcloud-desktop=2.6.2-1build1 libnextcloudsync0=2.6.2-1build1
> sudo apt-mark hold nextcloud-desktop libnextcloudsync0
> ```

You mean the official ubuntu 20.04 repositories?

**Comment by cypx** [comment] 2021-02-18 21:09
Yes but since I tried to rebuild package from source and it's work well

```bash
echo "deb-src http://ppa.launchpad.net/nextcloud-devs/client/ubuntu focal main" | sudo tee -a /etc/apt/sources.list.d/nextcloud-devs-ubuntu-client-focal-src.list
sudo apt update
sudo apt build-dep nextcloud-desktop
cd /tmp
apt source --compile nextcloud-desktop
sudo apt install ./nextcloud-desktop_3.1.3-20210218.151938.3842d306f-1.0~focal1_amd64.deb
```

**Comment by kcybulski** [comment] 2021-02-21 07:28
I create package, to fix missing dependency. 
Use on your own responsibility

```
#!/bin/bash

$(mkdir -p ./qtbase-abi-5-12-8-fix/DEBIAN)
echo 'Package: qtbase-abi-5-12-8-fix
Version: 1.0
Section: custom
Priority: optional
Provides: qtbase-abi-5-12-8
Depends: libqt5core5a
Architecture: amd64
Essential: no
Installed-Size: 0
Maintainer: custom
Description: Fix lack of qtbase-abi-5-12-8 in KDE Neon
' > ./qtbase-abi-5-12-8-fix/DEBIAN/control

$(dpkg-deb --build ./qtbase-abi-5-12-8-fix)

```
To install use ```dpkg -i ./qtbase-abi-5-12-8-fix.deb``` in console.

**Comment by YamiYukiSenpai** [comment] 2021-05-30 07:47
> sudo apt build-dep nextcloud-desktop

That didn't work because it says it depends on `kdelibs5-dev`, but it's not in the repo

**Comment by cyBea** [comment] 2021-12-03 10:21
I love the fix by @kcybulski  but I needed to remove "$(" and ")" in line 17 like so:
```
#!/bin/bash

$(mkdir -p ./qtbase-abi-5-12-8-fix/DEBIAN)
echo 'Package: qtbase-abi-5-12-8-fix
Version: 1.0
Section: custom
Priority: optional
Provides: qtbase-abi-5-12-8
Depends: libqt5core5a
Architecture: amd64
Essential: no
Installed-Size: 0
Maintainer: custom
Description: Fix lack of qtbase-abi-5-12-8 in KDE Neon
' > ./qtbase-abi-5-12-8-fix/DEBIAN/control

dpkg-deb --build ./qtbase-abi-5-12-8-fix
```
Also I wonder why this cannot be fixed by different packaging / dependency definition but needs a dummy package.

**Comment by wonx** [comment] 2022-04-06 05:01
For Kubuntu 22.04 the script has to be modified, since now it requires ``qtbase-abi-5-15-2``

It should be like this:
```
#!/bin/bash

$(mkdir -p ./qtbase-abi-5-15-2-fix/DEBIAN)
echo 'Package: qtbase-abi-5-15-2-fix
Version: 1.0
Section: custom
Priority: optional
Provides: qtbase-abi-5-15-2
Depends: libqt5core5a
Architecture: amd64
Essential: no
Installed-Size: 0
Maintainer: custom
Description: Fix lack of qtbase-abi-5-15-2 in KDE Neon
' > ./qtbase-abi-5-15-2-fix/DEBIAN/control

dpkg-deb --build ./qtbase-abi-5-15-2-fix
```

Then just save it as an .sh file, run it, and finally: 
``sudo dpkg -i ./qtbase-abi-5-15-2-fix.deb``

I don't get why it hasn't been fixed yet...

**Comment by cyBea** [comment] 2022-06-23 13:51
> I love the fix by @kcybulski but I needed to remove "$(" and ")" in line 17 like so:
> 
> ```
> #!/bin/bash
> 
> $(mkdir -p ./qtbase-abi-5-12-8-fix/DEBIAN)
> echo 'Package: qtbase-abi-5-12-8-fix
> Version: 1.0
> Section: custom
> Priority: optional
> Provides: qtbase-abi-5-12-8
> Depends: libqt5core5a
> Architecture: amd64
> Essential: no
> Installed-Size: 0
> Maintainer: custom
> Description: Fix lack of qtbase-abi-5-12-8 in KDE Neon
> ' > ./qtbase-abi-5-12-8-fix/DEBIAN/control
> 
> dpkg-deb --build ./qtbase-abi-5-12-8-fix
Using this hack the "Main Dialog" is not shown anymore in kde-neon (with version based on ubuntu 20.04)

**Comment by cyBea** [comment] 2022-12-11 15:54
Hi there! In lack of knowing a better place to post this:
I updated to kde-neon based on ubuntu 22.04 and the ugly + lucky "fix" works again:

repo:
```bash
cat /etc/apt/sources.list.d/nextcloud-client.list
deb http://ppa.launchpad.net/nextcloud-devs/client/ubuntu jammy main
```

script:
```bash
cat bin/nextcloud-desktop-dependency-workaround.sh 
#!/bin/bash

$(mkdir -p ./qtbase-abi-5-15-3-fix/DEBIAN)
echo 'Package: qtbase-abi-5-15-3-fix
Version: 1.0
Section: custom
Priority: optional
Provides: qtbase-abi-5-15-3
Depends: libqt5core5a
Architecture: amd64
Essential: no
Installed-Size: 0
Maintainer: custom
Description: Fix lack of qtbase-abi-5-15-3 in KDE Neon
' > ./qtbase-abi-5-15-3-fix/DEBIAN/control

dpkg-deb --build ./qtbase-abi-5-15-3-fix
```

create dummy-package:
```bash
bash bin/nextcloud-desktop-dependency-workaround.sh
```

installation:
```bash
sudo apt install ./qtbase-abi-5-15-3-fix.deb
sudo apt install dolphin-nextcloud
```

From a first glance everything seems to work (main-menu, settings window, dolphin file context menu). 😅️  But this will probably break again at some point 😪️
