### ISSUE TITLE
"Main window" is odd and does not work properly in GNOME

### ISSUE THREAD

**Issue by garrett** [nextcloud/desktop#3307] opened 2021-05-12 08:08 UTC
### Expected behaviour
Main window should act like other windows.

If it's intended to be a "popup", it should be launched like a popup (that is a click to make it appear) and it should actually pop up in the correct location, next to the icon (if available) where it was called from. And it shouldn't be launched from a menu item, if it's a "popup".

If it's intended to be window, it should act like other windows and be properly dismissable (× icon, either via a titlebar or client-side-decorations) as well.

I thought #2377 covered this, but it was mentioned in https://github.com/nextcloud/desktop/issues/2377#issuecomment-839533091, that the "main window" is something else. This has been a problem for years already, and I'm surprised it hasn't been fixed. (Has anyone on the NextCloud team actually tried using NextCloud on GNOME before?)

### Actual behaviour

Run NextCloud. The weird window pops up.

### Steps to reproduce
If there's no third party extension installed:

1. Run NextCloud desktop client in GNOME
2. Set it up
3. Quit NextCloud
4. Run NextCloud again
5. Weird window appears, nothing else happens
6. Click somewhere else, window goes away

If there is a third party extension ("KStatusNotifierItem/AppIndicator Support"):

1. Run NextCloud desktop client on GNOME
2. Set it up
3. Quit NextCloud client
4. Run NextCloud client again
5. There's an icon in the top right
6. Click on the icon
7. Select "Open main window"
8. An odd main window appears _in the middle of the screen_, with no titlebar
9. Click _anywhere else_ and it goes away... Also, if another window pops up (for any reason), this one goes away too.

Literally no other application acts like this, in either scenario (without the extension or with it).

### Client configuration
Client version: 
- 3.2.1 from Flathub
- 3.1.3 from Fedora

Operating system: Fedora 34, Silverblue version

OS language: English

Qt version used by client package (Linux only, see also Settings dialog): 5.15.2 on system. Unknown on Flathub version.

Client package (From Nextcloud or distro) (Linux only): Flathub and Fedora; both have issues.

**Comment by garrett** [comment] 2021-05-12 08:09
Whoops. Computer crashed (hardware issues) while filling out this issue and it ate some of the text. Fixed the title.

**Comment by garrett** [comment] 2021-05-12 08:20
I've been working around the issues for a while, but this issue is affecting other people's impression of Nextcloud. Look at the ratings in GNOME Software, for the Flathub version, for example:

![Screenshot from 2021-05-12 10-15-21](https://user-images.githubusercontent.com/10246/117942115-03851e80-b30b-11eb-891e-d6ac8c660223.png)

While it does work for some (I guess people using a KDE desktop?), it clearly isn't working for others. And it definitely isn't working at all for people using GNOME desktops, unless they install some arbitrary extension. And even then, it isn't working well.

I, like you all, would love for people to love the Nextcloud client. But as-is, it really is broken on GNOME desktops. :disappointed:

**Comment by FlexW** [comment] 2021-05-12 08:23
@jancborchardt Please also see my comment here why this might get never fixed https://github.com/nextcloud/desktop/issues/3307#issuecomment-839561172 .

**Comment by garrett** [comment] 2021-05-12 08:29
Copying @FlexW's comments over here:

https://github.com/nextcloud/desktop/issues/2377#issuecomment-839533091:
> It is expected that the main dialog has no window borders and it's not resizeable. The main dialog is thought as a tray popup, like the ones from OneDrive, Googe Sync and DropBox. I will close this issue.

https://github.com/nextcloud/desktop/issues/2377#issuecomment-839553141:
> @garrett There are two problems: Problem 1 is that GNOME dropped tray icon support, and if you have not installed the tray icon extension, the main dialog will pop up at random positions. Problem 2 is, if you are using Wayland, the main dialog will pop up at an arbitrary position even if you have installed the tray icon extension. That is because the client uses the global cursor position to find the place where it should open, and on Wayland there exists no concept of a global cursor position. Unfortunate, there is no other possibility on Linux to open a window at the position of the tray icon.
>
> These tray menus are something that is more common in the Windows world. As far as I know, this has been implemented in the Nextcloud client to align the client more with services like DropBox and OneDrive, to make it for (mostly Windows) users easier to transition. In think, a solution to this problem could be to make it configurable in the configuration file if the main dialog is a regular window (window borders, resizeable) or a tray popover. On Linux, I would default to setting the main dialog as a regular window due to the reason I mentioned above. As Ubuntu switched to Wayland per default lately, more and more people will stumble upon this problem.
@jancborchardt, any thoughts?

**Comment by garrett** [comment] 2021-05-12 08:39
> Problem 1 is that GNOME dropped tray icon support

_Years ago_. This isn't a new thing. It was intentional and they're not going to add it back.

> if you are using Wayland

Wayland has been the default for _years_ in many distributions. And those that were reluctant to switch have already switched by now or will switch soon as well.

The Nextcloud client should work "out of the box" on GNOME on Wayland in an expected manner. I've opened https://github.com/nextcloud/desktop/issues/3307. Apologies for sitting on this issue, thinking that it was referring to the same window.

But someone on the Nextcloud team should test the client in typical distributions, such as Fedora with GNOME. I understand that not every combination of wacky desktops on Linux can be tested, but GNOME and KDE are the biggest default desktops and both are shipped (in some way) by almost every distribution. It should work on both of these desktops by default, minimally.

**Comment by jancborchardt** [comment] 2021-05-12 10:35
@FlexW is it possible to check whether the client is launched via indicator icon or app launcher?
- When it’s started via indicator icon, it could stay like it is
- When it’s started via app launcher, it could start as a window

Or is that too complex?

**Comment by janvlug** [comment] 2021-05-12 10:55
Turning the main dialog into regular dialog by default on GNOME platforms would probably the best solution for that platform. There is already a pull request for that: #2649.

**Comment by FlexW** [comment] 2021-05-12 10:56
@jancborchardt That might be possible, but keep in mind that when the users use Wayland even if there are tray icons available on the system, the main dialog will still popup at a random position. That does not even look bad, but it makes the client also unusable because the main dialog closes as soon as the focus moves out of it. As @garrett already noted, Wayland is the future, and I think the majority of users use it already. For all this users the Nextcloud client is not really usable, or looks at best very broken.

I remember that we had a discussion while talking about the account wizard that after the account is configured, the main dialog pops up at the mouse cursor position instead of above/below the tray icon. This issue is also caused by the fact (and will most likley never been solved) that we can only use the cursor position as a reference point to open the main dialog on Linux. Thats really not a great first time experience.

**Comment by mgallien** [comment] 2021-05-12 11:14
Please @garrett and @jancborchardt I believe that this is mainly a design issue where what Nextcloud desktop is doing and what Gnome Desktop is doing somehow conflict.
Before doing any modifications on our side, the design should be agreed uppon by all relevant stakeholders. We will not just do something to revert it later because another platform has problem with the modified design.
Let's all try to come up with a solution that is working for all of us.
All the team will happily provide technical feedback like @FlexW already started doing.

**Comment by mgallien** [comment] 2021-05-12 11:16
> @FlexW is it possible to check whether the client is launched via indicator icon or app launcher?
> 
>     * When it’s started via indicator icon, it could stay like it is
> 
>     * When it’s started via app launcher, it could start as a window
> 
> 
> Or is that too complex?

As far as I understand, we can check if a tray host is running and act on that.
I am just unsure if that would be enough or if we would need to detect the desktop running and act based on that.

@garrett can people add Gnome extensions to add a tray or can we rely on Gnome being detected to know what to do ?

**Comment by garrett** [comment] 2021-05-12 11:40
People _can_ add extensions, but it's a third party one and there are a few different "tray" extensions. The one that works best is called "[KStatusNotifierItem/AppIndicator Support](https://extensions.gnome.org/extension/615/appindicator-support/)". I have it installed, but only specifically for Nextcloud, as the Nextcloud client is _completely_ broken without a tray at the moment.

But installing extensions is a "power user" thing. It requires one of the following:
- an unsandboxed browser (so browsers in Flatpaks don't work for this), with a browser extension installed ([for Firefox](https://addons.mozilla.org/en-US/firefox/addon/gnome-shell-integration/) or [for Chrome](https://chrome.google.com/webstore/detail/gnome-shell-integration/gphhapmejobijbbhgpjhcjognlahblep)) that talks to a natively installed package ("[chrome-gnome-shell](https://gitlab.gnome.org/GNOME/chrome-gnome-shell)")
- cloning a git repo of the extension and running some commands in a terminal
- using a distribution packaged version of an extension

(Managing extensions is handled by the "Extensions" app, but it does not provide a way to _install_ extensions.)

So you really cannot expect someone to even know that they need a notification area extension in the first place nor can you depend on someone having it installed.

I suggest you fire up a VM, install [Fedora 34 Workstation](https://getfedora.org/en/workstation/download/), and try to get Nextcloud working there. Ideally, you'd try to do this with Fedora's packaged version in an RPM _and_ also with the version from Flathub. (The experience is a little different for both.)

**Comment by mgallien** [comment] 2021-05-12 13:21
> I suggest you fire up a VM, install [Fedora 34 Workstation](https://getfedora.org/en/workstation/download/), and try to get Nextcloud working there. Ideally, you'd try to do this with Fedora's packaged version in an RPM _and_ also with the version from Flathub. (The experience is a little different for both.)

I will not do it because we are mostly talking about design issues and I am pretty bad at that and I have nice colleagues doing it for me.

I completely understand that there can be integration issues with Linux Desktops and not only Gnome. Fixing that wlll require a lot of care to details.

The flathub package is maintained by a third party. Should I expect some specific issues with it ?

I know by experience that one should spent time on the flathub packaging because you need to configure the sandboxing feature not to conflict with your software. You can still get issues because the portal dialogs are behaving a bit differently from normal dialogs (file picker, ...).

**Comment by garrett** [comment] 2021-05-12 15:05
> I will not do it now because we are mostly talking about design issues (not about crashes or things like that) and I am pretty bad at that.

My point is that it "crashes" from the point of view of someone trying to use it. It simply disappears from view and does not work.

> The flathub package is maintained by a third party. Should I expect some specific issues with it ?

The Flathub version doesn't have a way to hook into Nautilus. The Fedora version has a separate package to do so. They're similar if you don't install the Nautilus package. Plus, the Flathub version is more up to date, whereas the Fedora version is older at the moment.

For reference, here are the Fedora packages:

```
nextcloud-client-libs-3.1.3-1.fc34.x86_64
nextcloud-client-3.1.3-1.fc34.x86_64
nextcloud-client-nautilus-3.1.3-1.fc34.x86_64
```

(The libs package is installed by default, when either of both of the others are installed.)

And a lot of people are installing the client through the Flathub version too, so it's worth checking out for that reason alone. But, again, it shouldn't make much of a difference except for the reasons I mentioned above.

> sandboxing

The sandbox isn't really locked down much for the Nextcloud Desktop client, however. It has filesystem=host (which allows access to all system files) _in addition to_ `xdg-run/Nextcloud:create`.

But, still that's unrelated to any of the issues we're seeing when anyone tries to use the Nextcloud Desktop client software on GNOME... regardless of how it's packaged.

---

The problem is that you start it up, get the first run configuration window, fill out the details... and then it goes away and nothing happens. Then you try to run again and it goes away. It looks buggy and _feels like_ it crashed.

And even with the best case of working around this issue (through some know how and the ability to modify things), then the app window is still weird and problematic on GNOME.

If you or anyone else who works on Nextcloud would actually do a fresh install of Fedora (or any other distro that ships GNOME) in either a VM or a spare computer and try to set up Nextcloud, you'd immediately see the problems I'm talking about.

I've been working in FOSS for over two decades, am a designer+programmer, have been using Nextcloud for years (even back in the OwnCloud days) and love it... yet... the Nextcloud Desktop client is such a horrible experience on GNOME that I've recommended people don't even bother with it and use GNOME Online Acounts instead (which sets up a remote mount of davfs). This doesn't sync files at all, of course, and is slow, doesn't support offline, and so on. But it does work, unlike the desktop client.

I really want it to work though. I want it to be software I can fully and enthusiastically recommend.

**Comment by janvlug** [comment] 2021-05-12 16:59
> whereas the Fedora version is older at the moment.

A newer version will be available [soon](https://bodhi.fedoraproject.org/updates/FEDORA-2021-3ac334831c).

> I really want it to work though. I want it to be software I can fully and enthusiastically recommend.

The same for me, but it is really hard to explain someone who started using Nextcloud desktop after my recommendation on how to use it now.

**Comment by garrett** [comment] 2021-05-12 17:04
I set up a fresh VM for Fedora 34 and did a couple screencasts of a fresh experience on setting up the desktop client.

OK, let's start with the worst case scenario first. Here's a quick screencast of what the experience is like in GNOME with the version from Flathub:

https://user-images.githubusercontent.com/10246/118014715-cbee9480-b353-11eb-85c8-a013e90b75d9.mov


It's a little less bad with the Fedora version, as the client does now place a shortcut in the sidebar, with a lot of options:

https://user-images.githubusercontent.com/10246/118015428-8a121e00-b354-11eb-9cd4-d5a1496cbcd1.mov

But that's still not ideal.

**Comment by mgallien** [comment] 2021-06-07 14:03
@garrett 
so we had a meeting about how we can work on those issues
our plan is to switch to a dialog when we are on a Linux desktop where we are not reliably detecting a working systray host.
that means that on Gnome per default users will get an old fashion window to see the activity feed instead of a popup auto closing

we hope that will help people using our desktop client

as a second step we will work on issues when running a wayland desktop (first we want to be sure that the activity dialog is easy to use everywhere before working on that)

**Comment by jospoortvliet** [comment] 2021-06-23 12:20
@garrett you can try out the appimage in the PR: https://github.com/nextcloud/desktop/pull/3468

**Closed** 2021-07-12 14:18 UTC
Labels: approved, bug, design, feature: :cloud: system tray, os: :penguin: Linux

**Comment by gabrieleturchi** [comment] 2022-12-19 07:54
I still have the same problem, main window not opening, both on Fedora 36 and 37. The biggest problem is that I'm unable to add a new account. I honestly don't understand why, in setup window, there is not an "add account" button...
