### ISSUE TITLE
.htaccess files are not synchronized

### ISSUE THREAD

**Issue by phpdrill** [nextcloud/desktop#1155] opened 2019-03-23 15:55 UTC
### Expected behaviour
Nextcloud client should synchronize .htaccess files.

### Actual behaviour
.htaccess-files are not synchronized.

The client shows this error message:

> .htaccess: Server replied "500 Internal Server Error" to "PUT [server-path]/remote.php/dav/files/[user]/.htaccess" (OCP\Files\InvalidPathException)'

### Steps to reproduce
1. Put a .htaccess file in your Nextcloud directory.
2. Watch the Nextcloud client showing the above error message and refusing to sync the .htaccess file.

### Client configuration
Client version: Latest Github version (master)

Operating system: Windows 10 64 bit

OS language: German

Installation path of client: C:\Users\[user]\Nextcloud2

### Server configuration
Operating system: Debian 9

Web server: Apache2

Database: MariaDB

PHP version: 7.3.3

Nextcloud version: Latest Github version (master)

**Comment by caillou** [comment] 2019-03-23 17:41
I can confirm this bug from the OS X application.

<img width="316" alt="Screenshot 2019-03-23 at 18 12 28" src="https://user-images.githubusercontent.com/46739/54869589-2eaefb80-4d9b-11e9-8566-a6838f33bea4.png">

**Comment by michaelstingl** [comment] 2019-03-24 13:02
Related: https://github.com/nextcloud/desktop/issues/85 (duplicate?)

**Comment by caillou** [comment] 2019-03-24 16:26
@michaelstingl Yes, I would recommend closing this issue, as it is a duplicate of #85.

**Closed** 2021-07-13 14:08 UTC
