### ISSUE TITLE
Suddenly all local files removed (2.6.3)

### ISSUE THREAD

**Issue by MuellerSeb** [nextcloud/desktop#1801] opened 2020-02-21 17:21 UTC
### Expected behaviour
Sync files

### Actual behaviour
Nextcloud deleted all local files (OMG!)

### Steps to reproduce
1. sync with 2.6.2 on ubuntu 18.04
2. update to 2.6.3
3. all local files were instantly removed from the local storage

### Client configuration
Client version:
2.6.3

Operating system:
ubuntu 18.04

OS language:
german

Qt version used by client package (Linux only, see also Settings dialog):
5.9.5

### PS:
updating to 2.7.0 beta does not help, since it is crashing randomly after a few seconds with a core-dump (Some "PROPFIND" warnings in the log, nothing more)
EDIT: the last message in the log with 2.7.0 is:

    [OCC::SocketListener::sendMessage 	Sending SocketAPI message --> "GET_MENU_ITEMS:BEGIN" to QLocalSocket(0x7fe4380a1fc0)

then just the core-dump.

I tried to delete the connected account to reconfigure it and download the files from server again (with 2.6.3) but there I just get HTTP erros:

    "Es hat sich ein HTTP-Übertragungsfehler ereignet. Bei der Server-Dateierkennungsantwort fehlen Daten."

meaning:

    "The server file discovery reply is missing data."

This is maybe related to #819

**Comment by misch7** [comment] 2020-03-02 02:59
Which version of the NC server do you use?

I'd recommend to upgrade to NC 18 anyway, there has been a similar issue with NC 17 with a server DB corruption involved that got fixed in 18. From the client side, #1721 should have fixed the missing data / HTTP error issue.

**Comment by NicolasGoeddel** [comment] 2020-04-04 17:29
I just had a very similar issue. The client (v2.6.4) on Ubuntu 18.04 deleted 44 GB of data in around 60000 folders. I guess that at the same time the root partition ran out of space because of log files which were not rotated. But the synced data is saved on an other mount so there should be absolutely no issue.

The biggest issue now is the slowness. It sends a `PROPFIND` command for every folder to the server at around 6 request per second. On the server side I can see that in the `access.log` from Apache. And it seems the client wants to first discover all these 60000 folders until it decides to even begin syncing. I really hope this will not happen again. Is there already a feature request for a faster discovery? Why even send so many request? Why not just ask the server in one call for all the files recursively?

**Comment by er-vin** [comment] 2021-01-05 09:19
Duplicate of #1433

**Closed by er-vin** 2021-01-05 09:19 UTC
Labels: approved, bug, feature: :arrows_counterclockwise: sync engine
