### ISSUE TITLE
[Bug]: Tray popup suddenly misaligned

### ISSUE THREAD

**Issue by barkawa** [nextcloud/desktop#5319] opened 2023-01-09 18:52 UTC
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

After waking from suspend, I clicked on the tray icon and saw this. Then i killed and restarted Nextcloud and it was fine again.

<img width="886" alt="Bildschirmfoto 2023-01-08 um 22 47 43" src="https://user-images.githubusercontent.com/23111152/211382947-d024e282-ec0a-4731-82b0-71fd22f7146a.png">
...

### Steps to reproduce

I could not reproduce the bug. My best guess is, it had something to do with switching to a multi-monitor setup while Nextcloud is running.
...

### Expected behavior

When clicking on the tray icon, the tray popup should be aligned and usable.
...

### Which files are affected by this bug

2023-01-07 13-22.pdf

### Operating system

Mac OS

### Which version of the operating system you are running.

macOS 12.6

### Package

Other

### Nextcloud Server version

25.0.1

### Nextcloud Desktop Client version

3.6.4

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 3.4.2 to 3.4.4)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [X] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Nextcloud Server logs

```shell
I'm using a managed provider and can't get the logs.
```

### Additional info

I'm using a rMBP 2015 13'' connected via HDMI to a 1080p display.
[debug_archive.zip](https://github.com/nextcloud/desktop/files/10376032/debug_archive.zip)

**Comment by claucambra** [comment] 2023-01-10 15:56
This is a duplicate of #5268 so closing

**Closed by claucambra** 2023-01-10 15:56 UTC
Labels: 0. Needs triage
