### ISSUE TITLE
[Bug]: Nextcloud Client corrupting Harddrives (SSD) - Severe Bug?

### ISSUE THREAD

**Issue by q2apro** [nextcloud/desktop#6364] opened 2024-01-19 10:02 UTC
- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

Nextcloud starts with Windows. Starting full resynchronization process. Harddrive shows up as corrupted in Windows. No access to Harddrive and thus no sync is possible anymore (please read details below).

### Steps to reproduce

1. Have two SSDs (NTFS) in your system (one is 2TB, one is 4TB).
2. Use the system for a few months.
3. Turn your computer off for several days (shut down).
4. Work on another computer remotely, that syncs to the server too.
5. Start your main computer.
6. There is a chance that one of the harddrives shows up as "corrupted" and cannot be accessed anymore. 

![image](https://github.com/nextcloud/desktop/assets/6764548/eb3dc078-c3a6-4a65-b137-0aeadb44f0ea)

> Scan drive for errors

Forcing you to use fchdsk on next start which takes about 8 hours to fix the corrupted sectors!

Something similar has been reported at (but there with USB): https://www.reddit.com/r/NextCloud/comments/111o5pu/filesystem_corruption_due_to_nextcloud_am_i_the/)

Connection at my computer is SATA.

⚠️ After the first occurence of this "corrupted data" two months ago I bought a new 2 TB SSD and replaced the 2 TB SSD in my computer. Then I restarted Windows and Nextcloud started to sync/copy the server files to the SSD. After a few hours the same error showed up again. It was a brand new SSD!

⚠️ Once the error showed up on the 2 TB and a month later it happened on the 4TB.

⚠️ There were always files lost. I could see it with the "sync conflict" of the Nextcloud client. It showed the "local version" of the file with `0 MB` and the server version with data.

In my opinion it is definitely the Nextcloud desktop client that writes in some way that the SSDs (NTFS) get corrputed.

**SEVERE BUG**

### Expected behavior

---

### Which files are affected by this bug

several local files

### Operating system

Windows

### Which version of the operating system you are running.

Windows 10

### Package

Appimage

### Nextcloud Server version

27.1.5

### Nextcloud Desktop Client version

3.11.0

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Enabled

**Comment by marcotrevisan** [comment] 2024-01-19 11:52
Hi @q2apro The Nextcloud Desktop can only use the operating system's usermode API to write files, how can such kind of usage cause a corruption at file system level?

Can you exclude, for example, the following cause: your SATA cable/connector is slightly damaged (perhaps not visibly) and Nextcloud is using your drive more often than the other apps, so when your hardware problem is causing corruption it will likely happen on Nextcloud data? This possible cause is perfectly fit for your steps to reproduce and the observed effects, and has higher chances to be true than a user app corrupting the filesystem.

Unfortunately your steps to reproduce won't systematically determine the described effect.

I hope this helps

**Comment by marcotrevisan** [comment] 2024-01-19 14:24
Thanks for your sharing! You might as well try to configure Nextcloud Desktop's synchronization folder to be in another disk i.e. the main disk, that may also help speeding up your troubleshooting.
Last but not least, I know I may sound paranoic but I would add 3.5" to 2.5" adapters for those two SSD's, I know they're solid state drives but you never know 🤞

**Comment by joshtrichards** [comment] 2024-01-20 16:25
> Something similar has been reported at (but there with USB):

That other situation that was reported did turn out to be a hardware/local configuration issue. It was not the Desktop client.

**Comment by q2apro** [comment] 2024-01-31 18:45
Just wanted to report back that I did not turn off the socket/electricity, came back after 10 days, turned on the PC and the SSDs worked.

It could be that the issue is related to: https://www.reddit.com/r/buildapc/comments/14ib1v0/power_went_out_while_gaming_now_my_ssd_doesnt/

For anyone having some SSD issue, try:

> Power off the PC.
> Unplug the power cord from the power socket.
> Press power button for few seconds to drain all the residual power stored in the capacitors.
> Plug the cable back and power the PC now and check.

Next I will turn off the PC completely (also unplug the socket) and report back in two weeks if the error above happened again.

**Comment by q2apro** [comment] 2024-02-01 06:32
Update: 

In the evening I let the computer running, Nextcloud said the sync will take 5 hours.

The next morning I returned to the computer and see the Windows error message again: "Scan drive for errors"

Nextcloud was not running anymore. So I think Windows updated over night and restarted.

This morning I have changed the two SATA cables. Restarted the computer. 

I will report back.

**Comment by q2apro** [comment] 2024-02-01 07:17
And here is the Nextcloud sync log just before the other log file (which started `2024-01-31 21:56:38:453`):

```
2024-01-31 21:56:38:082 [ info nextcloud.sync.propagator.root.directory C:\Users\User\AppData\Local\Temp\windows-19197\client-building\desktop\src\libsync\owncloudpropagator.cpp:1525 ]:	OCC::SyncFileItem::Success slotSubJobsFinished OCC::PropagatorJob::Running pending uploads 0 subjobs state OCC::PropagatorJob::Finished
2024-01-31 21:56:38:085 [ info nextcloud.sync.propagator.root.directory C:\Users\User\AppData\Local\Temp\windows-19197\client-building\desktop\src\libsync\owncloudpropagator.cpp:1501 ]:	scheduleSelfOrChild OCC::PropagatorJob::Running pending uploads 0 subjobs state OCC::PropagatorJob::Finished
2024-01-31 21:56:38:085 [ info nextcloud.sync.propagator C:\Users\User\AppData\Local\Temp\windows-19197\client-building\desktop\src\libsync\owncloudpropagator.h:220 ]:	Starting CSyncEnums::CSYNC_INSTRUCTION_REMOVE propagation of "Portables/VLCPortable/App/vlc/lua/meta/fetcher" by OCC::PropagateLocalRemove(0x233fb48efc0)
2024-01-31 21:56:38:085 [ info nextcloud.sync.propagator.localremove C:\Users\User\AppData\Local\Temp\windows-19197\client-building\desktop\src\libsync\propagatorjobs.cpp:94 ]:	Start propagate local remove job
2024-01-31 21:56:38:085 [ info nextcloud.sync.propagator.localremove C:\Users\User\AppData\Local\Temp\windows-19197\client-building\desktop\src\libsync\propagatorjobs.cpp:102 ]:	Going to delete: "D:/Portables/VLCPortable/App/vlc/lua/meta/fetcher"
2024-01-31 21:56:38:085 [ warning nextcloud.sync.filesystem C:\Users\User\AppData\Local\Temp\windows-19197\client-building\desktop\src\libsync\filesystem.cpp:176 ]:	Error removing folder "D:/Portables/VLCPortable/App/vlc/lua/meta/fetcher"
2024-01-31 21:56:38:085 [ warning nextcloud.sync.propagator C:\Users\User\AppData\Local\Temp\windows-19197\client-building\desktop\src\libsync\owncloudpropagator.cpp:286 ]:	Could not complete propagation of "Portables/VLCPortable/App/vlc/lua/meta/fetcher" by OCC::PropagateLocalRemove(0x233fb48efc0) with status OCC::SyncFileItem::NormalError and error: "Could not remove folder \"D:\\Portables\\VLCPortable\\App\\vlc\\lua\\meta\\fetcher\""
2024-01-31 21:56:38:088 [ warning nextcloud.gui.activity C:\Users\User\AppData\Local\Temp\windows-19197\client-building\desktop\src\gui\tray\usermodel.cpp:878 ]:	Item  "Portables/VLCPortable/App/vlc/lua/meta/fetcher"  retrieved resulted in  "Could not remove folder \"D:\\Portables\\VLCPortable\\App\\vlc\\lua\\meta\\fetcher\""
2024-01-31 21:56:38:088 [ warning nextcloud.gui.activity C:\Users\User\AppData\Local\Temp\windows-19197\client-building\desktop\src\gui\tray\usermodel.cpp:840 ]:	Item  "Portables/VLCPortable/App/vlc/lua/meta/fetcher"  retrieved resulted in error  "Could not remove folder \"D:\\Portables\\VLCPortable\\App\\vlc\\lua\\meta\\fetcher\""
2024-01-31 21:56:38:105 [ info nextcloud.sync.propagator C:\Users\User\AppData\Local\Temp\windows-19197\client-building\desktop\src\libsync\owncloudpropagator.cpp:1384 ]:	PropagateDirectory::slotFirstJobFinished emit finished OCC::SyncFileItem::NormalError
2024-01-31 21:56:38:105 [ info nextcloud.sync.propagator C:\Users\User\AppData\Local\Temp\windows-19197\client-building\desktop\src\libsync\owncloudpropagator.cpp:1580 ]:	PropagateRootDirectory::slotDirDeletionJobsFinished emit finished OCC::SyncFileItem::NormalError
2024-01-31 21:56:38:124 [ info nextcloud.sync.engine C:\Users\User\AppData\Local\Temp\windows-19197\client-building\desktop\src\libsync\syncengine.cpp:983 ]:	Sync run took  63245 ms
2024-01-31 21:56:38:128 [ info nextcloud.gui.folder C:\Users\User\AppData\Local\Temp\windows-19197\client-building\desktop\src\gui\folder.cpp:1159 ]:	Client version 3.11.0stable-Win64 (build 20231211)  Qt 5.15.10  SSL  OpenSSL 3.1.3 19 Sep 2023
2024-01-31 21:56:38:128 [ warning nextcloud.gui.folder C:\Users\User\AppData\Local\Temp\windows-19197\client-building\desktop\src\gui\folder.cpp:1166 ]:	SyncEngine finished with ERROR
2024-01-31 21:56:38:133 [ debug com.nextcloud.owncloudgui C:\Users\User\AppData\Local\Temp\windows-19197\client-building\desktop\src\gui\owncloudgui.cpp:410 ]	[ OCC::ownCloudGui::slotShowTrayMessage ]:	Going to show notification with title: ' "Sync Activity" ' and message: ' "Portables\\VLCPortable\\App\\vlc\\lua\\meta\\fetcher could not be synced due to an error. See the log for details." '
2024-01-31 21:56:38:136 [ info nextcloud.gui.folder C:\Users\User\AppData\Local\Temp\windows-19197\client-building\desktop\src\gui\folder.cpp:412 ]:	Folder "" sync result:  OCC::SyncResult::SyncRunning
2024-01-31 21:56:38:136 [ info nextcloud.gui.folder C:\Users\User\AppData\Local\Temp\windows-19197\client-building\desktop\src\gui\folder.cpp:1195 ]:	the last 2 syncs failed
2024-01-31 21:56:38:137 [ info nextcloud.gui.application C:\Users\User\AppData\Local\Temp\windows-19197\client-building\desktop\src\gui\owncloudgui.cpp:233 ]:	Sync state changed for folder  "https://nx12345.your-storageshare.de/remote.php/dav/files/Nextcloud-Drive-Storage/Volume-D" :  "Error"
```

> SyncEngine finished with ERROR

**Comment by q2apro** [comment] 2024-02-01 13:46
And besides, the 139 error messages Nextcloud throws and says "Could not remove folder".

Here are etries from the log:

```
2024-02-01 15:39:36:539 [ info nextcloud.sync.propagator.localremove C:\Users\User\AppData\Local\Temp\windows-20060\client-building\desktop\src\libsync\propagatorjobs.cpp:94 ]:	Start propagate local remove job
2024-02-01 15:39:36:539 [ info nextcloud.sync.propagator.localremove C:\Users\User\AppData\Local\Temp\windows-20060\client-building\desktop\src\libsync\propagatorjobs.cpp:102 ]:	Going to delete: "E:/Pictures/Favorite Photos"
2024-02-01 15:39:36:539 [ warning nextcloud.sync.filesystem C:\Users\User\AppData\Local\Temp\windows-20060\client-building\desktop\src\libsync\filesystem.cpp:176 ]:	Error removing folder "E:/Pictures/Favorite Photos"
2024-02-01 15:39:36:539 [ warning nextcloud.sync.propagator C:\Users\User\AppData\Local\Temp\windows-20060\client-building\desktop\src\libsync\owncloudpropagator.cpp:286 ]:	Could not complete propagation of "Pictures/Favorite Photos" by OCC::PropagateLocalRemove(0x249991a0460) with status OCC::SyncFileItem::NormalError and error: "Could not remove folder \"E:\\Pictures\\Favorite Photos\""
2024-02-01 15:39:36:539 [ warning nextcloud.gui.activity C:\Users\User\AppData\Local\Temp\windows-20060\client-building\desktop\src\gui\tray\usermodel.cpp:878 ]:	Item  "Pictures/Favorite Photos"  retrieved resulted in  "Could not remove folder \"E:\\Pictures\\Favorite Photos\""
2024-02-01 15:39:36:539 [ warning nextcloud.gui.activity C:\Users\User\AppData\Local\Temp\windows-20060\client-building\desktop\src\gui\tray\usermodel.cpp:840 ]:	Item  "Pictures/Favorite Photos"  retrieved resulted in error  "Could not remove folder \"E:\\Pictures\\Favorite Photos\""
2024-02-01 15:39:36:539 [ info nextcloud.sync.propagator C:\Users\User\AppData\Local\Temp\windows-20060\client-building\desktop\src\libsync\owncloudpropagator.cpp:1384 ]:	PropagateDirectory::slotFirstJobFinished emit finished OCC::SyncFileItem::NormalError
 
2024-02-01 15:39:36:543 [ info nextcloud.sync.propagator C:\Users\User\AppData\Local\Temp\windows-20060\client-building\desktop\src\libsync\owncloudpropagator.h:220 ]:	Starting CSyncEnums::CSYNC_INSTRUCTION_REMOVE propagation of "Pictures/2024/Whatsapp/WhatsApp Voice Notes" by OCC::PropagateLocalRemove(0x249991a0be0)
2024-02-01 15:39:36:543 [ info nextcloud.sync.propagator.localremove C:\Users\User\AppData\Local\Temp\windows-20060\client-building\desktop\src\libsync\propagatorjobs.cpp:94 ]:	Start propagate local remove job
2024-02-01 15:39:36:543 [ info nextcloud.sync.propagator.localremove C:\Users\User\AppData\Local\Temp\windows-20060\client-building\desktop\src\libsync\propagatorjobs.cpp:102 ]:	Going to delete: "E:/Pictures/2024/Whatsapp/WhatsApp Voice Notes"
2024-02-01 15:39:36:543 [ warning nextcloud.sync.filesystem C:\Users\User\AppData\Local\Temp\windows-20060\client-building\desktop\src\libsync\filesystem.cpp:176 ]:	Error removing folder "E:/Pictures/2024/Whatsapp/WhatsApp Voice Notes"
2024-02-01 15:39:36:543 [ warning nextcloud.sync.propagator C:\Users\User\AppData\Local\Temp\windows-20060\client-building\desktop\src\libsync\owncloudpropagator.cpp:286 ]:	Could not complete propagation of "Pictures/2024/Whatsapp/WhatsApp Voice Notes" by OCC::PropagateLocalRemove(0x249991a0be0) with status OCC::SyncFileItem::NormalError and error: "Could not remove folder \"E:\\Pictures\\2024\\Whatsapp\\WhatsApp Voice Notes\""
2024-02-01 15:39:36:544 [ warning nextcloud.gui.activity C:\Users\User\AppData\Local\Temp\windows-20060\client-building\desktop\src\gui\tray\usermodel.cpp:878 ]:	Item  "Pictures/2024/Whatsapp/WhatsApp Voice Notes"  retrieved resulted in  "Could not remove folder \"E:\\Pictures\\2024\\Whatsapp\\WhatsApp Voice Notes\""
2024-02-01 15:39:36:544 [ warning nextcloud.gui.activity C:\Users\User\AppData\Local\Temp\windows-20060\client-building\desktop\src\gui\tray\usermodel.cpp:840 ]:	Item  "Pictures/2024/Whatsapp/WhatsApp Voice Notes"  retrieved resulted in error  "Could not remove folder \"E:\\Pictures\\2024\\Whatsapp\\WhatsApp Voice Notes\""
 
2024-02-01 15:39:36:618 [ warning nextcloud.sync.propagator C:\Users\User\AppData\Local\Temp\windows-20060\client-building\desktop\src\libsync\owncloudpropagator.cpp:286 ]:	Could not complete propagation of "Pictures/2023/2023-08/WhatsApp Video" by OCC::PropagateLocalRemove(0x2499930a490) with status OCC::SyncFileItem::NormalError and error: "Could not remove folder \"E:\\Pictures\\2023\\2023-08\\WhatsApp Video\\Private\", Could not remove folder \"E:\\Pictures\\2023\\2023-08\\WhatsApp Video\\Sent\""
2024-02-01 15:39:36:618 [ warning nextcloud.gui.activity C:\Users\User\AppData\Local\Temp\windows-20060\client-building\desktop\src\gui\tray\usermodel.cpp:878 ]:	Item  "Pictures/2023/2023-08/WhatsApp Video"  retrieved resulted in  "Could not remove folder \"E:\\Pictures\\2023\\2023-08\\WhatsApp Video\\Private\", Could not remove folder \"E:\\Pictures\\2023\\2023-08\\WhatsApp Video\\Sent\""
2024-02-01 15:39:36:618 [ warning nextcloud.gui.activity C:\Users\User\AppData\Local\Temp\windows-20060\client-building\desktop\src\gui\tray\usermodel.cpp:840 ]:	Item  "Pictures/2023/2023-08/WhatsApp Video"  retrieved resulted in error  "Could not remove folder \"E:\\Pictures\\2023\\2023-08\\WhatsApp Video\\Private\", Could not remove folder \"E:\\Pictures\\2023\\2023-08\\WhatsApp Video\\Sent\""
2024-02-01 15:39:36:618 [ info nextcloud.sync.propagator C:\Users\User\AppData\Local\Temp\windows-20060\client-building\desktop\src\libsync\owncloudpropagator.cpp:1384 ]:	PropagateDirectory::slotFirstJobFinished emit finished OCC::SyncFileItem::NormalError
2024-02-01 15:39:36:637 [ info nextcloud.sync.propagator.root.directory C:\Users\User\AppData\Local\Temp\windows-20060\client-building\desktop\src\libsync\owncloudpropagator.cpp:1501 ]:	scheduleSelfOrChild OCC::PropagatorJob::Running pending uploads 0 subjobs state OCC::PropagatorJob::Finished
2024-02-01 15:39:36:637 [ info nextcloud.sync.propagator C:\Users\User\AppData\Local\Temp\windows-20060\client-building\desktop\src\libsync\owncloudpropagator.h:220 ]:	Starting CSyncEnums::CSYNC_INSTRUCTION_REMOVE propagation of "Pictures/2023/2023-08/WhatsApp Images" by OCC::PropagateLocalRemove(0x24999309170)
```

How to fix this issue?

**Comment by mgallien** [comment] 2024-02-01 15:37
@q2apro 
I may kindly suggest to try asking for help in https://help.nextcloud.com where you have more chance of getting help
as others said, this is very unlikely a bug from desktop client
I have been syncing lots of files on very active servers for ages with SSD without having ever encountered any issue
To conclude, I am sorry for your trouble and really hope people can help you recover :blue_heart:

**Comment by mgallien** [comment] 2024-02-01 15:38
I prefer closing this issue as I believe this is more a request for help (and I know people are actively helping on the forum)
I am unconvinced this is a bug at the level of desktop client

**Closed by mgallien** 2024-02-01 15:37 UTC
Labels: discussion

**Comment by marcotrevisan** [comment] 2024-02-02 10:03
@q2apro as a side note: from the error messages you posted, looks like you're syncing also some app's internal folders (for instance: _"D:\\Portables\\VLCPortable\\App\\vlc\\lua\\meta\\fetcher\"_). 
This is generally not a good idea as the apps may keep their files open, and they may get corrupted when their work folders are touched by other processes. I'd avoid syncing an entire disk (even if it's an external one) or an entire user's folder. Much better setting a dedicated Nextcloud data folder and use that as a root for synchronization.
Also, it's worth noting that a given folder should never be synced by more than one sync service.
