### ISSUE TITLE
This client is still a headache when your users have thousands of files.

### ISSUE THREAD

**Issue by wmeneses** [nextcloud/desktop#6501] opened 2024-03-01 17:03 UTC
Unfortunately I have to synchronize thousands of files and hundreds of folders despite having a great architecture, it is almost impossible to keep customers happy with this client.

Why does it just work at least like the android version?
Why does the user have to wait hours for his files to show up (3 hours for 380,000 documents)?

I have gone out to buy webdav (webdrive) clients (I have to do it because microsoft little by little wants to kill the webadav service)...so the users don't have to wait. please consider not doing that sync just show the files and that's it like Google Drive does. and don't come to tell me that google is google, I have tried nextcloud in clusters with redis SDD S3 and how much stuff there is, but I see that this client is simply supremely slow.

**Comment by marcotrevisan** [comment] 2024-03-02 10:48
The Mac OS implementation is going to change in favor of a FileProvider approach, which changes things radically but unfortunately that API is available on MacOS only.
That said, I think the root cause of this issue was the initial approach, which seems to have been more like “wrapping rsync” (good for machine-to-machine) rather than decorating a caching proxy and expose that as a “network drive” of some kind (better choice for machine-to-human).

On the good side, it also seems like much has been done to ease rough edges out.
Hopefully we’ll soon see a more minimalistic approach in syncing, where the local dataset and the impact of a change will be kept minimal and only a fraction of the folder structure is kept in sync.

One step in that direction would be having a right-click mouse action  (available in virtual drive mode too) on folders and be able to remove that folder (and its contents) from sync, leaving it grayed (plus an “add” right-click action available) instead of having to do that in a config panel; that alone would drastically reduce the problems. Automate that using a lazy approach and you’re done…

**Comment by wmeneses** [comment] 2024-03-02 12:18
Well I wish, I still defend this kind of products, but when you face so many problems you think about going back to google, you end up investing more money in infrastructure, storage to guarantee a good service.

**Comment by marcotrevisan** [comment] 2024-03-02 13:03
This is related to #4424

**Comment by joshtrichards** [comment] 2024-08-16 23:39
From the sounds of it, this is a duplicate of #4424. If not, @wmeneses, please clarify and I'll re-open.

**Closed by joshtrichards** 2024-08-16 23:39 UTC
Labels: enhancement, feature: :minidisc: virtual filesystem

**Comment by joshtrichards** [comment] 2024-08-16 23:40
Duplicate of #4424
