### ISSUE TITLE
[Bug]: Setting expiration date not working - date entry not possible

### ISSUE THREAD

**Issue by theCreativeMind-mrTP** [nextcloud/desktop#4453] opened 2022-04-21 13:29 UTC
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

setting share expiry from right click menu not possible 

### Steps to reproduce

1. Right click on the file
2. Click on Share Options
3. set expiration date - here the date picker is buggy 
...

### Expected behavior

it should work!!!!

### Which files are affected by this bug

all the files

### Operating system

Mac OS

### Which version of the operating system you are running.

latest

### Package

Appimage

### Nextcloud Server version

enterprise version ... 22.2.5

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [X] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Additional info

Nextcloud is already annoys me to no end ... dropbox wannabe, yet there is not even a solid sync function existing ... is it version 0.0.0.1 pre-alpha ... no ... its version 22.2.5 ... ridiculous.

**Comment by tstreibl** [comment] 2022-05-08 16:24
see #4068 
see #4327 
still not solved

**Comment by claucambra** [comment] 2022-05-16 16:40
Hi, since this issue is a duplicate of #4068 I will close it, but thanks for reporting

**Closed by claucambra** 2022-05-16 16:40 UTC
Labels: 0. Needs triage
