### ISSUE TITLE
client 2.5.0 doesnt not show updates availables.

### ISSUE THREAD

**Issue by stratege1401** [nextcloud/desktop#1002] opened 2019-01-09 02:26 UTC
![ncw1](https://user-images.githubusercontent.com/8655165/50872030-1fd0c380-13be-11e9-894d-a6d37b8f2a84.jpg)
  v2.5.1 is now consider "released" version on https://nextcloud.com/install/#install-clients
but v2.5.0 show no updates available...

might be wrong as i dont remeber if iused daily build or mainstream build, but worth signaling it

**Comment by splitt3r** [comment] 2019-01-09 06:49
Looks like the update server still serves https://github.com/nextcloud/client_updater_server/blob/master/config/config.php

**Comment by MichaelDwucet** [comment] 2019-01-13 11:04
My Desktop Client 2.3.3.1 also reports that no updates are available.   
So I assume all your Windows clients have not received an automatic update the last year!

**Comment by stratege1401** [comment] 2019-02-04 18:38
@MichaelDwucet unfortunatly, yes.

-  
2.5.1 is out now. Please, consider this thread as close.

**Comment by GieltjE** [comment] 2019-02-18 12:49
Duplicate of #927 ?

**Comment by benbrummer** [comment] 2019-04-12 04:24
Have this problem on all our systems for month now. No matter which version number is installed, no new update is available. 2.5.2 is released. 2.5.1 shows no update.

**Comment by t-b-x** [comment] 2019-04-17 12:35
> 
> 
> Have this problem on all our systems for month now. No matter which version number is installed, no new update is available. 2.5.2 is released. 2.5.1 shows no update.

subscribe. same here.

**Comment by t-b-x** [comment] 2019-05-03 07:22
any comments on this? no one?

**Comment by e-alfred** [comment] 2019-05-08 10:12
This is a problem of the Nextcloud Client. It does not notify the user if a new version is available for download which is not good because people run outdated clients on their systems without ever noticing that they should update.

**Comment by jonathanmmm** [comment] 2019-05-09 18:02
Same Problem here

**Comment by StefvanEgmond** [comment] 2019-05-30 16:44
Same issue here with 2.5.1final

**Comment by jonathanmmm** [comment] 2019-05-30 17:40
@rullzer

Can you help, please?
Can you give any information? Do you know who is the right person for this problem?


We don't know what is going on, seems like these issues are ignored. Maybe they are more important problems right now, but having clients on as old as 2.3.3 is security wise not good. Clients should be always up to date or it should be possible to control as the admin if the clients get updates and if which version (like stable, only 2.4 or something like that).

**Comment by stanelie** [comment] 2019-08-21 14:51
2.5.2 shows "No updates available", while 2.5.3 is available at https://nextcloud.com/install/#install-clients

It's been an ongoing issue for a while now, we are now in august.

**Comment by stanelie** [comment] 2019-08-21 14:56
Duplicate of https://github.com/nextcloud/desktop/issues/1255 ?

**Comment by t-b-x** [comment] 2019-09-19 12:53
can confirm, same for 2.5.2 -> 2.5.3

**Comment by jonathanmmm** [comment] 2019-09-19 13:21
I have updated from 2.3.x to 2.5.x and I got erros and such, so I downgraded again. Maybe the reason is that 2.5.x is just not the production stable version.

**Comment by misch7** [comment] 2019-09-19 13:57
Hey, we discovered the error is on the update server. We'll fix it when we release the 2.6 stable version. Since it will be released soon we decided to skip the 2.5.3 for now since there seem to have been quite a few issues with it.

In the meantime you may try our 2.6 RC1, your problems might have been solved already:

**2.6 RC1 download links:**

_Linux_
https://download.nextcloud.com/desktop/prereleases/Linux/Nextcloud-2.6.0.20190906-rc1-x86_64.AppImage

_Mac_
https://download.nextcloud.com/desktop/prereleases/Mac/Nextcloud-qt5.9.2-2.6.0.20190907rc1.pkg

_Windows_
https://download.nextcloud.com/desktop/prereleases/Windows/nextcloud-2.6.0.5818-rc1-20190907.exe

**Comment by misch7** [comment] 2019-10-05 11:47
The updates are working now again, see: https://github.com/nextcloud/desktop/issues/927#issuecomment-538642639

So I'm closing this here :-)

**Closed by misch7** 2019-10-05 11:47 UTC
Labels: feature: :inbox_tray: install and update
