### ISSUE TITLE
[Bug]: Flatpak Nextcloud desktop client in Linux refuses to start without prompting an error message in UI

### ISSUE THREAD

**Issue by osbama** [nextcloud/desktop#5610] opened 2023-04-17 06:21 UTC
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

## Nextcloud desktop client in Linux refuses to start without prompting an error message in UI

I am using Nextcloud desktop client on PopOs, through flatpak. Often, the application refuses to start for various reasons. This time it is `Could not initialize GLX`. The big problem is that this information is not presented in UI when launching the application (I had to use flatpak to reach this information). Hence I often I am not aware the nextcloud desktop client is not running. This wreaks havoc in our shared workspace files with my colleagues. 

### Steps to reproduce

`flatpak run com.nextcloud.desktopclient.nextcloud` 

```
qt.glx: qglx_findConfig: Failed to finding matching FBConfig for QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(ResetNotification), depthBufferSize -1, redBufferSize 1, greenBufferSize 1, blueBufferSize 1, alphaBufferSize -1, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::SingleBuffer, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile)
qt.glx: qglx_findConfig: Failed to finding matching FBConfig for QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(ResetNotification), depthBufferSize -1, redBufferSize 1, greenBufferSize 1, blueBufferSize 1, alphaBufferSize -1, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::SingleBuffer, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile)
Could not initialize GLX
```
(This is silent and no information is presented in GUI) 

### Expected behavior

If the application fails to initialize, I expect an error message drawn in my GUI, so that I am aware of the synchronisation issues. 

### Which files are affected by this bug

Everything

### Operating system

Linux

### Which version of the operating system you are running.

PopOs 22.04 LTS

### Package

Distro package manager

### Nextcloud Server version

23.0.1

### Nextcloud Desktop Client version

3.8.9

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Enabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by mat-l** [comment] 2024-01-11 12:37
+1 on Ubuntu 20.04

$ flatpak install flathub com.nextcloud.desktopclient.nextcloud
Looking for matches…

com.nextcloud.desktopclient.nextcloud permissions:
    ipc                     network       wayland       x11      dri      file access [1]      dbus access [2]
    bus ownership [3]

    [1] host, xdg-config/kdeglobals:ro, xdg-run/Nextcloud:create
    [2] com.canonical.AppMenu.Registrar, org.freedesktop.Notifications, org.freedesktop.secrets, org.kde.KGlobalSettings, org.kde.StatusNotifierWatcher,
        org.kde.kconfig.notify, org.kde.kwalletd5
    [3] com.nextcloudgmbh.Nextcloud


        ID                                                       Branch             Op            Remote             Download
 1. [✓] com.nextcloud.desktopclient.nextcloud.Locale             stable             i             flathub             6.8 kB / 61.1 MB
 2. [✓] com.nextcloud.desktopclient.nextcloud                    stable             i             flathub            76.1 MB / 77.9 MB

Installation complete.

$ flatpak run com.nextcloud.desktopclient.nextcloud
qt.glx: qglx_findConfig: Failed to finding matching FBConfig for QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(ResetNotification), depthBufferSize -1, redBufferSize 1, greenBufferSize 1, blueBufferSize 1, alphaBufferSize -1, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::SingleBuffer, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile)
qt.glx: qglx_findConfig: Failed to finding matching FBConfig for QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(ResetNotification), depthBufferSize -1, redBufferSize 1, greenBufferSize 1, blueBufferSize 1, alphaBufferSize -1, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::SingleBuffer, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile)
Could not initialize GLX

**Comment by Kleisli** [comment] 2024-02-12 21:20
I had the same problem, the cause was that the excact version of the nvidia driver used by Ubuntu didn't match the version used by flatpack / org.freedesktop.Platform.GL. 

I could fix it following the steps described here https://pled.fr/?p=17598 just replace "460" with your current version of the nvidia driver in use.

**Comment by mgallien** [comment] 2024-02-13 07:40
for flatpak issues even if I would be happy to help, there is a specific repository for it https://github.com/flathub/com.nextcloud.desktopclient.nextcloud
can you move the issue there ?
I am closing it as this is purely a community maintained packaging effort
I want also to state that this is very very nice and really appreciated :blue_heart:

**Closed by mgallien** 2024-02-13 07:40 UTC
Labels: 0. Needs triage, bug, crash, package: downstream
