### ISSUE TITLE
[Bug]: Info message translation misleading/missing

### ISSUE THREAD

**Issue by rocketpie** [nextcloud/desktop#5354] opened 2023-01-21 14:17 UTC
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

After the latest update, nextcloud wanted to restart the computer.
After that reboot, i was greeted with an error message window.
It had the Nextcloud logo in the top left corner and a big, round, blue 'i' icon left to the message.
It's title and message was:
'Benötigt keine Übersetzung. Hier wird nur die formelle Übersetzung verwendet (de_DE).'

which roughly translates to english 'doesn't need a translation. only the formal translation is used here'.

### Steps to reproduce

1. windows with a german region setting
2. Update to the latest Nextcloud version
3. Select 'do not close applications'. A reboot will be required.
4. Select 'Manually reboot later' 
5. reboot the machine
6. get greeted with this message

### Expected behavior

if no translation is available, show the original version of the text.

### Which files are affected by this bug

none

### Operating system

Windows

### Which version of the operating system you are running.

Windows 10

### Package

Appimage

### Nextcloud Server version

? cannot find this info in ui/menus

### Nextcloud Desktop Client version

3.6.6

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 3.4.2 to 3.4.4)

### Are you using the Nextcloud Server Encryption module?

Encryption is Enabled

### Are you using an external user-backend?

- [X] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Additional info

![grafik](https://user-images.githubusercontent.com/24610637/213870967-9cdc1f56-8506-44fb-9b54-ee88754e2993.png)

**Comment by claucambra** [comment] 2023-01-21 22:17
Duplicate of #5339

**Closed by claucambra** 2023-01-21 22:17 UTC
Labels: 0. Needs triage
