### ISSUE TITLE
Nextcloud client 3.2.0 segmentation fault with ubuntu mate 21.04

### ISSUE THREAD

**Issue by nbattista89** [nextcloud/desktop#3175] opened 2021-04-20 19:00 UTC
Hi,
With Ubuntu Mate 21.04 the client goes in the segmentation fault.
Output log :

Apr 20 20:47:07 n-batnic kernel: [45588.540888] nextcloud[93715]: segfault at 8 ip 00007f6202bf263f sp 00007ffe85a5a810 error 4 in libQt5Core.so.5.15.2[7f6202993000+30b000]

Version instelled :

ii libnextcloudsync0:amd64 3.2.0-20210410.072919.14fbf1b10-1.0hirsute1
ii nextcloud-desktop 3.2.0-20210410.072919.14fbf1b10-1.0hirsute1
ii nextcloud-desktop-cmd 3.2.0-20210410.072919.14fbf1b10-1.0hirsute1
ii nextcloud-desktop-common 3.2.0-20210410.072919.14fbf1b10-1.0hirsute1
ii nextcloud-desktop-doc 3.2.0-20210410.072919.14fbf1b10-1.0hirsute1
ii nextcloud-desktop-l10n 3.2.0-20210410.072919.14fbf1b10-1.0hirsute1

Regards
Nicola.

**Comment by menschentier** [comment] 2021-04-21 08:11
I can confirm this after upgrading workstation from 20.10 to 21.04.
Exactly the same error. 

Take care
Simon

**Comment by sebgad** [comment] 2021-04-21 18:11
I can also confirm this error after upgrading my workstation from ubuntu 20.10 to 21.04. The AppImage is still working.

Greetings,
Sebastian

**Comment by marukuru** [comment] 2021-04-21 19:55
Can confirm for Xubuntu 21.04. AppImage working.

**Comment by FlexW** [comment] 2021-04-22 07:30
I think that is a duplicate of https://github.com/nextcloud/desktop/issues/3090

**Closed by FlexW** 2021-04-22 07:30 UTC
