### ISSUE TITLE
Nextcloud Client 2.5.1 crashes on ArchLinux

### ISSUE THREAD

**Issue by seehma** [nextcloud/desktop#950] opened 2018-12-16 08:40 UTC
### Expected behaviour
I try to start the Client and Enter my Credentials. Then there comes the question if i want to Grant Access to my Account. After i press that Grant Access Button the Client should start normally

### Actual behaviour
Instead of starting the client crashes with the following Stack Trace:
```
Received signal 11 SEGV_MAPERR 000000000000
#0 0x7fe126d9b98e <unknown>
#1 0x7fe126d94713 <unknown>
#2 0x7fe126d9b905 <unknown>
#3 0x7fe12037fe00 <unknown>
  r8: 0000561b8f0ffd50  r9: 0000000000000003 r10: 0000000000000000 r11: 00007fe1251bf5c5
 r12: 00007fff507fd340 r13: 00007fff507fd360 r14: 0000000000000001 r15: 0000561b8f263f10
  di: 0000561b8f263f10  si: 0000561b8f0ffd50  bp: 00007fff507fd310  bx: 0000561b8f556f40
  dx: 0000561b8f263f20  ax: 0000561b8f5037f0  cx: 0000561b8f263f20  sp: 00007fff507fd2c8
  ip: 0000000000000000 efl: 0000000000010206 cgf: 002b000000000033 erf: 0000000000000014
 trp: 000000000000000e msk: 0000000000000000 cr2: 0000000000000000
[end of stack trace]
Calling _exit(1). Core file will not be generated.

[1]  + 1276 exit 1     nextcloud
```
Unfortunately when starting the client there is another Error Message: 
`[1276:1325:1216/091524.011119:ERROR:cert_verify_proc_nss.cc(977)] CERT_PKIXVerifyCert for hostname.com failed err=-8179`

### Steps to reproduce
1. Just start the client
2. Enter Login Data
3. Click on Grant Access

### Client configuration
Client version:
mirall/2.5.1.git
Operating system:
Archlinux LSB Version 1.4 - 4.19.8-arch1-1-ARCH
OS language:
de_AT
Qt version used by client package (Linux only, see also Settings dialog):
By using qtdiag -> Qt 5.12.0 (settings not available because crashing first)
Client package (From Nextcloud or distro) (Linux only):
mirall ?
Installation path of client:
/bin/nextcloud

### Server configuration
Nextcloud running on linuxserver/nextcloud Docker Image (Synology NAS)

Operating system:
DSM 6.2.1.23824 Update 2

Web server:
-

Database:
MariaDB

PHP version:
dont know

Nextcloud version:
dont know; Using latest linuxserver/nextcloud Image and when i look into the changelist it looks like its the 13.0.1 version; But unfortunately dont know how to find the actual nextcloud version

**Comment by dvzrv** [comment] 2018-12-16 10:12
Dupe of #941

**Comment by FrostKnight** [comment] 2018-12-24 23:41
I keep getting an error in my arch based distro as well:
[localhost@hyperbola Documents]$ ./Nextcloud-2.5.1.AppImage
./Nextcloud-2.5.1.AppImage: /usr/lib/libQt5Core.so.5: version `Qt_5.11' not found (required by ./Nextcloud-2.5.1.AppImage)
./Nextcloud-2.5.1.AppImage: /usr/lib/libQt5Core.so.5: version `Qt_5.11' not found (required by /tmp/.mount_NextclJqbO9F/usr/bin/../lib/libnextcloudsync.so.0)
./Nextcloud-2.5.1.AppImage: /usr/lib/libQt5Core.so.5: version `Qt_5.11' not found (required by /tmp/.mount_NextclJqbO9F/usr/bin/../lib/libocsync.so.0)
./Nextcloud-2.5.1.AppImage: /usr/lib/libQt5Core.so.5: version `Qt_5.11' not found (required by /tmp/.mount_NextclJqbO9F/usr/bin/../lib/libQt5WebEngineWidgets.so.5)
./Nextcloud-2.5.1.AppImage: /usr/lib/libQt5Core.so.5: version `Qt_5.11' not found (required by /tmp/.mount_NextclJqbO9F/usr/bin/../lib/libQt5WebEngineCore.so.5)

Can you make it so that, the Nextcloud appimage, A: has no non-free Qt5WebEngineCore, and B: has everything in it already so it can run based on whats inside and not whats outside.

**Closed** 2019-01-07 14:01 UTC
