### ISSUE TITLE
MacOS Clients after 3.6.6 will not launch [Bug]: 

### ISSUE THREAD

**Issue by wolfgangrumpf** [nextcloud/desktop#5419] opened 2023-02-08 16:09 UTC
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

I'm running a Macbook Pro with Mac OS 10.15.7 (yes, it's old).  Nextcloud client was updated and suddenly I cannot connect to my server (which is the latest version).  

I have tried installing all versions moving backwards in time and the newest version that successfully launches AND connects to my server is 3.6.6

### Steps to reproduce

1. Install latest desktop client for Mac
2. Watch it not work

### Expected behavior

When launching it the application should launch

### Which files are affected by this bug

all

### Operating system

Mac OS

### Which version of the operating system you are running.

10.15.7

### Package

Other

### Nextcloud Server version

25.0.3

### Nextcloud Desktop Client version

3.7

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 3.3.6 to 3.4.0)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Nextcloud Server logs

```shell
{"reqId":"fynmkzZ6OejMVIKkGWE5","level":3,"time":"2023-02-07T20:27:31+00:00","remoteAddr":"192.168.7.43","user":"wolfgang","app":"PHP","method":"POST","url":"/index.php","message":"exif_read_data(): File not supported at /snap/nextcloud/33493/htdocs/lib/private/Metadata/Provider/ExifProvider.php#59","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/109.0","version":"25.0.3.2","exception":{"Exception":"Error","Message":"exif_read_data(): File not supported at /snap/nextcloud/33493/htdocs/lib/private/Metadata/Provider/ExifProvider.php#59","Code":0,"Trace":[{"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::"},{"file":"/snap/nextcloud/33493/htdocs/lib/private/Metadata/Provider/ExifProvider.php","line":59,"function":"exif_read_data"},{"file":"/snap/nextcloud/33493/htdocs/lib/private/Metadata/MetadataManager.php","line":68,"function":"execute","class":"OC\\Metadata\\Provider\\ExifProvider","type":"->"},{"file":"/snap/nextcloud/33493/htdocs/lib/private/Metadata/FileEventListener.php","line":101,"function":"generateMetadata","class":"OC\\Metadata\\MetadataManager","type":"->"},{"file":"/snap/nextcloud/33493/htdocs/lib/private/EventDispatcher/ServiceEventListener.php","line":87,"function":"handle","class":"OC\\Metadata\\FileEventListener","type":"->"},{"file":"/snap/nextcloud/33493/htdocs/3rdparty/symfony/event-dispatcher/EventDispatcher.php","line":251,"function":"__invoke","class":"OC\\EventDispatcher\\ServiceEventListener","type":"->"},{"file":"/snap/nextcloud/33493/htdocs/3rdparty/symfony/event-dispatcher/EventDispatcher.php","line":73,"function":"callListeners","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"->"},{"file":"/snap/nextcloud/33493/htdocs/lib/private/EventDispatcher/EventDispatcher.php","line":88,"function":"dispatch","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"->"},{"file":"/snap/nextcloud/33493/htdocs/lib/private/EventDispatcher/EventDispatcher.php","line":100,"function":"dispatch","class":"OC\\EventDispatcher\\EventDispatcher","type":"->"},{"file":"/snap/nextcloud/33493/htdocs/lib/private/Files/Node/HookConnector.php","line":118,"function":"dispatchTyped","class":"OC\\EventDispatcher\\EventDispatcher","type":"->"},{"file":"/snap/nextcloud/33493/htdocs/lib/private/legacy/OC_Hook.php","line":106,"function":"postWrite","class":"OC\\Files\\Node\\HookConnector","type":"->"},{"file":"/snap/nextcloud/33493/htdocs/lib/private/Files/View.php","line":641,"function":"emit","class":"OC_Hook","type":"::"},{"file":"/snap/nextcloud/33493/htdocs/lib/private/Files/View.php","line":692,"function":"emit_file_hooks_post","class":"OC\\Files\\View","type":"->"},{"file":"/snap/nextcloud/33493/htdocs/lib/private/Files/Node/File.php","line":71,"function":"file_put_contents","class":"OC\\Files\\View","type":"->"},{"file":"/snap/nextcloud/33493/htdocs/lib/private/legacy/OC_Util.php","line":257,"function":"putContent","class":"OC\\Files\\Node\\File","type":"->"},{"file":"/snap/nextcloud/33493/htdocs/lib/private/legacy/OC_Util.php","line":216,"function":"copyr","class":"OC_Util","type":"::"},{"file":"/snap/nextcloud/33493/htdocs/lib/private/User/Session.php","line":553,"function":"copySkeleton","class":"OC_Util","type":"::"},{"file":"/snap/nextcloud/33493/htdocs/lib/private/User/Session.php","line":403,"function":"prepareUserLogin","class":"OC\\User\\Session","type":"->"},{"file":"/snap/nextcloud/33493/htdocs/lib/private/User/Session.php","line":616,"function":"completeLogin","class":"OC\\User\\Session","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/snap/nextcloud/33493/htdocs/lib/private/User/Session.php","line":355,"function":"loginWithPassword","class":"OC\\User\\Session","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/snap/nextcloud/33493/htdocs/lib/private/Setup.php","line":433,"function":"login","class":"OC\\User\\Session","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/snap/nextcloud/33493/htdocs/core/Controller/SetupController.php","line":69,"function":"install","class":"OC\\Setup","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/snap/nextcloud/33493/htdocs/lib/base.php","line":980,"function":"run","class":"OC\\Core\\Controller\\SetupController","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/snap/nextcloud/33493/htdocs/index.php","line":36,"function":"handleRequest","class":"OC","type":"::"}],"File":"/snap/nextcloud/33493/htdocs/lib/private/Log/ErrorHandler.php","Line":92,"CustomMessage":"--"}}
{"reqId":"P6gd0DbkTcVukHsivaad","level":3,"time":"2023-02-07T20:27:45+00:00","remoteAddr":"","user":"--","app":"core","method":"","url":"--","message":"Error while running background job (class: OCA\\Theming\\Jobs\\MigrateBackgroundImages, arguments: Array\n(\n    [stage] => prepare\n)\n)","userAgent":"--","version":"25.0.3.2","exception":{"Exception":"OCP\\Files\\NotFoundException","Message":"/appdata_ocjh2ez3tl35/theming/global","Code":0,"Trace":[{"function":"get","class":"OC\\Files\\Node\\Root","type":"->"},{"file":"/snap/nextcloud/33493/htdocs/lib/private/Files/Node/LazyFolder.php","line":72,"function":"call_user_func_array"},{"file":"/snap/nextcloud/33493/htdocs/lib/private/Files/Node/LazyFolder.php","line":149,"function":"__call","class":"OC\\Files\\Node\\LazyFolder","type":"->"},{"file":"/snap/nextcloud/33493/htdocs/lib/private/Files/AppData/AppData.php","line":132,"function":"get","class":"OC\\Files\\Node\\LazyFolder","type":"->"},{"file":"/snap/nextcloud/33493/htdocs/apps/theming/lib/Jobs/MigrateBackgroundImages.php","line":167,"function":"getFolder","class":"OC\\Files\\AppData\\AppData","type":"->"},{"file":"/snap/nextcloud/33493/htdocs/apps/theming/lib/Jobs/MigrateBackgroundImages.php","line":99,"function":"storeUserIdsToProcess","class":"OCA\\Theming\\Jobs\\MigrateBackgroundImages","type":"->"},{"file":"/snap/nextcloud/33493/htdocs/apps/theming/lib/Jobs/MigrateBackgroundImages.php","line":78,"function":"runPreparation","class":"OCA\\Theming\\Jobs\\MigrateBackgroundImages","type":"->"},{"file":"/snap/nextcloud/33493/htdocs/lib/public/BackgroundJob/Job.php","line":78,"function":"run","class":"OCA\\Theming\\Jobs\\MigrateBackgroundImages","type":"->"},{"file":"/snap/nextcloud/33493/htdocs/lib/public/BackgroundJob/QueuedJob.php","line":58,"function":"start","class":"OCP\\BackgroundJob\\Job","type":"->"},{"file":"/snap/nextcloud/33493/htdocs/lib/public/BackgroundJob/QueuedJob.php","line":48,"function":"start","class":"OCP\\BackgroundJob\\QueuedJob","type":"->"},{"file":"/snap/nextcloud/33493/htdocs/cron.php","line":152,"function":"execute","class":"OCP\\BackgroundJob\\QueuedJob","type":"->"}],"File":"/snap/nextcloud/33493/htdocs/lib/private/Files/Node/Root.php","Line":209,"message":"Error while running background job (class: OCA\\Theming\\Jobs\\MigrateBackgroundImages, arguments: Array\n(\n    [stage] => prepare\n)\n)","exception":{},"CustomMessage":"Error while running background job (class: OCA\\Theming\\Jobs\\MigrateBackgroundImages, arguments: Array\n(\n    [stage] => prepare\n)\n)"}}
{"reqId":"ndYt0syvSt30YnOZa4Ug","level":2,"time":"2023-02-08T15:31:56+00:00","remoteAddr":"192.168.7.43","user":"--","app":"no app in context","method":"POST","url":"/index.php/login","message":"Login failed: wolfgang (Remote IP: 192.168.7.43)","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.6.1 Safari/605.1.15","version":"25.0.3.2","data":[]}
{"reqId":"iUVReUuBYY607mCmI1Fe","level":2,"time":"2023-02-08T15:32:07+00:00","remoteAddr":"192.168.7.43","user":"--","app":"no app in context","method":"POST","url":"/index.php/login","message":"Login failed: wolfgang (Remote IP: 192.168.7.43)","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.6.1 Safari/605.1.15","version":"25.0.3.2","data":[]}
{"reqId":"7sjyzrglppER0zisyQjZ","level":3,"time":"2023-02-08T15:56:59+00:00","remoteAddr":"192.168.7.43","user":"wolfgang","app":"PHP","method":"PUT","url":"/remote.php/dav/files/wolfgang/3D%20Models/Marvel/Iron%20Man%20Arc%20Reactors/MK%2050/ORIGINAL%20FILES/Information%20Pack/Etsy%20Shop%20Leaflet%20and%20QR%20Code%20Link.png","message":"exif_read_data(): File not supported at /snap/nextcloud/33493/htdocs/lib/private/Metadata/Provider/ExifProvider.php#59","userAgent":"Mozilla/5.0 (Macintosh) mirall/3.6.6git (build 13475) (Nextcloud, osx-19.6.0 ClientArchitecture: x86_64 OsArchitecture: x86_64)","version":"25.0.3.2","exception":{"Exception":"Error","Message":"exif_read_data(): File not supported at /snap/nextcloud/33493/htdocs/lib/private/Metadata/Provider/ExifProvider.php#59","Code":0,"Trace":[{"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::"},{"file":"/snap/nextcloud/33493/htdocs/lib/private/Metadata/Provider/ExifProvider.php","line":59,"function":"exif_read_data"},{"file":"/snap/nextcloud/33493/htdocs/lib/private/Metadata/MetadataManager.php","line":68,"function":"execute","class":"OC\\Metadata\\Provider\\ExifProvider","type":"->"},{"file":"/snap/nextcloud/33493/htdocs/lib/private/Metadata/FileEventListener.php","line":101,"function":"generateMetadata","class":"OC\\Metadata\\MetadataManager","type":"->"},{"file":"/snap/nextcloud/33493/htdocs/lib/private/EventDispatcher/ServiceEventListener.php","line":87,"function":"handle","class":"OC\\Metadata\\FileEventListener","type":"->"},{"file":"/snap/nextcloud/33493/htdocs/3rdparty/symfony/event-dispatcher/EventDispatcher.php","line":251,"function":"__invoke","class":"OC\\EventDispatcher\\ServiceEventListener","type":"->"},{"file":"/snap/nextcloud/33493/htdocs/3rdparty/symfony/event-dispatcher/EventDispatcher.php","line":73,"function":"callListeners","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"->"},{"file":"/snap/nextcloud/33493/htdocs/lib/private/EventDispatcher/EventDispatcher.php","line":88,"function":"dispatch","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"->"},{"file":"/snap/nextcloud/33493/htdocs/lib/private/EventDispatcher/EventDispatcher.php","line":100,"function":"dispatch","class":"OC\\EventDispatcher\\EventDispatcher","type":"->"},{"file":"/snap/nextcloud/33493/htdocs/lib/private/Files/Node/HookConnector.php","line":118,"function":"dispatchTyped","class":"OC\\EventDispatcher\\EventDispatcher","type":"->"},{"file":"/snap/nextcloud/33493/htdocs/lib/private/legacy/OC_Hook.php","line":106,"function":"postWrite","class":"OC\\Files\\Node\\HookConnector","type":"->"},{"file":"/snap/nextcloud/33493/htdocs/apps/dav/lib/Connector/Sabre/File.php","line":471,"function":"emit","class":"OC_Hook","type":"::"},{"file":"/snap/nextcloud/33493/htdocs/apps/dav/lib/Connector/Sabre/File.php","line":398,"function":"emitPostHooks","class":"OCA\\DAV\\Connector\\Sabre\\File","type":"->"},{"file":"/snap/nextcloud/33493/htdocs/apps/dav/lib/Connector/Sabre/Directory.php","line":151,"function":"put","class":"OCA\\DAV\\Connector\\Sabre\\File","type":"->"},{"file":"/snap/nextcloud/33493/htdocs/3rdparty/sabre/dav/lib/DAV/Server.php","line":1098,"function":"createFile","class":"OCA\\DAV\\Connector\\Sabre\\Directory","type":"->"},{"file":"/snap/nextcloud/33493/htdocs/3rdparty/sabre/dav/lib/DAV/CorePlugin.php","line":504,"function":"createFile","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/snap/nextcloud/33493/htdocs/3rdparty/sabre/event/lib/WildcardEmitterTrait.php","line":89,"function":"httpPut","class":"Sabre\\DAV\\CorePlugin","type":"->"},{"file":"/snap/nextcloud/33493/htdocs/3rdparty/sabre/dav/lib/DAV/Server.php","line":472,"function":"emit","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/snap/nextcloud/33493/htdocs/3rdparty/sabre/dav/lib/DAV/Server.php","line":253,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/snap/nextcloud/33493/htdocs/3rdparty/sabre/dav/lib/DAV/Server.php","line":321,"function":"start","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/snap/nextcloud/33493/htdocs/apps/dav/lib/Server.php","line":360,"function":"exec","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/snap/nextcloud/33493/htdocs/apps/dav/appinfo/v2/remote.php","line":35,"function":"exec","class":"OCA\\DAV\\Server","type":"->"},{"file":"/snap/nextcloud/33493/htdocs/remote.php","line":171,"args":["/snap/nextcloud/33493/htdocs/apps/dav/appinfo/v2/remote.php"],"function":"require_once"}],"File":"/snap/nextcloud/33493/htdocs/lib/private/Log/ErrorHandler.php","Line":92,"CustomMessage":"--"}}
```

### Additional info

No additional info

**Comment by fiee** [comment] 2023-02-08 17:06
I can confirm the same on MacOS 10.14.6 (Mac mini 2013).

3.6.6 works, 3.7.0rc3 and 3.7.1 don’t start.

**Comment by claucambra** [comment] 2023-02-08 19:26
Since this is a duplicate of https://github.com/nextcloud/desktop/issues/5415 I will close, thanks for reporting!

**Closed by claucambra** 2023-02-08 19:26 UTC
Labels: 0. Needs triage
