### ISSUE TITLE
[Bug]: Auto-Update updates to an non supported version (MAC OS)

### ISSUE THREAD

**Issue by xbluemonkx** [nextcloud/desktop#6309] opened 2023-12-21 10:29 UTC
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

On Mac the Auto-Update Feature of the NC Client will update to non-supported version.

https://help.nextcloud.com/t/macos-client-for-big-sur-11-7-10-not-working-anymore-after-upgrade/173647

### Steps to reproduce

use a mac

### Expected behavior

NC Client should not be auto-updated to non supported versions. (Or at least give a warning...)

### Which files are affected by this bug

software itself

### Operating system

Windows

### Which version of the operating system you are running.

macOS Big Sur 11.7.10

### Package

Other

### Nextcloud Server version

latest

### Nextcloud Desktop Client version

latest

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 3.4.2 to 3.4.4)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by joshtrichards** [comment] 2023-12-26 21:31
Duplicate of #6198 
Related #6176

**Closed by joshtrichards** 2023-12-26 21:31 UTC
Labels: 0. Needs triage, os: :apple: macOS, feature: :inbox_tray: install and update
