### ISSUE TITLE
[Bug]: Syncing every 4 seconds, but no files to update

### ISSUE THREAD

**Issue by metheos** [nextcloud/desktop#6041] opened 2023-09-08 20:43 UTC
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

I noticed recently that my tray icon was constantly toggling between the green check and the sync icon.
There seem to be PROPFIND records in the system log that line up with the syncs and the app log just spams the typical Syncrun started > Propogation starts > Syncrun finished.

Nothing is *broken* but it's weird and probably putting unnecessary load on things.

### Steps to reproduce

1. Connect nextcloud account
2. complete initial sync
3. watch it constantly start a sync, even when there are no files to update

### Expected behavior

Should only do a sync run occasionally?

### Which files are affected by this bug

none

### Operating system

Windows

### Which version of the operating system you are running.

Windows 11

### Package

Other

### Nextcloud Server version

26.0.5

### Nextcloud Desktop Client version

3.9.4

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 3.4.2 to 3.4.4)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [X] LDAP/ Active Directory
- [X] SSO - SAML
- [ ] Other

### Nextcloud Server logs

```shell
{"reqId":"biamHptLs3DLluvNrzYn","level":0,"time":"2023-09-08T20:36:33+00:00","remoteAddr":"10.0.1.84","user":"MattNelson","app":"user_saml","method":"PROPFIND","url":"/remote.php/dav/files/MattNelson/","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (Windows) mirall/3.9.4stable-Win64 (build 20230906) (Nextcloud, windows-10.0.22621 ClientArchitecture: x86_64 OsArchitecture: x86_64)","version":"26.0.5.1","data":{"app":"user_saml"}}
{"reqId":"biamHptLs3DLluvNrzYn","level":0,"time":"2023-09-08T20:36:33+00:00","remoteAddr":"10.0.1.84","user":"MattNelson","app":"user_ldap","method":"PROPFIND","url":"/remote.php/dav/files/MattNelson/","message":"Calling LDAP function ldap_explode_dn with parameters [\"MattNelson\",0]","userAgent":"Mozilla/5.0 (Windows) mirall/3.9.4stable-Win64 (build 20230906) (Nextcloud, windows-10.0.22621 ClientArchitecture: x86_64 OsArchitecture: x86_64)","version":"26.0.5.1","data":{"app":"user_ldap"}}
{"reqId":"biamHptLs3DLluvNrzYn","level":0,"time":"2023-09-08T20:36:33+00:00","remoteAddr":"10.0.1.84","user":"MattNelson","app":"user_ldap","method":"PROPFIND","url":"/remote.php/dav/files/MattNelson/","message":"Calling LDAP function ldap_explode_dn with parameters [\"6A5404A1-5295-4675-8153-8B6EE57E3754\",0]","userAgent":"Mozilla/5.0 (Windows) mirall/3.9.4stable-Win64 (build 20230906) (Nextcloud, windows-10.0.22621 ClientArchitecture: x86_64 OsArchitecture: x86_64)","version":"26.0.5.1","data":{"app":"user_ldap"}}
{"reqId":"biamHptLs3DLluvNrzYn","level":0,"time":"2023-09-08T20:36:33+00:00","remoteAddr":"10.0.1.84","user":"MattNelson","app":"user_ldap","method":"PROPFIND","url":"/remote.php/dav/files/MattNelson/","message":"Calling LDAP function ldap_explode_dn with parameters [\"A427C5C3-F9FE-45AB-A655-D3738F4E65A1\",0]","userAgent":"Mozilla/5.0 (Windows) mirall/3.9.4stable-Win64 (build 20230906) (Nextcloud, windows-10.0.22621 ClientArchitecture: x86_64 OsArchitecture: x86_64)","version":"26.0.5.1","data":{"app":"user_ldap"}}
{"reqId":"biamHptLs3DLluvNrzYn","level":0,"time":"2023-09-08T20:36:33+00:00","remoteAddr":"10.0.1.84","user":"MattNelson","app":"user_ldap","method":"PROPFIND","url":"/remote.php/dav/files/MattNelson/","message":"Calling LDAP function ldap_explode_dn with parameters [\"JoeSankey\",0]","userAgent":"Mozilla/5.0 (Windows) mirall/3.9.4stable-Win64 (build 20230906) (Nextcloud, windows-10.0.22621 ClientArchitecture: x86_64 OsArchitecture: x86_64)","version":"26.0.5.1","data":{"app":"user_ldap"}}
{"reqId":"biamHptLs3DLluvNrzYn","level":0,"time":"2023-09-08T20:36:33+00:00","remoteAddr":"10.0.1.84","user":"MattNelson","app":"user_ldap","method":"PROPFIND","url":"/remote.php/dav/files/MattNelson/","message":"Calling LDAP function ldap_explode_dn with parameters [\"9BE326AB-8DE4-48A6-89A7-BB6655EB06C4\",0]","userAgent":"Mozilla/5.0 (Windows) mirall/3.9.4stable-Win64 (build 20230906) (Nextcloud, windows-10.0.22621 ClientArchitecture: x86_64 OsArchitecture: x86_64)","version":"26.0.5.1","data":{"app":"user_ldap"}}
{"reqId":"biamHptLs3DLluvNrzYn","level":0,"time":"2023-09-08T20:36:33+00:00","remoteAddr":"10.0.1.84","user":"MattNelson","app":"user_ldap","method":"PROPFIND","url":"/remote.php/dav/files/MattNelson/","message":"Calling LDAP function ldap_explode_dn with parameters [\"5A0E1266-8343-46BF-9B6C-44D6DF877D4E\",0]","userAgent":"Mozilla/5.0 (Windows) mirall/3.9.4stable-Win64 (build 20230906) (Nextcloud, windows-10.0.22621 ClientArchitecture: x86_64 OsArchitecture: x86_64)","version":"26.0.5.1","data":{"app":"user_ldap"}}
{"reqId":"biamHptLs3DLluvNrzYn","level":0,"time":"2023-09-08T20:36:33+00:00","remoteAddr":"10.0.1.84","user":"MattNelson","app":"user_ldap","method":"PROPFIND","url":"/remote.php/dav/files/MattNelson/","message":"Calling LDAP function ldap_explode_dn with parameters [\"EC2DA82F-F3FC-4492-8864-F2D6EF517D60\",0]","userAgent":"Mozilla/5.0 (Windows) mirall/3.9.4stable-Win64 (build 20230906) (Nextcloud, windows-10.0.22621 ClientArchitecture: x86_64 OsArchitecture: x86_64)","version":"26.0.5.1","data":{"app":"user_ldap"}}
{"reqId":"biamHptLs3DLluvNrzYn","level":0,"time":"2023-09-08T20:36:33+00:00","remoteAddr":"10.0.1.84","user":"MattNelson","app":"user_ldap","method":"PROPFIND","url":"/remote.php/dav/files/MattNelson/","message":"Calling LDAP function ldap_explode_dn with parameters [\"AlexAlston\",0]","userAgent":"Mozilla/5.0 (Windows) mirall/3.9.4stable-Win64 (build 20230906) (Nextcloud, windows-10.0.22621 ClientArchitecture: x86_64 OsArchitecture: x86_64)","version":"26.0.5.1","data":{"app":"user_ldap"}}
{"reqId":"yjOteS3xdgsMIk2FJixO","level":0,"time":"2023-09-08T20:36:37+00:00","remoteAddr":"73.177.124.22","user":"AlexAlston","app":"user_saml","method":"PROPFIND","url":"/remote.php/dav/files/AlexAlston/","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (Windows) mirall/3.9.3stable-Win64 (build 20230818) (Nextcloud, windows-10.0.19044 ClientArchitecture: x86_64 OsArchitecture: x86_64)","version":"26.0.5.1","data":{"app":"user_saml"}}
{"reqId":"yjOteS3xdgsMIk2FJixO","level":0,"time":"2023-09-08T20:36:37+00:00","remoteAddr":"73.177.124.22","user":"AlexAlston","app":"user_ldap","method":"PROPFIND","url":"/remote.php/dav/files/AlexAlston/","message":"Calling LDAP function ldap_explode_dn with parameters [\"AlexAlston\",0]","userAgent":"Mozilla/5.0 (Windows) mirall/3.9.3stable-Win64 (build 20230818) (Nextcloud, windows-10.0.19044 ClientArchitecture: x86_64 OsArchitecture: x86_64)","version":"26.0.5.1","data":{"app":"user_ldap"}}
{"reqId":"SPXtIJLg1W7ow3gQVCch","level":0,"time":"2023-09-08T20:36:37+00:00","remoteAddr":"10.0.1.84","user":"MattNelson","app":"user_saml","method":"PROPFIND","url":"/remote.php/dav/files/MattNelson/","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (Windows) mirall/3.9.4stable-Win64 (build 20230906) (Nextcloud, windows-10.0.22621 ClientArchitecture: x86_64 OsArchitecture: x86_64)","version":"26.0.5.1","data":{"app":"user_saml"}}
{"reqId":"SPXtIJLg1W7ow3gQVCch","level":0,"time":"2023-09-08T20:36:37+00:00","remoteAddr":"10.0.1.84","user":"MattNelson","app":"user_ldap","method":"PROPFIND","url":"/remote.php/dav/files/MattNelson/","message":"Calling LDAP function ldap_explode_dn with parameters [\"MattNelson\",0]","userAgent":"Mozilla/5.0 (Windows) mirall/3.9.4stable-Win64 (build 20230906) (Nextcloud, windows-10.0.22621 ClientArchitecture: x86_64 OsArchitecture: x86_64)","version":"26.0.5.1","data":{"app":"user_ldap"}}
{"reqId":"SPXtIJLg1W7ow3gQVCch","level":0,"time":"2023-09-08T20:36:37+00:00","remoteAddr":"10.0.1.84","user":"MattNelson","app":"user_ldap","method":"PROPFIND","url":"/remote.php/dav/files/MattNelson/","message":"Calling LDAP function ldap_explode_dn with parameters [\"6A5404A1-5295-4675-8153-8B6EE57E3754\",0]","userAgent":"Mozilla/5.0 (Windows) mirall/3.9.4stable-Win64 (build 20230906) (Nextcloud, windows-10.0.22621 ClientArchitecture: x86_64 OsArchitecture: x86_64)","version":"26.0.5.1","data":{"app":"user_ldap"}}
{"reqId":"SPXtIJLg1W7ow3gQVCch","level":0,"time":"2023-09-08T20:36:37+00:00","remoteAddr":"10.0.1.84","user":"MattNelson","app":"user_ldap","method":"PROPFIND","url":"/remote.php/dav/files/MattNelson/","message":"Calling LDAP function ldap_explode_dn with parameters [\"A427C5C3-F9FE-45AB-A655-D3738F4E65A1\",0]","userAgent":"Mozilla/5.0 (Windows) mirall/3.9.4stable-Win64 (build 20230906) (Nextcloud, windows-10.0.22621 ClientArchitecture: x86_64 OsArchitecture: x86_64)","version":"26.0.5.1","data":{"app":"user_ldap"}}
{"reqId":"SPXtIJLg1W7ow3gQVCch","level":0,"time":"2023-09-08T20:36:37+00:00","remoteAddr":"10.0.1.84","user":"MattNelson","app":"user_ldap","method":"PROPFIND","url":"/remote.php/dav/files/MattNelson/","message":"Calling LDAP function ldap_explode_dn with parameters [\"JoeSankey\",0]","userAgent":"Mozilla/5.0 (Windows) mirall/3.9.4stable-Win64 (build 20230906) (Nextcloud, windows-10.0.22621 ClientArchitecture: x86_64 OsArchitecture: x86_64)","version":"26.0.5.1","data":{"app":"user_ldap"}}
{"reqId":"SPXtIJLg1W7ow3gQVCch","level":0,"time":"2023-09-08T20:36:37+00:00","remoteAddr":"10.0.1.84","user":"MattNelson","app":"user_ldap","method":"PROPFIND","url":"/remote.php/dav/files/MattNelson/","message":"Calling LDAP function ldap_explode_dn with parameters [\"9BE326AB-8DE4-48A6-89A7-BB6655EB06C4\",0]","userAgent":"Mozilla/5.0 (Windows) mirall/3.9.4stable-Win64 (build 20230906) (Nextcloud, windows-10.0.22621 ClientArchitecture: x86_64 OsArchitecture: x86_64)","version":"26.0.5.1","data":{"app":"user_ldap"}}
{"reqId":"SPXtIJLg1W7ow3gQVCch","level":0,"time":"2023-09-08T20:36:37+00:00","remoteAddr":"10.0.1.84","user":"MattNelson","app":"user_ldap","method":"PROPFIND","url":"/remote.php/dav/files/MattNelson/","message":"Calling LDAP function ldap_explode_dn with parameters [\"5A0E1266-8343-46BF-9B6C-44D6DF877D4E\",0]","userAgent":"Mozilla/5.0 (Windows) mirall/3.9.4stable-Win64 (build 20230906) (Nextcloud, windows-10.0.22621 ClientArchitecture: x86_64 OsArchitecture: x86_64)","version":"26.0.5.1","data":{"app":"user_ldap"}}
{"reqId":"SPXtIJLg1W7ow3gQVCch","level":0,"time":"2023-09-08T20:36:37+00:00","remoteAddr":"10.0.1.84","user":"MattNelson","app":"user_ldap","method":"PROPFIND","url":"/remote.php/dav/files/MattNelson/","message":"Calling LDAP function ldap_explode_dn with parameters [\"EC2DA82F-F3FC-4492-8864-F2D6EF517D60\",0]","userAgent":"Mozilla/5.0 (Windows) mirall/3.9.4stable-Win64 (build 20230906) (Nextcloud, windows-10.0.22621 ClientArchitecture: x86_64 OsArchitecture: x86_64)","version":"26.0.5.1","data":{"app":"user_ldap"}}
{"reqId":"SPXtIJLg1W7ow3gQVCch","level":0,"time":"2023-09-08T20:36:37+00:00","remoteAddr":"10.0.1.84","user":"MattNelson","app":"user_ldap","method":"PROPFIND","url":"/remote.php/dav/files/MattNelson/","message":"Calling LDAP function ldap_explode_dn with parameters [\"AlexAlston\",0]","userAgent":"Mozilla/5.0 (Windows) mirall/3.9.4stable-Win64 (build 20230906) (Nextcloud, windows-10.0.22621 ClientArchitecture: x86_64 OsArchitecture: x86_64)","version":"26.0.5.1","data":{"app":"user_ldap"}}
```

### Additional info

The debug archive is over 1 GB due to the constant log spamming, here is an excerpt.

`#=#=#=# Syncrun started 2023-09-08T20:39:27Z
#=#=#=#=# Propagation starts 2023-09-08T20:39:27Z (last step: 841 msec, total: 841 msec)
#=#=#=# Syncrun finished 2023-09-08T20:39:28Z (last step: 61 msec, total: 903 msec)
#=#=#=# Syncrun started 2023-09-08T20:39:30Z
#=#=#=#=# Propagation starts 2023-09-08T20:39:31Z (last step: 936 msec, total: 936 msec)
#=#=#=# Syncrun finished 2023-09-08T20:39:31Z (last step: 47 msec, total: 984 msec)
#=#=#=# Syncrun started 2023-09-08T20:39:34Z
#=#=#=#=# Propagation starts 2023-09-08T20:39:35Z (last step: 958 msec, total: 958 msec)
#=#=#=# Syncrun finished 2023-09-08T20:39:36Z (last step: 94 msec, total: 1053 msec)
#=#=#=# Syncrun started 2023-09-08T20:39:39Z
#=#=#=#=# Propagation starts 2023-09-08T20:39:40Z (last step: 1046 msec, total: 1046 msec)
#=#=#=# Syncrun finished 2023-09-08T20:39:40Z (last step: 77 msec, total: 1124 msec)
#=#=#=# Syncrun started 2023-09-08T20:39:43Z
#=#=#=#=# Propagation starts 2023-09-08T20:39:44Z (last step: 920 msec, total: 920 msec)
#=#=#=# Syncrun finished 2023-09-08T20:39:44Z (last step: 84 msec, total: 1005 msec)
#=#=#=# Syncrun started 2023-09-08T20:39:46Z
#=#=#=#=# Propagation starts 2023-09-08T20:39:47Z (last step: 939 msec, total: 939 msec)
#=#=#=# Syncrun finished 2023-09-08T20:39:47Z (last step: 62 msec, total: 1002 msec)
#=#=#=# Syncrun started 2023-09-08T20:39:50Z
#=#=#=#=# Propagation starts 2023-09-08T20:39:51Z (last step: 909 msec, total: 909 msec)
#=#=#=# Syncrun finished 2023-09-08T20:39:51Z (last step: 78 msec, total: 988 msec)
#=#=#=# Syncrun started 2023-09-08T20:39:54Z
#=#=#=#=# Propagation starts 2023-09-08T20:39:56Z (last step: 1760 msec, total: 1760 msec)
#=#=#=# Syncrun finished 2023-09-08T20:39:56Z (last step: 36 msec, total: 1797 msec)
#=#=#=# Syncrun started 2023-09-08T20:39:59Z
#=#=#=#=# Propagation starts 2023-09-08T20:40:00Z (last step: 1007 msec, total: 1007 msec)
#=#=#=# Syncrun finished 2023-09-08T20:40:00Z (last step: 74 msec, total: 1081 msec)
#=#=#=# Syncrun started 2023-09-08T20:40:03Z
#=#=#=#=# Propagation starts 2023-09-08T20:40:04Z (last step: 966 msec, total: 966 msec)
#=#=#=# Syncrun finished 2023-09-08T20:40:05Z (last step: 100 msec, total: 1067 msec)
#=#=#=# Syncrun started 2023-09-08T20:40:08Z
#=#=#=#=# Propagation starts 2023-09-08T20:40:09Z (last step: 1049 msec, total: 1049 msec)
#=#=#=# Syncrun finished 2023-09-08T20:40:09Z (last step: 78 msec, total: 1128 msec)
`

**Comment by Luatan** [comment] 2023-09-09 11:09
I can confirm this bug. It also happens on my Windows 10 PC. For me this is happening since I updated the client from Version 3.9.3 to 3.9.4.

I noticed it, because I have synced my desktop and on the desktop the icons change every 2-3 Seconds to syncing and then again to the green Checkmark.

Server Version is 27.0.2

If I create a debug Archive it is about 3 GB big.

**Comment by chrissi55** [comment] 2023-09-10 07:51
Seems to be a similar problem to mine

Server: Nextcloud 27.0.2
Tested on Win 10 Client and 2 Win11 Clients

After update from 3.9.3 to 3.9.4 my Win Explorer stuck in unusability because of the interaction between NC Desktop Client and Windows Components.
Re-Installed the 3.9.4 once on a Win11 machine with no effect.

Then downgraded all Clients to 3.9.3 and voila everything behaves as normal again.

In my case the tray icon switches between green -> blue (Sync) and -> grey (disconnected)

**Comment by marian-code** [comment] 2023-09-10 18:17
I have the same issue as @chrissi55
Server: Nextcloud 27.0.2
Tested on Win11 Client
Started to happen after upgrade from 3.9.3 to 3.9.4

**Comment by EVOTk** [comment] 2023-09-11 06:03
Same issue on Windows 10
Server: Nextcloud 27.0.2
Nextcloud Client 3.9.4

**Comment by hnoack2102** [comment] 2023-09-11 07:56
I can confirm this bug with two different Nextcloud AIO Docker installations.(27.0.2) and NC desktop client 3.9.4 for Windows. Clients running on Windows 11 Pro.

The clients sync every 3-4 seconds doing effectively nothing, other than putting additional load on the client and server. On a laptop it is severely limiting battery life. It also triggers the anti virus solution to constantly scan some files the client is touching, creating even more load. Going back to 3.9.3 solves this issue.

Other than that the client does it's normal job.

**Comment by Mika-6-9** [comment] 2023-09-11 09:23
Idem for me with Windows 11

**Comment by shrodi** [comment] 2023-09-11 22:57
Same here; I noticed it because of unusually high CPU usage; downgrading solved the problem.

**Comment by guidobonuzzi** [comment] 2023-09-12 08:55
Same here with 3.9.4., Windows 11, and server version 26.0.4.
Also, 3.10.0-rc2 has this issue.
The only solution is to downgrade to 3.9.3.

**Comment by bantanamera** [comment] 2023-09-12 22:00
I have the same phenomenon, but only when virtual files is enabled

**Comment by jnccompl** [comment] 2023-09-13 10:02
Same issue with 3.9.4 Desktop on Windows 11, Server version 25.0.5, DB engine MySQL 10.3.17.

Tray icon switches fast between green and blue.

**Comment by ementat** [comment] 2023-09-13 10:17
Same issue with 3.9.4 Desktop, but only if i enable virtual files support. Without virtual files all works as expected.

**Comment by allexzander** [comment] 2023-09-13 16:08
@metheos Can you upload the full logs archive here https://cloud.nextcloud.com/s/YSxWcs8gFNAebbs (please also make sure the issue is happening when you create logs unless you've stored the archive already before you downgraded to 3.9.3).

**Comment by metheos** [comment] 2023-09-13 17:01
> @metheos Can you upload the full logs archive here https://cloud.nextcloud.com/s/YSxWcs8gFNAebbs (please also make sure the issue is happening when you create logs unless you've stored the archive already before you downgraded to 3.9.3).

Sure, uploaded! I re-upgraded and confirmed the issue is still happening. The archive is much smaller this time since I just did the upgrade again.

**Comment by Sergeij2000** [comment] 2023-09-14 07:11
Same issue with 3.9.4 Desktop on W11, virtual files enabled. I also got a problem with 3.9.4 when printing files from the NC folder via Chrome: Here and then the printer spooler throws an error, that the file to be printed couldn't be found and stops printing. Issue disappears when downgrading to 3.9.3.

**Comment by xavier-rivas** [comment] 2023-09-14 21:30
Hi, I have the same issue, after upgrading Nextcloud Client 3.9.4 from 3.9.3. Also %APPData%\Nextcloud\logs is flooding with small logs. The blue and green icon change almost every second.

I have Windows 11 and Nextcloud server 27.0.2

**Comment by allexzander** [comment] 2023-09-15 10:15
We've merged a few fixes and the issue is gone in those scenarios I was able to reproduce locally. Feel free to install the RC3 to see if you do not have the issue as well anymore https://cloud.nextcloud.com/s/SfGaBdqJkm9MYs3/download/Nextcloud-3.10.0-rc3-x64.msi

**Comment by Mika-6-9** [comment] 2023-09-15 11:29
Hello, same issue with rc3 :-(

**Comment by allexzander** [comment] 2023-09-15 11:35
> Hello, same issue with rc3 :-(

Can you upload your logs here https://cloud.nextcloud.com/s/YSxWcs8gFNAebbs ?

**Comment by guidobonuzzi** [comment] 2023-09-15 12:31
> We've merged a few fixes and the issue is gone in those scenarios I was able to reproduce locally. Feel free to install the RC3 to see if you do not have the issue as well anymore https://cloud.nextcloud.com/s/SfGaBdqJkm9MYs3/download/Nextcloud-3.10.0-rc3-x64.msi

Thank you for the update! I've installed the RC3 version you provided, and it appears to be working well. My client displays version 3.9.83.

**Comment by xavier-rivas** [comment] 2023-09-15 12:41
> We've merged a few fixes and the issue is gone in those scenarios I was able to reproduce locally. Feel free to install the RC3 to see if you do not have the issue as well anymore https://cloud.nextcloud.com/s/SfGaBdqJkm9MYs3/download/Nextcloud-3.10.0-rc3-x64.msi

Thank you Allezander, The RC3 version  worked for me.

Windows 11 v10.0.22621
Nextcloud Client 3.9.83

**Comment by Mika-6-9** [comment] 2023-09-15 13:29
Really sorry, I tried with the rc2 version and not the rc3 version.
With the rc3 it works.

**Closed** 2023-09-15 14:03 UTC
Labels: 0. Needs triage
