### ISSUE TITLE
Menubar icon is vertically squished.

### ISSUE THREAD

**Issue by b-a0** [nextcloud/desktop#2829] opened 2021-01-16 15:28 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour
Icon in menubar is round.

### Actual behaviour
Icon in menubar is vertically squished on displays that are not in focus.

### Steps to reproduce
1. Connect one or more DisplayLink monitors
2. Start the Nextcloud client
3. Focus one display

### Client configuration
Client version: 3.1.1

Operating system: macOS 11.1

OS language: English

Installation path of client: `/Applications/nextcloud.app`

### Logs

1. Client logfile: [2021-01-16_nc_debug.zip](https://github.com/nextcloud/desktop/files/5824634/2021-01-16_nc_debug.zip)

2. Web server error log: N/A

3. Server logfile: nextcloud log (data/nextcloud.log):  N/A

### Notes
I've opened a similar issue for another application that has the same issue [here](https://github.com/keepassxreboot/keepassxc/issues/5762).  It appears this is a Qt bug ([#88600](https://bugreports.qt.io/browse/QTBUG-88600)) and this is [fixed in Qt](https://codereview.qt-project.org/c/qt/qtbase/+/322339).  
Merging the updated Qt version into the Nextcloud client (or any other affected software) should resolve this issue.

**Comment by er-vin** [comment] 2021-01-18 08:10
Duplicate of #2584

**Comment by elsiehupp** [comment] 2021-01-19 00:05
I updated [my Qt bug report](https://bugreports.qt.io/browse/QTBUG-90370) relating to #2584, so we'll see if Qt determines that it is related.

I can try and build Nextcloud Desktop on my Mac with a newer version of Qt to see if it resolves either #2584 or this issue, #2829.

**Comment by er-vin** [comment] 2021-01-19 07:41
> I can try and build Nextcloud Desktop on my Mac with a newer version of Qt to see if it resolves either #2584 or this issue, #2829.

Yes please, that would be useful.

I'll close this ticket in favor of #2584 though.

**Closed by er-vin** 2021-01-19 07:41 UTC

**Comment by b-a0** [comment] 2021-03-07 18:54
This issue is solved for me with 3.1.3. 

The nextcloud sync icon is on the far left, compare it to the KeePass icon on the right which suffers from the same Qt bug (but KeePass didn't fix this yet).

![image](https://user-images.githubusercontent.com/25707742/110251021-c7d27f00-7f7e-11eb-848c-11ef23d12b03.png)

**Comment by haroldm** [comment] 2021-03-08 15:41
The icon is smaller than mine and centered : #2584 also seems fixed for you. I run macOS 11.2.1 and latest Nextcloud 3.1.3 from Github release. If you have any idea of what causes these bugs to be fixed for you please report !
