### ISSUE TITLE
Some files not synced

### ISSUE THREAD

**Issue by stixpunk** [nextcloud/desktop#1014] opened 2019-01-12 17:47 UTC
### Expected behaviour
Sync all files

### Actual behaviour
If Android app sync photos from phone, it's not synced on desktop. I got error "file was deleted from server", but I can see it (or can download) with android app or web ui. Next problem is some files on desktop (all images and icons) - failed without error, then skipped because previous error.
I try new installation of nextcloud, then new installation on desktop client and new (full) sync from desktop - it failed on same images and icons. On server I try first NC 14.0.2, then 14.0.6 and now 15.0.2 - same problem with all versions. Android client and web ui was ok with all versions, so I think problem must be in desktop client. Before NC, I was using OC with same files and all worked fine.

### Steps to reproduce
don't know

### Client configuration
Client version: 2.5.1 final (build 20181204)
Operating system: Windows 10 Pro 64bit
OS language: Czech (cs_CZ)
Qt version used by client package (Linux only, see also Settings dialog): 5.11.1
Installation path of client: C:\Program Files (x86)\Nextcloud

### Server configuration
Operating system: Debian 9, kernel 4.15.0-39-generic
Web server: Nginx 1.15.8
Database: MariaDB 10.3.11
PHP version: 7.2.13
Nextcloud version: 15.0.2 (tried also with 14.0.2 and 14.0.6)
Storage backend (external storage): only local disk

### Logs
In nginx error log I found these errors:
`2019/01/12 18:02:17 [error] 8145#8145: *4160 open() "/data/www/xxxxx/public_html/remote.php/dav/files/stix/Mobile backup/Foto/Camera/DSC_0454.JPG" failed (20: Not a directory), client: x.x.x.x, server: xxxxx, request: "GET /remote.php/dav/files/stix/Mobile%20backup/Foto/Camera/DSC_0454.JPG HTTP/2.0", host: "xxxxx"`

It's error from downloading, errors from uploading not found in log. In nextcloud.log, nothing with these files found

![nextcloud](https://user-images.githubusercontent.com/3444103/51076568-724e0080-169a-11e9-8c5c-0c8c32337f4d.jpg)

**Comment by fossxplorer** [comment] 2020-08-02 18:23
@stixpunk did you find the root cause of the issue?

**Comment by stixpunk** [comment] 2020-08-02 19:10
@fossxplorer it's long time ago. if I remember correctly, it was fixed after a few updates

**Comment by er-vin** [comment] 2020-08-03 07:42
Closing since it is apparently reported as fixed.

**Closed by er-vin** 2020-08-03 07:42 UTC
