### ISSUE TITLE
[Feature request] right click on systray -> more actions : "open root folder" and "force sync now"

### ISSUE THREAD

**Issue by schmurtzm** [nextcloud/desktop#2847] opened 2021-01-20 17:38 UTC
### Expected behaviour
Right clic on systray icon (on windows client) should shows these quick options (in addition to existing):

- open main folder in explorer
- force sync now

I insist on "force sync now" because this option is very useful (if you upload pics from your smartphone you have to wait the sync, be able to force a quick sync couold be very useful (I know that we can do it in settings but it really deserve a shortcut).

These options

### Actual behaviour
Tell us what happens instead
Right clic on systray icon (on windows client) shows only these options :

- open main dialog
- pause sync
- settings
- exit 

### Client configuration

client version : 3.1.1.16134
Operating system: win 10

**Comment by FlexW** [comment] 2021-01-20 22:26
I think there is no such concept as a main folder in the Nextcloud client. The second problem can be solved more elegantly with the new push notifications available in the next release (3.1.2).

**Comment by er-vin** [comment] 2021-01-21 06:42
I'd say the first part is kind of a duplicate of #1184 they ask for a double click but feature wise that'd cover the need.

As for the second part I agree, the push notifications system will solve it anyway.

I thus close this one.

**Closed by er-vin** 2021-01-21 06:42 UTC
