### ISSUE TITLE
[Bug]: Updater offers updates that don't met the required minimum macOS version

### ISSUE THREAD

**Issue by wilfreddijksman** [nextcloud/desktop#6278] opened 2023-12-10 21:28 UTC
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

Nextcloud desktop running on macOS 10.15.7 is notifying users about an update (via the Sparkle framework) while the offered update can NOT run on the version of OS. This leaves the user with a non starting Nextcloud desktop app after the update.
![Schermafbeelding 2023-12-10 om 22 17 26](https://github.com/nextcloud/desktop/assets/1773594/6da15acc-d793-492e-8778-7177c1775941)

### Steps to reproduce

1. Mac with macOS 10.15.7 (also applies to other versions).
2. Install Nextcloud desktop 3.9.4 (last support of macOS 10.14 and higher, see https://docs.nextcloud.com/desktop/3.9/installing.html#system-requirements & https://docs.nextcloud.com/desktop/3.10/installing.html#system-requirements).
3. Open Nextcloud desktop.
4. Go to Settings
5. Click General
6. Click Check for updates
7. The latest updated is offered while not compatible with the macOS version.

### Expected behavior

The update should NOT be offert or at least the "Install update button" should be disabled.

The Sparkle framework supports setting the minimum required macOS version via `<sparkle:minimumSystemVersion>`. See https://sparkle-project.org/documentation/publishing/#minimum-system-version-requirements for more information.

### Which files are affected by this bug

Nextcloud client application installed on target macOS system

### Operating system

Mac OS

### Which version of the operating system you are running.

macOS 10.15.7

### Package

Appimage

### Nextcloud Server version

27.1.4

### Nextcloud Desktop Client version

3.9.4

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [X] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by wilfreddijksman** [comment] 2023-12-10 21:35
Relates to #6176 but that issue is missing above mentioned solution.

**Comment by joshtrichards** [comment] 2023-12-26 21:30
Duplicate of #6198

**Closed by joshtrichards** 2023-12-26 21:30 UTC
Labels: 0. Needs triage, os: :apple: macOS, feature: :inbox_tray: install and update
