### ISSUE TITLE
3.0.1 Client on Gnome missing title bar for settings window

### ISSUE THREAD

**Issue by Digitalone1** [nextcloud/desktop#2377] opened 2020-09-07 07:54 UTC
I updated the Nextcloud Desktop Client to the latest `3.0.1` version on Arch Linux Gnome Wayland. This new version is a big regression in my opinion. It's not only ugly compared to the previous, but it misses the title bar and the close button. 

This means I can't move the interface and can only close it from the Activity View. Besides, if I try to reopen the client, nothing happens, leaving the process running in background while I can't access to the user interface.

I downgraded to `2.6.5` version and added `nextcloud-client` package to the pacman ignore list. I won't update it till these issues will be resolved.

I switched from Mega (which offered much more GB free) to Nextcloud because of the usable UI client on Gnome Desktop. If these regression won't be fixed, I will take in consideration to switch to another cloud service.

### Expected behaviour
1. Ability to close the client UI
2. Ability to move the the client UI on the desktop
3. Ability to reopen the client UI after closing it

### Actual behaviour
1. Missing the ability to move the client UI because the titlebar is missing
2. Missing the ability to close the client from the UI because there's no command, therefore one is forced to close it from the Activity View
3. Missing the ability to reopen the client. The only way is to shut down the process from System Monitor and reopen the client from scratch

### Operating system:
Arch Linux
Gnome Wayland
nextcloud-client 3.0.1-1
qt5-base 5.15.0-5

**Comment by er-vin** [comment] 2020-09-07 11:39
@jancborchardt guidance welcome

**Comment by monreal** [comment] 2020-09-07 20:21
I spent some hours yesterday trying to get the new version (3.0.1 from flathub) to work on Fedora 32 with GNOME Shell. In the end I installed the "Kstatusnotifieritem/appindicator support" extension as a workaround. Without it, I would need to open the settings window right after starting in order to keep some kind of sync indicator. I found no other way to reopen the main window after it automatically disappears at some point like switching desktops.

It would be nice to have this app work on stock GNOME shell without tray extensions. It would also be nice to have it look and feel less out of place. The new main window actually looks fine to me, but it behaves like no other app (unable to move, just disappears etc).

**Comment by er-vin** [comment] 2020-09-08 11:21
Out of curiosity, @monreal, since GNOME decided to remove the systray how do other non GNOME (third party) applications with systray behave? They don't get a tray icon either? I guess you struggle with those as well?

Just trying to figure out what others use as strategy to cope with this GNOME decision.

**Comment by Digitalone1** [comment] 2020-09-08 11:36
They behave good because if you launch them from the activity, the running instance is showed, like the old version of Nextcloud Client.

Besides, they have a title or header bar to move the window through the desktop. Just like the old Nextcloud Client version. 

It's sad to say, but who developed this new version didn't had in mind Gnome Shell, which is quite disappointing.

**Comment by monreal** [comment] 2020-09-08 17:37
> Out of curiosity, @monreal, since GNOME decided to remove the systray how do other non GNOME (third party) applications with systray behave? They don't get a tray icon either? I guess you struggle with those as well?
> 
> Just trying to figure out what others use as strategy to cope with this GNOME decision.

I don't think I use any apps that provide a tray icon. Then again maybe the apps actually offer tray support but I just don't see it. Point is: I can use all other apps out oft the box and don't miss any functionality.

To be fair, I actually like having the tray icon for Nextcloud. I am not aware of any solution in GNOME for apps of this type.

**Comment by tomWhilbert** [comment] 2020-09-08 17:56
What distro are you using?  I'm using arch and the 3.0.1 client runs in the menu.  i enabled this by checking "Launch at System Startup" under "General Settings".

**Comment by Digitalone1** [comment] 2020-09-09 13:43
I'm sorry to say that I had to switch to another service.

For your future improvement, take a look at tresorit for an app that works good on various platforms.

Thanks anyway for your work.

**Comment by jancborchardt** [comment] 2020-09-10 10:24
So, the specific issue is:

> it misses the title bar and the close button.

I can confirm this and it happens for any of the dialogs (settings, sharing, etc.). And yeah, the best fix would be to just show the title bar again. :) 

![image](https://user-images.githubusercontent.com/925062/92717496-8c088500-f360-11ea-989b-2a0f00d49d4e.png)

**Comment by er-vin** [comment] 2020-09-10 10:32
Oh, my bad, I misunderstood... I had so many reports about the new window I misread and didn't assume the settings window.

OK, so that one we didn't change... it should still have the title bar like before.
Actually just tested the 3.0.1 AppImage on my Ubuntu VM with Gnome Shell and it still has the title bar as expected.

That starts to feel like something broken downstream...

**Comment by monreal** [comment] 2020-09-20 19:38
> I spent some hours yesterday trying to get the new version (3.0.1 from flathub) 
> to work on Fedora 32 with GNOME Shell. In the end I installed the
> "Kstatusnotifieritem/appindicator support" extension as a workaround. 

Small update: the workaround proved to be not very reliable. The app never started automatically and during the last few days I did not manage to start it at all (seemed to hang at startup). This was using Wayland session (default on Fedora 32). After falling back to Xorg session (which needs manual changes to some config files, as there is no longer a session selection on the login screen) the Nextcloud app now seems to work flawlessly.

As I am not sure how long falling back to Xorg session will even be possible it would be very nice if Wayland support would be improved in Nextcloud sync.

**Comment by bidetaggle** [comment] 2020-12-12 15:07
@er-vin 
It's often a necessity to have an eye on the nextcloud client window while moving files around on another space of the screen and feel as we lost a feature over fanciness. 

@monreal 
> To be fair, I actually like having the tray icon for Nextcloud. I am not aware of any solution in GNOME for apps of this type.

On GNOME, install the [tray icons extension](https://extensions.gnome.org/extension/1503/tray-icons/) and the nextcloud status will appear on the top bar, right side. It will have a similar behavior than on mac, you can click on it.

**Comment by mjanssens** [comment] 2020-12-17 13:22
Thanks @bidetaggle, I had [AppIndicator and KStatusNotifierItem Support](https://extensions.gnome.org/extension/615/appindicator-support/) installed and the systray icon was gone since desktop client 3.1.0. Your suggestion works, so i uninstalled AppIndicator and KStatusNotifierItem Support.
Running Gnome Shell Wayland 3.38.2
The funny thing is that this extension is based on Topicons Plus extension.

**Comment by garrett** [comment] 2021-03-02 08:13
Bot: Many people are still waiting for this to be fixed. It's not stale.

**Comment by garrett** [comment] 2021-04-12 08:33
This is still a problem.

**Comment by FlexW** [comment] 2021-05-11 08:52
@garrett Are you still having this issue with 3.2.1? I've tested it on GNOME, and there are titlebars on the settings window. Can you confirm that? However, there are no titlebars on the main dialog, but this is a different story.

**Comment by FlexW** [comment] 2021-05-12 07:27
It is expected that the main dialog has no window borders and it's not resizeable. The main dialog is thought as a tray popup, like the ones from OneDrive, Googe Sync and DropBox. I will close this issue.

**Closed by FlexW** 2021-05-12 07:27 UTC
Labels: bug, design, os: :penguin: Linux

**Comment by garrett** [comment] 2021-05-12 07:42
> The main dialog is thought as a tray popup, like the ones from OneDrive, Googe Sync and DropBox. I will close this issue.

But it's definitely not a popup and acts unlike any other software, at least on GNOME.

So you're saying the window is _intended_ to be so weird and buggy?

**Comment by FlexW** [comment] 2021-05-12 07:58
@garrett There are two problems: Problem 1 is that GNOME dropped tray icon support and if you have not installed the tray icon extension, the main dialog will popup at random positions. Problem 2 is, if you are using Wayland, the main dialog will poup at a random position even if you have installed the tray icon extension. That is because the client uses the global cursor position to find the place where it should open, and on Wayland there exists no concept of a global cursor position. Unfortunate, there is no other possibility on Linux to open a window at the position of the tray icon.

These tray menus are something that is more common in the Windows world. As far as I know, this has been implemented in the Nextcloud client to align the client more with services like DropBox and OneDrive, to make it (mostly Windows) users easier to transition. In think a solution to this problem could be to make it configurable in the configuration file if the main dialog is a regular window (window borders, resizeable) or a tray popover. On Linux I would default to setting the main dialog as a regular window, due to the reason I mentioned above. As Ubuntu switched to Wayland per default lately, more and more people will stumble upon this problem.

@jancborchardt any thoughts?

**Comment by janvlug** [comment] 2021-05-12 10:49
@FlexW I would highly appreciate your suggestion of the window behaving as a regular window by default on Linux. I am on Fedora 34 (default GNOME on Wayland) user. Your suggestion would make using Nextcloud desktop much more intuitive and aesthetic in this environment. I am a very experience Fedora Linux user, but I had troubles understanding how to use Nextcloud desktop now. For inexperienced users (that have no clue about tray icons and Wayland) on this platform the Nextcloud desktop behavior is now very hard to understand.

I think you suggestion has even been implemented already once. See for more details also: https://github.com/nextcloud/desktop/pull/2649.
