### ISSUE TITLE
Ability to scroll to top of the activities window

### ISSUE THREAD

**Issue by munrobasher** [nextcloud/desktop#6432] opened 2024-02-09 13:45 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you want to have the same feature implemented.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Feature description
The activities window on the client can have a lot of entries in it if you've (say) just added loads of files. If there is a sync error, it says "See below". Except the message you're looking for is at the top of the activity list.

There is no way to get back to the top of the activities list without (AFAIK) using the mouse scroll wheel or the up/down keys. Scroll bars would be very useful:

![image](https://github.com/nextcloud/desktop/assets/13134946/2712fa7c-986f-477f-944d-03d19d902eae)

**Comment by joshtrichards** [comment] 2024-08-16 03:36
Duplicate of #5536

**Closed by joshtrichards** 2024-08-16 03:36 UTC
Labels: enhancement, feature: :zap: activity and :bell: notification
