### ISSUE TITLE
Windows Nextcloud client installer restarts computer without prompt or warning

### ISSUE THREAD

**Issue by Normonator** [nextcloud/desktop#831] opened 2018-11-14 19:34 UTC
### Expected behaviour
Installation prompts to restart computer allowing user to save any ongoing work.

### Actual behaviour
Installer restarts immediately after displaying Run Nextcloud prompt and does not allow clicking on finish before restarting.

### Steps to reproduce
1. Have older version of Visual C++ Redistributable (prompting vc installer to reboot if not suppressed)
2. Install nextcloud client
3. Computer restarts immediately, resulting possibly in lost work.

### Client configuration
Client version:
2.5
Operating system:
Windows 10 1809 Build 17763.55 (up to date)
OS language:
English US
Installation path of client:
C:\Program Files (x86)\Nextcloud

### Logs

Event Viewer entry:
The process C:\Program Files (x86)\Nextcloud\i18n\vcredist_x64.exe (COMPUTERNAME) has initiated the restart of computer COMPUTERNAME on behalf of user USERNAME for the following reason: Application: Installation (Planned)
 Reason Code: 0x80040002
 Shutdown Type: restart
 Comment:

**Comment by RiSK1979** [comment] 2018-11-15 09:01
I experienced the same issue on two different Windows 10 computers.

**Comment by hillebr** [comment] 2018-11-15 16:56
...same here on two different Windows 10 computers.

**Comment by JarbyDev** [comment] 2018-11-16 00:07
Same Here, I tried on Windows 10 Computer and Windows Server 2016.

**Comment by pfeiferocks** [comment] 2018-11-17 22:24
Same here on 2 Windows 10 Computers and i will not try it on Windows Server 2016.

**Comment by gr4ssi** [comment] 2018-11-19 08:58
Wow, this sucks big time. Just had that too. Reason is, vcredist_x64.exe requests reboot without asking. 

> Vom Prozess "C:\Program Files (x86)\Nextcloud\i18n\vcredist_x64.exe (NB-xxx)" wurde auf Anforderung des Benutzers "NB-xxx\abc" das Ereignis "Neustart" für den Computer "NB-xxx" aus folgendem Grund initiiert: "Anwendung: Installiert (geplant)"
>  Ursachencode: "0x80040002"
>  Herunterfahrtyp: "Neustart"

This is definitely not expected behaviour for a desktop client. I almost put that on our server.    :-(

**Comment by toms1342** [comment] 2018-11-26 07:30
vcredist_x64.exe ignores/overwrites the "/norestart" switch of theNC 2.5.0 .msi client installer.

A fix of this behavior is highly appreciated for every admin how plans a rollout of the new client on productive machines.
Unfortunately we did not find a way to work around this.
Any help is welcome!

**Comment by Marcwa19197** [comment] 2018-11-26 10:51
i have exactly the same issue on two windows 10 computers, really annoying.

**Comment by stephanhendl** [comment] 2018-11-26 12:52
Same here with a couple of Windows 10 clients.

**Comment by Siedlerchr** [comment] 2018-12-07 21:50
I can confirm this with the latest release 2.5.1 on Windows 10 x64 .

**Comment by mioiox** [comment] 2019-01-04 07:57
I can confirm the issue stays with the current version (2.5.1) of NC client. Really annoying. Here is the event message from the System event log in English:

The process C:\Program Files (x86)\Nextcloud\i18n\vcredist_x64.exe (Computername) has initiated the restart of computer Computername on behalf of user Domain\Username for the following reason: Application: Installation (Planned)
 Reason Code: 0x80040002
 Shutdown Type: restart
 Comment:

**Comment by Shorty-KS** [comment] 2019-01-08 12:52
Ich habe zwar keine Lösung, aber einen funktionierenden Workaround:

Wie hier schon berichtet wurde, liegt das Problem an der Installation der vcredist_x64.exe, die den harten Neustart macht (Beim Nextcloud-2.5.1-setup wird automatisch die Version 14.14.26405.0 der der vcredist_x64 installiert). Installiert man aber vor dem Nextcloud-2.5.1-setup eine aktuellere Version der vcredist_x64.exe, erfolgt kein Neustart!

Eine neuere Version (14.16.27012.6) findet man z.B. hier:
https://support.microsoft.com/de-de/help/2977003/the-latest-supported-visual-c-downloads

Wenn man das ganze, so wie ich, per PowerShell App Deployment Toolkit macht, wäre die Reihenfolge also ungefähr so:

If ($ENV:PROCESSOR_ARCHITECTURE -eq "AMD64") {Execute-Process -Path 'VC_redist.x64.exe' -Parameters '/S /norestart'} 

If ($ENV:PROCESSOR_ARCHITECTURE -eq "AMD64") {$ReturnCode = Execute-Process -Path 'Nextcloud-2.5.1-setup.exe' -Parameters '/S /norestart' -IgnoreExitCodes ‘1223’ -PassThru}

**Comment by chapb** [comment] 2019-01-22 02:47
Same problem here.

**Comment by jellykells** [comment] 2019-01-22 19:20
Same issue on Windows 7 x64 SP1.

**Comment by moorsey** [comment] 2019-01-24 08:08
Duplicates of this #496 and #1040

**Comment by camilasan** [comment] 2019-01-25 14:59
Hi All!
Please, try this installer: https://download.nextcloud.com/desktop/daily/Windows/Nextcloud-2.5.1.5037-daily-20190125.exe
Let me know if it works for you!
Thanks @gr4ssi for the help!

**Comment by gr4ssi** [comment] 2019-01-25 16:13
Works for me on nearly naked Win7 DE 64Bit Prof. Thanks for updating the client. :-)

**Comment by Fr3llD** [comment] 2019-02-06 09:54
Same with the [technical preview](https://download.nextcloud.com/desktop/prereleases/virtualdrive/Nextcloud-virtualdrive-techpreview.exe). Maybe you should update that 

On Windows 2016 and Windows 10.

**Comment by Fortyseven** [comment] 2019-02-15 17:05
Thankfully, VirtualBox actually saved it's state before the reboot could finish, otherwise I might have lost some work this morning, in addition to the disruption. This is _awful_ behavior.

**Comment by jellykells** [comment] 2019-02-20 11:55
> Hi All!
> Please, try this installer: https://download.nextcloud.com/desktop/daily/Windows/Nextcloud-2.5.1.5037-daily-20190125.exe
> Let me know if it works for you!
> Thanks @gr4ssi for the help!

Works for me :-)

**Comment by burner-** [comment] 2019-03-26 14:28
I just take installer from https://nextcloud.com/install/#install-clients  for fresh install. And it restarted computer without any warning. 
"The process C:\Program Files (x86)\Nextcloud\i18n\vcredist_x64.exe (PC2) has initiated the restart of computer PC2 on behalf of user PC2\user for the following reason: Application: Installation (Planned)"

**Comment by xrammit** [comment] 2019-03-26 15:02
A new client version (2.5.2) was released but the Nextcloud website havn't been updated yet.
@camilasan Can you please ask the website maintainer to update the link to point to the new version?

**Comment by affinityv** [comment] 2019-03-26 16:45
@xrammit 2.5.1 is the latest actual release.  There is a newer tag for 2.5.2, but it isn't released yet.

https://github.com/nextcloud/desktop/releases

**Comment by xrammit** [comment] 2019-03-26 16:55
> @xrammit 2.5.1 is the latest actual release. There is a newer tag for 2.5.2, but it isn't released yet.

No, in my opinion version 2.5.2 was already released as there are (stable) binaries available on nextcloud.com for all platforms [1] and the new version was also published on the stable Nextcloud desktop client PPA [2].

[1] https://download.nextcloud.com/desktop/releases/
[2] https://launchpad.net/~nextcloud-devs/+archive/ubuntu/client

**Comment by e-alfred** [comment] 2019-06-09 18:38
> Yet, it needs to reboot before for the Windows Explorer integration to work!

Is a reboot really needed? Couldn't it be done by killing/restarting the Explore.exe process to enable the integration into the Windows Explorer instead of a sudden reboot?

**Comment by Dennis360ict** [comment] 2019-06-09 19:15
> Is a reboot really needed? Couldn't it be done by killing/restarting the Explore.exe process to enable the integration into the Windows Explorer instead of a sudden reboot?

The shell of windows is dependent on explorer.exe. Or actually explorer starts the shell (windows desktop) as you know it. So restarting explorer restarts your shell, which can gives weird issues as not all running apps can handle that.

Its also the reason bad explorer plugins could take down whole windows shell.

At least, this is how its been since windows 95, some of the newer builds of win10 might handle stuff differently, although i doubt it.

Anyway, a reboot for explorer integration isn’t that bad in my opinion. Windows needs lots of restarts anyway so one more isnt that bad in my opinion.

**Comment by jernejs** [comment] 2019-06-09 19:47
I know several programs that simply restart explorer.exe to get the shell extensions to load, and AFAIK, WinRAR uses some method to reload the extensions without doing anything visible to Explorer at all.

> Windows needs lots of restarts anyway so one more isnt that bad in my opinion.

What? This hasn't been true at all for years. Except for the updates, there's no need to reboot Windows nowadays at all.

**Comment by jancborchardt** [comment] 2019-10-27 19:01
Was confirmed above to be fixed, by @jellykells at https://github.com/nextcloud/desktop/issues/831#issuecomment-465544601 → closing hence. :)

**Closed by jancborchardt** 2019-10-27 19:01 UTC
Labels: bug, high, os: :door: Windows

**Comment by RadioactiveTapir** [comment] 2022-05-14 11:50
Problem still exists. Installer Nextcloud-3.5.0-x64.msi.

**Comment by jancborchardt** [comment] 2022-05-16 12:27
@RadioactiveTapir sincw the original issue is several years old, it is likely a different underlying issue. Could you open a new issue, filling out the issue template and provide logs to help debug the issue? Thanks

**Comment by Tower195** [comment] 2022-05-23 20:00
It happened again to me today, with Nextcloud update to version 3.5.1 on Windows 10 x64 . Hard to believe this is allowed to happen...

**Comment by gr4ssi** [comment] 2022-05-23 23:38
It didn't happen to me since the last fix.

**Comment by juliannoble** [comment] 2022-06-15 18:02
I know this is an old issue - but it's still happening, and still surprising.
This discourages regular updating and as such is bad for security.

**Comment by moorsey** [comment] 2022-07-11 09:11
@13xforever As per comment about, fresh bug has been requested

Looks like there are some other tickets #4305 #3551 #4377 Suggest following there
