### ISSUE TITLE
[Bug]: Automatik installation of 3.9.1 failes

### ISSUE THREAD

**Issue by geraldurbas** [nextcloud/desktop#5945] opened 2023-08-01 07:27 UTC
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

The automatic Update failes. After setup and Windows restart, it shows:
After some restarts and a manual Update, it switched back to the previous version.

![image](https://github.com/nextcloud/desktop/assets/121263/550a5bf3-5055-4ffe-af87-3958c3dc1748)
After some Oks the message switches to:
![image](https://github.com/nextcloud/desktop/assets/121263/06da1eb4-ac8c-4efd-a3f5-b45ad5283398)

### Steps to reproduce

1. let the automatic Update happen
2. Oks +
3. System restart
...

### Expected behavior

finished Update;)

### Which files are affected by this bug

libcryptr-1_1-x64.dll is missing

### Operating system

Windows

### Which version of the operating system you are running.

Windows 10

### Package

Appimage

### Nextcloud Server version

25.0.9

### Nextcloud Desktop Client version

3.9.1

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 3.3.6 to 3.4.0)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by cnmicha** [comment] 2023-08-06 08:08
Same issue here

**Comment by cnmicha** [comment] 2023-08-06 08:10
Probably duplicate of #5926

**Comment by joshtrichards** [comment] 2024-08-14 16:09
Duplicate of #5924

**Closed by joshtrichards** 2024-08-14 16:09 UTC
Labels: 0. Needs triage, bug, os: :door: Windows, feature: :inbox_tray: install and update
