### ISSUE TITLE
[2.5.1] client marks ignored files as sync conflict

### ISSUE THREAD

**Issue by Germano0** [nextcloud/desktop#566] opened 2018-08-18 10:55 UTC
I installed 2.5.0 over a previous 2.3.3 version. With the old client version, the folders synchronization was okay, with 2.5.0 instead it is stuck on a specific folder (let's call it "LLL") marked with "there are unresolved conflicts, click for details". I click and I simply get a list of files being ignored because they are usually temp or backup files, like `.foo.bar`, `foo.bar~`, `~foo.bar`.
So there are no conflicts, only files being ignored.

Note that as soon the "LLL" folder start the sync, I get the alert message and the sync stops

**Comment by zippytiff** [comment] 2018-10-12 13:11
Hi, 

I have just tried my 1st 2.5 build (Nextcloud-2.5.0.61459-daily-20181011)

I can see the Files ignored by Patterns, has been dramatically reduced, which is good.

However I also see this issue, except that despite hidden files being syncd is on, I get:

File is listed on the ignore list for ~$sampleexcel.xls (yes the file is closed)

Also im getting error on various files for Conflicts, where Server version downloaded, local copy renamed and not uploaded

finally .iTunes Preferences.plist thowing an error

In the end I just want everything to sync, unless either chosen by the server (which that feature was in this version eg settings controlled by the server !) or by me.

Me just seeing a Green tick as per 2.3.3

I will revert back to that version for now

Thanks ZT

**Comment by heidlma** [comment] 2018-10-31 09:55
I am seeing the same issue. The 2.5 client gives me "unresolved conflicts", but when I click on the message ("Click for details"), nothing happens. 

I am running on macOS HS, client version is 2.5.0rc1 (build 20181026)

After downgrade to 2.3.3 client, all seems to be ok again.

**Comment by augustseptember** [comment] 2018-11-14 21:08
In the 2.5git (ubuntu18.04) i get the same "unresolved conflicts". If I click on it, it shows me a very long list of ignored files, which should not be ignored anymore due to the reduced ignore patterns.

**Comment by TP75** [comment] 2018-11-15 21:00
**Confirmed.** The same issue with macOS 10.12 and NC Client _Nextcloud-2.5.0.20181112.pkg_ i.e. Version _2.5.0daily (build 20181112)_ for all the users of our local NC 13.0.7 server.

One may consider the Nextcloud Client Manual section [Conflicts](https://docs.nextcloud.com/desktop/2.5/conflicts.html) to manually resolve the a.m. issue. However, I am unsure if the paragraph [Uploading conflicts (experimental)](https://docs.nextcloud.com/desktop/2.5/conflicts.html#uploading-conflicts-experimental) might be useful for a workaround or would be misleading.

Please be aware there appears to be a more general documentation issue _What is the current Client Manual?_ #839 One would expect the availability of a documentation for both the 2.3 and the 2.5 NC Client.

**Comment by Germano0** [comment] 2018-11-15 21:09
I still experience the problem on 2.5.0 final.
I will not push nextcloud-client to Fedora / EPEL stable repository until this problem will be fixed

**Comment by wiserweb** [comment] 2018-11-16 21:01
Confirming that the issue described by OP is still occurring. 
It occurs on Linux as well.
The MacOS client with 2.3.3 does not have this bug.
I suppose this will have to be a new test-case that will be added to QA so to ensure that this functionality is properly tested before shipping as release as production ready.

**Comment by rullzer** [comment] 2018-11-19 12:08
Does anybody have log files or steps to reproduce this?
I tried it locally and it seems just to work no mater what I put in the ignore pattern

**Comment by augustseptember** [comment] 2018-11-19 12:46
Trying to sync a file with ~ at the end of the filename the client logs say:

`...[_csync_merge_algorithm_visitor 	INSTRUCTION_IGNORE             client file: path/to/file/file_with_tilde~
...
[csync_ftw 	 <= Closing walk for  with read_from_db 0
[csync_update 	Update detection for remote replica took 74.093 seconds walking 31725 files
[csync_memstat_check 	Memory: 2486580K total size, 873896K resident, 30828K shared
[OCC::SyncEngine::slotDiscoveryJobFinished 	#### Discovery end ####################################################  91355 ms
...
[OCC::PropagateItemJob::scheduleSelfOrChild 	Starting INSTRUCTION_IGNORE propagation of "path/to/file/file_with_tilde~" by OCC::PropagateIgnoreJob(0x55ddcab01f60)
[OCC::PropagateItemJob::done 	Could not complete propagation of "path/to/file/file_with_tilde~" by OCC::PropagateIgnoreJob(0x55ddcab01f60) with status 6 and error: "Die Datei ist in der Ignorierliste geführt."
[OCC::ActivityWidget::slotItemCompleted 	Item  "path/to/file/file_with_tilde~"  retrieved resulted in  "Die Datei ist in der Ignorierliste geführt."
[OCC::ActivityWidget::slotItemCompleted 	Item  "path/to/file/file_with_tilde~"  retrieved resulted in error  "Die Datei ist in der Ignorierliste geführt."
[OCC::ActivityListModel::addErrorToActivityList 	Error successfully added to the notification list:  "Die Datei ist in der Ignorierliste geführt."`

But in the ignore list is no entry for files with ~ 
![ignorelist](https://user-images.githubusercontent.com/6906270/48707836-fcc93500-ec00-11e8-9672-11033f7dce5b.png)

**Comment by augustseptember** [comment] 2018-11-19 12:59
Trying to sync a file with ~ at the end of the filename the client logs say:

`...[_csync_merge_algorithm_visitor 	INSTRUCTION_IGNORE             client file: path/to/file/file_with_tilde~
...
[csync_ftw 	 <= Closing walk for  with read_from_db 0
[csync_update 	Update detection for remote replica took 74.093 seconds walking 31725 files
[csync_memstat_check 	Memory: 2486580K total size, 873896K resident, 30828K shared
[OCC::SyncEngine::slotDiscoveryJobFinished 	#### Discovery end ####################################################  91355 ms
...
[OCC::PropagateItemJob::scheduleSelfOrChild 	Starting INSTRUCTION_IGNORE propagation of "path/to/file/file_with_tilde~" by OCC::PropagateIgnoreJob(0x55ddcab01f60)
[OCC::PropagateItemJob::done 	Could not complete propagation of "path/to/file/file_with_tilde~" by OCC::PropagateIgnoreJob(0x55ddcab01f60) with status 6 and error: "Die Datei ist in der Ignorierliste geführt."
[OCC::ActivityWidget::slotItemCompleted 	Item  "path/to/file/file_with_tilde~"  retrieved resulted in  "Die Datei ist in der Ignorierliste geführt."
[OCC::ActivityWidget::slotItemCompleted 	Item  "path/to/file/file_with_tilde~"  retrieved resulted in error  "Die Datei ist in der Ignorierliste geführt."
[OCC::ActivityListModel::addErrorToActivityList 	Error successfully added to the notification list:  "Die Datei ist in der Ignorierliste geführt."`

But in the ignore list is no entry for files with ~ 
![ignorelist](https://user-images.githubusercontent.com/6906270/48707836-fcc93500-ec00-11e8-9672-11033f7dce5b.png)

**Comment by leighss** [comment] 2018-11-19 13:19
@augustseptember 
My ignore files settings looked like that until I took brianbgness' advice from #851 and reset to defaults, then lots of other entries (including ~ones) appeared in the list

**Comment by augustseptember** [comment] 2018-11-19 13:50
@leighss thanks for the advice but this doesn't change anything for me.

**Comment by rullzer** [comment] 2018-11-19 13:53
@augustseptember that is a different issue. But ~ files are ignored because they are temp files by definition.we probably can make that more clear

**Comment by leighss** [comment] 2018-11-19 13:54
That also didn't change anything for me, but  I thought it may have helped in diagnosing problem

**Comment by augustseptember** [comment] 2018-11-19 13:59
@rullzer yes there could be some fixed entries in the ignore list, which can't be deleted from that list. You would at least be informed that some patterns (~) or files (like .htacess) are generally not synced.

But why is there still the warning about conflicts in the client?

**Comment by rullzer** [comment] 2018-11-19 14:00
Note that .htaccess is blocked server side.

I do not know why the warning is there. That is why I need steps to reproduce as it doesn't happen for me. No matter what I add to the sync list. Only if create conflicts in files that are synced I see them but that is to be exepcted.

**Comment by rullzer** [comment] 2018-11-19 14:11
Ah ok at least I'm a step further. It indeed looks like the system exclude list is always read. I'm not sure how this snuck back in. I'll prepare a PR to fix that at least.

**Comment by augustseptember** [comment] 2018-11-19 14:12
hmm...
i just updated my nextcloud-client from 2.3.3 to 2.5 with your ppa for ubuntu 18.04. The yellow warnings was there from the beginning.

![conflicts](https://user-images.githubusercontent.com/6906270/48712219-83840f00-ec0d-11e8-9c3c-a7d08d831e87.png)

**Comment by leighss** [comment] 2018-11-19 14:13
Hopefully I am not muddying the waters as I do not understand the technicalities, but...

@rullzer mentioning .htaccess jogged my memory...

I did notice that amongst the many yellow ! warning logs there were two red X server error logs and when I followed them in the file manager they were .htaccess files in my synced content.

I have three locations (I'll call them A, B & C) that I sync, and one .htaccess files is in B, and the other in C. However, A & C give me a yellow ! error overall, not a red X. 

A has started to give me a green tick again (I am not sure why, perhaps after resetting defaults?) and has no error relating to an .htaccess file

**Comment by rullzer** [comment] 2018-11-19 14:39
I do not think this solves it but it should make hte list more clear: https://github.com/nextcloud/desktop/pull/860

**Comment by TrilceAC** [comment] 2018-11-21 08:39
I'm having the same conflict issue described above. With the previous version on a Ubuntu 16.04 I had no issue. I've just update to 2.5.0git using the repository and now I have lots of "File is listed on the ignore list". In my case, I use Nextcloud to sync some python projects I'm working on. This is quite useful when changing from PC to laptop or going home. Sometimes the code is not in a state that I can commit, but I want to see and finish what I was working on on a different computer. To avoid silly or prejudicial syncs I added to the ignored files the following two patterns:

*.pyc
__pycache__/*

This has been working fine for me untill now. Since the update I see the yellow flag indicating that "There are unresolved conflicts. Click for details" When I click, all *.pyc files are mark as conflictive saying that "File is listed on the ignore list."

I hope I'm not doing something obviouly wrong and that this report helps to solve the issue.

**Comment by get2him** [comment] 2018-11-21 08:43
> This has been working fine for me untill now. Since the update I see the yellow flag indicating that "There are unresolved conflicts. Click for details" When I click, all *.pyc files are mark as conflictive saying that "File is listed on the ignore list."
> 
> I hope I'm not doing something obviouly wrong and that this report helps to solve the issue.

I had the same problem with win client 2.5.0.
I've checked the option to sync hidden files in the Advanced Options -> Ignored Files Editor. 
The issue resolved.

**Comment by TrilceAC** [comment] 2018-11-21 08:59
> I had the same problem with win client 2.5.0.
> I've checked the option to sync hidden files in the Advanced Options -> Ignored Files Editor.
> The issue resolved.

I think you resolved the issue because you are now sync hidden files. I already had this option marked but the isssue is there.

As mentioned [here](https://github.com/nextcloud/desktop/issues/851#issuecomment-439654290), I have just clicked on "Restore Defaults" and the list of ignored patters has significantly increased. Before clicking OK I have added the two extra patterns I mentioned above and I have clicked OK. After clicking, Nextcloud has performed a full check for changes. While it was performing it, it was happy with the sync, but just when it ended, the yellow flag and the unresolved conflicts have come back because of the .pyc files.

**Comment by rullzer** [comment] 2018-11-21 12:34
@leighss it makes sense it showsthere are unresolved conflicts if you still have conflict files.

Of course clicking on the message should show you which files.

I guess there might be an issue with conflict files and ignored file detection. I'll try to reproduce that.

**Comment by jamincollins** [comment] 2018-11-21 22:12
I can confirm that 2.5 is reporting a file conflicts but the link only takes me to a list of ignored (hidden) files.  Manually grepping the Nextcloud tree for **_conflict** did however find a file that I was then able to remove.  This is a rather poor user experience as-is.

**Comment by augustseptember** [comment] 2018-11-22 08:31
Thanks to @jamincollins I found one single "_conflict" file among all the ignored and hidden files. After deleting this "_conflict" file the green tick was there again.
Suggestion: let users sort or filter the activity-view by conflict or ignored files. Or simply put the conflict files on top, so you can instantly see the problem. (sorry for my bad english, i hope it was clear enough)

**Comment by TrilceAC** [comment] 2018-11-22 08:42
@augustseptember @jamincollins this has helped me too. Thanks!

**Comment by rullzer** [comment] 2018-11-22 11:34
Right so conflict files and ignored files have the same icon and they are not ordered it seems.
I'll see what we can do there.

**Comment by leighss** [comment] 2018-11-22 11:42
@rullzer in the hope that it may help, a couple of observations from my case:

1. The (old) conflict files were ignored by 2.3.3, the error was only flagged when upgrading to 2.5

2. When I clicked on the link I was directed to a 'file ignored' error (I am pretty sure it was the most recent one in a long list), NOT to a conflict error. In fact there were no conflict errors, only 'file ignored' warnings

**Comment by LukeLR** [comment] 2018-11-27 10:13
Happens for me as well in 2.5.0, and is extremely annoying. I have disabled the "sync hidden files" checkmark, since I have a lot of backup and meta files in my local Nextcloud directory I don't want to sync. Also, there's symbolic links that can't be synced. I want a possibility to dismiss these warnings, since otherwise my Nextcloud is yellow all the time and I can't see if it is properly synced or not.

**Comment by dszego** [comment] 2019-01-16 20:32
Jan. 15 2019 - same as everything described above.

**Comment by koroki** [comment] 2019-02-04 21:43
Same here...

**Comment by Githopp192** [comment] 2019-03-03 16:42
Me2, just did the Client (Windows 10) Upgrade to SyncAgent, 2.5.1final (build 20181204).
Now .. SyncStatus is not green, saying conflicts .. i did remove all files manually with names ".. conficts" .. but when clicking onto the message in the NC-Client Gui "there are conflicts" .. it Shows me a lot of files, which are ignored .. but i do not see any conflict .. also, it would be very helpfull to search into this Gui context, to sort all the stuff ..

**Comment by Githopp192** [comment] 2019-03-03 21:53
Now, after Rebooting all the Stuff (Windows 10), the NC SyncAgent 2.5.1 got the green flag again.

**Comment by Biopticon** [comment] 2019-04-13 15:20
I have version 2.5.1 of the client, and the NC version is 14.0.6. My OS is Win 7 pro. NC is running on Ubuntu 18.04.
I removed all the conflicts it was reported by the client. All the entries in the log file are ignored files.  If I click on the tab to go to the log to the conflict, there is none.  I tried both Sync hidden files on or off.  I reset the default ignore files option. But still, three folders on my drive marked after the scan are yellow.

Also, I get a warning that OpenOffice app which I do not have has a new version. How come?

**Comment by bunjes** [comment] 2019-05-28 06:28
Still present in MacOS Client 2.5.2git (Build 20190319)

**Comment by David-Lor** [comment] 2019-06-06 17:05
Still present under Ubuntu (2.5.2git)

**Comment by paulsommer** [comment] 2019-06-18 08:10
Same here. The activity list is flooded with yellow exclamation marks.rendering it useless for finding real conflicts.

**Comment by ppochon** [comment] 2019-07-07 02:32
Same here on ubuntu 16.04, "le fichier ou dossier a été ignoré car il est masqué".

**Comment by cloo** [comment] 2019-08-02 07:13
Same here on Windows 10 client / Ubuntu 18.04 server / Nexcloud 16.0.3

**Comment by Derridaralalala** [comment] 2019-09-13 11:27
This is still an issue in MAC OS clients from 2.5.2 up to 2.6 RC1. Crazy.

**Comment by keunes** [comment] 2019-09-16 21:49
I was going to create a new issue but GitHub suggested me this one instead. I had the impression I already had similar issues under 2.3, but I just upgraded to 2.5.3daily-Win64 (build 20190725) on Windows 10 and I (still) have the issue for sure. Indeed the most annoying thing is to be wrongly suggested that things are off while all actually is fine, as indicated by @LukeLR.

**Comment by keunes** [comment] 2019-09-16 21:54
Also experiencing this issue?
---
**Please consider giving a thumbs-up to the original post.** It can help indicate this issue as one that's affecting many users.

**Comment by paulsommer** [comment] 2019-09-16 21:56
It's hard to believe that such a simple issue is not fixed after one year. Seems as if the developer is not interested and someone has to fork the whole thing to fix that annoying error.

**Comment by Derridaralalala** [comment] 2019-09-22 10:22
@paulsommer agree. the only working version in this matter seems to be Nextcloud-2.3.3.84. Even Version 2.6.0rc1 does not fix the issue(s). (@camilasan)

**Comment by LukeLR** [comment] 2019-09-22 10:36
Surprisingly, the issue resolved itself a few days after my original reporting. I didn't have this problem for months now, it was only a short period.

**Comment by camilasan** [comment] 2019-09-23 17:48
I can't reproduce the problem mentioned by @Germano0. I see that in my file manager a conflict file has the same icon as an ignored file but that is not the case in the client main window. Would you all affected by the problem mind sharing some screenshots?

**Comment by tomdereub** [comment] 2019-09-23 21:07
Here an example with Nextcloud 2.5.3daily-Win64 (build 20190725), on windows 10:

![image](https://user-images.githubusercontent.com/16243499/65462780-cb3f7c80-de56-11e9-8744-64f137c66cca.png)

**Comment by keunes** [comment] 2019-09-24 07:20
Using Version 2.5.2git on Ubuntu 18.04.3 LTS. 3 types of 'errors' that shouldn't be (hidden, black list, ignore list):
![Screenshot from 2019-09-24 09-17-14](https://user-images.githubusercontent.com/11229646/65489904-6dd61a80-deac-11e9-8286-6eca09858930.png)

**Comment by TrilceAC** [comment] 2019-09-24 08:12
Some time ago, I thought that I was suffering this issue. In reality I did not:

In my case, there were files that had sync issues because they were written twice or more times in really shorts periods of time. Think about a small sqlite database, or when coding or writing a document, when you save and immediately after saving you realise about a typo: I save, I fix the typo and save again in less than a few seconds. In those situations Nextcloud isn't fast enough to properly make the whole synchronization procedure. This causes a local conflict in a file that you don't expect. And this changes the icon in the notifications bar from green to yellow.

The problem is that I hardly realise about this issue because when I go to the Activity tab in Settings: I have many ignored files that are reported with the yellow flag. This long list makes me difficult to find the actual conflict files.

I program in python under a nextcloud directory. Among others, I exclude the *.pyc files, but they are reported in the activity tab, which is fine, but the list is long, and therefore I hardly find actual conflicting files when there are. If for some reason I store a small sqlite database that I have forgotten to exclude for synchronization, and it is quickly changed many times by the program, this is a perfect candidate for conflict. In the end, it is not critical, since the latest version of the file is stored locally, but it might be somehow annoying.

Therefore, I recommend you to check twice that in fact you are not suffering from this. There might be a silly conflict hidden among that long list of ignored files.

Hope this helps someone.

**Comment by tomdereub** [comment] 2019-09-24 10:30
Ok, so we don't speak about the same issue. For me nextcloud's icon is green, I don't have conflicts for now, but I just don't want the ignored files to appear in the activity tab. Otherwise, when a conflicts appears, it's almost impossible to find which file is concerned because itqs lost in the middle of those thousand lines of "ignored files".

**Comment by David-Lor** [comment] 2019-10-05 14:50
Seems to be fixed on version 2.6.0 :)

**Comment by alexdetsch** [comment] 2019-10-07 14:41
@David-Lor No, for me it was not resolved. It still uploaded all the previously ignored files :/

**Comment by bunjes** [comment] 2019-10-09 10:11
Sorry, but the issue is still present in Version 2.6.0stable (build 20190927) on MacOS: Greenish 
Conflict Panel not clickable and exclamation-mark icon:
<img width="365" alt="tmp" src="https://user-images.githubusercontent.com/12167647/66472638-f1d3f900-ea8d-11e9-9c8c-8c297d849422.png">

**Comment by arenaq** [comment] 2019-10-12 19:07
Thank you Nextcloud for spending 2 hours to fix this after updating to new version. Solution? SSH to server, check the files against backup - OK. Run `php occ files:scan`. Delete local files and reinstall the application. Do the sync. Find out this issue is here for one year. Look for an alternative. Lived happily every after.

**Comment by keunes** [comment] 2019-10-13 08:17
Thanks @camilasan for adding this to the 2.7 milestone! :)

**Comment by f-soto** [comment] 2019-11-28 22:02
I had this issue. Many files not synced due to being hidden. Yello exclamation.
It was caused when I used cp to copy some files over manually and then ran the occ scan command against that particular folder:

# sudo -u www-data php occ files:scan --path="user/files/backup"

Unfortunately, it took AGES to run the command on a small folder to I killed it only to find that it was duplicating the folder structure within the backup folder and caused a corruption. I had to then manually remove these files from my desktop sync location by enabling the "view hidden files" in windows. I search ed for *.~* and removed the temp/corrupted files and cleaned up the directories and then all was well.

Moral of the story, done use the --path switch with occ.

**Comment by er-vin** [comment] 2020-06-11 10:11
OK, so that particular area changed a lot in the new GUI. Also this issue ticket went in plenty of different direction which makes it really hard to act on. I will close it for now, if some concern is still left unanswered by the upcoming 2.7, please open a new ticket focusing only on that particular concern.

**Closed by er-vin** 2020-06-11 10:11 UTC
Labels: approved, bug, feature: :arrows_counterclockwise: sync engine

**Comment by keunes** [comment] 2020-06-11 16:17
> that particular area changed a lot in the new GUI

Didn't know a GUI overhaul was coming to us - great :) Is there a place where we can see (visually) what 2.7 will/might look like?

**Comment by misch7** [comment] 2020-06-11 16:20
> Didn't know a GUI overhaul was coming to us - great :) Is there a place where we can see (visually) what 2.7 will/might look like?

Sure, you can try the beta :)

https://github.com/nextcloud/desktop/releases/tag/v2.7.0-beta1

(Some of the 2.7-related issues in GitHub also contain work-in-progress screenshots.)

**Comment by Grunthos** [comment] 2024-06-30 12:41
I'm still seeing this very unhelpful error in the current windows desktop client. I can see nothing in the tiny popup dialog that indicates a conflict, and searching for files with a name containing 'conflict' produces no results.

How can I get a list like we used to get before the dialog was turned into the tiny and unusable popup that it is now? Are there log files somewhere?
