### ISSUE TITLE
new folder not visible in client, only in the filesystem

### ISSUE THREAD

**Issue by damdamce** [nextcloud/desktop#137] opened 2018-01-27 17:34 UTC
I added a new folder on the server and moved a file into it  (the file existed on the client before). The change was visible in the directory tree of the system (i.e. cd blah and ls), but not in the nextcloud client tree (i.e. myUserName \n cloud.domain.xy tab). It was visible in the activities.

It was visible only after a restart.

My platform:
Linux Mint 18.2 (Ubuntu 16.04) with KDE updated via the neo distribution.
Nextcloud client 2.3.3
server 12.0.5

**Comment by rullzer** [comment] 2018-01-27 18:32
Seems we don't refresh that screen often enough. Maybe we should fireoff a refresh or something when you open the tab.

**Comment by damdamce** [comment] 2018-01-27 18:42
Or do it when you click on sync or do it when the file is downloaded. On tab change would be weird (why wouldn't it update although it pops up in the file manager) :)

**Comment by michaelstingl** [comment] 2018-01-29 09:16
Related: https://github.com/owncloud/client/issues/6337

Fix: https://github.com/owncloud/client/commit/14f60a42385af5744fba3f08115c7c34bbd19668
You could help test-drive with [tomorrows nightlies](https://download.owncloud.com/desktop/daily/?C=M;O=D)…

**Comment by damdamce** [comment] 2018-01-30 21:40
I'm a bit confused, are the owncloud and nextcloud clients 100% protocol compatible? How much are they source compatible? is one of them just following the other? Should I use the owncloud or nextcloud client for a nextcloud server?

**Comment by damdamce** [comment] 2018-01-30 22:04
well, i tried to build that owncloud daily, but i have unmet dependencies and i can't resolve them due to a poor decision about installing kde neon packages to my linux mint.

the repository is protected by password.

**Comment by DominiqueFuchs** [comment] 2019-09-25 15:09
As this is merged within the current codebase of the desktop client now (don't know when the sync has happened, but just confirmed by glimpsing through the code), I'll close this.

@damdamce If you're still interested in an answer (😄 ): Don't know what exactly you mean by "source compatible" but there are parts of the fundamental code base that are still identical (because there are parts that do not change or change only rarely). However, there are also portions of code with very frequent changes and those that develop in other directions than the owncloud ones (strategic/feature-wise) so no, they are not really "source compatible".

**Closed by DominiqueFuchs** 2019-09-25 15:09 UTC
Labels: enhancement
