### ISSUE TITLE
nextcloud: relocation error: nextcloud: symbol malloc version Qt_5 not defined in file libQt5WebEngineCore.so.5 with link time reference

### ISSUE THREAD

**Issue by Victor-Morel** [nextcloud/desktop#1653] opened 2019-12-02 08:58 UTC
### Expected behaviour
Nextcloud launches

### Actual behaviour
Nextcloud doesn't launch, and I got the following message: 

`nextcloud: relocation error: nextcloud: symbol malloc version Qt_5 not defined in file libQt5WebEngineCore.so.5 with link time reference`

### Steps to reproduce
1. Launch Nextcloud
2.
3.

### Client configuration
Client version: 2.7, and 2.6 before that

Operating system:
Debian Sid

**Comment by Q-Storm** [comment] 2019-12-03 19:10
I have the same issue. Do you need any more package or system information?

**Comment by er-vin** [comment] 2020-07-21 12:00
Yes indeed more information would be needed. At a glance it looks like a packaging issue could well be gone.

@ivaradi ? Does it ring any bell to you?

**Comment by Q-Storm** [comment] 2020-07-21 13:18
I cannot reproduce the problem anymore.

**Comment by Victor-Morel** [comment] 2020-07-21 13:22
Ditto for me

**Comment by er-vin** [comment] 2020-07-21 13:40
OK, let's close it then. Thanks for reporting.

**Closed by er-vin** 2020-07-21 13:40 UTC
Labels: bug, needs info
