### ISSUE TITLE
URL in updates notification + why use URL at all?

### ISSUE THREAD

**Issue by dosch** [nextcloud/desktop#2833] opened 2021-01-18 08:27 UTC
### Expected behaviour
New update for Nextcloud client is released: a prompt appears asking me to update. I click yes. Update happens in the background and client is restarted

### Actual behaviour
(ugly) Notification appears with a bad rendered url. I have to go to the website, download the installer, run the installer and delete downloaded files.

<img width="393" alt="Screenshot 2021-01-18 at 08 54 03" src="https://user-images.githubusercontent.com/5372610/104889980-3af04980-596f-11eb-81c3-d7ddecfb355b.png">

Operating system:
MacOS Big Sur

**Comment by er-vin** [comment] 2021-01-18 09:39
Duplicate of #1844

**Closed by er-vin** 2021-01-18 09:39 UTC
