### ISSUE TITLE
[Bug]: Nextcloud desktop installer should NOT automatically reboot without a confirmation AFTER installation

### ISSUE THREAD

**Issue by captainwasabi** [nextcloud/desktop#4793] opened 2022-07-31 17:49 UTC
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

Installer reboots system without confirmation immediately prior to the reboot.
...

### Steps to reproduce

1. Update on Windows
...

### Expected behavior

A dialog comes up after installation, prior to rebooting, asking to reboot now, or later.
...

### Which files are affected by this bug

n/a

### Operating system

Windows

### Which version of the operating system you are running.

Windows 10

### Package

Other

### Nextcloud Server version

NA

### Nextcloud Desktop Client version

latest auto update

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 3.4.2 to 3.4.4)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Nextcloud Server logs

```shell
NA
```

### Additional info

NA

**Comment by larena1** [comment] 2022-07-31 23:10
This is super annoying. It should definitely not just reboot the PC without giving the user a chance to postpone the reboot.
Why is a reboot needed after all and for every update? Neither Dropbox nor OneDrive need to reboot the PC.

**Comment by claucambra** [comment] 2022-08-01 00:21
Hi, this is a duplicate of #3551 so I will close -- you can find more information on the situation in that thread. Thanks though for reporting!

**Closed by claucambra** 2022-08-01 00:21 UTC
Labels: 0. Needs triage
