### ISSUE TITLE
3.2.1 VFS: "Error writing metadata to the database" still exists

### ISSUE THREAD

**Issue by Lars1963** [nextcloud/desktop#3280] opened 2021-05-06 19:04 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

I'm still getting this error (now on nc21.0.2), so I've to reopen. Logs shows over and over again these entrys:
https://github.com/nextcloud/desktop/issues/3158#issuecomment-830699653_

@tobru seems to be able to reproduce this also:
https://github.com/nextcloud/desktop/issues/3158#issuecomment-833748857_

**Comment by allexzander** [comment] 2021-05-07 07:07
@Lars1963 Haven't seen you've opened a new issue. I am going to close this one as a duplicate, since, I've reopened the original one and left some comments for you.

Duplicate of https://github.com/nextcloud/desktop/issues/3158

**Closed** 2021-05-07 07:08 UTC
Labels: bug
