### ISSUE TITLE
[Bug]: Nextcloud 3.14.1 crashed when syncing virtual file

### ISSUE THREAD

**Issue by ymj0424** [nextcloud/desktop#7279] opened 2024-10-08 04:33 UTC
### ⚠️ Before submitting, please verify the following: ⚠️

- [x] This is a **bug**, not a question or a configuration issue.
- [x] This issue is **not** already reported on Github (I've searched it).
- [x] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

app crashed when syncing virtual files

### Steps to reproduce

1. Open the application
2. Wait until synchronisation starts
3. Application crashes

### Expected behavior

Application should not crash

### Which files are affected by this bug

Don't know

### Operating system

Windows

### Which version of the operating system you are running.

Windows 10/11

### Package

Official Windows MSI

### Nextcloud Server version

29.0.6

### Nextcloud Desktop Client version

3.14.1

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [x] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Nextcloud Server logs

2024-10-08 11:00:11:445 [ warning default qrc:/qml/src/gui/tray/NCProgressBar.qml:22 ]:	qrc:/qml/src/gui/tray/NCProgressBar.qml:22:17: QML QQuickRectangle: The current style does not support customization of this control (property: "background" item: QQuickRectangle(0x13b4a3a8520, parent=0x0, geometry=0,0 0x0)). Please customize a non-native style (such as Basic, Fusion, Material, etc). For more information, see: https://doc.qt.io/qt-6/qtquickcontrols2-customize.html#customization-reference
2024-10-08 11:00:11:458 [ warning default qrc:/qml/src/gui/tray/NCProgressBar.qml:31 ]:	qrc:/qml/src/gui/tray/NCProgressBar.qml:31:18: QML QQuickItem: The current style does not support customization of this control (property: "contentItem" item: QQuickItem(0x13b4a3a8600, parent=0x0, geometry=0,0 0x0)). Please customize a non-native style (such as Basic, Fusion, Material, etc). For more information, see: https://doc.qt.io/qt-6/qtquickcontrols2-customize.html#customization-reference
2024-10-08 11:00:11:480 [ info nextcloud.sync.engine C:\Users\User\AppData\Local\Temp\windows-26085\client-building\desktop\src\libsync\syncengine.cpp:1045 ]:	#### Reconcile (aboutToPropagate) ####################################################  53634 ms
2024-10-08 11:00:11:480 [ info nextcloud.sync.statustracker C:\Users\User\AppData\Local\Temp\windows-26085\client-building\desktop\src\libsync\syncfilestatustracker.cpp:239 ]:	Investigating "工作/直观/维修/REP-2024-545/2024REP545出口报关单(制单).xls" OCC::SyncFileItem::NoStatus CSyncEnums::CSYNC_INSTRUCTION_SYNC OCC::SyncFileItem::Down
2024-10-08 11:00:11:482 [ info nextcloud.sync.statustracker C:\Users\User\AppData\Local\Temp\windows-26085\client-building\desktop\src\libsync\syncfilestatustracker.cpp:239 ]:	Investigating "工作/直观/维修/REP-2024-545/223320231000849582 报关单.pdf" OCC::SyncFileItem::NoStatus CSyncEnums::CSYNC_INSTRUCTION_NEW OCC::SyncFileItem::Up
2024-10-08 11:00:11:482 [ info nextcloud.sync.statustracker C:\Users\User\AppData\Local\Temp\windows-26085\client-building\desktop\src\libsync\syncfilestatustracker.cpp:239 ]:	Investigating "工作/直观/维修/REP-2024-545/修理物品情况说明.docx" OCC::SyncFileItem::NoStatus CSyncEnums::CSYNC_INSTRUCTION_NEW OCC::SyncFileItem::Up
2024-10-08 11:00:11:587 [ info nextcloud.sync.engine C:\Users\User\AppData\Local\Temp\windows-26085\client-building\desktop\src\libsync\syncengine.cpp:1052 ]:	#### Reconcile (aboutToPropagate OK) ####################################################  53742 ms
2024-10-08 11:00:11:591 [ debug nextcloud.sync.database C:\Users\User\AppData\Local\Temp\windows-26085\client-building\desktop\src\common\syncjournaldb.cpp:3062 ]	[ OCC::SyncJournalDb::commitInternal ]:	Transaction commit "post treewalk" and starting new transaction
2024-10-08 11:00:11:602 [ debug nextcloud.sync.database C:\Users\User\AppData\Local\Temp\windows-26085\client-building\desktop\src\common\syncjournaldb.cpp:1706 ]	[ OCC::deleteBatch ]:	Removing stale "downloadinfo" entries: "工作/直观/维修/REP-2024-545/2024REP545出口报关单(制单).xls, 工作/直观/维修/REP-2024-545/4500281580.pdf"
2024-10-08 11:00:11:602 [ info nextcloud.sync.engine C:\Users\User\AppData\Local\Temp\windows-26085\client-building\desktop\src\libsync\syncengine.cpp:231 ]:	Deleting stale temporary file:  "E:/Nextcloud/工作/直观/维修/REP-2024-545/.2024REP545出口报关单(制单).xls.~de9"
2024-10-08 11:00:11:603 [ info nextcloud.sync.engine C:\Users\User\AppData\Local\Temp\windows-26085\client-building\desktop\src\libsync\syncengine.cpp:231 ]:	Deleting stale temporary file:  "E:/Nextcloud/工作/直观/维修/REP-2024-545/.4500281580.pdf.~529e"
2024-10-08 11:00:11:604 [ debug nextcloud.gui.folderwatcher C:\Users\User\AppData\Local\Temp\windows-26085\client-building\desktop\src\gui\folderwatcher_win.cpp:160 ]	[ OCC::WatcherThread::watchChanges ]:	Skipping syncing of "E:/Nextcloud/工作/直观/维修/REP-2024-545"
2024-10-08 11:00:11:615 [ debug nextcloud.sync.database C:\Users\User\AppData\Local\Temp\windows-26085\client-building\desktop\src\common\syncjournaldb.cpp:3062 ]	[ OCC::SyncJournalDb::commitInternal ]:	Transaction commit "post stale entry removal" and starting new transaction
2024-10-08 11:00:11:616 [ info nextcloud.sync.engine C:\Users\User\AppData\Local\Temp\windows-26085\client-building\desktop\src\libsync\syncengine.cpp:1106 ]:	#### Post-Reconcile end ####################################################  53770 ms
2024-10-08 11:00:11:616 [ debug nextcloud.sync.filesystem C:\Users\User\AppData\Local\Temp\windows-26085\client-building\desktop\src\libsync\filesystem.cpp:67 ]	[ OCC::FileSystem::filePathLockFilePatternMatch ]:	Checking if it is a lock file: "E:/Nextcloud/工作/直观/维修/REP-2024-545/.2024REP545出口报关单(制单).xls.~de9"
2024-10-08 11:00:11:616 [ debug nextcloud.gui.folderwatcher C:\Users\User\AppData\Local\Temp\windows-26085\client-building\desktop\src\gui\folderwatcher.cpp:226 ]	[ OCC::FolderWatcher::changeDetected ]:	Locked files: QList()
2024-10-08 11:00:11:616 [ debug nextcloud.gui.folderwatcher C:\Users\User\AppData\Local\Temp\windows-26085\client-building\desktop\src\gui\folderwatcher.cpp:236 ]	[ OCC::FolderWatcher::changeDetected ]:	Unlocked files: QList()
2024-10-08 11:00:11:616 [ debug nextcloud.gui.folderwatcher C:\Users\User\AppData\Local\Temp\windows-26085\client-building\desktop\src\gui\folderwatcher.cpp:237 ]	[ OCC::FolderWatcher::changeDetected ]:	Locked files: QSet()
2024-10-08 11:00:11:616 [ info nextcloud.gui.folderwatcher C:\Users\User\AppData\Local\Temp\windows-26085\client-building\desktop\src\gui\folderwatcher.cpp:252 ]:	Detected changes in paths: QSet("E:/Nextcloud/工作/直观/维修/REP-2024-545/.2024REP545出口报关单(制单).xls.~de9")
2024-10-08 11:00:11:617 [ debug nextcloud.gui.folder C:\Users\User\AppData\Local\Temp\windows-26085\client-building\desktop\src\gui\folder.cpp:911 ]	[ OCC::Folder::pathIsIgnored ]:	* Ignoring file "E:/Nextcloud/工作/直观/维修/REP-2024-545/.2024REP545出口报关单(制单).xls.~de9"
2024-10-08 11:00:11:617 [ debug nextcloud.sync.vfs.cfapi C:\Users\User\AppData\Local\Temp\windows-26085\client-building\desktop\src\libsync\vfs\cfapi\vfs_cfapi.cpp:330 ]	[ OCC::VfsCfApi::pinStateLocal ]:	Couldn't find pin state for regular non-placeholder file "E:\\Nextcloud\\工作\\直观\\维修\\REP-2024-545\\.2024REP545出口报关单(制单).xls.~de9"
2024-10-08 11:00:11:617 [ debug nextcloud.sync.vfs.cfapi C:\Users\User\AppData\Local\Temp\windows-26085\client-building\desktop\src\libsync\vfs\cfapi\vfs_cfapi.cpp:303 ]	[ OCC::VfsCfApi::setPinState ]:	setPinState "工作/直观/维修/REP-2024-545/.2024REP545出口报关单(制单).xls.~de9" (4)
2024-10-08 11:00:11:617 [ warning nextcloud.sync.vfs.cfapi.wrapper C:\Users\User\AppData\Local\Temp\windows-26085\client-building\desktop\src\libsync\vfs\cfapi\cfapiwrapper.cpp:836 ]:	Couldn't set pin state (4) for "E:\\Nextcloud\\工作\\直观\\维修\\REP-2024-545\\.2024REP545出口报关单(制单).xls.~de9" with recurse mode 1 : "句柄无效。"
2024-10-08 11:00:11:617 [ warning nextcloud.gui.folder C:\Users\User\AppData\Local\Temp\windows-26085\client-building\desktop\src\gui\folder.cpp:577 ]:	Could not set pin state of "工作/直观/维修/REP-2024-545/.2024REP545出口报关单(制单).xls.~de9" to excluded
2024-10-08 11:00:11:617 [ info nextcloud.gui.folder C:\Users\User\AppData\Local\Temp\windows-26085\client-building\desktop\src\gui\folder.cpp:1184 ]:	#### Propagation start ####################################################
2024-10-08 11:00:11:617 [ debug nextcloud.gui.socketapi C:\Users\User\AppData\Local\Temp\windows-26085\client-building\desktop\src\gui\socketapi\socketapi.cpp:515 ]	[ OCC::SocketApi::slotUpdateFolderView ]:	Not sending UPDATE_VIEW for "1" because status() is OCC::SyncResult::SyncRunning
2024-10-08 11:00:11:621 [ warning default unknown:0 ]:	QString::arg: 1 argument(s) missing in Syncing %1 (A few seconds left)
2024-10-08 11:00:11:624 [ info nextcloud.gui.application C:\Users\User\AppData\Local\Temp\windows-26085\client-building\desktop\src\gui\owncloudgui.cpp:247 ]:	Sync state changed for folder  "https://share.ymj0424.com:2854/remote.php/dav/files/liuxiaorong/" :  "Sync running"
2024-10-08 11:00:11:625 [ info nextcloud.sync.propagator.root.directory C:\Users\User\AppData\Local\Temp\windows-26085\client-building\desktop\src\libsync\owncloudpropagator.cpp:1582 ]:	scheduleSelfOrChild OCC::PropagatorJob::NotYetStarted pending uploads 0 subjobs state OCC::PropagatorJob::NotYetStarted
2024-10-08 11:00:11:626 [ info nextcloud.sync.propagator C:\Users\User\AppData\Local\Temp\windows-26085\client-building\desktop\src\libsync\owncloudpropagator.h:221 ]:	Starting CSyncEnums::CSYNC_INSTRUCTION_SYNC propagation of "工作/直观/维修/REP-2024-545/2024REP545出口报关单(制单).xls" by OCC::PropagateDownloadFile(0x13b49ee4940)
2024-10-08 11:00:11:627 [ debug nextcloud.sync.propagator.download C:\Users\User\AppData\Local\Temp\windows-26085\client-building\desktop\src\libsync\propagatedownload.cpp:452 ]	[ OCC::PropagateDownloadFile::start ]:	"工作/直观/维修/REP-2024-545/2024REP545出口报关单(制单).xls" 0
2024-10-08 11:00:11:632 [ warning default unknown:0 ]:	QString::arg: 1 argument(s) missing in Syncing %1 (A few seconds left)
2024-10-08 11:00:11:634 [ debug nextcloud.sync.database C:\Users\User\AppData\Local\Temp\windows-26085\client-building\desktop\src\common\syncjournaldb.cpp:3062 ]	[ OCC::SyncJournalDb::commitInternal ]:	Transaction commit "download file start" and starting new transaction
2024-10-08 11:00:11:634 [ debug nextcloud.gui.folderwatcher C:\Users\User\AppData\Local\Temp\windows-26085\client-building\desktop\src\gui\folderwatcher_win.cpp:160 ]	[ OCC::WatcherThread::watchChanges ]:	Skipping syncing of "E:/Nextcloud/工作/直观/维修/REP-2024-545"
2024-10-08 11:00:11:635 [ info nextcloud.sync.accessmanager C:\Users\User\AppData\Local\Temp\windows-26085\client-building\desktop\src\libsync\accessmanager.cpp:67 ]:	2 "" "https://share.ymj0424.com:2854/remote.php/dav/files/liuxiaorong/工作/直观/维修/REP-2024-545/2024REP545出口报关单(制单).xls" has X-Request-ID "eefa11ab-a506-4ce9-9a3c-30c6132cb4e4"
2024-10-08 11:00:11:635 [ debug nextcloud.sync.cookiejar C:\Users\User\AppData\Local\Temp\windows-26085\client-building\desktop\src\libsync\cookiejar.cpp:90 ]	[ OCC::CookieJar::cookiesForUrl ]:	QUrl("https://share.ymj0424.com:2854/remote.php/dav/files/liuxiaorong/工作/直观/维修/REP-2024-545/2024REP545出口报关单(制单).xls") requests: QList(QNetworkCookie("__Host-nc_sameSiteCookielax=true; secure; HttpOnly; SameSite=Lax; expires=Fri, 31-Dec-2100 23:59:59 GMT; domain=share.ymj0424.com; path=/"), QNetworkCookie("__Host-nc_sameSiteCookiestrict=true; secure; HttpOnly; SameSite=Strict; expires=Fri, 31-Dec-2100 23:59:59 GMT; domain=share.ymj0424.com; path=/"), QNetworkCookie("oc_sessionPassphrase=ENyOR2e6RsxzTuB4kYgeNuavK03xWeUx2WnnV22Pc2lBcMhOrQOBteSmhGLD4fb9ElAixFCgIFM%2FdrBHM6zD6KqSLAbknlALVN%2FB9aAevEd9crKuP5Z5xVJMYDmVm%2BPJ; secure; HttpOnly; SameSite=Lax; domain=share.ymj0424.com; path=/"), QNetworkCookie("oc2eofa1x8yo=73dd8a86160855a9ae8ebaeaa6c2fabd; secure; HttpOnly; SameSite=Lax; domain=share.ymj0424.com; path=/"))
2024-10-08 11:00:11:636 [ debug nextcloud.sync.networkjob.get C:\Users\User\AppData\Local\Temp\windows-26085\client-building\desktop\src\libsync\propagatedownload.cpp:133 ]	[ OCC::GETFileJob::start ]:	OCC::BandwidthManager(0x13b47ca5d58) false false
2024-10-08 11:00:11:636 [ info nextcloud.sync.networkjob C:\Users\User\AppData\Local\Temp\windows-26085\client-building\desktop\src\libsync\abstractnetworkjob.cpp:365 ]:	OCC::GETFileJob created for "https://share.ymj0424.com" + "/工作/直观/维修/REP-2024-545/2024REP545出口报关单(制单).xls" "OCC::PropagateDownloadFile"
2024-10-08 11:00:11:636 [ debug nextcloud.sync.filesystem C:\Users\User\AppData\Local\Temp\windows-26085\client-building\desktop\src\libsync\filesystem.cpp:67 ]	[ OCC::FileSystem::filePathLockFilePatternMatch ]:	Checking if it is a lock file: "E:/Nextcloud/工作/直观/维修/REP-2024-545/.2024REP545出口报关单(制单).xls.~1527"
2024-10-08 11:00:11:636 [ debug nextcloud.gui.folderwatcher C:\Users\User\AppData\Local\Temp\windows-26085\client-building\desktop\src\gui\folderwatcher.cpp:226 ]	[ OCC::FolderWatcher::changeDetected ]:	Locked files: QList()
2024-10-08 11:00:11:636 [ debug nextcloud.gui.folderwatcher C:\Users\User\AppData\Local\Temp\windows-26085\client-building\desktop\src\gui\folderwatcher.cpp:236 ]	[ OCC::FolderWatcher::changeDetected ]:	Unlocked files: QList()
2024-10-08 11:00:11:636 [ debug nextcloud.gui.folderwatcher C:\Users\User\AppData\Local\Temp\windows-26085\client-building\desktop\src\gui\folderwatcher.cpp:237 ]	[ OCC::FolderWatcher::changeDetected ]:	Locked files: QSet()
2024-10-08 11:00:11:636 [ info nextcloud.gui.folderwatcher C:\Users\User\AppData\Local\Temp\windows-26085\client-building\desktop\src\gui\folderwatcher.cpp:252 ]:	Detected changes in paths: QSet("E:/Nextcloud/工作/直观/维修/REP-2024-545/.2024REP545出口报关单(制单).xls.~1527")
2024-10-08 11:00:11:637 [ debug nextcloud.gui.folder C:\Users\User\AppData\Local\Temp\windows-26085\client-building\desktop\src\gui\folder.cpp:911 ]	[ OCC::Folder::pathIsIgnored ]:	* Ignoring file "E:/Nextcloud/工作/直观/维修/REP-2024-545/.2024REP545出口报关单(制单).xls.~1527"
2024-10-08 11:00:11:637 [ debug nextcloud.sync.vfs.cfapi C:\Users\User\AppData\Local\Temp\windows-26085\client-building\desktop\src\libsync\vfs\cfapi\vfs_cfapi.cpp:330 ]	[ OCC::VfsCfApi::pinStateLocal ]:	Couldn't find pin state for regular non-placeholder file "E:\\Nextcloud\\工作\\直观\\维修\\REP-2024-545\\.2024REP545出口报关单(制单).xls.~1527"
2024-10-08 11:00:11:637 [ debug nextcloud.sync.vfs.cfapi C:\Users\User\AppData\Local\Temp\windows-26085\client-building\desktop\src\libsync\vfs\cfapi\vfs_cfapi.cpp:303 ]	[ OCC::VfsCfApi::setPinState ]:	setPinState "工作/直观/维修/REP-2024-545/.2024REP545出口报关单(制单).xls.~1527" (4)
2024-10-08 11:00:11:639 [ info nextcloud.sync.propagator.root.directory C:\Users\User\AppData\Local\Temp\windows-26085\client-building\desktop\src\libsync\owncloudpropagator.cpp:1582 ]:	scheduleSelfOrChild OCC::PropagatorJob::Running pending uploads 0 subjobs state OCC::PropagatorJob::Running
2024-10-08 11:00:11:639 [ warning nextcloud.sync.propagator.directory C:\Users\User\AppData\Local\Temp\windows-26085\client-building\desktop\src\libsync\owncloudpropagator.cpp:1261 ]:	Useless task found for file "工作/直观/维修/REP-2024-545/223320231000849582 报关单.pdf" instruction CSyncEnums::CSYNC_INSTRUCTION_NEW
2024-10-08 11:00:11:639 [ warning nextcloud.sync.propagator.directory C:\Users\User\AppData\Local\Temp\windows-26085\client-building\desktop\src\libsync\owncloudpropagator.cpp:1261 ]:	Useless task found for file "工作/直观/维修/REP-2024-545/修理物品情况说明.docx" instruction CSyncEnums::CSYNC_INSTRUCTION_NEW
2024-10-08 11:00:11:708 [ warning default unknown:0 ]:	QString::arg: 1 argument(s) missing in Syncing %1 (A few seconds left)
2024-10-08 11:00:11:708 [ info nextcloud.sync.credentials.webflow C:\Users\User\AppData\Local\Temp\windows-26085\client-building\desktop\src\gui\creds\webflowcredentials.cpp:405 ]:	request finished
2024-10-08 11:00:11:742 [ info nextcloud.sync.checksums C:\Users\User\AppData\Local\Temp\windows-26085\client-building\desktop\src\common\checksums.cpp:204 ]:	Computing "SHA1" checksum of "E:/Nextcloud/工作/直观/维修/REP-2024-545/.2024REP545出口报关单(制单).xls.~1527" in a thread
2024-10-08 11:00:11:742 [ debug nextcloud.sync.networkjob C:\Users\User\AppData\Local\Temp\windows-26085\client-building\desktop\src\libsync\abstractnetworkjob.cpp:297 ]	[ OCC::AbstractNetworkJob::slotFinished ]:	Network job OCC::GETFileJob finished for "/工作/直观/维修/REP-2024-545/2024REP545出口报关单(制单).xls"
2024-10-08 11:00:11:742 [ debug nextcloud.sync.networkjob.get C:\Users\User\AppData\Local\Temp\windows-26085\client-building\desktop\src\libsync\propagatedownload.cpp:332 ]	[ OCC::GETFileJob::slotReadyRead ]:	Get file job finished bytesAvailable/_saveBodyToFile: 0 / true
2024-10-08 11:00:11:743 [ debug nextcloud.sync.propagator.download C:\Users\User\AppData\Local\Temp\windows-26085\client-building\desktop\src\libsync\propagatedownload.cpp:1183 ]	[ OCC::PropagateDownloadFile::downloadFinished ]:	setModTime "E:/Nextcloud/工作/直观/维修/REP-2024-545/.2024REP545出口报关单(制单).xls.~1527" 1727419381
2024-10-08 11:00:21:023 [ warning default unknown:0 ]:	Qt has caught an exception thrown from an event handler. Throwing
exceptions from an event handler is not supported in Qt.
You must not let any exception whatsoever propagate through Qt code.
2024-10-08 11:00:21:024 [ debug nextcloud.gui.socketapi C:\Users\User\AppData\Local\Temp\windows-26085\client-building\desktop\src\gui\socketapi\socketapi.cpp:228 ]	[ OCC::SocketListener::sendMessage ]:	Sending SocketAPI message --> "UNREGISTER_PATH:E:\\Nextcloud" to QLocalSocket(0x13b47cd7ee0)
2024-10-08 11:00:21:113 [ info nextcloud.sync.engine C:\Users\User\AppData\Local\Temp\windows-26085\client-building\desktop\src\libsync\syncengine.cpp:1309 ]:	Aborting sync in propagator...
2024-10-08 11:00:21:146 [ debug nextcloud.gui.folderwatcher C:\Users\User\AppData\Local\Temp\windows-26085\client-building\desktop\src\gui\folderwatcher_win.cpp:100 ]	[ OCC::WatcherThread::watchChanges ]:	Received stop event, aborting folder watcher thread
2024-10-08 11:00:21:148 [ info nextcloud.sync.database C:\Users\User\AppData\Local\Temp\windows-26085\client-building\desktop\src\common\syncjournaldb.cpp:693 ]:	Closing DB "E:/Nextcloud/.sync_dfbd63976676.db"
2024-10-08 11:00:21:812 [ debug nextcloud.gui.socketapi C:\Users\User\AppData\Local\Temp\windows-26085\client-building\desktop\src\gui\socketapi\socketapi.cpp:321 ]	[ OCC::SocketApi::~SocketApi ]:	dtor
2024-10-08 11:00:21:812 [ info nextcloud.gui.socketapi C:\Users\User\AppData\Local\Temp\windows-26085\client-building\desktop\src\gui\socketapi\socketapi.cpp:354 ]:	Lost connection  QLocalSocket(0x13b47cd7ee0)

**Comment by zen010101** [comment] 2024-10-08 04:52
Have you tried version 3.13.4 and it crashes?

**Comment by ymj0424** [comment] 2024-10-08 06:19
> Have you tried version 3.13.4 and it crashes?

Thanks, it works. 
So what's the difference between 3.13.4 and 3.14.1 which makes this issue? I want to know when should I upgrade the client.

**Comment by MaximeMaW** [comment] 2024-10-08 11:44
I am also affected (VFS sync would never complete), I could not find anything in the logs. Reverting to 3.13.4 fixed the issue.

**Comment by mgallien** [comment] 2024-10-09 06:57
this is a duplicate of https://github.com/nextcloud/desktop/issues/7265
please have a look there as I have a test build made from 3.14 stable branch with a fix for this

**Closed by mgallien** 2024-10-09 06:57 UTC
Labels: 0. Needs triage, bug
