### ISSUE TITLE
IDEA/VSCODE File Cache Conflicts + null characters + dropped changes when I write code

### ISSUE THREAD

**Issue by lllong33** [nextcloud/desktop#5165] opened 2022-11-11 06:10 UTC
### Bug description

nextcloud + IDEA/VSCODE File Cache Conflict occurs when I write code. It affects my normal operation. In VSCODE, the last few lines of the file are replaced with null characters, and even the last few lines of code are deleted.
![image](https://user-images.githubusercontent.com/29864358/201274828-11d14b2c-8262-464c-b08e-3a41235f024c.png)

### Which version of the operating system you are running.
windows 10 and 11

### Nextcloud Server version

19,0,4,2

### Nextcloud Desktop Client version

3.6.1

------------------------------- 2022-11-18
![image](https://user-images.githubusercontent.com/29864358/202699600-16a76911-fcf1-48dd-a56f-8b091bc962c1.png)

**Comment by joshtrichards** [comment] 2023-11-26 03:33
Thanks for the report.

Sounds like a couple others have encountered the nulls with VSCode + syncing too:
https://www.reddit.com/r/vscode/s/eR3f7mdAAU

Editors and things that make lots of transient files or persistent data updates can be tough for sync. They bring out all the edge cases. :-)

P.S. Side note, but there are WebDAV add-ons to VSCode that could be interesting combined when Nextcloud (I haven't tried any myself). Also thought you might find this thread of interest: https://www.reddit.com/r/NextCloud/s/p49QzoQpqA

**Comment by lllong33** [comment] 2023-11-28 00:12
After removing the git project, this issue does not occur. 

Thank you very much for your reply.

**Comment by joshtrichards** [comment] 2024-08-20 20:41
Duplicate of #5035

**Closed by joshtrichards** 2024-08-20 20:41 UTC
Labels: 0. Needs triage, bug, feature: :arrows_counterclockwise: sync engine
