### ISSUE TITLE
Speed up initial sync

### ISSUE THREAD

**Issue by mgallien** [nextcloud/desktop#3975] opened 2021-11-15 09:46 UTC
When users are using virtual files on Windows and they have a big sync folder, the initial sync can be very slow.
The idea is to speed up initial sync when using virtual files because we do not need to sync the content but just the metadata of the files to create the virtual files placeholders.

**Comment by mgallien** [comment] 2021-11-15 09:47
@tobiasKaminsky as discussed

**Comment by claell** [comment] 2021-11-15 14:49
(Slightly) Related: #3914 

Issues for slow sync (not virtual files): #2669, #691

**Comment by tomdereub** [comment] 2021-11-27 01:26
It's linked with this issue too : https://github.com/nextcloud/desktop/issues/3120
I like the way the android client is managing it : it never scans all folders, but only those you access, and then it keeps the folder tree in cache. To be reactive, it could keep syncing only the metadata of folders that has already been accessed once.
In medium and large organisation, each user needs to access just a small part of all data.

**Comment by marcotrevisan** [comment] 2022-02-22 07:19
Another linked issue is #4239.

**Comment by marcotrevisan** [comment] 2022-03-02 05:37
In my current setup the new version 3.4.3 has further slowed down the initial sync. 
Moreover, on some error situations like folders with trailing spaces, it will now stop and restart forever.
The problem with these file names is that the average user has no clue of this being a problem as Finder allows for that.

**Comment by tobiasKaminsky** [comment] 2022-11-03 07:32
Duplicate of https://github.com/nextcloud/desktop/issues/4424

**Closed by tobiasKaminsky** 2022-11-03 07:32 UTC
Labels: enhancement, feature: :minidisc: virtual filesystem, approved
