### ISSUE TITLE
server stopped accepting new streams before this stream was established

### ISSUE THREAD

**Issue by Karman40** [nextcloud/desktop#1533] opened 2019-10-20 18:00 UTC
- Client version: `2.6.0stable-Win64 (build 20190927)`
- Operating system: `WIN 10 Enterprise`
- OS language: `Hungary`
- Nextcloud version: `17.0.0`

I tried on several client machines but could not find a solution to the sync error.
I also have the following error:
[https://help.nextcloud.com/t/sync-error-server-stopped-accepting-new-streams-before-this-stream-was-established/59209](https://help.nextcloud.com/t/sync-error-server-stopped-accepting-new-streams-before-this-stream-was-established/59209)

**Comment by e-alfred** [comment] 2019-11-11 22:32
This is a duplicate of https://github.com/nextcloud/desktop/issues/1503.

**Closed** 2020-01-14 00:40 UTC
