### ISSUE TITLE
Can't open virtual file with German umlaut

### ISSUE THREAD

**Issue by CaptainBalou** [nextcloud/desktop#3629] opened 2021-08-05 08:37 UTC
Hello,

I am using virtual files beta function on macOS. It normally works fine with the *.nextcloud extensions but not with German umlauts in file names.

### Expected behaviour
Double clicking a file with *.nextcloud extension should download the file to local, remove the place holder file and open the real file.

### Actual behaviour
On files w/o German umlauts this works fine.
On files with German umlauts the icon of the file flickers for a second and then nothing happens. As soon the German umlaut gets removed the file can be loaded normally.

### Steps to reproduce
1. Generate a file e.g. abcöäü.pdf on the webinterface or another client.
2. Go to macOS client with virtual file feature enabled and try to open abcöäü.pdf.nextcloud. It won't work.
3. Rename the file to abc.pdf.nextcloud and try to open this file. It downloads the file as expected and opens it.

### Client configuration
Client version:
3.2.4 (newer version 3.3.0 does not sync new files at all so I cannot test this behaviour with 3.3.0).

Operating system:
macOS Big Sur 11.5.1

OS language:
German

### Server
Nextcloud version:
20.0.11

### Logs
I know logs are important but I cannot collect them right now. If needed I can try to do this (my first time) later but right now I am not able to.

Regards
Marco

**Comment by CaptainBalou** [comment] 2022-01-28 14:02
I cannot test if this bug is gone in a newer version of nextcloud desktop because of another issue https://github.com/nextcloud/desktop/issues/3806 which blocks me from upgrading.
Does anyone has the same issue with German umlauts or am I the only one experiencing this?

**Comment by CaptainBalou** [comment] 2022-11-27 11:11
Hello @xavi-b ,

thanks for replying to my issue report. I always try to report things I find as a user/administrator but I'm no developer and honestly I don't know how to test your fixed version you mentioned in the linked PR. Or is this already included in an official release I probably could install?

Regards
Marco

**Comment by xizu0x** [comment] 2023-01-24 08:18
I also experience this issue.  Still present with Nextcloud Client Version 3.6.6.
This issue is only on MacOS. On WIndows it works fine.

**Comment by tflidd** [comment] 2023-08-04 08:11
> I believe it is linked to my issue : #4950
> Which I have fixed here : #4957

The fix went into the 3.9.0 milestone (see on the right side the milestone of the pull request). And it was backported to 3.8.2 (further down, and this other pull request has the 3.8.2 milestone).


> Still present with Nextcloud Client Version 3.6.6.

Please check again with a client 3.8.2 or later.

**Comment by joshtrichards** [comment] 2024-08-17 17:21
Duplicate of #4950
Fixed in #4957

**Closed by joshtrichards** 2024-08-17 17:21 UTC
Labels: bug, os: :apple: macOS, feature: :minidisc: virtual filesystem, approved
