### ISSUE TITLE
Can not use installer to update version after updating to windows 21 H1

### ISSUE THREAD

**Issue by Gornoka** [nextcloud/desktop#3571] opened 2021-07-20 09:09 UTC
### Expected behaviour
Installer should allow me to update the software

### Actual behaviour
Installer informs me that allegedly my windows version is not above 1709 and cancels installations

### Steps to reproduce
1. Update to 21H1
2. start installer

### Client configuration
Client version:

Operating system:
Version	10.0.19043 Build 19043
20H1
OS language:
German / Deutsch

Installer File:
Nextcloud-3.2.4-x64.msi

![image](https://user-images.githubusercontent.com/45569834/126294143-231c39e6-4cae-4b44-b99a-bfba74350b1d.png)

**Comment by FlexW** [comment] 2021-07-20 09:47
Duplicate of https://github.com/nextcloud/desktop/issues/3378

**Closed by FlexW** 2021-07-20 09:47 UTC
Labels: bug

**Comment by Gornoka** [comment] 2021-07-20 16:57
thanks for the quick answer
