### ISSUE TITLE
Multiple UI issues for 2FA notifications received in the destop Nextcloud client

### ISSUE THREAD

**Issue by narFnarF** [nextcloud/desktop#2114] opened 2020-06-21 22:21 UTC
When using the Two Factor Authentication plugin ([link](https://github.com/nickv-nextcloud/twofactor_nextcloud_notification)) there are a few UI and user experience issues that could be improved. I was redirected by the author of this plugin to report these here. See my original report: https://github.com/nickv-nextcloud/twofactor_nextcloud_notification/issues/343

### Steps to reproduce
1. Attempt login to Nextcloud
2. Open the Nextcloud client on Windows or MacOS
1. Observe that no Notifications are displayed in Windows or MacOS
3. Go to the Activity tab in the Nextcloud client
1. Observe that Windows or MacOS will not display the notification

### Current behaviour
Multiple problems:
- The Notification on Windows or MacOS is not received until the user opens the Nextcloud client and navigate to the Activity tab
- The "More info" button is non-functional (On my screenshot, it's says "Plus d'informations" which is French for "More info")
- The main path of action (approving or rejecting) is hidden behind the "..." button

### Expected behaviour
- The notification on Windows or MacOS should appear immediately, while the Nextcloud client is active, without having to open it
- The "More info" button has functionality when clicked, or is removed. If this "More info" is meant to say that "there is more info, you should click the "..." button", then this text should not look like a button.
- The main actions (approving or rejecting) should be more prominently displayed, without having to open a sub-menu.
![](https://i.imgur.com/m289JtW.png)

### Client configuration
Client version: Version 2.6.4stable-Win64 (build 20200303)

Operating system: Windows 10 or MacOSX

OS language: Canadian French

Installation path of client: C:\Program Files (x86)\Nextcloud

### Server configuration
Nextcloud version: 17.0.7

**Comment by er-vin** [comment] 2020-06-22 07:02
Thanks for the report.

It turns out we changed things quite a bit in the GUI lately and some of what you report seems tied to the GUI (not all of it though). Could you try out one of our daily builds and let us know how it's doing there?

You could for instance use: https://download.nextcloud.com/desktop/daily/Windows/nextcloud-2.7.0.15534-daily-20200622-Release.exe

Thanks in advance.

**Comment by narFnarF** [comment] 2020-09-12 00:34
I'm now running the Nextcloud client 3.0.1 so I was able to try what you asked for.

I would say, it's a worst experience unfortunately.

- No notification is received on Windows (my phone received the notification immediately though)
- There is no way to accept the login attempt in the 3.0 client

This makes the Two Factor Authentication plugin completely nonfunctional :(

**Comment by er-vin** [comment] 2020-09-16 16:18
Isn't it a duplicate of #2339 ? (that second one is more recent but provides more 3.0 related context)

**Comment by narFnarF** [comment] 2020-09-17 18:21
I agree that #2339 is better to describe attempting to accept the login attempt. But the other problem (that you don't receive the notification on Windows) is a separate problem. Maybe I should open a separate ticket?

**Comment by er-vin** [comment] 2020-09-29 10:50
Ah you mean it's not even in the activity list on windows? This would be surprising, or you're talking about a native passive popup notification?

**Comment by narFnarF** [comment] 2020-09-29 15:47
What I mean is that, other that the entry that silently appears in Nextcloud's activity list, there's no other notification. Basically, there's nothing that direct me to open Nextcloud's activity list.

![](https://i.imgur.com/pvhKYdM.png)

**Comment by er-vin** [comment] 2020-09-29 17:25
Fair enough, that'll likely be fixed with #2486

**Comment by david-beers** [comment] 2020-10-19 19:35
> 
> 
> I'm now running the Nextcloud client 3.0.1 so I was able to try what you asked for.
> 
> I would say, it's a worst experience unfortunately.
> 
>     * No notification is received on Windows (my phone received the notification immediately though)
> 
>     * There is no way to accept the login attempt in the 3.0 client
> 
> 
> This makes the Two Factor Authentication plugin completely nonfunctional :(

I am having the same issue on 3.0.2. I don't use the Windows notification system so the 2FA notification system on Desktop is unusable.

**Closed** 2020-12-02 14:42 UTC
Labels: bug, feature: :zap: activity and :bell: notification

**Comment by allexzander** [comment] 2020-12-02 14:57
Everything, except this part "The Notification on Windows or macOS is not received until the user opens the Nextcloud client and navigate to the Activity tab" is fixed by #2666 

To make the OS notification appear immediately, without having to open the app's tray window, we need to implement push notifications first. Those are not on the roadmap at the moment.

Please, create a separate issue about that.

Here is a small workaround I offer until we got the push notifications implemented.

You just need to add a property into a config file of your Nextcloud client desktop app.
Kindly find the file named **nextcloud.cfg** in your **AppData** folder (for Windows it is in C:\Users\<YOUR_USER_NAME>\AppData\Roaming\Nextcloud).

Add the following snippet one-line **before** the [Accounts] section:

[Nextcloud]
notificationRefreshInterval=60000

This will allow a notification query to run every 1 minute (it's the lowest value possible).

Be advised, this may increase the load on your server depending on how many desktop clients will have this option changed and how many clients are online simultaneously.

Otherwise, you may as well disregard this setting, and just open the tray manually until we implement push notifications.
