### ISSUE TITLE
Implement support for sharing in File Provider VFS files

### ISSUE THREAD

**Issue by claucambra** [nextcloud/desktop#6197] opened 2023-11-05 13:29 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you want to have the same feature implemented.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Feature description
Virtual files in the File Provider system should support sharing just like their traditional sync engine counterparts

**Comment by tobiasKaminsky** [comment] 2024-01-09 06:28
Duplicate of https://github.com/nextcloud/desktop/issues/6200

**Closed by tobiasKaminsky** 2024-01-09 06:28 UTC
Labels: enhancement, os: :apple: macOS, feature: :minidisc: virtual filesystem
