### ISSUE TITLE
Some files with special characters in file names do not sync

### ISSUE THREAD

**Issue by jernst** [nextcloud/desktop#2014] opened 2020-05-24 21:21 UTC
### Expected behaviour
File sync!

### Actual behaviour
Affected files are shown with a red X in the Finder, and not sync'd.

### Steps to reproduce
* Create a file with an unsupported character in the file name.
* Easiest: vcf files created by Apple Address Book, which sometimes have those characters in it -- perhaps from a business card scanning program. This is how I came across it. But given than Apple supports those files, Nextcloud should.
* Example file names:
  * ``Foo Bar\;PH.D..vcf``
  * ``Foo Bar\, MS.vcf``
  * ``American express\ntravelers checks.vcf``

### Client configuration
Client version: 2.6.1stable

Operating system:
macOS

### Server configuration
UBOS Linux (not that it should matter)

**Comment by warnerbryce** [comment] 2020-06-06 06:42
It’s normal. 
Nextcloud sync files for Linux / Windows / OS X and every OS have it’s folder and files restrictions. 
You can’t put a / or \ in a folder name in Windows. 
The nextcloud sync client will halt and throw error when it detect this kind of name in file or folder.

**Comment by jernst** [comment] 2020-06-07 03:26
Of course mapping would be required. Just like for so many other situations, like Windows file names on DOS filesystems, or colons on MacOS before OSX, or cygwin, or OSX Finder view vs filesystem view etc. This is not a new problem and IMHO Nextcloud should solve it similarly to how it has been solved before in other contexts.

**Comment by er-vin** [comment] 2020-08-11 05:49
Duplicate of #464 it seems

**Closed** 2020-08-11 05:51 UTC
