### ISSUE TITLE
[Bug]: Migration to new config fails

### ISSUE THREAD

**Issue by simonschaufi** [nextcloud/desktop#6905] opened 2024-07-11 12:50 UTC
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

When running the App Image in Ubuntu in Terminal, I get the following error output:

```bash
./Nextcloud-3.13.2-x86_64.AppImage 
nextcloud.gui.application: Migrating old config from "/home/simon/.local/share/Nextcloud" to "/home/simon/.config/Nextcloud"
nextcloud.gui.application: Failed to move the old config directory to its new location ( "/home/simon/.local/share/Nextcloud" to "/home/simon/.config/Nextcloud" )
nextcloud.gui.application: Will move the individual files ("Nextcloud_sync.log")
nextcloud.gui.application: Fallback move of  "Nextcloud_sync.log" also failed
```

### Steps to reproduce

1. Run `chmod +x Nextcloud-3.13.2-x86_64.AppImage`
2. Run `./Nextcloud-3.13.2-x86_64.AppImage`

### Expected behavior

Migration works and no error output

### Which files are affected by this bug

Nextcloud-3.13.2-x86_64.AppImage

### Operating system

Linux

### Which version of the operating system you are running.

Ubuntu

### Package

Appimage

### Nextcloud Server version

does not matter

### Nextcloud Desktop Client version

3.13.2

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 3.4.2 to 3.4.4)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by simonschaufi** [comment] 2024-07-11 13:45
The config is under `/home/simon/.config/Nextcloud` but the logs are still written to `/home/simon/.local/share/Nextcloud` which is strange. That's why I don't understand that it still tries to migrate the config which is not there.

> What version are you upgrading from?

I was upgrading from 3.12.6

**Comment by PhilippSchlesinger** [comment] 2024-07-19 09:07
This seems to be a duplicate of older issues regarding the same problem: https://github.com/nextcloud/desktop/issues/6791 and https://github.com/nextcloud/desktop/issues/6201
Nextcloud developers have commented in those issues and they already contain deeper insight.

**Comment by joshtrichards** [comment] 2024-08-14 21:21
Duplicate of #6201

**Closed by joshtrichards** 2024-08-14 21:21 UTC
