### ISSUE TITLE
Activity tray and activity list design improvements

### ISSUE THREAD

**Issue by criwe** [nextcloud/desktop#889] opened 2018-11-24 15:27 UTC
### Expected behaviour

Activity tray should show when file is synced

### Actual behaviour

Activity tray of the desktop keeps showing "syncing", see picture:

![sync](https://user-images.githubusercontent.com/7531138/48969841-e8bc7380-f004-11e8-9852-f3587ad27b1c.jpg)

I´ve checked it on the server, the file was already there

### Steps to reproduce
1. Change a file / create a news file
2. Start the desktop client
3. watch the activity

### Client configuration
Client version: 2.5.0

Operating system: Win7

OS language: German

Qt version used by client package (Linux only, see also Settings dialog): n/a

Client package (From Nextcloud or distro) (Linux only): n/a

Installation path of client: C:\Program Files (x86)\Nextcloud

### Server configuration

Operating system: don´t know, shared hosting

Web server:  don´t know, shared hosting

Database: MySQL 5.6.19

PHP version: 7.2.11

Nextcloud version: 14.0.4

Storage backend (external storage): n/a

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

1. Client logfile: Output of `nextcloud --logwindow` or `nextcloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the Nextcloud directory)
(See also https://docs.nextcloud.com/desktop/2.3/troubleshooting.html#log-files)

2. Web server error log:

3. Server logfile: nextcloud log (data/nextcloud.log):

**Comment by camilasan** [comment] 2018-11-27 13:19
Hi! Activities that represent a file that got synced show the syncing icon. From your screenshot and description what you see is the correct expected behavior.

**Comment by jancborchardt** [comment] 2018-11-27 14:47
@criwe could you post a full screenshot of the surroundings of where this is displayed? :) If it’s a dialog, ideally the full dialog, so I can check where it is. Thanks!

**Comment by criwe** [comment] 2018-11-27 21:44
@jancborchardt sure!

![unbenannt - 1](https://user-images.githubusercontent.com/7531138/49113361-a9588600-f295-11e8-8a69-097e23d83e3e.jpg)

Hope it gets clearer now. In the 2.3.3 there was an difference between "is syncing" and "is snyced", in 2.5 its not. I´ve added an expample how it would expect the behavior.

**Comment by jancborchardt** [comment] 2018-11-27 21:50
Right, totally agree. If it's synced successfully, we should use the green checkmark icon. The blue circular arrows are only if something is to be synced or currently syncing.

**Comment by camilasan** [comment] 2018-11-29 14:44
Feedback from the Telegram group about the new Activities list: "It would be great to get the activity split back - also, an option to override the warnings for things like symlinks in win, lin, osx.. It is confusing, as on the one hand, all the folders with integration are green, but the overall status is yellow - same for conflicts. If there are conflicts, i'd expect the folder (and all up to the root) would show yellow, so it is easier to find the culprits.  Also: The Links in question were hidden and system, so they should be completely ignored by the client, in my opinion (better: Make it an option *grin*"

"did nc client (win) 2.5 drop the server activity etc windows?? and unresolved conflicts.. cool. then, the activity window has 500 entries about files on the ignore list...?! - this is not an improvement, IMHO. I am confused, and I am the IT support..."

**Comment by vitaliis** [comment] 2018-12-01 14:31
> Warnings for symlinks should be grouped into only one row. Symbolic links are not supported in syncing: keeporsweep.py, nextcloud-update.sh, and 3 others. Alternatively, symlinks on macOS and Linux should just be synced. #605 

Normally you don't have tons of files in the root of the folder and have folders with subfolders.
I suppose the full path (at least from the sync root) should be displayed. Not only the file name. File with path per line would make it easier to read and would make it easier to scan through all files from the same folder as they will be aligned by the same length of the folder name.

**Comment by jancborchardt** [comment] 2018-12-02 14:45
@vitaliis since the symlinks are not synced anyway, showing all of them is not really the point. It's important to let people know that it doesn't happen, but we don't need to list them all in detail.

**Comment by pjotrek-b** [comment] 2019-01-22 19:47
I stumbled over this thread, because symlink and ignored-files cause my nextcloud client to seem like it's never working: always the warning symbol.

I also think this is issue is related to #965 ?

**Comment by christianlupus** [comment] 2019-02-20 10:12
> - Warnings for symlinks should be grouped into only one row. `Symbolic links are not supported in syncing: keeporsweep.py, nextcloud-update.sh, and 3 others`. Alternatively, symlinks on macOS and Linux should just be synced. #605
>  - Warnings for ignored files should not even be there? Because they are ignored, they should be ignored everywhere. (At most, again just one row: `Files not synced because of ignore list rules: ._DS_Store, .gitblasomething, and 200 more`)
> 
> 
> How does that sound? Also, can they post screenshots of how the dialog looks so we can productively move forward? ;)

I  would remark in this case that it would be nice, if the user can click on the condensed row of a warning type to get a new window/dialog that states verbosely what files caused problems to check/track them down.

**Comment by chaos-prevails** [comment] 2019-02-27 15:24
Hello,
I think it would be easier to get an overview of the sync activity if the "time of sync" information is in a separate column (=standard excel "one cell = 1 bit of information" grid), not below the corresponding filename. 

![nextcloud-desktop2 5_activity](https://user-images.githubusercontent.com/17159225/53501010-c165be80-3aab-11e9-9330-caed066245b5.jpg)

**Comment by jancborchardt** [comment] 2019-03-12 09:18
@chaos-prevails that is how it was before and it was very difficult to get an overview. Now you have all the crucial info on the left.

We need to additionally improve the display of the file name by separating it from the folder path:

> Synced **New document.odt** (in My Documents 🢒 Important 🢒 Testing)
> 5 minutes ago

That way all the important info is on the left, easily scannable. Details and actions are on the right.

**Comment by Mannshoch** [comment] 2019-04-03 13:56
May add a compare tool for sync conflict files.

![grafik](https://user-images.githubusercontent.com/7795891/55484541-f2945a00-5628-11e9-87b7-91a3133cf6ac.png)

**Comment by jancborchardt** [comment] 2019-04-18 11:53
@Mannshoch could I ask you to open a seprate issue for that as it’s a different topic? :) It’s a good proposal and could benefit from slightly simplified design – maybe take a look at the conflict dialog on the server. Thank you!

**Comment by koying** [comment] 2019-04-22 10:04
Coming from #872 as requested, but I really think conflicts identification should be prioritized over more "generic" UI improvements.
I mean, having conflicts in a nextcloud should be addressed *immediately*, and it's just not possible to find 1 or 2 conflicts in an ocean of warnings regarding ignored files, currently. 

Pretty, pretty please, just add a checkbox allowing to *not* display warnings about hidden/ignored files. Thanks :)

**Comment by jancborchardt** [comment] 2019-04-22 20:23
@koying conflicts and errors should show at the very top in any of the activity view, so that is taken care of. Warnings and ignored files are less important, hence sorted below. (And again, multiple ignored/hidden files should be collapsed into one entry.)

**Comment by jancborchardt** [comment] 2019-08-15 08:36
Btw @camilasan @misch7 this is kind of a precursor to **Improved tray menu #877** as the activity list would be integrated in there too and needs to be made less noisy before as per my comment above at https://github.com/nextcloud/desktop/issues/889#issuecomment-443032646

> - Warnings for symlinks should be grouped into only one row. `Symbolic links are not supported in syncing: keeporsweep.py, nextcloud-update.sh, and 3 others`. Alternatively, symlinks on macOS and Linux should just be synced. #605 
> - Warnings for ignored files should not even be there? Because they are ignored, they should be ignored everywhere. (At most, again just one row: `Files not synced because of ignore list rules: ._DS_Store, .gitblasomething, and 200 more`)

**Comment by koying** [comment] 2019-09-28 10:00
I was so hopeful this would have been addressed in 2.6.0 😢

**Comment by misch7** [comment] 2019-09-29 12:50
We also would have liked to have it already but login issues and bugs sadly had to be addressed with priority.

This is the next nice thing to have in our 2.7 release [hoping]. We also have more fun implementing new features ^^ 😅😊

**Comment by er-vin** [comment] 2020-06-11 09:52
This GUI doesn't exist anymore since the new systray window was introduced.

**Closed by er-vin** 2020-06-11 09:52 UTC
Labels: 1. to develop, design, enhancement
