### ISSUE TITLE
[Bug]: nextcloud desktop mess up with my files: weird suffix show up when syncing

### ISSUE THREAD

**Issue by binary-husky** [nextcloud/desktop#5507] opened 2023-03-09 07:39 UTC
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

Sometimes weird suffix show up, 
shouldn't nextcloud be in read only mode when uploading/syncing ??

...
![image](https://user-images.githubusercontent.com/96192199/223951790-96a34fd6-4f44-47e6-afe2-b021f2c2e75b.png)

### Steps to reproduce

1. Open vscode to edit files handled by nextcloud desktop
2. Edit it and save it
3. Sometimes weird suffix show up
...

### Expected behavior

When clicking on the share dialog, share by e-mail should be an option.
...

### Which files are affected by this bug

.tex, .py

### Operating system

Windows

### Which version of the operating system you are running.

win10

### Package

Appimage

### Nextcloud Server version

23.0

### Nextcloud Desktop Client version

3.5.0

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 3.4.2 to 3.4.4)

### Are you using the Nextcloud Server Encryption module?

Encryption is Enabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by anonbergine** [comment] 2023-03-10 15:07
I had this issue today for first time, didn't realise it was nc until I saw this issue.

For me it was editing a .js file, using MS VS Code, in a nc managed folder. Suddenly there were red `null` markers at the very end of the file.

I wonder if it might have something to do with https://github.com/nextcloud/desktop/pull/5474 ?

**Comment by binary-husky** [comment] 2023-03-11 07:18
I'm constantly running into this problem for several months,
it happens almost once / twice a day.

And I cannot even understand what nc is doing, 
considering this file is only edited by myself and only edited on a single machine, 
nc should have never asked for the file write privilage on this machine,
because all it has to do is read and upload in this case

**Comment by joshtrichards** [comment] 2024-08-16 15:47
Duplicate of #5165

**Closed** 2024-08-16 15:47 UTC
Labels: 0. Needs triage
