### ISSUE TITLE
Nextcloud Desktop offline files option

### ISSUE THREAD

**Issue by axheli** [nextcloud/desktop#2645] opened 2020-11-16 21:28 UTC
I know nextcloud is doing something with dokan and that you access it via a shared drive but it would be really nice to have it integrated in the nextcloud app just like OneDrive, Google Drive, Dropbox have it. Please see below image and is this something nextcloud can do? I got alot of feedback from some of my clients and they would prefer the offline files option better. 

![image](https://user-images.githubusercontent.com/59488153/99310145-3056ee00-2820-11eb-8ba0-228df29b4e71.png)

**Comment by johkoenig** [comment] 2020-11-26 23:10
Using Windows cloud files API could solve this, see #2637

**Comment by er-vin** [comment] 2020-11-30 11:25
Thus closing as duplicate of #2637

**Closed by er-vin** 2020-11-30 11:25 UTC
