### ISSUE TITLE
Unable to grant access to users with spaces in username (Windows 10, Linux, macOS clients)

### ISSUE THREAD

**Issue by KBlixt** [nextcloud/desktop#1018] opened 2019-01-14 07:43 UTC
so yeah, I'm unable to grant access to my server from my windows 10 machine because I have a space in my user name. I get prmpted to log in after pointing to my server and log in works well but then When I should click "grant access" the loading wheel just spins for ever... logging in to any account without a space in the user name works as expected.

am I missing something or is this a bug?

I'm running the latest mariadb/nexcloud docker releases on an Ubuntu 18.04 machine and trying to access it from the latest windows 10 client. I don't think that anything that I've configured on my server should affect this since I can login to my server from my android client as well as the browser client.

I'm watching the log table while the loading wheel spins and the only thing that appear there are two failed login attempts at approximately 30 seconds intervals after pressing the "grant access" button.  (although I think the 30 seconds intervals is a result of that my ip address have failed too many log in attempts.)

don't know how to troubleshoot this any further.

**Comment by victorbw** [comment] 2019-01-17 08:41
unfortunatley the reference was not the same error.

nonetheless, I can confirm this error happens on recently upgraded NC 15.0.2 and can reproduce it.

@rullzer if you need some credentials let me know.

**Comment by rullzer** [comment] 2019-01-17 08:56
Yes please :smile:

**Comment by victorbw** [comment] 2019-01-17 09:31
@rullzer meet me here: https://insinova.cloud-hosting.ch/index.php/call/epn244ix

**Comment by KBlixt** [comment] 2019-01-18 06:32
I  can also provide login credentials but not sure where to give them to you.

**Comment by rullzer** [comment] 2019-01-18 07:54
@KBlixt always good to have more to test. Could you send them to `roeland` @ `nextcloud.com`

**Comment by KBlixt** [comment] 2019-01-18 13:03
I sent two logins, one with spaces in the username that isn't working and one without space which works.

**Comment by Wikinaut** [comment] 2019-02-17 20:25
Hello Team, we (users and admins with a legal(!) space character in their user names) urgently need a fix for this issue - it is not limited to the Windows10 desktop clients, but also to Linux clients.

**Comment by AndyScherzinger** [comment] 2019-02-19 11:18
@rullzer could you reproduce this issue with a user name containing a space?

**Comment by Wikinaut** [comment] 2019-02-20 18:54
I tested with a second instance, same issue. Desktop people, wake up and fix this regression please.

**Comment by Wikinaut** [comment] 2019-02-26 13:53
@AndyScherzinger I don't see any progress to fix this apparent regression.

**Comment by rullzer** [comment] 2019-02-26 14:25
Did you test the latest rc https://download.nextcloud.com/desktop/prereleases/Windows/Nextcloud-2.5.2.5117-rc1-20190205.exe ?

This should be fixed in the RC. At least I have been unable to trigger it.

**Comment by Wikinaut** [comment] 2019-02-26 22:20
@rullzer No: I use Nextcloud Desktop on Debian and LinuxMint.

**Comment by Tom31100** [comment] 2019-02-27 16:12
Waiting for a fix, you can use OWNcloud client. It's working for the space in login names. I don't know for the space in filenames

**Comment by victorbw** [comment] 2019-02-28 10:25
> 
> 
> Did you test the latest rc https://download.nextcloud.com/desktop/prereleases/Windows/Nextcloud-2.5.2.5117-rc1-20190205.exe ?
> 
> This should be fixed in the RC. At least I have been unable to trigger it.

@rullzer works fine now, also with folders which have whitespace in its name.

Environment:

- W7x64 Professional
- Desktop Client 2.5.2.5117-rc1-20190205
- NC 15.0.4

![grafik](https://user-images.githubusercontent.com/8447071/53559808-494ed580-3b4b-11e9-9b81-49fda815c302.png)

**Comment by Wikinaut** [comment] 2019-02-28 10:41
I need the debian and ubuntu versions.

**Comment by victorbw** [comment] 2019-02-28 12:26
@rullzer just got a message that MacOSx Clients are affected as well.

**Comment by victorbw** [comment] 2019-02-28 12:58
> 
> 
> I need the debian and ubuntu versions.

there you go: https://download.nextcloud.com/desktop/prereleases/Linux/Nextcloud-2.5.2.20190205-rc1-x86_64.AppImage

**Comment by Wikinaut** [comment] 2019-03-02 19:15
@victorbw I do not use Appimages on my machines.

**Comment by Wikinaut** [comment] 2019-03-05 19:01
It seems to be fixed by https://github.com/nextcloud/desktop/commit/5ebee92991248a4f982f2af7e79c31e917cc6816

**Comment by camilasan** [comment] 2019-03-05 20:05
Shall I close this ticket then?

**Comment by Wikinaut** [comment] 2019-03-06 00:13
This issue is not solved for users of the current release 2.5.1, I don't know your policy regarding "closing" issues (I suggest to leave it open until the 2.5.2 is released).

**Comment by victorbw** [comment] 2019-04-05 13:48
> 
> 
> This issue is not solved for users of the current release 2.5.1, I don't know your policy regarding "closing" issues (I suggest to leave it open until the 2.5.2 is released).

According to the repo, 2.5.2 is out: https://download.nextcloud.com/desktop/releases/Windows/Nextcloud-2.5.2-setup.exe

Ive tested the new release under Windows 7 environment, and the issue seems to be fixed in this version.

**Comment by jancborchardt** [comment] 2019-10-27 18:59
Thanks a lot for confirming @victorbw, closing hence. :)

**Closed by jancborchardt** 2019-10-27 18:59 UTC
Labels: bug, high, os: :apple: macOS, os: :door: Windows, os: :penguin: Linux, regression
