### ISSUE TITLE
[Bug]: Folder status not running properly on Mac OS - not available for sharing via desktop app

### ISSUE THREAD

**Issue by davidpremero** [nextcloud/desktop#6082] opened 2023-09-21 13:31 UTC
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

The share dialog is looking incomplete.
...
On my local file structure, the files and folders have a status sign, blue when sincronizing, green when ready to be shared.
The problem is that those status icons are not available anymore.
Then I just can share files/folders by accessing via web.

### Steps to reproduce

1. Right click on the file
2. Click on Share Options
3. The share dialog does not display the option to share by e-mail
...

### Expected behavior

When clicking on the share dialog, share by e-mail should be an option.
...

### Which files are affected by this bug

BATAVO folder is an example.

### Operating system

Mac OS

### Which version of the operating system you are running.

Mac OS Ventura 13.5.2

### Package

Appimage

### Nextcloud Server version

3.10.0 Mac OS

### Nextcloud Desktop Client version

3.10.0 Mac OS

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Enabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by claucambra** [comment] 2024-11-26 05:21
Closing as a duplicate of #5193 thank you for reporting!

**Closed by claucambra** 2024-11-26 05:21 UTC
Labels: 0. Needs triage, os: :apple: macOS, feature: 🐚 shell integration
