### ISSUE TITLE
3.0.3 fails running clean update on windows 10

### ISSUE THREAD

**Issue by pstimpel** [nextcloud/desktop#2626] opened 2020-11-11 17:24 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour
When I run an update, I expect several things.

A.) a kind of smooth transition from version old to version new
B.) no hassle

### Actual behaviour

Since you promote Version 3 of the desktop client, no single update runs hassle free. The update from 3.0.2 to 3.0.3 caused again problems, this time the uninstallation did not run, and the install of the shell extensions did not proceed.

The uninstallation was triggered, but was not executed. It told "another one runs already", in German. Therefore I do not have the exact English message. I was restarting the computer, same issue. So I removed the old one from the control center of my windows installation, and restarted the machine again. The installer was able not able to finish when I enable shell extensions installation. It was trying to replace QTfiles. I wonder, why they still exist after uninstall AND reboot. So, the installation happened finally, without the shell extensions. 

### Steps to reproduce
1. Install 3.0.2, and try to update once Nextcloud asks you to do so.

### Client configuration
Client version: 3.0.3

Operating system: Win 10

OS language: German

Installation path of client: C:\Program Files\Nextcloud

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile: 
No logfiles, since basically, it was a clean installation after I was forced to uninstall first.

### Wishes for the future

Nextcloud was always reliable. Can we go back to this, please? 3.0.x is really a pain in the a** so far. 

BR
Peter

**Comment by er-vin** [comment] 2020-11-12 08:47
@camilasan this is the one you've been looking at right?

**Comment by goldengel** [comment] 2020-11-13 11:56
Workaround:
1. Open Task Manager
2. Close "Explorer" (kill)
3. Try again to install NextCloud
4. Task Manager run process "explorer.exe" > OK

**Comment by pstimpel** [comment] 2020-11-13 12:08
> 
> 
> Workaround 

Call it dirty hack ;) Cheers!

**Comment by alx-tuilmenau** [comment] 2020-11-13 21:07
Got also updates wihile updating to 3.0.3. After the update (without error) I got an Nextcloud Process using a lot of CPU permanently. After reboot, all seems good first. But the client says Version 3.0.2 in the settings panel. Today, I got a message to update to 3.0.3 again. But the setup says "version 3.0.3 already installed". After Deinstallation and re-installation (new downloaded from nextcoud.com)  I got the same with version 3.0.2 in the settings.

**Comment by Czester0** [comment] 2020-11-15 18:58
> Got also updates wihile updating to 3.0.3. After the update (without error) I got an Nextcloud Process using a lot of CPU permanently. After reboot, all seems good first. But the client says Version 3.0.2 in the settings panel. Today, I got a message to update to 3.0.3 again. But the setup says "version 3.0.3 already installed". After Deinstallation and re-installation (new downloaded from nextcoud.com) I got the same with version 3.0.2 in the settings.

exactly the same - total chaos. Alternating with errors:
qt5core.dll or NCOverlays.dll. Randomly as in the lottery.

**Comment by er-vin** [comment] 2020-11-16 11:05
Duplicate of #2606

**Closed by er-vin** 2020-11-16 11:06 UTC
Labels: bug, feature: :inbox_tray: install and update, os: :door: Windows
