### ISSUE TITLE
After upgrade not all sync folders show up

### ISSUE THREAD

**Issue by csware** [nextcloud/desktop#2291] opened 2020-08-19 18:49 UTC
After upgrading to Nextcloud Desktop 3 only one sync folder per account shows up.

It requires one restart of the Nextcloud client for an additional sync folder to show up. It seems as if one one sync folder per account is migrated per start of Nextcloud and not all at once.

### Expected behaviour

All configured syncfolders should be migrated at once.

### Actual behaviour

Only one sync folder per account is migrated.

### Steps to reproduce
1. Configure an account with several sync folders using  Nextcloud client 2.x
2. Upgrade to 3.0.0

### Client configuration
Client version: 3.0.0

Operating system: WIn10

OS language: de

**Comment by er-vin** [comment] 2020-08-19 18:53
Duplicate of #2279 I think. Isn't it?

**Comment by csware** [comment] 2020-08-19 19:54
It also seems as if all configured sync exceptions are lost.

**Comment by er-vin** [comment] 2020-08-20 05:41
> It also seems as if some configured sync exceptions are lost.

From the description of that bug that wouldn't be surprising indeed. Anyway, I'll close this one in favor of #2279.

**Closed by er-vin** 2020-08-20 05:41 UTC
Labels: bug, feature: :arrows_counterclockwise: sync engine
