### ISSUE TITLE
Option to hide shortcuts from Nautilus & other file managers

### ISSUE THREAD

**Issue by MichalLebeda** [nextcloud/desktop#2613] opened 2020-11-04 10:09 UTC
Hi, I have to say that Nextcloud is really amazing but there is a small think that really makes me sad.
IMO there should be an **option to turn these shortcuts off**.
![Screenshot from 2020-11-04 10-16-50](https://user-images.githubusercontent.com/5246963/98097510-6645bb00-1e8d-11eb-95b8-5082c83992a8.png)  
It is really annoying as I have duplicate shortcuts. Otherwise NC integration is really great so I don't want to turn it off completely (even though I can't even do that).

Gnome version: 3.38
Nextcloud version: 3.0.1

**Comment by Id3aFly** [comment] 2020-11-04 10:56
For Windows there is an option in the general settings to enable/disable explorer integration:

**Comment by MichalLebeda** [comment] 2020-11-04 14:06
@Id3aFly The problem is that I really dont't think that turning integration completely off is beneficial. For me it is good to see what is synced and what is not (folder/file badges)

**Comment by 3ernhard** [comment] 2021-04-28 05:23
I would also very much like an option to remove this!
Also a fresh instance of Nautilus automatically starts the nextcloud-client, I don't know if this is intended or not, but I also would really like to disable this.

**Comment by ruffson** [comment] 2021-05-15 18:19
I agree and I find it really annoying that this just forced onto the user without any confirmation. At least this should be opt-in. And honestly, this should be labelled as a bug because not only are there many folders cluttering Nautilus, also opening Nautilus can launch Nextcloud if it is not running. Like it was reported above. This is way too aggressive.
The only way to get rid of it (which I found on reddit) was:

```
sudo rm /usr/share/cloud-providers/com.nextcloudgmbh.Nextcloud.ini 
```
This should not be necessary.

**Comment by loppanloppis** [comment] 2023-03-31 22:14
> I agree and I find it really annoying that this just forced onto the user without any confirmation. At least this should be opt-in. And honestly, this should be labelled as a bug because not only are there many folders cluttering Nautilus, also opening Nautilus can launch Nextcloud if it is not running. Like it was reported above. This is way too aggressive. The only way to get rid of it (which I found on reddit) was:
> 
> ```
> sudo rm /usr/share/cloud-providers/com.nextcloudgmbh.Nextcloud.ini 
> ```
> 
> This should not be necessary.

Wow! Thank you very much @ruffson for sharing the solution you found. Worked fine for me on Gnome 43.4.

I'm a huge Nextcloud fan and I use it for basically everything - couldn't live without it - I know it's free software but seeing shenanigans like this appearing in Nautilus without my consent (and even without a switch to turn it off) was quite a surprise.

Unfortunately each time I do system updates (I'm on Manjaro) these bookmarks come back and I have to run the command above again. And now I realized this ticket is from 2020 so I assume there's no real fix planned anytime soon.

Gotta make sure to bookmark the solution posted by @ruffson :D.

Why is this labeled as a feature request, and not as a bug?

Nextcloud is great nevertheless, keep up the good work.

Cheers Peter

**Comment by phanky5** [comment] 2023-07-09 07:41
It would be great to have this removed.

**Comment by emes81** [comment] 2023-10-10 21:07
> I agree and I find it really annoying that this just forced onto the user without any confirmation. At least this should be opt-in. And honestly, this should be labelled as a bug because not only are there many folders cluttering Nautilus, also opening Nautilus can launch Nextcloud if it is not running. Like it was reported above. This is way too aggressive. The only way to get rid of it (which I found on reddit) was:
> 
> ```
> sudo rm /usr/share/cloud-providers/com.nextcloudgmbh.Nextcloud.ini 
> ```
> 
> This should not be necessary.

This should have been fixed, the issue was flagged two years ago. Unfortunately, this workaround is currently no longer working for me on GNOME 45.0, Arch.

**Comment by MichalLebeda** [comment] 2023-10-13 13:38
@emes81 I labeled it so as the desired state is a setting toggle, not forced or completely disabled feature.

**Comment by cweiske** [comment] 2024-01-21 11:26
Duplicate of #1982.

**Comment by joshtrichards** [comment] 2024-08-14 21:09
Duplicate of #1982

**Closed by joshtrichards** 2024-08-14 21:09 UTC
Labels: enhancement, feature: :gear: settings, feature: 🐚 shell integration
