### ISSUE TITLE
too large tray icon on macOS

### ISSUE THREAD

**Issue by verymilan** [nextcloud/desktop#3549] opened 2021-07-14 14:40 UTC
Hi there, i couldn't find a matching issue and hope that it isn't a duplicate.
On my MacBook 13'' from 2015, the tray icon looks terrible:  

<img width="312" alt="Bildschirmfoto 2021-07-14 um 16 36 46" src="https://user-images.githubusercontent.com/10698140/125641009-54546e43-d075-492b-bde7-043dcee94e09.png">

The behavior seems not to be affected by the dpi setting, which i had assumed first (i run on 1440p mode, but have tried standard to see if something changes).

The MacBook runs on macOS 11.0.1 and with Nextcloud Desktop 3.2.4

**Comment by FlexW** [comment] 2021-07-15 06:50
I don't have a MacBook just a MacMini and it looks fine there. So it will be difficult to fix that. Do you use multiple displays? Is this from the laptop screen?

**Comment by marcoambrosini** [comment] 2021-07-23 07:23
I can reproduce this on a 13,3 M1 macbook air, on the laptop screen. Here's a screenshot
<img width="482" alt="Screenshot 2021-07-23 at 09 20 52" src="https://user-images.githubusercontent.com/26852655/126749664-75fc482c-b2cf-438a-a272-8551d536e543.png">

**Comment by verymilan** [comment] 2021-07-23 07:47
Oh, appears that i cannot reply by mail anymore for some reason... this was my reply:

Hi, this is the laptop screen.. no external displays.
I have now changed the scaling option to 'Standard' and restarted Nextcloud Client - it is still too large. :/

**Comment by marcoambrosini** [comment] 2021-08-20 09:13
Another thing to note is that the icon itself looks a bit wobbly and not pixel-perfect. cc @jancborchardt  & @nimisha-vijay

**Comment by nimisha-vijay** [comment] 2021-08-20 09:59
It looks a bit blurry, no?
Do you think using a png instead of svg causes the issue?

**Comment by marcoambrosini** [comment] 2021-08-20 10:15
> Do you think using a png instead of svg causes the issue?

No, it shouldn't. I think that the problem is that the shape is not properly aligned with the pixel grid. This means it's not pixel-perfect and when you export it, aliasing occurs.
check out https://helpx.adobe.com/fi/illustrator/how-to/pixel-perfect.html

**Comment by mgallien** [comment] 2021-09-06 16:04
> > Do you think using a png instead of svg causes the issue?
> 
> No, it shouldn't. I think that the problem is that the shape is not properly aligned with the pixel grid. This means it's not pixel-perfect and when you export it, anti-aliasing occurs.
> check out https://helpx.adobe.com/fi/illustrator/how-to/pixel-perfect.html

and we might need to do that at different sizes
I guess Breeze icon theme do it also for high DPI icons with a scaling factor of 2

**Comment by elsiehupp** [comment] 2021-09-07 07:17
This is a duplicate of [a much older issue](https://github.com/nextcloud/desktop/issues/2584) and seems to be specifically a bug in the exact version of Qt used for Nextcloud’s CI builds. There is nothing wrong with the icon assets or the application code.

**Comment by elsiehupp** [comment] 2021-09-07 07:26
If you’re curious about the technical details, I actually dug into it a bit, and you can read more about it on the older issue.

macOS in particular uses raster assets for icons, both in the dock and in the “notification area” (the Mac name for the “system tray”), while using vector assets almost everywhere else. The problem is that after Apple increased the height of the menubar in macOS Big Sur, the change broke the code Qt was using to render notification-area icons, so it takes a correctly sized asset and scales it up by a weird fractional amount.

On the other issue, people have mentioned that the bug seems to be fixed in more recent versions of Qt, but upgrading from one version of Qt to the next is labor-intensive, so getting to the point where Nextcloud can use the upstream fix is kind of taking a while.

Anyway, I’m closing this because it’s a duplicate. Feel free to subscribe to updates on the other issue, though!

**Closed by elsiehupp** 2021-09-07 07:26 UTC
Labels: bug, os: :apple: macOS, feature: :cloud: system tray
