### ISSUE TITLE
Connect... button in Connection Wizard stays disabled for non-empty Local Folder

### ISSUE THREAD

**Issue by janvlug** [nextcloud/desktop#1597] opened 2019-11-10 12:17 UTC
### Expected behaviour
When I create a connection through the Connection Wizard, and define a Local Folder that does contain files from a previous ownCloud connection, the Connect... should become active.

### Actual behaviour
The Connect... button is disabled.

![image](https://user-images.githubusercontent.com/5903208/68543825-60251780-03bc-11ea-9f3e-8bf91402d14c.png)

### Steps to reproduce
1. Setup a connection with a ownCloud server.
2. Remove this account from Nextcloud client, but keep the files.
3. Try to create the connection again through the Connection Wizard, and to reuse the Local Folder.

### Client configuration
Client version:
Fedora 2.6.1

Operating system:
Fedora

Client package (From Nextcloud or distro) (Linux only):
nextcloud-client.x86_64    2.6.1-1.fc31

### Server configuration

Nextcloud version:
This is a ownCloud server

**Comment by janvlug** [comment] 2019-11-10 12:38
I saw that there were a few hidden files in the Local Folder:
._sync_xxx.db
._sync_xxx.db-shm
._sync_xxx.db-wal
Because I thought that these files could be the cause of the issue, I moved them away.
I saw that a new ._sync_xxx.db was automatically created again. Maybe this was done because the previous synchronization was somehow still active (I removed the Nextcloud connection in the same login session as where I tried to create it again). Note that I also use the Nautilus Nextcloud plugin (nextcloud-client-nautilus).
I logged out, and logged in again, removed the hidden files, tried to make the connection through the Connection Wizard, and all went well.

So, I think that somehow a Nextcloud connection stays active (in the current login session), even after you remove it from the desktop client GUI.

**Comment by Old-Mother-Hubbard** [comment] 2021-03-10 16:33
This issue still exists with the 3.1.3 Ubuntu client as well.  The workaround of removing the hidden files was only effective after restarting the host.  I was attempting to migrate to a new server hosting NextCloud 21 and was unable to use the original folder even after removing all visible items from it.

**Comment by joshtrichards** [comment] 2024-09-02 13:59
Duplicate of #2457

**Closed** 2024-09-02 14:00 UTC
Labels: bug, feature: :gear: settings, approved, stable-2.6
