### ISSUE TITLE
2 account from one server?

### ISSUE THREAD

**Issue by tabyr** [nextcloud/desktop#1921] opened 2020-04-10 16:48 UTC
Hello. In win desktop app try to add second acount from the same server that have the first acount, but after login it show me folders from first account. How add two accounts from one server ?

**Comment by criwe** [comment] 2020-04-14 08:36
HI!
That works fine for me. I´ve just added the accounts, defined the local folder to sync to. Nothing more todo. You should see the accouts on the top of the client. There you can switch beweet thoses.
Best

**Comment by tabyr** [comment] 2020-04-14 16:20
> HI!
> That works fine for me. I´ve just added the accounts, defined the local folder to sync to. Nothing more todo. You should see the accouts on the top of the client. There you can switch beweet thoses.
> Best

What version you use? Accounts from one cloud server?

**Comment by criwe** [comment] 2020-04-14 18:44
The newest one. yes, from one cloud server

**Comment by FrancoisMz** [comment] 2020-05-18 21:47
Hi!

Same behaviour as tabyr for me, even if not under Windows.
Xubuntu 19.10
Nextcloud client 2.6.4 (the newest one)
2 different Nextcloud accounts on the same Nextcloud server

When you want to add the second account, after entering the url, it does not propose to enter login and password, but instead goes to the web browser to automatically validate the first account (re-using the same token if I correctly understand). If you complete the 2nd account creation, you end up with twice the same account in the Nextcloud client.

**Comment by ChessMaster55** [comment] 2020-06-06 19:28
I can verify that in (Windows) Nextcloud Desktop client version 2.6.4 it does not ask you for login information when you try to add an additional account after you already have one account active.  It assumes you are using the active account credentials, and will even set up another separate account with the old assumed credentials and username. 
The older client(s) worked perfectly, as I had set up and used 2 separate accounts on them previously.

**Comment by FlexW** [comment] 2021-03-17 16:19
You need to logout in your browser before you try to authenticate the client. Then you should be able to add two different accounts from the same server.

Closing because duplicate of https://github.com/nextcloud/desktop/issues/1935

**Closed by FlexW** 2021-03-17 16:19 UTC
