### ISSUE TITLE
Don't recreate desktop shortcut after updates 

### ISSUE THREAD

**Issue by sausje** [nextcloud/desktop#5710] opened 2023-05-18 07:40 UTC
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

If the desktop shortcut is moved to another folder, updating the application causes it to automatically recreate it each time..

### Steps to reproduce

Move desktop shortcut to another folder -> update the application.

### Expected behavior

Updating shouldn't need to recreate the desktop shortcut?? 

### Which files are affected by this bug

desktop shortcut

### Operating system

Windows

### Which version of the operating system you are running.

Windows 11

### Package

Other

### Nextcloud Server version

latest

### Nextcloud Desktop Client version

10.0.22621

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 3.4.2 to 3.4.4)

### Are you using the Nextcloud Server Encryption module?

Encryption is Enabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by joshtrichards** [comment] 2024-08-12 19:38
Duplicate of #3771

**Closed by joshtrichards** 2024-08-12 19:38 UTC
Labels: 0. Needs triage, enhancement, os: :door: Windows, feature: :inbox_tray: install and update
