### ISSUE TITLE
Support for TAG syncing in KDE Plasma 5 / Ubuntu /all other platforms ..

### ISSUE THREAD

**Issue by vbspam** [nextcloud/desktop#257] opened 2018-04-19 18:33 UTC
Support for TAG syncing in KDE Plasma 5 / Ubuntu /all other platforms ..

This is the same report as #71 modified for KDE Plasma (Neon/Ubuntu/...)

As far as I can tell, Nextcloud does not support syncing tags that are added to files in Dolphin/Gwenview/[in geeneral in Plasma/KF5]. I think it would be extremely beneficial to add this to the Nextcloud feature set.

**Steps to reproduce**

1. Install Nextcloud on more than one Neon/Kubuntu with Plasma 5.
2. Add a tag to a synced file.
3. Tag never syncs to other computers.

**Expected behaviour**

The tags should be synced.

**Actual behaviour**

Nothing happens.

**Comment by steynh** [comment] 2018-06-13 11:48
This would be great.

**Comment by MorrisJobke** [comment] 2018-07-19 08:29
Duplicate of #206

**Closed by MorrisJobke** 2018-07-19 08:29 UTC
Labels: feature request
