### ISSUE TITLE
After enabling virtual file support, client aborts: "error writing metadata to database"

### ISSUE THREAD

**Issue by vasyugan** [nextcloud/desktop#3165] opened 2021-04-18 15:26 UTC
### Expected behaviour
After enabling virtual file support, the client should continue functioning.

### Actual behaviour

The client aborts with "error writing metadata to database" each time it ecounters files in a dotted directory (.[dirname])
Only disabling virtual file support again fixes it. Removing and re-adding the folder synchronisation is not enough to fix it.
UPDATE: Not just dotted directories.

### Steps to reproduce
1. Have one or more dotted directories on your server
2. turn on virtual file support for a folder sync
3. wait and see.

### Client configuration
Client version: 3.2.0

Operating system: Windows 10

OS language: German

Installation path of client: C:\Program Files\Nextcloud

### Server configuration

Nextcloud version: 2.0.0.9

Storage backend (external storage):

### Logs

 From the client log:

```
[ debug nextcloud.sync.database.sql ]	[ OCC::SqlQuery::exec ]:	SQL exec "SELECT lastTryEtag, lastTryModtime, retrycount, ```
errorstring, lastTryTime, ignoreDuration, renameTarget, errorCategory, requestId FROM blacklist WHERE path=?1 COLLATE NOCASE"
2021-04-18 17:00:11:961 [ info sync.discovery ]:	Processing "SoundRecords/SoundRecord-2018-06-23-09-38-28.wav" | valid: false/false/true | mtime: 0/0/1529739654 | size: 0/0/12544044 | etag: ""//"db042bb5ac4dddb1603b8a5534044a81" | checksum: ""//"" | perm: 0x7ffa10f9b198//0x255468c93b8 | fileid: ""//"07601023oc7hcigoi6nl" | inode: 0/0/ | type: CSyncEnums::ItemTypeSkip/CSyncEnums::ItemTypeSkip/CSyncEnums::ItemTypeFile | e2ee: false/false | e2eeMangledName: ""/""
2021-04-18 17:00:11:961 [ info sync.discovery ]:	Discovered "SoundRecords/SoundRecord-2018-06-23-09-38-28.wav" CSyncEnums::CSYNC_INSTRUCTION_NEW OCC::SyncFileItem::Down CSyncEnums::ItemTypeFile
2021-04-18 17:00:11:961 [ debug nextcloud.sync.database.sql ]	[ OCC::SqlQuery::bindValue ]:	SQL bind 1 "SoundRecords/SoundRecord-2018-06-23-09-38-28.wav"
2021-04-18 17:00:11:962 [ debug nextcloud.sync.database.sql ]	[ OCC::SqlQuery::exec ]:	SQL exec "SELECT lastTryEtag, lastTryModtime, retrycount, errorstring, lastTryTime, ignoreDuration, renameTarget, errorCategory, requestId FROM blacklist WHERE path=?1 COLLATE NOCASE"
2021-04-18 17:00:11:962 [ info sync.discovery ]:	Processing "SoundRecords/SoundRecord-2018-07-24-15-37-59.wav" | valid: false/false/true | mtime: 0/0/1532465185 | size: 0/0/44602924 | etag: ""//"ffd1a333ec1b3fa1c679103b77800521" | checksum: ""//"" | perm: 0x7ffa10f9b198//0x255468c8d28 | fileid: ""//"07601009oc7hcigoi6nl" | inode: 0/0/ | type: CSyncEnums::ItemTypeSkip/CSyncEnums::ItemTypeSkip/CSyncEnums::ItemTypeFile | e2ee: false/false | e2eeMangledName: ""/""
2021-04-18 17:00:11:962 [ info sync.discovery ]:	Discovered "SoundRecords/SoundRecord-2018-07-24-15-37-59.wav" CSyncEnums::CSYNC_INSTRUCTION_NEW OCC::SyncFileItem::Down CSyncEnums::ItemTypeFile
2021-04-18 17:00:11:962 [ debug nextcloud.sync.database.sql ]	[ OCC::SqlQuery::bindValue ]:	SQL bind 1 "SoundRecords/SoundRecord-2018-07-24-15-37-59.wav"
2021-04-18 17:00:11:962 [ debug nextcloud.sync.database.sql ]	[ OCC::SqlQuery::exec ]:	SQL exec "SELECT lastTryEtag, lastTryModtime, retrycount, errorstring, lastTryTime, ignoreDuration, renameTarget, errorCategory, requestId FROM blacklist WHERE path=?1 COLLATE NOCASE"
2021-04-18 17:00:11:962 [ info sync.discovery ]:	Processing "SoundRecords/SoundRecord-2018-07-24-16-49-01.wav" | valid: false/false/true | mtime: 0/0/1532477093 | size: 0/0/716509740 | etag: ""//"cb22f24fbdbf6ff21e00da4b02e30919" | checksum: ""//"" | perm: 0x7ffa10f9b198//0x255468c9028 | fileid: ""//"07601113oc7hcigoi6nl" | inode: 0/0/ | type: CSyncEnums::ItemTypeSkip/CSyncEnums::ItemTypeSkip/CSyncEnums::ItemTypeFile | e2ee: false/false | e2eeMangledName: ""/""
2021-04-18 17:00:11:962 [ info sync.discovery ]:	Discovered "SoundRecords/SoundRecord-2018-07-24-16-49-01.wav" CSyncEnums::CSYNC_INSTRUCTION_NEW OCC::SyncFileItem::Down CSyncEnums::ItemTypeFile
2021-04-18 17:00:11:962 [ debug nextcloud.sync.database.sql ]	[ OCC::SqlQuery::bindValue ]:	SQL bind 1 "SoundRecords/SoundRecord-2018-07-24-16-49-01.wav"
```

**Comment by Lars1963** [comment] 2021-04-18 15:28
duplicate? of #3158

**Comment by FlexW** [comment] 2021-04-19 07:34
Thanks for the report, but thats a duplicate of https://github.com/nextcloud/desktop/issues/3158

**Closed by FlexW** 2021-04-19 07:34 UTC
