### ISSUE TITLE
No indicator/tray icon at startup using version 3.1.1 on Ubuntu 20.04

### ISSUE THREAD

**Issue by DerXteMensch** [nextcloud/desktop#2772] opened 2020-12-27 08:13 UTC
### Expected behaviour
At startup, the program should be started in the background and an indicator/tray icon (most often the green check icon) should appear.

### Actual behaviour
At startup the "main window" is shown (with the list of data changes and app updates) and no indicator/tray icon appears. If I click somewhere on the screen, this "main window" disappears (the client is still running in the background, but without any visability). I can bring back the "main window" by clicking on the client icon in the Gnome apps list. Only if I close nextcloud via the "main window" or via terminal and start it again, the indicator/tray icon appears (andat that time, the "main window" is not shown).

### Steps to reproduce
1. Update to 3.1.1
2. Restart

### Client configuration
Client version: 3.1.1-20201225.075704.75c329f4f-1.0~focal1 (from the ppa)
(fyi: I also had the in many issues reported problem with version 3.1 that the client didn't start at all due to a Memory access error at start.)

Operating system: Ubuntu 20.04

OS language: German

Qt version used by client package: 5.12.8

Client package (From Nextcloud or distro) (Linux only): From the Nextcloud ppa

Installation path of client: /usr/bin/nextcloud

### Logs

Client logfile: 
I don't know how to have a log file from what happens at startup. If I create a logfile after closing the client and running "nextcloud --logdebug --logfile log.txt", the file is 85.9 MB big and contains lots of sensitive user information. So I didn't upload it here.

**Comment by Daniel219** [comment] 2020-12-27 22:28
Same problem with 3.1.1 and Ubuntu 18.04

**Comment by er-vin** [comment] 2020-12-28 08:42
Feels like a duplicate of #1977

**Closed by er-vin** 2020-12-28 08:42 UTC

**Comment by DerXteMensch** [comment] 2020-12-28 09:31
Actually I don't think it's a duplicate. I've never had any such problems before (neither with version 2.6 nor 3.0), it just began when 3.1.1 was installed (while 3.1 didn't run at all)

**Comment by er-vin** [comment] 2020-12-28 10:09
I beg to differ. The root cause is a race condition so it's kind of "random" or at least tied to other conditions. Might be something else starting faster or slower in your session in some reason to get to it or not have it.

**Comment by DerXteMensch** [comment] 2020-12-28 11:20
And why does the main window appear at startup if it's just about my setup being faster or slower? In 2.6 the main window didn't even exist yet.

**Comment by er-vin** [comment] 2020-12-28 12:24
Ah yeah that it's something else (we got another ticket for that somewhere). It's because somehow it gets started twice during startup. I guess it got registered twice in the startup of your session. During 2.6 times you'd have the settings dialog instead.

**Comment by DerXteMensch** [comment] 2020-12-28 14:50
It was indeed twice in the startup list. However if I remove the second entry, the behaviour unfortunately doesn't change

**Comment by DerXteMensch** [comment] 2020-12-28 15:00
I also removed the second entry. When I turned on the "Start at startup" setting again, there was a new but different entry: ""/usr/bin/nextcloud" --background" instead of just /usr/bin/nextcloud. Now the main window doesn't appear at startup anymore, however the tray icon still doesn't appear at startup... Will wait until this is resolved.

**Comment by rogercreagh** [comment] 2020-12-29 13:31
The absence of any icon on Ubuntu 20.04 may well be related to a recent (just before Christmas) update to the appindicator gnome extension. This may have happened coincident with your update to NC 3.1.1.
Try downgrading appindicator to 33-1
`sudo apt install gnome-shell-extension-appindicator=33-1`
followed by 
`sudo apt-mark hold gnome-shell-extension-appindicator` 
to prevent it being updated again until fixed.
Of course this may reveal the three dots probelm which is possibly due to NC taking too long to get ready...see other issue [1977](https://github.com/nextcloud/desktop/issues/1977)

**Comment by DerXteMensch** [comment] 2021-01-20 17:21
Sorry for my late reply. Downgrading the extension indeed helped.

Is there a ticket at Ubuntu to fix the extension so I don't need to downgrade the extension for the following years?

**Comment by FlexW** [comment] 2021-01-20 22:31
Like stated in the linked issue this should be solved with https://github.com/ubuntu/gnome-shell-extension-appindicator/pull/260
