### ISSUE TITLE
MSI package

### ISSUE THREAD

**Issue by Dennis1993** [nextcloud/desktop#2091] opened 2020-06-13 09:31 UTC
Hello,

where I can find a .msi package to roll out the client for our users?
We are interested in to use nextcloud more and more but we want wo install the latest release automatically. At the moment we update the client if a problem exists or on new clients. For security it would be better to install the latest release by a windows GPO.

Why is no msi published?

**Comment by splitt3r** [comment] 2020-06-13 16:08
I think https://nextcloud.com/blog/branded-nextcloud-clients/ has the information you are looking for.

**Comment by wiswedel** [comment] 2020-09-23 11:49
Duplicate of https://github.com/nextcloud/desktop/issues/59

**Closed by wiswedel** 2020-09-23 11:49 UTC
