### ISSUE TITLE
Client on Ubuntu: timeout while trying to connect to Nextcloud at status.php

### ISSUE THREAD

**Issue by mathiasconradt** [nextcloud/desktop#12] opened 2017-10-12 19:44 UTC
This issue was also noticed by other users in the help forum at https://help.nextcloud.com/t/timeout-while-trying-to-connect-to-nextcloud/7429/5

I run Nextcloud 12 on a raspberry pi in my wifi network, and I can access it via browser just fine. But the **desktop client fails on Ubuntu 17.04 Gnome** with the timeout message seen in the screenshot below.
The client is netxtcloudclient version 2.2.4.5 from Snapcraft

The Nextcloud client on my **Mac OS X** on the other hand **works fine** with the same Nextcloud instance, can connect there without problems, and via the same host name  (raspberrypi2).

![screenshot from 2017-10-12 21-27-08](https://user-images.githubusercontent.com/295122/31515542-ce4fdd62-af95-11e7-95d4-9950774cd9f7.png)

As you can see from the screenshot, the mentioned URL opens just fine in the web browser.

Related, but not exactly identical: https://github.com/nextcloud/client/issues/4

**Comment by mathiasconradt** [comment] 2017-10-12 23:55
Update from my side: I just found that while entering the hostname, in my case “raspberrypi2”, does not work, as shown in my comment above, the IP address (IPv4) instead (in my case 192.168.178.39) works just fine.

When I do a “ping raspberrypi2” from my machine, I get this:

PING raspberrypi2(2003:c1:13cb:4c00:e41d:2f49:2c72:e8a8 (2003:c1:13cb:4c00:e41d:2f49:2c72:e8a8)) 56 data bytes

Maybe it’s a problem with the IPv6 and that it’s resolved like that.

**Comment by camilasan** [comment] 2018-04-26 09:32
Do you still have this problem @mathiasconradt ?

**Comment by rullzer** [comment] 2018-07-02 19:18
@mathiasconradt as far as I remember you used the appimage right?
There was an http2 and ipv6 issue on the old qt version there.

Should be fixed now.
If not please reopen.

**Closed by rullzer** 2018-07-02 19:18 UTC
Labels: needs info

**Comment by NightMachinary** [comment] 2018-12-30 13:40
@rullzer I have this exact problem, too, even with explicit ip. (Things work fine in a browser but the client timeouts. The client is connected with no problems to my other nextcloud on another box. Both nextclouds are installed via snaps.)
I use the latest macOS client:
```
Version 2.5.0daily (build 20181112). For more information please visit nextcloud.com.
This release was supplied by Nextcloud GmbH
Built from Git revision 371001 on Nov 12 2018, 01:03:46 using Qt 5.9.2, OpenSSL 1.0.2m 2 Nov 2017
```

**Comment by Gsam333** [comment] 2023-11-20 06:25
The timeout issue in connecting to Nextcloud on Mac is caused by the network connection configuration, which is set to "Specify proxy manually." To resolve this problem, you simply need to go to the "Proxy Settings" in the "Network" section of the settings and change it to "No Proxy." This will fix the issue and allow you to connect to Nextcloud without any timeout errors.
