### ISSUE TITLE
[Bug]: app main window not showing

### ISSUE THREAD

**Issue by nc82-nc** [nextcloud/desktop#7165] opened 2024-09-19 12:30 UTC
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

Hello,

The main desktop app window is not showing anymore since 3.14, on my deskop and laptop, windows 11. Computers were rebooted after installation.

right click > open main dialog show nothing
clicking on notification shows nothing
clicking on parameters works and opens parameters

So I can't see the syncing process and solve conflicts etc

rolling back to 3.13 => main dialog shows fine again

### Steps to reproduce

Install 3.14, try to access main dialog

### Expected behavior

User should see the main dialog screen

### Which files are affected by this bug

N/A

### Operating system

Windows

### Which version of the operating system you are running.

Windows 11

### Package

Official Windows MSI

### Nextcloud Server version

29.0.5

### Nextcloud Desktop Client version

3.14

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 3.4.2 to 3.4.4)

### Are you using the Nextcloud Server Encryption module?

Encryption is Enabled

### Are you using an external user-backend?

- [X] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Nextcloud Server logs

```shell
saw nothing relevant in server log sorry
```

**Comment by PhilippSchlesinger** [comment] 2024-09-19 13:14
Duplicate of https://github.com/nextcloud/desktop/issues/7156

**Comment by claucambra** [comment] 2024-10-10 04:35
Closing due to duplicate

**Closed by claucambra** 2024-10-10 04:35 UTC
Labels: 0. Needs triage
