### ISSUE TITLE
NextCloud client 3.2.4 macOS dark mode UI glitch (Catalina and/or newer)

### ISSUE THREAD

**Issue by mackonsti** [nextcloud/desktop#3560] opened 2021-07-17 09:46 UTC
### Description

Updated NextCloud client to 3.2.4 on macOS Catalina (latest) and during setup of a new account/connection whilst in dark mode, the window to connect a folder was not legible.

### Expected behaviour

During setup of a new account/connection whilst in dark mode, the window to connect a local folder should be legible and use dark mode colours.

### Actual behaviour

Unfortunately, during setup of a new account/connection whilst in dark mode, the window to connect a local folder was not legible.

### Steps to reproduce

1. Run macOS Catalina (possibly Mojave too and Big Sur) and switch to dark mode.
2. Install NextCloud 3.2.x version and add a new user and a new folder sync (connection)
3. In the folder select window, the text is not legible due to bad palette.

### Client configuration

Client version: NextCloud 3.2.4 (via PKG) for Mac
Operating system: macOS Catalina 10.15.7
OS language: English
Qt version used by client package (Linux only, see also Settings dialog): N/A
Client package (From Nextcloud or distro) (Linux only): N/A
Installation path of client: `/Applications/`

### Server configuration

N/A

### Logs

N/A

### Screenshots

![NextCloud Catalina Dark Mode Local Folder Sync](https://user-images.githubusercontent.com/1313613/126033047-b2e11af6-ae20-4b0f-bde1-3289325a8a7f.png)

Thank you in advance!

**Comment by FlexW** [comment] 2021-07-19 12:00
Duplicate of https://github.com/nextcloud/desktop/issues/3310

**Closed by FlexW** 2021-07-19 12:00 UTC
Labels: bug
