### ISSUE TITLE
Client icon is not shown in Ubuntu 20.04 top right panel

### ISSUE THREAD

**Issue by Digitale-Substanz** [nextcloud/desktop#2783] opened 2020-12-31 09:00 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour
Ubuntu desktop client starts via auto start. When client is running, a specific icon should be displayed in the top right icon panel of Ubuntu / Gnome Shell. The icon should also change according to the synchronization status (check mark or cycling arrows). 

![screenshot-with-nextcloud-icon](https://user-images.githubusercontent.com/8035912/103402883-7c4ebf80-4b4e-11eb-8bba-6560642fce34.png)

### Actual behaviour
No panel icon is displayed, when client is started via systems auto start. However, if client is started manually, the icon is right on place.

![screenshot-icon-panel-no-nextcloud](https://user-images.githubusercontent.com/8035912/103402136-12351b00-4b4c-11eb-8325-5d22939512d5.png)

### Steps to reproduce
1. Have a fresh Ubuntu 20.04.1 installation ready with all updates installed.
2. Add developer's PPA to system according to [this page](https://launchpad.net/~nextcloud-devs/+archive/ubuntu/client)
3. Set 'Run on Startup' option in settings
4. Start system 

### Client configuration
Client version: 3.1.1-20201225.075704.75c329f4f-1.0~focal1

Operating system: Ubuntu 20.04

OS language: German

Qt version used by client package (Linux only, see also Settings dialog): not shown in client settings

Client package (From Nextcloud or distro) (Linux only): from NextCloud PPA

Installation path of client: /usr/bin/nextcloud

### Server configuration

Nextcloud version: 

Storage backend (external storage):

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile: cannot post debug logs here as it reveals the whole structure of my cloud file systems.

Output of `nextcloud --logdebug --logwindow` or `nextcloud --logdebug --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the Nextcloud directory)
(See also https://docs.nextcloud.com/desktop/2.3/troubleshooting.html#log-files)

2. Web server error log:

3. Server logfile: nextcloud log (data/nextcloud.log):

**Comment by janvlug** [comment] 2020-12-31 13:05
I'm using Fedora 33, and I experience this issue as well.
Would it be possible to let Nextcloud client try to show the icon more persistently?
There are several GNOME extensions that show icons (of non GTK/GNOME applications I guess):
- [TopIcons plus](https://extensions.gnome.org/extension/1031/topicons/) (I prefer this one)
- [Top Indicator App](https://extensions.gnome.org/extension/3681/top-indicator-app/)

But for some applications with tray icons the extensions work better than for others. The [Element](https://element.io/) tray icon for example is usually correctly shown, also when GNOME extensions are disabled and enabled again.

Some additional info can be found here:
- [Fix qt based tray icons not appearing on startup](https://github.com/ubuntu/gnome-shell-extension-appindicator/pull/260)
- [Desktop Client - SysTray Icon does not show on Ubuntu 20.10](https://github.com/nextcloud/desktop/issues/2597)
- [App icons tray disappear after update](https://github.com/ubuntu/gnome-shell-extension-appindicator/issues/250)
- [Nextcloud client icon not visible](https://github.com/phocean/TopIcons-plus/issues/154)

**Comment by er-vin** [comment] 2021-01-04 13:56
Duplicate of #1977

**Closed by er-vin** 2021-01-04 13:56 UTC
