### ISSUE TITLE
Moving a dehydrated E2E encrypted file to another folder results in this file removed from both the source and destination folders

### ISSUE THREAD

**Issue by allexzander** [nextcloud/desktop#3379] opened 2021-05-28 08:53 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour
Moving a placeholder file should work as expected, similar to how it works when dealing with non-encrypted destination and hydrated file move.

### Actual behaviour
When moving an E2E encrypted dehydrated file (placeholder) from one folder to another folder, the file gets removed from the destination folder upon finalizing the sync, while it was also removed from the source folder.

### Steps to reproduce
1. Put a file into a local sync folder
2. Move it (either with drag and drop or with Ctrl+X and Ctrl+V) into an encrypted folder
3. The file is removed from the source folder and is also removed from the destination folder when the sync is finished

### Client configuration
Client version:

Operating system:

OS language:

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From Nextcloud or distro) (Linux only):

Installation path of client:

### Server configuration

Nextcloud version:

Storage backend (external storage):

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile: 
Since 3.1: Under the "General" settings, you can click on "Create Debug Archive ..." to pick the location of where the desktop client will export the logs and the database to a zip file.
On previous releases: Via the command line: `nextcloud --logdebug --logwindow` or `nextcloud --logdebug --logfile log.txt`
(See also https://docs.nextcloud.com/desktop/3.0/troubleshooting.html#log-files)

2. Web server error log:

3. Server logfile: nextcloud log (data/nextcloud.log):

**Comment by FlexW** [comment] 2021-06-11 11:18
That's not only related to e2ee. Happens with normal files too.

**Comment by biva** [comment] 2021-06-11 20:12
Thanks @FlexW for having identified that this issue is the same as #3434. 

In order to complete the information about this issue, this happens also when renaming a file: it disappears if the file is in a virtual folder that is _not available locally_.

Did you identify where the issue is? It's a critical issue in our understanding.

**Comment by biva** [comment] 2021-06-11 20:55
I also see that renaming a file, in a virtual folder which is _available locally_, leads to the deletion of the original file (including the previous versions) and the creation of a new file with the new name. Is it related to this issue, or is it related to https://github.com/nextcloud/desktop/pull/3311 ? (my desktop client is 3.2.2)

**Comment by FlexW** [comment] 2021-06-14 07:11
@biva The issue is definitely bad and we will work on fixing that. No, the second issue that you describe is not related to this issue. Could you open a new issue for this, so we can keep the issues focused.

**Comment by biva** [comment] 2021-06-15 07:45
Hi @FlexW thanks, I'll wait to test it when #3311 will be released in the desktop client: if it's not related, I'll open another issue.

**Comment by FlexW** [comment] 2021-06-17 11:55
@biva in fact there I realize now that I was maybe wrong because I misread your message. The issue that you linked is probably related to the pull request you mentioned.

**Comment by biva** [comment] 2021-06-17 13:03
Understood, thanks :) Did you manage to find a solution for this current bug? #3379 ?

**Comment by FlexW** [comment] 2021-06-17 13:30
@FlexW No, I'm currently working on other issues.

**Comment by biva** [comment] 2021-06-17 14:25
OK, I imagine that you have a lot to do. And I'm surprised that Nextcloud in general does not give a higher priority issue because data loss is involved here.

**Comment by biva** [comment] 2021-07-15 21:20
Hey nextcloud team, any news about this critical issue?

**Comment by mgallien** [comment] 2021-07-20 08:05
> Hey nextcloud team, any news about this critical issue?

If this is important for your business, get a [Nextcloud subscription](https://nextcloud.com/pricing/) and we help you fix it in a few hours or days (according to the SLA).
We are trying our best to solve as many github issues as possible but if we spent time answering questions like that we will achieve nothing.

**Comment by biva** [comment] 2021-07-20 08:23
@mgallien Thanks for your answer and I know you do your best. I would not insist if this issue wouldn't be critical in my opinion, not only for us but for all users: a simple and standard action (moving or renaming a file) leads to data loss with this feature that Nextcloud introduced recently. 

Maybe I'm wrong, but I feel a bit of frustration in your answer? I'm sorry to have created that, that was not my intention. This issue is not a specific need from us that we're asking you to develop: this is a relevant bug that can lead to data loss.

Regarding your suggestion to get a Nextcloud subscription, I understand it and I'm sorry to not be able to do it: our organisation is in Africa, and we have absolutely no resources to subscribe to Nextcloud: our best way to contribute to this nice open source project is to report bugs and to help solving them as much as we can.

**Comment by allexzander** [comment] 2021-07-21 11:44
@biva Right now, I suggest you don't use E2EE folders with VFS until we have fixed the issue. You can use 3.2.4 or, even RC1 of 3.3.0 from here https://download.nextcloud.com/desktop/releases/Windows/Nextcloud-3.3.0-rc1-x86_64.msi as it has most of the severe issues with VFS fixed (keep in mind it's a pre-release, so, you may use it only if you think it works better for you, as, official release 3.2.4 is the latest and, is currently recommended).
Other than that, I agree with @mgallien and it is good that you understand that we have a lot of work to do and the priority is always higher for our subscribers.

**Comment by biva** [comment] 2021-07-21 16:09
Thanks @allexzander , but why do you mention encrypted folders? I don't use them: the issue is not related to encryption for me.

Also, don't you think that Nextcloud users should be at least aware of this bad issue? The VFS feature has been publically advertised and this issue makes it, in my opinion, not usable (moving and rename files are not advanced or specific usage, they are basics in file management).

**Comment by allexzander** [comment] 2021-07-21 16:15
Hello @biva. The issue can not be reproduced with non-E2EE files/folders on our end. The one that you are experiencing, is, likely, something different. You need to try the latest version 3.2.4. In 3.2.3 I was able to reproduce this problem. With the latest 3.2.4 - this is no longer the case. VFS in its current state is completely fine. Expect it to evolve and issues fixed as time goes. It's a normal process of gradual improvements. Every software (especially open-source) goes through it. And, as @mgallien mentioned already, issues can be fixed much faster in case you are using support while having an active Nextcloud subscription. Otherwise, expect issues like this one to get fixed sometime later when have time.

**Comment by biva** [comment] 2021-07-21 16:35
Ho, indeed, the issue is solved for me on 3.2.4: it wasn't clear for me, before your last message, that I should test 3.2.4. Congrats and thanks!

**Closed** 2021-08-25 10:36 UTC
Labels: 1. to develop, bug, feature: :lock: end to end encryption, feature: :minidisc: virtual filesystem, approved
