### ISSUE TITLE
[Bug]: Desktop 3.5.1 craches on MacOS HighSierra 10.13.6 

### ISSUE THREAD

**Issue by dgedgedge** [nextcloud/desktop#4593] opened 2022-05-24 06:07 UTC
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

I did upgrade my client to Release 3.5.1 on my Mac.
Result the client did crash.
Clicking on the application gave nothing.
After some investigation I tried something like : 
```
MBP-Denis:\~ denis$ /Applications/nextcloud.app/Contents/MacOS/Nextcloud
2022-05-23 23:48:38.197 Nextcloud[1126:8483] \*\*\* Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '\*\*\* -[\_\_NSPlaceholderArray initWithObjects:count:]: attempt to insert nil object from objects[0]'
\*\*\* First throw call stack:
(
	0   CoreFoundation                      0x00007fff3c9d1f3b \_\_exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x00007fff63d97942 objc\_exception\_throw + 48
	2   CoreFoundation                      0x00007fff3ca11fcc \_CFThrowFormattedException + 194
	3   CoreFoundation                      0x00007fff3c8d220d -[\_\_NSPlaceholderArray initWithObjects:count:] + 237
	4   CoreFoundation                      0x00007fff3c8d9304 +[NSArray arrayWithObjects:count:] + 52
	5   Nextcloud                           0x000000010fe6bb1b \_ZN3OCC30registerNotificationCategoriesERK7QString + 187
	6   Nextcloud                           0x000000010fd3159e \_ZN3OCC7SystrayC2Ev + 430
	7   Nextcloud                           0x000000010fd31055 \_ZN3OCC7SystrayC1Ev + 21
	8   Nextcloud                           0x000000010fd30ff6 \_ZN3OCC7Systray8instanceEv + 54
	9   Nextcloud                           0x000000010fcafe84*\_ZN3OCC11ownCloudGuiC2EPNS\_*11ApplicationE + 244
	10  Nextcloud                           0x000000010fcb2b9d*\_ZN3OCC11ownCloudGuiC1EPNS\_*11ApplicationE + 29
	11  Nextcloud                           0x000000010fbf44d7 \_ZN3OCC11ApplicationC2ERiPPc + 8215
	12  Nextcloud                           0x000000010fbf9dc5 \_ZN3OCC11ApplicationC1ERiPPc + 37
	13  Nextcloud                           0x000000010fb8b3aa main + 682
	14  libdyld.dylib                       0x00007fff649b2015 start + 1
	15  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
Abort trap: 6

```

Here it's not directly the output of the command exactly after the upgrade because I lost it.
It's the output after multiple reinstall and clean of all Nextcloud state files.

After this crash I thought that the crash was due to some special state of my files, so I removed all files linked to netxcloud state by searching in my account => same.
Then I did create a new account => same. 

Included the files generated in ./Library/Logs/DiagnosticReports/.

The first one was generated just after the install while there was still all Nextcloud conf/state files.
The last one after clean of them.

[LogCrash.zip](https://github.com/nextcloud/desktop/files/8759870/LogCrash.zip)

### Steps to reproduce

On a new Account Install the Desktop Client on MacOS HighSierra 10.13.6 .
Lanch the Client => Crash.

### Expected behavior

Ask for Configuration.

### Which files are affected by this bug

Descktop Clien 3.5.1

### Operating system

Mac OS

### Which version of the operating system you are running.

10.13.6 

### Package

Appimage

### Nextcloud Server version

Nextcloud Hub II (23.0.4)

### Nextcloud Desktop Client version

3.5.1

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 3.3.6 to 3.4.0)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Nextcloud Server logs

```shell
See description.
```

### Additional info
Result of the command : /Applications/nextcloud.app/Contents/MacOS/Nextcloud --logdir /tmp/nextcloud_log
[nextcloud.log.zip](https://github.com/nextcloud/desktop/files/8759927/nextcloud.log.zip)

**Comment by claucambra** [comment] 2022-05-24 08:30
Hi, this is a duplicate of #4567 so I will close, but I will post here what I posted in the other thread:

>  I'm sorry to say with 3.5.1 we are bumping up our minimum requirements for macOS to 10.14, as the UserNotification system required for actionable notifications in macOS is unavailable on versions <10.14.
>
> If you need the desktop client and are unable to upgrade your OS, we recommend you stick to version 3.5.0 of the desktop client or lower to retain compatibility. Thanks however for reporting

**Closed by claucambra** 2022-05-24 08:30 UTC
Labels: 0. Needs triage
