### ISSUE TITLE
[Bug]: Client crashes with ENFORCE: "_state != Finished" owncloudpropagator.cpp:227

### ISSUE THREAD

**Issue by marcatsmci** [nextcloud/desktop#5805] opened 2023-06-13 14:46 UTC
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

Trying to start the client : it crashes immediately with this message in log : 
`2023-06-13 16:01:29:021 [ fatal default C:\Users\sysadmin\AppData\Local\Temp\2\windows-16015\client-building\desktop\src\libsync\owncloudpropagator.cpp:227 ]:	ENFORCE: "_state != Finished" in file C:\Users\sysadmin\AppData\Local\Temp\2\windows-16015\client-building\desktop\src\libsync\owncloudpropagator.cpp, line 227
`

Client removed from PC, reboot, reinstall, no way...

[20230613_1601_nextcloud.log.zip](https://github.com/nextcloud/desktop/files/11736006/20230613_1601_nextcloud.log.zip)

### Steps to reproduce

Launch client

### Expected behavior

Client running

### Which files are affected by this bug

NA

### Operating system

Windows

### Which version of the operating system you are running.

Windows 11

### Package

Other

### Nextcloud Server version

26.0.2

### Nextcloud Desktop Client version

3.8.2 (downloaded from nextcloud.com)

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [X] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Additional info

Nextcloud server log : 
[nextcloud.log.gz](https://github.com/nextcloud/desktop/files/11736106/nextcloud.log.gz)

**Comment by marcatsmci** [comment] 2023-06-14 05:15
Same with new client : 3.9.0

**Comment by mgallien** [comment] 2023-09-14 10:07
closing
duplicate of #5473

**Closed by mgallien** 2023-09-14 10:07 UTC
Labels: 0. Needs triage
