### ISSUE TITLE
[Bug]: Right click "copy public link" and "copy internal link" doesn't work

### ISSUE THREAD

**Issue by schiessle** [nextcloud/desktop#5670] opened 2023-05-09 13:43 UTC
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

When I right click on a synced file and select "copy public link" or "copy internal link" in the Nextcloud menu nothing happens. No link is copied to the clipboard and if I open the share dialog afterwards als no public link was created.

### Steps to reproduce

1. Right click on the file
2. click on "copy public link" or "copy internal link"
3. check your clipboard (and for public links the share dialog)
...

### Expected behavior

Links are copied to the clipboard
In case of a public link, the link is created

### Which files are affected by this bug

all

### Operating system

Linux

### Which version of the operating system you are running.

Fedora 38

### Package

Distro package manager

### Nextcloud Server version

26

### Nextcloud Desktop Client version

3.8.1

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 3.4.2 to 3.4.4)

### Are you using the Nextcloud Server Encryption module?

Encryption is Enabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by claucambra** [comment] 2023-05-10 02:09
Hi @schiessle are you running wayland?

**Comment by j-lakeman** [comment] 2023-05-21 08:18
Same on Debian 12 (bookworm) x86_64 GNOME 43.4 under Wayland
Nextcloud Desktop-Client Version 3.7.3 (Debian) debian-6.1.0-9-amd64

Also the sharing options window stay like this forever:


![Bildschirmfoto vom 2023-05-21 10-13-08](https://github.com/nextcloud/desktop/assets/101660243/c6770b55-a35a-47aa-b196-0b5f976cc890)

**Comment by j-lakeman** [comment] 2023-05-21 08:27
Probably duplicate of #5614

**Comment by avatar1024** [comment] 2024-01-31 15:50
> Probably duplicate of #5614

Indeed. Should be marked as a duplicate.

**Comment by joshtrichards** [comment] 2024-08-14 16:13
Duplicate of #5614

**Closed by joshtrichards** 2024-08-14 16:13 UTC
Labels: 0. Needs triage
