### ISSUE TITLE
new tray window (#1565) not showing (in cinnamon)

### ISSUE THREAD

**Issue by brainchild0** [nextcloud/desktop#2085] opened 2020-06-11 10:57 UTC
# Expected behaviour

A single left click on the tray icon  displays the new menu added in #1565.

# Actual behaviour

The click is ignored. Displaying the menu seems to be impossible.

# Steps to reproduce
1. Start application.
2. Click on tray icon.

### Client configuration
- **Client version:** v2.7.0 Tray menu Beta 1
- **Operating system:** Linux Mint 19.3
- **Desktop environment:** Cinnamon 4.4.8
- **OS language:** English
- **Qt version:**    5.12.5
- **Client package:** Official AppImage build (`Nextcloud-2.7.0.20200119-beta1-x86_64.AppImage`)

# Logs

The log file almost entirely represents network activity.

However the following line is recurrent:

```
[unknown 	file:///tmp/.mount_NextclKP3hEp/usr/qml/QtQuick/Controls.2/MenuItem.qml: QML IconImage: Host requires authentication
```

**Comment by veddox** [comment] 2020-06-17 09:16
What desktop environment do you have? Does double-clicking/right-clicking work?

(On Ubuntu, we have a problem with the GNOME AppIndicator plugin, which seems to only allow double-clicks, at least in some cases.)

**Comment by brainchild0** [comment] 2020-06-17 09:25
@veddox: Sorry, I always think of Cinnamon and Mint together, and  forget that Mint is not the desktop environment. I updated the original description to show the version of Cinnamon that I run.  

Double clicking has no effect, like single clicking. Right clicking shows the menu for the *System Tray* panel applet, which is where all the tray icons always appear on a Cinnamon desktop.  This effect for right clicking is consistent with all the other applications in the tray.

**Comment by er-vin** [comment] 2020-06-18 07:31
We did some adjustments there, could you please try again with the latest daily build like that one: https://download.nextcloud.com/desktop/daily/Linux/Nextcloud-2.7.0.20200618-daily-x86_64.AppImage

Just to be 100% sure.

**Comment by brainchild0** [comment] 2020-06-18 08:02
Sorry, but I notice no change.

**Comment by er-vin** [comment] 2020-06-18 09:20
OK, @jancborchardt I think this is the "no context menu" again. I'll likely need to confirm. But please advise if that's confirmed, we're bound to get more such reports for the various environments out there.

**Comment by er-vin** [comment] 2020-06-18 09:22
Ah, one more thing to test please @brainchild0

If you run the application a second time, does the main dialog show up?

**Comment by brainchild0** [comment] 2020-06-18 10:22
The second invocation produces a window and console output shown below (file and user information redacted for privacy). Note that the popup appears in a position relative to the terminal window that ran the second process, and disappears on outside click.  The second process exits immediately, leaving the visible popup.

---

![Screenshot from 2020-06-18 06-15-09](https://user-images.githubusercontent.com/34869175/85008782-6f76fb00-b12b-11ea-9b69-2bf6b533cf5f.png)


```
$ ./Nextcloud-2.7.0.20200618-daily-x86_64.AppImage 
nextcloud.gui.application: Already running, exiting...
[OCC::Systray::computeWindowReferencePoint 	screenRect: QRect(0,0 1920x1080)
[OCC::Systray::computeWindowReferencePoint 	taskbarRect: QRect(0,0 1920x32)
[OCC::Systray::computeWindowReferencePoint 	taskbarScreenEdge: OCC::Systray::TaskBarPosition::Top
[OCC::Systray::computeWindowReferencePoint 	trayIconCenter: QPoint(379,375)
[OCC::Systray::computeWindowPosition 	taskbarScreenEdge: OCC::Systray::TaskBarPosition::Top
[OCC::Systray::computeWindowPosition 	screenRect: QRect(0,0 1920x1080)
[OCC::Systray::computeWindowPosition 	windowRect (reference) QRect(179,36 401x511)
[OCC::Systray::computeWindowPosition 	windowRect (adjusted ) QRect(179,36 401x511)
$ echo $?
```

**Comment by er-vin** [comment] 2020-06-18 11:39
OK, good so there's a way to reach that window by launching the application. It's just that clicking on the icon confusedly does nothing.

**Comment by brainchild0** [comment] 2020-06-18 11:43
In the past, the second invocation caused the display of the *Settings* dialog box. Overall, from a user standpoint, I find this effect more useful, as launching the application from the desktop menu may be more convenient than using the menu in the tray.

**Comment by er-vin** [comment] 2020-06-18 16:20
Well that's because before the only dialog was the settings dialog. In 2.7 we got a main dialog and a settings dialog, we fixed it recently to display the main dialog on second invocation indeed.

**Comment by jancborchardt** [comment] 2020-06-18 23:20
> OK, @jancborchardt I think this is the "no context menu" again. I'll likely need to confirm. But please advise if that's confirmed, we're bound to get more such reports for the various environments out there.

So should I test what happens on my GNOME with that new Appimage you linked – and what to test exactly? I didn’t have issues with the main dialog not opening so far.

@brainchild0 yes, the new expected behavior is that the new main dialog gets opened, no matter how the app is accessed (tray icon click, or app started via programs) to have consistency. It’s a change to the existing way, and that’s because this main dialog is new.

**Comment by brainchild0** [comment] 2020-06-19 00:00
@er-vin: I may not understand your comments fully, because  I'm not sure what you mean by "new main dialog".  To be clear,  for me, if I launch an executable,  I prefer to see a dialog box that has a frame, and that persists until dismissed, rather than to see  a popup that dismisses itself on a click. But anyway, I don't want to go off topic. I'll wait until the functionality is stable.

**Comment by er-vin** [comment] 2020-06-19 10:59
> > OK, @jancborchardt I think this is the "no context menu" again. I'll likely need to confirm. But please advise if that's confirmed, we're bound to get more such reports for the various environments out there.
> 
> So should I test what happens on my GNOME with that new Appimage you linked – and what to test exactly? I didn’t have issues with the main dialog not opening so far.

Not what I meant. I'm just pointing out that if Cinnamon doesn't forward us the left click when no context menu is installed (I suspect there will be other environments like this) we'll get plenty more of those reports saying "I click the icon and nothing happens".

**Comment by brainchild0** [comment] 2020-06-19 12:27
At the risk of intruding with comments that you would find distracting, I would offer a few thoughts.  It  seems, though I may not understand,  that  the desired behavior going forward is that activation of the tray icon cause of window to appear, rather than a menu, but some desktop environments prefer that the tray icon action is limited to the display of a context menu.  In that case, can the contents of the window pane be wrapped in a `QWidgetAction`, which is then passed to `QMenu.addAction()`, the resulting menu then being passed to `QSystemTrayIcon.setContextMenu()`?  Then, would the constraints of the desktop environment be satisfied, with the possibility remaining open to wrap a separate instance of the same top-level `QWidget` in a window, for display from events not related to the tray icon?

**Comment by brainchild0** [comment] 2020-06-19 13:03
Also, though I found the conversation entirely confusing, I discovered from https://github.com/linuxmint/Cinnamon/issues/4946 that the pre-release image *does work as intended* if I disable the Cinnamon option, under *System Settings* / *General*, called *Enable support for indicators*.    That is, a single left-click on the tray icon shows the new-style pop-up without any issues.

---

![Screenshot from 2020-06-19 08-57-32](https://user-images.githubusercontent.com/34869175/85135068-7a08c180-b20b-11ea-9da3-76d4d14a698c.png)

**Comment by brainchild0** [comment] 2020-06-19 13:31
See also the  *System tray* section from the Cinnamon 17.3 [release notes](https://www.linuxmint.com/rel_rosa_cinnamon_whatsnew.php).

**Comment by bastiencyr** [comment] 2022-07-30 23:03
Hello @er-vin , it seems that this issue is back since the last release (3.5.3) :( Can you confirm @brainchild0  ?

**Comment by brainchild0** [comment] 2022-07-31 02:18
I can't test this particular issue at the moment, because the client version you cite prompts for a `kdewallet` password. Running Cinnamon, my passwords are stored in Gnome keyring.

**Comment by bastiencyr** [comment] 2022-07-31 08:24
@brainchild0 actually I have cinnamon too plus Gnome keyring. And I don't have kdewallet... Where did you see that this client version ask for kdewallet password ? Did you experience it ? Maybe it's a bug too.

**Comment by brainchild0** [comment] 2022-07-31 08:29
@bastiencyr, Yes, I assume it is a regression, but I have not reported it nor looked for a report. The prompt was a popup window that appeared at the time of application launch. It seems generally that the application state represents that it is running in a KDE environment, in contrast to earlier versions, that understand that the environment is in the GNOME family. 

I ran the new version from the *Appimage* (`Nextcloud-3.5.3-x86_64.AppImage`). Normally, I run from the Ubuntu repository, which is currently version 3.5.2.

**Comment by bastiencyr** [comment] 2022-07-31 08:46
I run from the ppa : `deb http://ppa.launchpad.net/nextcloud-devs/client/ubuntu focal main`
I think I will reopen a ticket if there is no reaction. I will just wait some days.

**Comment by brainchild0** [comment] 2022-07-31 09:22
My distribution is based on `jammy`, not `focal`.

**Comment by jancborchardt** [comment] 2022-08-03 11:24
Can confirm this issue is back on Ubuntu 20.04 @claucambra @mgallien @ivaradi

**Comment by brainchild0** [comment] 2022-08-03 12:46
There is possibly some confusion over the scope of this issue, as the official Cinnamon distribution runs under Mint, which is based on Ubuntu, but is not actually Ubuntu.

It may be helpful to clarify the earlier question. Perhaps the the idea is to ask about running Cinnamon under Mint 20.3, which is based on 20.04.

Cinnamon directly under Ubuntu may be possible in principle, but I think is not common, and I tend personally to doubt the stability.

**Comment by claucambra** [comment] 2022-08-04 20:38
I suspect the issue here will be the same as it was before -- something needs to be patched to work with Ubuntu's/Mint's antiquated version of Qt.

Will investigate

**Comment by brainchild0** [comment] 2022-08-04 20:45
Does the *antiquated* characterization apply to the Qt version packaged in Ubuntu 22.04 (`jammy`), the new LTS release, or only in the older 20.04 (`focal`)?

**Comment by claucambra** [comment] 2022-08-04 20:47
> Does the _antiquated_ characterization apply to the Qt version packaged in Ubuntu 22.04 (`jammy`), the new LTS release, or only in the older 20.04 (`focal`)?

20.04 only (Qt 5.12).

**Comment by brainchild0** [comment] 2022-08-04 21:06
Especially as Mint 21 has just been released, support for any Ubuntu version preceding 22.04 is not needed. Older versions are not supported, and users should expect that newer software may not work on systems that have not upgraded the operating system.

I am not reproducing this issue with current versions of the operating system and application, and have not reproduced it for some time. The report is over two years old. The issue  probably was resolved for me quite a long time ago, and I simply forgot to report back.

I personally have no reason for this issue to remain open, but I will defer the decision to close to someone else.

**Comment by claucambra** [comment] 2022-08-04 21:17
> Especially as Mint 21 has just been released, support for any Ubuntu version preceding 22.04 is not needed. Older versions are not supported, and users should expect that newer software may not work on systems that have not upgraded the operating system.

Community packagers committed their time to providing this release for 20.04 users, and since we did not disapprove, we intend to support said package as best we can.

> I am not reproducing this issue with current versions of the operating system and application, and have not reproduced it for some time. The report is over two years old. The issue probably was resolved for me quite a long time ago, and I simply forgot to report back.
>
> I personally have no reason for this issue to remain open, but I will defer the decision to close to someone else.

We have to fix the root issue anyway, and it's not as if this issue is _totally_ unrelated -- after all, some users are not having the tray window showing on Cinnamon. This issue has already been reopened so we might as well close it when the issue is resolved

**Comment by ivaradi** [comment] 2022-08-07 06:36
I have updated the stable packages (3.5.4), and the main dialog should now work with Mint 20.03 Cinnamon too.

**Comment by bastiencyr** [comment] 2022-08-08 07:53
Yes it works well now, thank you 😍

**Comment by claucambra** [comment] 2022-08-08 09:07
Thanks @ivaradi for issuing a patch!

Since the issue has been fixed I will close the issue. Thanks all for reporting

**Closed by claucambra** 2022-08-08 09:07 UTC
Labels: bug, approved
