### ISSUE TITLE
Subfolders on Windows client not syncing when added with copy & paste

### ISSUE THREAD

**Issue by madralf** [nextcloud/desktop#4127] opened 2022-01-03 11:20 UTC
It seems that this issue was already reported several times before (e.g. https://github.com/nextcloud/desktop/issues/1000) but was never fixed, although the issues were marked closed.

**Expected behaviour**
After pasting content into the Nextcloud folder on a Windows client PC, it is expected that all content is synchronized to the server.

**Actual behaviour**
All folders seem to sync, however some files in deeper level subfolders don't sync. The folder structure with all subfolders is there but (mostly) empty. It seems like, the deeper the folder structure the higher the chance the files are not synced.

**Steps to reproduce**
Outside of the Nextcloud folder, create a folder structure with several subfolders, at least three levels deep. Add files to every subfolder. Copy the whole folder structure to the Nextcloud folder on a Windows client PC.

**Client configuration**
Version 3.4.1 (Windows)
windows-10.0.19043

**Server configuration**
Nextcloud Hub II (23.0.0)
Operating System:	Linux 5.10.60-qnap x86_64 (Linux LXD Container running on QNAP NAS)
PHP 8.0.14
mysql 10.3.32

Debug archive is attached. **If additional logs are required please advice on where to find them!**
[nc_debug.zip](https://github.com/nextcloud/desktop/files/7801603/nc_debug.zip)

**Comment by claell** [comment] 2022-01-06 18:50
Thanks, @madralf. I have reopened #1000, as it seems to be the oldest issue with this problem, correct? I'll mark this one as a duplicate, then.

**Comment by claell** [comment] 2022-01-06 18:51
Duplicate of #1000

**Closed by claell** 2022-01-06 18:51 UTC
Labels: bug

**Comment by Lars1963** [comment] 2022-01-07 09:46
Same problem here with desktop 3.4.1 (without VFS) and nc 23.0.0
