### ISSUE TITLE
Libraries conflict during last upgrade on KDE Neon (Qt version 5.15.2) and installing Nextcloud-desktop 3.1

### ISSUE THREAD

**Issue by pcapiod** [nextcloud/desktop#2719] opened 2020-12-15 10:23 UTC
### Expected behaviour
Install of the Nextcloud client 3.1 on KDE Neon 5.20.4, Qt version 5.15.2

### Actual behaviour
During the upgrade to the Qt version 5.15.2, some libraries (litqt5core5a and the subsequent qtbase-abi) have been update to 5.15.2. Thus removing qtbase-abi-5-12-8 which is required to run the nextcloud-client.
This is the message I get in my terminal :
```
The following packages have unmet dependencies:
 nextcloud-desktop : Depends: qtbase-abi-5-12-8
                     Recommends: nextcloud-desktop-doc but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

### Steps to reproduce
1. Upgrade to KDE Neon 5.20.4, KDE frameworks 5.77, Qt version 5.15.2
2. Try to install Nextcloud-desktop

### Client configuration
Client version: 3.1 from ppa:nextcloud-devs/client

Operating system: KDE Neon 5.20.4, KDE frameworks 5.77, Qt version 5.15.2

OS language: English

Qt version used by client package (Linux only, see also Settings dialog): Qt version 5.15.2

Client package (From Nextcloud or distro) (Linux only): ppa:nextcloud-devs/client

Hope I sufficiently provided info for this issue. Please let me know if you need more.

**Comment by er-vin** [comment] 2020-12-15 11:22
@ivaradi looks like a duplicate of #2711 or I'm confused?

**Comment by pcapiod** [comment] 2020-12-15 11:33
Indeed it is a duplicate. I did not see that one. Sorry !

**Comment by er-vin** [comment] 2020-12-15 11:51
Alright, no worries. Thanks for reaching out anyway. I'll just close this one then.

**Closed by er-vin** 2020-12-15 11:51 UTC
Labels: bug, package: PPA
