### ISSUE TITLE
Option for Desktop icon on updates

### ISSUE THREAD

**Issue by dsiminiuk** [nextcloud/desktop#3771] opened 2021-09-09 17:29 UTC
For updates that are applied via the General Tab of the desktop client (Windows), running the update places a NextCloud icon on the Windows desktop. Can the update ask if I want a Desktop icon instead of assuming?  I'm pretty tired of deleting it.

**Comment by Bond246** [comment] 2021-09-12 09:44
I would like to ask the same.
Everytime the client gets an update the icon will be placed in administration folder of the desktop. I always have to get admin rights to delete it again. This should be smarter :)

**Comment by mgallien** [comment] 2021-09-13 07:50
@dsiminiuk @Bond246 
I do not expect anybody from the Nextcloud team to have time to work on this soon
do you want to try doing it yourself ?

**Comment by dsiminiuk** [comment] 2021-09-13 17:48
@mgallien
Ha. Ha. Ha.
No idea how to do that. Not a coder, sorry. I'll wait.

**Comment by joshtrichards** [comment] 2024-08-12 19:44
Duplicate of #3248

**Closed by joshtrichards** 2024-08-12 19:44 UTC
Labels: enhancement, good first issue, os: :door: Windows, feature: :inbox_tray: install and update, approved
