### ISSUE TITLE
Wrong system requirements on website for Mac

### ISSUE THREAD

**Issue by User65481** [nextcloud/desktop#4349] opened 2022-03-15 08:41 UTC
Download website for Nextcloud Client Mac says for current version MacOS 10.12+ is required. This should be changed to 10.13+

### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour
PKG installs and you can launch Nextcloud client

### Actual behaviour
Pop-Up shows up, telling users that they need 10.13 or newer.

### Steps to reproduce
1. Download current PKG
2. Install PKG on MacOS 10.12.X
3. Try to launch Client

### Steps to fix
Change system requirements on website from 10.12+ to 10.13+
Optionally: Additional legacy download button for 10.12 besides 10.10 (tested and working for me: 3.0.1)

### Client configuration
Client version: 3.4.3

Operating system: MacOS 10.12.6 (16G2136)

OS language: jp-JP

Installation path of client: /Applications

**Comment by claucambra** [comment] 2022-03-15 09:50
Thanks for reporting, this seems to be a duplicate of #4114 so will close

**Closed by claucambra** 2022-03-15 09:50 UTC
Labels: bug
