### ISSUE TITLE
[Bug]: Nexcloud desktop 3.13.2 crash on surface go 2 windows 11 and external microsd storage

### ISSUE THREAD

**Issue by tigernero79** [nextcloud/desktop#6920] opened 2024-07-15 19:54 UTC
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

after updating from version 3.12.0 to 3.13.2 nextcloud on surface go 2 original windows 11 crashes, in the sense that it starts, and after 2 seconds the app closes, I don't know where to get logs that can help you.

if I put the 3.12.X back everything works again

Greetings

Please how to resolve?

https://github.com/nextcloud-releases/desktop/issues/13#event-13509408034

### Steps to reproduce

this latest version also crashes if at startup the synchronized folders are saved on an external microsd, typical use for a surface go which has an external module for even fast and capacious microsds. with version 3.12.x everything worked so I think it's a regression. can it be solved?

### Expected behavior

not working 
...

### Which files are affected by this bug

All’

### Operating system

Windows

### Which version of the operating system you are running.

Windows 10 e 11

### Package

Appimage

### Nextcloud Server version

29.x

### Nextcloud Desktop Client version

3.13.2

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 3.4.2 to 3.4.4)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by hanneschu1z** [comment] 2024-07-19 11:37
I have the same issue.

**Comment by PhilippSchlesinger** [comment] 2024-07-19 13:39
See https://github.com/nextcloud/desktop/issues/6707

**Comment by hanneschu1z** [comment] 2024-07-20 13:24
I solved the issue by downgrading to Version 3.12.5!

**Comment by tigernero79** [comment] 2024-07-20 14:24
we know that the 3.12.x versions work currently there is 3.12.7 but if you notice it asks for an update to version 3.13.x at every startup. although we post disable update control the latest version has this bug and I hope it will be resolved soon.

**Comment by joshtrichards** [comment] 2024-08-12 20:54
Duplicate of #6707

**Closed by joshtrichards** 2024-08-12 20:54 UTC
Labels: 0. Needs triage
