### ISSUE TITLE
[Bug]: App broken on MacOS Ventura 13.0

### ISSUE THREAD

**Issue by hendrikreimers** [nextcloud/desktop#5091] opened 2022-10-24 19:36 UTC
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

Desktop Client App doesn't start. App is tagged to be broken. Only option is to move it to the trash. No more details available. Reinstalling it doesn't help.

Latest version available and tried to reinstall with the downloadable PKG File from the NC website.

### Steps to reproduce

1. Upgrade to latest MacOS 13.0 Ventura
2. Start the app.

### Expected behavior

Latest Nextcloud client runs under the latest macOS.

### Which files are affected by this bug

Nextcloud Desktop Client (PKG)

### Operating system

Mac OS

### Which version of the operating system you are running.

macOS Ventura 13.0

### Package

Other

### Nextcloud Server version

25.0.0

### Nextcloud Desktop Client version

3.6.1

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Nextcloud Server logs

```shell
---
```

### Additional info

[See alos Nextcloud Support Forum](https://help.nextcloud.com/t/nextcloud-client-for-mac-desktop-doesnt-work-under-macos-ventura/148265)

**Comment by VDRrulez** [comment] 2022-10-24 20:26
Got the same error on my 2017 IMac, but the app works on my M1 Macbook.

**Comment by kusmi** [comment] 2022-10-24 20:33
For me the problem-path was like this:

1. I upgraded to macOS Venture
2. got the error, that app is damaged
3. deleted the nextcloud app from my Applications folder
4. downloaded and installed 3.6.1 again
5. works now!

**Comment by thoto77** [comment] 2022-10-25 06:44
> For me the problem-path was like this (running on an M1 macbook air):
> 
> 1. I upgraded to macOS Venture
> 2. got the error, that app is damaged
> 3. deleted the nextcloud app from my Applications folder
> 4. downloaded and installed 3.6.1 again
> 5. works now!

Could reproduce this on my M1 Air. Works now.

**Comment by artler-tech** [comment] 2022-10-25 09:55
I got the same error on my 2020 iMac (latest Intel). Reinstall doesn't help.

**Comment by git-horst** [comment] 2022-10-25 10:03
> I got the same error on my 2020 iMac (latest Intel). Reinstall doesn't help.

Can confirm, reinstalling does not solve the problem, the installation is ended with an unspecific note of an unsuccessful processing.

MacBook Pro 13", 2018, Intel

**Comment by VDRrulez** [comment] 2022-10-25 10:22
Deleteted the App from Applications Folder
New install
worked

**Comment by boris-bc** [comment] 2022-10-25 11:35
Same problem on MBP 2019. Nextcloud desktop was installed with brew. Reinstall didn't help. Deleting from the application folder and reinstalling from brew fixed the problem. My settings were preserved.

**Comment by terafirmanz** [comment] 2022-10-25 21:00
For me, M1 Macbook air - after the upgrade app opened fine but said it was offline and would not go online. Downloaded the installer and run over the top of the existing install and everything works fine.

**Comment by jensus11** [comment] 2022-10-26 10:00
I updated to Ventura and now i have only the normal sync option, not the virtual folders options. I use a Mac Mini M1. A fresh install didn't help.

**Comment by DazClimax** [comment] 2022-10-27 08:57
Same here MacBook 16" Intel 2018. Delete reinstalled. Still not working. Bugfix soon would be nice.

**Comment by vanilla-user** [comment] 2022-10-27 17:38
I tryed all previous things but nothing works for me. Than I install Nextcloud over brew. Before run it through application folder I run this command line :  /opt/homebrew/bin/nextcloudcmd --user **** --password ****** /Users/ardee/Nextcloud/ cloud.xxx.xxx. It starts to do a lot of things but not sync. After few minutes I lost patience and try to run application. And it starts to work normally! So I cancel commandline and it simply work...

**Comment by terafirmanz** [comment] 2022-10-27 21:08
> For me, M1 Macbook air - after the upgrade app opened fine but said it was offline and would not go online. Downloaded the installer and run over the top of the existing install and everything works fine.
> 
> All using stable 3.6.1 not beta branch.

Have now found out that the app breaks upon sleep and resume of the laptop and since that, a reinstall doesn't fix it. About to try a reboot (not common for me with Mac).

**Comment by martinscott** [comment] 2022-10-29 08:43
I can confirm all of that too. I use a Mac, currently MacOS Monterey (12.5.1), and the Nextcloud client works perfectly for one session with the Mac, also if you continue working after beeing on sleeping modus. But as soon as you shut down the computer, the Nextcloud client no longer opens automatically, and if you try to start it manually, it doesn't open, and instead of, you get an error message. Then I have to reinstall the current software, and then I can open the client. And I have to repeat that all the time.

**Comment by vanilla-user** [comment] 2022-11-02 08:44
It seems to me that version 3.4.4 is working normally! After start it is offline a moment and than work like a charm...

**Comment by phaus** [comment] 2022-11-05 10:39
I did downgrade to Nextcloud-3.5.1 and it does run without issues.
Nextcloud-3.6.1 does start, shows the Icon in the Menu, but I cannot open the UI.

**Comment by claucambra** [comment] 2022-11-07 10:41
Folks, you might want to try fully deleting the desktop client application from your system and then doing a clean install. Your account settings and files should be retained, but it is likely the issue will go away.

You can purge the client by deleting `Nextcloud.app` from your `Applications` folder, as well as deleting `~/Library/ApplicationSupport/Nextcloud`

**Comment by terafirmanz** [comment] 2022-11-07 23:33
After a clean install and then also updating some of my Nextcloud apps to patches released over the last week or so my desktop client now syncs. I'm on the latest version 25 so have had lots of app updates to do over the last few weeks.

**Comment by terafirmanz** [comment] 2022-11-09 07:45
> After a clean install and then also updating some of my Nextcloud apps to patches released over the last week or so my desktop client now syncs. I'm on the latest version 25 so have had lots of app updates to do over the last few weeks.

So that had nothing to do with it. Still broken but I have found that if I keep the settings window open after a few minutes it will connect and sync. While it is failing the settings window does show an error about HTTP 500 PROPEND but that goes once it eventually syncs.

**Comment by effatee** [comment] 2022-11-21 13:10
Hi, simillar issues here. With a difference, no crash, just start and hang.
After a successful upgrade to MacOs Ventura, the NC client has been working flawlessly for two weeks.
Suddenly today, it has stopped working correctly. No sync is possible, NC client re-install does not help.

### Symptoms

- NC client starts normally.
- Within a few seconds, CPU usage of NC client process reaches 100% and is unresponsive.
- MacOs Task manager reports process is not responding.
- The client is not accessible from the GUI for any other troubleshooting (mouse spinning wheel when hover).
- Starting the client from the command line with the `--logwindow` flag does not allow to get any log reports, since the client becomes unresponssive immediately, and no logs are found when exiting.
- Waiting does not help, client remains unresponsive and sollicitating 100% CPU.
- No sync occurs, no contact is made with the NC server.
- Attempts at removing and re-installing the latest client version, brings no improvement, and leads to the same symptoms.
- Other clients from other devices are synching correctly to same NC server instance
- NC Server instance is working perfectly, accepting and treating all requests as usual

### Client version
3.6.2

### Host system version
MacOs 13.0.1

### Server version
25.0.1

Please let me know about any further information I may provide.
Thanks.

**Comment by markus-k** [comment] 2022-11-25 16:08
Same problem here on macOS 13.0.1 with Nextcloud 25. I'm not exactly sure when the problem started.

I tried deleting `~/Library/Preferences/Nextcloud` and then setting it up again. Worked at first, but as it almost completed the resync, the freeze problems started again.

**Comment by effatee** [comment] 2022-11-26 08:53
So from another NC thread, this appears to be related to 
- NC server config.php, bulkupload setting
- NC client, network settings, bandwidth limits

The issue can be solved by
- Setting the NC server bulkupload setting to `'bulkupload.enabled' => false`
- Setting the NC client network settings to 'No Limit'
At least several people have tried it, including myself, and it does solve the client issue.

**Of course this is a workaround to what appears to be a bug.**

Ref:
[https://help.nextcloud.com/t/macos13-1-ventura-ncclient-3-6-2-hang-does-not-respond-no-sync/150338/8](https://help.nextcloud.com/t/macos13-1-ventura-ncclient-3-6-2-hang-does-not-respond-no-sync/150338/8)

**Comment by terafirmanz** [comment] 2022-11-29 07:24
Does anyone else here have the apps "Brute-force settings" or "Suspicious Login" enabled as I am finding sync to be far more reliable when they are turned off. I am still testing to see if it is one of them in particular or if even related to them at all.

**Comment by Basster** [comment] 2022-12-04 21:58
> Setting the NC Client network settings to 'No Limit'

Fixed it for me. Removed `'bulkupload.enabled' => false` from config.php again after changing the network settings and client still runs properly.

**Comment by terafirmanz** [comment] 2023-01-12 21:21
> * 'bulkupload.enabled' => false

The issue spread to all clients on Windows and MacOS for me now and this config change has fixed it for now.

I did notice that the client was showing the PROPFIND error 500 in the settings window every time it tried to sync. If I waited long enough, it would start working.

Only happens on server v25.

**Comment by ZID-TU-Graz** [comment] 2023-01-31 09:36
We noticed that the issue (message "app broken") also occurs when using the auto update mechanism ("nextcloud (autoupdate).app")

![10 08 53](https://user-images.githubusercontent.com/100593683/215722901-9e22567e-567a-4570-87c6-3c7d969d5f12.jpg)

Manually downloading and installing the app was working.

(Currently using NC v24.x)

**Comment by claucambra** [comment] 2023-05-16 03:41
Crash on open issues should be fixed by versions post-3.6.0 and should not occur on 3.8.x 🙂

For hang issues we have merged #5680

**Closed** 2023-05-16 03:40 UTC
Labels: 0. Needs triage
