### ISSUE TITLE
[Bug]: Hard Crash When Digitally Signing Documents

### ISSUE THREAD

**Issue by farhills** [nextcloud/desktop#6020] opened 2023-09-04 19:22 UTC
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

The client silently crashes when applying a digital signature to .pdf files.  This issue is repeatable, and has been ongoing for 6m+.  I've finally enabled debug to capture the issue in the logs.

When digitally signing the file, the software (Bluebeam Revu) appears to create one or more temporary files, `filename.pdf.~3cb1 ` (and similar trailing names .~XXXX).

Not every time, but frequently, the client will crash while signing a PDF.  My guess is these files flash in and out of existence quickly, sometimes leading to an unhandled condition.

Likely related to #5805 but the issue I'm reporting is repeatable, and occurs while the client is running normally; not associated with startup or update.

### Steps to reproduce

1. Open PDF in Revu
2. Apply digital signature
3. Frequently the client will no longer be running (no windows crash report or other indication of the crash given)

### Expected behavior

No crash when signing a PDF

### Which files are affected by this bug

owncloudpropagator.cpp

### Operating system

Windows

### Which version of the operating system you are running.

Windows 10, 22H2

### Package

Appimage

### Nextcloud Server version

27.0.2

### Nextcloud Desktop Client version

3.9.3

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 3.4.2 to 3.4.4)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [X] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Nextcloud Server logs

```shell
2023-09-04 11:17:44:966 [ info nextcloud.sync.propagator C:\Users\sysadmin\AppData\Local\Temp\2\windows-17172\client-building\desktop\src\libsync\owncloudpropagator.cpp:1396 ]:	PropagateDirectory::slotSubJobsFinished emit finished OCC::SyncFileItem::SoftError
2023-09-04 11:17:44:966 [ info nextcloud.sync.propagator.root.directory C:\Users\sysadmin\AppData\Local\Temp\2\windows-17172\client-building\desktop\src\libsync\owncloudpropagator.cpp:1478 ]:	OCC::SyncFileItem::SoftError slotSubJobsFinished OCC::PropagatorJob::Running pending uploads 0 subjobs state OCC::PropagatorJob::Finished
2023-09-04 11:17:44:966 [ info nextcloud.sync.propagator C:\Users\sysadmin\AppData\Local\Temp\2\windows-17172\client-building\desktop\src\libsync\owncloudpropagator.cpp:1494 ]:	PropagateRootDirectory::slotSubJobsFinished emit finished OCC::SyncFileItem::SoftError
2023-09-04 11:17:44:967 [ debug nextcloud.gui.folderwatcher C:\Users\sysadmin\AppData\Local\Temp\2\windows-17172\client-building\desktop\src\gui\folderwatcher_win.cpp:160 ]	[ OCC::WatcherThread::watchChanges ]:	Skipping syncing of "D:/[folder with pdf file]"
2023-09-04 11:17:44:967 [ warning nextcloud.sync.filesystem C:\Users\sysadmin\AppData\Local\Temp\2\windows-17172\client-building\desktop\src\common\filesystembase.cpp:209 ]:	Renaming temp file to final failed:  "WindowsError: 5: Access is denied."
2023-09-04 11:17:44:967 [ warning nextcloud.sync.propagator.download C:\Users\sysadmin\AppData\Local\Temp\2\windows-17172\client-building\desktop\src\libsync\propagatedownload.cpp:1259 ]:	"Rename failed: D:/xxxxx.pdf.~34c6 => D:/xxxxx.pdf"
2023-09-04 11:17:44:967 [ info nextcloud.gui.lockwatcher C:\Users\sysadmin\AppData\Local\Temp\2\windows-17172\client-building\desktop\src\gui\lockwatcher.cpp:37 ]:	Watching for lock of "D:/xxxxx.pdf" being released
2023-09-04 11:17:44:967 [ fatal default C:\Users\sysadmin\AppData\Local\Temp\2\windows-17172\client-building\desktop\src\libsync\owncloudpropagator.cpp:227 ]:	ENFORCE: "_state != Finished" in file C:\Users\sysadmin\AppData\Local\Temp\2\windows-17172\client-building\desktop\src\libsync\owncloudpropagator.cpp, line 227
```

### Additional info

I've kept a full copy of the debug logs, it's too much work to sanitize for public posting.  Will email to the devs if/when they have a chance to look into the issue.

**Comment by mgallien** [comment] 2023-09-07 09:18
@farhills thanks for your report
could you try again with the latest release candidate we just released ?
https://github.com/nextcloud-releases/desktop/releases/tag/v3.10.0-rc2
there is a good chance that my colleagues fixed this bug

**Comment by farhills** [comment] 2023-09-07 15:56
Installed, should be able to report back today.

I assume Version 3.9.82 is correct for 3.10 RC2?

![image](https://github.com/nextcloud/desktop/assets/83388006/abc5a131-77c7-4f12-b12b-826ba7d5883a)

**Comment by farhills** [comment] 2023-09-09 00:34
Update:  No issues yesterday, working well!  Today I signed a document, no crash, but received a sync conflict for the file.  I suspect this is due to something else causing slow synchronization.  The app hasn't crashed yet when signing documents.

CPU has been running hard ever since upgrading to RC2, slow loading of folder contents and occasional errors when trying to open documents (same error as when the nextcloud application isn't running).  I will post some logs in the release issue.

**Comment by mgallien** [comment] 2023-09-14 10:08
closing
duplicate of #5473

**Closed by mgallien** 2023-09-14 10:08 UTC
Labels: 0. Needs triage, os: :door: Windows, crash
