### ISSUE TITLE
[Bug]: Newest Nextcloud windows client makes Windows explorer constantly restart

### ISSUE THREAD

**Issue by jamezsan** [nextcloud/desktop#6576] opened 2024-03-24 15:48 UTC
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

Newest update to the Windows client for Nextcloud has introduced a new issue where Explorer will constantly crash and restart. 
Event viewer in Windows says that ntdll.dll has something to do with it, but the only solution I have found to fix the issue is uninstalling the program, and rebooting.

Reinstalling does not fix the issue.

### Steps to reproduce

1. Install latest version of Nextcloud Windows client
2. Perform any task in File Explorer
3. After a few crashes of Explorer, it becomes more and more unstable.

### Expected behavior

Being able to freely use File Explorer.

### Which files are affected by this bug

explorer.exe, ntdll.dll

### Operating system

Windows

### Which version of the operating system you are running.

Windows 10 Pro Version 10.0.19045 Build 19045

### Package

Appimage

### Nextcloud Server version

28.0.3

### Nextcloud Desktop Client version

3.12.2

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [X] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by PatrickSchmidtSE** [comment] 2024-03-25 07:32
Same, this is bad :(

**Comment by PhilippSchlesinger** [comment] 2024-03-25 11:09
This seems to be a duplicate of https://github.com/nextcloud/desktop/issues/6566

**Comment by joshtrichards** [comment] 2024-03-25 12:32
Duplicate of #6566

**Closed by joshtrichards** 2024-03-25 12:32 UTC
Labels: 0. Needs triage
