### ISSUE TITLE
[Bug]: App keeps uselessly syncing the same files over and over again without stopping

### ISSUE THREAD

**Issue by JustRedTTG** [nextcloud/desktop#5191] opened 2022-11-19 15:12 UTC
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

<img width="444" alt="image" src="https://user-images.githubusercontent.com/46073266/202856051-eee7fb46-d979-4caf-9c3e-e762114e4b76.png">

### Steps to reproduce

Unsure but I think it might have to do with the always keep on device feature
<img width="218" alt="image" src="https://user-images.githubusercontent.com/46073266/202856092-3ae786ce-9c97-482c-aee5-159c811fd43a.png">

### Expected behavior

It shouldn't sync these files, or it should sync them at not sync them again 5 minutes later, these are a lot of files and it puts some minimal but annoying strain when I want to use the service to backup stuff and it also uses pc resources

### Which files are affected by this bug

short named files mostly

### Operating system

Windows

### Which version of the operating system you are running.

Windows 11 latest public release

### Package

Other

### Nextcloud Server version

Nextcloud hub 3 (25.0.1)

### Nextcloud Desktop Client version

3.6.2

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [X] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by anonbergine** [comment] 2023-01-04 08:11
I also run in to this bug, or maybe something similar.

Most commonly there will be newly created files (eg. `notes.txt`) on the local machine which NC should sync up to the server. It does sync them up, but some will show as not synced (despite now being on server) and they'll just reupload over and over and over again forever.

Screenshot of sync status showing same files, again, being synced:

![image](https://user-images.githubusercontent.com/120770250/210511184-ee5a1713-a4fb-4042-9fa1-107c4b512e2f.png)

In File Explorer (Win10) the blue 🔄 icon shows for the files no matter how many times they've been synced. These files are not being changed on server or local, but they keep getting synced over and over.

**Comment by Nirostar** [comment] 2023-01-18 10:49
Probably a duplicate of https://github.com/nextcloud/desktop/issues/4226

**Comment by andyxheli** [comment] 2023-02-07 16:18
Still an issue on 3.7.1

**Comment by joshtrichards** [comment] 2024-08-16 23:45
This may have been addressed in #5474.

The other possibility that comes to mind is something bulk upload related.

Are you still experiencing this behavior?

**Comment by AndyXheli** [comment] 2024-08-17 01:42
Hi @joshtrichards i haven't seen this issue for a while now.

**Closed** 2024-11-08 08:50 UTC
Labels: 0. Needs triage, bug, needs info, feature: :arrows_counterclockwise: sync engine
