### ISSUE TITLE
Desktop Client on openSUSE Linux terminates by signal SIGSEV (Address boundary error)

### ISSUE THREAD

**Issue by Reitmania** [nextcloud/desktop#2752] opened 2020-12-20 19:48 UTC
Hi,

I'm not able to open/use the nextcloud desktop client on openSUSE linux any longer. The application terminates during the starting. I got:

`reiti@guybrush ~> nextcloud`
`fish: “nextcloud” terminated by signal SIGSEGV (Address boundary error)`

The same problem appears using the official appimage. 

Any suggestions? Thx!

**Comment by frncesc** [comment] 2020-12-20 21:58
Same problem on Ubuntu 20.04 with kernel 5.4.0-58-generic.

Versions 3.1.0 of both the [AppImage](https://nextcloud.com/install/#install-clients) and `.deb` files (from the [PPA](https://launchpad.net/~nextcloud-devs/+archive/ubuntu/client))  hang after running for a couple of seconds:

```
$ ./Nextcloud-3.1.0-x86_64.AppImage 
Segmentation fault (core dumped)
```

**Comment by er-vin** [comment] 2020-12-21 06:52
Could we have a backtrace of the crash? Otherwise honestly can't do much about it. I suspect this is a duplicate of #2710 though, so one option is to try out the appimage on #2713 and see if that helps.

**Comment by Reitmania** [comment] 2020-12-21 07:56
The appimage of #2713 works fine, thanks! But currently some kind of a workaround - will this be fixed in the stable of nextcloud-desktop soon?

**Comment by er-vin** [comment] 2020-12-21 08:13
Yes, #2713 will be in 3.1.1. I was wondering if it was the same error or not.

Closing as duplicate of #2710 then.

**Closed by er-vin** 2020-12-21 08:13 UTC
Labels: bug

**Comment by frncesc** [comment] 2020-12-21 17:35
The new appimage works fine also for me. Thank you!
