### ISSUE TITLE
[Bug]: Nextcloud Sync slowdown

### ISSUE THREAD

**Issue by DasCanard** [nextcloud/desktop#6108] opened 2023-09-30 18:56 UTC
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

Opening the client menu from the taskbar causes an extreme drop in download speed (download speed & files per minute).

Unfortunately, there was no large file in the example video, because the download speed drops to a few kb for large files.

Note: I have a 250Mbit connection.

Video: https://youtu.be/mZPiIbHDODs

### Steps to reproduce

1. Have a running sync
2. Switch between Nextcloud settings and the taskbar dashboard
3. see speed decrease

### Expected behavior

Maintain speed

### Which files are affected by this bug

*

### Operating system

Windows

### Which version of the operating system you are running.

Windows 11

### Package

Appimage

### Nextcloud Server version

27.1.0

### Nextcloud Desktop Client version

3.10.0

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [X] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by PhilippSchlesinger** [comment] 2023-10-03 07:22
This is a duplicate of https://github.com/nextcloud/desktop/issues/4918

**Comment by PhilippSchlesinger** [comment] 2024-01-11 08:57
@DasCanard so you may close this bug and maybe add valuable details to #4918.
There is also a possible fix provided in https://github.com/nextcloud/desktop/issues/4918#issuecomment-1637504707 by disabling the syncing icon animation.

**Comment by joshtrichards** [comment] 2024-08-14 16:05
Duplicate of #4918

**Closed by joshtrichards** 2024-08-14 16:05 UTC
Labels: 0. Needs triage, bug, feature: :cloud: system tray, Performance 🚀
