### ISSUE TITLE
Don't show "File/Folder is ignored" in activity

### ISSUE THREAD

**Issue by icewind1991** [nextcloud/desktop#965] opened 2018-12-21 14:04 UTC
Currently when I go to the Activity tab, any useful information is drowned out by a massive list of ignored files.

### Expected behaviour

The activity tab tells me what is being synced/failed to sync

### Actual behaviour
The activity tab is full of ignored message

While the ignored messages can be useful for finding out why a file is not on your server, it shouldn't be grouped with "real" activity messages, especially since the ignored messages seem to be repeated every time the sync runs

**Comment by kevinkk525** [comment] 2018-12-21 17:03
I can put a seconds opinion to that. The makeover of the GUI made it actually useless as you can't filter between activities, downloaded/uploaded files and ignored files. Searching for anything in there is no fun. The old interface was a lot better in that way.

**Comment by JohnWalkerx** [comment] 2018-12-22 22:15
Maybe a filter will be useful. Where you can select which typ of messages are displayed.

**Comment by caugner** [comment] 2019-01-18 07:53
This is especially annoying when you have a message *There are unresolved conflicts. Click for details.* on the main tab that just redirects to the Activity tab and you cannot locate the actual conflict(s).

**Comment by pjotrek-b** [comment] 2019-01-22 19:40
Unfortunately, I have to agree:

I just switched from owncloud to nextcloud and was irritated that the nextcloud systray icon is always the warning symbol. Until I read the activity log, I assumed something was broken :disappointed:

**Comment by christianlupus** [comment] 2019-02-20 10:14
I would really anticipate this feature. When running into problems or even the uncertainty if a certain file is successfully transferred, the current state is a mess as the warnings always to to the top.

**Comment by caugner** [comment] 2019-02-20 10:49
@camilasan Since [those lines](https://github.com/nextcloud/desktop/blob/d1b9d100b420f9b4a8678a899814302025a8371e/src/gui/activitylistmodel.cpp#L105-L109) were last touched by you, do you think it would be hard not to use a warning symbol for `SyncFileItem::FileIgnored`?

**Comment by hanscomps** [comment] 2019-05-16 14:55
I would like to +1 on a feature to at least filter Activity types in the list.
Users are complaining they have sync errors but have to navigate 1000s of ignore files to get to the activity message.

**Comment by pjotrek-b** [comment] 2019-05-17 07:11
@hanscomps True! Same here. Not 1000s, but still needle/haystack-ish :wink:

**Comment by hanscomps** [comment] 2019-05-17 14:14
We literally have 1000s; some CAD tools generate most of them.

**Comment by cweiske** [comment] 2019-05-22 18:07
Duplicate of #566.

**Comment by ftoledo** [comment] 2019-07-17 20:41
PLease add this functionality to hide the "hidden files" messages too.

**Comment by caugner** [comment] 2019-07-24 17:50
With #1347 merged, the next version will make it easier to spot conflicts visually, since all the activities concerning ignored files will appear with a blue info icon rather than the yellow warning icon.

Having said this, a filter function is still desirable.

**Comment by keunes** [comment] 2019-10-13 08:17
Related: #566

**Comment by camilasan** [comment] 2021-02-12 16:17
They show up now (3.1.2) in one message.

**Closed by camilasan** 2021-02-12 16:17 UTC
